### ISSUE TITLE
Corrupt cam.h0.nc file on Edison

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/E3SM#1005]
One of my simulation on Edison [(20160520.A_WCYCL1850.ne30_oEC.edison.alpha6_01)](https://acme-climate.atlassian.net/wiki/display/SIM/20160520.A_WCYCL1850.ne30_oEC.edison.alpha6_01) produced a corrupted cam.h0.nc history file. I have placed a copy of the corrupted file is under

`/project/projectdirs/acme/golaz/misc/20160809`

The corrupted data is located between levels 958 and 889 hPa. It appears that some data was never written to the output file. @polunma has experienced similar problems in the past.

**T at 889 hPa:**

![t_889hpa](https://cloud.githubusercontent.com/assets/15743046/17533723/eca00b1e-5e3a-11e6-8a5f-ffaabf9116a4.png)

**T at 958 hPa:**

![t_958hpa](https://cloud.githubusercontent.com/assets/15743046/17533733/f42c6f12-5e3a-11e6-8b08-46ed142eaf1f.png)

To visualize the data with ncview, I first extracted the temperature field and then regridded it:

```
cd /project/projectdirs/acme/golaz/misc/20160809

# Extract T field
~zender/bin_edison/ncks -v T 20160520.A_WCYCL1850.ne30_oEC.edison.alpha6_01.cam.h0.0100-01.nc T.0100-01.nc

# Remap to la-lon grid
~zender/bin_edison/ncremap -i T.0100-01.nc -m /global/homes/z/zender/data/maps/map_ne30np4_to_fv129x256_aave.20150901.nc -o T.0100-01.129x226.nc

# Visualize with ncview
module load ncview
ncview T.0100-01.129x226.nc &
```

**Comment by ndkeen** [comment]
What should I do about this old issue at this point?

**Comment by singhbalwinder** [comment]
It is probably okay to close it as Edison is gone and we haven't heard about this issue in the past few years.
