### ISSUE TITLE
Negative ci in photosynthesis calculation.

### ISSUE THREAD

**Issue by jinyuntang** [E3SM-Project/E3SM#1233]
The coupling between stomata conductance and photosynthesis occasionally resulted in negative intracellular CO2 concentrations in the current numerical solver. This in the short-term requires a fix for situations when the gs-An formulation does not have a solution.

**Comment by rljacob** [comment]
@bishtgautam is this still an active bug?   Not sure why PR #1272 didn't fix it.

**Comment by bishtgautam** [comment]
#1272 was merged to next and then reverted as [it resulted in unexpected results](https://github.com/E3SM-Project/E3SM/pull/1272#issuecomment-297863842). The CIME update closed the issue as Github or Git misinterpreted the same issue number in e3sm and cime repo.

**Comment by rljacob** [comment]
Ok I see the rest of the conversation now.  There doesn't seem to be a way to remove the "Merged" status from that PR.

**Comment by bishtgautam** [comment]
We can close this issue as negative ci has not been reported in any of the multiple simulations the team has run since 2017.
