### ISSUE TITLE
./case.build --clean-all does not remove Srcfiles and Depends

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/E3SM#1465]
Related to ESMCI/cime#1431

Comments from @mrnorman 

When I added a new file to a source directory used by cam's configure script, I expected it to automatically be seen after I ran ./case.build --clean-all. However, the ./case.build --clean-all script does not remove the Srcfiles and Depends files from the bld/atm/obj directory, and so my compilation failed. Once I manually removed these files, the compilation succeeded. I think it's reasonable to expect ./case.build --clean-all to remove those files since it doesn't take that long to recreate them anyway with a fresh search of the directories. I'd like the --clean-all function to do this (or at least another flag be added that does this).

**Comment by rljacob** [comment]
This was fixed.
