### ISSUE TITLE
I1850CNECACNTBC test crashes in DEBUG mode

### ISSUE THREAD

**Issue by bishtgautam** [E3SM-Project/E3SM#1510]
The ERS_PMx1.f19_g16.I1850CNECACNTBC test runs successfully in non-debug mode,
but crashes in debug mode.

Reported by @ndkeen.

**Comment by ndkeen** [comment]
fwiw, I verified this test is still failing with a more recent master

**Comment by ndkeen** [comment]
I think this is the same as https://github.com/E3SM-Project/E3SM/issues/3786
So close it?

**Comment by bishtgautam** [comment]
The compset doesn't exist any longer. So, won't fix it.
