### ISSUE TITLE
Issue with interaction between Dynamics Init and HOMME

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/E3SM#1593]
My issue is with how dyn_npes interacts with HOMME in setting up the variable "par".  I give a detailed description of my problem below, but in summary my questions are:

1) Based on what I write below, does anyone more familiar with HOMME see the possibility that this problem can break or impact something else down the pipe?

2) Does the way HOMME sets up communication groups for ATM (or the par variable in general) impact the initialization of the other models (i..e LND, CPL, etc.) and if so are there any suggestions on a good way to proceed?

Details:
I've been trying to tackle a bug associated with runs where the maximum number of cores is greater than the total number of elements.  This bug is related to PR #1393 and #1520.

I found that in cases where npes > dyn_npes that the variable "par" created in "components/homme/src/share/parallel_mod.F90", subroutine "initmp" will have different values depending on which processor calls it.  I think it is related to this section of code:

 ```
   call MPI_comm_size(mpicom,npes_cam,ierr)
    if(present(npes_in)) then
       npes_homme=npes_in
    else
       npes_homme=npes_cam
    end if
    call MPI_comm_rank(mpicom,iam_cam,ierr)
    color = iam_cam/npes_homme
    call mpi_comm_split(mpicom, color, iam_cam, par%comm, ierr)
```
which will end up assigning a different "color" to chunks of processors in a modular way.  So for example if

   npes = 48
   dyn_npes = 20 (called npes_in in this subroutine)

then processors 0-19 will have color 0, 20-39 color 1, and 40-47 color 2

This has the effect of setting up 3 communication groups (stored as par%comm) and for the last 8 processors the par%nprocs value will be 8 instead of 20 like it should be.   It also produces the following warning message in the acme logfile:

      initmp:  disagrement accross nodes for nmpi_per_node

I found this bug after I split the dynamics and physics solves onto separate cores.  It causes the initialization of the COUPLER (CPL) to break whenever the number of physics cores is not **an even multiple** of the number of dynamics cores.  It is worth noting that the runs don't break when using the default dynamics/physics coupling.  

I have also been working with @whannah1 on an issue he is running into when using SP with npes>dyn_npes that I think may be related.

**Comment by mt5555** [comment]
let's assume this has been fixed...
