### ISSUE TITLE
CLM setup fails for A_BGCEXP_BCRC_RDCN_2000 compset

### ISSUE THREAD

**Issue by maltrud** [E3SM-Project/E3SM#1831]
it appears that changes to CLMBuildNamelist.pm cause failure when setting up fully coupled BGC.  the failure didn't occur in the development branch.  here is the error message:

ERROR : CLM build-namelist::CLMBuildNamelist::setup_cmdl_methane() : use_lch4 is inconsistent with the commandline setting of -methane
ERROR clm.buildnml: /global/u1/m/maltrud/acme_repo/master_has_BGC_updates_Oct05_2017/components/clm/bld/build-namelist -infile /global/u1/m/maltrud/acme_repo/master_has_BGC_updates_Oct05_2017/A_BGCEXP_BCRC_RDCN_2000_ne30_oEC60to30v3_edison01/Buildconf/clmconf/namelist  -csmdata /project/projectdirs/acme/inputdata -inputdata /global/u1/m/maltrud/acme_repo/master_has_BGC_updates_Oct05_2017/A_BGCEXP_BCRC_RDCN_2000_ne30_oEC60to30v3_edison01/Buildconf/clm.input_data_list -ignore_ic_year -namelist " &clm_inparm  start_ymd=00010101

the error can easily be averted by adding use_lch4 = .true. in user_nl_clm, but the hope is that it would be set automatically (as it apparently was in the development branch) when using create_newcase.

**Comment by bishtgautam** [comment]
The compset doesn't exist in the master, so won't fix it.
