### ISSUE TITLE
Using invalid compset can cause confusion about exact radius of the earth in MPAS-CICE

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#1833]
Using a master as of yesterday. Can try with more recent if this is known?
This is on cori-knl.  Can also try edison to see if this is machine-specific? 
I'm pretty sure I (and others) have run this or something like this not that long ago, so it might be a recent change.

`./create_newcase -case /global/cscratch1/sd/ndk/acme_scratch/cori-knl/A_WCYCL1850S_ne30_oEC60to30v3_cori-knl01 -compset A_WCYCL1850S -res ne30np4_oEC60to30v3 -mach cori-knl`

Fails quickly, so can use debug Q.

```
cori05% cat run/log.cice.0000.err
----------------------------------------------------------------------
Beginning MPAS-cice Error Log File for task       0 of    5120
    Opened at 2017/10/11 14:54:58
----------------------------------------------------------------------

CRITICAL ERROR: rescale_mesh: inconsistent radii: sphere_radius: 6371230.00000000, earthRadius: 6371229.00000000
Logging complete.  Closing file at 2017/10/11 14:54:58
```

casedir:
`/global/cscratch1/sd/ndk/acme_scratch/cori-knl/A_WCYCL1850S_ne30_oEC60to30v3_cori-knl01`

**Comment by jonbob** [comment]
Thanks @jgfouca
