### ISSUE TITLE
Help needed for atm regional history output capability and current status

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#1834]
It is a desirable feature to have the capability of saving history files only for selected columns or regions of interest, particularly for saving high-frequency fields (2D and 3D) during long simulations. It is also part of CFMIP request to save high-frequency data over a handful of sites (columns).

The CAM model has this capability by design, and it has been working well for regular lat-lon based grids (e.g., FV dycore).  It has not been actively discussed if  it works with SE dycore (or how to make it work), partly probably because of inconvenience of post-processing the irregular layout of regional output.

The current V1 beta2 appears to have inherited this regional output capability to some extent, but has major problem remains.

It recognizes column or regional output namelist specifications in the format like

                  fincl3lonlat           = '120e_2n','262e_35n','120e:130e_2n:5n'

which would output fields in fincl3, respectively for the column nearest to (120E, 2N), (262E, 35N), and a rectangular region between 120E-130E and 2N-5N.

The output appears to be sensitive to the size of the record dimension (time) in the netcdf history file. If mfilt=1, namely, one time slice per file, all is good. If mfilt is more than 1, the record dimension size always ends up as "2*mfilt-1", and the values for all fields starting at the 3rd time slice in the file are all "-1". History files still generated at correct internal determined by mfilt, but the same problem exists in all such files.

Helps and hints are much appreciated. (Attn: @gold2718 , @mt5555 ,  @worleyph , @singhbalwinder )

**Comment by rljacob** [comment]
@wlin7 is this capability now working in the lastest master?

**Comment by wlin7** [comment]
Yes, @rljacob. It has been working since PR #1904 merged to the master. I haven't specifically tested this feature in recent masters, though.
