### ISSUE TITLE
PET test with ocn-ice BGC fails

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#1931]
During testing for [MPAS-Dev PR #1455](https://github.com/MPAS-Dev/MPAS/pull/1455), we found that PET tests fail for compsets with active ocn-ice BGC on (GMPAS-OIECO-IAF).

**Comment by rljacob** [comment]
This test started failing when Chrysalis made NTHREADS > 1 in PR #4168

 SMS_Ld2.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.chrysalis_intel.elm-bgcexp
