### ISSUE TITLE
Why does it take so long to rebuild a freshly built executable?

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/E3SM#1959]
Something I never understood...

I check out a fresh copy of the source code and patiently wait for the executable to build. Fine, it's a big code. But then, even if I don't make any changes to the source code, rebuilding the executable a second time around takes forever (6 minutes in the example below).

Isn't this a problem that was supposed to have been solved a long time ago with makefiles?

```
swav built in 0.991562 seconds
sesp built in 1.010070 seconds
sglc built in 1.026794 seconds
Component ice build complete with 4 warnings
mpascice built in 24.721927 seconds
Component ocn build complete with 4 warnings
mosart built in 40.027123 seconds
mpaso built in 40.049233 seconds
Component atm build complete with 1 warnings
cam built in 68.970087 seconds
clm built in 303.398857 seconds
Building acme with output to /global/cscratch1/sd/golaz/ACME_simulations/20171205.beta3rc10_hist.ne30_oECv3_ICG.edison/build/acme.bldlog.171205-151304
Time spent not building: 59.335339 sec
Time spent building: 363.865171 sec
MODEL BUILD HAS FINISHED SUCCESSFULLY
```

**Comment by rljacob** [comment]
Closing.  The long times were mostly because of the perl build which has been mostly replaced.
