### ISSUE TITLE
 SMS_D.ne4_oQU240.A_WCYCL1850S_CMIP6 fails on edison/cori.  `pio_support::pio_die:: myrank=   -1 : ERROR: ionf_mod.F90`

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#2043]
On edison, with and without DEBUG, we get a failure trying to run the ne4 version of this test.  It would be nice to have for debugging. This is on next, but we also see the same error with master of several days ago.

 I also see a failure on cori, but the error is different.  It is an error I've seen before when there is trouble with a netcdf file format. I would need to put print statements in the code to find out which file it is trying to open.  May not be the same error as below.

```
 6:  UrbanInputldomain and input file do not match dims 
 6:  UrbanInputldomain%ni,ni,=          866       48602
 6:  UrbanInputldomain%nj,nj,=            1           1
 6:  UrbanInputldomain%ns,ns,=          866       48602
 6:  ENDRUN:
 6:  ERROR in UrbanParamsType.F90 at line 467                                       
 6:                                                                                 
 6:                                                                                 
 6:                                                                                 
 6:                                                                                 
 6:                                                                                 
 6:                                        
 6:  ERROR: Unknown error submitted to shr_abort_abort.
 6: Image              PC                Routine            Line        Source             
 6: acme.exe           000000001144599D  Unknown               Unknown  Unknown
 6: acme.exe           000000000E7F903F  shr_abort_mod_mp_         114  shr_abort_mod.F90
 6: acme.exe           000000000E7F8EBC  shr_abort_mod_mp_          61  shr_abort_mod.F90
 6: acme.exe           0000000008098E48  abortutils_mp_end          43  abortutils.F90
 6: acme.exe           000000000AB83EC9  urbanparamstype_m         467  UrbanParamsType.F90
 6: acme.exe           00000000080D5500  clm_initializemod         211  clm_initializeMod.F90
 6: acme.exe           00000000080693D8  lnd_comp_mct_mp_l         200  lnd_comp_mct.F90
 6: acme.exe           00000000004532C1  component_mod_mp_         231  component_mod.F90
 6: acme.exe           000000000041C8A1  cime_comp_mod_mp_        1183  cime_comp_mod.F90
 6: acme.exe           0000000000449E2D  MAIN__                     92  cime_driver.F90
```

`/global/cscratch1/sd/ndk/acme_scratch/edison/n30-mjan19/SMS_D.ne4_oQU240.A_WCYCL1850S_CMIP6.edison_intel.20180119_131652_m0zwzm`

**Comment by ndkeen** [comment]
I added manual print statements so that we can see what file it is trying to read. Note that currently the open call (where it fails) is *before* any debug prints that indicate the filename.

The file it is having trouble with is:

```
cori05% ll /project/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc 
-rw-rw-r--+ 1 pjc pjc 271093 Nov  2  2017 /project/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc
cori05% ncdump -k /proect/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc
netCDF-4

And  a file it read OK just before is here:
cori05% ncdump -k /project/projectdirs/acme/inputdata/atm/cam/physprops/poly_rrtmg_c130816.nc
classic
```

**Comment by ndkeen** [comment]
This is also the same error that we see with a near nightly test `SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.cori-knl_intel.allactive-v1cmip6`

In this test, the file that is causing trouble is a different one, but is still same format:

```
cori07% ncdump -k /project/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc
netCDF-4
```

**Comment by ndkeen** [comment]
I can try, but I'm wondering if it makes more sense for the owner of the file to do this? Or at least someone who is more familiar with those data files?

**Comment by rljacob** [comment]
No go ahead and switch the format.  It doesn't alter the content.

**Comment by ndkeen** [comment]
My understanding was that we can't alter files in inputdata in place -- should create a new name, delete the others, etc.

Also, shouldn't the fix be made at the source? That is, the files on the server where these would come from if they were missing?  I haven't verified yet to see if these files are a different format on the new server.

**Comment by rljacob** [comment]
Noel, just switch it temporarily to see if it fixes the problem.  Yes they should all be changed at the source and with new filenames.

**Comment by ndkeen** [comment]
OK, I can try the `nccopy -k 2 input_filename output_filename` command, but then how can I tell my case to then use the new output_filename?

**Comment by rljacob** [comment]
Copy the current file somewhere safe.  Give the new file the same name.

**Comment by ndkeen** [comment]
Hmm, looks like one of the files mentioned above has some other issue and nccopy isn't working:

```
cori03% nccopy -k nc6 /project/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc t.nc
NetCDF: Not a valid data type or _FillValue type mismatch
Location: file nccopy.c; line 788
```

**Comment by jayeshkrishna** [comment]
Try the ncks tool (module load nco) it worked for me,
```
ncks -3 /project/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc t.nc
```

**Comment by ndkeen** [comment]
The ncks command did work for 2 files that were failing to convert with nccopy.  But now I'm seeing a few more that are failing with nccopy and the same trick doesn't work:

```
cori05%  nccopy -k nc6  /project/projectdirs/acme/inputdata/ocn/mpas-o/oRRS18to6v3/oRRS18to6v3.restartFrom_titan0228.170321.nc  t.nc
NetCDF: One or more variable sizes violate format constraints
Location: file nccopy.c; line 1449
1.054u 0.004s 0:01.05 100.0% 0pf+0w
cori05% ncks -6 -O /project/projectdirs/acme/inputdata/ocn/mpas-o/oRRS18to6v3/oRRS18to6v3.restartFrom_titan0228.170321.nc t.nc
ERROR NC_EVARSIZE One or more variable sizes violate format constraints
HINT: NC_EVARSIZE errors occur when attempting to copy or aggregate input files together into an output file that exceeds the per-file capacity of the output file format, and when trying to copy, aggregate, or define individual variables that exceed the per-variable constraints of the output file format. The per-file limit of all netCDF formats is not less than 8 EiB on modern computers, so any NC_EVARSIZE error is almost certainly due to violating a per-variable limit. Relevant limits: netCDF3 NETCDF_CLASSIC format limits fixed variables to sizes smaller than 2^31 B = 2 GiB ~ 2.1 GB, and record variables to that size per record. A single variable may exceed this limit if and only if it is the last defined variable. netCDF3 NETCDF_64BIT_OFFSET format limits fixed variables to sizes smaller than 2^32 B = 4 GiB ~ 4.2 GB, and record variables to that size per record. Any number of variables may reach, though not exceed, this size for fixed variables, or this size per record for record variables. The netCDF3 NETCDF_64BIT_DATA and netCDF4 NETCDF4 formats have no variable size limitations of real-world import. If any variable in your dataset exceeds these limits, alter the output file to a format capacious enough, either netCDF3 classic with 64-bit offsets (with -6 or --64), to PnetCDF/CDF5 with 64-bit data (with -5), or to netCDF4 (with -4). For more details, see http://nco.sf.net/nco.html#fl_fmt
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_enddef()
nco_err_exit(): ERROR Error code is -62. Translation into English with nc_strerror(-62) is "NetCDF: One or more variable sizes violate format constraints"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
1.159u 0.012s 0:01.19 97.4% 0pf+0w
```

**Comment by jonbob** [comment]
@ndkeen - there is an inconsistency between the resolution and compset for this test and I would not expect it to work. The 1850S compset designation refers to using a spun-up initial condition state for ocn/ice, but the resolution should be ne4_oQU240_ICG to match. And I don't believe that even exists, since the ultra-low resolution is specifically for testing. Also, there is no A_WCYCL1850_CMIP6 (missing the "S"), since that compset requires an initial state. So this test is simply not currently supported -- though our scripts should be capable of letting users know that this combination is usable.

**Comment by ndkeen** [comment]
Thanks Jon. I was using this test as I thought I had found the smallest possible test that exhibited an issue (which it does in the sense that it fails on the same file as the other issue referenced). But now that you have indicated this test name is no good, I can close and we can just follow 2413.

Is there a ne4 case that uses CMIP6?

**Comment by jonbob** [comment]
@ndkeen - I don't think we have a current CMIP6 test that could use ne4. I believe all the CMIP tests start from a previous condition, and since ne4-oQU240 is just an ultra-low testing resolution, we don't ever think of spinning up any initial conditions for it. I think if you really wanted to, you could go through the process, but scientifically it would be meaningless and you might get push-back for having CMIP runs on testing resolution that someone might mistake for scientific results. 2143 is certainly a real -- and critical -- configuration to make sure functions correctly.
