### ISSUE TITLE
FATES has trouble with threading tests on some machines

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#2077]
On bebop, cetus and Titan, the ERP test with FATES fails.
ERP_Ld3.f45_f45.ICLM45ED.<machine>-<compiler>.clm-fates

But it passes on other platforms so its probably compiler-related.  Still this points a possible reproducibility issue with FATES for different thread counts.

**Comment by amametjanov** [comment]
Threaded runs are passing with master on Bebop and Theta, both with 1 and 2 threads in the initial run:
* ERP_Ld3.f45_f45.ICLM45ED.theta_intel.clm-fates (Intel 18.0.0 + Cray-Mpich 7.7.10)
* ERP_Ld3.f45_f45.ICLM45ED.bebop_intel.clm-fates (Intel 17.0.4 + Intel-MPI 2017.3)
