### ISSUE TITLE
Error affecting MODIS simulator in COSP

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#2113]
COSP developer notified us of an error in MODIS simulator output affecting COSP versions including the one currently implemented in E3SM V1.

_

> In COSP 1.4 and 1.4.1 and COSP 2.0 all MODIS simulator variables are affected by an error manifest only when clouds with both liquid and ice visible from space. In CESM the impacts are quite small (https://www.esrl.noaa.gov/psd/people/dustin.swales/COSP/v1.4.2/cosp_quicklooksV1.4.2.html).
> 
> In COSP 1.4.1 variables jpdftaureliqmodis and jpdftaureicemodis are further affected by an error in initialization. We expect that when these errors are manifest the data will be nonsensical._
> 

A patch was provided by the developer and has been applied to E3SM via [PR# 2097](https://github.com/ACME-Climate/ACME/pull/2097). 

A pair of 15-month simulations that were performed with and without this fixes ([amwg diagnostics ](http://portal.nersc.gov/project/m2136/V1beta/testing/HadPI.ne30.COSPmodis_1-HadPI.ne30/)show the impact is small.

E3SM COSPLITE test found the following diagnostic quantities are affected.

> CLHMODIS CLIMODIS CLMMODIS CLMODIS CLTMODIS IWPMODIS LWPMODIS PCTMODIS REFFCLIMODIS REFFCLWMODIS TAUILOGMODIS TAUIMODIS TAUTLOGMODIS TAUTMODIS

**Comment by susburrows** [comment]
@rljacob , since the bug fix was merged last year, I am going to close this issue.
