### ISSUE TITLE
Fail compare with ERP_Ld31.ne4_ne4.FC5AV1C-L and ERP_Ld31.ne30_ne30.FC5AV1C-L (cori-knl/edison)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#2176]
This test fails memory leak test, but I'm certainly not sure if it's actually a memory leak yet.

`/global/cscratch1/sd/ndk/acme_scratch/cori-knl/ncsafer/ERP_Lm3.ne4_ne4.FC5AV1C-L.cori-knl_intel.r01`

**Comment by ndkeen** [comment]
With the branch in https://github.com/E3SM-Project/E3SM/pull/2377, I tried again.  
On cori-knl, I see a MEMLEAK fail with intel, and COMPARE fails with gnu (and gnu7).

**Comment by singhbalwinder** [comment]
Thanks @ndkeen for running these tests. It seems like 31 day run fails irrespective of the grid. I will give it a try on our cluster to see if i can reproduce it.

**Comment by singhbalwinder** [comment]
It fails on my end as well. It is quite confusing as *cprnc.out file shows that the history files are different from the two runs (initial and restart) but the atm.log.* files from both runs shows exact same checksum numbers at `nstep, te ` lines. The restart runs started at time step 194 and numbers after `nstep, te ` are exactly the same as the initial run for all time steps. 

My hope was that the runs will start differing after few initial steps and we can go after those to track it down but it looks like a different kind of problem. I am tagging @philrasch, @worleyph and @mt5555 if they have any ideas on how to proceed.

**Comment by rljacob** [comment]
Which fields exactly are different?   Its possible for diagnostic fields to differ while the prognostic state matches between the two runs.

**Comment by singhbalwinder** [comment]
Thanks Rob! I should have checked this earlier, it is the cice history file which is different between the runs. I do not have any experience with cice model but I will see if I can get more info on what might have gone wrong.

**Comment by rljacob** [comment]
Ok.  We usually don't write cice history in the tests that run for a few steps or days.  Those only show up when you run for a month (the default cice output time).   The baseline test will compare all history files that it finds.

**Comment by singhbalwinder** [comment]
That explains why the tests are failing at the month boundary.  The good thing is that the failure is not affecting the atm simulation. We will eventually move to MPAS-CICE for this compset but until then we have to use cice.

**Comment by ndkeen** [comment]
Closing as the 2 tests noted in title are passing with master of Nov 6th.
