### ISSUE TITLE
create_test: single submit option

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#2199]
When I tried the single submit option, it still results in each test submitted as a separate batch job.

`./create_test e3sm_developer --machine summit --compiler $compiler --single-submit -t $mytest -r $mytestdir`

What am I missing?

**Comment by rljacob** [comment]
One job to run all the tests one-at-a-time within that job?

**Comment by sarats** [comment]
Yes

**Comment by jgfouca** [comment]
@rljacob , @sarats , just confirming, you want the dumbed-down single-submit we discussed? IE, sequential running of tests?

**Comment by jgfouca** [comment]
OK, what's the priority on this?

**Comment by sarats** [comment]
@rljacob Just a reminder, this functionality is probably needed for efficient CI testing on Summit.

**Comment by sarats** [comment]
Closure unrelated to this.

**Comment by jgfouca** [comment]
@sarats , are you still wanting this feature? @rljacob mentioned in our telecon that we are not going to be doing CI/nightly testing on Summit.

**Comment by jgfouca** [comment]
Closing unless I hear something from @sarats .
