### ISSUE TITLE
HOMME fails to build with GNU (6.3, 7.3, 8.2) on cori-knl

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#2207]
I thought I already had an open issue about this, but don't see one. I think this has been failing to build for a long time. I recall that something in HOMME's build system is confused about whether we are building with GNU or Intel.  The error in homme.log is that `-mkl` is not recognized.

`/global/cscratch1/sd/ndk/acme_scratch/cori-knl/mfcatm/HOMME_P24.f19_g16_rx1.A.cori-knl_gnu.gnu00`

**Comment by ndkeen** [comment]
Noting this is still the case -- HOMME builds fail with gnu and gnu7 on edison/cori-knl

**Comment by ndkeen** [comment]
We are now using gnu 7.3 as the GNU compiler on cori (https://github.com/E3SM-Project/E3SM/pull/2442) and indeed the HOMME test fails to build.

**Comment by ndkeen** [comment]
This is still failing in same way with a master from Nov 6th, which uses `gcc/8.2.0(default)`.

`HOMME_P24.f19_g16_rx1.A.cori-knl_gnu`

**Comment by ndkeen** [comment]
Trying again with July 7th master (which uses GNU 8.3), I still get a build error.

```
-- CMAKE_Fortran_COMPILER_ID = GNU
-- Performing Test CXX11_SUPPORTED
-- Performing Test CXX11_SUPPORTED - Success
-- Performing Test CXXLIB_SUPPORTED
-- Performing Test CXXLIB_SUPPORTED - Failed
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found OpenMP Flags
-- OpenMP_Fortran_FLAGS: -fopenmp
-- OpenMP_C_FLAGS: -fopenmp
-- OpenMP_CXX_FLAGS: -fopenmp
-- OpenMP_EXE_LINKER_FLAGS: 
--   Using HORIZ_OPENMP
-- Looking for AVX on host... found AVX2.
-- HOMME_USE_MKL=TRUE, adding -mkl
-- Fortran Flags =  -ffree-line-length-none -O3 -g -fopenmp -traceback -craype-verbose -mkl
-- C Flags =  -O2 -g -fopenmp  -mkl
-- CXX Flags =  -std=c++11 -g -std=c++11 -O3 -DNDEBUG -g -fopenmp -mavx2  -mkl
-- Linker Flags =    -mkl
** Configuring SCORPIO with:
-- NetCDF_PATH = /opt/cray/pe/netcdf-hdf5parallel/4.6.3.2/GNU/8.2
-- PnetCDF_PATH = /opt/cray/pe/parallel-netcdf/1.11.1.1/GNU/8.2
-- NetCDF_Fortran_PATH = 
-- NetCDF_C_PATH = 
-- PnetCDF_Fortran_PATH = 
-- PnetCDF_C_PATH = 
-- Fortran compiler does not support c_sizeof function
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
-- Could NOT find MPI_Fortran (missing: MPI_Fortran_LIB_NAMES MPI_Fortran_F77_HEADER_DIR MPI_Fortran_MODULE_DIR MPI_Fortran_WORKS) 
CMake Error at /global/common/sw/cray/cnl7/haswell/cmake/3.14.4/gcc/8.2.0/2hef55n/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND MPI_Fortran_FOUND)
Call Stack (most recent call first):
  /global/common/sw/cray/cnl7/haswell/cmake/3.14.4/gcc/8.2.0/2hef55n/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /global/common/sw/cray/cnl7/haswell/cmake/3.14.4/gcc/8.2.0/2hef55n/share/cmake-3.14/Modules/FindMPI.cmake:1672 (find_package_handle_standard_args)
  utils/externals/scorpio_classic/pio/CMakeLists.txt:38 (find_package)

-- Configuring incomplete, errors occurred!
```

**Comment by oksanaguba** [comment]
That cmake cache file is invalid for gnu, at least for MKL part. It is just a matter of making a proper cache file.

**Comment by ndkeen** [comment]
Still same issue with master of Nov19th

**Comment by mt5555** [comment]
No reason to fix this on cori-knl, but adding some notes for future reference:

The cmake "machinefile" is chosen in e3sm/cime/CIME/cime/CIME/SystemTests/hommebaseclass.py
It currently uses a single machinefile independent of compiler.  In this case, that would be cori-knl.cmake, which only works with intel compilers.  

One possible solution would be to have the HOMME machine file, cori-knl.cmake, detect if we are using gnu or intel, and then have the various settings for both compilers within the same machine file (but historically, HOMME has had a different machine file for each compiler).   

So a better solution might be to create a cori-knl-gnu.cmake machinefile, and have CIME's hommebaseclass.py look for cori-knl-{compiler}.cmake, when the compiler is not the default for that system.   CIME already has logic to add a "-bfb" postfix to the machinefile name, so we can test HOMME with default settings and with bfb settings.

**Comment by mt5555** [comment]
```
cmake_cmd = "cmake -C {0}/components/homme/cmake/machineFiles/{1}{6}.cmake -DUSE_NUM_PROCS={2} {0}/components/homme -DHOMME_\
BASELINE_DIR={3}/{4} -DCPRNC_DIR={5}/..".format(
                srcroot, mach, procs, baselinedir, basename, cprnc, self.cmakesuffix
            )
```

**Comment by ndkeen** [comment]
Closing this old issue
