### ISSUE TITLE
STOP_OPTION and STOP_N ignored when using multinstance 

### ISSUE THREAD

**Issue by jhkennedy** [E3SM-Project/E3SM#2212]
I've been working on adding a (CIME) system test to E3SM which uses the mulitinstance capability (`MVK`).  When I set `STOP_OPTION=ndays` and `STOP_N=400` it does not seem to have an effect -- my jobs have been hitting the wallclock limit after running for ~5 years. 

Importantly, I've tried a couple of different combinations of `STOP_OPTION` and `STOP_N`s, (e.g, `nyears` and `1`), and in *all* cases, it overruns the stop option. However, if I leave `STOP_OPTION` and `STOP_N` at the default (`ndays`, `5`) it does stop as expected. 

~~So far, I've only been running on Titan, so I don't know if this applies to other machines as well.~~ *This is machine independent -- both Cori and Titan exhibit this behavior.* 

*Note, I rebased my branch (`jhkennedy/cime/mvk-test`; a0c2c0455) onto 6274c032e ; the current master and still see this.*

Additionally, @salilmahajan and others in our group have noticed this behavior on titan when running a multiinstance case setup using `create_newcase` as well, so it's not limited to CIME system tests. An example script which sets up a similar multiinstance case outside the system test structure can be found here: `/ccs/home/kennedy/ACME/salil-miltii/run_multiFC5_ne4.csh`

---

This is how I created my latest run which has been overrunning `STOP_N` on titan:

```bash
# once logged into titan
module load python
export CHARGE_ACCOUNT=cli106ice
cd /ccs/home/kennedy/ACME/ACME/cime/scripts
./create_test MVK.ne4_oQU240.FC5 -p cli106 --baseline-root "/ccs/home/kennedy/acme_scratch/baselines" -g -o
```

Its case directory on titan: 
```
/ccs/home/kennedy/acme_scratch/cli115/MVK.ne4_oQU240.FC5.titan_pgi.G.20180329_114324_j5t7i1
```
Checking the XML:

```
$ ./xmlquery STOP_OPTION,STOP_N

Results in group run_begin_stop_restart
	STOP_OPTION: ndays
	STOP_N: 400
```
---
Finally, note: my branch only makes minor changes to `cime/config/config_tests.xml` and adds system tests. 

```
$ git diff --name-status master
M	cime/config/config_tests.xml
A	cime/scripts/lib/CIME/SystemTests/mvk.py
A	cime/scripts/lib/CIME/SystemTests/slr.py
A	cime/scripts/lib/CIME/SystemTests/src.py
```

**Comment by jhkennedy** [comment]
@jgfouca I've figured out what's going on here. We were setting the `dtime` directly in the multi-instance namelists instead of using `ATM_NCPL` (and the like) which, apparently, screws up the couplers time handling and this is how it manifests.

Closing.

**Comment by jgfouca** [comment]
@jhkennedy , glad you figured it out.
