### ISSUE TITLE
Test Failure: ERP_Ld31.ne4_ne4.FCAV1C.edison_intel fails compare_base_rest

### ISSUE THREAD

**Issue by crjones-amath** [E3SM-Project/E3SM#2263]
Just tried generating baselines for some tests on edison with the current E3SM/master, and ran into a compare_base_rest failure.

commit dbdcbcdb87802fc4a6bf5d8222c425a0df6db577
Merge: c133017ec a95b2079d

Test Location: /global/cscratch1/sd/crjones/acme_scratch/edison/ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel.G.20180406_104456_pe0c8c/

Process:
>> cd ACME
>> git pull
>> git submodule update --init
>> nohup ./create_test -r $REG_HOME/cases/generate/$tstamp -o -g -p $PROJID --baseline-root $REG_HOME/baselines ERP_Ld31.ne4_ne4.FC5AV1C        >&

>> ./cs.status.20180406_104456_pe0c8c
20180406_104456_pe0c8c
  ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel (Overall: FAIL) details:
    PASS ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel CREATE_NEWCASE
    PASS ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel XML
    PASS ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel SETUP
    PASS ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel SHAREDLIB_BUILD time=1575
    PASS ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel NLCOMP
    PASS ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel MODEL_BUILD time=1072
    PASS ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel SUBMIT
    PASS ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel RUN time=1499
    FAIL ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel COMPARE_base_rest
    PASS ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel GENERATE master
    FAIL ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel MEMLEAK memleak detected, memory went from 1710.820000 to 2271.380000 in 29 days

Seems to be differences in the ... cice.h... file: 
>> tail ERP_Ld31.ne4_ne4.FC5AV1C.edison_intel.G.20180406_104456_pe0c8c.cice.h.0001-01.nc.base.cprnc.out
************************************************************************************************************************************
  
SUMMARY of cprnc:
 A total number of     68 fields were compared
          of which     40 had non-zero differences
               and      0 had differences in fill patterns
 A total number of      0 fields could not be analyzed
 A total number of      0 fields on file 1 were not found on file2.
  diff_test: the two files seem to be DIFFERENT

**Comment by ndkeen** [comment]
I think that https://github.com/E3SM-Project/E3SM/issues/2175 is the same issue. If agreed, go ahead and close this one. I'm checking again now, but I suspect there is no change (ie tests still fail)
