### ISSUE TITLE
line too long in mpas_li_thermal.F

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/E3SM#2296]
PGI compiler on Titan reported an error of "line too long" during compiling maps_li_thermal.F. The trace stack pointed to a comment line at Line 3060.

! Seroussi, H., Y. Nakayama, E. Larour, D. Menemenlis, M. Morlighem, E. Rignot, and A. Khazendar (2017), Continued retreat of Thwaites Glacier, West Antarctica, controlled by bed topography and ocean circulation, Geophys. Res. Lett., 1-9, doi:10.1002/2017GL072910.

**Comment by minxu74** [comment]
@matthewhoffman Could you fix the problem and let the length of the comment line be less than 132? I have done tests and confirmed that the change will fix the fails of three MPASLI related tests in E3SM developer test suite.  Thanks.

**Comment by matthewhoffman** [comment]
@minxu74 , I started working on this and found many more instances that also need to be cleaned up.  I won't get to finish it today.

**Comment by rljacob** [comment]
Don't close this until its merged to master.

**Comment by minxu74** [comment]
Yes. Exactly.

**Comment by jonbob** [comment]
I checked and it looks like all the changes we made recently to mpas-albany-landice were lost in an mpas-ocean update to the mpas-source submodule. We'll track it down and get it fixed as soon as possible.
