### ISSUE TITLE
Info: Bug in Summit job submission check

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#2316]
Documenting the issue here for anyone else puzzled by this.

There is a system-wide bug on Summit's job submission system which aborts if it sees '-n' anywhere. It even picked it up from command line argument while running tests.

Our simulation workflow submits a job like the following. This triggered an error regarding '-n <slots>' although that isn't present in our launch script.
```
$ bsub   -q batch -W 0:45 -P CSC190ACME    .case.test  --skip-preview-namelist
#######################################################
###      1 ERROR(S) FOUND.  JOB NOT SUBMITTED.       ###

30: The '-n <slots>' flag is no longer supported.  Please use '-nnodes <node_count>' to request nodes.
Please address the given error(s) and resubmit.
```
But it worked, when I remove the command line argument to my script '--skip-preview-namelist'. So the check is false-positive for -n within an argument to the script.

This is identical to another issue I submitted last year (ticket #372061: Summitdev LSF: Job script check). I have avoided having '-n' in job names etc. to workaround this issue.

**Comment by jgfouca** [comment]
Add '--allow-pnl' to create_test command.

**Comment by jgfouca** [comment]
@rljacob , why reopen?

**Comment by rljacob** [comment]
This is more about the problem on Summit.  But I guess we should close it since its not an E3SM bug.
