### ISSUE TITLE
Current FORCE_BUILD_SMP behavior and documentation disagree

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2324]
FORCE_BUILD_SMP is defined as

      <desc>TRUE implies always build model for openmp capability
      If FALSE, component libraries are built with OpenMP capability only if
      the NTHREADS_ setting for that component is greater than 1 in env_mach_pes.xml.
      If TRUE, the component libraries are always built with OpenMP capability.</desc>

Currently, if ANY component has NTHREADS_ > 1, then ALL components are built with OpenMP capability, independent of the value of FORCE_BUILD_SMP. The only time the value of FORCE_BUILD_SMP matters is if NTHREADS_ == 1 for all components.

This is a change of behavior from a year ago. v1.0.0-beta.1 (commit 00a38722dbce8eaefa690669c1d98bdd11d56154 on March 3, 2017) behaved as described as above. However, this behavior was lost by v1.0.0-beta.2 (September 2017).

So, we either need to restore the original behavior or change the description of this variable, and any other discussion of the impact of setting NTHREADS_XXX .

I hate to lose capability because of a misunderstanding of existing functionality during CIME development. However, this capability has not been missed, and changing the design documents and other documentation to match reality may be simplest. (At least once it was useful to compile some components with threading enabled and others not, but nothing recently to my knowledge.) It is still worth it in my opinion to determine whether or not the original functionality could be restored easily before giving up on it though.

(See also @amametjanov and @rljacob .)

**Comment by worleyph** [comment]
Issue still exists. @jgfouca? , @amametjanov ? @rljacob?  Simplest fix is to change comment in env_build.xml (and associated documentation?) to reflect what FORCE_BUILD_SMP actually does.

**Comment by Rxzel** [comment]
> FORCE_BUILD_SMP is defined as
> 
> ```
>   <desc>TRUE implies always build model for openmp capability
>   If FALSE, component libraries are built with OpenMP capability only if
>   the NTHREADS_ setting for that component is greater than 1 in env_mach_pes.xml.
>   If TRUE, the component libraries are always built with OpenMP capability.</desc>
> ```
> 
> Currently, if ANY component has NTHREADS_ > 1, then ALL components are built with OpenMP capability, independent of the value of FORCE_BUILD_SMP. The only time the value of FORCE_BUILD_SMP matters is if NTHREADS_ == 1 for all components.
> 
> This is a change of behavior from a year ago. v1.0.0-beta.1 (commit [00a3872](https://github.com/E3SM-Project/E3SM/commit/00a38722dbce8eaefa690669c1d98bdd11d56154) on March 3, 2017) behaved as described as above. However, this behavior was lost by v1.0.0-beta.2 (September 2017).
> 
> So, we either need to restore the original behavior or change the description of this variable, and any other discussion of the impact of setting NTHREADS_XXX .
> 
> I hate to lose capability because of a misunderstanding of existing functionality during CIME development. However, this capability has not been missed, and changing the design documents and other documentation to match reality may be simplest. (At least once it was useful to compile some components with threading enabled and others not, but nothing recently to my knowledge.) It is still worth it in my opinion to determine whether or not the original functionality could be restored easily before giving up on it though.
> 
> (See also @amametjanov and @rljacob .)

Hi can anyone teach me?

**Comment by Rxzel** [comment]
> Issue still exists. @jgfouca? , @amametjanov ? @rljacob? Simplest fix is to change comment in env_build.xml (and associated documentation?) to reflect what FORCE_BUILD_SMP actually does.



> FORCE_BUILD_SMP is defined as
> 
> ```
>   <desc>TRUE implies always build model for openmp capability
>   If FALSE, component libraries are built with OpenMP capability only if
>   the NTHREADS_ setting for that component is greater than 1 in env_mach_pes.xml.
>   If TRUE, the component libraries are always built with OpenMP capability.</desc>
> ```
> 
> Currently, if ANY component has NTHREADS_ > 1, then ALL components are built with OpenMP capability, independent of the value of FORCE_BUILD_SMP. The only time the value of FORCE_BUILD_SMP matters is if NTHREADS_ == 1 for all components.
> 
> This is a change of behavior from a year ago. v1.0.0-beta.1 (commit [00a3872](https://github.com/E3SM-Project/E3SM/commit/00a38722dbce8eaefa690669c1d98bdd11d56154) on March 3, 2017) behaved as described as above. However, this behavior was lost by v1.0.0-beta.2 (September 2017).
> 
> So, we either need to restore the original behavior or change the description of this variable, and any other discussion of the impact of setting NTHREADS_XXX .
> 
> I hate to lose capability because of a misunderstanding of existing functionality during CIME development. However, this capability has not been missed, and changing the design documents and other documentation to match reality may be simplest. (At least once it was useful to compile some components with threading enabled and others not, but nothing recently to my knowledge.) It is still worth it in my opinion to determine whether or not the original functionality could be restored easily before giving up on it though.
> 
> (See also @amametjanov and @rljacob .)

**Comment by Rxzel** [comment]
Can anyone teach me?

**Comment by Ashofstone13977** [comment]
I'm a newbie

**Comment by Rxzel** [comment]
Oh

Pada tanggal Min, 12 Jan 2020 04.33, Ashofstone13977 <
notifications@github.com> menulis:

**Comment by Ashofstone13977** [comment]
Yeah someone pretty much stole all the account linked with the 2 emails

**Comment by Ashofstone13977** [comment]
Music games movies

**Comment by jgfouca** [comment]
@worleyph , I'll do the simple fix.

**Comment by worleyph** [comment]
Do you want me to provide the correct description of the logic? Should be obvious, but happy to do so.

**Comment by jgfouca** [comment]
@worleyph , you described it well in the ticket. I'll make the change on the CIME side.

**Comment by worleyph** [comment]
Thanks

**Comment by rljacob** [comment]
I opened a similar issue in https://github.com/ESMCI/cime/issues/3352
