### ISSUE TITLE
E3SM master module issue on Cori-KNL after its return from PM

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2328]
Just now tried to submit a job on Cori-KNL. It failed with

     ...
     Checking that inputdata is available as part of case submission
     ERROR: module command /opt/modules/default/bin/modulecmd python load craype PrgEnv-intel cray-mpich failed with message:
     /opt/modules/default/bin/modulecmd: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory

If I do a ./preview_run, every thing looks file. However, if I first

     source .env_mach_specific.csh

and then try

     /preview_run

I get the same error as in ./case.submit described above.

**Comment by ndkeen** [comment]
I can also repeat this error.

I'm not seeing any module changes on Cori from the maintenance that would affect us. I can do all of the module commands by hand without issue, as well as sourcing the '.env_mach_specifc.csh' file. 

However, what our system actually does is use:
```
/opt/modules/default/bin/modulecmd python rm craype
```
for example.  And when I try this on the command line, it shows me some output as if it is removing the module, but then a 
```
 /opt/modules/default/bin/modulecmd python list
```
still shows that craype is present.

I'm not really sure how to debug the `/opt/modules/default/bin/modulecmd python` method.

@jgfouca : any advice on how to debug potentially different behavior between the module commands I might issue on the command line vs how python is doing those same commands?

**Comment by ndkeen** [comment]
I'm not sure if this is the right way to debug, but here is a better example of what I mean by the two different "methods" of working with modules are behaving differently:

```
cori07% module list -t > & ml ; grep zlib ml
zlib/1.2.8
cori07% /opt/modules/default/bin/modulecmd python list -t > & ml ; grep zlib ml
zlib/1.2.8
cori07% module rm zlib
cori07% module list -t > & ml ; grep zlib ml
cori07% /opt/modules/default/bin/modulecmd python list -t > & ml ; grep zlib ml
cori07% module load zlib
cori07% module list -t > & ml ; grep zlib ml
zlib/1.2.8
cori07% /opt/modules/default/bin/modulecmd python list -t > & ml ; grep zlib ml
zlib/1.2.8
cori07% /opt/modules/default/bin/modulecmd python rm zlib >& o
cori07% module list -t > & ml ; grep zlib ml
zlib/1.2.8
cori07% /opt/modules/default/bin/modulecmd python list -t > & ml ; grep zlib ml
zlib/1.2.8
```

I'm using the -t flag to module which is for "terse" and will show one module per line, which makes the following grep output nicer to look at.  I just picked one module named zlib.

**Comment by ndkeen** [comment]
You are right, Pat. It appears that whatever is happening is outside of python.  I can execute all of the commands in that file on the command line multiple times.  And I can:

```
cori07% csh .env_mach_specific.csh 
1.613u 0.335s 0:01.98 97.9% 0pf+0w
cori07% csh .env_mach_specific.csh
1.633u 0.266s 0:01.95 96.9% 0pf+0w
cori07% source .env_mach_specific.csh 
cori07% csh .env_mach_specific.csh
cray-netcdf/4.4.1.1.3(9):ERROR:150: Module 'cray-netcdf/4.4.1.1.3' conflicts with the currently loaded module(s) 'cray-netcdf-hdf5parallel/4.4.1.1.3'
cray-netcdf/4.4.1.1.3(9):ERROR:102: Tcl command execution failed: conflict cray-netcdf-hdf5parallel

/opt/cray/pe/modules/3.2.10.6/bin/modulecmd: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
/opt/cray/pe/modules/3.2.10.6/bin/modulecmd: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
/opt/cray/pe/modules/3.2.10.6/bin/modulecmd: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
...
```

**Comment by ndkeen** [comment]
Yes, simply removing the module load of zlib allows the test to build/run.  I will investigate if we still need zlib (I recall adding it) and/or if we can find a work-around (and tell NERSC).

**Comment by worleyph** [comment]
I also verified that it was not just the number of module loads. Commenting out others and keeping zlib still produces the error. So, zlib it is. Thanks @ndkeen .

**Comment by ndkeen** [comment]
Currently running tests where I'm simply removing the module load of zlib. We added it here https://github.com/E3SM-Project/E3SM/pull/1230/ and it may be that it's not needed anymore as the HOMME test is passing.

**Comment by ndkeen** [comment]
Just FYI, I narrowed down the issue to the following module commands which I sent to NERSC.  But I think for now, we can remove the zlib module commands to avoid and I will make a PR.

```
module rm craype PrgEnv-intel PrgEnv-cray PrgEnv-gnu
module list >& m00.txt

module load craype PrgEnv-intel

module rm zlib
module load zlib/1.2.8

module list >& m01.txt

module rm craype PrgEnv-intel PrgEnv-cray PrgEnv-gnu
module list >& m02.txt

module load craype
module load PrgEnv-intel

Should see the following error:
/opt/cray/pe/modules/3.2.10.6/bin/modulecmd: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
```

**Comment by ndkeen** [comment]
I have https://github.com/E3SM-Project/E3SM/pull/2332 merged to next
