### ISSUE TITLE
Cloning repo instructions

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#2337]
Perhaps we can use `git clone --recurse-submodules` to simplify cloning workflow? --recursive is similar but seems to be deprecated.

```
--recursive, --recurse-submodules
 After the clone is created, initialize all submodules within, using their default settings. 
This is equivalent to running git submodule update --init --recursive immediately after the clone is finished. 
This option is ignored if the cloned repository does not have a worktree/checkout 
(i.e. if any of --no-checkout/-n, --bare, or --mirror is given)
```
Existing repo clones would use : git submodule update --init --recursive
Discussion: https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by rljacob** [comment]
e3sm.org "quick start" has been updated to tell people to use --recursive.
