### ISSUE TITLE
Took more than 2 hours to write a netcdf4p file for the test ERIO.ne30_g16_rx1.A on Titan

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/E3SM#2341]
The test was hanging for 2 hours when it tried to write a cpl instantaneous history file using netcdf4p on Titan and quit after it used up 2 hours wall-time.

**Comment by jayeshkrishna** [comment]
NetCDF4P is very sensitive to the version of NetCDF and HDF5 libraries. Some combinations (versions) of these libraries results in hangs.
You can try out a different version of HDF5 + NetCDF and see if the test works (I have not found a documentation that details these issues, and had to resort to trial and error in the past).

**Comment by minxu74** [comment]
@jayeshkrishna Thanks. Let me try some combinations of NetCDF and HDF5 versions on Titan.

**Comment by rljacob** [comment]
Closing since Titan is no more.
