### ISSUE TITLE
ECA phosphatase flux calculation used a wrong profile

### ISSUE THREAD

**Issue by qzhu-lbl** [E3SM-Project/E3SM#2362]
Phosphatase activity is assigned to each individual phosphorus pool based on their percentage fraction. Previously, it looped over litter1,litter2,litter3,cwd,soil1,soil2,soil3. Now, it is corrected to loop over only soil1,soil2,soil3.

**Comment by rljacob** [comment]
Thanks.  A few pointers:  Pretend you didn't already make a PR to fix it so don't reference the PR in the title or the description.   github will add that link when you reference this bug in the PR.

Why was looping over litter1,litter2,litter3,cwd wrong?  People who may have run with this bug are going to want to know.
