### ISSUE TITLE
FATES compilation error with IBM compilers

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#2365]
While compiling FATES with IBM XL compilers on Summit, I encountered the following error:
```
E3SM/components/clm/src/external_models/fates/biogeochem/EDMortalityFunctionsMod.F90", 
line 110.33: 1513-041 (S) Arguments of the wrong type were specified for the INTRINSIC procedure "min".
 ** edmortalityfunctionsmod   === End of Compilation 1 ===
1501-511  Compilation failed for file EDMortalityFunctionsMod.F90.
```

The troublemaker is from 
https://github.com/NGEET/fates-release/blob/master/biogeochem/EDMortalityFunctionsMod.F90#L110
```
    temp_dep  = max(0.0,min(1.0,1.0 - (temp_in_C - &
EDPftvarcon_inst%freezetol(cohort_in%pft))/frost_mort_buffer) )
```

Thought it might be line continuation character but that didn't fix the problem.
Then introduced a temporary variable for the expression in min but that didn't help.

Any suggestions?

Ref: Compiler invocation  
`mpixlf  -c -I. -I../../ibm/spectrum-mpi/nodebug/nothreads/include -I../../ibm/spectrum-mpi/nodebug/nothreads/mct/noesmf/c1a1l1i1o1r1g1w1e1/include -I/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20180502/netcdf-4.4.1-53k2c6jmtr7lxhoyxngf7ukoaxfe6qpk/include -I/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20180502/netcdf-fortran-4.4.4-xrwee65patlyiqh55hbs46br73pthoyp/include -I/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20180502/parallel-netcdf-1.8.0-anw4q6sxalhwbbiaep7vqmw4d56enfv2/include -I../../ibm/spectrum-mpi/nodebug/nothreads/include -I../../lnd/obj -I../../lnd/obj -I. -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/cime/scripts/myfc5av1c-h01a-ibm/SourceMods/src.clm -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/main -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/data_types -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/biogeophys -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/biogeochem -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/dyn_subgrid -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/fates/main -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/fates/biogeophys -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/fates/biogeochem -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/fates/fire -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/mpp/src/mpp/dtypes -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/mpp/src/mpp/thermal -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/mpp/src/mpp/util -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/mpp/src/mpp/vsfm -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/emi/src/ -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/emi/src/elm_types -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/emi/src/em/betr -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/emi/src/em/fates -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/emi/src/em/ptm -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/emi/src/em/vsfm -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/emi/src/data_types -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/betr/betr_core -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/betr/betr_dtype -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/betr/betr_bgc -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/betr/betr_grid -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/betr/betr_para -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/betr/betr_main -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/betr/betr_math -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/betr/betr_rxns -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/betr/betr_util -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/driver/shared -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/driver/alm -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/Applications/app_util -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/Applications/soil-farm/bgcfarm_util -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/sbetr/src/Applications/soil-farm/CENT_ECACNP -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/utils -I/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/cpl -I/gpfs/alpinetds/scratch/sarat/csc190/e3sm_scratch/myfc5av1c-h01a-ibm/bld/lib/include -g -qfullpath -qmaxmem=-1 -qphsinfo   -qzerosize -qfree=f90 -qxlf2003=polymorphic  -qspillsize=2500 -qextname=flush  -O2 -qstrict -Q  -WF,-DMODAL_AER -WF,-DLINUX -WF,-DNDEBUG -WF,-DHAVE_MPI -WF,-DPIO1 -WF,-DFORTRAN_SAME -WF,-DCPRIBM -WF,-DLINUX -WF,-DHAVE_SLASHPROC -qsuffix=f=f90:cpp=F90   -WF,-DUSE_CONTIGUOUS=contiguous\\, /autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/external_models/fates/biogeochem/EDMortalityFunctionsMod.F90`

**Comment by rzurob** [comment]
Hello.  XL Fortran is following the standard in this case.  All arguments to MIN() must have the same kind.  In the referenced code, there is:
`min(1.0,1.0 - (temp_in_C - & ...`
The literal 1.0 is real(4) by default while temp_in_C is real(r8).
You can make the code standard-compliant, and make XLF happy, but specifying the kind on the 1.0 literals. For example:
`min(1.0_r8,1.0_r8 - (temp_in_C - & ...`

**Comment by worleyph** [comment]
Explicit typing of all constants used to be a requirement in CESM. I don't know if we have dropped this, but I would strongly encourage re-adopting this. @rljacob , would it be worthwhile going through and identifying untyped constants in E3SM?

**Comment by sarats** [comment]
Thanks @rzurob . I knew it had to be something right in front my eyes.

**Comment by rgknox** [comment]
Thanks all for your help, I will get this fix worked in.

**Comment by rgknox** [comment]
@worleyph , I like explicit constants too, I've been slowly trying to get them into fates here and there.  I think it helps especially with code readability.

**Comment by worleyph** [comment]
@rljacob , for the original campaign, I think that Tony Craig developed some sort of script to help with this. This was a long time ago, so perhaps I am misremembering.
