### ISSUE TITLE
Not saving component log files in logs subdirectory eliminates them from perf. archive

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2369]
The decision not to copy the component and e3sm log files back to $CASE/log has the side effect of also preventing the CPL and E3SM log files from being saved in the performance archive. These logs files containt important performance monitoring data.

Code that no longer works as expected is in provenance.py:

    globs_to_copy.append("logs/e3sm.log.{}.gz".format(lid))
    globs_to_copy.append("logs/cpl.log.{}.gz".format(lid))

(lines 345-346).

**Comment by worleyph** [comment]
@jgfouca , I'll create the PR and test, but I would greatly appreciate it if you would provide the replacements for the lines

     globs_to_copy.append("logs/e3sm.log.{}.gz".format(lid))
     globs_to_copy.append("logs/cpl.log.{}.gz".format(lid))

to copy these files from rundir instead of the logs/ directory. Looking at the existing code, it would take me some time to fumble around and figure it out, and then it might not be how you would do it in any case. Hopefully this is a 3 minute task for you.

**Comment by jgfouca** [comment]
@worleyph , will do

**Comment by worleyph** [comment]
@jgfouca , I can take a whack at this if you don't have time, and can then assign you as a reviewer to make sure that what I did was reasonable. I would like to get this in asap, since performance archiving is not working as expected until a fix goes in.

**Comment by jgfouca** [comment]
@worleyph , that's what I was expecting. Did I misinterpret your comment from 5 days ago?

**Comment by worleyph** [comment]
@jgfouca , at this point I'm confused about what we are confused about :-). I was hoping for a suggested modification to the lines

      globs_to_copy.append("logs/e3sm.log.{}.gz".format(lid))
      globs_to_copy.append("logs/cpl.log.{}.gz".format(lid))

from you but will try to figure this out myself if you do not have the time. I'll take a whack at it tonight or tomorrow morning I guess.

**Comment by jgfouca** [comment]
@worleyph ,

Here's how I would do it:

```
  globs_to_copy.append(os.path.join(rundir, "logs/e3sm.log.{}.gz".format(lid)))
  globs_to_copy.append(os.path.join(rundir, "logs/cpl.log.{}.gz".format(lid)))
```

And then make a minor modification to the loop a few lines later:

```
    for glob_to_copy in globs_to_copy:
	glob_to_copy = glob_to_copy if glob_to_copy.startswith("/") else os.path.join(caseroot,	glob_to_copy)
        for item in glob.glob(glob_to_copy):
            ...
```

**Comment by worleyph** [comment]
why is this better? (just curious). There are other examples using explicit '/' in building paths.

**Comment by worleyph** [comment]
@jgfouca , just now saw your explanations.

**Comment by jgfouca** [comment]
@worleyph , you mean os.path.join vs. str + "/" + str? os.path.join is more portable (will work on systems where "/" is not the path separation character). It is highly unlikely CIME will ever support non-linux systems, so it just comes down to programmer preference.
