### ISSUE TITLE
ERS.f19_g16.I1850CNRDCTCBC fails on bebop

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/E3SM#2370]
The test fails on bebop because the input file, 
clm_params_c*,  cannot be read using PnetCDF
because it is not a valid NetCDF file.

**Comment by jayeshkrishna** [comment]
A new version of the clm_params_* file, clm_params_c180524.nc, has been uploaded to the ACME svn repository.
The previous version of the file had a NetCDF incompatible content in the header and was removed using the ncvalidator tool to create the new input file.
More info available at https://acme-climate.atlassian.net/wiki/spaces/SE/pages/720273485/Testing+for+CDF+Compatibility+Validity
@jqyin : Can you try out the new file and see it it works?

**Comment by jqyin** [comment]
Thanks @jayeshkrishna . I'm running test now.

**Comment by jqyin** [comment]
I confirm that with new version of clm_params and CNP files ERS.f19_g16.I1850CNRDCTCBC test passed.  Just to be sure, which original files did you use to generate the new versions? Are they clm_params_c180312.nc and CNP_parameters_c180312.nc?

**Comment by jqyin** [comment]
I tried cprnc which didn't work, but nudump outputs are identical except filename. So I think we're good.
