### ISSUE TITLE
Is ne4 stable?

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/E3SM#2379]
Recently, @cjvogl had an ne4 F case crash after making a change we weren't expecting to have major impact. Then yesterday @jhkennedy told me that he had to reduce the model timestep for an ensemble of 1 yr simulations he was running in order to avoid crashes. In both cases the crashes occurred after several simulated months. Upon hearing this, @singhbalwinder checked ne4 nightly tests and found that they had passed just fine in the previous few days. Has anyone else had problems with ne4 stability recently? Does anyone know whether its timestep has been pushed far towards efficiency at the possible price of stability? I'm not asking for a change, I'm just trying to understand how to interpret these recent crashes. Thanks!

**Comment by AaronDonahue** [comment]
@PeterCaldwell Just in case it is helpful.  I ran the latest version of master on ne4 with a 7200sec timestep (the default) using 433 cores on LC-syrah and had no issues for a 1yr run.  I also ran two years on LC-quartz as a check.  Also no problems.

**Comment by ndkeen** [comment]
Aside from a few issues that I've recorded in github with ne4 (particular cases), I don't know of any other crashes. With ne4 F cases, they are so easy to try, please create an issue with the commands used and relevant output. Would be easy to try on other machines.

**Comment by cjvogl** [comment]
@ndkeen We haven't had any issues running code from any commit in the master branch.  The issues  came up during experiments with changing some of the microphysics code: changes that should be very minor and have no significant effect were causing the code to crash after a few months.  When we apply the same changes to the ne30 grid, no issues arise in 5 year runs.  I think @PeterCaldwell and I are just going to move forward without using ne4 for debugging.

**Comment by ndkeen** [comment]
Looking through old issues. Can we close this one?

**Comment by cjvogl** [comment]
Sounds good to me

**Comment by rljacob** [comment]
Yes the ne4 timestep was changed in PR #3434
