### ISSUE TITLE
CLM submodule not available

### ISSUE THREAD

**Issue by mark-petersen** [E3SM-Project/E3SM#2386]
On today's master, 2873c2005, a submodule is not available, so I can't easily proceed with standard work.  Please change the submodule to point to a previous commit that exists in the repo.
```
git submodule update components/clm/src/external_models/fates
error: Server does not allow request for unadvertised object bea1fb10c4840a727d82c8cdb431590e0e4b7d30
Fetched in submodule path 'components/clm/src/external_models/fates', but it did not contain bea1fb10c4840a727d82c8cdb431590e0e4b7d30. Direct fetching of that commit failed.
```

**Comment by bishtgautam** [comment]
Most likely `git submodule sync` prior to `git submodule update` should fix the error for you.

**Comment by bishtgautam** [comment]
@mark-petersen, Is this still an issue?

**Comment by mark-petersen** [comment]
It no longer appears, thanks.
