### ISSUE TITLE
Conditional batch directives not working?

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#2393]
For Summit, I have 
```
       <directive compiler="!pgiacc">-alloc_flags smt2</directive>
       <directive compiler="pgiacc">-alloc_flags "gpumps smt2"</directive>
```

But, when I use ibm compilers, .case.run has both lines when it should just have the first line.
```
#BSUB -alloc_flags smt2
#BSUB -alloc_flags "gpumps smt2"
```

What am I missing?

**Comment by jgfouca** [comment]
@sarats , probably not your fault, let me look.

**Comment by jgfouca** [comment]
See https://github.com/ESMCI/cime/pull/2670 if you need fix immediately.
