### ISSUE TITLE
sbetr submodule error on fresh clone.

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#2412]
When initilizing the submodules on a fresh clone, this happens:
```
CSI0350919[121]: git submodule update --init
Submodule 'components/clm/src/external_models/fates' (git@github.com:NGEET/fates-release.git) registered for path 'components/clm/src/external_models/fates'
Submodule 'alm-mpp' (git@github.com:MPP-LSM/MPP.git) registered for path 'components/clm/src/external_models/mpp'
Submodule 'sbetr' (git@github.com:BeTR-biogeochemistry-modeling/sbetr.git) registered for path 'components/clm/src/external_models/sbetr'
Submodule 'components/mpas-source' (git@github.com:MPAS-Dev/MPAS-Model.git) registered for path 'components/mpas-source'
Cloning into '/Users/jacob/E3SMtry/components/clm/src/external_models/fates'...
Cloning into '/Users/jacob/E3SMtry/components/clm/src/external_models/mpp'...
Cloning into '/Users/jacob/E3SMtry/components/clm/src/external_models/sbetr'...
Cloning into '/Users/jacob/E3SMtry/components/mpas-source'...
Submodule path 'components/clm/src/external_models/fates': checked out 'b0b7c9dba5d1cfce126c65b6e5b58d8b5deab2e5'
Submodule path 'components/clm/src/external_models/mpp': checked out '38e0b0461ce10da7de809b752bacc70860ae8bbd'
Fetched in submodule path 'components/clm/src/external_models/sbetr', but it did not contain f2cbe748addb922c3df55835ae75d7204be9ffda. Direct fetching of that commit failed.
Exit 1
```

**Comment by jinyun1tang** [comment]
@rljacob it seems this was pointing to a commit that does not exist in the master of sbetr.

**Comment by jinyun1tang** [comment]
@bishtgautam, probably you may link it with the branch bishtgautam/elm-bgc-refactor to fix the issue?

**Comment by rljacob** [comment]
How did this happen?  I don't see any recent PRs that touched the sbetr module

**Comment by jinyun1tang** [comment]
@rljacob , it is in the branch bishtgautam/fix-type-definition, and I accidentally removed it by considering it as obsolete. But I do have a local copy, and I can push it back to remote. What is the best command to do this?

**Comment by rljacob** [comment]
You mean it was deleted from github.com/BeTR-biogeochemistry-modeling/sbetr ?
Just do "git push <remote> bishtgautam/fix-type-definition" from your local copy.

**Comment by jinyun1tang** [comment]
@rljacob, I tried and get the following
git push bishtgautam/fix-type-definition
fatal: You didn't specify any refspecs to push, and push.default is "nothing".

**Comment by rljacob** [comment]
Oh sorry.   formatting error.  you need to specify the remote.
`git push <remote> bishtgautam/fix-type-definition`

**Comment by jinyun1tang** [comment]
@rljacob get it done. Please try it again.

**Comment by bishtgautam** [comment]
Is this still an issue? I was able to successfully clone the repo without any issues.

**Comment by jinyun1tang** [comment]
Then it is fixed after I restore the link

**Comment by rljacob** [comment]
Ok it works now.  Thanks!

**Comment by rljacob** [comment]
@bishtgautam  That bishtgautam/fix-type-definition branch has to live forever or any E3SM master hash that used it will break.  You should probably tag it if its not already.

**Comment by bishtgautam** [comment]
@jinyun1tang, Did you earlier delete bishtgautam/fix-type-definition branch?

**Comment by bishtgautam** [comment]
@jinyun1tang, Never mind. I just read your explanation in https://github.com/E3SM-Project/E3SM/issues/2412#issuecomment-401125252
