### ISSUE TITLE
Failing test SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.cori-knl_intel.allactive-v1cmip6 

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#2413]
Similar to issue https://github.com/E3SM-Project/E3SM/issues/2043, this test also fails. 

First I added a debug print statement to print the name file that was having troubling opening, and we see that it is a "netCDF-4" type:

```
cori04% ls -l /project/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc
-rw-rw-r--+ 1 pjc pjc 271093 Nov  2  2017 /project/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc

cori04% ncdump -k /project/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc
netCDF-4
```
I then used the ncks command from the nco module to convert the file to 64bit offset:

```
cori04% module load nco

cori04% ncks -6 /project/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc t.nc

cori04% ncdump -k t.nc 
64-bit offset
```

I then copied this file to overwrite the file in a *copy* of inputdata stored on scratch.  To use the inputdata on scratch, the following commands can be used:

```
./xmlchange DIN_LOC_ROOT="/global/cscratch1/sd/acmedata/inputdata"
./xmlchange DIN_LOC_ROOT_CLMFORC="/global/cscratch1/sd/acmedata/inputdata/atm/datm7"
```

This allowed the test to complete 2 days.  We now need to make this file conversion into the official set of inputdata, which will require a name change.

Note that I am making a separate issue from 2043 because: in that case, I also made a similar netcdf file conversion, which does seem to allow the run to go beyond where it was stopping, however there is still an error which is likely unrelated.

**Comment by ndkeen** [comment]
There are about 60 netcdf files that are "netCDF-4" and another 76 that are "netCDF-4 classic model". My above experiment only changed the ~60 that are "netCDF-4".  There are also a handful of files that are having troubling converting, but are not causing an issue with this test.

Should I:
a) Try to find smallest set of files that need to be changed to allow this test to work?
b) Make a PR to change all ~60 netcdf files -- or at least document the files and we can decide which ones to convert
c) Go ahead and try to convert all files (the 60+76) that are netcdf4?

**Comment by rljacob** [comment]
Do a and make a PR for that.

Then also do the documentation part of b.   We can make a Confluence page with the list.

**Comment by ndkeen** [comment]
OK, I think we can get away with just one file conversion. This case points to only one file that is "netCDF-4", and a few others that are "netCDF-4 classic model".  So it *could* be that "netCDF-4 classic model" is OK?  

Here is info on the file that I'm suggesting converting

```
-rw-rw-r--+ 1 pjc pjc 271093 Nov  2  2017 /project/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc

-rw-rw-r--  1 ndk ndk 210852 Jun 27 17:09 /global/cscratch1/sd/acmedata/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc

+ ncdump -k /project/projectdirs/acme/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc
netCDF-4

+ ncdump -k /global/cscratch1/sd/acmedata/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc
64-bit offset

```

**Comment by ndkeen** [comment]
Well, I got ahead of myself. Appears that after making this change, there is at least one other file that this test will fail on:

```
cori04% ls -l /project/projectdirs/acme/inputdata/atm/cam/chem/trop_mozart_aero/oxid/oxid_1.9x2.5_L26_1850-2015_c20171110.nc
-rw-rw-r--+ 1 golaz golaz 1564819036 Nov 13  2017 /project/projectdirs/acme/inputdata/atm/cam/chem/trop_mozart_aero/oxid/oxid_1.9x2.5_L26_1850-2015_c20171110.nc
cori04% ncdump -k /project/projectdirs/acme/inputdata/atm/cam/chem/trop_mozart_aero/oxid/oxid_1.9x2.5_L26_1850-2015_c20171110.nc
netCDF-4 classic model
```

I created a new file on blues that has a new name (todays date) and is 64bit offset.

```
blogin4% ls -l /lcrc/group/acme/public_html/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20180629.nc
-rw-rw----+ 1 ndk climate 210852 Jun 29 12:04 /lcrc/group/acme/public_html/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20180629.nc

blogin4% ncdump -k /lcrc/group/acme/public_html/inputdata/atm/cam/solar/Solar_1850control_input4MIPS_c20180629.nc
64-bit offset

I then updated the following two files to point to this newer version of the solar control file:

before:
./bld/namelist_files/use_cases/1850_cam5_CMIP6.xml:8:<solar_data_file>atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc</solar_data_file>
./bld/namelist_files/use_cases/1850_cam5_CMIP6_bgc.xml:5:<solar_data_file>atm/cam/solar/Solar_1850control_input4MIPS_c20171101.nc</solar_data_file>

after:
./bld/namelist_files/use_cases/1850_cam5_CMIP6.xml:8:<solar_data_file>atm/cam/solar/Solar_1850control_input4MIPS_c20180629.nc</solar_data_file>
./bld/namelist_files/use_cases/1850_cam5_CMIP6_bgc.xml:5:<solar_data_file>atm/cam/solar/Solar_1850control_input4MIPS_c20180629.nc</solar_data_file>

```

I just created the branch `ndk/nml/add-solarfile-with-64bitoffset` which has that change.

Note I was unable to get Cori to download that file from blues, so to test, I simply added it manually to /project.  And testing shows that I hit an error with the file noted above.

**Comment by ndkeen** [comment]
OK, double-checking, I can run the test using scratch inputdata, but not the project inputdata. The file that it dies on is identical. I can try debugging this further:
1) Are netcdf4 files only sometimes failing?
2) Does the filesystem itself matter? (project is GPFS while scratch is lustre)
3) Is there something else different between the 2 sets of inputdata
4) Something amiss with my experiments

Or I could try converting more of the files (esp those in or around that atm directory with cmip6 in the name) from netcdf4 to 64bit offset.

Or we could try to figure out why we even have trouble with netcdf4 at all?
This is supposedly an improved format.

**Comment by jayeshkrishna** [comment]
Does the test (SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6) pass on other machines?

**Comment by jayeshkrishna** [comment]
This could be an issue with the netcdf module on Cori

**Comment by golaz** [comment]
@ndkeen : the file system could matter if it has to do with file locking and hdf5 1.10+ (needed by netCDF4). Out of the blue, you may want to try:

`export HDF5_USE_FILE_LOCKING=FALSE`

This sounds like possibly the same problem as https://github.com/E3SM-Project/acme_diags/issues/161#issuecomment-397118388 and https://github.com/E3SM-Project/acme_diags/issues/164

**Comment by ndkeen** [comment]
Huh, nice catch @golaz .

At http://www.nersc.gov/users/data-analytics/data-management/i-o-libraries/hdf5-2/hdf5/
I see:

```
    HDF5 1.10.0 file locking issue (Fixed with 1.10.1) but need to set one env variable)

HDF5 1.10.x which has the SWMR feature, and enables flock to allow multiple applications opening the same file. The flock, however, is not enabled by certain filesystem at NERSC, e.g., /project, burst buffer, so the fix is to disable the HDF5's flock by setting the environmental variable HDF5_USE_FILE_LOCKING to be FALSE. The flock is enabled on Lustre file system, i.e., SCRATCH, so you won't see any flock error there. Note that Cray's default version (1.10.1.1) is ok, but you can also compile your code with NERSC-built 1.10.1. 
```

Which does suggest that project may act different than scratch.  Easy to test...

**Comment by ndkeen** [comment]
Well unfortunately, that test was not successful. I tried HDF5_USE_FILE_LOCKING=FALSE and I still see the same error.

**Comment by rljacob** [comment]
So the oxid_1.9x2.5_L26_1850-2015_c20171110.nc file can be read fine from scratch but not from project?  Are you sure they are identical?  Try cmp file1 file2

**Comment by ndkeen** [comment]
Yes the two files appear identical.  From cprnc: `diff_test: the two files seem to be IDENTICAL`.
I'm now trying to debug why we get the error in the first place. I see that error_handling is set by PIO to be `PIO_INTERNAL_ERROR` and it's not clear if it's being changed. It even looks like it's only checked for iotypes `iotype_pnetcdf` and `iotype_netcdf,pio_iotype_netcdf4p,pio_iotype_netcdf4c`

**Comment by ndkeen** [comment]
The module version changes I'm referring to are:

```
Changing these:
cray-netcdf-hdf5parallel/4.4.1.1.3
cray-hdf5-parallel/1.10.0.3
to:
cray-netcdf-hdf5parallel/4.4.1.1.6
cray-hdf5-parallel/1.10.1.1
```

For cori-knl and cori-haswell.  On edison, it looks like I had already bumped the version of cray-hdf5-parallel, but not the other.  I'm running some tests on edison to confirm it's OK to increase the versions of both of these modules on all 3 nersc machines.

I'm also testing if setting `HDF5_USE_FILE_LOCKING` to FALSE changes anything. The documentation makes me think we should turn this off as any potential benefits of file locking are out weighed by ill effects of this behavior on GPFS.

**Comment by ndkeen** [comment]
So far, all tests are passing. This branch has the changes needed. `ndk/machinefiles/nersc-netcdf-hdf-version-update-NOLOCK`

**Comment by ndkeen** [comment]
OK to merge to next?
