### ISSUE TITLE
Can't build with intel-18; need to update the compiler flags to use -qopenmp

### ISSUE THREAD

**Issue by mfdeakin-sandia** [E3SM-Project/E3SM#2418]
Intel changed the `-openmp` flag to `-qopenmp`, and removed the old option name in the 2018 release
This is fixed by updating the `intel` compiler block in `config_compilers.xml`

**Comment by rljacob** [comment]
There's an intel18 option on edison.  Can you reproduce this bug there?

**Comment by ndkeen** [comment]
Yes, there is already a `--compiler=intel18` option, which uses `-openmp`.

**Comment by mfdeakin-sandia** [comment]
Ah. I just didn't realize that existed. I'm building on testbeds here at Sandia which use intel18, so I'll change to that block. Thanks!
