### ISSUE TITLE
SMS_Ld1.ne4_ne4.FC5AV1C-L-AQUAP.cam-clubb_only failing on sandiatoss3

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#2420]
SMS_Ld1.ne4_ne4.FC5AV1C-L-AQUAP.sandiatoss3_intel.cam-clubb_only is failing on both skybridge and chama (same architecture:  sandiatoss3).

**Comment by singhbalwinder** [comment]
@zhangshixuan1987 has suggested a fix for this test. I am currently testing that fix.
