### ISSUE TITLE
ERIO.ne30_g16_rx1.A fails on NERSC machines (problem with netcdf4p type)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#2425]
This is a relatively new test to e3sm_developer and apparently never worked at NERSC.
The test cycles thru all of the valid netcdf types that are in env_run.xml:
`<valid_values>netcdf,pnetcdf,netcdf4p,netcdf4c</valid_values>`
and attempts to run a problem with that type.

The failure mode is that it simply hangs and runs out of time.

I also tried `ERIO.ne4_oQU240.A` which fails in the same way.

I can verify that the problem is with type `netcdf4p`.  The other types seem to work.
To look at this, I first created several `SMS.ne4_ne4.FC5AV1C-L` cases, and then modified the netcdf types (`xmlchange PIO_TYPENAME=xxx`) within each case. They all work except for `netcdf4p`, which hangs. For each of these I changed the typename for all components.  In an attempt to start narrowing things down, for the netcdfp case that fails, I tried a few things and the case will pass when all components except CPL have netcdf4p.  Therefore, I would conclude that the CPLer must be doing some that causes a hang when using netcdf4p.

As an additional test, I modified `cime/src/build_scripts/buildlib.pio` to simply remove netcdf4p from the list of valid types. With this change both `ERIO.ne30_g16_rx1.A` and `ERIO.ne4_oQU240.A` will pass. This is just a test that ERIO passes without netcdf4p.

**Comment by jayeshkrishna** [comment]
Most likely an issue with netcdf4p (combination of netcdf and hdf5 library versions that don't work well together).
You might want to try with a different combination of these libraries (versions of netcdf4 and hdf5)

**Comment by ndkeen** [comment]
I just adjusted the versions of those 2 modules to allow us to get past #2413.
There currently aren't many options to choose from and we are now using the very latest.
It seems like if our code is so sensitive to the versions of these tools, then perhaps we should be configuring/building them ourselves.

**Comment by ndkeen** [comment]
I tested again with very latest modules on Cori after maintenance:
```
cray-netcdf-hdf5parallel/4.6.1.0
cray-hdf5-parallel/1.10.2.0
```
and this test still fails.

This tests will fail on all nersc machines. What's worse is that it will timeout each time (using max wallclock time).

Should we 
a) remove the netcdf4p from the valid set just for nersc? (even possible?)
b) remove test from nersc (or otherwise modify if possible?)
c) leave as failing test until fixed
d) actively try to find out whats going on and fix?

**Comment by rljacob** [comment]
Yes we should just remove netcdf4p from NERSC. The valid values set for PIO_TYPENAME in env_run.xml is machine-dependent.  On anvil only netcdf and pnetcdf are tested.  But I can't see where that list is generated.  Yes we should just remove netcdf4p

**Comment by amametjanov** [comment]
netcdf4p/netcdf4c types can be removed by removing `cray-hdf5-parallel` module and replacing `cray-netcdf-hdf5parallel` module with just `cray-netcdf`.

**Comment by rljacob** [comment]
How can CIME look at the module use commands and conclude "That's a netcdf4p setting"?  There are no standards for naming modules.

**Comment by amametjanov** [comment]
During the build, PIO tests for string "netcdf4p" and if not present edits env_run.xml to remove netcdf4p/netcdf4c from available pio types. The strings are present only when cray-netcdf-hdf5parallel and cray-hdf5-parallel are loaded in the current build env.

**Comment by ndkeen** [comment]
Huh.  I was most suspicious of the suggestion by Az. I assumed we needed those modules as that's what I inherited and I see it in other places.  Apparently we don't?

Made this change:
```
    <modules mpilib="!mpi-serial">
      <command name="rm">cray-netcdf-hdf5parallel</command>
      <!--command name="load">cray-netcdf-hdf5parallel/4.4.1.1.6</command-->
      <!--command name="load">cray-hdf5-parallel/1.10.1.1</command-->
      <command name="load">cray-parallel-netcdf/1.8.1.3</command>
      <command name="load">cray-netcdf/4.4.1.1.6</command>
    </modules>
```

And sure enough, the list of netcdf types that the test will cycle thru is only these 2:
`env_run.xml:      <valid_values>netcdf,pnetcdf</valid_values>`

And this ERIO test passes.

I'm also running e3sm_developer.  What are the downsides of doing this?  Why have we been using those modules with hdf5?

**Comment by ndkeen** [comment]
Connecting this issue to the following discussion:  https://acme-climate.atlassian.net/wiki/spaces/EIDMG/pages/769130507/Picking+a+netcdf+type+for+all+input+files

**Comment by ndkeen** [comment]
Nothing new, just summarizing that `netcdf4p` has trouble at NERSC. We know how to remove hdf5 altogether and only use `netcdf,pnetcdf`, but that doesn't seem like a good long term solution (perhaps we would like to use the others for performance?). I would like to find a way to allow the tests to pass, if even we find some temporary way of not trying `netcdf4p` in this test (not clear we can do that). Or of course, finding out why it's failing.

**Comment by dqwu** [comment]
@jayeshkrishna 
Not sure if this is a PIO1 issue, but this test pass with PIO2 on Cori.

**Comment by jayeshkrishna** [comment]
Unlikely that it is a PIO1 issue (more an issue with netcdf + hdf5 IMO), are we using the same versions of hdf5 + netcdf for the PIO2 testing (and in PIO2 we use the C interface of these libs)?

**Comment by dqwu** [comment]
@jayeshkrishna 
PIO1 and PIO2  testing use the same latest Cori modules for netcdf and hdf5.

**Comment by ndkeen** [comment]
NERSC has some newer versions of modules now and I just tried this test with most recent versions.  It looks like it's still failing (or hanging) in the same way as before.  Logging onto compute node, I see this is where the code is during hang:

```#0  0x00002aaab06f295a in poll_active_fboxes () from /opt/cray/pe/lib64/libmpich_intel.so.3
#1  0x00002aaab06f71c8 in MPIDI_CH3I_Progress () from /opt/cray/pe/lib64/libmpich_intel.so.3
#2  0x00002aaab063ddcd in MPIC_Wait () from /opt/cray/pe/lib64/libmpich_intel.so.3
#3  0x00002aaab063e067 in MPIC_Recv () from /opt/cray/pe/lib64/libmpich_intel.so.3
#4  0x00002aaab06641ec in MPIR_CRAY_Bcast_Tree () from /opt/cray/pe/lib64/libmpich_intel.so.3
#5  0x00002aaab06664dc in MPIR_CRAY_Bcast () from /opt/cray/pe/lib64/libmpich_intel.so.3
#6  0x00002aaab057614b in MPIR_Bcast_impl () from /opt/cray/pe/lib64/libmpich_intel.so.3
#7  0x00002aaab0661ace in MPIR_CRAY_Allreduce () from /opt/cray/pe/lib64/libmpich_intel.so.3
#8  0x00002aaab0571664 in MPIR_Allreduce_impl () from /opt/cray/pe/lib64/libmpich_intel.so.3
#9  0x00002aaab0572005 in PMPI_Allreduce () from /opt/cray/pe/lib64/libmpich_intel.so.3
#10 0x00002aaab076b3b3 in PMPI_File_set_view () from /opt/cray/pe/lib64/libmpich_intel.so.3
#11 0x00002aaab6c2cc22 in ?? () from /opt/cray/pe/lib64/libhdf5_parallel_intel.so.103
#12 0x00002aaab69e4f77 in H5FD_write () from /opt/cray/pe/lib64/libhdf5_parallel_intel.so.103
#13 0x00002aaab69beb6f in H5F__accum_write () from /opt/cray/pe/lib64/libhdf5_parallel_intel.so.103
#14 0x00002aaab6af2c81 in H5PB_write () from /opt/cray/pe/lib64/libhdf5_parallel_intel.so.103
#15 0x00002aaab69cbb69 in H5F_block_write () from /opt/cray/pe/lib64/libhdf5_parallel_intel.so.103
#16 0x00002aaab6c1c7c2 in H5D__mpio_select_write () from /opt/cray/pe/lib64/libhdf5_parallel_intel.so.103
#17 0x00002aaab6c280d7 in ?? () from /opt/cray/pe/lib64/libhdf5_parallel_intel.so.103
#18 0x00002aaab6c1dfa5 in ?? () from /opt/cray/pe/lib64/libhdf5_parallel_intel.so.103
#19 0x00002aaab6c27696 in H5D__chunk_collective_write () from /opt/cray/pe/lib64/libhdf5_parallel_intel.so.103
#20 0x00002aaab69887ab in H5D__write () from /opt/cray/pe/lib64/libhdf5_parallel_intel.so.103
#21 0x00002aaab6987e6f in H5Dwrite () from /opt/cray/pe/lib64/libhdf5_parallel_intel.so.103
#22 0x00002aaab276e1e1 in NC4_put_vars () from /opt/cray/pe/lib64/libnetcdf_parallel_intel.so.15
#23 0x00002aaab276dad6 in NC4_put_vara () from /opt/cray/pe/lib64/libnetcdf_parallel_intel.so.15
#24 0x00002aaab26f1260 in nc_put_vara_double () from /opt/cray/pe/lib64/libnetcdf_parallel_intel.so.15
#25 0x00002aaaaacf1a92 in nf_put_vara_double_ () from /opt/cray/pe/lib64/libnetcdff_parallel_intel.so.7
#26 0x00002aaaaad45313 in netcdf_mp_nf90_put_var_1d_eightbytereal_ () from /opt/cray/pe/lib64/libnetcdff_parallel_intel.so.7
#27 0x00000000009a9fd2 in pionfwrite_mod_mp_write_nfdarray_double_ ()
    at /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/mfcdt11i18/ERIO.ne30_g16_rx1.A.cori-knl_intel.rallmax/bld/intel/mpt/nodebug/nothreads/mct/pio/pio1/pio//global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-update-modules-cdt1911-intel18/externals/scorpio_classic/pio/pionfwrite_mod.F90.in:119
#28 0x000000000096b807 in piodarray_mp_write_darray_nf_double_ ()
    at /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/mfcdt11i18/ERIO.ne30_g16_rx1.A.cori-knl_intel.rallmax/bld/intel/mpt/nodebug/nothreads/mct/pio/pio1/pio//global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-update-modules-cdt1911-intel18/externals/scorpio_classic/pio/piodarray.F90.in:692
#29 0x000000000096e276 in piodarray_mp_write_darray_1d_double_ ()
    at /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/mfcdt11i18/ERIO.ne30_g16_rx1.A.cori-knl_intel.rallmax/bld/intel/mpt/nodebug/nothreads/mct/pio/pio1/pio//global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-update-modules-cdt1911-intel18/externals/scorpio_classic/pio/piodarray.F90.in:221
#30 0x00000000004def71 in seq_io_mod_mp_seq_io_write_avs_ () at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-update-modules-cdt1911-intel18/cime/src/drivers/mct/main/seq_io_mod.F90:769
#31 0x00000000004d06d5 in seq_hist_mod_mp_seq_hist_write_ () at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-update-modules-cdt1911-intel18/cime/src/drivers/mct/main/seq_hist_mod.F90:332
#32 0x000000000041faa1 in cime_comp_mod_mp_cime_run_write_history_ () at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-update-modules-cdt1911-intel18/cime/src/drivers/mct/main/cime_comp_mod.F90:4506
#33 0x0000000000418c09 in cime_comp_mod_mp_cime_run_ () at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-update-modules-cdt1911-intel18/cime/src/drivers/mct/main/cime_comp_mod.F90:2863
#34 0x000000000043893d in MAIN__ () at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-update-modules-cdt1911-intel18/cime/src/drivers/mct/main/cime_driver.F90:133
#35 0x000000000041628e in main ()
```

**Comment by ndkeen** [comment]
Using a master of May 27th, this test passed. Who is the masked developer fixing issues with PR's and not taking credit for them?

**Comment by ndkeen** [comment]
Looking in CDASH, this test starting passing on May 30th (last fail on May 27th).
I see one change that might have been responsible?
Update CIME to ESMCI cime5.8.23 (PR #3603)

@jayeshkrishna do you know if there was a change that might have fixed this issue? 
Would it make sense to find what fixed it? Or just close it?

**Comment by jayeshkrishna** [comment]
We recently switched the default I/O library in E3SM from Scorpio classic (PIO_VERSION=1) to Scorpio (PIO_VERSION=2). This change could have fixed the issue (Try switching back to PIO_VERSION=1 and see if the problem persists).

**Comment by ndkeen** [comment]
I don't think the PIO_VERSION is a factor.
a) I had already tested using PIO_VERSION=2 before
b) The change to use PIO_VERSION=2 was May 22nd (in the git log output). This test was still failing on May 27th.

I noted a mention of a PIO-related fix in the above PR, but don't know if there was potential for it to impact this.

**Comment by rljacob** [comment]
There was a change to the erio.py code in CIME back on April 28th was part of the recent CIME update.
```
diff --git a/scripts/lib/CIME/SystemTests/erio.py b/scripts/lib/CIME/SystemTests/erio.py
index a52dd9a84..f76414684 100644
--- a/scripts/lib/CIME/SystemTests/erio.py
+++ b/scripts/lib/CIME/SystemTests/erio.py
@@ -58,10 +58,10 @@ class ERIO(SystemTestsCommon):
     def run_phase(self):
 
         for idx, pio_type1 in enumerate(self._pio_types):
-            if pio_type1 != "default":
+            if pio_type1 != "default" and pio_type1 != "nothing":
                 self._case.set_value("PIO_TYPENAME", pio_type1)
                 self._full_run(pio_type1)
                 for pio_type2 in self._pio_types[idx+1:]:
-                    if pio_type2 != "default":
+                    if pio_type2 != "default" and pio_type1 != "nothing":
                         self._case.set_value("PIO_TYPENAME", pio_type2)
                         self._restart_run(pio_type2, pio_type1)
```

**Comment by ndkeen** [comment]
Thanks Rob. I tried using recent master and then changing that one file (erio.py) to be back to previous version, then ran the ERIO test again and it still passed.

**Comment by ndkeen** [comment]
We still don't know which PR allowed this test to pass, but it seems to be working. Closing issue.
