### ISSUE TITLE
Unexpected multi-instance infile names

### ISSUE THREAD

**Issue by jhkennedy** [E3SM-Project/E3SM#2427]
The pythonization of the pearl `components/*/cime_config/buildnml` scripts changed the multi-instance component infile names to the form `COMPONENT_inNINST` instead of the previous `COMPONENT_in_NINST`. 

This leads to errors like: 
```
FIO-F-209/OPEN/unit=97/'OLD' specified for file which does not exist.            
File name = atm_in_0001
In source file $E3SM/components/cam/src/control/runtime_opts.F90, at line number 394
```
When I run cases using the multi-instance capability. 

Which form should the infile names take? 
**New:** `COMPONENT_inNINST`
**Old:** `COMPONENT_in_NINST`

I expect that the old form should be maintained. 

---

Note: the pythonization happened across multiple component specific PRs:
 
PR #2364 via commit ef9e9580 
PR #2363 via commit c56babcf 
PR #2355 via commit 52c654ea 
PR #2347 via commit a9cb397b 
PR #2344 via commit c41bcb69 
PR #2342 via commit 10d68b12 
PR #2335 via commit e4d9adfc 

I've already got a branch off of #2364 (see below) with the fix for all of the affected components, however, should I instead create create an individual bug-fix PR for each component?

**Comment by jhkennedy** [comment]
@jgfouca did you mean to change the for of the instance suffix?

**Comment by jgfouca** [comment]
@jhkennedy , no, looks like I made a mistake.

**Comment by jhkennedy** [comment]
@jgfouca should I make seperate PRs for these fixes since they are across different components?

**Comment by jgfouca** [comment]
@jhkennedy , no, one PR is fine. Thanks

**Comment by rljacob** [comment]
I don't think we test multi-instance at all.  Can you also add a test for it, @jhkennedy ?

**Comment by jhkennedy** [comment]
@rljacob sure! As part of this PR, or a new one?

**Comment by rljacob** [comment]
You can do it as part of the PR to fix this issue.
