### ISSUE TITLE
MEMLEAK fail with SMS_P64_Ly1.ne4_oQU480.A_WCYCL1850.cori-knl_intel 

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#2453]
The 5-day test passed, and I wanted to try a year.

```
MEMLEAK memleak detected, memory went from 2889.900000 to 4069.630000 in 1129 days
```
1129 days?  Looking in cpl.log file, indeed the memory is increasing every day, so there is probably something ill.

```
case:
/global/cscratch1/sd/ndk/acme_scratch/cori-knl/m84-jul17/SMS_P64_Ly1.ne4_oQU480.A_WCYCL1850.cori-knl_intel.rintel
```

hash=`700a6cf25`

**Comment by jonbob** [comment]
Thanks @ndkeen - I'll take a look first thing tomorrow

**Comment by jonbob** [comment]
@ndkeen - I'm trying a one-year T62-oQU480 G-case to see if we can get a better sense of which model might be having memory issues

**Comment by jonbob** [comment]
On anvil, a one-year ne4_oQU480.A_WCYCL1850 test had the memory high-water go from 2072.05 to 2117.65 MB. Could this somehow be a cori-knl issue?

**Comment by jonbob** [comment]
My SMS_P64_Ly1.T62_oQU480.GMPAS-IAF.cori-knl_intel test had high-water memory go from 2850.16 to 2909.93 MB. So maybe not the MPAS components? Are you testing master?

**Comment by ndkeen** [comment]
Test `SMS_P64_Ly1.ne4_oQU480.A_WCYCL1850.cori-knl_intel` completed with master of Nov 6th, so I'm closing.
