### ISSUE TITLE
Compact output of mapping of MPI tasks to compute nodes

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2457]
Currently MPI task to compute node mapping information is
output in two locations, once in CAM, where it is
truncated after the first 256 MPI tasks, and once in CLM,
where it is truncated after the first 100 MPI tasks,
both only for these two components. This is not useful in current
production runs. The use of environment variables, such as
MPICH_CPUMASK_DISPLAY on Cray systems, generate data that are
unnecessarily verbose for our needs. A common routine that would
output these data in a compact representation would allow us to
provide these data (useful for code debugging and for diagnosing system
failures) without depending on system environment variables.

**Comment by rljacob** [comment]
The e3sm.log file also has a list truncated after 256.
```
 0:         1350 pes participating in computation
   0:  -----------------------------------
   0:  TASK#  NAME
   0:   0  nid01568
   0:   1  nid01568
   0:   2  nid01568
   0:   3  nid01568
   0:   4  nid01568
   0:   5  nid01568
   0:   6  nid01568
.
.
.
   0:  ... list truncated at 256
```

But I can not find what outputs this info.  It doesn't appear to be from Fortran code.

**Comment by rljacob** [comment]
Oh I see.  It is atmosphere code "subroutine spmdinit( mpicom_atm )" but its getting output to e3sm.log, not atm.log

**Comment by worleyph** [comment]
Yes - both CAM and CLM write out this information to the e3sm.log . I was planning on doing the same, simply because it is the current design (and because this is what iulog points to at this point in CAM and CLM).
