### ISSUE TITLE
mpibcast calls with wrong type in cam/src/physics/cam/phys_control.F90

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2461]
The following was found by @shz0116 in cam/src/physics/cam/phys_control.F90

     integer           :: convproc_method_activate = 2      ! controls activation in the unified convective transport/removal                                                                                                                 
     integer           :: mam_amicphys_optaa   = 0          ! <= 0 -- use old microphysics code (separate calls to gasaerexch,      
     ...          
     call mpibcast(convproc_method_activate,        1 , mpilog,  0, mpicom)
     call mpibcast(mam_amicphys_optaa,              1 , mpilog,  0, mpicom)

Note that the mpibcast calls should use mpiint instead of mpilog.

Shan has a branch that fixes this, and will likely submit a PR in the near future. We do not know how critical this is.

**Comment by singhbalwinder** [comment]
This is a good catch. It might cause issues with some compilers where they might complain about it. I do not think it is critical but, now that we know about it, it is a good idea to fix it.
