### ISSUE TITLE
inefficient bcast code in cam/src/chemistry/mozart/mo_jlong.F90

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2462]
The following was identified by @shz0116 in cam/src/chemistry/mozart/mo_jlong.F90 -

     allocate( rsf_tab(nw,nump,numsza,numcolo3,numalb),stat=iret )
     ...
      do w = 1,nw
         call mpibcast( rsf_tab(w,:,:,:,:), numalb*numcolo3*numsza*nump, mpir4, 0, mpicom )
      enddo

This forces internal array copies as well as unnecessary multiple mpibcast calls. The fix, proposed by Shan, is to replace this by

     call mpibcast( rsf_tab, nw*numalb*numcolo3*numsza*nump, mpir4, 0, mpicom )

Shan will be submitting a PR for this, and this is issue will be pointed to by the PR.

**Comment by singhbalwinder** [comment]
Thanks @worleyph and @shz0116 for identifying and fixing this. Please assign me as an integrator when the PR is ready.
