### ISSUE TITLE
modifying ocn_comp_mct.F90 not recognized by build

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2466]
1) modifying ocn_comp_mct.F90 and then doing 

     ./case.build 

does not capture the changes.

2) modifying ocn_comp_mct.F90, then doing

     ./case.build --clean ocn
     ./case.build

ALSO does not capture the changes.

(1) has been true (forever, and always has been annoying). Perhaps I just misremembered, but I was surprised that (2) also did not work. I prefer not to do --clean-all just to make modifications to ocn_comp_mct.F90. I'll try deleting things directly in the build directory next, but this is very annoying. If this could be put back on someone's list, I'd appreciate it.

Don't know who to ask to look at this. Perhaps @jonbob can remind me whether this is a feature or a bug.

**Comment by rljacob** [comment]
This seems like a build system bug more then an ocean model bug so assigning @jgfouca

**Comment by jonbob** [comment]
This has never worked for any of the mpas components, and probably has to do with the mpas build system and its interactions with the e3sm one. @jgfouca , I'd like to help so we can make the mpas build more tractable for other aspects as well, like using SourceMods correctly... Thanks

**Comment by jgfouca** [comment]
The CIME build system is mostly just a handoff to the build scripts for a component, so this is most likely a problem with the mpas build script (components/mpas-ocean/cime_config/buildlib).

**Comment by worleyph** [comment]
This issue has now been resolved (based on an examination of the build after making changes to ocn_comp_mct.F and re-executing ./case.build).
