### ISSUE TITLE
minor naming issues in MPAS component build subdirectories

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2467]
bld/ocn/source/Makefile.in.ACME
     bld/ocn/source/ocean_cesm_driver/

     bld/ice/source/Makefile.in.ACME
     bld/ice/source/seaice_acme_driver/

I assume that these should be 

     bld/ocn/source/ocean_e3sm_driver/
     bld/ice/source/seaice_e3sm_driver/ 

and that Makefile.in.ACME should be Makefile.in.E3SM for both ???

**Comment by jonbob** [comment]
@worleyph - I'm following up on this, but it will require changes in MPAS as well as E3SM.

**Comment by worleyph** [comment]
This was just an fyi for you ... no urgency on my part. Thanks.

**Comment by worleyph** [comment]
With the changes associated with the move to CMake (and other changes?), this issue has been resolved. The only remaining appearances of "cesm" are in seaice, with a file named

     ice_meltpond_cesm.F90

and a directory named

     mpas-source/src/core_seaice/column/constants/cesm/
