### ISSUE TITLE
Check input data script not downloading missing data from NCAR server

### ISSUE THREAD

**Issue by bishtgautam** [E3SM-Project/E3SM#2472]
All the missing data for the test reported for [this E3SM nightly test](https://my.cdash.org/testDetails.php?test=40975136&build=1487351) 
is available at NCAR’s server at https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/.
But, the data from NCAR's server was not downloaded.

**Comment by jgfouca** [comment]
It was actually just taking so long that Jenkins was timing out. I've confirm the script is working correctly and manually downloaded the files.
