### ISSUE TITLE
Cime issue related to validate_variable_value

### ISSUE THREAD

**Issue by acme-y9s** [E3SM-Project/E3SM#2478]
When I tried to write the land model output variable named 'M_LIVECROOTC_STORAGE_TO_LITTER_FIRE' to the history file (the default is inactive in history file), I got the error message 

ERROR: in validate_variable_value (package Build::Namelist): Variable name hist_fincl2 has a string element that is too long: 'M_LIVECROOTC_STORAGE_TO_LITTER_FIRE' 

Does anyone have any experiences for this?   Thanks!

**Comment by bishtgautam** [comment]
Please give `bishtgautam/lnd/field-name branch` a try.

**Comment by acme-y9s** [comment]
@bishtgautam  Thank you so much. I will try it!

**Comment by acme-y9s** [comment]
@bishtgautam  That worked! Thanks

**Comment by rljacob** [comment]
Leave this open until the problem is fixed on master.
