### ISSUE TITLE
Compact output of mapping of MPI tasks to compute nodes per component

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2485]
Component-specific MPI task to compute node mapping information is output in two locations, once in CAM, where it is truncated after the first 256 MPI tasks, and once in CLM, where it is truncated after the first 100 MPI tasks, and only for these two components. These component-specific data are also written to the e3sm log file.

With PR #2458, we now have global MPI task to compute node mapping information written to the e3sm log. The current component-specific information is not useful as implemented. We could just leave this as is, but all of the following options would be enhancements.

a) remove all component-specific task-to-node mapping information from the log files.

b) use shr_taskmap_write in CAM and in CLM to write out all task-to-node mapping information in the new more compact representation, so no longer truncated.

c) use shr_taskmap_write in CAM and in CLM to write out all task-to-node mapping information in the new more compact representation, and direct the output to the associated component log file.

d) use shr_taskmap_write in CAM, CLM, Mosart, mpas-albany-landice, mpas-ocean, mpas-seaice to write out all task-to-node mapping information in the new more compact representation, and redirect the output to the associated component log file. 

Based on some recently noticed unexpected PE layout issues, (d) can be useful, and it is consistent across the active components.

**Comment by rljacob** [comment]
Does (d) tell you something that you can't get from the info from PR #2458.

I'm wondering if (a) is the better option.  I think the old CAM and CLM routines for this dates back to the multiple-executable days when there was no main that knew everything.

**Comment by worleyph** [comment]
> Does (d) tell you something that you can't get from the info from PR #2458 ?

It tells you the component-specific information. While this can be reverse engineered from knowing the PE layout and the info  from PR #2458 , it is immediately accessible from the output of (d). It might be useful in more easily diagnosing ill-formed PE layouts, as well as tracking component process issues to specific nodes .

@ndkeen was wondering about a further compression of this information: replacing runs, e.g. 0 1 2 3 4 5 with 0-5. I wouldn't want to do this with the global communicator information (yet), but this might be good for the per component information.

So ... I have a mild preference for (d), but would be comfortable with (a) as well. Would want CAM and CLM developers to weigh in before deleting these output.

**Comment by rljacob** [comment]
If the compacting by (d) reduces the number of lines in atm.log and lnd.log compared to current practice, I'm ok with it.

**Comment by worleyph** [comment]
Actually, atm.log and lnd.log will increase in length (one line for each compute node). The old task-to-node mapping information was output to e3sm.log. Even beyond this, the number of lines will increase if more than 256 nodes are used for CAM or more than 100 nodes are used for CLM (since the old logic truncated after this many MPI tasks). And this information has never showed up for the other components. 

So, it sounds like you will vote for (a). Depends then on whether the database developers (@sarat), POCs (@ndkeen ), bug chasers (@amametjanov ), or component developers (@jonbob , @bishtgautam , @singhbalwinder ) have any interest in this. We have lived without it, so this does not have to go in now and people can think about it and play with it. If so, I can then submit the alternative PR to implement (a).

**Comment by mt5555** [comment]
I vote for (d).  I'm the one who put in the truncation many years ago, when we were first running on Mira with O(100,000) MPI tasks and were getting very large log files!

**Comment by worleyph** [comment]
We can also do this by component. If, for example, CAM and CLM developers want this, but ROF and the MPAS developers do not, that is also an option. Or we can put this in, and people can vote it out in the future (so many options :-) ). With the use of the share routine, it is easy to call or not call this.

**Comment by rljacob** [comment]
Pat, what's the path to to test run you did on Cori with all components outputting?  We can look at the logs.

**Comment by worleyph** [comment]
Please look in 

     /global/cscratch1/sd/worleyph/acme_scratch/cori-knl/A_WCYCL1950S_CMIP6_LR_ne30_oECv3_ICG_t2nmap_c/run

I just now verified that everything should be readable (all directories and the files themselves). The task-to-node mapping information is at the beginning of each of the associated component log files.

This was for a low resolution job (ne30_oECv3) and on 60 nodes, so is not representative of a high resolution job, but you can get the idea.

**Comment by worleyph** [comment]
@mt5555 , please note that the previous PR did add task-to-node mapping information for the global communicator (in e3sm.log), so this information is already available. Perhaps this is all you need.

Note that I also (tried) to add support for multi-instance component calls in this PR. Since I have never run E3SM in this manner, I do not know if what I did is useful in this context or not. It is no worse than what was done before however.

**Comment by worleyph** [comment]
@rljacob @mt5555 @bishtgautam @amametjanov @sarats @ndkeen @singhbalwinder @jonbob 

Please also look in 

     /global/cscratch1/sd/worleyph/acme_scratch/cori-knl/A_WCYCL1950S_CMIP6_LR_ne30_oECv3_ICG_t2nmap_d/run

This is the output after a further change to shr_taskmap_write. This would require a new CIME-only PR, but the changes would affect PR #2486 as indicated without further modification. If you look at e3sm.log you'll see the original "verbose" format, but the component logs all use a more compact representation.

Note that the compact representation will be lost if we use a non-block ordering,, e.g. a wrap map.

**Comment by worleyph** [comment]
FYI - new, more compact, format was suggested by @ndkeen (thanks Noel).

**Comment by amametjanov** [comment]
Pat, it'd be useful to add two env_run.xml variables to minimize the output: defaults could be
```
DEBUG | print_glob_task_node_map | print_comp_task_node_map
-------------------------------------------------------------
true  | true                     | true
false | true                     | false
```
which then would allow one to
```
$ ./xmlchange --id print_glob_task_node_map --val false
$ ./xmlchange --id print_comp_task_node_map --val true
```

**Comment by worleyph** [comment]
The first once would touch CIME, requiring a CIME PR. The other one should perhaps be component-specific, one flag ending up in eachcomponent namelists? 

I can just disable these for now in the current PR (except the global output, which is already in there) and we can re-enable if there is sufficient interest. This will be equivalent to option (a) but leave the logic in there for further discussion. 

I'm leaving for exended travel soon and can't do much more before I leave as I have another critical task to complete befor then.

If others have an opinion, please speak up.
