### ISSUE TITLE
calling endrun in CAM can cause misleading error reporting

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2498]
In phys_grid.F90 there are two general ways that endrun is called, e.g. 

       if (pcols < maxblksiz) then
          write(iulog,*) 'pcols = ',pcols, ' maxblksiz=',maxblksiz
          call endrun ('PHYS_GRID_INIT error: phys_loadbalance -1 specified but PCOLS < MAXBLKSIZ')
       endif

and

         else
            if (masterproc) then
               write(iulog,*) "PHYS_GRID_INIT error: opt", opt, "specified, ", &
                  "but could not divide processes into pairs."
            endif
            call endrun()
         endif

endrun is just a renamed version of shr_abort_abort.

     module cam_abortutils
       use shr_sys_mod, only: endrun => shr_sys_abort
       implicit none
       private
       save
       public :: endrun
     end module cam_abortutils

and

     MODULE shr_sys_mod
     ...
        use shr_abort_mod, only: shr_sys_abort => shr_abort_abort

When called in the second fashion, a meaningful message is written to atm.log by masterproc, but then shr_abort_abort prints out nprocs-1 copies of the following to e3sm.log and one copy to atm.log:

      ERROR: Unknown error submitted to shr_abort_abort.

It is probably worthwhile going through and adding real error messages to the endrun calls (at a minimum). However, a single error message is probably preferred are well? Not sure what the design should be, but it took me awhile to think to look in atm.log to find the real error message in atm.log after seeing all of the "Unknown error" messages in e3sm.log .

Asking both Balwinder (for phys_grid) and Rob (for shr_abort_abort in CIME) to think about this and reassign as appropriate (and it you think that this is worth addressing).

**Comment by rljacob** [comment]
Does the first fashion result in a meaningful error message and no extra junk?

**Comment by worleyph** [comment]
@rljacob , I'm not sure. I think that second one will print out the "meaningful" error message many times.

The second is a global ATM error that everyone will notice, and so only one ATM process needs to report it. (This is the one I ran into.) The first one also looks to be a global error (I'll have to verify), which again only needs to be reported once. The first one at least will give a meaningful error message, in both atm.log and e3sm.log .

I can take a whack at cleaning up the endrun calls in phys_grid.F90, if @singhbalwinder does not have the time or interest, looking at each instance. I don't know the history of endrun, but it didn't always point at shr_abort_abort, so perhaps it behaved differently in the distant past. Perhaps shr_abort_abort should not print a message at all if the optional string argument is missing. It looks like this is what is assumed by the way endrun is used (in some locations) in phys_grid.F90?

In any case, cleaning up endrun usage should be coordinated with any decision to modify shr_abort_abort behavior.

**Comment by worleyph** [comment]
edit to previous comment: first line should be

     @rljacob , I'm not sure. I think that the first one will print out the "meaningful" error message many times.

**Comment by singhbalwinder** [comment]
Thanks @worleyph for bringing this up. I also prefer if we have an error message string as an argument to `endrun` call (`call endrun('error message')`) as it avoids printing out less helpful error messages.


There is another way of calling `endrun` with no parenthesis and no argument (`call ensrun`) which might be equivalent to `call endrun ( )`. 

A simple grep revealed there are about 618 instances of `call endrun` and 81 instances of `call endrun()`. I will have to put it on my to-do list for now as I am busy with some other tasks.

**Comment by worleyph** [comment]
@singhbalwinder , 692 instances are a lot to be adding string arguments to. Assuming that each is already associated with an explicit error message, how about the following as a step forward (or a "good enough" solution)?

I'll create a PR in which endrun is defined as having two optional parameters which, if either or both exist, they will be used in a call to shr_sys_abort. If the endrun string parameter is missing, the call to shr_sys_abort will include the string "ERROR: see atm.log for the error description" . 

This will at least indicate where the error occurred (in ATM) and where the true error message should be found . Do you think that this would be an improvement? If so, I'll create the PR (and assign it to you :-) ).
