### ISSUE TITLE
F case not working on Anvil when using PGI compiler

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2503]
Since we are not testing this, perhaps no one cares, but the following both fail on Anvil:

     -compset FC5AV1C -res ne4_ne4 -mach anvil -compiler pgi
     -compset FC5AV1C -res ne30_ne30 -mach anvil -compiler pgi

for 48x1 and 72x1 for the ne4 case and for the default PE layout for the ne30 case (though this apparently has nothing to do with PE layout). In both cases, the failures are seq. faults, e.g.

     [b683:mpi_rank_1784][error_sighandler] Caught error: Segmentation fault (signal 11)

in micro_mg_cam_tend occurring during ATM init phase 2. Based on experiments moving mpi_barriers around with associated write statements, the problem occurs in 

     call post_proc%process_and_unpack()

for ne30, and in

    call post_proc%finalize()

for ne4. In any case, one of these two are likely suspects.

**Comment by singhbalwinder** [comment]
@worleyph , thanks for reporting this issue. Are these errors messages came from a run using debug flags?

**Comment by worleyph** [comment]
@singhbalwinder , no - this is just from using create_newcase with the indicated PE layouts. Note that using Intel works fine. I localized the error "manually".

**Comment by rljacob** [comment]
Noting for the record:   This is with PGI 16.3

**Comment by sarich** [comment]
Running with DEBUG=TRUE doesn't give much more helpful messages, but I see that one of the processes (for the ne4 case) failed with 
[100] [b635:mpi_rank_100][error_sighandler] Caught error: Floating point exception (signal 8)
The other processes all failed with seg faults:
[48] [b634:mpi_rank_48][error_sighandler] Caught error: Segmentation fault (signal 11)
...

**Comment by worleyph** [comment]
@amametjanov ? @rljacob? Should I close this? PGI is not an available option in master at the moment, so this issue is no longer relevant (and can't be worked on without a PGI option for Anvil)?

**Comment by worleyph** [comment]
@amametjanov ? @rljacob ?

**Comment by amametjanov** [comment]
Yes, I think it's okay to close. My vote is to get nightly PGI testing to work on Compy.

**Comment by worleyph** [comment]
If we ever add a PGI option for Anvil, we can revisit, but it seems that the decision was made implicitly when the PGI option for Anvil was dropped. Thanks.

**Comment by rljacob** [comment]
Yes Compy is the priority for PGI.
