### ISSUE TITLE
Remove the restriction of MPI use for Single-Column Model

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/E3SM#2512]
In the components/cam/bld/configure file, at line 1211.
```
1210 if ($scam eq 'ON' and $dyn_pkg eq 'eul' and $spmd ne 'OFF') {
1211     die <<"EOF";
1212 **  ERROR: SCAM mode assumes a serial build.
1213 **         Requested parallel modes are: spmd=$spmd  smp=$smp
1214 EOF
```
It prevents the use of MPI library for SCAM cases and let them run in a serial mode.  However SCAM can be compiled and run successfully with MPI and MPI-serial respectively and their results are bit-for-bit on Titan. So this restriction could be removed.   

Any other reasons I missed to prevent SCAM using MPI here?

**Comment by rljacob** [comment]
Yes I'm pretty sure that can be removed.

**Comment by rljacob** [comment]
@minxu74 What hash were you using?  It looks like that block of code was removed in:  https://github.com/E3SM-Project/E3SM/pull/2267

**Comment by rljacob** [comment]
Closing unless this is still a problem on master.
