### ISSUE TITLE
logger.info changed to logger.debug in case_run.py

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2540]
In PR #2356 -

     Single process operations within CIME before and after model execution
     can take significant time on some systems, for example, on Cori-KNL.
     logger.info calls with timestamps are added to improve the ability to
     diagnose where these costs are occurring.

The calls to logger.info have since been changed to calls to logger.debug, removing this information from production jobs, so we are back to where we started. 

@ndkeen, you and I were most interested in this information. Do we want to argue that this be restored to what it was previously? I don't know what discussion led to this change - somebody thought that it was ugly or was there a technical reason?

**Comment by jgfouca** [comment]
@worleyph , the CESM folks didn't want it. I suppose we can just put if (model == "e3sm") around all of it.

**Comment by jgfouca** [comment]
This was fixed a while ago.
