### ISSUE TITLE
Bug in check_energy.F90 (IEFLX output) 

### ISSUE THREAD

**Issue by kaizhangpnl** [E3SM-Project/E3SM#2548]
There is a bug in check_energy.F90 that will potentially affect the IEFLX output. "ieflx(:ncol)" should be "ieflx" in the outfld call. In the original code, on machines where pcols is not equal to ncol, a machine-dependent value (zero or NaN) will be assigned to a certain grid boxes. This resulted in a bfb diff when https://github.com/E3SM-Project/E3SM/commit/c636144c9561912c73ed3138f4ab539308e53166  was merged and the chunk assignments changed. A bugfix PR was issued: https://github.com/E3SM-Project/E3SM/pull/2545

**Comment by worleyph** [comment]
FYI:

      on machines where pcols is not equal to ncol

This is not a machine-specific issue. Rather, the number of processes and threads used with a given grid resolution will determine whether ncol == pcols. In practice, it is rare for ncol to be equal to pcols for all chunks, and at scale it is not true for any chunk.
