### ISSUE TITLE
Automated input data download does not work for multi-instance runs

### ISSUE THREAD

**Issue by singhbalwinder** [E3SM-Project/E3SM#2562]
I recently found out that scripts to download missing input data do not work for multi-instance runs. In my multi-instance run, I had a different `ncdata` file for each instance. Launching `check_input_data` downloads only the `ncdata` file for the last instance. I looked into the script and it looks like `check_input_data` script download files mentioned in  `*.input_data_list` (e.g. `cam.input_data_list`) and `*.input_data_list`  file captures only the file from the last instance. 

I am not sure what would be the best way to solve this issue. One solution that I can think of is to add a "ninst" (total number of instances) loop which creates `*.input_data_list` files for each instance and then `check_input_data` scripts go through all these files to download missing data.

**Comment by singhbalwinder** [comment]
Hi @jgfouca , I tentatively assigned you for this issue, please feel free to reassign.

**Comment by jgfouca** [comment]
@singhbalwinder , can you file this in https://github.com/ESMCI/cime ?

**Comment by singhbalwinder** [comment]
Sure. I will create an issue at ESMCI.

**Comment by jgfouca** [comment]
This was fixed a while ago by a CIME merge last fall.
