### ISSUE TITLE
MPAS IO Error: Bad return value from PIO (E3SM, Edison, quick start guide, MPAS-seaice)

### ISSUE THREAD

**Issue by chengdang** [E3SM-Project/E3SM#2584]
I'm testing E3SM on Edison following the instructions by E3SM Quick Start: https://e3sm.org/model/running-e3sm/e3sm-quick-start/, using run_e3sm script with the default set up:

`./run_e3sm.DECKv1b_piControl.ne30_oEC.edison.csh`

The model runs successfully and reproduces the atmospheric global integrals of original piControl simulation, as instructed.

However, under the run directory, there are numerous MPAS-seaice error log files:

```
$USER@edison11:/global/cscratch1/sd/$USER/E3SM_simulations/
20180420.DECKv1b_piControl.ne30_oEC.edison/run$ more log.seaice.0000.err
----------------------------------------------------------------------
  Beginning MPAS-seaice Error Log File for task       0 of     640
    Opened at 2018/10/18 15:01:43
----------------------------------------------------------------------
 
ERROR: MPAS IO Error: Bad return value from PIO
```

Is this caused by an unsupported PIO library? how to fix this?  Thanks.

**Comment by jonbob** [comment]
@chengdang - can you please tell me your username on edison so I can try to look at the output? Thanks!

**Comment by jonbob** [comment]
Thanks @chengdang. I think you'll have to change permissions for /global/cscratch1/sd/cdang/... to allow us to see your output

**Comment by chengdang** [comment]
@jonbob Permission changed. Please check if you can see the files. Thank you.

**Comment by jonbob** [comment]
Thanks so much -- I can see it all now

**Comment by jonbob** [comment]
@chengdang - how old is your codebase?

**Comment by chengdang** [comment]
@jonbob hmmm, I stopped using this NERSC account about 3 years ago, and it's been reactivated for about 2 weeks. So if there were upgrades that a user should perform, I have not done any.

**Comment by rljacob** [comment]
Jon means the E3SM code.    Jon, @chengdang is using the run script from e3sm.org so its the head of the maint-1.0 branch.

**Comment by chengdang** [comment]
@rljacob  thanks for clarifying this.

**Comment by jonbob** [comment]
@rljacob - do we test that run script?

**Comment by jonbob** [comment]
@rljacob - the run_e3sm script doesn't use the testmods_dirs/allactive/v1cmip6/ settings, which among other things sets PIO_TYPENAME=netcdf. So if I build this case by hand it runs with no issues, but @chengdang gets a failure using the e3sm script

**Comment by rljacob** [comment]
I think the script makes the same changes as those v1cmip6 settings.  We don't test that particular script.  But @chengdang did not have a fatal error (which would happen if there was a netcdf issue).  The model ran fine but there were these MPAS seaice error log files.   Do you see those?

**Comment by jonbob** [comment]
No, I don't get those errors because the PIO_TYPENAME for seaice is set to netcdf when using those v1cmpi6 settings and pnetcdf when using run_e3sm

**Comment by jonbob** [comment]
So I guess the run_e3sm script is incomplete? Is there a reason that it does not use the same compset settings and tries to duplicate the v1cmpi6 settings in a different way? That would seem like a bad approach, meaning any changes would have to be made to both the testmods_dir and run_e3sm script?

**Comment by rljacob** [comment]
The run_e3sm script on e3sm.org is only for edison where, except for these annoying error messages, pnetcdf works.  At least it does not trigger the fatal read errors on atmosphere input data that are the usual problem.  The v1cmip6 settings are for running that case on any machine.

@chengdang to get rid of those errors, uncomment lines 1206-1208 in the run script or follow the "Running Manually" instructions on the e3sm.org website.

**Comment by chengdang** [comment]
@rljacob @jonbob  thanks for the instructions and explanations.

**Comment by jonbob** [comment]
@rljacob - how do you want to handle this issue? Can we close it?

**Comment by rljacob** [comment]
One thing still left:  was the model run really successful?  @chengdang said it was but there are these error messages.  Was all the expected output there?

**Comment by chengdang** [comment]
@rljacob  I was wondering about the same thing. I only checked the atm log file following section "Verifying your results" on https://e3sm.org/model/running-e3sm/e3sm-quick-start/, and they matched.

I don't think the sea ice log file is complete. It shows that the coupling is completed within certain time intervals, while there are no numerical outputs in ice log. So I guess even if there is no successful output from one model component, the coupled E3SM simulation still continues? Do all model components output data at the same time steps?

**Comment by jonbob** [comment]
@rljacob - it looks like the run completed, but not quite cleanly? All components created data successfully (@chengdang , the seaice output ends up in history and analysis member files) and all component logs show successful completion, but only three of the logs gzipped? The batch output says the model execution finished and it looks like it still had queue time left. Except for the logs not being zipped, everything looks fine.

**Comment by chengdang** [comment]
@jonbob I see. I gzipped those three files manually to check the output, they were zipped by default.

**Comment by jonbob** [comment]
@chengdang - that's good news. It means the run finished just fine, despite the seaice errors.

**Comment by jonbob** [comment]
@rljacob - ok to close?

**Comment by rljacob** [comment]
Yes
