### ISSUE TITLE
Configurations with the oRRS30to10v3wLI grid without ice shelf melt fluxes fail

### ISSUE THREAD

**Issue by darincomeau** [E3SM-Project/E3SM#2606]
When running with the oRRS30to10v3wLI grid with ice shelf cavities, but without ice shelf melt fluxes, i.e.

config_land_ice_flux_mode = 'pressure_only',

the simulation dies in the ocean after 6 hours with the following in log.ocean.*.err files:

CRITICAL ERROR: ERROR: State validation failed.

**Comment by xylar** [comment]
@mark-petersen, Could it be that the spin-up for this initial condition wasn't long enough and there are still waves to dissipate or something else like that?  @darincomeau, could you paste the time series for CFL below to see if there's any indication of a violation there?

**Comment by xylar** [comment]
Actually, there's probably no global stats available with such an early crash.  We'd probably need to run again with global stats per time step to see what's breaking.

**Comment by darincomeau** [comment]
I've reran my test with globalStatsOutput set to hourly. Here are the CFL numbers:

data:

 CFLNumberGlobal = 0.10438274862216, 0.164277406834342, 0.296548067281053,
    0.335961086963873, 0.421937463393641, 1.28407714792356 ;

**Comment by xylar** [comment]
Yeah, 0.42 is already dangerous if I remember right.  My guess is that we need to do a longer spin-up with Rayleigh damping and/or a smaller time step.  @mark-petersen, what was the spin-up procedure in this case?

**Comment by darincomeau** [comment]
I'm guessing we should hold off on starting the 30to10wLI with melt fluxes until this is resolved? I'm not sure who was planning to run that (@stephenprice ?)

**Comment by rljacob** [comment]
What changed?   SMS.T62_oRRS30to10v3wLI.GMPAS-IAF is part of our high res test suite and last passed back in late October with master hash  0757e202255
https://my.cdash.org/viewTest.php?onlypassed&buildid=1551671

**Comment by darincomeau** [comment]
@xylar that may be it. @rljacob the sea ice initial condition was changed for this grid in #2645.

**Comment by rljacob** [comment]
Then this issue does not cover the fails for the above test that started appearing around Oct 30?

**Comment by rljacob** [comment]
I started a new issue for the test suite fail.  https://github.com/E3SM-Project/E3SM/issues/2654

**Comment by jonbob** [comment]
I can get this to run by simply removing the seaice disk initial condition -- my test successfully ran 20 days last night. With the default seaice IC, I was seeing a negative cell thickness after about 9 hours of simulation time -- so I'm guessing there's one or two cells that maintain stability just from having some inflow from the melt fluxes.

**Comment by darincomeau** [comment]
Following @jonbob 's lead, I've got two runs out two months so far on Theta, with and without melt fluxes (GMPAS-IAF and GMPAS-IAF-ISMF). The only change I made was to reduce the sea ice initial condition boundary from +/- 75&deg; to +/-85&deg;:
`` config_initial_latitude_north = 85.0``
``config_initial_latitude_south = -85.0``
I'll try to run this out for a year to see if the instability arises.
