### ISSUE TITLE
Latest E3SM commit breaks build on IC: issue with ice_comp_mct.f90

### ISSUE THREAD

**Issue by bradyrx** [E3SM-Project/E3SM#2627]
The current bleeding edge commit (067f39e99fd7fb243f87720d5008910cf7314980) breaks ./case.build for both wolf and grizzly (note however, that this could be related to a less recent commit).

See `/lustre/scratch3/turquoise/rileybrady/ACME/cases/GMPAS-IAF.test4/bld/ice.bldlog.181115-121031`:

```
ice_comp_mct.f90:834:63:

         call seaice_timestep(domain, domain % clock, itimestep)
                                                               1
Error: Missing actual argument for argument 'ierr' at (1)
make[2]: *** [ice_comp_mct.o] Error 1
make[2]: Leaving directory `/lustre/scratch3/turquoise/rileybrady/ACME/cases/GMPAS-IAF.test4/bld/ice/source/seaice_acme_driver'
make[1]: *** [drver] Error 2
make[1]: Leaving directory `/lustre/scratch3/turquoise/rileybrady/ACME/cases/GMPAS-IAF.test4/bld/ice/source'
make: *** [all] Error 2
ERROR: mpas-seaice buildlib cd /lustre/scratch3/turquoise/rileybrady/ACME/cases/GMPAS-IAF.test4/bld/ice/source; make all CORE=seaice ESM=ACME DRIVER=seaice_acme_driver GEN_F90=true ROOT_DIR="/lustre/scratch3/turquoise/rileybrady/ACME/cases/GMPAS-IAF.test4/bld/ice/source" failed: 512
```

The `ierr` argument was removed from `ice_comp_mct.f90` which is required when calling the`seaice_timestep` subroutine.

@jonbob , it looks like the change was made in 829671357a7209997206ff0df268ccd897e42d10. Let me know if I'm missing something here.

**Comment by xylar** [comment]
For what it's worth, I saw the same error on Edison when testing https://github.com/MPAS-Dev/MPAS-Model/pull/109#issuecomment-437237210. This went away when I rebased onto e3sm/develop.

**Comment by jonbob** [comment]
@bradyrx - can you check that this is still an issue? You may have to make sure your submodules are up-to-date as well, since this issue is due to a mismatch between versions of e3sm and mpas-source. Thanks, and sorry I didn't see this sooner -- please just assign these issues to me next time...

**Comment by worleyph** [comment]
FYI - perhaps irrelevant, but changes to the MPAS driver files, like ice_comp_mct.f90, are not recognized by the build system, so you have to do a build clean (of that component, at least) for changes to take effect. See Issue #2466 .

**Comment by bradyrx** [comment]
@jonbob, good call. My original issue occurred when I paired the most recent E3SM commit with @pwolfram's LIGHT branch, which is not up to date with the MPAS submodule. Using the most recent E3SM + most recent MPAS solves this issue.
