### ISSUE TITLE
Topography smoothing in dycore is broken

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/E3SM#2632]
The dycore includes a (somewhat hidden) option to apply Laplacian smoothing to the surface geopotential (PHIS) field. This is only used when creating a new topography input file, but is critical to producing new atmosphere grids. This option is currently broken for two reasons. First, the namelist option to turn on the smoothing is missing from namelist_defaults.xml. Second, when the namelist option is properly added, the code will segfault because the arrays used to do the smoothing are deallocated before they are used. I have a fix for this already ([https://github.com/E3SM-Project/E3SM/tree/brhillman/atm/fix-topo-smooth](https://github.com/E3SM-Project/E3SM/tree/brhillman/atm/fix-topo-smooth)), and will submit a PR when I confirm that tests pass.

**Comment by rljacob** [comment]
I am liking the clear description of this bug.  Not the existence of the bug.

**Comment by brhillman** [comment]
@mt5555 should I implement the fix for this, or have you removed this code from the dycore already in favor of using stand-alone HOMME?

**Comment by mt5555** [comment]
Lets go with the stand-alone HOMME version.  that code is done, and I will submit the PR soon.

**Comment by mt5555** [comment]
fixed via PR #2673
