### ISSUE TITLE
gen_mapping_files in cime/tools/mapping is inconsistent with v2 grids

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/E3SM#2634]
For new grids, we are transitioning to mapping files generated using TempestRemap, and ncremap can be used to generate all needed mapping files between components. The tool in `cime/tools/mapping/gen_mapping_files` is inconsistent with this approach, and might be misleading to anyone perusing the source at this point. The script used here should probably be adapted to be consistent with our new approach. Alternatively, this directory could be dropped, since I think all of this is now supported in ncremap within NCO.

**Comment by rljacob** [comment]
Remember that CIME contains tools used by CESM and E3SM and potentially more models.  E3SM is still using the tools in runoff_to_ocean.  You could maybe update the README to point people to ncremap.
