### ISSUE TITLE
Domain generation code exists in two different places

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/E3SM#2635]
The code to generate domain files exists in two different locations within our source tree: `cime/tools/mapping/gen_domain_files` and `components/clm/tools/shared/gen_domain`. At the moment these codes seem to differ by only a CPP directive or two, but PR #2633 makes some updates to the `gen_domain` tool located at `cime/tools/mapping/gen_domain_files` to allow the tool to work with mapping files generated using TempestRemap. This will cause these two codes to diverge, and rather than make sure both versions are up to date (and to prevent confusion in the future) I propose we remove the `gen_domain` source from the CLM component source tree and only use the source within the CIME source tree to generate domain files (especially since these files do not seem to be used by only the land model).

**Comment by rljacob** [comment]
@thorntonpe any concerns about removing above code from ELM?
