### ISSUE TITLE
why does it take so long to build mpaso (case GMPAS-IAF, grid T62_oEC60to30v3)

### ISSUE THREAD

**Issue by chengdang** [E3SM-Project/E3SM#2644]
I'm trying to build a G-case on Edison created by 

> ./create_newcase --case GMPAS-IAF-test --compset GMPAS-IAF --res T62_oEC60to30v3 --mach edison --project m1795

While it takes forever (> 40 minutes) to build mpaso so I terminate the build, is this normal?
Is there anything wrong with my case setup? 
Thank you.

**Comment by jonbob** [comment]
Hi @chengdang - yes, the build on edison takes a very long time. Please be patient and see if it completes successfully? And if not, please post the output here. I'll try to look into why it takes so long, but we all suffer through that. And not just mpas-o, but almost all the components...

**Comment by worleyph** [comment]
This is really fuzzy, but I believe that we used to have the same problems on Titan due to the build taking place in the lustre scratch space. Having acme_scratch/.../bld be in home directory space could speed up the compiliation (significantly?), at the cost of filling up your home space allocation quickly. If important to you, you might try specifying a different build location. (Someone else will have to tell you how to do this, but I know that you can specify this.)

**Comment by jonbob** [comment]
@chengdang - following up on @worleyph's suggestion, you can try changing EXEROOT in env_build. But it takes some effort to get the scripts to correctly point to one place to build and another to run...

**Comment by chengdang** [comment]
@jonbob @worleyph   Thank you. In this case, I'll wait longer to see if it build successfully for now. If not, I'll post more information, and perhaps working on changing the directory...

**Comment by chengdang** [comment]
Yeah, I terminate the build after 4 hours. I’ll try build again tomorrow....

**Comment by tangq** [comment]
I had similar slowness issue on Edison before. The exact cause is still a mystery...but one likely hypothesis is that the free space on the scratch disk is too low. Have you reported the issue to NERSC help desk?

**Comment by chengdang** [comment]
Not yet, that is a good idea. I’ll report this issue now. Thanks!

So usually how long does it take to build a G case? assuming there is enough space on scratch. Would 1 hour be a reasonable expectation?

**Comment by tangq** [comment]
I've never built a G case, but for fully coupled A case it is usually less than 1 hour. I would imagine G cases should build faster than A cases.

**Comment by jonbob** [comment]
@chengdang - the G-case build also takes about an hour. The whole E3SM build happens in parallel, so whichever component takes longest sets the time for the build (mostly). There is one other possibility -- depending on how you have git set up, it may be looking for a passphrase for submodules during the build. If so, you would see something like this:
````
Creating test directory /global/cscratch1/sd/jonbob/acme_scratch/edison/SMS.T62_oEC60to30v3.GMPAS-IAF.edison_intel.20181129_102531_47hc3q
RUNNING TESTS:
  SMS.T62_oEC60to30v3.GMPAS-IAF.edison_intel
Starting CREATE_NEWCASE for test SMS.T62_oEC60to30v3.GMPAS-IAF.edison_intel with 1 procs
Finished CREATE_NEWCASE for test SMS.T62_oEC60to30v3.GMPAS-IAF.edison_intel in 7.790812 seconds (PASS)
Starting XML for test SMS.T62_oEC60to30v3.GMPAS-IAF.edison_intel with 1 procs
Finished XML for test SMS.T62_oEC60to30v3.GMPAS-IAF.edison_intel in 3.664605 seconds (PASS)
Starting SETUP for test SMS.T62_oEC60to30v3.GMPAS-IAF.edison_intel with 1 procs
Finished SETUP for test SMS.T62_oEC60to30v3.GMPAS-IAF.edison_intel in 12.774891 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS.T62_oEC60to30v3.GMPAS-IAF.edison_intel with 1 procs
Finished SHAREDLIB_BUILD for test SMS.T62_oEC60to30v3.GMPAS-IAF.edison_intel in 1305.372747 seconds (PASS)
Starting MODEL_BUILD for test SMS.T62_oEC60to30v3.GMPAS-IAF.edison_intel with 4 procs
Enter passphrase for key '/global/homes/j/jonbob/.ssh/id_rsa': 
````
If you aren't watching for it, that last line can get lost -- but some part of the parallel build is waiting for a response and won't complete without one....

For what it's worth, i just tested a G-case build on edison09 and it completely successfully in about 40 minutes

**Comment by worleyph** [comment]
@philipwjones put in a workaround for the passphrase request issue. Do 

     cd components/mpas-source/src/core_ocean
    ./get_cvmix.sh
    ./get_BGC.sh

You'll be asked for a passphre for each of the two scripts, but then you won't be asked again during the build.

**Comment by chengdang** [comment]
@jonbob  Thank you! I think this is the reason. During my test, the passphrase requests appear along with multiple messages that indicate successful components built, which make sense since the build is processed in parallel. 

I executed the get_cvmix.sh and get_BGC.sh before the case build follows @worleyph, then no passphrase requests show up during e3sm build. I'm able to build a G-case within reasonable time now.

Thank you.

**Comment by jonbob** [comment]
@chengdang - OK to close this?

**Comment by chengdang** [comment]
@jonbob  sure. Thank you!

**Comment by jonbob** [comment]
Thanks @chengdang - glad we figured it out
