### ISSUE TITLE
preqx_cxx is not a target

### ISSUE THREAD

**Issue by oksanaguba** [E3SM-Project/E3SM#2648]
In the line below preqx_cxx needs to be replaced with preqx_kokkos.

https://github.com/E3SM-Project/E3SM/blob/d6b52862bd04daecdaa71aba23d4952ae16d4b90/components/cam/bld/configure#L2912

**Comment by bartgol** [comment]
@oksanaguba I'm fixing preqx_kokkos build issue (related to the copies of files in preqx/share). I can add this to the list of commit, and have one branch fix the preqx_kokkos altogether. Is that ok with you?

**Comment by oksanaguba** [comment]
sure, thanks! then i will try to build your branch to see if the right directives are picked up.
