### ISSUE TITLE
E3SM compiling error with MPAS-seaice code in development

### ISSUE THREAD

**Issue by chengdang** [E3SM-Project/E3SM#2657]
In /components/mpas-seaice/driver/ice_comp_mct.F, seaice_timestep is called with 4 arguments that matches the definition of seaice_timestep in released MPAS-seaice source code

`832         call seaice_timestep(domain, domain % clock, itimestep, ierr)`

While I am trying to compile E3SM with MPAS-seaice code in development (https://github.com/MPAS-Dev/MPAS-Model/tree/seaice/develop), seaice_timestep is modified to include only three arguments.

`seaice_timestep(domain, clock, itimestep)`

Attempting to complie E3SM with source code in development raises error:

```
ice_comp_mct.f90(829): error #6784: The number of actual arguments cannot be greater than the number of dummy arguments.   [SEAICE_TIMESTEP]
        call seaice_timestep(domain, domain % clock, itimestep, ierr)
-------------^
compilation aborted for ice_comp_mct.f90 (code 1)
Makefile:21: recipe for target 'ice_comp_mct.o' failed
make[2]: *** [ice_comp_mct.o] Error 1

```

Model build with "ierr" argument removed in ice_comp_mct.F is sucessful. Not sure if this will raise error during model run yet.

**Comment by jonbob** [comment]
@chengdang - I think your E3SM codebase and submodules may be out of alignment. Did you run "git submodule update --init"?
