### ISSUE TITLE
case_submit.py has an inaccurate test for continuing a run

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#2668]
The test for making sure continue_run makes sense in case_submit.py is not really valid. There's a line that uses successful completion of a previous run as the test instead of checking for valid pointer files. That section of the script looks like:
```
    # Check if CONTINUE_RUN value makes sense
    if job != "case.test" and case.get_value("CONTINUE_RUN"):
        rundir = case.get_value("RUNDIR")
        caseroot = case.get_value("CASEROOT")
        expect(os.path.isdir(rundir),
               "CONTINUE_RUN is true but RUNDIR {} does not exist".format(rundir))
        expect(len(glob.glob(os.path.join(rundir, "*.nc"))) > 0,
               "CONTINUE_RUN is true but this case does not appear to have been run before (no .nc files in RUNDIR)")
        expect(does_file_have_string(os.path.join(caseroot, "CaseStatus"), "case.run {}".format(CASE_SUCCESS)),
               "CONTINUE_RUN is true but this case does not appear to have ever run successfully")
````
The last line either should be modified to really check for the requirements of a continued run or removed.

**Comment by jgfouca** [comment]
@jonbob , can you file this ticket here: https://github.com/ESMCI/cime

**Comment by jonbob** [comment]
sure -- I'll do that right now

**Comment by jonbob** [comment]
Moved to [ESMCI Issue #2954](https://github.com/ESMCI/cime/issues/2954)
