### ISSUE TITLE
create_test is not python3-compatible

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/E3SM#2677]
It appears as though `create_test` is not compatible with (at least certain versions of) Python 3. When using `create_test` with Python 3.6.6, I get the following:
```
Traceback (most recent call last):
  File "./create_test", line 632, in <module>
    _main_func(__doc__)
  File "./create_test", line 610, in _main_func
    parse_command_line(sys.argv, description)
  File "./create_test", line 440, in parse_command_line
    test_names.sort(cmp=get_tests.sort_by_time)
TypeError: 'cmp' is an invalid keyword argument for this function
```
The problem seems to be that for E3SM, the `cmp` argument to `list.sort()` is being used, which is valid in Python 2.x but not in Python 3.6.6:
```
    # for e3sm, sort by walltime
    if model == "e3sm":
        if args.walltime is None:
            test_names.sort(cmp=get_tests.sort_by_time)
        else:
            test_names.sort()
```
For reference, from my Python 3.6.6 environment:
```
>>> help(list.sort)
Help on method_descriptor:

sort(...)
    L.sort(key=None, reverse=False) -> None -- stable sort *IN PLACE*
```
but from a Python 2.7.9 environment:
```
>>> help(list.sort)
Help on method_descriptor:

sort(...)
    L.sort(cmp=None, key=None, reverse=False) -- stable sort *IN PLACE*;
    cmp(x, y) -> -1, 0, 1
```
It would be nice to make this agnostic to Python version so that we do not have to load specific modules before issuing any CIME or E3SM-specific commands. A simple fix here would be to remove the conditional that sorts E3SM tests by walltime, but I'm not sure what the implications of that would be.

**Comment by jgfouca** [comment]
This is fixed on current master. I accidentally pushed the fix directly to master and appear to have lost the ability to reset the master branch.

**Comment by jgfouca** [comment]
Fixed by https://github.com/E3SM-Project/E3SM/commit/d0241119c45f6864d90fdee50dabccec3bdfa865

**Comment by brhillman** [comment]
Awesome, thanks @jgfouca confirmed this now works for me!
