### ISSUE TITLE
Compsets with ISMF failing ERS tests

### ISSUE THREAD

**Issue by darincomeau** [E3SM-Project/E3SM#2702]
The following compsets with ice shelf melt fluxes on (ISMF) are failing ERS tests:

A_WCYCL1850-DIB-ISMF_CMIP6
GMPAS-DIB-IAF-ISMF

@mark-petersen has confirmed that in MPAS-Ocean standalone, configurations with ice shelf melt fluxes on do pass exact restart tests (for the oEC60to30v3wLI grid).

**Comment by mark-petersen** [comment]
I tested MPAS-Ocean stand-alone, using ice shelf cavities and melt fluxes on, but for the QU240 resolution.  I get exact match between 12 hour restart files, after a single 12 hour run compared with two sequential 6-hour runs.

Do you know if the E3SM ERS tests pass when melt fluxes are off, i.e. with the flag
`config_land_ice_flux_mode = 'pressure_only'`

**Comment by jonbob** [comment]
@mark-petersen - I'll test that

**Comment by jonbob** [comment]
@mark-petersen - it does pass in E3SM when melt fluxes are off

**Comment by mark-petersen** [comment]
Could you point me to the directories for those tests so I can poke around?

**Comment by jonbob** [comment]
Sure. On anvil there's a test at /lcrc/group/acme/jwolfe/acme_scratch/anvil/ERS.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel.20190122_114959_txleb6 that has both salinity restoring and the melt fluxes off. I had used this same test with melt fluxes on previously

**Comment by mark-petersen** [comment]
@xylar I looked through every variable that is used when melt fluxes are on in MPAS-O:
`src/core_ocean/shared/mpas_ocn_surface_land_ice_fluxes.F`

I'm trying to find a variable that:
1. should be added to coupler restart.
2. is passed through the coupler but with a delay.
3. should be in MPAS-O restart
4. is uninitialized.

We can then retest the exact restart test with the suspicious variables in the coupler restart or ocean restart file.

The only suspicious variable I found was `landIceSurfaceTemperature`, which is used as `iceTemperature` in computing melt fluxes, but appears to be uninitialized when run in E3SM.  It is in the `forcing_data` stream, and all other variables in that stream are passed through the coupler.

@xylar could you look at `landIceSurfaceTemperature` in the MPAS-Ocean code.  Do you agree that it is used but might be uninitialized in E3SM?  That variable appears nowhere in E3SM.

I looked at all the other variables on the RHS of these lines, but I think they are all known at a restart or computed in `mpas_ocn_diagnostics.F`.
```
surfaceStress(iEdge) = surfaceStress(iEdge) + topDrag(iEdge)
surfaceThicknessFlux(iCell) = surfaceThicknessFlux(iCell) + landIceFreshwaterFlux(iCell) / rho_sw
tracersSurfaceFlux(1, iCell) = tracersSurfaceFlux(1, iCell) + landIceHeatFlux(iCell)/(rho_sw*cp_sw)

subroutine compute_HJ99_melt_fluxes(...
      outFreshwaterFlux(iCell) = rho_sw*oceanSaltTransferVelocity(iCell) &
        * (oceanSalinity(iCell)/outInterfaceSalinity(iCell) - 1.0_RKIND)

      ! According to Jenkins et al. (2001), the temperature fluxes into the ocean are:
      !   1. the advection of meltwater into the top layer (or removal for freezing)
      !   2. the turbulent transfer of heat across the boundary layer, based on the termal driving
      outOceanHeatFlux(iCell) = cp_sw*(outFreshwaterFlux(iCell)*outInterfaceTemperature(iCell) &
        - rho_sw*oceanHeatTransferVelocity(iCell)*(oceanTemperature(iCell)-outInterfaceTemperature(iCell)))

      ! Since we're considering only melting and ignoring diffusion,
      ! the ice loses heat simply by the loss of ice mass at the prescribed
      ! (surface?) ice temperature
      outIceHeatFlux(iCell) = -cp_land_ice*outFreshwaterFlux(iCell)*iceTemperature(iCell)
```

**Comment by xylar** [comment]
@jonbob, it looks like something went weird with permissions.  Could you chmod the NetCDF files in:
```
/lcrc/group/acme/jwolfe/acme_scratch/anvil/ERS.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel.20190122_114959_txleb6/run/
```
so I can take a look at them?

**Comment by xylar** [comment]
@mark-petersen asked:
> Do you know if the E3SM ERS tests pass when melt fluxes are off, i.e. with the flag
> config_land_ice_flux_mode = 'pressure_only'

No, it appears that melt fluxes are on:
```
config_land_ice_flux_mode = 'standalone'
```

It would be useful to do a test with `config_land_ice_flux_mode = 'pressure_only'` to try to isolate the restart issue to the melt fluxes themselves.

Could someone point me to instructions on how to run one of these test cases myself?

**Comment by xylar** [comment]
@rljacob wrote:
> Does this compset send a new field through the coupler? It may need to be in the coupler restart and isn't.

No, for now the melt fluxes are computed internally in MPAS-O and the coupler isn't involved so that shouldn't the the issue here.

**Comment by xylar** [comment]
Could someone help me with running the test myself.  I'm getting a bunch of errors:
<details>
<summary> Error log </summary> <p>

```
Starting RUN for test ERS.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel with 1 proc on interactive node and 720 procs on compute nodes
Finished RUN for test ERS.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel in 26.470892 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /lcrc/group/acme/xylar/acme_scratch/anvil/ERS.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel.20190125_063508_dcka8r
    Errors were:
        Model mpassi missing file graph720 = '/home/ccsm-data/inputdata/ice/mpas-cice/oEC60to30v3wLI/mpas-cice.graph.info.170905.part.720'
          Model mpaso missing file graph720 = '/home/ccsm-data/inputdata/ocn/mpas-o/oEC60to30v3wLI/mpas-o.graph.info.170328.part.720'
          Model mpassi missing file graph720 = '/home/ccsm-data/inputdata/ice/mpas-cice/oEC60to30v3wLI/mpas-cice.graph.info.170905.part.720'
        FAIL: Repo 'https://web.lcrc.anl.gov/public/e3sm/inputdata/' does not have file 'https://web.lcrc.anl.gov/public/e3sm/inputdata/ice/mpas-cice/oEC60to30v3wLI/mpas-cice.graph.info.170905.part.720'
        Reason:
        Spider mode enabled. Check if remote file exists.
        --2019-01-25 06:47:17--  https://web.lcrc.anl.gov/public/e3sm/inputdata/ice/mpas-cice/oEC60to30v3wLI/mpas-cice.graph.info.170905.part.720
        Resolving web.lcrc.anl.gov... 140.221.74.23
        Connecting to web.lcrc.anl.gov|140.221.74.23|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        Remote file does not exist -- broken link!!!
        
          Model mpaso missing file graph720 = '/home/ccsm-data/inputdata/ocn/mpas-o/oEC60to30v3wLI/mpas-o.graph.info.170328.part.720'
        FAIL: Repo 'https://web.lcrc.anl.gov/public/e3sm/inputdata/' does not have file 'https://web.lcrc.anl.gov/public/e3sm/inputdata/ocn/mpas-o/oEC60to30v3wLI/mpas-o.graph.info.170328.part.720'
        Reason:
        Spider mode enabled. Check if remote file exists.
        --2019-01-25 06:47:18--  https://web.lcrc.anl.gov/public/e3sm/inputdata/ocn/mpas-o/oEC60to30v3wLI/mpas-o.graph.info.170328.part.720
        Resolving web.lcrc.anl.gov... 140.221.74.23
        Connecting to web.lcrc.anl.gov|140.221.74.23|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        Remote file does not exist -- broken link!!!
        
        
        Could not connect to svn repo 'https://acme-svn2.ornl.gov/acme-repo/acme/inputdata'
        This is most likely either a credential, proxy, or network issue .
        To check connection and store your credential run 'svn ls https://acme-svn2.ornl.gov/acme-repo/acme/inputdata' and permanently store your password
          Model mpassi missing file graph720 = '/home/ccsm-data/inputdata/ice/mpas-cice/oEC60to30v3wLI/mpas-cice.graph.info.170905.part.720'
        FAIL: SVN repo 'https://acme-svn2.ornl.gov/acme-repo/acme/inputdata' does not have file 'https://acme-svn2.ornl.gov/acme-repo/acme/inputdata/ice/mpas-cice/oEC60to30v3wLI/mpas-cice.graph.info.170905.part.720'
        Reason:
        svn: OPTIONS of 'https://acme-svn2.ornl.gov/acme-repo/acme/inputdata/ice/mpas-cice/oEC60to30v3wLI/mpas-cice.graph.info.170905.part.720': could not connect to server (https://acme-svn2.ornl.gov)
        
          Model mpaso missing file graph720 = '/home/ccsm-data/inputdata/ocn/mpas-o/oEC60to30v3wLI/mpas-o.graph.info.170328.part.720'
        FAIL: SVN repo 'https://acme-svn2.ornl.gov/acme-repo/acme/inputdata' does not have file 'https://acme-svn2.ornl.gov/acme-repo/acme/inputdata/ocn/mpas-o/oEC60to30v3wLI/mpas-o.graph.info.170328.part.720'
        Reason:
        svn: OPTIONS of 'https://acme-svn2.ornl.gov/acme-repo/acme/inputdata/ocn/mpas-o/oEC60to30v3wLI/mpas-o.graph.info.170328.part.720': could not connect to server (https://acme-svn2.ornl.gov)
        
          Model mpassi missing file graph720 = '/home/ccsm-data/inputdata/ice/mpas-cice/oEC60to30v3wLI/mpas-cice.graph.info.170905.part.720'
        FAIL: SVN repo 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata' does not have file 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/ice/mpas-cice/oEC60to30v3wLI/mpas-cice.graph.info.170905.part.720'
        Reason:
        svn: URL 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/ice/mpas-cice/oEC60to30v3wLI/mpas-cice.graph.info.170905.part.720' non-existent in that revision
        
          Model mpaso missing file graph720 = '/home/ccsm-data/inputdata/ocn/mpas-o/oEC60to30v3wLI/mpas-o.graph.info.170328.part.720'
        FAIL: SVN repo 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata' does not have file 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/ocn/mpas-o/oEC60to30v3wLI/mpas-o.graph.info.170328.part.720'
        Reason:
        svn: URL 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/ocn/mpas-o/oEC60to30v3wLI/mpas-o.graph.info.170328.part.720' non-existent in that revision
        
        Client protocol None not enabled
        ERROR: Could not find all inputdata on any server

Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
At test-scheduler close, state is:
FAIL ERS.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel (phase RUN)
    Case dir: /lcrc/group/acme/xylar/acme_scratch/anvil/ERS.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel.20190125_063508_dcka8r
test-scheduler took 745.611119986 seconds
```
</p>
</details>

**Comment by darincomeau** [comment]
@xylar the default settings for this test use a PE layout that doesn't have a sea ice graph partition file, so you'll need to change it in the case directory to one that exists, then rebuild and resubmit. If you're testing the G-case, you'll also want to turn off salinity restoring, since that will currently cause the test to fail.

You may also want to test the B-case, which should run out of the box, and we'll also want this to pass:
./create_test ERS.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.edison_intel

**Comment by mark-petersen** [comment]
Hmm..  I get a bfb restart match in MPAS-Ocean stand-alone. Started with the same file as E3SM test, `oEC60to30v3wLI60lev.171031.nc` in MPAS-O, with melt fluxes on.

I have reproduced the E3SM ERS test on edison (both intel and gnu).  I can test further from there.

**Comment by mark-petersen** [comment]
FYI, I am able to reproduce the restart mismatch in the ERS test, then setting these variables to zero within each loop in `mpas_ocn_surface_land_ice_fluxes.F`, it passes the ERS test.  I'll know which are causing the mismatch later today.
```
surfaceStress
surfaceThicknessFlux
tracersSurfaceFlux
outFreshwaterFlux
outOceanHeatFlux
outIceHeatFlux
```

**Comment by mark-petersen** [comment]
@jonbob I'm getting the following:
```
./create_test ERS_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu  -q debug --walltime 00:30:00
`config_land_ice_flux_mode = 'pressure_only'`
FAILS
```
Could you confirm I did it right?  My directory is here:
```
/global/cscratch1/sd/mpeterse/acme_scratch/cori-knl/ERS_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu.20190129_112407_bytgi9
```
and I can see the flag in mpaso_in.

That is really confusing, because I lost my ability to find the bug.  I'll continue debugging with the B case, as I did confirm an ERS PASS on that one.

**Comment by jonbob** [comment]
@mark-petersen - that looks right, but you'll have to change permissions on that directory for me to check more carefully

**Comment by darincomeau** [comment]
@mark-petersen are you running this test with a current version of master, since other bug fixes affecting this compset (DIB restarts, salinity restoring) have been merged in the last few days?

**Comment by mark-petersen** [comment]
Good point.  I'm on Monday's commit.  Will try again with HEAD.

**Comment by mark-petersen** [comment]
I ran a bunch of tests.  The bfb restart mismatch is caused by this line:
```
mpas_ocn_diagnostics.F.
surfaceStress(iEdge) = surfaceStress(iEdge) + topDrag(iEdge)
```
topDrag is computed here:
```
src/core_ocean/shared/mpas_ocn_tendency.F
1717          velocityMagnitude = sqrt(kineticEnergyCell(1,cell1) + kineticEnergyCell(1,cell2))
1720          topDrag(iEdge) = - rho_sw * landIceEdgeFraction * config_land_ice_flux_topDragCoeff &
1721                           * velocityMagnitude * normalVelocity(1,iEdge)
```
and it ended up that there is some restart mismatch in the kineticEnergyCell calculation here:
```
src/core_ocean/shared/mpas_ocn_diagnostics.F
kineticEnergyCell(k,iCell) = 5.0_RKIND / 8.0_RKIND * kineticEnergyCell(k,iCell) + 3.0_RKIND / 8.0_RKIND &
                           * kineticEnergyVertexOnCells(k,iCell)
```
where we mix 5/8 cell + 3/8 vertex KE values.   Commenting this line out, or using _only_  `kineticEnergyVertexOnCells` lets us pass the B case bfb restart.  I don't see the root cause yet, need to ask @philipwjones for help.

**Comment by xylar** [comment]
@mark-petersen, wow, again nice detective work!  Could there be halo issues with `kineticEnergyVertexOnCells`?  Or perhaps isn't not being computed on init/restart?

**Comment by xylar** [comment]
Looking at the code, I would at least try doing a halo update on `kineticEnergyCell` and see if that solves the issue.  That may not be the long-term solution but it could at least verify that it's likely a halo issue.

**Comment by darincomeau** [comment]
@xylar do you have a chance to test what you've proposed?

**Comment by jonbob** [comment]
@mark-petersen - in the second set of fixes, is that line 382 instead of 282?

**Comment by jonbob** [comment]
With the second set, the following passed:
* ERS.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel

I'm trying the B-case as well right now

**Comment by mark-petersen** [comment]
Yes, line 382 on the second set. I'll edit above.

**Comment by mark-petersen** [comment]
@jonbob could you give me the full `./create_test` command that you use on anvil?  How do you specify the core count - with `--pesfile`?

**Comment by jonbob** [comment]
@mark-petersen - you can use something like:
./create_test ERS_P480.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel

At least that works for a set number of processors, which is appropriate for the G-case. I'll have to test the B-case

**Comment by jonbob** [comment]
For B-cases, I'm testing the one-line create test that looks like this:
./create_test ERS.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.anvil_intel --pesfile /lcrc/group/acme/jwolfe/acme_scratch/anvil/ERS.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.anvil_intel.20190205_162126_suqqpp/env_mach_pes.xml

**Comment by mark-petersen** [comment]
Here is my pass/fail list using master with a Feb 2 commit 71f4e1927 and mpas-source alterations at https://github.com/MPAS-Dev/MPAS-Model/pull/147, same as second set above: https://github.com/E3SM-Project/E3SM/issues/2702#issuecomment-460770082

Fail on all these means it ran, but in `TestStatus` I see `FAIL ... COMPARE_base_modpes`

**Exact Restart: B-Case Pass, G-Case Fail**
```
PASS ERS_Ld3.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.cori-knl_gnu  /global/cscratch1/sd/mpeterse/acme_scratch/cori-knl/ERS_Ld3.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.cori-knl_gnu.20190205_203113_a7h5as
FAIL ERS_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu   /global/cscratch1/sd/mpeterse/acme_scratch/cori-knl/ERS_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu.20190205_203126_n8o5iq
```

**PEM: All Fail**
```
PEM_Ln9.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.cori-knl_gnu   /global/cscratch1/sd/mpeterse/acme_scratch/cori-knl/PEM_Ln9.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.cori-knl_gnu.20190205_204701_94qhgb
PEM_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu   /global/cscratch1/sd/mpeterse/acme_scratch/cori-knl/PEM_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu.20190205_204731_x4l427
```

**PET: All Pass**
```
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu   /global/cscratch1/sd/mpeterse/acme_scratch/cori-knl/PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu.20190205_204725_7ubnpw
PET_Ln9.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.cori-knl_gnu  /global/cscratch1/sd/mpeterse/acme_scratch/cori-knl/PET_Ln9.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.cori-knl_gnu.20190205_204657_ayffuj
```

**Comment by jonbob** [comment]
@mark-petersen - can you please open the permissions on the PEM test directories? I'd like to look at them and see if I understand

**Comment by jonbob** [comment]
On anvil, the PEM tests also fail until I turn off the ismf features with config_land_ice_flux_mode. I'm testing now with the first approach for haloing to see if that fixes the issue

**Comment by jonbob** [comment]
The PEM test still fails under ismf configurations, even with the first halo approach

**Comment by mark-petersen** [comment]
On master 71f4e19 + KE halo update at [MPAS-Dev/MPAS-Model#147](https://github.com/MPAS-Dev/MPAS-Model/pull/147), I add the `user_nl_mpaso` line
`config_land_ice_flux_mode = 'pressure_only'`
I still get fail on:
```PEM_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu```
@jonbob you get a pass on that test, right?  I also maxed out ALL halos in the ocean diagnostics routines, and it still failed. I'm not sure how to proceed.  

One idea is to change all entries in nCellsArray to max halo in framework as a test, just to see if we can get a pass.

**Comment by darincomeau** [comment]
@mark-petersen with those two line changes in ``src/core_ocean/shared/mpas_ocn_diagnostics.F`` that you reference above, I get:

PEM_P512.T62_oEC60to30v3wLI.GMPAS-DIB-IAF.edison_intel PASS
PEM_P512.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.edison_intel FAIL

So I think this is only one issue related to ISMF, and there isn't a second issue with DIB.

**Comment by mark-petersen** [comment]
The ERS bug has been solved with the above fix in mpas-source alterations at [MPAS-Dev/MPAS-Model#147](https://github.com/MPAS-Dev/MPAS-Model/pull/147), same as second set above: [#2702 (comment)](https://github.com/E3SM-Project/E3SM/issues/2702#issuecomment-460770082).  

I'm opening a new issue for the PEM bug at #2739.
