### ISSUE TITLE
Conservation problems for non-water species

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/E3SM#2704]
From Peter Lauritzen via @PeterCaldwell:

> The bugs we found for CAM were related to all non-water tracers (i.e. not Q,CLDLIQ,CLDICE, ...) that were not diffused mass-conservatively in the vertical diffusion (CLUBB) and gravity wave drag. Modal aerosols were not updated correctly with surface flux (i.e. modal aerosol mass budget not closed). Below is a summary of the bug fixes for the incorrect mixing ratios based on a CESM2 release tag:
> 
> 0. Remove wet conversion in chemistry/mozart/chemistry.F90 (bad code)
> 
> 1. physics/cam/constituents.F90: make cnst_type (identifier for wet or dry mixing ratio) a protected type (so 0. is now impossible).
> 
> 2a. physics/cam/vertical_diffusion.F90: vertical diffusion code did not conserve mass for dry tracers. Fixed by converting all mixing ratios to wet inside vertical diffusion code!
> 
> 2b. physics/cam/vertical_diffusion.F90: For modal aerosol the surface flux was added to state assuming state was wet. Fixed with 1a code change!
> 
> 3. physics/cam/clubb_intr.F90: CLUBB expects all tracers to be wet and hence (in CAM) its vertical diffusion of non-water variables was not mass-conserving. Fixed by converting to wet in CLUBB interface code!
> 
> 4. physics/cam/gw_drag.F90: Gravity wave drag assumes that all tracers are wet. Fixed by converting to wet inside gravity wave code!

**Comment by susburrows** [comment]
This is a critical bug for longer prognostic CO2 simulations.  We will need it fixed for v2.  Flagging @kvcalvin .

**Comment by mt5555** [comment]
@wlin7 : here is the issue w.r.t. tracer conservation in the atmosphere.

**Comment by AaronDonahue** [comment]
Does this also fix issue #2765?

**Comment by beharrop** [comment]
I didn't check, but I wouldn't think so.  Energy depends on the water species, but those are always kept as wet mixing ratios, so were not subject to this bug.  Though the fact that it was the same two parameterizations for both issues is suspicious.

I can try a quick run with print_energy_errors = .true. set.  Does the error show up immediately?  Can I get away with running just a few time steps?

**Comment by AaronDonahue** [comment]
@beharrop , yes, the conservation errors pop up in the first few steps so you should be able to see what happens with print_energy_error = .true. right away.

**Comment by beharrop** [comment]
@AaronDonahue, great.  I will try that and report back.

**Comment by beharrop** [comment]
@AaronDonahue, Nope.  #2883 still yields energy conservation error printouts from gwdrag.  I only ran out 14 timesteps and didn't see any errors from CLUBB.

**Comment by AaronDonahue** [comment]
@beharrop , thanks for checking.  I wonder if the CLUBB energy errors have been remedied.  It is on my todo list to re-simulate the errors and put together a more comprehensive explanation of what is going on.  I'll report back about the CLUBB errors when I do.
