### ISSUE TITLE
Compsets with ISMF failing PEM tests

### ISSUE THREAD

**Issue by mark-petersen** [E3SM-Project/E3SM#2739]
This fails:
`PEM_Ln3.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF`
On master [71f4e19](https://github.com/E3SM-Project/E3SM/commit/71f4e19270286b74d8bdac89204f9413a467fb92) + KE halo update at [MPAS-Dev/MPAS-Model#147](https://github.com/MPAS-Dev/MPAS-Model/pull/147)
Behavior is seen on cori-knl with gnu, and anvil.

**Comment by mark-petersen** [comment]
I had test jobs running all weekend. We are passing restart tests, but bfb across partitions fails.  Note data ice bergs are off, and this is a G case that fails:
```
./create_test PEM_Ln3.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.cori-knl_gnu  -q debug --walltime 00:30:00
```
Note All tests discussed here are on master [71f4e19](https://github.com/E3SM-Project/E3SM/commit/71f4e19270286b74d8bdac89204f9413a467fb92) + KE halo update at [MPAS-Dev/MPAS-Model#147](https://github.com/MPAS-Dev/MPAS-Model/pull/147)

It only fails when land ice fluxes are on, i.e. test passes with 
`config_land_ice_flux_mode = 'pressure_only'`
I tested all the lines in `mpas_ocn_surface_land_ice_fluxes.F` to find the root cause.  PEM fails when _any_ of these three lines are active:
```
surfaceStress(iEdge) = surfaceStress(iEdge) + topDrag(iEdge)
surfaceThicknessFlux(iCell) = surfaceThicknessFlux(iCell) + landIceFreshwaterFlux(iCell) / rho_sw
tracersSurfaceFlux(1, iCell) = tracersSurfaceFlux(1, iCell) + landIceHeatFlux(iCell)/(rho_sw*cp_sw)
```
These variables appear to be uninvolved in the PEM bug, as each line by itself still results in PEM fail:
```
surfaceStressMagnitude(iCell) = surfaceStressMagnitude(iCell) + topDragMagnitude(iCell)
outFreshwaterFlux(iCell) = rho_sw*oceanSaltTransferVelocity(iCell) &
        * (oceanSalinity(iCell)/outInterfaceSalinity(iCell) - 1.0_RKIND)
outOceanHeatFlux(iCell) = cp_sw*(outFreshwaterFlux(iCell)*outInterfaceTemperature(iCell) &
        - rho_sw*oceanHeatTransferVelocity(iCell)*(oceanTemperature(iCell)-outInterfaceTemperature(iCell)))
outIceHeatFlux(iCell) = -cp_land_ice*outFreshwaterFlux(iCell)*iceTemperature(iCell)
```
So I expanded the halos everywhere I could think of.  In the end I expanded all halos to the max ring in all places in all modules involved with land ice fluxes in any way:
```
mpas_ocn_effective_density_in_land_ice.F 
mpas_ocn_init_routines.F
mpas_ocn_diagnostics.F 
mpas_ocn_frazil_forcing.F
mpas_ocn_surface_land_ice_fluxes.F 
mpas_ocn_tracer_surface_restoring.F
```
but it still failed PEM.  Then, to make extra sure, I hard-wired the variables
`nCellsArray, nEdgesArray, nVerticesArray`
to be the max halo, so all halos are maxed out except where the variable `nCellsSolve` is called as a dimension explicitly (BTW, that should be added as a debug feature, see https://github.com/mark-petersen/MPAS-Model/commit/251ae3680ec85da42b7c9a62a92cc5bb2a50fb96).  

_It still failed PEM test with all halos maxed out_

OK, stay calm. This means that there is a halo update missing somewhere.  So I wrote out all variables after one timestep and computed a diff.  There are order 1e-6 differences in:
`temperature, salinity, kineticEnergyCell`
but only at the edge of Antarctica at what appears to be partition boundaries and below ice shelves.
![image](https://user-images.githubusercontent.com/4036816/52565816-24c1d200-2dc5-11e9-9530-f95a919caea7.png)
I also wrote out all tendency terms, which is great for debugging.  All match exactly between the two PEM runs except vertical mixing.  This is true at top and next layer.
![image](https://user-images.githubusercontent.com/4036816/52566759-d530d580-2dc7-11e9-82a5-9dc2db313d0b.png)

Aha! smoking gun.  So I reran the original test, i.e. using master [71f4e19](https://github.com/E3SM-Project/E3SM/commit/71f4e19270286b74d8bdac89204f9413a467fb92) + KE halo update at [MPAS-Dev/MPAS-Model#147](https://github.com/MPAS-Dev/MPAS-Model/pull/147) and 
`config_use_cvmix = .false.`

_AND IT PASSES PEM_

Summary: Land ice fluxes require a halo update of some variable involved in land ice fluxes before implicit vertical mixing is called.  I am looking for this variable now. May need to bring in @xylar and @vanroekel later today.

**Comment by mark-petersen** [comment]
I saved every field imaginable after one timestep and used ncdiff between the two PEM runs, then take max(abs()).  This is still using master [71f4e19](https://github.com/E3SM-Project/E3SM/commit/71f4e19270286b74d8bdac89204f9413a467fb92) + KE halo update at [MPAS-Dev/MPAS-Model#147](https://github.com/MPAS-Dev/MPAS-Model/pull/147), but no flags.
<details>
<summary> netcdf commands</summary> <p>

```
ncdiff -d Time,0 mpaso.hist.0001-01-01_00000.nc case2run/mpaso.hist.0001-01-01_00000.nc ncdiff_mpaso.hist.0001-01-01_00000.nc
ncwa -d Time,0 -O -y mabs ncdiff_mpaso.hist.0001-01-01_00000.nc mabs_ncdiff_mpaso.hist.0001-01-01_00000.nc
ncdump mabs_ncdiff_mpaso.hist.0001-01-01_00000.nc|grep 'data:' -A 1000|grep -
ncdump mabs_ncdiff_mpaso.hist.0001-01-01_00000.nc|grep 'data:' -A 1000|grep -v -|grep =
```
 </p></details>


**These variables do not match after one timestep**
```
 BruntVaisalaFreqTop = 1.50271878014002e-09 ;
 kineticEnergyCell = 6.83911607003013e-06 ;
 normalVelocity = 5.74483620812416e-05 ;
 RiTopOfCell = 0.0671803719671047 ;
 salinity = 2.92366792820076e-06 ;
 salinityVertMixTendency = 1.62425996011153e-09 ;
 temperature = 6.6031428120894e-06 ;
 temperatureVertMixTendency = 3.66841267338303e-09 ;
 topDrag = 8.27926557088743e-05 ;
 topDragMagnitude = 4.85031716227491e-05 ;
 vertDiffTopOfCell = 6.09728764582838e-05 ;
 vertViscTopOfCell = 6.0698797604699e-05 ;
 vertViscTopOfEdge = 0.000209806207352491 ;
```


<details>
<summary> These variables match exactly after one timestep</summary> <p>

```
 bulkRichardsonNumber = 0 ;
 bulkRichardsonNumberBuoy = 0 ;
 bulkRichardsonNumberShear = 0 ;
 cellMask = 0 ;
 edgeMask = 0 ;
 evaporationFlux = 0 ;
 fractionAbsorbed = 0 ;
 frazilLayerThicknessTendency = 0 ;
 heatFluxToLandIce = 0 ;
 iceFraction = 0 ;
 iceRunoffFlux = 0 ;
 indexSurfaceLayerDepth = 0 ;
 landIceFreshwaterFlux = 0 ;
 landIceHeatFlux = 0 ;
 latentHeatFlux = 0 ;
 layerThickness = 0 ;
 maxLevelEdgeTop = 0 ;
 nonLocalSalinitySurfaceFlux = 0 ;
 nonLocalTemperatureSurfaceFlux = 0 ;
 penetrativeTemperatureFlux = 0 ;
 rainFlux = 0 ;
 refBottomDepth = 0 ;
 refLayerThickness = 0 ;
 refZMid = 0 ;
 riverRunoffFlux = 0 ;
 salinityHorizontalAdvectionTendency = 0 ;
 salinityNonLocalTendency = 0 ;
 salinitySurfaceFlux = 0 ;
 salinitySurfaceFluxRemoved = 0 ;
 salinitySurfaceFluxRunoff = 0 ;
 salinitySurfaceFluxTendency = 0 ;
 salinitySurfaceRestoringTendency = 0 ;
 salinityVerticalAdvectionTendency = 0 ;
 seaIceEnergy = 0 ;
 seaIceFreshWaterFlux = 0 ;
 seaIceHeatFlux = 0 ;
 seaIceSalinityFlux = 0 ;
 sensibleHeatFlux = 0 ;
 shortWaveHeatFlux = 0 ;
 snowFlux = 0 ;
 ssh = 0 ;
 surfaceBuoyancyForcing = 0 ;
 surfaceFrictionVelocity = 0 ;
 surfaceStress = 0 ;
 surfaceStressMagnitude = 0 ;
 surfaceThicknessFlux = 0 ;
 temperatureHorizontalAdvectionTendency = 0 ;
 temperatureNonLocalTendency = 0 ;
 temperatureShortWaveTendency = 0 ;
 temperatureSurfaceFlux = 0 ;
 temperatureSurfaceFluxRemoved = 0 ;
 temperatureSurfaceFluxRunoff = 0 ;
 temperatureSurfaceFluxTendency = 0 ;
 temperatureVerticalAdvectionTendency = 0 ;
 tendSSH = 0 ;
 vertCoordMovementWeights = 0 ;
 vertexMask = 0 ;
 viscosity = 0 ;
 windStressMeridional = 0 ;
 windStressZonal = 0 ;
 xtime = "0" ;
 zMid = 0 ;
```
 </p></details>

**Comment by mark-petersen** [comment]
The above variables can be put in order by cause and effect:
1. `vertDiffTopOfCell, vertViscTopOfEdge`
are first. Then all vertical mixing tendencies will differ:
2. `salinityVertMixTendency, temperatureVertMixTendency`
making prognostic variables differ:
3. `salinity, temperature, normalVelocity`
then diagnostics is run at the end of the timestep, and anything dependent on prognostic variables differs:
4. `BruntVaisalaFreqTop kineticEnergyCell RiTopOfCell topDrag topDragMagnitude`

I also ran a few more tests:
```
config_cvmix_shear_mixing_scheme = 'PP' **FAILS PEM**
change to config_use_cvmix_kpp = .false. *PASSES PEM*
```

**Comment by vanroekel** [comment]
@mark-petersen did you try increasing nCellsSolve -> nCells in this routine of the land ice flux computation?

https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/shared/mpas_ocn_surface_land_ice_fluxes.F#L357

From how I read this routine, it looks like landIceHeatFlux and landIceFreshwaterFlux is computed to nCellsSolve, but then at the top of the routine it is added to surfaceTracerFlux and surfaceFreshThickness flux to all 3 halos.  This could explain the PEM failure with KPP on.  But I may be missing a halo update of the land ice fluxes before the other routines are called in ocn_tendency

**Comment by xylar** [comment]
@vanroekel, I think you're probably on to something.  We probably need to be doing all those computations over `nCells` or at least a bigger halo than `nCellsSolve`.  @mark-petersen, this may have gone unnoticed because `nCellsSolve` is passed into 2 different routines but is called `nCells` within the routines.

**Comment by mark-petersen** [comment]
I saw that last week and thought the same thing, but when I  changed from `nCellsSolve` to `nCells` it still didn't pass PEM.  Of course, there could be multiple bugs that are causing this confusion.  I did try tests where I put all halo expansions together, including this one, as well as some extra halo exchanges, but the tests always failed.

Tonight I started from the beginning again, adding small sets of halo expansions at a time.  Still always failing.  Now I'm adding halo exchange to `surfaceBuoyancyForcing, surfaceFrictionVelocity` just before the vmix call, as suggested by @vanroekel (thanks!).

@vanroekel the test with
`config_use_cvmix_fixed_boundary_layer = .true.`
still failed.

**Comment by vanroekel** [comment]
@mark-petersen the failure for fixed boundary layer implies this is a problem in the surfaceBuoyancyForcing and/or surfaceFrictionVelocity.  Hopefully a halo update on those variables will fix this.  There seem to be a whole lot of variables computed in the land-ice fluxes to nCellsSolve and the halo update on those two variables may be the quickest fix.  I'll keep my fingers crossed.

**Comment by mark-petersen** [comment]
Got it.  The minimal change required to pass PEM is:
```
+++ src/core_ocean/mode_forward/mpas_ocn_time_integration_split.F
@@ -1768,6 +1768,10 @@ module ocn_time_integration_split
        call ocn_diagnostic_solve(dt, statePool, forcingPool, meshPool, diagnosticsPool, scratchPool, tracersPool, 2)
+        call mpas_dmpar_field_halo_exch(domain, 'surfaceFrictionVelocity')
```
This halo exchange is within a block loop.  If this is the final solution, will need to put halo exchange after block loop.  Also looking at variables that go into surfaceFrictionVelocity to see if we can avoid halo exchange.

**Comment by mark-petersen** [comment]
`surfaceFrictionVelocity` can be traced back to `surfaceStress`
```
mpas_ocn_diagnostics.F
1320     subroutine ocn_compute_KPP_input_fields

1438       nCells = nCellsArray( 3 )
...
1447       do iCell = 1, nCells
...
1492        ! compute magnitude of surface stress
1493         deltaVelocitySquared = 0.0_RKIND
1494         do i = 1, nEdgesOnCell(iCell)
1495           iEdge = edgesOnCell(i, iCell)
1496           factor = 0.5_RKIND * dcEdge(iEdge) * dvEdge(iEdge) * invAreaCell
1497           delU2 =  (surfaceStress(iEdge))**2
1498           deltaVelocitySquared = deltaVelocitySquared + factor * delU2
1499         enddo
1500         surfaceStressMagnitude(iCell) = sqrt(deltaVelocitySquared)
1501
1502        ! compute surface friction velocity
1503          surfaceFrictionVelocity(iCell) = sqrt(surfaceStressMagnitude(iCell) / rho_sw)
```

We add topDrag to surfaceStress for ice shelves:
```
mpas_ocn_surface_land_ice_fluxes.F
 140    subroutine ocn_surface_land_ice_fluxes_vel

 183       call mpas_pool_get_dimension(meshPool, 'nEdges', nEdges)
 
 189       do iEdge = 1, nEdges
 190         surfaceStress(iEdge) = surfaceStress(iEdge) + topDrag(iEdge)
 191       end do
```

and topDrag is computed here:
```
mpas_ocn_diagnostics.F
1541    subroutine ocn_compute_land_ice_flux_input_fields

1664       call mpas_pool_get_dimension(meshPool, 'nEdges', nEdges)

1704       do iEdge = 1, nEdges
1705          cell1 = cellsOnEdge(1, iEdge)
1706          cell2 = cellsOnEdge(2, iEdge)
1707
1708          ! top drag tau = - CD*|u|*u, where |u| = sqrt(2*KE) = sqrt(KE1 + KE2) from the neighboring cells
1709          velocityMagnitude = sqrt(kineticEnergyCell(1,cell1) + kineticEnergyCell(1,cell2))
1710          landIceEdgeFraction = 0.5_RKIND*(landIceFraction(cell1)+landIceFraction(cell2))
1711
1712          topDrag(iEdge) = - rho_sw * landIceEdgeFraction * config_land_ice_flux_topDragCoeff &
1713                           * velocityMagnitude * normalVelocity(1,iEdge)
1714
1715       end do

```

There are no obvious halos to expand in these. One of the RHS variables must have a bad halo.

**Comment by mark-petersen** [comment]
Strange.  If I add a halo exchange to topDrag just after it is computed, rather than the later halo exchange to `surfaceFrictionVelocity` here https://github.com/E3SM-Project/E3SM/issues/2739#issuecomment-462801452, it fails. 

Specifically, this does not get PEM to match:
```
mpas_ocn_diagnostics.F
  91    subroutine ocn_diagnostic_solve

 835       call ocn_compute_land_ice_flux_input_fields(meshPool, statePool, forcingPool, scratchPool, &
 836                                          diagnosticsPool, timeLevel)
 837 +       call mpas_dmpar_field_halo_exch(domain, 'topDrag')
```

**Comment by mark-petersen** [comment]
Scratch that last comment.  I forgot to make the `nCellsSolve->nCells` change mentioned last night here https://github.com/E3SM-Project/E3SM/issues/2739#issuecomment-462611157.  Turns out that _is_ required in addition to the others.  When that is added, then:

 I can get a PEM pass with halo exchange `topDrag` after the call
```
mpas_ocn_diagnostics.F
  91    subroutine ocn_diagnostic_solve

 835       call ocn_compute_land_ice_flux_input_fields(meshPool, statePool, forcingPool, scratchPool, &
 836                                          diagnosticsPool, timeLevel)
 837 +       call mpas_dmpar_field_halo_exch(domain, 'topDrag')
```
OR I get a PEM pass with a halo exchange on `kineticEnergyCell` before the call
```
mpas_ocn_diagnostics.F
  91    subroutine ocn_diagnostic_solve
 834 +       call mpas_dmpar_field_halo_exch(domain, 'kineticEnergyCell')
 835       call ocn_compute_land_ice_flux_input_fields(meshPool, statePool, forcingPool, scratchPool, &
 836                                          diagnosticsPool, timeLevel)
```
but I get a PEM FAIL with a halo exchange on `normalVelocity`
```
mpas_ocn_diagnostics.F
  91    subroutine ocn_diagnostic_solve
 834 +       call mpas_dmpar_field_halo_exch(domain, 'normalVelocity')
 835       call ocn_compute_land_ice_flux_input_fields(meshPool, statePool, forcingPool, scratchPool, &
 836                                          diagnosticsPool, timeLevel)
```
So it was a problem with the halo on `kineticEnergyCell` after all. Running tests now with just the right halo expansions together...

**Comment by mark-petersen** [comment]
This still fails PEM. So I still don't understand the problem with `kineticEnergyCell` that is solved by a halo exchange in the previous post.
<details>

```
diff --git a/src/core_ocean/shared/mpas_ocn_diagnostics.F b/src/core_ocean/shared/mpas_ocn_diagnostics.F
index f9f560ee..2a836b84 100644
--- a/src/core_ocean/shared/mpas_ocn_diagnostics.F
+++ b/src/core_ocean/shared/mpas_ocn_diagnostics.F
@@ -314,7 +314,7 @@ contains
       !$omp end do

       ! Need 0 and 1 halo cells
-      nCells = nCellsArray( 2 )
+      nCells = nCellsArray( size(nCellsArray) )
       !
       ! Compute divergence, kinetic energy, and vertical velocity
       !
diff --git a/src/core_ocean/shared/mpas_ocn_surface_land_ice_fluxes.F b/src/core_ocean/shared/mpas_ocn_surface_land_ice_fluxes.F
index 9a7c7d00..e521c092 100644
--- a/src/core_ocean/shared/mpas_ocn_surface_land_ice_fluxes.F
+++ b/src/core_ocean/shared/mpas_ocn_surface_land_ice_fluxes.F
@@ -439,7 +439,7 @@ contains
       call mpas_pool_get_config(ocnConfigs, 'config_land_ice_flux_useHollandJenkinsAdvDiff', &
                                 config_land_ice_flux_useHollandJenkinsAdvDiff)

-      call mpas_pool_get_dimension(meshPool, 'nCellsSolve', nCellsSolve)
+      call mpas_pool_get_dimension(meshPool, 'nCells', nCellsSolve)

       call mpas_pool_get_array(diagnosticsPool, 'landIceFrictionVelocity', landIceFrictionVelocity)
</details>

**Comment by mark-petersen** [comment]
A halo exchange on `kineticEnergyCell` just before the call to `ocn_compute_land_ice_flux_input_fields` solves the problem.  So I tried halo exchanges on all variables used by `kineticEnergyCell`, just before the kinetic energy calculation. It passes PEM, but only when `config_include_KE_vertex=.false.`.
```
mpas_ocn_diagnostics.F
 318       ! Need 0,1,2 halo cells
 319       nCells = nCellsArray( 4 )
 320       call mpas_dmpar_field_halo_exch(domain, 'normalVelocity')
 321       call mpas_dmpar_field_halo_exch(domain, 'dcEdge')
 322       call mpas_dmpar_field_halo_exch(domain, 'dvEdge')
 323       call mpas_dmpar_field_halo_exch(domain, 'maxLevelCell')
 324       call mpas_dmpar_field_halo_exch(domain, 'areaCell')
```
A halo exchange here on `normalVelocity` alone does not pass PEM.  It appears that a halo update on mesh variables is needed, which is very surprising. 

I also tried to add vertex variable halo updates in addition to those above:
```
      call mpas_dmpar_field_halo_exch(domain, 'areaTriangle')
      call mpas_dmpar_field_halo_exch(domain, 'kiteAreasOnVertex')
```
but I was never able to pass PEM using this strategy when using the default `config_include_KE_vertex=.true.`.

**Comment by mark-petersen** [comment]
Sorry for all the lengthy detail.  In the end I was not able to fix it in a more basic fashion.  The most robust solution at this point appears to be a halo update on `surfaceFrictionVelocity`.
```
+++ src/core_ocean/mode_forward/mpas_ocn_time_integration_split.F
@@ -1768,6 +1768,10 @@ module ocn_time_integration_split
        call ocn_diagnostic_solve(dt, statePool, forcingPool, meshPool, diagnosticsPool, scratchPool, tracersPool, 2)
+        call mpas_dmpar_field_halo_exch(domain, 'surfaceFrictionVelocity')
```

See https://github.com/MPAS-Dev/MPAS-Model/pull/147 where I've added the required changes.
