### ISSUE TITLE
Change the env variable of NetCDF library path in MPAS

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/E3SM#2748]
MPAS uses the NETCDF_PATH env variable to find NetCDF libraries, while other model components have used two env variables NETCDF_C_PATH and NETCDF_FORTRAN_PATH to find C and FORTRAN libraries respectively.  It would be better to change the NETCDF_PATH to either NETCDF_C_PATH or NETCDF_FORTRAN_PATH in MPAS makefiles for consistency and long-term needs.

**Comment by philipwjones** [comment]
Sorry for not catching this earlier, but the MPAS makefile does look for a NETCDFF environment variable, so defining the NETCDFF environment variable as the NETCDF_FORTRAN_PATH should work. Just tried in a standalone MPAS-O and summit and it worked fine. Again, apologize for not catching this for the previous PR.

**Comment by minxu74** [comment]
@philipwjones Thanks. I see. In the mpas-source/Makefile, the NETCDF and NETCDFF are used for NETCDF C and FORTRAN lib paths respectively.  The NETCDF is defined in mpas-source/src/Makefile.in.ACME as NETCDF_PATH, but NETCDFF is not. I will submit a PR to fix it.
