### ISSUE TITLE
MPAS-O analysis bug leads to testing failures

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#2768]
A recently commit introduced a bug in the mpas-ocean analysis member coding that causes failures in the automated testing of SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.allactive-v1cmip6, on sandiatoss3 and anvil using intel compilers

**Comment by milenaveneziani** [comment]
Hi Jon, any idea what the bug is? Could you please open an issue on the MPAS-A side? Thanks.

**Comment by xylar** [comment]
@jonbob, you're referring to an analysis member (online analysis), not MPAS-Analysis, correct?

**Comment by jonbob** [comment]
Sorry if that wasn't clear. The bug appears in one of the online mpas-ocean analysis member calculations, though my suspicion is that the error itself is in calculating a new array to be time-averaged

**Comment by xylar** [comment]
Yep, that's what I thought.  Thanks for clarifying.

**Comment by mark-petersen** [comment]
I was able to reproduce this with
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
```

It only occurs in debug mode.  I’m getting an overflow on this line
```
mpas_ocn_time_series_stats.f90
2301 subroutine operate3r_avg (start_block, variable, buffers)
 
2333   out_array = (out_array * &                    !!!!!!!!!!!!!!!!!!! This line
2334     (buffers(b) % counter - 1) + in_array) &
2335     / buffers(b) % counter
```
and only when this new variable is in the time monthly output
`activeTracerVerticalAdvectionTopFlux`

**Comment by mark-petersen** [comment]
Fix here.  Thanks @jonbob for the help. https://github.com/MPAS-Dev/MPAS-Model/pull/165

**Comment by jonbob** [comment]
Great - and thanks for the quick fix @mark-petersen. Just let me know when the new submodule is accessible by e3sm
