### ISSUE TITLE
CLM providing invalid starts/counts to the PIO

### ISSUE THREAD

**Issue by bishtgautam** [E3SM-Project/E3SM#2778]
CLM is providing invalid starts/counts to the PIO library and this commit fixes that issue.
With PIO1 the entire library is implemented in fortran and since fortran arrays always include the size with it these bugs did not show up (inadvertently). When testing with PIO2 these bugs showed up.

**Comment by bishtgautam** [comment]
@jayeshkrishna, I was wondering if we should also inform NCAR about this issue, if you haven't already done so. What do you think?

**Comment by jayeshkrishna** [comment]
I am not sure why they haven't seen this error. My guess is that JimE@NCAR must have made some similar changes in CESM.

 When we started using PIO2 with E3SM, I had asked JimE regarding any CESM changes that was required (so we could port it to E3SM) and he said there were some changes that he made in CESM but did not have a list (we ended up testing E3SM+PIO2 and finding/fixing the bugs). So its possible they already have associated/related changes.


Regards,

Jayesh

________________________________

**Comment by jayeshkrishna** [comment]
In any case it might be useful to ping them and see if they have seen the issue.
