### ISSUE TITLE
MODIS simulator incorrectly adds snow

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/E3SM#2782]
In porting the COSP implementation to work with the MMF, I ran across an issue in the MODIS simulator code where the code to account for the addition of "snow" in the total cloud amount is incorrectly adding the convective cloud amount twice instead of using the snow. The affected code occurs between lines 217 and 233 of `components/cam/src/physics/cosp/cosp_modis_simulator.F90`:
```
      ! Loop version of spread above - intrinsic doesn't work on certain platforms.
      do k = 1, nLevels
        do j = 1, nSubCols
          do i = 1, nSunlit
            if((subCols%prec_frac(sunlit(i), j, k) == 1 .or. &
		        subCols%prec_frac(sunlit(i), j, k) == 3) .and. &
               snowSize(i, j, k) > 0.                    .and. &
               gridBox%dtau_s_snow(sunlit(i),   k) > 0. ) then
                 opticalThickness(i, j, k) = opticalThickness(i,j,k) + gridBox%dtau_c(sunlit(i), k)
		       cloudSnow(i, j, k) = subcolHydro%mr_hydro(sunlit(i), j, k, I_LSSNOW)
	        else
               cloudSnow       (i, j, k) = 0.
               snowSize        (i, j, k) = 0. 
            end if 
          end do 
        end do
      end do !+JEK
```
Notice that `opticalThickness(i,j,k)` is incremented with `gridBox%dtau_c(sunlit(i),k)` instead of `gridBox%dtau_s_snow(sunlit(i),k)` here, effectively double counting the convective snow optical depth (it's added in above), and neglecting the snow altogether. Note that this will not affect the climate at all (simulator diagnostics do not affect the model solution), but it will affect MODIS simulator outputs.

**Comment by brhillman** [comment]
NOTE: branch brhillman/atm/fix-modis-snow applies the fix here. Differences in MODIS cloud fraction after the fix:
![screen shot 2019-03-06 at 9 26 24 am](https://user-images.githubusercontent.com/15826727/53900705-fa44ec80-3ff1-11e9-84b3-1e8f32a27683.png)

**Comment by tangq** [comment]
Thanks for confirming. This issue was reported before in #2770.

**Comment by brhillman** [comment]
Ah great! Thanks @tangq I couldn't find a corresponding issue for it.
