### ISSUE TITLE
livestemn_to_litter_patch and livestemp_to_litter_patch are initialized to NaN before they are used, which causing FPE in debug mode

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/E3SM#2792]
In the components/clm/src/biogeochem/CNNitrogenFluxType.F90, the variable 'livestemn_to_litter_patch' is initialized to NaN and is only set to value_patch when crop_prog = .true.. The variable is used directly in the Summary subroutine in the CNNitrogenFluxType.F90. The bug caused FPE in debug mode. I did not find any meaningful definition for this variable except for initialization under the clm directory. Do we really need it?  Same for the variable ' livestemp_to_litter_patch' in the components/clm/src/biogeochem/PhosphorusFluxType.F90

**Comment by jinyun1tang** [comment]
@minxu74, I remember I once found this and handed it over to Gautam together with a few other similar things.

**Comment by minxu74** [comment]
@jinyun1tang Thanks a lot for pointing out. During my debugging on a I-case on Summit, I found those incorrectly initialized variables in the land model and noticed that most of them have been reported in the  #2733 and #2734. But I just looked at the titles and did not read the issues carefully. Since it has been reported in the #2734,  I am closing it now.
