### ISSUE TITLE
An error of running query_testlists

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/E3SM#2795]
Tried to run query_testlists and got the following error:
`cime/config/e3sm/allactive/testlist_allactive.xml is an unsupported version of the testfile format and will be ignored`

**Comment by jgfouca** [comment]
@minxu74 , E3SM doesn't use XML testlists, we use python.

Our tests are defined in:
```
cime/config/e3sm/tests.py
```

You can list them via
```
cime/scripts/Tools/list_e3sm_tests
```
