### ISSUE TITLE
RRTMGP code should be submodule?

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/E3SM#2798]
Tagging this with the question label, because I'm not 100% sure this is the right thing to do but wanted to get input before I go ahead with it. Our new radiation package (RRTMGP) is maintained in a separate external repository. Currently, we have a copy of the code integrated into E3SM, but since RRTMGP is still under fairly active development, any time I want to pull in updates to the external repo, I need to copy over the files and commit on our end. This does not seem like the best way of doing this. Would it be appropriate to make the RRTMGP code a submodule, or is there a more preferred way of handling this now?

**Comment by rljacob** [comment]
If the development is one-way, from the external RRTMGP to E3SM, a submodule would be appropriate.  But you still have to do a PR to update the commit the submodule is pointing to.

**Comment by jgfouca** [comment]
I agree, a submodule would make sense.

**Comment by brhillman** [comment]
The development is one way. I'll put together a PR.

**Comment by jgfouca** [comment]
For what it's worth, submodules are great for two-way development too.
