### ISSUE TITLE
"Error in opening the compiled module file"

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#2807]
Every once in a while, a test will fail to build with the error "Error in opening the compiled module file".   If you just wait a day, the test runs fine.    It seems to be random but I think its always complaining about the same file.  This issue will log these errors as they come up.

In comments below, note the date, test(s), filename with the error and provide a link to the TestStatus in cdash.

**Comment by rljacob** [comment]
2019-03-15
SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.sandiatoss3_intel.allactive-v1cmip6
cosp/quickbeam/radar_simulator.f90(15): error #7002: Error in opening the compiled module file
https://my.cdash.org/testDetails.php?test=45925310&build=1622191

**Comment by rljacob** [comment]
2019-03-16
SMS_D_Ln5.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-cosplite_nhtfrq5
cosp/quickbeam/radar_simulator.f90(15): error #7002: Error in opening the compiled module file.
https://my.cdash.org/testDetails.php?test=45943876&build=1622561

**Comment by rljacob** [comment]
2019-03-16
SMS_D_Ln5.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-cosplite_nhtfrq5
cosp/quickbeam/radar_simulator.f90(15): error #7002: Error in opening the compiled module file.
https://my.cdash.org/testDetails.php?test=45943876&build=1622561

**Comment by brhillman** [comment]
I've run into this before, and I think made some temporary changes at the time to work around it. Part of the problem I think is that `cosp/quickbeam/radar_simulator.f90` is *not* a module, it's just a subroutine. I think in the past I changed this to a module (and made corresponding changes where the subroutine is used to `use` the  module), and/or renamed the file to `cosp/quickbeam/radar_simulator.F90`.

**Comment by rljacob** [comment]
2019-04-02
SMS_D_Ln5.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-cosplite_nhtfrq5 
cosp/quickbeam/radar_simulator.f90(15): error #7002: Error in opening the compiled module file.
https://my.cdash.org/testDetails.php?test=46341293&build=1630227

**Comment by rljacob** [comment]
So the message about a missing module is not accurate but I'm more concerned with why it is random.

**Comment by brhillman** [comment]
Yeah I don't know why this would be random, and we'd probably need a reproducible error to be sure of the fix.

**Comment by rljacob** [comment]
Its random in time but so far its always sandiatoss3.  Its always that same file.

**Comment by brhillman** [comment]
Well, I could make the changes to code to make that file an actual module, and see if these "random" errors go away I guess. It's a pretty trivial change, but we don't really have any way of testing if it fixes the problem other than waiting.

**Comment by wlin7** [comment]
The error message seems to suggest that it couldn't find the module "scale_LUTs_io". 

The file scale_LUTs_io.f90 is a normal module file.  Next time when it failed, please try to check if 
scale_LUTs_io.o  and .mod exist under bld/atm/obj/cosp.

If they don't exist, either the dependency rule somehow broke, or the compilation of scale_LUTs_io.f90 itself failed. In the latter case, the error log on compiling scale_LUTs_io.f90 may tell us something.

**Comment by wlin7** [comment]
It is likely scale_LUTs_io.f90 was not compiled before radar_simulator.f90 did for the failed test.  Can someone please give a check on the bld directory of build/atm/obj/cosp.

In cam/src/physics/cosp/Makefile.cospinline.in,  the object radar_simulator.o is not explicitly made dependent of scale_LUTs_io.o.  I don't see an indirect dependency either.  Does that mean we have been relying on racing on other machines and luck on sandiatoss3 to have them compiled in proper order?

If this is the case, PR #2835 hopefully can resolve this issue. It makes radar_simulator.o explicitly dependent of module scale_LUTs_io.o

**Comment by rljacob** [comment]
I thought the dependency list for the atmosphere was generated dynamically with each build by parsing the Fortran files.  The result is in $EXEROOT/bld/atm/obj/Depends for each case  and is generated by CIME using the cime/scripts/Tools/mkDepends program.

**Comment by wlin7** [comment]
Yeah, this procedure is not yet applied to the build of cosp.   Currently for building libcosp.a, it directly uses the template as in Makefile.cospinline.in. It should be helpful to check the dependency rule in bld/atm/obj/cosp/Makefile. And in the case of failed test, check if indeed module scale_LUTs_io was not yet compiled. Once confirmed, I think we can use PR #2835 as a tentative fix until switching to mkDepends

**Comment by brhillman** [comment]
Nice catch @wlin7

**Comment by wlin7** [comment]
Resolved via PR [#2835.](https://github.com/E3SM-Project/E3SM/pull/2835)
