### ISSUE TITLE
BGCEXP tests fail on cori

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/E3SM#2809]
The following tests failed on cori,

SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.cori-knl_intel.clm-bgcexp
SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.cori-knl_intel.clm-bgcexp

From the error message it looks like these tests (ocn bcc) don't work with multiple threads

**Comment by jayeshkrishna** [comment]
Error message (from @dqwu ),

```
SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.cori-knl_intel.clm-bgcexp     Failed     0s     Completed (FAIL)     Broken
/global/cscratch1/sd/dqwu/Cori/e3sm_integration/test_e3sm_pio1/SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.cori-knl_intel.clm-bgcexp.20180924_102116_uyyyql/env_mach_specific.xml already exists, delete to replace
ERROR:  ERROR mpas-o buildnml: ocn bgc cannot be run with more than 1 thread

SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.cori-knl_intel.clm-bgcexp     Failed     0s     Completed (FAIL)     Broken
/global/cscratch1/sd/dqwu/Cori/e3sm_integration/test_e3sm_pio1/SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.cori-knl_intel.clm-bgcexp.20180924_102116_uyyyql/env_mach_specific.xml already exists, delete to replace
ERROR
```

**Comment by jayeshkrishna** [comment]
This failure was seen by @dqwu while testing E3SM with PIO2

**Comment by amametjanov** [comment]
There is a pending PR E3SM-Project/E3SM#2732 for this issue.

**Comment by jayeshkrishna** [comment]
Should I go ahead and close this issue/PR as a duplicate?

**Comment by jayeshkrishna** [comment]
The PR #2732 includes changes to remove the restriction that OCN BGC needs to run single threaded (PR #2732 instead of forcing the test to run with a single thread, removes the restriction and discusses fixing any issues that come up. OCN needs to run threaded for good performance on KNL)
