### ISSUE TITLE
Multi-threaded cases are not built with threading flags

### ISSUE THREAD

**Issue by amametjanov** [E3SM-Project/E3SM#2826]
Current master (`v1.1.0-beta-1202-g6e47b9f`) appears to have dropped threading flags (`-qopenmp` for Intel compiler) for multi-threaded cases such as `SMS_P12x2.ne4_oQU240.A_WCYCL1850`.

**Comment by jgfouca** [comment]
Hi @amametjanov , on which machine and compiler did you see this?

**Comment by amametjanov** [comment]
Anvil+Intel

**Comment by jgfouca** [comment]
OK, looking at it now.

**Comment by jgfouca** [comment]
I see the problem. It was introduced by the latest cime update, specifically compile_threaded was changed from lower to upper (true vs. TRUE) but many of our XML files were not updated. Fix coming.

**Comment by rljacob** [comment]
Does this mean threading tests like PET were not changing the threading?

**Comment by amametjanov** [comment]
Yes, both runs of a PET test were built with MPI-only flags. Environment for the first run was set for 2 threads, but that doesn't matter if the executable is built without threading flags.
