### ISSUE TITLE
Issue with isnan intrinsic function

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#2838]
Case: FC5AV1C-L
Res: ne4
Compiler: PGI and IBM
File: components/clm/src/data_types/VegetationDataType.F90

PGI error: 
PGF90-S-0038-Symbol, isnan, has not been explicitly declared (/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/data_types/VegetationDataType.F90)

IBM error:
/autofs/nccs-svm1_home1/sarat/repos/E3SM/components/clm/src/data_types/VegetationDataType.F90", line 3132.28: 1516-036 (S) Entity isnan has undefined type.

isnan seems to be GNU instrinsic.
https://gcc.gnu.org/onlinedocs/gfortran/ISNAN.html

Thanks to @minxu74, I found shr_infnan_mod. 

So looks like troublesome code should be replaced with 
> var_is_nan = shr_infnan_isnan(x)

This in turn uses ieee_is_nan() that is part of the standard ieee_arithmetic module.

**Comment by sarats** [comment]
Intel seems to have this intrinsic : https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference-isnan

Still, I wonder why our tests haven't caught this. Looks like we are testing just GNU and Intel? 
@rljacob Can we add at least PGI to the tests? Perhaps using PGI community edition.

**Comment by minxu74** [comment]
Base on my.cdash.org, only Gnu and Intel are tested now.

**Comment by rljacob** [comment]
We stopped testing PGI when we stopped testing on Titan.

To add back PGI we need a machine that has it along with the associated software stack that needs to be built with PGI (mpich, pnetcdf, etc).  I think Anvil has it.   Someone who cares about pgi will have to watch the test report on the dashboard.

**Comment by ndkeen** [comment]
Noting that PGI will be the preferred compiler for perlmutter at NERSC.  And, in general, I think the more compilers we test with, the better.

**Comment by rljacob** [comment]
At the time we glad to be rid of PGI since it always seems to be a buggy compiler.  Otherwise yes the more compilers the better especially for Fortran.

**Comment by crjones-amath** [comment]
Noting also that the ACME-ECP project is running on Summit and requires pgi.

**Comment by rljacob** [comment]
ACME-ECP is responsible for doing their own testing.  E3SM itself has no time on Summit.

**Comment by crjones-amath** [comment]
@rljacob Understood, and we're happy to log issues on E3SM as they arise during our testing. I just wanted to echo @ndkeen's comment with another voice of support for testing PGI.

**Comment by rljacob** [comment]
Our ORNL testing required a person to log in and run the suite which then reported to the dashboard.  If someone in ECP wants to take that on, we can provide instructions.

**Comment by sarats** [comment]
Few thoughts that motivated this discussion:

If our INCITE allocation next year or two for E3SM (not MMF) targets Summit, we don't want to hit all these bugs at that time. Especially, testing the CPU-only portions of code in components like land that will not be ported to GPUs. 

Moreover, Summit might not be suitable for running integration tests due to queue limits. We would need the the 'single-submit' create-test option for making such tests feasible. 

Meanwhile, the testing can happen on a workstation with PGI community edition compilers.

**Comment by minxu74** [comment]
@rljacob Can CIME just compile the tests without actually submitting them and report the compilation results back to cdash.  If so, I think I can do it weekly.  At least we can catch these compilation errors.

**Comment by rljacob** [comment]
@jgfouca can we run an entire suite as "build-only" and wait-for-tests report that correctly?

**Comment by jgfouca** [comment]
@rljacob , yes. The --no-run option would need to be provided to create_test and the --no-wait option to wait_for_tests.

**Comment by rljacob** [comment]
@jgfouca so @minxu74 can cd to cime/scripts and do
create_test --no-run e3sm_integration_next_pgi
Then where does he run wait_for_tests ?

**Comment by jgfouca** [comment]
@rljacob , @minxu74 : 

```
./create_test --no-run e3sm_integration -t XXX
./Tools/wait_for_tests /$path-to-test-root/*XXX/TestStatus --no-run -b $cdash_build_name
```

**Comment by minxu74** [comment]
@jgfouca @rljacob Thanks a lot. Let me try.

**Comment by sarats** [comment]
@bishtgautam Would you or someone from land group look into this? 
Although it's a minor fix, just wanted to get this to the notice of Land developers that IBM (specifically) and PGI compilers seem to adhere relative strictly to the standards. So, something to be aware of.
