### ISSUE TITLE
Unexpected flags in PIO2 build log on Cori

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#2858]
With the latest E3SM master (09f1a3363aac8f5ca74d2a319a900efb69121421), PIO2 build (using PIO2 from E3SM fork) contains unexpected flags (however the build and run do not fail).

How to reproduce:
1) Checkout latest E3SM master branch
2) Edit cime/src/drivers/mct/cime_config/config_component.xml to change
default PIO_VERSION to 2
3) Replace cime/src/externals/pio2 with latest pio2 master branch:
```
cd cime/src/externals
mv pio2 pio2_backup
git clone https://github.com/E3SM-Project/ParallelIO.git pio2
```
4) Create a simple ne4_ne4 F case
5) Edit env_mach_pes.xml to use 2 threads
6) Run case.setup and case.build
7) View pio.bldlog.****.gz in the build directory

Problematic flags:
1) LDFLAGS="-qopenmp -qopenmp"
Note that there is a duplicate "-qopenmp" flag (it was not shown before)

Also, "-cxxlib" is no longer included in LDFLAGS (it was there before), even it is set by intel compiler
```
<compiler COMPILER="intel">
...
  <CXX_LDFLAGS>
    <base> -cxxlib </base>
</CXX_LDFLAGS>
...
```
2) CMAKE_CXX_FLAGS:STRING="-std=c++11 -fp-model source -qopenmp ... -std=gnu99 -qopenmp ..."
There is also a duplicate "-qopenmp" flag.

PS, it seems incorrect to always include "-qopenmp" as the base of CXXFLAGS
```
<compiler COMPILER="intel">
...
  <CXXFLAGS>
    <base> -std=c++11 -fp-model source -qopenmp </base>
    <append DEBUG="TRUE"> -O0 -g </append>
    <append DEBUG="FALSE"> -O2 </append>
  </CXXFLAGS>
...
```
For other flags in config_compilers.xml, "-qopenmp" is always conditionally appended
when compile_threaded is TRUE
`<append compile_threaded="TRUE"> -qopenmp </append>`

**Comment by rljacob** [comment]
@jgfouca you might need to look at this.

**Comment by jayeshkrishna** [comment]
This could be the source of the "-cxxlib" flag missing for PIO2,
```ifeq ($(strip $(PIO_VERSION)),1)
  CPPDEFS += -DPIO1
else
  USE_CXX = true
endif```

true instead of TRUE

**Comment by jgfouca** [comment]
@dqwu , @jayeshkrishna , does PIO2 use C++ (CXX)?

**Comment by jayeshkrishna** [comment]
Yes, PIO2 uses C++ (and C, Fortran)

**Comment by jgfouca** [comment]
OK, I'll take a look at it.

**Comment by jgfouca** [comment]
@dqwu , it worked for me:

```
% ./create_test SMS_P16x2.ne4_ne4.FC5AV1C-L --no-run
...
PASS SMS_P16x2.ne4_ne4.FC5AV1C-L.cori-knl_intel MODEL_BUILD
% cd $case
% ./xmlquery PIO_VERSION
2
```

Should I have expected the build to fail? Or just the flags to be messed-up?

**Comment by jayeshkrishna** [comment]
(@jgfouca : Note that you need to replace pio2 on master with pio2 in E3SM fork)

**Comment by dqwu** [comment]
@jgfouca 
Just look at the flags in the build log (pio.bldlog.****.gz). The build does not fail, though.

**Comment by jgfouca** [comment]
OK, I have a branch with some fixes. The lack of -cxxlib was due to the Makefile problem that @jayeshkrishna found (wrong case for TRUE). I'm still looking for the source of qopenmp duplication. Fixed the intel CXX definition to only add qopenmp if compile_threaded=TRUE did not fix the problem.

**Comment by jgfouca** [comment]
@dqwu , try my branch: jgfouca/cime/minor_compiler_fixes

The qopenmp duplication is still there, but it appears to be harmless.

**Comment by dqwu** [comment]
@jgfouca 
Thanks for the quick fix. I tried that branch with PIO1/PIO2 (1 thread and 2 threads)
and it seems good.
1) cxxlib is in LDFLAGS for PIO2 (it is not there for PIO1, which is expected)
2) If compile_threaded is FALSE, qopenmp is not in LDFLAGS or CXXFLAGS.

PS, are you able to identify the source of qopenmp duplication?
If compile_threaded is TRUE, qopenmp still appears twice in both LDFLAGS and CXXFLAGS.
Note, in CMAKE_C_FLAGS, qopenmp appears only once.

**Comment by jgfouca** [comment]
@dqwu , I was not able to identify the source of the duplicated qopenmp. I was going to leave it alone since it didn't appear to break anything.

**Comment by dqwu** [comment]
@jgfouca 
That's OK, you can go ahead to create a PR, thanks.
