### ISSUE TITLE
Unable to disable regionalStatisticsOutput in streams.seaice for G case

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#2866]
--compset GMPAS-NYF --res T62_oRRS18to6v3
Test with just 1 thread due to known MPAS-Ocean threading issue.

After case.setup, copy streams.seaice in the run directory to SourceMods/src.mpassi

Edit this file to change output_interval of regionalStatisticsOutput to none.
```
<stream name="regionalStatisticsOutput"
        type="output"
        io_type="pnetcdf"
        filename_template="mpassi.hist.am.regionalStatistics.$Y.$M.nc"
        output_interval="00-00-01_00:00:00"
```

Run case.setup --reset before case.build and case.submit.

However, the following file is still output to the run directory:
mpassi.hist.am.regionalStatistics.0001.01.nc

**Comment by jonbob** [comment]
@dqwu - can you please try adding the following line to user_nl_mpassi?

 config_am_regionalstatistics_enable = .false.

With the MPAS stream routines, analysis members that are enabled will be output. Some of the control is in the streams file, but some is in the namelist -- here is the namelist for that file:
````
&am_regionalstatistics
 config_am_regionalstatistics_compute_interval = '0000-00-01_00:00:00'
 config_am_regionalstatistics_compute_on_startup = true
 config_am_regionalstatistics_enable = true
 config_am_regionalstatistics_ice_extent_limit = 0.15
 config_am_regionalstatistics_output_stream = 'regionalStatisticsOutput'
 config_am_regionalstatistics_write_on_startup = true
/````
From these settings, it certainly will be output during initialization and computed every day. It's easier to simple disable the whole thing in the namelist file.

**Comment by dqwu** [comment]
@jonbob 
Thanks for your information. Setting config_am_regionalstatistics_enable to false in user_nl_mpassi works for me.
