### ISSUE TITLE
Fix our math to compute the "-c flag". Especially for cori-knl.

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#2869]
We currently compute the -c flag for the machine, but it doesn't account for all situations.

```
<arg name="thread_count">-c $SHELL{echo 272/`./xmlquery --value MAX_MPITASKS_PER_NODE`|bc}</arg>
```

This is usually correct:

For 64 MPI's per node, 272/64=4.25, which is integer-mathed to be 4.

However, for 16 MPI's per node, 272/16=17.0, and 17 is used. It doesn't make sense to use "-c 17" (and I am pretty sure the performance will be bad). The correct -c flag should be 16 in that case.

**Comment by amametjanov** [comment]
IIRC, 272 was chosen for full occupancy of a node. If a power-of-two number of cores/node is the most commonly used case, then might as well switch from 272 to 256.

**Comment by ndkeen** [comment]
Well, using 256 would help some, but not others. I think we just need some new logic here. I guess there's still no other variables in that config XML file that we can use to do this, huh...  Seems silly to be doing this math in shell language embedded in XML, but I'm sure we can make it work.
