### ISSUE TITLE
PGI Compiling errors on summit when compiler for GPU

### ISSUE THREAD

**Issue by shz0116** [E3SM-Project/E3SM#2873]
I am working on porting atm ndrop.F90 file to GPU on summit Using OpenACC. When trying to 
create a sequential kernel for activate_modal by adding "!$acc routine seq", the compiler generated
the following error (mpif90):

PGF90-S-0000-Internal compiler error. Call in OpenACC region to support routine - __builtin_alloca (/autofs/nccs-svm1_home1/hshan/E3SM/components/cam/src/physics/cam/ndrop.F90)

I know It is probably related with stack allocation. But how to solve this problem.

**Comment by shz0116** [comment]
I found the problem. By default, -Mstack_array is defined, which caused the problem.
Removing this option solves the problem. Just wonder why this option is enabled ?
Is there any performance advantage ?

**Comment by minxu74** [comment]
It is said that the speed accessing to stack is faster than to heap memory, but it is not necessary true for all situations.  We can profile the performances w and w/o that option on Summit.

**Comment by sarats** [comment]
@shz0116 You can go ahead with -Mnostack_arrays specifically for that file if you want to be selective. I presume you are doing 'routine seq' in the interim. You can also allocate such arrays explicitly.

https://www.pgroup.com/resources/docs/18.10/pdf/pgi18ref-x86.pdf
```
-Mstack_arrays
places automatic arrays on the stack.
-Mnostack_arrays
allocates automatic arrays on the heap. -Mnostack_arrays is the default and what
traditionally has been the approach used
```

**Comment by sarats** [comment]
Looking into activate_modal function, some of those arrays might be large, hence the need for allocating them on the heap. If you wish, you can selectively allocate the larger arrays. 

As I understand, stack_arrays was used to obviate expensive allocates on the GPU side.

**Comment by shz0116** [comment]
Thx. Setting -Mnostack_arrays works.

shan
