### ISSUE TITLE
Potential issue with SMS_D.ne4_ne4.FC5AV1C-L using intel19 'Attempt to use pointer ELEM when it is not associated with a target'

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#2899]
On Cori, I'm testing using newer versions of Intel MPI (impi) and the v19 compiler.

With `SMS_D_Ln5.ne4_ne4.FC5AV1C-L`, I see:

```
129: forrtl: severe (408): fort: (7): Attempt to use pointer ELEM when it is not associated with a target
129:
129: Image              PC                Routine            Line        Source
129: e3sm.exe           000000000BC8F186  Unknown               Unknown  Unknown
129: e3sm.exe           00000000024EC92E  dyn_comp_mp_dyn_i         189  dyn_comp.F90
129: e3sm.exe           0000000000A8C459  inital_mp_cam_ini          31  inital.F90
129: e3sm.exe           000000000083458A  cam_comp_mp_cam_i         159  cam_comp.F90
129: e3sm.exe           000000000080069F  atm_comp_mct_mp_a         312  atm_comp_mct.F90
129: e3sm.exe           000000000045B652  component_mod_mp_         257  component_mod.F90
129: e3sm.exe           000000000041C570  cime_comp_mod_mp_        1328  cime_comp_mod.F90
129: e3sm.exe           000000000045222D  MAIN__                    122  cime_driver.F90
129: e3sm.exe           000000000040A732  Unknown               Unknown  Unknown
129: e3sm.exe           000000000BD73619  Unknown               Unknown  Unknown
```

**Comment by ndkeen** [comment]
Note that with  https://github.com/E3SM-Project/E3SM/pull/2939, I updated the version of Intel 19 to be 19.0.3.199. I wanted to note that this happens to be a case where the number of MPI's is larger than the number of elements. It could very well be that elem is used before init. Should we change the code to account for this?

Here is the code in dyn_comp.F90

```
    if (par%nprocs .lt. npes_cam) then
! Broadcast quantities to auxiliary processes
#ifdef SPMD
       call mpibcast(neltmp, 3, mpi_integer, 0, mpicom)
#endif
       if (.not.par%dynproc) then
          nelemdmax = neltmp(1)
          nelem     = neltmp(2)
          call set_horiz_grid_cnt_d(neltmp(3))
       endif
    endif


    !
    ! This subroutine creates mapping files using SE basis functions if requested
    !
    call native_mapping_readnl(NLFileName)
    call create_native_mapping_files( par, elem,'native')  !<-- line with error
    call create_native_mapping_files( par, elem,'bilin')
```

**Comment by mt5555** [comment]
I'd suggest we simply remove native_mapping.F90, these calls and the corresponding namelist variables.  This code creates mapping files (SE grid to lat/lon grid).   These days the code is never used since we make mapping files with ncremap.

**Comment by ndkeen** [comment]
We should probably address this issue as I need to update the compiler on Cori to intel19.  Note this will fail on any machine with intel19. The reason it fails on Cori and not others, is that the default PE layout for this problem on Cori is pushing the number of MPI's to be larger than number of elements.

**Comment by jeff-cohere** [comment]
I just encountered this running Valgrind against a small atmosphere case in order to try to build a call graph that illustrates how CAM uses MAM.

Compset: FC5AV1C-L
Grid: ne4_ne4

I've encountered it on 1- and 2-node PE layouts on both Cori's KNL and Haswell nodes. Valgrind hits memory pretty hard. In any case, if this code is needlessly being called (if I understand @mt5555 correctly), maybe we should just remove it.

**Comment by ndkeen** [comment]
The simple ne4 test will pass if I do:

```
-    call native_mapping_readnl(NLFileName)
-    call create_native_mapping_files( par, elem,'native')
-    call create_native_mapping_files( par, elem,'bilin')
+    !ndk call native_mapping_readnl(NLFileName)
+    !ndk call create_native_mapping_files( par, elem,'native')
+    !ndk call create_native_mapping_files( par, elem,'bilin')
```

Is this what you had in mind Mark?
