### ISSUE TITLE
Input data not downloading automatically to NERSC

### ISSUE THREAD

**Issue by cameronsmith1** [E3SM-Project/E3SM#2900]
I just added new inputdata to the master sever on Blues at ANL.  However, when E3SM at NERSC tries to download the new data I get the following error:

```
Checking server https://web.lcrc.anl.gov/public/e3sm/inputdata/ with protocol wget
ERROR: Could not connect to repo '{0}'
This is most likely either a proxy, or network issue .
```

I have checked that I can access the data correctly using a web-browser, so I think it is a problem with either NERSC or wget.

Qi Tang ( @tangq ) said he had the same problem last month (April 2019), but not in Feb.  He worked around the problem by downloading the data to NERSC manually.

Any suggestions?  (pinging: @ndkeen @rljacob , cc @golaz )

**Comment by singhbalwinder** [comment]
Are you using the latest master? Unless it is a new issue, I think it was fixed via PR #2849 .

**Comment by cameronsmith1** [comment]
My code base is a few weeks old.  Will this change be picked up on maint-1.0 ?

**Comment by singhbalwinder** [comment]
I don't think this was merged into any of the maint branches.

@jgfouca may know more about it.

**Comment by jgfouca** [comment]
It looks like maint needs this PR:
https://github.com/E3SM-Project/E3SM/pull/2849

**Comment by cameronsmith1** [comment]
It does look like PR2849 should fix my problem.   However, I just manually installed the new version of wget.py into my local version of maint-1.0, and I now get the error below on Edison.  I have checked that the file is available from Blues, and that it doesn't show up in the NERSC data directory.

```  Model cam missing file bndtvghg = '/project/projectdirs/acme/inputdata/atm/cam/ggas/GHG_CMIP_SSP585-1-2-1_Annual_Global_2015-2500_c20190310.nc'
FAIL: Repo 'https://web.lcrc.anl.gov/public/e3sm/inputdata/' does not have file 'https://web.lcrc.anl.gov/public/e3sm/inputdata/atm/cam/ggas/GHG_CMIP_SSP585-1-2-1_Annual_Global_2015-2500_c20190310.nc'
Reason:
Spider mode enabled. Check if remote file exists.
--2019-05-02 12:03:37--  https://web.lcrc.anl.gov/public/e3sm/inputdata/atm/cam/ggas/GHG_CMIP_SSP585-1-2-1_Annual_Global_2015-2500_c20190310.nc
Resolving web.lcrc.anl.gov (web.lcrc.anl.gov)... 140.221.70.30
Connecting to web.lcrc.anl.gov (web.lcrc.anl.gov)|140.221.70.30|:443... connected.
ERROR: cannot verify web.lcrc.anl.gov's certificate, issued by '/C=US/O=Entrust, Inc./OU=See www.entrust.net/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Certification Authority - L1K':
  Unable to locally verify the issuer's authority.
To connect to web.lcrc.anl.gov insecurely, use `--no-check-certificate'.
```

**Comment by jgfouca** [comment]
@cameronsmith1 , looks like I missed one spot when adding no-check-certificate. Try doing this:

BEFORE:
```
    def fileexists(self, rel_path):
        full_url = os.path.join(self._server_loc, rel_path)
        stat, out, err = run_cmd("wget {} --spider {}".format(self._args, full_url))
```

AFTER:
```
    def fileexists(self, rel_path):
        full_url = os.path.join(self._server_loc, rel_path)
        stat, out, err = run_cmd("wget {} --no-check-certificate --spider {}".format(self._args, full_url))
```

**Comment by cameronsmith1** [comment]
Thanks.  I fixed manually in my local version, and it is now working.

Can this PR (with extra fix) be added to maint-1.0?   We are trying to start the simulation as soon as possible, so we can do a run before Edison goes away.

**Comment by jgfouca** [comment]
@cameronsmith1 , yes, doing it now.

**Comment by jgfouca** [comment]
@cameronsmith1 , done.

**Comment by cameronsmith1** [comment]
Thanks, @jgfouca .  It now works as hoped.
