### ISSUE TITLE
CAM does not respect value of PIO_NETCDF_FORMAT XML variable

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/E3SM#2903]
CAM PIO interface appears to not respect the value of the `PIO_NETCDF_FORMAT` variable in `env_run.xml`. The default for this variable is `64bit_offset`, but valid values include `64bit_data`. When working with very large grids (i.e., ne512) variable sizes become too large to write with the 64bit offset format, and we need to use the 64bit data format (which does not have size limitations). One would hope that setting `PIO_NETCDF_FORMAT=64bit_data` in `env_run.xml` would fix this, but the value appears to not be propagated to `cam_pio_createfile`, because the history, restart, and new initial condition files are all written in the 64bit offset format (confirmed in a ne4 test). I can hard-code `pio_64bit_data` in `cam_pio_utils.F90` to get the desired output type with the following changes:
```
diff --git a/components/cam/src/utils/cam_pio_utils.F90 b/components/cam/src/utils/cam_pio_utils.F90
index a599ac4ef..dc095d03c 100644
--- a/components/cam/src/utils/cam_pio_utils.F90
+++ b/components/cam/src/utils/cam_pio_utils.F90
@@ -1071,7 +1071,7 @@ contains

   subroutine cam_pio_createfile(file, fname, mode_in)
     use pio, only : pio_createfile, file_desc_t, pio_noerr, pio_clobber,      &
-         pio_64bit_offset, pio_iotask_rank
+         pio_64bit_offset, pio_64bit_data, pio_iotask_rank
     use cam_abortutils, only : endrun

     ! Dummy arguments
@@ -1083,10 +1083,11 @@ contains
     integer                                   :: ierr
     integer                                   :: mode

-    mode = ior(PIO_CLOBBER, PIO_64BIT_OFFSET)
-    if (present(mode_in)) then
-      mode = ior(mode, mode_in)
-    end if
+    !mode = ior(PIO_CLOBBER, PIO_64BIT_OFFSET)
+    !if (present(mode_in)) then
+    !  mode = ior(mode, mode_in)
+    !end if
+    mode = ior(PIO_CLOBBER, PIO_64BIT_DATA)
```
and the resulting files have netcdf type `cdf5`. This of course does not deal with the problem of propagating the value of `PIO_NETCDF_FORMAT` down to the CAM PIO interface, but does show that we can get the desired behavior and that there is indeed a problem here. I think this is related to #1544 (writing restart files for ne120 on titan), but the issue I am reporting here is not specific to any specific architecture (my tests were on cori-knl). I'll point out that we needed to hard-code `PIO_64BIT_DATA` for our ne120 MMF simulations on Summit as well. The ability to set this via `env_run.xml` and get the expected behavior would be much appreciated! 64bit data should also probably be the default for large grids.

Simple example to reproduce the bug: configure any F-compset case (ne4 and FC5AV1C-L will work), run `./xmlchange PIO_NETCDF_FORMAT=64bit_data` in the case directory, setup, build, and submit, and then run `ncdump -k` on any of the CAM output files (the restart file will suffice). Note that it will be "64bit offset" as opposed to "cdf5".

**Comment by jayeshkrishna** [comment]
What is missing here might be a call to shr_pio_getioformat() in CAM to get the PIO I/O format from CIME and use it.

**Comment by jayeshkrishna** [comment]
Something like,
```
mode = shr_pio_getioformat(atm_id)
mode = ior(mode,PIO_CLOBBER)
if (present(mode_in)) then
   mode = ior(mode, mode_in)
end if

```

**Comment by brhillman** [comment]
Thanks @jayeshkrishna it actually looks like there's a query to `shr_pio_getioformat(atm_id)` in the initialization, it's just not being used here (or rather, I think overwritten by the setting of `mode = ior(PIO_CLOBBER, PIO_64BIT_OFFSET)`, so maybe this is the problem. I'll try a few quick tests.

**Comment by brhillman** [comment]
Okay I was mistaken about `shr_pio_getioformat()` being called already, but nonetheless the fix you posted @jayeshkrishna resulted in files being written in netCDF classic format instead of recognizing the PIO_NETCDF_FORMAT xml variable.

**Comment by jayeshkrishna** [comment]
Note that the callers of the function cam_pio_createfile() should not pass in a mode (mode_in) for the above fix to work (get the ioformat from CIME).
Did shr_pio_getioformat() return the wrong mode (instead of the one set by the user in env_run.xml) ?

**Comment by brhillman** [comment]
Yeah, good call, apparently the caller is setting `mode_in`, because that was being selected over `shr_pio_getioformat()`. Is the proper solution to remove the `mode_in` option then, and just get the io format from the call to `shr_pio_getioformat()`?

**Comment by jayeshkrishna** [comment]
In my opinion mode_in should be left as is, but should only be used (by the caller) to explicitly override the defaults. But I think this is a question for the ATM group developers.

**Comment by brhillman** [comment]
It looks like the caller (in this case I think `h_define` in `cam_history`) hard-codes `PIO_CLOBBER` for the `mode` argument, which would overwrite the call to `shr_pio_getioformat()` in `cam_pio_createfile`. So I think we should remove the hard-coded mode type in `cam_history` and just not pass the optional `mode_in` argument.

**Comment by jayeshkrishna** [comment]
I agree, since the previous version of code always used PIO_CLOBBER it (removing mode_in at the caller) should not affect the behaviour. My suggestion would be to remove mode_in args from callers unless the caller explicitly wants to override the defaults (and my guess would be that most/all calls do not need to specify mode_in).

**Comment by brhillman** [comment]
That makes sense to me. Doing a quick test with the mode argument removed from the callers.

**Comment by brhillman** [comment]
Alright changes seem to work, going to run tests and submit a PR. Thanks for your help @jayeshkrishna
