### ISSUE TITLE
EOS conflict in papi module

### ISSUE THREAD

**Issue by mark-petersen** [E3SM-Project/E3SM#2910]
When trying to run a standard test on eos, I get a conflict in the papi module.  It is fixed by simply specifying to load `papi/5.6.0.2`.

**Comment by mark-petersen** [comment]
On the eos machine at ORNL, I can submit with any test, for example:
```
./create_test SMS_Ln9.T62_oEC60to30v3.GMPAS-IAF.eos_intel  -p cli127
```
and we get the error:
```
case.run error
ERROR: module command $MODULESHOME/bin/modulecmd python load intel/18.0.1.163 papi cray-netcdf-hdf5parallel/4.3.3.1 cray-parallel-netcdf/1.6.1 cmake3/3.2.3 python/2.7.9 failed with message:
papi/5.6.0.4(8):ERROR:150: Module 'papi/5.6.0.4' conflicts with the currently loaded module(s) 'papi/5.6.0.2'
papi/5.6.0.4(8):ERROR:102: Tcl command execution failed: conflict papi
```
There is no module `papi/5.6.0.4`.
This small change in the eos section fixes the problem:
```
cime/config/e3sm/machines/config_machines.xml
@@ -2367,7 +2367,7 @@
-        <command name="load">papi</command>
+        <command name="load">papi/5.6.0.2</command>
```
but I didn't make a pull request, because I was not sure if that was the preferred method to fix it.

**Comment by worleyph** [comment]
Why is papi being loaded in the first place?

**Comment by mark-petersen** [comment]
I have no need for papi myself. I'm just getting a case to work from master on eos.

**Comment by minxu74** [comment]
@mark-petersen I just tried your case on EOS with the latest master and I could not reproduce your problem. Could you share your software_environment.txt? Also could you try to load those software packages manually to see if you get the same error? (module load  intel/18.0.1.163 papi cray-netcdf-hdf5parallel/4.3.3.1 cray-parallel-netcdf/1.6.1 cmake3/3.2.3 python/2.7.9 on your shell). Thanks.

**Comment by worleyph** [comment]
@mark-petersen , my question is why master is trying to load papi for eos. Papi is not specified on any other system in config_machines.xml . My suggestion is just to delete it.

**Comment by minxu74** [comment]
If deleting PAPI, we also need to delete the block in the config_compiler.xml as follows: 
  <CPPDEFS>
    <append MODEL="gptl"> -DHAVE_PAPI </append>
  </CPPDEFS>
Because gptl may be compiled with PAPI.

**Comment by worleyph** [comment]
Thanks for remembering that.

**Comment by mark-petersen** [comment]
Huh. It must be something in my environment. This works:
```
module load intel/18.0.1.163 papi cray-netcdf-hdf5parallel/4.3.3.1 cray-parallel-netcdf/1.6.1 cmake3/3.2.3 python/2.7.9 
```
But on current master fbb8b81 I get the same error as above. Software_environment.txt is here:
https://gist.github.com/mark-petersen/ee421bedbf2e1dbda10c0ff0d052623f
or in my case directory at
`/ccs/home/mpetersen/acme_scratch/cli127/SMS_Ln9.T62_oEC60to30v3.GMPAS-IAF.eos_intel.20190506_234923_ijla4n`

But if it's not a problem for others, I can just do my little local fix and close this ticket.

**Comment by minxu74** [comment]
@mark-petersen Thanks. Based on the software_environment.txt, it seemed that the PAPI has been loaded successfully. If you do not use the PAPI features by yourself, could you remove PAPI loading and CPP flags in the machine files to see if the problem is gone. If so, I can make a PR to remove the PAPI dependency. If you want to use the PAPI, we can merge your fix.

**Comment by mark-petersen** [comment]
This issue is no longer a problem.
