### ISSUE TITLE
ERS_Ld5.ne4_ne4.FC5AV1C-L.theta_intel.cam-rrtmgp failing on theta nightly

### ISSUE THREAD

**Issue by sarich** [E3SM-Project/E3SM#2917]
In e3sm log:
load_and_init(): can't open file /projects/ccsm/acme/inputdata/atm/cam/rad/rrtm
 gp_coefficients_sw_c181004.nc

File exists and is readable:
ncdump -k /projects/ccsm/acme/inputdata/atm/cam/rad/rrtmgp_coefficients_sw_c181004.nc
classic

**Comment by sarich** [comment]
The test script is trying to access this file for writing, but doesn't have permissions for it. We can probably add the user to the group or change the group name of the file, but I'm guessing that this file should be open read-only (NF90_NOWRITE)


In mo_load_coeffecients.F90 line 100:
```
 if(nf90_open(trim(fileName), NF90_WRITE, ncid) /= NF90_NOERR) &
      call stop_on_err("load_and_init(): can't open file " // trim(fileName))
```


The nc file here is available to unix group 'ccsm', but the test runner is user 'climenrg', which isn't part of the ccsm group:
```
$ groups climenrg
climenrg : ClimateEnergy_3 users ClimateEnergy_2
```


```
ls -l /projects/ccsm/acme/inputdata/atm/cam/rad/rrtmgp_coefficients_sw_c181004.nc 
-rw-rw-r-- 1 azamatm ccsm 14886664 Oct  4  2018 /projects/ccsm/acme/inputdata/atm/cam/rad/rrtmgp_coefficients_sw_c181004.nc

```

**Comment by brhillman** [comment]
Ah, yeah, there's no reason for that to be opened with NF90_WRITE. That's a bug in RRTMGP which I will get fixed.

**Comment by sarich** [comment]
Thanks! I'll re-assign this to you then
