### ISSUE TITLE
Failing ERP_Ln5.ne30_ne30.FC5AV1C-L.sandiatoss3_intel

### ISSUE THREAD

**Issue by oksanaguba** [E3SM-Project/E3SM#2919]
The test in nightlies breaks in the second run after restart with NaNs in homme's repro_sum cause Nans are passed to homme. This test can be fixed by making it run longer, it seems that restart files are corrupt. In e3sm output one could see 
```
 (seq_timemgr_clockInit)  WARNING: Stop time too short, not all components will
 be advanced and restarts won't be written
```
We tried a few different lengths, Ln24, Ln80, Ld2. Each one was failing (d2 run did not even config), but Ld4 run worked ( run without -c, /gscratch/onguba/acme_scratch/sandiatoss3/ERP_Ld4.ne30_ne30.FC5AV1C-L.sandiatoss3_intel.20190510_175312_wyb94d ) . I still don't quite understand what this test does, but whoever put it in, maybe, they can help fix it. It also seems that this test never passed in nightlies.

**Comment by rljacob** [comment]
This test does an exact restart test but changes the tasks/threads for the second run.

**Comment by oksanaguba** [comment]
Thanks! First i was puzzled how exactly it does so. I am not 100% sure but i think it runs 1st time at time T dumping restart file at T/2 and then runs from that restart for T/2 time, and then compares both runs. It does not change number of threads on sandiatoss3; from the output and env file, it only runs with 1 thread each time (but it reduces #of ranks by 2 for the second run).

**Comment by mt5555** [comment]
this test should be using threads.  that's a bad sign, because if this test is not using threads on sandiatoss3 systems, then there's a good chance none of the other ERP tests are as well, and we are not testing threading in our baselines?

**Comment by oksanaguba** [comment]
i can check that

**Comment by oksanaguba** [comment]
About this case first, in case i don't know where to look: i checked software_env files for both runs and then homme output from both runs. Is there any chance CAM runs with more threads than homme? Is there way to use more threads even if in software env file OMP_NUM_THREADS is set to 1?

```
cd /gpfs1/jenkins/acme_scratch/sandiatoss3/J/ERP_Ln5.ne30_ne30.FC5AV1C-L.sandiatoss3_intel.JMasterExtra_coverage20190508_172332


grep OMP_NUM_THREADS software_environment.txt 
OMP_NUM_THREADS=1

cd case2/ERP_Ln5.ne30_ne30.FC5AV1C-L.sandiatoss3_intel.JMasterExtra_coverage20190508_172332/

grep OMP_NUM_THREADS software_environment.txt 
OMP_NUM_THREADS=1

in file /gscratch/jenkins/acme_scratch/sandiatoss3/ERP_Ln5.ne30_ne30.FC5AV1C-L.sandiatoss3_intel.JMasterExtra_coverage20190508_172332/run/atm.log.16988807.190508-183542.gz

prim_init1: total threads: nthreads =            1
 threads across elements    hthreads =            1
 threading within elements  vthreads =            1


in file /gscratch/jenkins/acme_scratch/sandiatoss3/ERP_Ln5.ne30_ne30.FC5AV1C-L.sandiatoss3_intel.JMasterExtra_coverage20190508_172332/run/case2run/atm.log.16988807.190508-183814 
 prim_init1: total threads: nthreads =            1
 threads across elements    hthreads =            1
 threading within elements  vthreads =            1
```

**Comment by oksanaguba** [comment]
Looking in atm.log for /gscratch/jenkins/acme_scratch/sandiatoss3/ERP_Ln9.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.C.JNextIntegration20190511_220554/run it is the same, only 1 thread for both runs.

**Comment by rljacob** [comment]
The tests on a machine pick up whatever the default pe layout is for the case.  That test does have multiple threads on other machines (cori).  The SMS_P12x2.ne4_oQU240.A_WCYCL1850.*.allactive-mach_mods forces 2 threads on all machines.

**Comment by jgfouca** [comment]
@oksanaguba ,

```
% cd $case
% ./xmlquery NTHRDS
```

**Comment by oksanaguba** [comment]
I tried to trace this test in git history but tests.py is not old enough. 1 year ago the test was already there. I'd like to know who introduced it, so that it is removed or fixed.

**Comment by singhbalwinder** [comment]
I probably added this test after we did a revamp of all atm and land tests. It use to work fine. Do we know what has changed which broke this test?

**Comment by oksanaguba** [comment]
@singhbalwinder , I am copying your response here for records:
```
Balwinder Singh [11:43 AM]
I think I have added that test. I added that as I think ne30 grid is not tested for restarts and thread changes. I am surprised that it is failing now...it used to work fine in the past. Do you know what has changed in the meanwhile?```

I do not know anything about it and why it broke. One day it was broken and afaik it did not pass for a while. It just seems to be too short (see above). Cdash does not go far enough to see if it ever passed. When we checked 1 month ago, it was already broken for a month. If you think it is needed, would you make changes to it? like making it long?

**Comment by singhbalwinder** [comment]
If we omit `Ln5` in the test definition, the test will default to `Ld5`, which should work according to your experiments. I can issue a PR to make this change.

We actually made changes to the code so that we are able to test restarts with just a few time steps (see #1705 and #1546). There are tests in the testing suite such as `ERP_Ln9.ne4_ne4.FC5AV1C-L.sandiatoss3_intel` which runs with a pass. Only difference here is the grid (ne30 vs. ne4). I am not sure how would change in grid would make a test to fail.

**Comment by oksanaguba** [comment]
ne4 test also has warnings about being too short, but it passes.

**Comment by oksanaguba** [comment]
More on this test is in #3229 .
