### ISSUE TITLE
20TR I case test starts in year 1850

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#2920]
This test has "20TR" in the name:
ERS.f19_g16.I20TRGSWCNPRDCTCBC.sandiatoss3_intel.clm-ctc_f19_g16_I20TRGSWCNPRDCTCBC

But the compset longname shows it starts in year 1850
1850_DATM%GSWP3v1_CLM45%CNPRDCTCBC_SICE_SOCN_MOSART_SGLC_SWAV

See https://my.cdash.org/testDetails.php?test=47042171&build=1647281

**Comment by golaz** [comment]
@rljacob, not commenting on this specific compset. But in general, '20TR' is not incompatible with a start date of 1850. The E3SMv1 low-res historical coupled simulations spanned the period 1850-2014 and were using a '20TR' compset.

**Comment by bishtgautam** [comment]
@golaz is correct. 20TR implies the run period is 1850-present day.

**Comment by rljacob** [comment]
Ok this is not a bug.

**Comment by bishtgautam** [comment]
@rljacob, I now understand the point you were trying to make and how I got confused.

A "20TR" compset **should** start at 1850 and run up to present day, but the compset definition **should not** start with 1850. Thus, the long name of `I20TRGSWCNPRDCTCBC` should be 
`20TR_DATM%GSWP3v1_CLM45%CNPRDCTCBC_SICE_SOCN_MOSART_SGLC_SWAV` and not `1850_DATM%GSWP3v1_CLM45%CNPRDCTCBC_SICE_SOCN_MOSART_SGLC_SWAV`. I will create a PR to fix this.

**Comment by rljacob** [comment]
query_config shows 4 compsets with this issue.
