### ISSUE TITLE
python 3 breaks developer suite tests on Cori-KNL

### ISSUE THREAD

**Issue by whannah1** [E3SM-Project/E3SM#2935]
I grabbed a fresh copy of E3SM/master and tried to run baselines for the developer suite on Cori, but I got build failures on these tests:

ERS_Ld5.T62_oQU120.CMPASO-NYF.cori-knl_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
SMS_P12x2.ne4_oQU240.A_WCYCL1850.cori-knl_intel.allactive-mach_mods

The error I get is clearly a python version problem:

```
make[3]: Entering directory '/global/cscratch1/sd/whannah/acme_scratch/cori-knl/tests/ERS_Ld5.T62_oQU120.CMPASO-NYF.cori-knl_intel.G.20190520_074846_d88883/bld/ocn/source/core_ocean/.cvmix_all/src/shared'
./makedep.py ./shared_deps.d . .
  File "./makedep.py", line 56
    print file_name+'.o depends on '+file_used+'.o'
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(file_name+'.o depends on '+file_used+'.o')?
```

This seems related to Issue #2895 

I also got a SHAREDLIB_BUILD error from this test:
SEQ.f19_g16.X.cori-knl_intel

An abbreviated version of the error I got:
```
Command: ./case.build --sharedlib-only
Output: b"WARNING: Found difference in test STOP_N: case: 10 original value 5\n
...
WARNING: Test case setup failed. Case2 has been removed, but the main case may be in an inconsistent state. If you want to rerun this test, you should create a new test rather than trying to rerun this one.\nERROR: Wrong type for entry id 'NTASKS'"
```

I'm not sure why this is related to python3 but using 2.7 fixed the problem.

**Comment by xylar** [comment]
Yes, the first error is the same as in #2895.

**Comment by jhkennedy** [comment]
There are 2 issues reported here, the first being a duplicate and a downstream (component) problem and the second being CIME problem (confirmed). 

To better track these issues, I've opened a separate issue for the second one and am closing this issue and making it a duplicate.
