### ISSUE TITLE
seg fault, A_WCYCL20TRS_CMIP6 on Cori

### ISSUE THREAD

**Issue by chengdang** [E3SM-Project/E3SM#2944]
I'm running some tests on Cori-knl with the following code and config: maint-1.0 + new features, A_WCYCL20TRS_CMIP6, ne30_oECv3_ICG

and encountered the following seg fault:

>    1: forrtl: severe (174): SIGSEGV, segmentation fault occurred
>  257: forrtl: severe (408): fort: (3): Subscript #1 of the array NEWLYFORMEDICELOGICAL has value 1 which is less than the lower bound of 4607182418800017407
>  257:
>  934: forrtl: severe (408): fort: (3): Subscript #1 of the array NEWLYFORMEDICELOGICAL has value 1 which is less than the lower bound of 1073741829

I've updated the config_machine files to the latest version, which does not fix this problem.
Any suggestion on how to fix this?
Thanks.

**Comment by darincomeau** [comment]
@chengdang this looks like a bug in the code (uninitialized variable?) - have you tried to bisect the bug, starting with the code for the new features?

**Comment by chengdang** [comment]
@darincomeau thanks for the suggestion! I removed some new features under development by others and the bug is gone. So this is not a lib issue. I'll close the case.
