### ISSUE TITLE
Compset name issue with DTESTM

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#2953]
When trying to run the MPAS ice-only test, I got an error. This used to work.

This is on cori, but I suspect it doesn't matter.

```
cori07% create_newcase --case c --res T62_oEC60to30v3 --mach cori-knl --compiler intel --compset DTESTM --project acme --walltime=0:22:00 --queue=debug
Compset longname is 2000_DATM%NYF_SLND_MPASSI_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST 
Compset specification file is /global/cscratch1/sd/ndk/wacmy/m03-may21/components/mpas-seaice/cime_config/config_compsets.xml
ERROR: Unknown model type, TEST

I _can_ do the following: 

cori07% create_newcase --case c --res T62_oEC60to30v3 --mach cori-knl --compiler intel --compset 2000_DATM%NYF_SLND_MPASSI_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST --project acme --walltime=0:22:00 --queue=debug
Did not find an alias or longname compset match for 2000_DATM%NYF_SLND_MPASSI_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST 
Automatically adding SIAC to compset
Automatically adding SESP to compset
Compset forcing is 
Com forcing is --DO NOT USE FOR LONG SIMULATIONS:present day:
...

I'm not yet sure if it will do what we want, just noting for debugging purposes.
```

We may already know the problem. 
In `components/mpas-seaice/cime_config/config_compsets.xml`
there are trailing whitespaces after the long compset name.  And the `_TEST` may also no longer be needed.

```
Trying this worked:
  <compset>
    <alias>DTESTM</alias>
    <!--lname>2000_DATM%NYF_SLND_MPASSI_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST </lname-->
    <lname>2000_DATM%NYF_SLND_MPASSI_DOCN%SOM_DROF%NYF_SGLC_SWAV</lname>
  </compset>
```

**Comment by jonbob** [comment]
@jgfouca - I ran "git blame" on the file that seems incorrect and your name was associated with these changes, from 2019-04-10. Is there a reason for the "_TEST "?

**Comment by jonbob** [comment]
And thanks for filing this, @ndkeen

**Comment by rljacob** [comment]
You can't trust "git blame" on a CIME file on this side because of the subtree splitting.  Run it on ESMCI.

**Comment by jonbob** [comment]
It's not a CIME file -- it's ~/components/mpas-seaice/cime_config/config_compsets.xml

**Comment by rljacob** [comment]
Oh sorry you're right.  The "_TEST" string can be used in config_components.xml to trigger certain options but I don't think its used for this compset.

**Comment by rljacob** [comment]
telecon discussion:  remove the _TEST string in that compset and add it to e3sm_developer.  @ndkeen can you do that PR?

**Comment by jgfouca** [comment]
@jonbob , the changes I made were:
```
-    <lname>2000_DATM%NYF_SLND_MPASCICE_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST </lname>
+    <lname>2000_DATM%NYF_SLND_MPASSI_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST </lname>
   </compset>
 
   <compset>
     <alias>DTESTM-BGC</alias>
-    <lname>2000_DATM%NYF_SLND_MPASCICE%BGC_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST </lname>
+    <lname>2000_DATM%NYF_SLND_MPASSI%BGC_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST </lname>
```
IE, just changing "MPASCICE" to "MPASSI".

**Comment by jonbob** [comment]
Thanks - I don't know where the "_TEST " came from then. Not a big deal -- I just wasn't sure it was something that got added for a reason.

**Comment by ndkeen** [comment]
OK here is the closed issue.

**Comment by jonbob** [comment]
@ndk - you can probably close the new issue then...
