### ISSUE TITLE
Fix atm build using CMake on anlworkstation

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#2956]
atm build using CMake is not supported on anlworkstation so far.

1) cmake-2.8.12 needs to be upgraded to 3.9 or higher in config_machines.xml.
Applicable versions in softenv are 3.11.1, 3.12.1, 3.12.4, 3.14.3

2) NETCDF_PATH and PNETCDF_PATH needs to be set in config_compilers.xml:
```
<compiler MACH="anlworkstation" COMPILER="gnu">
...
<NETCDF_PATH>$ENV{NETCDF_PATH}</NETCDF_PATH>
<PNETCDF_PATH>$ENV{PNETCDF_PATH}</PNETCDF_PATH>
```
With these changes it seems to work on anlworkstation.

However, in atm.bldlog, the compiler versions seems incorrect:
```
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- The Fortran compiler identification is GNU 4.8.4
```
Note that in config_machines.xml, softenv is set to use gcc-6.2.0
`<command name="add">+gcc-6.2.0</command>`

In pio.bldlog, the expected versions are displayed:
```
-- The C compiler identification is GNU 6.2.0
-- The Fortran compiler identification is GNU 6.2.0
```
Since some other machines (e.g. anvil) use softenv as well, we might need to check if they also have this bug (use default compilers other than specified by softenv).

**Comment by jgfouca** [comment]
Hi @dqwu , sorry, I neglected to test the Cmake stuff on anlworkstation since it's not one of our primary testing platforms. I have a PR coming soon with fixes.

**Comment by dqwu** [comment]
@jgfouca 
Could you please also check atm.bldlog on anvil to see if it prints out expected C/Fortran compiler identifications?

**Comment by jgfouca** [comment]
@dqwu , I don't expect the CMake compiler identification to be accurate. Recall that we aren't setting compilers until deep in our CMakeLists file. This will be resolved in a future refactor.

**Comment by jgfouca** [comment]
@dqwu , can you give me the case you were building? For me, even prior to the CMake PR, I can't get F cases to build due to a problem in csm_share:

```
% ./create_test --no-run ERP_Ln9.ne4_ne4.FC5AV1C-L.anlworkstation_gnu
...
ERROR: /nfs2/acmetest/E3SM/cime/src/build_scripts/buildlib.csm_share FAILED
```

**Comment by jgfouca** [comment]
ERROR:
```
/nfs2/acmetest/E3SM/cime/src/share/util/shr_const_mod.F90:91:6:

 !$omp declare simd(shr_const_isspval)
      1
Error: OpenMP directives at (1) may not appear in PURE or ELEMENTAL procedures
```

**Comment by dqwu** [comment]
I have deleted that line in shr_const_mod.F90 for it to work on anlworkstation. It is a known issue that OpenMP directive is not supported by GNU 6.2.0

**Comment by dqwu** [comment]
It is inconsistent that cime uses GNU 4.8.4 to build atm and uses GNU 6.2.0 to build PIO.
Do you mean that GNU 6.2.0 is still used to build atm code although CMake compiler identification incorrectly shows it is 4.8.4? Why does PIO's build log show accurate compiler identification?

**Comment by jgfouca** [comment]
> Do you mean that GNU 6.2.0 is still used to build atm code although CMake compiler identification incorrectly shows it is 4.8.4?

Yes. The compilers get set after the main CMakeLists file is run. PIO is still being driven by the core Makefile, which sets up arguments to CMake so that it knows what the "real" compile is at launch.
