### ISSUE TITLE
SMS_B.ne4_ne4.FC5AV1C-L-AQUAP.cori-knl_intel.cam-hommexx fails during phase CREATE_NEWCASE

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#2970]
`        ERROR: Command: 'SMS_B.ne4_ne4.FC5AV1C-L-AQUAP.cori-knl_intel.cam-hommexx.20190604_121705_bpk2sw/shell_commands' failed with error 'ERROR: No variable CAM_TARGET found in case' from dir 'SMS_B.ne4_ne4.FC5AV1C-L-AQUAP.cori-knl_intel.cam-hommexx.20190604_121705_bpk2sw'`

Note: this test was part of the integration test suite for cori-knl, but it has been replaced by:
SMS_B.ne4_ne4.F-EAMv1-AQP1.cori-knl_intel.cam-hommexx
This new test does not have this issue.

**Comment by oksanaguba** [comment]
I got the same error on anvil for this test.

**Comment by dqwu** [comment]
@oksanaguba 
Which test fails on anvil?
SMS_B.ne4_ne4.FC5AV1C-L-AQUAP or SMS_B.ne4_ne4.F-EAMv1-AQP1?

**Comment by oksanaguba** [comment]
SMS_B.ne4_ne4.FC5AV1C-L-AQUAP.anvil_intel.cam-hommexx fails.

**Comment by oksanaguba** [comment]
I don't think it is homme related. It can be EAM related?

**Comment by dqwu** [comment]
So SMS_B.ne4_ne4.FC5AV1C-L-AQUAP fails on Cori and anvil, maybe on more machines.
Perhaps that is the reason why it has been replaced by SMS_B.ne4_ne4.F-EAMv1-AQP1 in the e3sm_integration suite.

**Comment by dqwu** [comment]
@jayeshkrishna 
Should we close this issue since it is no longer part of e3sm_integration test suite?
Otherwise we can assign it to someone who is able to fix it for various machines.

**Comment by oksanaguba** [comment]
Can we remove homme label? Homme is just dycore code, the error is coming from cime or cam configs.

**Comment by dqwu** [comment]
@oksanaguba 
OK, removed homme label. I added it because the test name contains homme.

**Comment by dqwu** [comment]
@singhbalwinder 
Is compset FC5AV1C-L-AQUAP valid for integration test?

**Comment by dqwu** [comment]
@oksanaguba 
Since this test is no longer part of the test suite, is it OK to close this issue?
Or do you prefer it to remain open for a fix in cime (or cam configs)?

**Comment by oksanaguba** [comment]
Thank you for asking but I don't think this is up to me. I did not put this test in, we'd better ask person who introduced this test. In https://github.com/E3SM-Project/E3SM/blob/master/cime/config/e3sm/tests.py there is no record for this test, so, how did it come up on cori? I was looking at tests list to trace which commit introduced it.

**Comment by whannah1** [comment]
The "AQUAP" compsets were removed when the aquaplanet mode was restored with PR #2752. Prior to this the "AQUAP" compsets disabled the land component but left the topography in place, so there were mountains of water where the Himalayas used to be. This is obviously a problem for anyone wanting to use the aquaplanet mode for science. Also, I wanted to restore the ability to easily use the various patterns prescribed by the aqua planet inter-model comparison project, so I made new aquaplanet compsets.

**Comment by oksanaguba** [comment]
@dqwu would you please remind me how this issue came up? I cannot find this test on cdash and it is not in tests.py. So, if it is not run, then maybe it is ok to close the issue, thought I still think there is a bug in cime/configs, because CAM_TARGET functionality should work anyway. But there is no motivation to debug this since our other cases with CAM_TARGET work.

**Comment by dqwu** [comment]
@oksanaguba 
I once ran all e3sm_integration tests on Cori, and the old E3SM header is:
```
commit 152fae6e2bc42566bfaea961863d532e4b496766
Merge: c726a77df 8e69ae471
Author: Azamat Mametjanov <azamat@mcs.anl.gov>
Date:   Thu Apr 11 17:38:24 2019 -0500

    Merge branch 'azamat/anvil/backout-version-upgrades' (PR #2850)
    
    Anvil module updates.
    
    [non-BFB] - due to module version changes
```
At that time, SMS_B.ne4_ne4.FC5AV1C-L-AQUAP.XXXX.cam-hommexx was one of the 58 integration tests. It failed with:
`errput: ERROR: No variable CAM_TARGET found in case`

It seems that this test has been replaced by SMS_B.ne4_ne4.F-EAMv1-AQP1.XXXX.cam-hommexx in e3sm_integration suite. That is why you could not find it on cdash or test.py with latest E3SM.

**Comment by oksanaguba** [comment]
Thanks! If you don't mind, I will follow your suggestion and close this.
