### ISSUE TITLE
NetCDF paths and CMake on Summit 

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#2974]
While updating compiler and MPI versions for Summit, I ran into build errors from cmake. The updated module versions are in a pending PR (https://github.com/E3SM-Project/E3SM/pull/2973) in order to replicate this issue. 

As you can see, config_machines.xml has the respective NETCDF_C and FORTRAN_PATHs set. But cmake seems to have trouble finding it. Both cam and clm builds fail with same error. 

This issue is encountered with both PGI and XL compilers. 

https://github.com/E3SM-Project/E3SM/blob/34083d2eacbc2ceb2020f567c6004615f0e5ea4b/cime/config/e3sm/machines/config_machines.xml#L3167
```
<env name="NETCDF_C_PATH">$ENV{OLCF_NETCDF_ROOT}</env>
<env name="NETCDF_FORTRAN_PATH">$ENV{OLCF_NETCDF_FORTRAN_ROOT}</env>
```

```
 24 See also "/gpfs/alpine/cli115/proj-shared/sarat/e3sm_scratch/ibmfne4_june5/bld/atm/obj/CMakeFiles/CMakeOutput.log".
 25 CMake Error at CMakeLists.txt:196 (message):
 26   NETCDF not found: Define NETCDF_PATH or NETCDF_C_PATH and
 27   NETCDF_FORTRAN_PATH in config_machines.xml or config_compilers.xml
 28 ERROR: CMake Error at CMakeLists.txt:196 (message):
 29   NETCDF not found: Define NETCDF_PATH or NETCDF_C_PATH and
 30   NETCDF_FORTRAN_PATH in config_machines.xml or config_compilers.xml
```

**Comment by sarats** [comment]
FYI @worleyph, there is still a problem getting Summit builds after fixing modules.

**Comment by jayeshkrishna** [comment]
@sarats : Does this issue (unable to find NetCDF) occur only after updating the modules (Did cmake find the modules as expected before the update in PR #2973?)?

**Comment by sarats** [comment]
@jayeshkrishna There were missing module errors as the old MPI module is removed. So, we need the updated versions. I don't think anybody else tried it after Summit s/w upgrade.

For sanity check,: 
```
$ cat .env_mach_specific.sh
# This file is for user convenience only and is not used by the model
# Changes to this file will be ignored and overwritten
# Changes to the environment should be made in env_mach_specific.xml
# Run ./case.setup --reset to regenerate this file
source /sw/summit/lmod/7.7.10/rhel7.3_gnu4.8.5/lmod/lmod/init/sh
module purge
module ls
module load DefApps python/3.5.2 subversion/1.9.3 git/2.13.0 cmake/3.13.4 essl/6.1.0-2 netlib-lapack/3.8.0 xl/16.1.1-3 netcdf/4.6.1 netcdf-fortran/4.4.4 spectrum-mpi/10.3.0.0-20190419 parallel-netcdf/1.8.1 hdf5/1.10.3
export COMPILER=ibm
export MPILIB=spectrum-mpi
export OMP_STACKSIZE=128M
export NETCDF_C_PATH=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/netcdf-4.6.1-flee5cwbvbcasa6azvvfwolevlmtth4d
export NETCDF_FORTRAN_PATH=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/netcdf-fortran-4.4.4-bagwe7hxmjhzfuhuqkcdh652cs2cpfrj
export NETCDF_PATH=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/netcdf-fortran-4.4.4-bagwe7hxmjhzfuhuqkcdh652cs2cpfrj
export NETCDFF=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/netcdf-fortran-4.4.4-bagwe7hxmjhzfuhuqkcdh652cs2cpfrj
export ESSL_PATH=/sw/summit/essl/6.1.0-2/essl/6.1
export NETLIB_LAPACK_PATH=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/netlib-lapack-3.8.0-vnf3evngccubuacxu6ngrw3dua2gih2w
export HDF5_PATH=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/hdf5-1.10.3-7lytqbw6z7q4vvjcak53m7ohdcvvawux
export OMPI_MCA_io=romio314
export PNETCDF_PATH=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/parallel-netcdf-1.8.1-mib5e6ivbcesgal3hvzvbwxso3dugyun
```

**Comment by sarats** [comment]
@jayeshkrishna It's not technically unable to find NetCDF, it appears to be CMake which did not detect the environment variables.

**Comment by sarats** [comment]
A related question: has anyone tested master on a machine with separate NetCDF C and Fortran paths after the cmake changes?

**Comment by dqwu** [comment]
@sarats 
According to PR #2922,
It is no-longer enough to have NETCDF settings in the environment, they need to be explicit in the Macros (config_compilers.xml).

One commit of that PR updated anvil like this:
https://github.com/E3SM-Project/E3SM/pull/2922/commits/e3d7f9bce027f99a021dedf15929d0dba1b8bacb

**Comment by jgfouca** [comment]
@dqwu is correct. If you set NETCDF in config_compilers and add CMake in the list of module loads (grab the newest one you can) then things should work. Let me know if that's not the case.

**Comment by sarats** [comment]
@jgfouca It's the need for config_compilers macros that's new. Previously just env vars would suffice.

**Comment by jgfouca** [comment]
@sarats the need for config_machines.xml to load a newish cmake is also new, but it must already be happening for summit if things are working. Glad it's working now.

**Comment by sarats** [comment]
@jgfouca Just FYI, we always loaded cmake module on Summit.  So that helped. 
Btw, thanks for all hard work in cmakefying.
