### ISSUE TITLE
18x4 ne4 F case on Anvil producing NaNs

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2979]
@singhbalwinder noticed that using 4 threads per process on Anvil was leading to some failures. I determined that using an 18x4 decomposition (thus using 2 nodes) for 

     --res ne4_ne4 --compset FC5AV1C-L --compiler intel

fails approximately 70% of the time. When it fails, it either reports NaNs in reprosum, e.g.

     SHR_REPROSUM_CALC: Input contains  0.10000E+03 NaNs and  0.00000E+00 INFs on process       0
      ERROR: shr_reprosum_calc ERROR: NaNs or INFs in input

 right after the output

      nstep, te        1   0.32979826924921732E+10   0.32981382047614088E+10   0.21501496260284258E-02   0.98515947862105517E+05

or, more rarely, 

      ERROR: lapack_wrap.F90: Singular matrix detected in band_solve

right after 

      nstep, te        2   0.26361939827774453E+10   0.32982129229854422E+10   0.91980619458198216E+01   0.98035837897079109E+05

If the simulation gets beyond these two failure points (e.g., through timestep 3), it always completes successfully. A decomposition of 9x4 (i.e. one node) always succeeds. I do not know if this means that the MPI library is involved or not.

Adding debug statements identifies these NaNs at various points in the simulation, but the process of printing them out can also "move them around", eliminating them from one field or elements of that field, but showing up then in other locations, indicating a memory issue? Increasing the OMP stack size had no apparent effect.

I was able to eliminate the problem by adding a critical section around the second large loop in the routine parcel_dilute in zm_conv.F90, starting at line 3667:

     !$omp critical
     do k = pver, msg+1, -1
        do i=1,ncol
     ...
        end do ! Loop for columns
     
     end do  ! Loop for vertical levels.
     !$omp end critical

Starting the critical section just inside of the k-loop did not eliminate the problem however. I see nothing about the code in this loop that appears suspect, though it is a little complicated. Perhaps this is a compiler error? The sensitivity to the thread count (which means that threads for one process per node are on both sockets) might indicate an architecture issue, but this should still work. The NaNs occur on most/all processes, and this critical section should be a local to a process, so the weird thread layout for a couple of processes should be irrelevant here?

So, I do not have a real diagnosis, and the 'fix' is not acceptable, but perhaps someone else has some insight, or suggestions as to what to do.

**Comment by worleyph** [comment]
Note that I also tried adding a thread barrier at the top of this loop instead of the "omp critical", and it still produced NaNs.

**Comment by oksanaguba** [comment]
@worleyph how did you locate that particular loop? i am just trying to learn. thanks!

**Comment by worleyph** [comment]
@oksanaguba , unfortunately, just manual labor. After I gave up on using write statements to chase NaNs, I tried commenting out OpenMP parallel do directives on the major loops, and identified that commenting out the one in phys_run1 (on the loop containing the call to tphysbc) was enough. (Based on the appearance of the NaNs, either dp_coupling or the physics was the probably source of the problem). After re-enabling this and determining that manually restricting the number of active threads to 1 still worked but any number greater than 1 failed, I started adding omp critical/end critical around code, decreasing the scope and moving inside subroutines as I went. Fortunately this had a single location. It still required 142 experiments (many of them repeats as it doesn't fail every time even when a build is buggy). Each experimental run took 1-2 minutes, with time for scheduling the jobs, modifying and rebuilding. Kind of mindless, but also kind of time consuming.


142 experiments

**Comment by whannah1** [comment]
@worleyph, have you tried printing out the value of "msg" on every column to see if the limits of the loop are getting messed up?

**Comment by worleyph** [comment]
@whannah1 , not yet. I'll give that a try next. I'm still befuddled that this occurs "the first time" or not at all. Doesn't seem like a typical threading issue.

**Comment by worleyph** [comment]
Haven't tried the suggestion by @whannah1  yet, but tried

     a) built with DEBUG=TRUE: worked fine (3 different experiments, so probably works)
     b) zm_conv compiled with -O0, but rest of the model compiled normally: got NaNs the first time

both without the critical section in parcel_dilute. So, issue is not just with zm_conv compilation, but lower compiler optimization does avoid the error if applied widely enough. May add some more files to the Depends file to lower optimization, just to check if it is still a kind of  "local" compilation issue.

**Comment by worleyph** [comment]
I've continued to try adding files to Depends (including all of physics/cam) and also with only threading in ATM. I though that I was making progress, identifying as few as 4 files that need -O0 for the model to run successfully. However, all I did was decrease the frequency of the failures, and all of my "successes", with the possible exception of the DEBUG build, have proven to still be failures. I'll try to confirm that the DEBUG build can run reliably, but I am essentially starting over.

**Comment by worleyph** [comment]
Debug build still seems to work (5 experiments, over time), though will keep testing a few more times to try to be sure this time.

**Comment by worleyph** [comment]
Latest: 

- DEBUG applied just to ATM (in this F case) worked (so far)
- looking at elements of DEBUG for intel, adding only '-heap-arrays' compiler flag (to normal flags, e.g. -O2) also worked (so far)

will proceed with seeing which files need the additional '-heap-arrays' tp work. If necessary, could just apply this for all ATM when using intel on Anvil. If so, I'll check the performance implications for a case that works without this (2 or 3 OpenMP threads?)

**Comment by singhbalwinder** [comment]
Thanks @worleyph for continuing to work on this issue. Probably you already know that heap array flag asks the compiler to allocate heap (slower) memory rather than the stack memory. I have run into issues before where there wasn't enough stack memory so I had to use this flag to get past the crash point. 

It is interesting to see that everything works okay if we choose heap memory flag. If this is true, the issue is more likely with the memory rather than the threading itself. It will be interesting to see what we find out in the end.

I am also chasing some other issues that I saw while working with the CLUBB code. I will fill in as I learn more about those if they are relevant.

**Comment by worleyph** [comment]
>  If this is true, the issue is more likely with the memory rather than the threading itself. It will be interesting to see what we find out in the end.

But if it was memory, and not threading, you'd think that other thread counts would also have problems. I just now tried 12x6 (instead of 18x4) and 12x6 is working fine (repeated experiments). Also, I did double OMP_STACKSIZE over the default, and nothing changed. I can try increasing it even more and see what happens.

**Comment by worleyph** [comment]
@singhbalwinder , I spoke too soon. Got NaNs when running with 12x6 in my third experiment. (Yay?). I'll focus on memory more seriously now.

**Comment by worleyph** [comment]
@singhbalwinder , I went back to the 18x4 F case (unmodified) and tried again the 64M OMP_STACKSIZE (the default) and saw the usual NaNs. I then also tried 32M, 128M, 256M, and 512M. I got NaNs in all of these cases as well.

**Comment by singhbalwinder** [comment]
@worleyph : I am guessing here so I could be wrong. Assuming that if we add "heap arrays" flag, everything works, it might be that some thread might be asking for more memory than the largest (512M) you have allocated so far for this particular PE-layout. If it is indeed the case, we still need to figure out why.  I do not know how OMP_STACKSIZE works or if there is a way to set it unlimited for testing purposes only. 

Again, I am assuming that with "heap array" flag, everything works. Would it be useful to try setting stacksize to something even larger (e.g. 1G or 2G) just to see if it makes a difference? In some my experiments, I saw the error going away with increasing omp_stacksize (thanks to Az!).

**Comment by worleyph** [comment]
I'll try even larger OMP_STACKSIZE. However, both 36x2 and 24x3 work fine (with 64M OMP_STACKSIZE), while 18x4 and 12x6 fail, and 18x4 fails for up to 512M OMP_STACKSIZE.

**Comment by worleyph** [comment]
Summary so far: Have two workarounds (but no acceptable fixes):

     1) Add a critical section around the second major loop in parcel_dilute in zm_conv.F90

     2) Compile all of CAM with -heap-arrays

It might/should be possible to compile less than all of CAM with -heap-arrays, but compiling all of cam/src/physics/cam was not sufficient, and this does include all of the files that are involved in parcel_dilute, at least "going down". Some of the arrays passed into parcel_dilute as arguments could possibly be the ones that matter and perhaps originate in other files. This still needs to be investigated.

**Comment by worleyph** [comment]
Update: Compiling all of CAM with -heap-arrays when running 18x4 (still) "works" consistently, and is internally BFB. However, it is not BFB with a build using 36x2 and compiled normally. In contrast, 18x4 with the critical section around the loop in parcel_dilute is BFB with the 36x2 run (unmodified) and also works in all experiments that I have tried. I don't know if this non-BFB behavior would be expected when using -heap-arrays or not. The critical section fix appears to be preferred at the moment though.

**Comment by singhbalwinder** [comment]
@worleyph : I am also not sure if we should expect the solutions to be BFB with or without using heap array flag. Do the run start to differ at the very first time step or they differ from the second time step (like we saw earlier)?

**Comment by worleyph** [comment]
@singhbalwinder , I've convinced myself that compiling with -heap-arrays is comparable to changing optimization level, and we don't require the model to be BFB wrt to that. I am not concerned about it. @mt5555 suggested trying a different version of the intel compiler. Perhaps the problem will "go away", especially since it does not occur on Compy. Homme is using a more recent version of Intel on Anvil than is E3SM. I'll give that a try.

**Comment by worleyph** [comment]
@singhbalwinder and @amametjanov , I think that I found the solution to this issue. Add

          <command name="add">+mkl</command>

to

          <modules compiler="intel">

in env_mach_specific.xml, e.g.

         <modules compiler="intel">
           <command name="add">+intel-17.0.0</command>
           <command name="add">+netcdf-c-4.4.1-f77-4.4.4-intel-17.0.0-serial</command>
           <command name="add">+mkl</command>
        </modules>

Apparently by not linking in mkl, the code is calling a not-very-thread-safe linear solver. Using mkl eliminates this issue.

@singhbalwinder , please test this yourself. If it works, please ask @amametjanov to make the change in the correct place for CIME to pick this up when creating a case.

Note that I found this by trying @mt5555 's suggestion to use the same version of the intel compiler that they use for standalone HOMME. This was specified in Mark's .soft file, including ...

     +intel-18.0.3
     +mvapich2-2.3-intel-18.0.3-acme
     +netcdf-4.6.2-intel-18.0.3-mvapich2-2.3-acme
     +netcdf-fortran-4.4.4-intel-18.0.3-mvapich2-2.3-acme
     
     +mkl

I tried building without mkl the first time, and the build failed. I then added this in, and the build using intel/18.0.3 ran this case with no problem (7 experiments). Just to be sure that the version of the intel compiler was the issue, I then added mkl to the build using intel/17.0.0 , and this also worked. (I've run 11 experiments without a failure so far ... seems like this is a reliable fix.)

**Comment by worleyph** [comment]
@singhbalwinder,

> You are amazing! 

I'll take credit for being too stubborn to give up, but nothing much that I tried was very productive until Mark made his suggestion. Thanks again to @mt5555 for his input.

**Comment by mt5555** [comment]
thanks @worleyph , great work!

**Comment by amametjanov** [comment]
Explicit load `+mkl` should not be necessary, because `+intel-17.0.0` key already sets MKLROOT:
```
$ soft-dbq +intel-17.0.0 | grep MKLROOT
    MKLROOT = /soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.0-yko5ui4sbwwehofzpvvdx3k5cii6n63s/compilers_and_libraries_2017.0.098/linux/mkl

$ soft-dbq +mkl | grep MKLROOT
    MKLROOT = /soft/mkl/11.0.5.192/mkl
```

If adding `+mkl` is fixing the issue, then this indicates a bug in the default MKL bundled with Intel v17 compiler.

**Comment by mt5555** [comment]
a bug in the intel17 mkl library could be an explanation.  In which case what about +mkl-11.0.5.192 ?

**Comment by amametjanov** [comment]
I'm not sure. If this MKL version is from 2011, mixing with 2017 compiler may bring issues. I think Jason is looking into this with e3sm_developer tests.

**Comment by mt5555** [comment]
yikes, using mkl for 2011 sounds like a terrible idea.  what about:

+intel-mkl-2017.3.196

**Comment by mt5555** [comment]
https://software.intel.com/en-us/articles/which-version-of-the-intel-ipp-intel-mkl-and-intel-tbb-libraries-are-included-in-the-intel

+mkl-11.0.5.192 is from 2013, so not quite as old as 2011, but still pretty old.  
+intel-mkl-2017.3.196 might be v2017, update 3, bundled with intel 17 update 4.  

From Pat's comments above, I think he confirmed the bug is fixed with both intel17 and intel18 when using "+mkl", so I dont think we know yet if any of the newer versions of mkl will fix this problem.

**Comment by worleyph** [comment]
> From Pat's comments above, I think he confirmed the bug is fixed with both intel17 and intel18 when using "+mkl", ...

For the reproducer used in this issue, correct. I have not tried different PE layouts or other cases.

**Comment by mt5555** [comment]
@worleyph : can you run your reproducer with

intel17 +  intel-mkl-2017.3.196 
intel18 (with default mkl)

this would confirm that the problem is in the particular version of mkl with intel17.0.0.   It could also be a "feature" of all modern versions of mkl

**Comment by rljacob** [comment]
Since Intel19 is available, I've been thinking we should move all platforms to 18 or 19 and drop 17.  That's an option.

**Comment by worleyph** [comment]
@mt5555 , in my original experiments, as mentioned above, I tried intel18 without specifying +mkl, and the build failed. Is this the same as

     intel18 (with default mkl)

? It built and then ran correctly with +mkl . 

Note that the build failure when not specifying +mkl was

     ld: cannot find -lmkl_intel_lp64
     gmake: *** [/lcrc/group/acme/worleyph/acme_scratch/anvil/FC5AV1C-L-ne4_ne4_intel18/bld/e3sm.exe] Error 1

**Comment by worleyph** [comment]
@mt5555 , first example with 

     intel17 + intel-mkl-2017.3.196

worked, but second test died with the NaNs.

**Comment by worleyph** [comment]
@mt5555 , is there a different experiment you want me to try? Yet a different version of mkl, with either intel 17, 18, or 19? I'd need guidance on what mkl libraries are available, and on how to use intel 19 (and any libraries that need version changes).

**Comment by mt5555** [comment]
From @amametjanov 's message, I was under the impression each intel came with a version of MKL.  But running the command he suggested, soft-dbq +intel-18.0.3 | grep -i mkl, suggests not.   So my suggested of intel18 + default mkl doesn't make sense, sorry about that.  

Since intel17 + intel-mkl-2017.3.196 failed, I suppose there is no point running intel18 + intel-mkl-2017.3.196

Current options seem to be (1) live with this and dont run strange thread combinations, (2) use mkl from 2013.  

We could also request Anvil install mkl 2018, or mkl 2019?

**Comment by worleyph** [comment]
@mt5555 , unfortunately, it is no longer "strange thread combinations", but rather thread counts > 3. (using 6 threads also has the same problem, and this is not a 'strange' choice for Anvil.)

We could also use one of the original workarounds: critical section in parcel_dilute or compiling CAM with -heap-arrays (though the latter generates very slow code). Not really proposing either of these, but these appear to play a part in the issue.

**Comment by rljacob** [comment]
Do we know what exactly the limits/rules are for combining an Intel compiler version and an mkl version?

**Comment by mt5555** [comment]
@worleyph : on the off chance that this is compiler related, can you try intel18 + mkl-2017.3.196?

**Comment by worleyph** [comment]
@mt5555 , as with intel17 experiment, intel18+mkl-2017.3.196 worked the first time, but generated NaNs the second time. (Not sure what is going on with this 'second test failure' pattern, but it happens often, but not always.)

**Comment by rljacob** [comment]
Using soft-dbq to list compiler and its "internal" mkl versioni:
+intel-17.0.0:   MKL 2017.0.098
+intel-17.0.1:   MKL  2017.1.132
+intel-17.0.2:  MKL 2017.2.174
+intel-17.0.4:  Not included
+intel-18.0.3:  Not included

So the +intel-mkl-2017.3.196 softkey should be used with Intel-17.0.4 and intel-18.0.3.  We shouldn't use any of the other mkl softkeys on anvil centos6 or "+mkl" because they are very old.

NOTE: In 2016, MKL changed its versioning from "10.1", "11.2" to start with the year.   "2017" was the first to do that.   So anything with aversion of "11.3" or less is from 2016 or earlier.  See slide 3 in https://collegeville.github.io/CW3S19/WorkshopResources/Presentations/CW3S19_Knepper.pdf

Also, I'm told a given MKL version is tested with the current Intel compiler and at most 2 versions back.

**Comment by worleyph** [comment]
Random experiments ... 

a) modified Macro.(c)make to emulate PGI options: -llapack -lblas and removed -mkl, then built/ran without +mkl in env_mach_specific.xml.

Died with NaNs

b) as in (a) modified Macro.(c)make to emulate PGI options: -llapack -lblas and removed -mkl, BUT then built/ran WITH +mkl in env_mach_specific.xml.

Worked (tried three times).

Looking in build log files and see -llapack -lblas and do not see -mkl. Looked in build environment file, and see, for example,

     MKLROOT=/soft/mkl/11.0.5.192/mkl
     ...
     LIBRARY_PATH=(some mkl references)
     ...
     FPATH=/soft/mkl/11.0.5.192/mkl/include
     MIC_LD_LIBRARY_PATH=(some mkl references)
     ...
     LD_LIBRARY_PATH=.(some mkl references)
     ...
     MIC_LIBRARY_PATH=.(some mkl references)
     ...
     CPATH=(some mkl references)
     NLSPATH=(some mkl references)
     ...
     LD_RUN_PATH=/soft/mkl/11.0.5.192/mkl/lib/intel64
     ...
     INCLUDE=/soft/mkl/11.0.5.192/mkl/include:...

so, picking up mkl implementations of lapack and blas? or an implicit link to mkl that I am not seeing in the build files?

**Comment by singhbalwinder** [comment]
So essentially having +mkl (loading mkl) is helping to avoid this error. Can we check which blas and lapack is being linked to the executable using something like `ldd` command?

**Comment by sarats** [comment]
FYI, I previously used MKL link line advisor to determine appropriate flags for threaded application runs etc.
https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor/

For instance, latest MKL version with 64-bit integer support would have:
```
 -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_ilp64.a ${MKLROOT}/lib/intel64/libmkl_intel_thread.a ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group -liomp5 -lpthread -lm -ldl
```

I'm unsure about the softenv module situation on Anvil but wondering if adding +mkl configures LIBRARY paths or flags that make it threadsafe.

**Comment by worleyph** [comment]
Don't know if it means anything (or what it means), but I put the omp critical in parcel_dilute, so that the code runs without adding +mkl, then ran with and without +mkl. The results differ by nstep,te = 1. First differences show up for the output starting with

      nstep=           2  time=  4.166666666666666E-002  [day]
       u     =  -0.124798388898807E+03  0.119861366902396E+03  0.966862326160788E+06
       ...

which is before

(default)

      nstep, te        1   0.32979826924883456E+10   0.32981382047584338E+10   0.21501496378164677E-02   0.98515947862105488E+05

(with +mkl)

      nstep, te        1   0.32979826918317533E+10   0.32981382068406358E+10   0.21501875046473630E-02   0.98515947880015563E+05

So, not obviously wrong, but seems a little large for just changing the version of the math library. omp critical is eliminating the NaNs, but may not be addressing all of the issues? Without a real diagnosis, I am still concerned about this.

**Comment by worleyph** [comment]
@singhbalwinder ,

     Can we check which blas and lapack is being linked to the executable using something like ldd command?

I haven't found any way to check this. I tried building without --static-intel:  this built and ran fine (though with some error messages after the job finished), but did not get any useful information from ldd.

**Comment by worleyph** [comment]
Just now got a failure using 3 threads per process (18x3 for the ne4 case) when not specifying +mkl (so using the default mkl version associated with the intel17 compiler).

**Comment by worleyph** [comment]
Comparing numerics with the omp critical around the loop in parcel_dilute for both with and without +mkl when using intel 17. While the two different versions of mkl differ, as indicated above, they are internally consistent, with identical atm.logs (for the lines that should be identical in a BFB run) when comparing 18x1, 18x2, 18x3, and 18x4. That is reassuring.

**Comment by worleyph** [comment]
Note that the 18x3 failure without +mkl was without the OMP CRITICAL in parcel_dilute.

**Comment by worleyph** [comment]
Also getting same numerics with and without OMP CRITICAL in parcel_dilute, when they work (for a fixed MKL version).

**Comment by amametjanov** [comment]
Tried various MKL link lines for the 2017 version: static vs. dynamic and sequential vs. omp threading layer -- still getting NaNs.

As an option, we can put in a check to env_mach_specific to prevent threads of a process from getting assigned to two different sockets:
```
<arg name="thread_count">-c $SHELL{case $OMP_NUM_THREADS in 1|2|3|6|9|18)echo $OMP_NUM_THREADS;;*)echo bad thread_count=$OMP_NUM_THREADS;exit 1;;esac}</arg>

```

**Comment by worleyph** [comment]
@amametjanov 

     As an option, we can put in a check to env_mach_specific to prevent threads of a process from getting assigned to two different sockets:

this is not sufficient. Even "normal" thread counts are exhibiting this behavior. Got a failure with 18x3 (just once though) and 12x6 (pretty regularly).

**Comment by amametjanov** [comment]
Hi Pat, please try out PR #3182. In my tests, 72x1, 36x2, 24x3, 12x6, 8x9, 4x18 all worked fine for 1 initial and 10 sequential restart runs that are 5 days each, total of 55 days. The updated MKL link line should eliminate the errors that you observed for "normal" thread counts.

**Comment by worleyph** [comment]
Hi Az, I'm off the project until mid to late October. Probably coming back then, but we'll see if I am missed :-). In any case, I won't be looking at this until then. Also, are the "non-normal" thread choices, eg.g x4, still broken? If so, still seems like a bug to me.

**Comment by amametjanov** [comment]
Yes, when some threads of a process are on one socket and remaining threads on another, NaNs appear in various places without a pattern. Intel v18 didn't help either. I think the two 45MB L3 caches on two sockets are not getting sync'ed.

We can keep the issue open. That update will just prevent a case from being set up with such thread counts for now.

**Comment by worleyph** [comment]
Your diagnosis makes sense, except that the earlier fix (using -mkl and linking in the really old MKL)  eliminated all of the NaNs. Still seems like it is something related to the MKL library.

**Comment by worleyph** [comment]
Sorry - that was not as clear as I had hoped. Adding +mkl and linking in the old version of MKL eliminated the NaNs (and similar failures) even for cases with threads that cross sockets, e.g., 4 OpenMP threads per process .

**Comment by worleyph** [comment]
Just now tested latest master with 18x4 decomposition, and with 18x3 and 12x6, and multiple times, and all experiments worked fine (both 5 day and 1 month) and all were BFB with each other. Appears that the problem has been addressed, and that evern "weird" thread counts are now working (and still supported). Closing this issue.
