### ISSUE TITLE
Model crashes when online interpolation is turned on

### ISSUE THREAD

**Issue by singhbalwinder** [E3SM-Project/E3SM#2983]
The current master code crashes when online interpolation is turned on via namelist option:
`interpolate_output = .true.`

The model crashes with error:
```
105: forrtl: severe (408): fort: (3): Subscript #1 of the array CAM_GRIDS has value -1 which is less than the lower bound of 1
105: e3sm.exe           0000000000A7BC76  cam_grid_support_        2207  cam_grid_support.F90
105: e3sm.exe           00000000009189CC  cam_history_mp_h_        3711  cam_history.F90
105: e3sm.exe           000000000098E161  cam_history_mp_ws        4629  cam_history.F90
```
I tracked it down and found out that `CAM_GRIDS`'s index `gridind` is not initialized for procs >96 for ne4 grid. It has a value of -1 (default value), when it it not initialized. This explains why the model works when run with 1 or 2 nodes on Anvil (36 cores per node). As soon as we ask for 3 or more nodes, it fails. Anvil asks for 4 nodes by default for ne4 grid therefore it fails on Anvil.

The reason `gridind` is not initialized is due to `par%dynproc` which is FALSE for all procs >96. `par%dynproc` is set in `components/homme/src/share/parallel_mod.F90`. I do not know this code well so I would appreciate if anybody can suggest me how should we resolves this issue. Tagging @AaronDonahue as he has most recently added new features to this part of the code.

I ran into another issue when I ran the model with interpolation turned on for PE layout using very few processors. The code fails with the following error:
```
4: forrtl: severe (408): fort: (3): Subscript #1 of the array BBUFFER has value -1 which is less than the lower bound of 1
4: e3sm.exe           000000000411FA4C  interp_mod_mp_wri         303  interp_mod.F90
```
I was able to get past it by commenting out the following OpenMP directive in  `components/cam/src/dynamics/se/interp_mod.F90`:
`!$omp parallel do private (ie, bpter, icol)`

The code was failing with only some PE layouts while working with others so I thought it might be an OpenMP or MPI issue. I didn't look into it further. Tagging @amametjanov and @worleyph if they have any insights.

**Comment by worleyph** [comment]
For the first error, @mt5555 will have to give the definitive answer, and @amametjanov is also familiar with this aspect of the code, but the dynamics does not support using more processes than elements. The interpolate_output logic probably should not be trying to use processes that do not contain an element (or am I not understanding the error condition)?

**Comment by rljacob** [comment]
Sounds like if this option is on, it should error out if there are to many processes.   @mt5555 ?

**Comment by mt5555** [comment]
I'm hoping it's an easy fix - to add some (if (dyn_pes) ) code in front of the interpolation calls.   But I haven't had time to work on this yet.

**Comment by singhbalwinder** [comment]
I recently met with another error on Compy when I ran ne4 with 160 tasks (default). The error went away when I used <= 96 tasks. I am not sure why the model complains on some machines about it while working fine on others. May be we should let the model error out when somebody tries to use more # of tasks than the # of elements. That way, we will never run into this situation and online interpolation will work fine. It would be better if it is a configure/compile time error (rather than a run time error) with a clear and explicit error message.

**Comment by mt5555** [comment]
I looked into this further.  It would be difficult to support interpolated output with physics  PEs > dynamics PEs.   so for now I will add an abort() statement if interpolated I/O is turned in this case.

However, we do want to allow physics PEs > dyn PEs, as the physics an use more PEs then the dynamics.  

For future reference: 

The I/O is called by the physics by all the physics PEs.   For interpolated output, these routines need to initialize some data structures.  These data structures are initialized by a routine in the dycore.  Currently, the dycore routines can only be called by the dyanmics PEs, and thus this data is not initialized.  In the case of inteprolated output, the physics PEs that are not dynamics PEs will not have any data, but they still need correct metadata.   All access to this metadata probably needs to be protected by if (dyn_pes) statements. 

 


That's because the I/O is called by all the physics PEs, and all these PEs need to initi

but the interpolation initiailizaiton routines routines are

**Comment by mt5555** [comment]
@singhbalwinder : when e3sm test were you using to trigger the above errors?  I'd like to run that test to make sure PR #3064 will fix the omp errors on low processor counts, and correctly abort when using too many atm tasks.

**Comment by singhbalwinder** [comment]
I was using SMS.ne4_ne4.FC5AV1C-L on Compy with the Intel compiler. This test uses 160 tasks. It should abort with the same error as the PE layout (for ne4) is still not fixed for Compy yet.

**Comment by mt5555** [comment]
I ran that test on Anvil, but it doesn't turn on interpolated output?

**Comment by singhbalwinder** [comment]
Sorry, I thought you were trying to replicate the error I described in one of my comment [above](https://github.com/E3SM-Project/E3SM/issues/2983#issuecomment-506868310). 

For interpolated output, you would need `interpolate_output = .true.` in the `atm_in` namelist. The same test should fail. Originally, `REP_Ln5.ne4_ne4.FC5AV1C-L.cam-intrp_out_frq5ts` was failing.
