### ISSUE TITLE
CLM fails to build on Summit

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/E3SM#2985]
The following case fails to build on Summit (IBM compiler) with Sarat's latest branch (sarats/machinefiles/summit-june5 - PR #2973 - v1.1.0-beta-1636-g55772a4),

-compset FC5AV1C-H01B -res ne120_oRRS18v3

The issue seems to be a minor bug in the write statement and the fix below works,

```
diff --git a/components/clm/src/external_models/emi/src/emi_data_definition/E
MI_DataMod.F90 b/components/clm/src/external_models/emi/src/emi_data_definition/
EMI_DataMod.F90
index 8191444..77e9bfb 100644
--- a/components/clm/src/external_models/emi/src/emi_data_definition/EMI_Data
Mod.F90
+++ b/components/clm/src/external_models/emi/src/emi_data_definition/EMI_Data
Mod.F90
@@ -882,7 +882,7 @@ contains
     integer, optional :: rank
 
     if (present(rank)) then
-       write(iulog,*),rank,') ' // trim(this%name)
+       write(iulog,*) rank,') ' // trim(this%name)
     else
        write(iulog,*)trim(this%name)
     endif

```

**Comment by sarats** [comment]
Same issue reported at https://github.com/E3SM-Project/E3SM/issues/2976
Thanks Jayesh for suggesting the fix. 
Close both issues when merging a PR.

**Comment by sarats** [comment]
@bishtgautam Can you (or someone else from land) include this fix when you get a chance?
