### ISSUE TITLE
Set CXX_LINKER flag to FORTRAN for pgi

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#2993]
In config_compilers.xml, there is a comment on this flag:
```
CXX_LINKER (CXX/FORTRAN): When C++ code is included in the build, do
we use a C++ or Fortran linker?
```
This flag is set to FORTRAN for gnu and intel, but it is set to CXX for pgi and pgiacc.
```
<compiler COMPILER="gnu">
  ...
  <CXX_LINKER>FORTRAN</CXX_LINKER>

<compiler COMPILER="intel">
  ...
  <CXX_LINKER>FORTRAN</CXX_LINKER>

<compiler COMPILER="pgi">
  ...
  <CXX_LINKER>CXX</CXX_LINKER>

<compiler COMPILER="pgiacc">
  ...
  <CXX_LINKER>CXX</CXX_LINKER>
```
On Summit, when pgi compiler is used to build E3SM with pio2 (thus CXX is required), the linker uses mpiCC to create e3sm.exe and causes some link errors:
```
mpiCC  -o bld/e3sm.exe ...
/usr/bin/ld: bld/pgi/spectrum-mpi/nodebug/nothreads/mct/lib/libmpeu.a(m_ioutil.o): undefined reference to symbol 'flush_'
/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/pgi-19.4-6acz4xyqjlpoaonjiiqjme2aknrfnzoy/linuxpower/19.4/lib/libpgf90rtl.so: error adding symbols: DSO missing from command line
```
Was there a reason for pgi to use CXX for CXX_LINKER?

**Comment by jgfouca** [comment]
@dqwu , sorry for the slow response. I'm not responsible for summit configuration, so I'm going to reassign to someone else.

**Comment by sarats** [comment]
Just FYI, you may need to look at old Titan configuration etc. to see what extra libraries if any are needed for linker when changing this. Ideally, this testing would be better off with a configuration that uses C++ (sub-)components.

**Comment by dqwu** [comment]
@minxu74 @jgfouca 
Looks like this issue has been partially fixed by PR #3043, the commit (Fix summit cxx linking) is:
https://github.com/E3SM-Project/E3SM/commit/48fc5ebb8c6c0fa16ec6b7e9357eaca2bfd59c5a

PS, pgiacc still uses CXX for CXX_LINKER on Summit, which might be updated as well.

**Comment by dqwu** [comment]
I tested latest E3SM master branch with pgi compiler on Summit, no link errors to build e3sm.exe with scorpio.

**Comment by jgfouca** [comment]
It looks like this issue can be closed.
