### ISSUE TITLE
Issue with `-compset F_SCAM5 -res T42_T42` on maint-1.0

### ISSUE THREAD

**Issue by chihchen24** [E3SM-Project/E3SM#3002]
When submitting a job on cori, I got the following error message:
ERROR: module command /opt/modules/default/bin/modulecmd python load craype PrgEnv-intel cray-mpich failed with message:
/opt/modules/default/bin/modulecmd: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory

I am using maint-1.0 of E3SM.

**Comment by ndkeen** [comment]
This was an error we might see in repos from about a year ago. That module issue should have been fixed quite a while ago.  How old is your repo?

I just cloned a fresh repo for maint-1.0 branch and started a test. It is building now, but if there was a problem with the modules, it would have probably already failed.

Your comment states that the message was at submit time. I'm wondering if this was an old case that you are wanting to run again and therefore see the issue at submit time?

**Comment by chihchen24** [comment]
I just got the code from the github by executing:
git clone -b maint-1.0 --recursive https://github.com/E3SM-Project/E3SM.git

Then, I have to modify env_mach_specific.xml
craype craype/2.5.13 to  craype craype/2.5.15
cray-mpich cray-mpich/7.6.2 to cray-mpich cray-mpich/7.7.3

before I can execute case.set, case,build, and the error comes when I execute case.submit

**Comment by ndkeen** [comment]
The test `SMS.T62_oQU120_ais20.MPAS_LISIO_TEST` seems to be working with the current maint-1.0 branch.  

I did not make need to make any changes. I wouldn't think the module version changes you mentioned would have an issue though.

**Comment by chihchen24** [comment]
I have a colleague at LLNL reporting the same issue.
What we did was a clean clone by executing:
git clone -b maint-1.0 --recursive https://github.com/E3SM-Project/E3SM.git

Could you please try doing the same test?

Thanks a lot!

**Comment by ndkeen** [comment]
I just did a test using a clean checkout and it works.  The test I used was `SMS.T62_oQU120_ais20.MPAS_LISIO_TEST`

Have you tried without making any changes?

**Comment by chihchen24** [comment]
Hi,

Sorry for the delay in responding to your question. I was at a workshop the past few days.

No, I did not make any change to the code. I was trying to do a SCM run (using run_e3sm_scm_ARM97.csh)

when it got to ./case.setup, I got:
ERROR: module command /opt/modules/default/bin/modulecmd python swap craype craype/2.5.13 failed with message:
craype(3):ERROR:105: Unable to locate a modulefile for 'craype/2.5.13'

I have to modify env_mach_specific.xml to switch to craype/2.5.15.

Then, case.setup & case.build both went fine.

When I executed ./case.submit, I got:
ERROR: module command /opt/modules/default/bin/modulecmd python load craype PrgEnv-intel cray-mpich failed with message:
/opt/modules/default/bin/modulecmd: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory

I have also tried checking out the master branch, and I got the same errors as using maint-1.0

Thank you again for your help on this.

**Comment by ndkeen** [comment]
You should not need to change that module version.  I'm wondering if that run_e3sm script is pulling a an older repo? Can you share? Can you try with the latest repo?

**Comment by chihchen24** [comment]
Yes, I was pointing the code to an older version of E3SM indeed.

I have fixed it by pointing to two branches I am working with.
1) maint-1.0:
I get the message of
ERROR: Multiple matches (at create_newcase)

2) the master branch
it got to case.build and the error is:
ERROR: /global/u2/c/cchen24/code/E3SM/cime/src/build_scripts/buildlib.mpi-serial FAILED, cat /global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/build/mpi-serial.bldlog.190620-120031

and in the log file, it says:
gmake -f /global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/case_scripts/Tools/Makefile  -C /global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/build/intel/mpi-serial/nodebug/nothreads/mct/mct/mpi-serial  CIME_MODEL=e3sm  compile_threaded=FALSE CASEROOT="/global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/case_scripts" CASETOOLS="/global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/case_scripts/Tools" CIMEROOT="/global/u2/c/cchen24/code/E3SM/cime" COMP_INTERFACE="mct" COMPILER="intel" DEBUG="FALSE" EXEROOT="/global/u2/c/cchen24/code/SCM_runs//run_e3sm_scm_ARM97/build" INCROOT="/global/u2/c/cchen24/code/SCM_runs//run_e3sm_scm_ARM97/build/lib/include" LIBROOT="/global/u2/c/cchen24/code/SCM_runs//run_e3sm_scm_ARM97/build/lib" MACH="cori-knl" MPILIB="mpi-serial" NINST_VALUE="c1a1l1i1o1r1g1w1i1e1" OS="CNL" PIO_VERSION="1" SHAREDLIBROOT="/global/u2/c/cchen24/code/SCM_runs//run_e3sm_scm_ARM97/build" SMP_PRESENT="FALSE" USE_ESMF_LIB="FALSE" USE_MOAB="FALSE" CAM_CONFIG_OPTS="-phys cam5 -scam -nlev 72 -clubb_sgs -nospmd -nosmp -chem none" COMPARE_TO_NUOPC="FALSE" USE_ALBANY="FALSE" USE_PETSC="FALSE"  MODEL=mpi-serial /global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/build/intel/mpi-serial/nodebug/nothreads/mct/mct/mpi-serial/Makefile.conf
gmake: Entering directory '/global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/build/intel/mpi-serial/nodebug/nothreads/mct/mct/mpi-serial'
/global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/case_scripts/Tools/mkSrcfiles
cp -f Filepath Deppath
/global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/case_scripts/Tools/mkDepends  Deppath Srcfiles > Depends
gmake: Leaving directory '/global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/build/intel/mpi-serial/nodebug/nothreads/mct/mct/mpi-serial'
cat: Filepath: No such file or directory
cat: Srcfiles: No such file or directory
%file_modules
%file_includes
@check_includes

gmake: *** No rule to make target '/global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/build/intel/mpi-serial/nodebug/nothreads/mct/mct/mpi-serial/Makefile.conf'.  Stop.
ERROR: cat: Filepath: No such file or directory
cat: Srcfiles: No such file or directory
%file_modules
%file_includes
@check_includes

gmake: *** No rule to make target '/global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/build/intel/mpi-serial/nodebug/nothreads/mct/mct/mpi-serial/Makefile.conf'.  Stop.

I have attached the script and sorry about the confusion.
Thanks again for your help.

[run_e3sm_scm_ARM97.csh.txt](https://github.com/E3SM-Project/E3SM/files/3311750/run_e3sm_scm_ARM97.csh.txt)

**Comment by ndkeen** [comment]
OK, naming the script run_e3sm doesn't make it a "run_e3sm" script, which I realize doesn't have a great definition. For example, I don't see where the script is downloading the repo.

**Comment by chihchen24** [comment]
Here is the script that I use:
https://github.com/E3SM-Project/scmlib/blob/master/run_e3sm_scm_ARM97.csh

For the two branches I use:
1) maint-1.0
I executed:
git clone -b maint-1.0 --recursive https://github.com/E3SM-Project/E3SM.git
to get the code (then I renamed it as E3SM_maint-1.0)

2) master branch
I executed:
git clone https://github.com/E3SM-Project/E3SM.git
cd E3SM
git submodule update --init 
to get the code

**Comment by ndkeen** [comment]
I think the problem is the following.

```
cori09% ./create_newcase -case case  -compset F_SCAM5 -res T42_T42
ERROR: Multiple matches
```

I don't see this with master.

**Comment by chihchen24** [comment]
With master, I got to case.build, and the error message is:
ERROR: /global/u2/c/cchen24/code/E3SM/cime/src/build_scripts/buildlib.mpi-serial FAILED, cat /global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/build/mpi-serial.bldlog.190620-120031

**Comment by ndkeen** [comment]
Have you run this script on any machine with E3SM? It sorta looks like CESM. It also does not look like the issue is particular to Cori.

I don't think I'm supposed to be debugging your script here, but I simplified it and it build/submitted for me. Job has not yet run.

If you look into that bldlog that the above error points to (which we can't for yours as we don't have permission), you will see that there is some confusion about the directory structure.

Attaching what I used, which would need to be done in cime/scripts of a repo that works for `-compset F_SCAM5 -res T42_T42`

I think the issue of it not working with maint-1.0 is that the pattern to match this compset/resolution is finding more than one. It's not clear if we need to fix this on maint-1.0 or not. Do you need a particular version of the repo or would master be OK?

[tmp-run_e3sm_scm_ARM97.csh.txt](https://github.com/E3SM-Project/E3SM/files/3312360/tmp-run_e3sm_scm_ARM97.csh.txt)

**Comment by chihchen24** [comment]
The script is for SCM runs for E3SM obtained from:
https://github.com/E3SM-Project/scmlib/blob/master/run_e3sm_scm_ARM97.csh

When using the master branch, it stopped at building the model and the error is
ERROR: /global/u2/c/cchen24/code/E3SM/cime/src/build_scripts/buildlib.mpi-serial FAILED, cat /global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/build/mpi-serial.bldlog.190620-120031

I have changed the permission of my home directory.
I wonder if you could take a look at my case:
/global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97

Thanks.

**Comment by chihchen24** [comment]
Just checking in with you to see if you have got a chance to look at my case yet.

Thanks a lot!

**Comment by ndkeen** [comment]
Were you able to see the script I attached? It worked for me.

**Comment by chihchen24** [comment]
No. Could you please attach your script again?

Thanks.

**Comment by chihchen24** [comment]
OK, I believe you referred to tmp-run_e3sm_scm_ARM97.csh.txt

I modified your script and used the master branch.
I am getting the same error at build, and the message is:
Building mpi-serial with output to file /global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/build/mpi-serial.bldlog.190626-110820
   Calling /global/u2/c/cchen24/code/E3SM/cime/src/build_scripts/buildlib.mpi-serial
ERROR: /global/u2/c/cchen24/code/E3SM/cime/src/build_scripts/buildlib.mpi-serial FAILED, cat /global/u2/c/cchen24/code/SCM_runs/run_e3sm_scm_ARM97/build/mpi-serial.bldlog.190626-110820

This is what I got last week as well using the master branch.

**Comment by ndkeen** [comment]
What happens if you do NOT modify the script I attached?

**Comment by chihchen24** [comment]
The original script is not pointing to any tag.
Here is the error I got when executing your script without modification:
./create_newcase: Command not found.
run_e3sm_scm_ARM97: No such file or directory.

**Comment by ndkeen** [comment]
That script is just a collection of commands.  And those commands, such as create_newcase, need to be run from the cime/scripts directory of the repo of interest.  So I thought you would try it inside a recent version of master.

**Comment by chihchen24** [comment]
Indeed, it works within the master branch by executing all the commands in the script.

Thanks a lot.

**Comment by rljacob** [comment]
So master works.  See #3020 for maint-1.0.
