### ISSUE TITLE
git complains about rrtmpg external when checking out old branch

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#3004]
If you start from latest master and checkout and old branch, git will complain about all the files in the submodule rrtmgp/external:
```
[jaco316@compy-e E3SM]$ git checkout  shz0116/cam/erf
error: The following untracked working tree files would be overwritten by checkout:
(list all files in components/cam/src/physics/rrtmgp/external)
Please move or remove them before you can switch branches.
```

You can force the branch checkout by adding "-f".  But this doesn't happen with other modules that don't exist in the old branch like kokkos.

Was rrtmpg/external not added correctly?

**Comment by rljacob** [comment]
Actually the files its complaining about seem to be the ones that were deleted before conversion to a submodule.

https://gist.github.com/rljacob/2795c71c0ff3536c05ec1dd89d3b7357

**Comment by jgfouca** [comment]
@rljacob , yes, the conversion of a subdirectory to a submodule seems to be handled a bit awkwardly by git. Not much we can do about it though.

**Comment by rljacob** [comment]
So that's the only submodule we have that replaced an existing directory?
