### ISSUE TITLE
Issue building BGC compsets using maint-1.1 branch on compy

### ISSUE THREAD

**Issue by kvcalvin** [E3SM-Project/E3SM#3016]
@maltrud is having troubles running BGC compsets on compy. He tried to add machine definitions to the v1.1 based on Az’s branch that works for other simulations.  Those files are in:
/qfs/people/malt823/e3sm_repo/20190624_BDRC_CNPCTC20TR_OIBGC_compy/cime/config/e3sm/machines

But, the build for PIO fails with a netcdf problem regardless of the adjustments he tries:

/compyfs/malt823/e3sm_scratch/20190624.BDRC_CNPCTC20TR_OIBGC.ne30_oECv3.compy/build/pio.bldlog.190625-102650

**Comment by singhbalwinder** [comment]
I met this error on maint1.0 and @jayeshkrishna helped me to resolve this. The fix is here (cime/src/externals/pio1/pio/pionfput_mod.F90.in): https://github.com/E3SM-Project/E3SM/pull/2877/files#diff-46185b1f6650e0d70d79fb4e63471a2d

**Comment by maltrud** [comment]
thanks @singhbalwinder .  i'll give it a try.

**Comment by kvcalvin** [comment]
Thanks @singhbalwinder. Mat says this is now working.

**Comment by rljacob** [comment]
@jayeshkrishna can you explain what that fix does?
