### ISSUE TITLE
get_BGC.sh no longer working

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#3022]
The script get_BGC.sh (in components/mpas-source/src/core_ocean) is used to download the BGC code so that git passwords are not requested in the middle of a compile (when you are not paying attention and forget that this may be needed). There is also a script get_cvmix.sh, for cvmix source, which still works.

When working correctly, the first time you execute get_BGC.sh after a new E3SM clone or after a new version of MPAS-O requires an update to the BGC code, I get (on Anvil)

     $ ./get_BGC.sh
      ** Using git to acquire BGC source. ** 
     Enter passphrase for key '/home/worleyph/.ssh/id_rsa': 

After entering my passphrase, if I execute this again, I get

     $ ./get_BGC.sh
      BGC version is current. Skip update

With current master, every time I execute ./get_BGC.sh it requests a passphrase, and when trying to build E3SM, there it (also) requests a passphrase, e.g. on Compy

     Enter passphrase for key '/qfs/people/worl312/.ssh/id_rsa':

(but compilation then completes successfully).

I have observed this on both Compy and Anvil with latest master. It broke very recently.

**Comment by xylar** [comment]
@worleyp, we recently changed the tag that is pointed in the get_BGC.sh script. However, no other recent changes have been made:
https://github.com/MPAS-Dev/MPAS-Model/blame/e3sm/develop/src/core_ocean/get_BGC.sh

Could you confirm that the problem persists with a fresh clone of E3SM? But even if so, the script should have only asked you once to update the BGC code in your current checkout and then left you alone. @markpetersen, any idea why this is happening?

**Comment by xylar** [comment]
I see what it is. I put in the long tag but it's checking against the short tag here
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/get_BGC.sh#L25

@markpetersen, can you make a bug fix for this? I'm currently on travel.
