### ISSUE TITLE
Improve HOMME's cmake logic to check compiler in a CUDA build

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/E3SM#3049]
Currently, when HOMME has to check if it's a GPU build, cmake inspects the name of the C++ compiler for the substring `nvcc`. This breaks when building with the MPI wrappers, using the standard way of modifying MPI's undelying C++ compiler (i.e., changing the OMPI_CXX env variable), since the C++ compiler name is still `mpicxx` (with a different back-end).

A better way to check that the C++ compiler is indeed `nvcc_wrapper` from Kokkos would be to try to run the compiler with the flag `--nvcc-wrapper-show` (which is peculiar to `nvcc_wrapper`) and check the output. `nvcc_wrapper` would output a string a long the line of `nvcc -ccbin g++ -arch=sm_70` while any other compiler would generate an error/warning about the unrecognized option, plus an error because no file was specified.

**Comment by pbosler** [comment]
Another option is to use `Kokkos_generated_settings.cmake`, e.g., lines 26--38 here: https://github.com/E3SM-Project/COMPOSE/blob/master/CMakeLists.txt

**Comment by bartgol** [comment]
The generated settings do not change the cxx compiler though. So you're still stuck with whatever cmake picked up.

**Comment by pbosler** [comment]
Fixed with PR #3044
