### ISSUE TITLE
Threading bug in HOMME reduction_mod

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/E3SM#3072]
There appears to be a threading bug in
```
    e3sm/components/homme/src/share/reduction_mod.F90
```
exposed, for example, by calling
```
    a = 3.0
    b = 4.0
    a = ParallelMin(a, hybrid)
    b = ParallelMin(b, hybrid)
    print *, 'mbe',a,b
```
The bug is as follows: In the first call, all threads reach the barrier at
reduction_mod.F90:389. Now imagine that one or more threads linger at that
barrier, while one thread races ahead. It completes the call at
reduction_mod.F90:84 and returns. Then the second ParallelMin call starts, and
this fast thread makes it to the implied barrier at reduction_mod.F90:369,
having written to `red%buf`. The slow threads now catch up, returning to
reduction_mod.F90:84. But now they access data from the overwritten
`red_min%buf`.

This can be fixed by putting a barrier before the `omp single` in each
`pmin_`/`pmax_` impl. This is reasonable because the write to the buffer must be
protected. (Edit: Fixed after Oksana's comment below; thanks.)

I suspect this bug does not show up in practice because the use pattern is to
call ParallelMin, then ParallelMax. This ends up working because, first, these
use different buffers; second, the barrier in ParallelMax effectively protects
the buffer used in ParallelMin.

**Comment by oksanaguba** [comment]
Barrier before critical did not help for my example. Barrier before single did help.

**Comment by ambrad** [comment]
Yes, thanks. I meant before the `omp single`.
