### ISSUE TITLE
FC5AV1C-04P2.ne30_ne30 failing on cori-knl and cori-haswell

### ISSUE THREAD

**Issue by xuezhengllnl** [E3SM-Project/E3SM#3085]
The error message in e3sm.log:
2680: forrtl: severe (174): SIGSEGV, segmentation fault occurred
2680: Image              PC                Routine            Line        Source
2680: e3sm.exe           0000000004487CED  Unknown               Unknown  Unknown
2680: e3sm.exe           0000000003CF7600  Unknown               Unknown  Unknown
2680: e3sm.exe           0000000001916FA0  radar_simulator_          230  radar_simulator.f90
2680: e3sm.exe           000000000190DB04  mod_cosp_radar_mp         172  cosp_radar.F90
2680: e3sm.exe           00000000017D3805  mod_cosp_simulato         105 cosp_simulator.F90
2680: e3sm.exe           0000000001496072  mod_cosp_mp_cosp_         615  cosp.F90
2680: e3sm.exe           0000000001492BEB  mod_cosp_mp_cosp_         194  cosp.F90
2680: e3sm.exe           0000000001049AB4  cospsimulator_int        3922  cospsimulator_intr.F90
2680: e3sm.exe           00000000007B364A  radiation_mp_radi        1572  radiation.F90
2680: e3sm.exe           0000000001187706  physpkg_mp_tphysb        2747  physpkg.F90
2680: e3sm.exe           0000000001181111  physpkg_mp_phys_r        1047  physpkg.F90
2680: e3sm.exe           00000000005006B7  cam_comp_mp_cam_r         250  cam_comp.F90
2680: e3sm.exe           00000000004EC929  atm_comp_mct_mp_a         577  atm_comp_mct.F90
2680: e3sm.exe           000000000042D0DF  component_mod_mp_         737  component_mod.F90
2680: e3sm.exe           000000000040CFF7  cime_comp_mod_mp_        2790  cime_comp_mod.F90
2680: e3sm.exe           000000000042CD5D  MAIN__                    133  cime_driver.F90
2680: e3sm.exe           000000000040A80E  Unknown               Unknown  Unknown
2680: e3sm.exe           000000000459AA79  Unknown               Unknown  Unknown
2680: e3sm.exe           000000000040A6F9  Unknown               Unknown  Unknown

**Comment by ndkeen** [comment]
I counter with these 2 passing tests on cori-knl using aster as of today: 

`create_test SMS_Ln5.ne30_ne30.FC5AV1C-04P2 SMS_D_Ln5.ne30_ne30.FC5AV1C-04P2`

**Comment by lxu16** [comment]
I met the same error last week on cori. Uou might want to try switch off "-cosp" in your runscript to see if it succeed?

**Comment by xuezhengllnl** [comment]
Thanks @lxu16 
I tried to run it without "-cosp" and it worked, which is consistent with the error message. However, I need to switch on "-cosp" to get the cosp simulator output for the model diagnostics.

**Comment by lxu16** [comment]
@xuezhengllnl Did you try to define cosp_lite=.true. in the namelist and use "-cosp" in the runscript? Just to check it works and the output variables you need for the model diagnostics.

**Comment by xuezhengllnl** [comment]
> @xuezhengllnl Did you try to define cosp_lite=.true. in the namelist and use "-cosp" in the runscript? Just to check it works and the output variables you need for the model diagnostics.

It is working with cosp_lite. Thanks!
