### ISSUE TITLE
compset DTESTM still needs adjustments to work

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#3096]
I thought we had fixed this already or at least had an issue open.

The DTESTM compset is for testing ICE only and we found the fix (or at least work-around) by simply removing a space in `components/mpas-seaice/cime_config/config_compsets.xml`

I wanted to remind us of the details here:

```
2019-07-30 18:23:16: CREATE_NEWCASE FAILED for test 'SMS.T62_oEC60to30v3.DTESTM.cori-knl_intel'.
Command: /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-july2019-upgrade/cime/scripts/create_newcase --case /global/cscratch1/sd/ndk/acme_scratch/cori-knl/mfjuly19/SMS.T62_oEC60to30v3.DTESTM.co
ri-knl_intel.r06 --res T62_oEC60to30v3 --compset DTESTM --test --machine cori-knl --compiler intel --project acme  --output-root /global/cscratch1/sd/ndk/acme_scratch/cori-knl/mfjuly19  --walltime 00
:34:00
Output: Compset longname is 2000_DATM%NYF_SLND_MPASSI_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST 
Compset specification file is /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-july2019-upgrade/components/mpas-seaice/cime_config/config_compsets.xml
ERROR: Unknown model type, TEST

```

And here is what I changed in a different repo to allow things to work as expected:
(remove space)

```
--- a/components/mpas-seaice/cime_config/config_compsets.xml
+++ b/components/mpas-seaice/cime_config/config_compsets.xml
@@ -11,7 +11,8 @@
 
   <compset>
     <alias>DTESTM</alias>
-    <lname>2000_DATM%NYF_SLND_MPASSI_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST </lname>
+    <!--lname>2000_DATM%NYF_SLND_MPASSI_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST </lname-->
+    <lname>2000_DATM%NYF_SLND_MPASSI_DOCN%SOM_DROF%NYF_SGLC_SWAV_TEST</lname>
   </compset>
```

**Comment by jonbob** [comment]
@ndk - it looks like that issue was inadvertently closed on June 25. I think for that old issue @rljacob had asked you to make a PR? Do you want to take it on? Or for me to?

**Comment by ndkeen** [comment]
OK, I just could not recall where we left things and github-searching proved unfruitful. Is this the change we want? Note that this file also has another line that may have an extra space. And for that matter, should we check all of these entries for trailing spaces? Or does it make sense to adjust the python that parses the line?

**Comment by ndkeen** [comment]
closing and re-opening https://github.com/E3SM-Project/E3SM/issues/2953
