### ISSUE TITLE
Upgrade spectrum-mpi module on Summit

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#3114]
On Summit, the current default spectrum-mpi module is:
`spectrum-mpi/10.3.0.1-20190611`

PS, "module avail spectrum-mpi" shows this version only.

If we purge this latest version and load spectrum-mpi/10.3.0.0-20190419,
"module list" marks it as a hidden module:
```
spectrum-mpi/10.3.0.0-20190419 (H)
  Where:
   H:  Hidden Module
```

This suggests that spectrum-mpi/10.3.0.0-20190419 is deprecated on Summit.
However, it is still the specified version in latest config_machines.xml:
```
      <modules compiler="ibm" mpilib="!mpi-serial">
	    <command name="load">spectrum-mpi/10.3.0.0-20190419</command>
      </modules>
      <modules compiler="pgi.*" mpilib="!mpi-serial">
	    <command name="load">spectrum-mpi/10.3.0.0-20190419</command>
      </modules>
      <modules compiler="gnu" mpilib="!mpi-serial">
	    <command name="load">spectrum-mpi/10.3.0.0-20190419</command>
      </modules>
```
If spectrum-mpi/10.3.0.0-20190419 is used, a low-res F case (e.g. --compset FC5AV1C-H01B --res ne4_ne4) fails on Summit:
SIGSEGV - Segmentation violation in procedure ncmpiio_open

Switching to spectrum-mpi/10.3.0.1-20190611 seems to work.

**Comment by whannah1** [comment]
I've had luck by removing the version completely when running with the ECP fork. I also had to remove the versions from other libraries and that seemed to fix some issues we were having.

**Comment by sarats** [comment]
We explicitly mention software versions in master to record what was known to work  (last known good configuration) and keep track of changes in software environment.
