### ISSUE TITLE
compile error related to sbetr

### ISSUE THREAD

**Issue by xuchongang** [E3SM-Project/E3SM#3125]
@bishtgautam, @jinyuntang, @wjriley , The current clm configure file refer to external_models/sbetr/src/Applications/soil-farm/CENT_ECACNP 
https://github.com/E3SM-Project/E3SM/blob/aae9dfafdf2899a1bd5402a7e7cab8daec007378/components/clm/bld/configure#L686
which does not exist in the most recent version of code for sbetr within E3SM: 

git@github.com:ACME-Climate/sbetr.git. 

This result in the compile errrors. It woulbe great to update the configure file to resolve this compile error.

**Comment by rgknox** [comment]
@xuchongang , I've run into some compile issues with sbetr too, but they were resolved after reloading all of the submodules.  From the root E3SM folder:

git submodule update --init --recursive

Note, it doesn't like doing this if you have uncommited changes:

**Comment by xuchongang** [comment]
Ryan,
  Thank you very much for the suggestion. I have resolved this issue by
replacing the the bishtgautam/fixes-for-e3sm-cmake branch of sbetr.

yours
Chonggang
