### ISSUE TITLE
Problems with GNU-built E3SM executables on Cori after SW upgrade

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#3127]
I had found that any test using GNU would build OK, but fail at runtime immediately with errors that look like:

```
160: seg 0, mem 0: remap(0x43afe000,0x4277000,0x4277000,0x3,0x2aaab2ab0000) failed, error 14
192: seg 0, mem 0: remap(0x43afe000,0x4277000,0x4277000,0x3,0x2aaab2ab0000) failed, error 14
 85: seg 0, mem 0: remap(0x43afe000,0x4277000,0x4277000,0x3,0x2aaab2ab0000) failed, error 14
```

Assuming this was related to something on the system, I reported to NERSC and waited a while.  It was suggested I try to unload the hugepages modules. This is a module that is now default loaded for all Cori users. It can sometimes improve performance of apps, but we did not see any performance impact with these hugepages modules (there are a few different sizes). Simply removing this module and rebuilding, the GNU runs seem to be running. However, several are failing for others reasons.

I'm testing a branch now.

**Comment by whannah1** [comment]
I'm about to issue a PR that will fix an error when trying to build with GNU in debug mode. So this might address some of these failures.

**Comment by ndkeen** [comment]
OK, would that be errors that look like:

```
Error: Argument 'P' of MOD at (1) shall not be zero
```
I count 7 tests that fail at build time with that.

And then quite a few runtime fails. IN fact, these are the only tests that pass with GNU right now:

```
ERS.f09_g16_g.MALISIA.cori-knl_gnu.r01                                                            pass                   e=0  r0=2019-08-14 16:36:35 n=   1 m=  1.6 h=    0 s= COMPLETED c=0 n=
ERS.f19_g16_rx1.A.cori-knl_gnu.r01                                                                pass                   e=0  r0=2019-08-14 16:19:52 n=   1 m=  3.5 h=    0 s= COMPLETED c=0 n=
ERS.ne30_g16_rx1.A.cori-knl_gnu.r01                                                               pass                   e=0  r0=2019-08-14 16:12:31 n=   1 m=  4.5 h=    0 s= COMPLETED c=0 n=
ERS_Ld5.T62_oQU120.CMPASO-NYF.cori-knl_gnu.r01                                                    pass                   e=0  r0=2019-08-14 15:44:59 n=   2 m= 12.1 h=    0 s= COMPLETED c=0 n=
SEQ.f19_g16.X.cori-knl_gnu.r01                                                                    pass                   e=0  r0=2019-08-14 15:52:57 n=   1 m= 11.1 h=    0 s= COMPLETED c=0 n=
SMS.ne30_f19_g16_rx1.A.cori-knl_gnu.r01                                                           pass                   e=0  r0=2019-08-14 16:36:33 n=   1 m=  1.5 h=    0 s= COMPLETED c=0 n=
```

**Comment by whannah1** [comment]
Yes, PR #3128 will fix that build error.

**Comment by ndkeen** [comment]
Closing as https://github.com/E3SM-Project/E3SM/pull/3129 should allow for GNU-built exe's to at least run.
