### ISSUE TITLE
Reduce debugging output from MOSART

### ISSUE THREAD

**Issue by amametjanov** [E3SM-Project/E3SM#3150]
At https://github.com/E3SM-Project/E3SM/blob/master/components/mosart/src/riverroute/RtmMod.F90#L2267:

> Please comment out or surround this line with #ifndef NDEBUG ... #endif to activate it for debug runs. A 5-day run produced 122721 writes to e3sm.log.

And at https://github.com/E3SM-Project/E3SM/blob/master/components/mosart/src/riverroute/RtmTimeManager.F90#L734:

> Please comment out or surround this write with #ifndef NDEBUG ... #endif.

**Comment by rljacob** [comment]
@hydrotian please fix this issue.

**Comment by rljacob** [comment]
@liho745 please fix this issue.
