### ISSUE TITLE
case.submit error on anlworkstation

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#3166]
This issue seems to be caused by PR #3155.
Not sure if other machines with a non-batch system are also affected.

It can be reproduced by running a simple F case (--compset FC5AV1C-H01B --res ne4_ne4)
on anlworkstation.

Before that PR is merged, the output information is:
```
...
mach anlworkstation 
resubmit_num 0
2019-08-29 11:28:43 CASE.RUN HAS FINISHED
Submitted job case.run with id None
```
After that PR is merged, the output information is:
```
...
mach anlworkstation 
resubmit_num 0
2019-08-29 11:38:43 CASE.RUN HAS FINISHED
ERROR: No result from jobs [('case.run', None)]
```
CaseStatus file also shows:
```
...
2019-08-29 11:38:43: case.run success 
 ---------------------------------------------------
2019-08-29 11:38:43: case.submit error 
ERROR: No result from jobs [('case.run', None)]
```

**Comment by jayeshkrishna** [comment]
A temporary fix for this issue would be to specify that the machine does not have a batch system in the command line,

**Comment by jayeshkrishna** [comment]
@jgfouca might know better about this issue, but it seems to me that CIME is only reading the configuration information in the case of a resubmit,
