### ISSUE TITLE
Issue with build.setup on Cori

### ISSUE THREAD

**Issue by lpassarella** [E3SM-Project/E3SM#3187]
I'm having an issue setting up the E3SM on Cori using the current master branch. I get the following error:

`Calling /global/project/projectdirs/acme/lpass/E3SM/components/clm/cime_config/buildnml
ERROR: Command: '/global/project/projectdirs/acme/lpass/E3SM/components/clm/bld/configure    -comp_intf mct -phys clm4_5 -phys clm4_5 -cppdefs -DMODAL_AER -usr_src /global/project/projectdirs/acme/lpass/E3SM/cime/scripts/ne4_mmf/SourceMods/src.clm' failed with error '** source directory does not exist: /global/project/projectdirs/acme/lpass/E3SM/components/clm/src/external_models/fates/main' from dir '/global/project/projectdirs/acme/lpass/E3SM/cime/scripts/ne4_mmf/Buildconf/clmconf'

**Comment by lpassarella** [comment]
I am unsure how to solve this. I tried just manually adding the directory but there were multiple missing directories

**Comment by jonbob** [comment]
@lpassarella - can you tell me the command you used to create that case? And what you've done after creating it?

**Comment by lpassarella** [comment]
sure,

I run this command 

> ./create_newcase -compset FC5AV1C-L -case ne4_mmf -res ne4_ne4 -project acme

and then 

> ./case.setup

**Comment by jonbob** [comment]
That's close, but it will need the machine and compiler specified as well. Something more like:
```
./create_newcase --case /global/homes/j/jonbob/E3SM-cases/test1 --compset GMPAS-IAF --mach cori-knl --res T62_oEC60to30v3 --compiler intel```

**Comment by whannah1** [comment]
Did you sync/update your submodules?
    git submodule sync ; git submodule update --init
That usually fixes this type of problem for me.

**Comment by lpassarella** [comment]
I tried both of those things and still got the same error. When I tried to update the submodules, it updated most and then I got an error

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:E3SM-Project/scorpio.git' into submodule path '/global/project/projectdirs/acme/lpass/E3SM/externals/scorpio_classic' failed
Failed to clone 'externals/scorpio_classic'. Retry scheduled
Cloning into '/global/project/projectdirs/acme/lpass/E3SM/components/cam/src/physics/rrtmgp/external'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by jonbob** [comment]
You may have to try again

**Comment by whannah1** [comment]
You should be ok anyway, since you probably aren't using those submodules.

**Comment by brhillman** [comment]
@whannah1 I think all builds use scorpio now (new name for PIO)

**Comment by lpassarella** [comment]
I figured out the issue. It would not find the public key to download the submodule repos from my server, so I just changed them all in the .gitmodule file to the public url.

After syncing and updating again I was able to successfully run the model.

Thanks everyone for your help!
