### ISSUE TITLE
STEND_CLUBB

### ISSUE THREAD

**Issue by xuezhengllnl** [E3SM-Project/E3SM#3220]
The model output variable STEND_CLUBB from clubb_intro.F90 is misleading now. It is the tendency of static energy from CLUBB and the unit of this variable should be something like kJ kg-1s-1. However, the long name defined for STEND_CLUBB is 'Temperature tendency' with the unit of 'k/s'. People might misuse it as the temperature tendency from CLUBB and be surprised by the huge value (1000 times larger than they would expect because of cpair). If they don't know the reason, they might just simply reduce the value by 1e-3 (instead of 1/cpair).
I would suggest that we either correct the long name and unit of the variable (**option 1**) or divide it by cpair during outfld (and even change it to be TTEND_CLUBB) (**option 2**). 
Hi @kaizhangpnl @wlin7, did you notice this before? Thanks!

**Comment by golaz** [comment]
@xuezhengllnl, thanks for reporting this. I agree that we should correct this inconsistency. I have a slight preference for **option 2** because other physics parameterizations already output temperature tendencies.

**Comment by wlin7** [comment]
@xuezhengllnl , I didn't notice this. I will correct it. I also favors option 2. Thanks.

**Comment by golaz** [comment]
@wlin7, since nobody voiced any strong opinion, I would suggest to go ahead with implementing **option 2** suggested by @xuezhengllnl. Thanks for volunteering to do this.

**Comment by wlin7** [comment]
This is addressed in PR #3274 .
