### ISSUE TITLE
module versions missing on theta with master and maint-1.0

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#3227]
After theta downtime yesterday, I see several module versions we were using are missing. There is a "module load archive" command that will allow us access to those older commands.  Adding the following to `config_machines.xml` seems to be working (after `case.setup -c; case.setup`).

```
      <modules>
        <command name="load">archive</command>
      </modules>
```

(deleting previous comments here as I no longer see that particular issue)

**Comment by sarich** [comment]
@ndkeen It looks like alcf systems has fixed something, can you try again?

**Comment by ndkeen** [comment]
I do seem to have moved past what I reported above -- though we still need to add "module load archive" somewhere in theta env.  It may have been the fact that I had the `archive` module loaded in my current env while making these attempts.  I was able to submit a job in existing case (will not know if there are any issues until it runs) as well as submit a new test case (again has not run).

**Comment by naromero77** [comment]
@ndkeen Are you testing through the debug queue? Those large production jobs seem to take 1 - 2 days to get through the production queue.

**Comment by ndkeen** [comment]
I cant use the debug Q for the tests I'd like to run.

Also, it does look like the modules avail are different than they were when I ran into this issue.
It looks like now, it's only the version of cray-mpich that is not avail on the machine.
Was that intended?  We had been using 7.6.2

```
cray-mpich/7.5.5
cray-mpich/7.6.3
cray-mpich/7.7.2
cray-mpich/7.7.3(default)
cray-mpich/7.7.4
cray-mpich/7.7.10
cray-mpich-abi/7.5.2
cray-mpich-abi/7.5.3
cray-mpich-abi/7.5.4
cray-mpich-abi/7.5.5
cray-mpich-abi/7.6.0
cray-mpich-abi/7.6.2
cray-mpich-abi/7.6.3
cray-mpich-abi/7.7.0
cray-mpich-abi/7.7.2
cray-mpich-abi/7.7.3(default)
cray-mpich-abi/7.7.4
cray-mpich-abi/7.7.10
```

**Comment by ndkeen** [comment]
And also just let me be more clear. Currently, both master (as of today) and maint-1.0 is broken on theta.

This is what it would like for master of today:
```
thetalogin4% create_test SMS_D_Ln5.ne4_ne4.FC5AV1C-L 
Using project from env PROJECT: ClimateEnergy_3
Creating test directory /projects/ClimateEnergy_3/ndkeen/SMS_D_Ln5.ne4_ne4.FC5AV1C-L.theta_intel.20191008_192709_qwfrct
RUNNING TESTS:
  SMS_D_Ln5.ne4_ne4.FC5AV1C-L.theta_intel
Starting CREATE_NEWCASE for test SMS_D_Ln5.ne4_ne4.FC5AV1C-L.theta_intel with 1 procs
Finished CREATE_NEWCASE for test SMS_D_Ln5.ne4_ne4.FC5AV1C-L.theta_intel in 1.289663 seconds (PASS)
Starting XML for test SMS_D_Ln5.ne4_ne4.FC5AV1C-L.theta_intel with 1 procs
Finished XML for test SMS_D_Ln5.ne4_ne4.FC5AV1C-L.theta_intel in 0.279174 seconds (PASS)
Starting SETUP for test SMS_D_Ln5.ne4_ne4.FC5AV1C-L.theta_intel with 1 procs
Finished SETUP for test SMS_D_Ln5.ne4_ne4.FC5AV1C-L.theta_intel in 0.918282 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /projects/ClimateEnergy_3/ndkeen/SMS_D_Ln5.ne4_ne4.FC5AV1C-L.theta_intel.20191008_192709_qwfrct
    Errors were:
        ERROR: module command /opt/modules/default/bin/modulecmd python load craype/2.5.12 cmake/3.11.4 intel/18.0.0.128 PrgEnv-intel/6.0.4 craype-mic-knl cray-mpich/7.6.2 cray-netcdf/4.4.1.1.3 cray-parallel-netcdf/1.8.1.3 failed with message:
        cray-mpich(3):ERROR:105: Unable to locate a modulefile for 'cray-mpich/7.6.2'
        cray-netcdf(3):ERROR:105: Unable to locate a modulefile for 'cray-netcdf/4.4.1.1.3'

Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
At test-scheduler close, state is:
FAIL SMS_D_Ln5.ne4_ne4.FC5AV1C-L.theta_intel (phase SETUP)
    Case dir: /projects/ClimateEnergy_3/ndkeen/SMS_D_Ln5.ne4_ne4.FC5AV1C-L.theta_intel.20191008_192709_qwfrct
test-scheduler took 2.82187604904 seconds
2.049u 0.571s 0:03.33 78.3% 0pf+0w
```

**Comment by sarich** [comment]
I had master working for me earlier today (after adding the archive), now it seems to be broken again. 

I'm not sure if this will fix it, but it looks like there's a problem with the perftools-base module (loaded in by the PrgEnv-intel module). I'll make an issue of it with alcf.

ssh theta
$ module purge
$ module load archive
$ module load perftools-base
perftools-base/6.4.5(142):ERROR:102: Tcl command execution failed: if { [is_avail rca] } {
    if {[module-info mode load]} {
        module load rca
    }
}

**Comment by ndkeen** [comment]
Noting I am able to continue running using "module load archive", which seems to be OK so far.
