### ISSUE TITLE
Add CUDA support in CMake

### ISSUE THREAD

**Issue by mrnorman** [E3SM-Project/E3SM#3232]
I'm adding some cuda files in our ACME-ECP repo, which need to be found and compiled properly. This involves changing the following line in components/CMakeLists.txt from:

```cmake
  file(GLOB MATCHES RELATIVE "${SRCROOT_ABS}/components" "${DIRSEARCH}/*.[Ffc]" "${DIRSEARCH}/*.[Ff]90" "${DIRSEARCH}/*.cpp" "${DIRSEARCH}/*.F90.in" )

```

to

```cmake
  file(GLOB MATCHES RELATIVE "${SRCROOT_ABS}/components" "${DIRSEARCH}/*.[Ffc]" "${DIRSEARCH}/*.[Ff]90" "${DIRSEARCH}/*.cpp" "${DIRSEARCH}/*.F90.in" "${DIRSEARCH}/*.cu" )
```

**Comment by jgfouca** [comment]
Will need to be applied to https://github.com/E3SM-Project/E3SM/pull/3043 . You're the first to use .cu files, so there may be additional tweaks needed to support that suffix.

**Comment by mrnorman** [comment]
Yeah, it could get a bit hairy if someone needs to combine MPI and CUDA in the same file. There's also the question of where CMake looks for "nvcc". I'll try to work some of this out on my ACME-ECP branch.

**Comment by jgfouca** [comment]
@mrnorman , this dropped-off my radar. Do you need anything from me?

**Comment by mrnorman** [comment]
Thanks for the message. I've probably changed how I've done things since I posted this, so it's good to delete this. For my codes, I no loner use the .cu extention. Instead, I use .cpp, and I declare that it's a CUDA file in my CMakeLists.txt. I will probably need help again when we integrate it into the ATM CMake, but let's do that over slack instead.
