### ISSUE TITLE
cprnc executable cannot be found on summit

### ISSUE THREAD

**Issue by crjones-amath** [E3SM-Project/E3SM#3233]
For testing on summit, the executable `/gpfs/alpine/cli115/world-shared/e3sm/tools/cprnc.summit/cprnc` does not appear to exist.

I attempted to follow the instructions in `$CIMEROOT/tools/cprnc/README`, which failed as follows:

```
> ../configure --macros-format=Makefile --mpilib=mpi-serial

ERROR: FakeCase does not support getting value of 'SMP_PRESENT'
```

**Comment by minxu74** [comment]
Sorry. It was purged. I recompiled it with IBM XL compiler and put it /gpfs/alpine/cli115/world-shared/e3sm_olcf/tools/cprnc.summit/. Please let me know if you have any problem on it.

**Comment by crjones-amath** [comment]
Thanks @minxu74 

I just tested it again, and the file is there now, but I received the following error:
```
/gpfs/alpine/cli115/world-shared/e3sm/tools/cprnc.summit/cprnc: symbol lookup error: 
/gpfs/alpine/cli115/world-shared/e3sm/tools/cprnc.summit/cprnc: undefined symbol:
__netcdf_NMOD_nf90_open
```

**Comment by rljacob** [comment]
@minxu74 instead of an executable binary, make cprnc an executable shell script that loads the right modules and then calls the cprnc binary.

**Comment by minxu74** [comment]
@rljacob Thanks. Cool idea. I just made cprnc as a shell script that loads the corresponding modules. 
@crjones-amath so sorry for that. On Summit the cprnc cannot be compiled in a static way, so it depends on some dynamic libs of netcdf, libm, and libc. As suggested by @rljacob I made it as a script. Could you please try it again? Thanks.

**Comment by crjones-amath** [comment]
Thanks for your quick work on this @minxu74! Just tested it and everything seems to be in order.
