### ISSUE TITLE
Restart file name prefix in mpas-seaice buildnml not compatible with e3sm_init

### ISSUE THREAD

**Issue by herrwang0** [E3SM-Project/E3SM#3247]
The name change in c947c07f9627f26a10adeb859b274f198595c1cd (from ``mpascice`` to ``mpassi``) prohibits buildnml to recognize the restart files with the prefix ``mpascice`` in e3sm_init

**Comment by jonbob** [comment]
@herrwang0 - you can work around this by copying the name of the mpascice.rst.XXXX.nc file to mpassi.rst.XXXX.nc. The names changed but not the file contents.

**Comment by herrwang0** [comment]
@jonbob OK, thanks!

**Comment by jonbob** [comment]
Work around fixed the issue for the reporter
