### ISSUE TITLE
Warning about timer polluting e3sm.log files

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#3255]
In `cime/src/drivers/mct/shr/seq_timemgr_mod.F90`, this warning is being triggered quite often and can really be annoying with many MPI ranks:

```        call ESMF_TimeIntervalSet( TimeStep, s=dtime(n), rc=rc )
        if(CurrTime + TimeStep > minStopTime ) then
-          write(logunit,*) subname//" WARNING: Stop time too short, not all components will be advanced &
-                                    &and restarts won't be written"
        endif
```

I've been temporarily commenting the write and have not looked for the cause.

This happens with every repo I've used on cori/theta and with F compsets for sure.

**Comment by rljacob** [comment]
That warning should only be printed by the root node.   Can you open this issue in CIME?

**Comment by ndkeen** [comment]
This has been fixed in CIME. Not sure when it will be merged to E3SM.

**Comment by ndkeen** [comment]
Not sure exactly when this made it into master (from CIME), but using a July 7th master, I no longer see these warnings.
