### ISSUE TITLE
write(iulog,*) should go to atm.log or e3sm.log? 

### ISSUE THREAD

**Issue by mt5555** [E3SM-Project/E3SM#3258]
This code in atm_comp_mct.F90:
  
     if (masterproc) then
          inquire(file='atm_modelio.nml'//trim(inst_suffix), exist=exists)
          if (exists) then
             iulog = shr_file_getUnit()
             call shr_file_setIO('atm_modelio.nml'//trim(inst_suffix), iulog)
          endif
          write(iulog,*) "CAM atmosphere model initialization"
       endif

means that iulog is set to the "atm.log" file on masterproc, but on all other MPI tasks, it will be the default value of 6, meaning that output from these processors goes to e3sm.log.   Is this by design?

**Comment by tangq** [comment]
This is interesting. When I did some MPI tests in CESM/WACCM a while ago, all output went into atm.log. I haven't done anything related to MPI more recent though.

**Comment by jedwards4b** [comment]
@mt5555 yes this is by design - although it should be clear that masterproc is the MPI_TASK=0 of the given component and may not be the global MPI_TASK=0.    We should try to minimize output from components that is not restricted to masterproc.

**Comment by mt5555** [comment]
very good - thanks.
