### ISSUE TITLE
incorrect ocn_co2_type setting for bcrd case

### ISSUE THREAD

**Issue by maltrud** [E3SM-Project/E3SM#3289]
in the file components/mpas-ocean/bld/build-namelist, there is an incorrect setting in the bcrd section:

} elsif ($ocn_co2_type eq 'bcrd' ) {
       add_default($nl, 'config_ecosys_atm_co2_option', 'val'=>"constant");
       add_default($nl, 'config_ecosys_atm_alt_co2_option', 'val'=>"constant");
       add_default($nl, 'config_ecosys_atm_alt_co2_use_eco', 'val'=>".false.");
       add_default($nl, 'config_ecosys_atm_co2_constant_value', 'val'=>$atm_co2_const_val);

the default config_ecosys_atm_alt_co2_option should be "diagnostic" instead of "constant".

**Comment by jonbob** [comment]
closed by [PR #3294](https://github.com/E3SM-Project/E3SM/pull/3294)
