### ISSUE TITLE
HOMME_P24.f19_g16_rx1.A failed on some machines

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#3339]
See
https://my.cdash.org/testDetails.php?test=52191441&build=1739840
https://my.cdash.org/testDetails.php?test=52192925&build=1739857

Reproducible on anlworkstation as well.

For next branch, the failure is caused by PR #3306 (confirmed on anlworkstation).
PS, this PR has been merged to master.

**Comment by rljacob** [comment]
The HOMME test type doesn't quite follow the rest of the test types.  I think it will show "FAIL" when there is just a diff.  Is that right @mt5555 ?

**Comment by rljacob** [comment]
Yes that's right.  These "FAILs" are expected and will be blessed.
