### ISSUE TITLE
shr_sys_irtc is not thread safe

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#3401]
As identified in issue #3395, shr_sys_irtc is not thread safe. I do not know if it is intended to be. As we currently call this in physpkg.F90 in cam/src/physics/cam within threaded loops, we need to at least wrap the calls in critical sections.

Based on experiments on Compy, shr_sys_irtc can be made thread safe if we wrap the whole body of the routine in a critical section, including the call to system_clock. However, even if system_clock is thread safe (why woulnd't it be?) there are local save variables that are updated within the routine, and so are subject to race conditions when called within a threaded region, so most of the body would need to be in a critical section in any case.

**Comment by worleyph** [comment]
@jgfouca , you might report to this to the CIME crowd and see whether this is a feature or a bug. In any case, I'll be addressing the issue in physpkg.F90 without introducing changes in shr_sys_irtc. Note that this function is in cime/src/share/util/shr_sys_mod.F90 .

**Comment by rljacob** [comment]
CIME issue:  https://github.com/ESMCI/cime/issues/3357

**Comment by amametjanov** [comment]
Variables with `save` attribute should be marked `threadprivate` to make accesses to them thread-safe: e.g.
```
diff --git a/cime/src/share/util/shr_sys_mod.F90 b/cime/src/share/util/shr_sys_mod.F90
index 5a04d66535..600696c3af 100644
--- a/cime/src/share/util/shr_sys_mod.F90
+++ b/cime/src/share/util/shr_sys_mod.F90
@@ -215,6 +215,7 @@ integer(SHR_KIND_I8) FUNCTION shr_sys_irtc( rate )
    integer(SHR_KIND_IN)      :: count_max
    integer(SHR_KIND_IN),save :: last_count   = -1
    integer(SHR_KIND_I8),save :: count_offset =  0
+!$omp threadprivate(last_count,count_offset)
 
    !----- formats -----
    character(*),parameter :: subName =   '(shr_sys_irtc) '
```

**Comment by worleyph** [comment]
@amametjanov , looking at the threadprivate description:

     The threadprivate directive specifies that variables are replicated, with each thread having its own copy.

I'm not sure that using threadprivate is correct. last_count and count_offset are used to handle the situation where the underlying hardware timer "wraps", and needs to be independent of indiviudal threads (I think). This may be why the call to system_clock needs to be within the critical section ... if the counter wraps after the call to system_clock but before a thread gets into the critical section it may be making a decision with the wrong value.

**Comment by worleyph** [comment]
Think that I see how this might work in this context. I’ll give it a try and report back.

**Comment by worleyph** [comment]
@amametjanov , this eliminated the problem in my one experiment (which demonstrated the problem every run before this change). This is a much better fix :-). @rljacob  - what should I do? Should I submit a CIME-only PR with this change to shr_sys_irtc, and then back out the critical section additions in this PR? They both need to go in in order eliminate the bug. I also still need to check that this eliminates the problem on Cori-KNL.
