### ISSUE TITLE
need updated CLM initial data file for A_WCYCL1950S_CMIP6_HR?

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#3410]
On Theta using master, tried

     ./create_newcase ... --compset A_WCYCL1950S_CMIP6_HR --res ne120_oRRS18v3_ICG ...

with

      <entry id="RUN_TYPE" value="startup">
      <entry id="CONTINUE_RUN" value="FALSE">

and the job died during land initialization with

      Reading restart dataset
      Opened existing file
      /projects/ccsm/acme/inputdata/lnd/clm2/initdata_map/clmi.A_WCYCL1950.ne120np4_oRRS18to6v3_ICG_simyr1950_c20180124.nc          98
      check_dim ERROR: mismatch of input dimension       963134  with expected value    239478  for variable topounit

Perhaps user error (tried a case that @ndkeen was using with a branch that diverged awhile back), but pointers to what is wrong with this would then be appreciated as well.

**Comment by bishtgautam** [comment]
@worleyph The specification of land IC within the compset definition is a mess. If you are performing simulation for performance testing (i.e. not for a science run), a workaround would be to comment out:

[components/clm/bld/namelist_files/use_cases/1950_CMIP6HR_control.xml#L22](https://github.com/E3SM-Project/E3SM/blob/master/components/clm/bld/namelist_files/use_cases/1950_CMIP6HR_control.xml#L22)

There hasn't been any clarity on how the land IC will be fixed, so I'm suggesting the workaround.

**Comment by worleyph** [comment]
@bishtgautam , thanks! I got past this by setting finidat = ' '. I'll close this then (since this is a known issue).
