### ISSUE TITLE
ne4 fails with FC5AV1C-L compset

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/E3SM#3430]
The FC5AV1C-L simulation on ne4 using the current master fails midway through month 7 with a "vertical layer thickness" error.

This behavior has been reproduced on several machines:
1) Livermore Computing - quartz - nstep=1705 (user Aaron Donahue)
2) NERSC - Cori-KNL - nstep=1648 (user Chris Terai)
3) Sandiatoss3 - ghost - nstep=1564 (user Ben Hillman)*

git hash: ae200d3bd8f43f1bad7539c659e86794c1a5d463) 
from: Feb 4th, 2020 

*The sandiatoss3 simulation was conducted using the scream-fork but shortly after an upstream merge from e3sm.

**Comment by rljacob** [comment]
@oksanaguba could your group of changes have done this?   Did they change anything about preqx?

**Comment by whannah1** [comment]
@AaronDonahue, can you retry with ne4pg2? We used to get these a lot with the ECP fork. Using the surface flux smoothing option helped us a lot when it was happening at the surface, but that doesn't seem to be necessary anymore with pg2, so I wonder if that could help here. 

Are we sure this didn't happen before? Was anyone running ne4 simulations for that long in the past?

**Comment by rljacob** [comment]
We have a test in extra_coverage that runs ne4 for a year.
https://my.cdash.org/testDetails.php?test=53972301&build=1768082
Looks like it passed on Jan 22, failed on Jan 29.

**Comment by oksanaguba** [comment]
It is most likely CFL thing, I will look today and change namelist.

**Comment by AaronDonahue** [comment]
> @AaronDonahue, can you retry with ne4pg2? We used to get these a lot with the ECP fork. Using the surface flux smoothing option helped us a lot when it was happening at the surface, but that doesn't seem to be necessary anymore with pg2, so I wonder if that could help here.
> 
> Are we sure this didn't happen before? Was anyone running ne4 simulations for that long in the past?

@whannah1 , switching to pg2 at least got as far as nstep=10810 before my run timed out in the debug queue.

**Comment by oksanaguba** [comment]
@AaronDonahue with these changes this compset ran for me for 1 year with ne4:
diff --git a/components/cam/bld/namelist_files/namelist_defaults_cam.xml b/components/cam/bld/namelist_files/namelist_defaults_cam.xml
index b5a29a3..18f2ad8 100755
--- a/components/cam/bld/namelist_files/namelist_defaults_cam.xml
+++ b/components/cam/bld/namelist_files/namelist_defaults_cam.xml
@@ -1497,7 +1497,7 @@
 <nu_div> -1.0 </nu_div>
 
 
-<nu_div hgrid="ne4np4" >  1.25e18 </nu_div>
+<nu_div hgrid="ne4np4" >  5.0e17 </nu_div>
 @@ -1569,7 +1569,7 @@
 <rsplit dyn_target="preqx" hgrid="ne11np4" >  2 </rsplit>
 <rsplit dyn_target="preqx">  3 </rsplit>
 
-<se_nsplit dyn_target="preqx" hgrid="ne4np4" >   2 </se_nsplit>
+<se_nsplit dyn_target="preqx" hgrid="ne4np4" >   4 </se_nsplit>
 
This is just to make it run, not sure which settings will be used for ne4 by default.

**Comment by rljacob** [comment]
What was the recent change to HOMME that made this ne4 case susceptible to CFL violations?

**Comment by oksanaguba** [comment]
One CFL condition, for nu_div (viscosity for div part of velocity), was already violated. Overall, setup was probably only borderline stable for this particular case. Topography and physics coupling can affect stability; what changed is that 2 new nonbfb PRs (energy and gwd taper) came into physics. Most likely, energy changes changed forcing enough to make this case unstable. Note that other similar setups with ne4 with different physics-dynamics coupling (tested in nightlies) also needed smaller timesteps.

**Comment by whannah1** [comment]
Isn't the default physics time step for ne4 set at 2 hours? That kinda seems absurdly long anyway, so wouldn't it be simpler to just reduce that than messing with the dynamics time step and hyperviscosity? For the MMF we have to reduce that to around 30 min for the CRM coupling to be stable anyway.

**Comment by oksanaguba** [comment]
Yes, it is 2 h for ne4. Correct me if i am wrong but i think ne4 is a quick debugging tool, not a realistic setup. Though I can do whatever is decided about timesteps.

**Comment by AaronDonahue** [comment]
My two cents, ne4 is pretty fast because of the small number of DOF.  I think switching to a 1hr timestep, if that worked, would probably not impact the performance by much.  Of course it would be half as fast, but still pretty fast.  My only caution would be to make sure that it isn't the case that dropping the timestep to 1hr is a band-aid for a different problem.

**Comment by whannah1** [comment]
@AaronDonahue I agree. The fact that it used to be more stable is a bit troubling, but I've always wondered if the 2 hour time step might be at the edge of stability. Just thinking about radiation it seems weird to have the sun move so far over a time step.

**Comment by rljacob** [comment]
Maybe @eroesler can comment.  She has been running ne4 cases for long simulation lengths.
