### ISSUE TITLE
maint-1.2 does not build on Cori

### ISSUE THREAD

**Issue by darincomeau** [E3SM-Project/E3SM#3431]
Similar to #3304 , the maint-1.2 branch currently does not build on Cori, due to machine file updates and NERSC dropping support for python 2.7. The following PRs have necessary updates missing in maint-1.2:

Machine file updates: #3097 
Update python 3 in cvmix and BGC: #3308 

After cherry-picked commits from these PRs (and the relevant commits to mpas-source), I can get maint-1.2 to build on Cori-KNL.

**Comment by xylar** [comment]
@darincomeau, are you getting the help you need to get these fixes in?  Maybe @jonbob is the one to make it happen?

**Comment by darincomeau** [comment]
We'll also need #3476 .

**Comment by darincomeau** [comment]
..and this https://github.com/E3SM-Project/E3SM/pull/3404 .

**Comment by darincomeau** [comment]
I'll close this once https://github.com/E3SM-Project/E3SM/pull/3308 gets into maint-1.2.

**Comment by rljacob** [comment]
Someone has to make a separate PR to make that change in maint-1.2.

**Comment by darincomeau** [comment]
Yes I believe @mark-petersen is on it

**Comment by mark-petersen** [comment]
Sorry for the delay. Yes, I need to add the variable vertical GM to Maint 1.2, and @jonbob was going to look at the machine files.

**Comment by darincomeau** [comment]
Yeah @jonbob got the machine files updated with https://github.com/E3SM-Project/E3SM/pull/3494. I was just making a note as to why I hadn't closed this issue yet.

**Comment by darincomeau** [comment]
Addressed by https://github.com/E3SM-Project/E3SM/pull/3513.
