### ISSUE TITLE
incorrect mpi-serial library name in build_model.cmake

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/E3SM#3443]
The mpi-serial library is compiled and named as libmpi-serial.a under cime external sources, but it was set incorrectly in build_model.cmake as follows:

```
  if (MPILIB STREQUAL "mpi-serial")
    set(MPISERIAL "${INSTALL_SHAREDPATH}/lib/lib-mpi-serial.a")
    set(MLIBS "${MLIBS} ${MPISERIAL}")
  endif()
```

Changing "lib-mpi-serial.a" to "libmpi-serial.a" is a simple fix.

**Comment by jgfouca** [comment]
Thanks for finding this. Fix coming.
