### ISSUE TITLE
The problem of create_newcase using "--walltime" option on Summit

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/E3SM#3444]
The usual time format of "--walltime" is "HH:MM:SS", but on Summit, the format of "-W" (walltime) option of bsub is "[hour]minutes". They are not consistent. So when using "--walltime 2:00:00" in create_newcase and the time was propagated to the bsub command and caused an error during case submission.

**Comment by jgfouca** [comment]
Looking at this now.

**Comment by rljacob** [comment]
Is this the same issue? https://github.com/ESMCI/cime/issues/3151

**Comment by minxu74** [comment]
Hmm.  I think they are same.

**Comment by jgfouca** [comment]
@rljacob , thanks for reminding me. Yes, same issue.
