### ISSUE TITLE
Different values of topo in clm2.h0 with different version of PIO

### ISSUE THREAD

**Issue by bishtgautam** [E3SM-Project/E3SM#3447]
Reported by @jayeshkrishna:
>Hi, I am trying to do some baseline comparison tests with SMS_Ln9.ne4_ne4.FC5AV1C-L.anvil_intel.cam-outfrq9s and I see that while generating the baselines with scorpio classic the variable topo(lndgrid) in clm.h0.* has 0 values (all values in the variable are 0s). However with scorpio (PIO_VERSION=2) when comparing the result with the baselines I see that the model generates non-zero values (0s, 7s and 6.*s) . Have you seen this behavior before? What is the expected value for this variable?

**Comment by rljacob** [comment]
Based on the fix in #3448, scorpio-classic must be setting a default of zero if a field is defined but never actually output.  scropio is doing something different.
