### ISSUE TITLE
type error of ninst when "create_newcase --multi-driver --ninst" under py3

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/E3SM#3450]
When creating a new case with "--multi-driver and --ninst", it failed with the type error of ninst. The reason is that in the "create_newcase": 
```
    parser.add_argument("--ninst",default=1,
                        help="Specify number of model ensemble instances. "
                        "\nThe default is multiple components and one driver/coupler. "
                        "\nUse --multi-driver to run multiple driver/couplers in the ensemble.")
```
Under py2, the default option will make the type of ninst integer, but under py3, its type is string still. 

The simple fix is to add "type=int" behind the "default=1". 

The error happened on [if multi_driver and ninst>1:](https://github.com/E3SM-Project/E3SM/blob/d2acc26163bb942b37ede09a5fb66343588aa7e8/cime/scripts/lib/CIME/case/case.py#L991)

**Comment by jgfouca** [comment]
Fixed by #3451
