### ISSUE TITLE
ERS_Ld3.f45_f45.ICLM45ED.anvil_intel.clm-fates failed with scorpio

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#3461]
This failure can also be reproduced on anlworkstation with Address Sanitizer.

First, subroutine initialize1 (CLM initialization first phase, in components/clm/src/main/clm_initializeMod.F90) calls set_fates_global_elements, which calls fates_history_maps.
At this time, num_elements is still 0, element_list is still null.
fates_hdim_levelem is allocated with size 0 (actually occupies 1 byte for some compilers)
```
allocate( fates_hdim_levelem(num_elements))
...
! Make an element array, each index is the PARTEH global identifier index

do iel = 1, num_elements
    fates_hdim_levelem(iel) = element_list(iel)
end do
```
Later, InitPARTEHGlobals is called by subroutine init (initializes the hlm_fates_interface_type, in components/clm/src/main/clmfates_interfaceMod.F90)
It will set num_elements and allocate for element_list
```
select case(hlm_parteh_mode)
case(prt_carbon_allom_hyp)

    num_elements = 1
    allocate(element_list(num_elements))
    element_list(1) = carbon12_element
```
The issue is that fates_history_maps is called before PARTEH globals are initialized.
After this, num_elements is set to 1, but fates_hdim_levelem buffer remains empty.

Next, in htape_timeconst, scorpio is used to put variable fates_levelem
`call ncd_io(varname='fates_levelem',data=fates_hdim_levelem, ncid=nfid(t),flag='write')`

For this ncd_io call, num_elements is 1, but size(fates_hdim_levelem) is 0
scorpio classic is OK with this, but for scorpio, PnetCDF will try to copy 4 bytes of integer data from an empty buffer (actually occupies 1 byte), and cause a segmentation fault.

Besides fates_hdim_levelem, a few other buffers that also rely on num_elements have the same issue.
```
allocate( fates_hdim_levelem(num_elements))
allocate( fates_hdim_elmap_levelpft(num_elements*numpft))
...
allocate( fates_hdim_agemap_levelage(num_elements*nlevage))
```

One workaround would be adding the following check before calling ncd_io:
```
if (num_elements > 0 .and. size(fates_hdim_levelem) > 0) then
    call ncd_io(varname='fates_levelem',data=fates_hdim_levelem, ncid=nfid(t),flag='write')
    call ncd_io(varname='fates_elmap_levelpft',data=fates_hdim_elmap_levelpft, ncid=nfid(t),flag='write')
...
    call ncd_io(varname='fates_agemap_levelage',data=fates_hdim_agemap_levelage, ncid=nfid(t),flag='write')
end if
```

However, this might avoid outputting data that is required by the model developers, so a better fix might be something else in fates.

**Comment by dqwu** [comment]
@bishtgautam 
Feel free to reassign it to a developer who might know how to fix it in fates, thanks.

**Comment by bishtgautam** [comment]
@rgknox, @glemieux, Any thoughts?

**Comment by rgknox** [comment]
Thanks for bringing this issue up @dqwu and @bishtgautam , looking into it.

**Comment by rgknox** [comment]
Here is where the alm_fates object is initialized, which has the call to InitPARTEHGlobals():

https://github.com/E3SM-Project/E3SM/blob/master/components/clm/src/main/clm_instMod.F90#L232

I think a solution is to move InitPARTEHGlobals() into set_fates_global_elements(), and adding an argument to the call that has the NL variable fates_parteh_mode.

**Comment by rgknox** [comment]
I also see that 

call control_setNL("lnd_in"//trim(inst_suffix))

is prior to 

 call initialize1( )

in lnd_cml_mct.F90, so the NL parameters should be usable at this point in the call sequence.

**Comment by rgknox** [comment]
@dqwu , as per your second half of the bug description, I think the fixes I am working on should adress this issue where the allocation for this history dimensions is 0 but the number of elements is >0.  
If anything, where you propose that check , we could have it gracefully fail if the allocation does not match the number of elements.

Will check back in with a patch.

**Comment by dqwu** [comment]
@rgknox 
Thanks for the update. Once you have a patch in a new branch, I can test it on both anvil and anlworkstation to make sure it works.

**Comment by rgknox** [comment]
@dqwu , here are the branches. This does require a synchronized update to FATES, so I will hold on making the pull request until we integrate the FATES side changes.

https://github.com/rgknox/E3SM/tree/rgknox/lnd/fates-init-bugfix
https://github.com/rgknox/fates/tree/rgknox-fix-setglobals

**Comment by rgknox** [comment]
see above

**Comment by dqwu** [comment]
@rgknox 
I used your feature branch to rerun the previously failed test on both anlworkation and anvil.

ERS_Ld3.f45_f45.ICLM45ED.anlworkstation_gnu.clm-fates passed with Address Sanitizer.
ERS_Ld3.f45_f45.ICLM45ED.anvil_intel.clm-fates also passed. PS, it does need the patch from PR #3463 to fix invalid file names written out to the NetCDF output files.

You can go ahead to create a PR, thanks.

**Comment by rgknox** [comment]
Thanks @dqwu , I'm running the land-developer test suite now on our local cluster.  Do you want me to submit this PR now to get things rolling, or wait for the tests to finish?

**Comment by dqwu** [comment]
@rgknox 
You can create the PR later. FYI, so far there are some failed tests (DIFFs) with next branch and we are looking into them.

**Comment by jayeshkrishna** [comment]
The PR could still be created right now, it needs to be merged to next/master once its OPEN for merging.
