### ISSUE TITLE
Possible RRTMGP bug: bandwidth

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/E3SM#3479]
Possible bug reported by Xianglei Huang from UMich:

> 	We are moving along to work with RRTMGP. One thing that we noticed is that the RRTMGP code that we obtained following your previous instruction has some inconsistencies with the RRTMGP reported in Pincus 2019 RRTMGP paper. The details are as follows:
> 
> 	The boundaries for two spectral bands in RRTMGP are not the same as what described in Pincus paper, and they apparently are still the old values used in the RRTMG_LW. For example, the first band should be 0-250cm-1, not 0-350cm-1. We have tested and validated that 0-250cm-1 (as in Pincus paper) should be the right bandwidth. 
> 
> 	In components/cam/src/physics/rrtmgp/radconstants.F90
> Line 37, 2600 should be 2680
> Line 40, 2600 should be 2680
> Line 84, 350 should be 250
> Line 85, 2600 should be 2680
> Line 88, 350 should be 250
> Line 89, 2600 should be 2680
> 
> 	These mistakes might not directly affect the simulations you have done, assuming they have updated the data files correctly but just copied & pasted wrong band widths. It might warrant a double check with developers who put RRTMGP to this code to make sure about this. For us, because we need to recompute surface skin temperature, a wrong bandwidth can mess up the entire simulation.
> 
> 	Xianglei

**Comment by brhillman** [comment]
Thanks for finding this. This shouldn't affect simulations (doing a test now), but should be corrected. The better thing to do is to get the band limits from the absorption coefficient inputdata, as these are subject to change. I will put together a PR with the fix. Note that you can find the proper band limits in the `rrtmgp_coefficients_sw_20181204.nc` and `rrtmgp_coefficients_lw_20181204.nc` files, in the `bnd_limits_wavenumber` variables. Those are the values that should be used for your calculations, as those reflect what is actually used in the code (`radconstants.F90` was provided only for backward compatibility with codes developed for RRTMG).

**Comment by brhillman** [comment]
Also, within the code, the safer way to get the band limits is to use the `kdist%get_band_lims_wavenumber()` method of the `ty_gas_optics_rrtmgp` class. This will always return the bands that RRTMGP is actually using.

**Comment by brhillman** [comment]
Confirmed this doesn't affect the simulation, but working on a more robust setting of these values to avoid confusion in the future.
