### ISSUE TITLE
cosp2 fails cam-cosplite_nhtfrq5 in an odd way: bloated e3sm.exe?

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#3482]
cosp2 in next via PR #3458 fails cosplite test in likely all machines. Take anvil as an example,
The test is SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-cosplite_nhtfrq5

Backtrace of the error messages are 
```
62: forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable SD_CS when it is not allocated
 62: 
 62: Image              PC                Routine            Line        Source             
 62: e3sm.exe           000000000B6F8E36  Unknown               Unknown  Unknown
 62: e3sm.exe           000000000225FFC9  cospsimulator_int        2099  cospsimulator_intr.F90
 62: e3sm.exe           000000000134F8B9  radiation_mp_radi        1572  radiation.F90
 62: e3sm.exe           0000000002742CE6  physpkg_mp_tphysb        2767  physpkg.F90
 62: e3sm.exe           000000000270CFA1  physpkg_mp_phys_r        1047  physpkg.F90
 62: e3sm.exe           0000000000856CE6  cam_comp_mp_cam_r         250  cam_comp.F90
 62: e3sm.exe           000000000082997A  atm_comp_mct_mp_a         574  atm_comp_mct.F90
```
The allocatable variable SD_CS that the above error message refers to is not supposed to be invoked, because it is used only when lradar_sim = .true. (radar simulator), and with cosplite, lradar_sim = .false.

A manually creased case using the same compset FC5AV1C-L and grid ne4_ne4, using the following command to enable cosp
  
./xmlchange -file env_build.xml CAM_CONFIG_OPTS="-cosp" -append

and add cosp_lite = .true. in user_nl_cam, would run well. 

The configurations for the manual case and SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-cosplite_nhtfrq5 are supposed to be the same.

But e3sm.exe generated by SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-cosplite_nhtfrq5 is more than twice as large as the one generated from the manual case.

When soft-linking in the e3sm.exe from the manual case  then manually launch ./case.submit from the casedir of SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-cosplite_nhtfrq5. The run was also ok.

What was causing the size of the two executables to be so different? It is presumed that at some point (and not throughout the module of cospsimulator_intr.F90) that lradar_sim was rendered true , causing the unallocated SD_CS to be invoked.

For reference, the CASEDIR for SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-cosplite_nhtfrq5 is
/home/wulin/gscr/anvil/SMS_D_Ln5.ne4_ne4.FC5AV1C-L.anvil_intel.cam-cosplite_nhtfrq5.20200304_145129_1dvt79

The casedir  and blddir for for the manual case are
/home/wulin/ACME/Cases/testing/anvil/testCOSP2-submodule-ne4
/home/wulin/gscr/anvil/testCOSP2-submodule-ne4/bld

**Comment by wlin7** [comment]
There is a notable difference recorded in CMakeCache.txt: 

 DEBUG:UNINITIALIZED=TRUE in nightly test build, versus
 DEBUG:UNINITIALIZED=FALSE in manual build.

**Comment by wlin7** [comment]
To check if there are bugs similar to that reported in #3318, which affect CLUBB in debug mode but may also affect COSP.

**Comment by wlin7** [comment]
The problem is now fixed. It is not that lradar_sim was incorrectly rendered in the middle of the run. It is because allocatable sd_cs(lchnk) is used as real argument in call to subsample_and_optics.
sd_cs is only allocated when lradar_sim is true. When lradar_sim is false as in csm-cosplite_nhtfrq5 test, it is unallocated, while the dummy argument  asks for one that is either allocated or not an allocatable variable. When the arguments are checked more strictly in debug mode, the inconsistency in argument types causes the failure.
It is changed to use an intermediate variable sd_wk, which takes value from sd_cs(chnk) when lradar_sim is true before calling subsample_and_optics and assign back after the call.

**Comment by dustinswales** [comment]
@wlin7 
I ran cosp_lite=.true. in CESM2 on Cheyenne using Intel and didn't have any issues.
When we tested COSP2 in CESM2, both NAG and Intel compilers were used. I don't recall the specific versions used, but that could always cause an issue.

Generally all changes needed by the host-model to run COSP should live outside of COSP (e.g. not in physics/cosp2/src). So it's expected that you may need to make changes to the cosp-2-cam interface (e.g. cospsimulator_intr.F90 and physics/cosp2/NOTsrc).

**Comment by wlin7** [comment]
Thank you for chiming in, @dustinswales . Yes, the change was made to the interface module cospsimulator_intr.F90. The problem only shows up when  the model is built in a debug mode (Intel FFLAGS: FFLAGS: -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created). E3SM happens to have a nightly test for cosp in debug mode. The same test using PGI also failed. Nevertheless, I don't think it has an impact on the cosp results when cosp_lite = .true., when the model is not built in debug mode. The said variable would not be used in calculations as long as lradar_sim == .false..
