### ISSUE TITLE
e3sm.exe linked with PnetCDF 1.9.0 or higher versions fails on Summit (used to work)

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#3487]
The default (and the only one that is available so far) PnetCDF module installed
on Summit is parallel-netcdf/1.8.1

I have also installed some custom versions (including 1.8.1) under
/gpfs/alpine/cli115/world-shared/3rdparty/pnetcdf to test E3SM.

Version 1.11.2 used to work until recently. In scorpio (or scorpio classic) code,
when PnetCDF calls ncmpi_inq_dimid() on certain opened input files (e.g. cami_mam3_Linoz_ne4np4_L72_c160909.nc), it always returns an error code
NC_EBADID (-33), causing E3SM case run to fail at a very early stage.

This issue is reproducible with custom PnetCDF 1.9.0 or higher versions on Summit,
but not reproducible with version 1.8.1 (system module or the custom version). 

It is confirmed that this issue is caused by PR #3043 and PR #3359. If not fixed, some
E3SM cases run on Summit might not be able to use higher versions of PnetCDF.

It is likely a specific e3sm.exe build/link issue (related to PR 3043 and 3359) on Summit:
PnetCDF 1.9.0 or higher versions still works on other machines like Cori or anlworkstation.
Also, stand-alone PnetCDF or scorpio test programs on Summit cannot reproduce this
error with the same input files.

I have created some feature branches to reproduce this issue. These branches all
switched default PnetCDF 1.8.1 to custom 1.11.2 for testing. A small X Case is used
in the scenarios below (only requires 1 compute node and 1-min of walltime), with
default scorpio classic and IBM XL compiler. Actually, it is also reproducible with ne4
F case, scorpio and GNU compiler.

[Scenario 1]
Before PR 3043 was merged, no errors.
```
git clone --branch dqwu/test_summit_pnetcdf_d15f283 https://github.com/E3SM-Project/E3SM.git E3SM_d15f283
cd E3SM_d15f283
git submodule update --init
cd cime/scripts
./create_newcase --case X_f19_g16_d15f283 --compset X --res f19_g16 --walltime 00:01
cd X_f19_g16_d15f283
./xmlchange STOP_N="1"
./xmlchange REST_OPTION="none"
./case.setup
./case.build
./case.submit
```
[Scenario 2]
After PR 3043 was merged (also include PR 3325 to fix Depends.ibm.cmake), PnetCDF
returns NC_EBADID.
```
git clone --branch dqwu/test_summit_pnetcdf_18922c8 https://github.com/E3SM-Project/E3SM.git E3SM_18922c8
cd E3SM_18922c8
git submodule update --init
cd cime/scripts
./create_newcase --case X_f19_g16_18922c8 --compset X --res f19_g16 --walltime 00:01
cd X_f19_g16_18922c8
./xmlchange STOP_N="1"
./xmlchange REST_OPTION="none"
./case.setup
./case.build
./case.submit
```
case.run error
`pio_support::pio_die:: myrank= -1 : ERROR: nf_mod.F90: 1293 : NetCDF: Not a valid ID`

Note, "./case.build --use-old" still works until PR 3359 was merged.

[Scenario 3]
Before PR 3359 was merged, no errors if we build e3sm.exe with "--use-old" option.
```
git clone --branch dqwu/test_summit_pnetcdf_5696a44 https://github.com/E3SM-Project/E3SM.git E3SM_5696a44
cd E3SM_5696a44
git submodule update --init
cd cime/scripts
./create_newcase --case X_f19_g16_5696a44 --compset X --res f19_g16 --walltime 00:01
cd X_f19_g16_5696a44
./xmlchange STOP_N="1"
./xmlchange REST_OPTION="none"
./case.setup
./case.build --use-old
./case.submit
```
[Scenario 4]
After PR 3359 was merged, PnetCDF returns NC_EBADID even if we build e3sm.exe
with "--use-old" option.
```
git clone --branch dqwu/test_summit_pnetcdf_09304fb https://github.com/E3SM-Project/E3SM.git E3SM_09304fb
cd E3SM_09304fb
git submodule update --init
cd cime/scripts
./create_newcase --case X_f19_g16_09304fb --compset X --res f19_g16 --walltime 00:01
cd X_f19_g16_09304fb
./xmlchange STOP_N="1"
./xmlchange REST_OPTION="none"
./case.setup
./case.build --use-old
./case.submit
```
case.run error
`pio_support::pio_die:: myrank= -1 : ERROR: nf_mod.F90: 1293 : NetCDF: Not a valid ID`

Comments:
PR 3043 is a big PR that switches E3SM's default build-system to be cmake-based.

However, for Summit, PR 3359 is just a small PR that moves some link flags from
LDFLAGS to SLIBS. This only changes the position of some specific linker flags for
PnetCDF with old build-system:
`mpif90 -o e3sm.exe ... -L/gpfs/alpine/cli115/world-shared/3rdparty/pnetcdf/1.11.2/xl-16.1.1/lib -lpnetcdf ...`

I guess PR 3043 has also changed the position of linker flags for PnetCDF with new
cmake-based build-system.

It is still unknown why this trivial position change of linker flags might cause PnetCDF (1.9.0
or higher versions) to return NC_EBADID on Summit if it is linked to e3sm.exe.

**Comment by jgfouca** [comment]
Thanks for the detailed report. I'll look at it soon, probably tomorrow.

**Comment by jgfouca** [comment]
@dqwu , I am able to get the error to repeat on summit:

```
% ./create_test SMS.f19_g16.X --wait
...
1: 68: /gpfs/alpine/cli115/proj-shared/acmetest/e3sm_scratch/SMS.f19_g16.X.summit_ibm.20200311_165742_6ajh0m/bld/e3sm.exe: symbol lookup error: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/spectrum-mpi-10.3.0.1-20190611-aqjt3jo53mogrrhcrd2iufr435azcaha/lib/pmix/mca_psec_native.so: undefined symbol: pmix_output_verbose
```

**Comment by jgfouca** [comment]
This is really frustrating. I don't know why I'm seeing the link error and you are not.

```
undefined symbol: pmix_output_verbose

% ldd ../e3sm.exe   
       ...
	libpmix.so.2 => /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/spectrum-mpi-10.3.0.1-20190611-aqjt3jo53mogrrhcrd2iufr435azcaha/lib/libpmix.so.2 (0x0000200004240000)
        ...

% % nm /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/spectrum-mpi-10.3.0.1-20190611-aqjt3jo53mogrrhcrd2iufr435azcaha/lib/libpmix.so.2 | grep pmix_output_verbose
0000000000018fe0 t 00000198.plt_call.pmix_output_verbose
0000000000044a10 T pmix_output_verbose
```

**Comment by philipwjones** [comment]
@dqwu @jgfouca @sarats @minxu74 Rob Aulwes and I just got a successful MPAS-only standalone build/run by updating to their latest Spectrum mpi and a slight upgrade to hdf5. So changing the machine env to include
module load spectrum-mpi/10.3.1.2-20200121
module load hdf5/1.10.4
with the scorpio build seems to work.

**Comment by philipwjones** [comment]
And yeah, I had been hitting the pmix_output_verbose so the above fixed that

**Comment by jgfouca** [comment]
Oh, nice! Glad you found a fix. It sounds like you just need to add your changes to config_machines.xml.

**Comment by jgfouca** [comment]
Didn't notice you said mpas-only. I'll try your changes in CIME.

**Comment by jgfouca** [comment]
@philipwjones , thanks, that got me past the link error.

**Comment by minxu74** [comment]
@philipwjones Thanks a lot for making the fix. @jgfouca I assume that you will merge the changes to the machine file with the fixes of this issue? If not, I can merge it.  Thanks.

**Comment by jgfouca** [comment]
@minxu74 , yes, I have fixes coming. The problem was much deeper than I originally thought.
