### ISSUE TITLE
ne30pg2_r05_oECv3_ICG not BFB across restart and change in PE layout

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/E3SM#3492]
I'm running a coupled simulation using theta-l+SL+physgrid on compy. See

https://acme-climate.atlassian.net/wiki/spaces/EWCG/pages/1247347152/20200310.alpha22.piControl.ne30pg2+r05+oECv3+ICG.compy

According to my tests, the model is not BFB when changing PE layout from 'S' to 'L' or when restarting. I have three segments of interest:

- 10-day test run with 'S' layout (`/compyfs/gola749/E3SM_simulations/20200310.alpha22.piControl.ne30pg2_r05_oECv3_ICG.compy/test_10d`)
- Two overlapping segments of the production run (`/compyfs/gola749/E3SM_simulations/20200310.alpha22.piControl.ne30pg2_r05_oECv3_ICG.compy/run`; 0001-01-01 to 0006-02-02 and then 0006-01-01 - on-going).

```
cd /compyfs/gola749/E3SM_simulations/20200310.alpha22.piControl.ne30pg2_r05_oECv3_ICG.compy

# Comparing 'S' and 'L' layouts
gunzip -c test_10d/run/atm.log.82319.200310-151855.gz | grep '^ nstep, te ' > atm_S.txt
gunzip -c run/atm.log.82331.200310-182454.gz | grep '^ nstep, te ' > atm_L.txt
gvim -d atm_S.txt atm_L.txt
#--> different after first time step

# Comparing overlapping segments with 'L' layout:
cat run/atm.log.82448.200311-085404 | grep '^ nstep, te ' > atm_L2.txt
gvim -d atm_L.txt atm_L2.txt
#--> different after first time step
```

**Comment by whannah1** [comment]
Seems like this might be related to #3477

**Comment by ambrad** [comment]
I'm going to do a deep dive into the physgrid infrastructure. @whannah1 do you have any objection to my removing `fv_physics_coupling_mod` and anything else that I find that is stale?

**Comment by whannah1** [comment]
@ambrad I've been meaning to do a PR to remove that, so feel free to rip it out.

**Comment by whannah1** [comment]
@ambrad, It would be useful if we could isolate the problem down to either physics or dynamics, would it be possible to do a dry restart test without any physics?

**Comment by golaz** [comment]
In my case, it is possible that this is a coupled problem. I'm running a comparable atmosphere simulation and it's BFB when changing PE layout.

**Comment by ambrad** [comment]
Thanks @golaz. To be clear, you changed PE layout on restart for an F-case and got BFB results?

**Comment by golaz** [comment]
No quite, I did two initial runs with different PE layouts.

**Comment by ambrad** [comment]
Thanks. I'll keep looking at the case I mentioned. I had already tested (several weeks ago) restart with same PE layout and initial with different PE layouts. It's possible that restart with different PE layout has a bug, and that's what I'm focusing on right now.

**Comment by whannah1** [comment]
In my tests with the MMF compsets I found that ERP tests were BFB for certain PE changes, but not others. That makes me think these problems might be related.

**Comment by ambrad** [comment]
I ran a spot check on case F20TRC5-CMIP6, res ne30pg2_r05_oECv3, as follows:

First, run 5 days on 10 nodes and save a restart.
Second, run 5 days on 10 nodes from the restart.
Third, run 5 days on 7 nodes from the restart.

Both the atm.log nstep lines (crude) and diffs of the output nc files look
good. For example,

```
$ grep "SE will use\|nstep, te      481" restart.ntask.400/atm.log.82504.200311-152214 
 SE will use          400   tasks
 nstep, te      481   0.26184533678232899E+10   0.26184532077070432E+10  -0.88552553532773202E-05   0.98515568545831557E+05
$ grep "SE will use\|nstep, te      481" atm.log.82510.200311-163617 
 SE will use          280   tasks
 nstep, te      481   0.26184533678232899E+10   0.26184532077070432E+10  -0.88552553532773202E-05   0.98515568545831557E+05
```

Now I'll set up a script to check many more combinations and perhaps run more
days.

**Comment by ambrad** [comment]
We tracked and resolved a separate workflow issue that gets triggered by the
theta-l cam_target switch. Based on what we learned there, we see that the
following data show that BFB cannot be expected between any two of these three
runs:
```
cat atm.log.82319.200310-151855 | grep 'transport_alg\|^ nstep, te ' > atm_S.txt
cat atm.log.82331.200310-182454 | grep 'transport_alg\|^ nstep, te ' > atm_L.txt
cat atm.log.82448.200311-085404 | grep 'transport_alg\|^ nstep, te ' > atm_L2.txt
$ head -n 2 *.txt
==> atm_L2.txt <==
 readnl: transport_alg   =           12
 nstep, te    87601   0.25989052147438869E+10   0.25989067153821087E+10   0.83009098315103838E-04   0.98496516694113307E+05
==> atm_L.txt <==
 readnl: transport_alg   =            0
 nstep, te        0   0.26056300603406334E+10   0.26056300603406334E+10   0.00000000000000000E+00   0.98499814932227440E+05
==> atm_S.txt <==
 readnl: transport_alg   =           12
 nstep, te        0   0.26056300603406334E+10   0.26056300603406334E+10   0.00000000000000000E+00   0.98499814932227440E+05
```
To confirm that this workflow issue is the only culprit, I ran an 11-node
initial coupled run for 20 days and then restarted at day 10 on 21 nodes. (I ran
XS -> S so I could run on the debug queue. The XS PE layout will go in the
better-output PR.) Restarted and initial runs are BFB in the overlap period,
based on "nstep, te" output. This of course does not definitively rule out a
BFBness problem in the S -> L jump instead of my XS -> S jump, but given the
theta-Eulerian issue, it seems there is no particular reason to think there is
one.

Chris suggested I record these details and the close the issue, so I'm doing
that.

**Comment by rljacob** [comment]
I'm not clear on what the workflow issue is.

**Comment by ambrad** [comment]
In the run script, if you set `old_executable = false`, you have to be sure to `${xmlchange_exe} CAM_TARGET=theta-l` before the `# CONFIGURE` block, or else `Buildconf/camconf/config_cache.xml` has `preqx` as the dycore. Then `cam/cime_config/buildnml` uses this wrong datum to generate a bad `atm_in`.
