### ISSUE TITLE
cosp2 appears to be much more expensive than cosp1, really so?

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#3506]
Since cosp2 (PR #3458 was merged, there are several reports that cosp2 appears to be much more expensive than cosp1 (see the comment section of #3458). @amametjanov and @golaz noticed that the cost of full coupled run increases by 20% on multiple machines. Az also showed that based on cosp_run timer, the slow-down from cosp1 to cosp2 can be 11x. The allactive test 
SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6 also reported increase in computational time

`Computation time increase > 10 pct from baseline`

@wlin7 tested in 10-dam atm simulations on anvil using the hashes before and after the merge , and found cosp2 itself cost 2x as much as cosp1, based on cosp_run timer statitics. The ratio of cosp to total simulation time increases from 1.1% to 2.1%. The system throughput was stable during the test, so the pre-COSP2 and post-COSP2 performance are fairly comparable in that settings. The cost of cosp as a ratio of the total simulation cost is much less than the degradation in performance observed by Az and Chris on fully coupled runs.

Moreover, cosp2 developer @dustinswales indicated that cosp2 is less expensive than cosp1 in CESM (cosp_amwg mode). This is apparently inconsistent with what observed with E3SM.

During allactive coupled run, it was also observed that the execution of cosp2 become slower over time during the course of the simulation. Longer atm-only simulations are being carried out on anvil to see if this behavior reproducible. Further tests will be performed to see if the 20% jump in cost unique to the coupled run (which by itself does not make sense, but it could imply some memory issue. The full coupled simulation with cosp2 did show increase in memory usable over time)

**Comment by amametjanov** [comment]
Re-ran on Compy
```
SMS_Lm1.ne30_ne30.FC5AV1C-L.compy_intel.cam-cosplite and 
SMS_Lm1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6
```
before and after cosp2. Still seeing ~20% total time increase, but a ~2x in `a:cosp_run` (these are 1-month runs vs 2-day nightly testing runs).

There is a ~4x increase in `CPL:COMM`. In F-compset runs,
Before:
```
name                                     on  processes  threads        count      walltotal   wallmax (proc   thrd  )   wallmin (proc   thrd  )
"CPL:COMM"                                -        900      900 9.373500e+06   6.504470e+04   118.332 (   836      0)    17.167 (   273      0)
  "CPL:A2C"                               -        900      900 1.339200e+06   6.240186e+04   114.999 (   836      0)    14.613 (   273      0)
    "CPL:a2c_atma2atmx"                   -        900      900 1.339200e+06   2.953700e+04    99.994 (    18      0)     0.160 (   236      0)
    "CPL:a2c_infoexch"                    -        900      900 1.339200e+06   3.286173e+04    78.368 (   311      0)     7.054 (   869      0)
```
After:
```
name                                     on  processes  threads        count      walltotal   wallmax (proc   thrd  )   wallmin (proc   thrd  )
"CPL:COMM"                                -        900      900 9.373500e+06   3.134736e+05   415.580 (   782      0)   255.893 (   266      0)
  "CPL:A2C"                               -        900      900 1.339200e+06   3.105860e+05   411.848 (   782      0)   252.922 (   266      0)
    "CPL:a2c_atma2atmx"                   -        900      900 1.339200e+06   1.229373e+05   251.536 (   669      0)    10.855 (   527      0)
    "CPL:a2c_infoexch"                    -        900      900 1.339200e+06   1.876457e+05   323.021 (   778      0)   104.152 (   869      0)
```

Is there more MPI and synchronization in cosp2?

**Comment by ambrad** [comment]
I agree @amametjanov. As another data point, see: https://github.com/E3SM-Project/E3SM/pull/3458#issuecomment-597804360. This was related to the finding described on [this page](https://acme-climate.atlassian.net/wiki/spaces/EWCG/pages/1247347152/20200310.alpha22.piControl.ne30pg2+r05+oECv3+ICG.compy). Search for "There does seem to be some large slowdown in your run." on that page to see the timer analysis.

**Comment by rljacob** [comment]
Is there still some doubt about if cosp2 is more expensive.  It plainly is.  But why?

My understanding is that cosp is a bunch of emulators and you can make it more or less expensive by turning ones on or off.  That's what is behind "cosp_lite" mode.

So is cosp2 more expensive because the same emulators now have a more expensive calculation either for legit reasons (algorithm) or non-legit (bad loop ordering).  Or there are more emulators, some with expensive calculations?

And how can this be true:  

> Moreover, cosp2 developer @dustinswales indicated that cosp2 is less expensive than cosp1 in CESM (cosp_amwg mode). This is apparently inconsistent with what observed with E3SM.

Depends on what "less" means.

**Comment by worleyph** [comment]
@az, could you point me at your case and run directories, or tell me how to repeat your experiment (what hashes to check out)? I'll see if adding some timers will illuminate what is going on, unless you want to do this. Thanks.

**Comment by worleyph** [comment]
@amametjanov, see previous request. Thanks.

**Comment by amametjanov** [comment]
Before:
```
/compyfs/mame117/e3sm_scratch/SMS_Lm1.ne30_ne30.FC5AV1C-L.compy_intel.cam-cosplite.C.20200320_073744_jkuq7v
```
After:
```
/compyfs/mame117/e3sm_scratch/SMS_Lm1.ne30_ne30.FC5AV1C-L.compy_intel.cam-cosplite.G.20200320_073522_syiyqu
```

**Comment by worleyph** [comment]
Thanks. I'll poke around as well.

**Comment by PeterCaldwell** [comment]
@rljacob - I recall Jen Kay (one of the COSP developers, tied to CESM) telling me a few years ago that COSP2 was substantially faster than COSP1. My memory is murky, but I want to say that it was 20% faster and that the CloudSat simulator - which is the main thing our COSP-Lite turns off - takes a negligible fraction of run time. I may be remembering these details incorrectly, but I definitely had the expectation based on CESM experience that COSP2 would be substantially faster. 
I think you make a good point that we shouldn't necessarily compare COSP1-Lite against COSP2-Full.

**Comment by worleyph** [comment]
I just started looking, but comparing the ATM log I see that some of the  MASTER FIELD LIST variables have more vertical levels when using cosp2 than with cosp1. Examples include ...

     <  2152 CLD_CAL                          percent             1 A  Lidar Cloud Fraction (532 nm)
     >  2152 CLD_CAL                          percent            40 A  Calipso Cloud Fraction (532 nm)

     <  2154 CFAD_SR532_CAL                   fraction            1 A  Lidar Scattering Ratio CFAD (532 nm)
     >  2154 CFAD_SR532_CAL                   fraction           40 A  Calipso Scattering Ratio CFAD (532 nm)

     <  2157 CLD_CAL_LIQ                      percent             1 A  Lidar Liquid Cloud Fraction
     <  2158 CLD_CAL_ICE                      percent             1 A  Lidar Ice Cloud Fraction
     <  2159 CLD_CAL_UN                       percent             1 A  Lidar Undefined-Phase Cloud Fraction
     <  2160 CLD_CAL_TMP                      percent             1 A  NOT SURE WHAT THIS IS Cloud Fraction
     <  2161 CLD_CAL_TMPLIQ                   percent             1 A  NOT SURE WHAT THIS IS Cloud Fraction
     <  2162 CLD_CAL_TMPICE                   percent             1 A  NOT SURE WHAT THIS IS Cloud Fraction
     <  2163 CLD_CAL_TMPUN                    percent             1 A  NOT SURE WHAT THIS IS Cloud Fraction
     >  2157 CLD_CAL_LIQ                      percent            40 A  Calipso Liquid Cloud Fraction
     >  2158 CLD_CAL_ICE                      percent            40 A  Calipso Ice Cloud Fraction
     >  2159 CLD_CAL_UN                       percent            40 A  Calipso Undefined-Phase Cloud Fraction
     >  2160 CLD_CAL_TMP                      percent            40 A  NOT SURE WHAT THIS IS Cloud Fraction
     >  2161 CLD_CAL_TMPLIQ                   percent            40 A  NOT SURE WHAT THIS IS Cloud Fraction
     >  2162 CLD_CAL_TMPICE                   percent            40 A  NOT SURE WHAT THIS IS Cloud Fraction
     >  2163 CLD_CAL_TMPUN                    percent            40 A  NOT SURE WHAT THIS IS Cloud Fraction

Here the columns are

     f, fldname, listentry%field%units, listentry%field%numlev, &
             listentry%avgflag(1), trim(listentry%field%long_name)
This might increase the cost of accumulating and writing out these data?

**Comment by rljacob** [comment]
I would hope these comparison already have cosp1-lite vs. cosp2-full in to account.

@wlin7 did "cosp_lite" get carried over to cosp2 and results in the same emulators being selected.

**Comment by worleyph** [comment]
> I would hope these comparison already have cosp1-lite vs. cosp2-full in to account.

@rljacob , @amametjanov 's experiments (which I am repeating) have cosp_lite = .true. in user_nl_cam for both cosp1 and cosp2. So your question is whether cosp_lite is really supported in COSP2 and means the same thing in COSP1 and COSP2? (This is my question also :-) ).

**Comment by rljacob** [comment]
Yes that's my question.

**Comment by worleyph** [comment]
History file is around 14% larger (one month run):

     992411612 Mar 20 16:46 FC5AV1C-L_ne30_ne30_cosp1.cam.h0.0001-01.nc

vs.

     1129663660 Mar 20 17:25 FC5AV1C-L_ne30_ne30_cosp2.cam.h0.0001-01.nc

**Comment by worleyph** [comment]
COSP1:

        if (cosp_lite) then
           llidar_sim = .true.
           lisccp_sim = .true.
           lmisr_sim = .true.
           lmodis_sim = .true.
           cosp_ncolumns = 10
           cosp_nradsteps = 3
        end if

COSP2:

        if (cosp_lite) then
           llidar_sim = .true.
           lparasol_sim = .true.
           lisccp_sim = .true.
           lmisr_sim = .true.
           lmodis_sim = .false.
           cosp_ncolumns = 10
           cosp_nradsteps = 3
        end if

Assuming that the names mean the same thing (still to be verified), differences are

     COSP2 has  lparasol_sim = .true.

while

     COSP1 has  lmodis_sim = .true.

May be other simulators not controlled by the above as well, but I don't see anything obvious at the moment.

**Comment by worleyph** [comment]
I set 'lparasol_sim = .false.' in the code block for cosp_lite in the COSP2 branch, and the run died with a seg. fault in cospsimulator_intr.F90, perhaps at ...

       ! PARASOL. In COSP2, the Parasol simulator is independent of the calipso simulator.                                                                                                                                         
       refl_parasol(1:ncol,1:nsza_cosp) = cospOUT%parasolGrid_refl                                ! CAM version of parasolrefl (time,sza,profile)

probably because

    ! PARASOL                                                                                                                                                                                                                      
    if (lparasol_sim) then
       allocate(x%parasolPix_refl(Npoints,Ncolumns,PARASOL_NREFL))
       allocate(x%parasolGrid_refl(Npoints,PARASOL_NREFL))
    endif

so the first statement is executed whether lparasol_sim is true or not, while the associated allocate is not. I'll try to fix this and try running without parasol_sim again.

**Comment by worleyph** [comment]
Based on the comment, parasol perhaps is bundled with calipso in COSP1, so this may be a red herring.

**Comment by worleyph** [comment]
As far as I can tell it is a bug in the COSP1 version that CLD_CAL, for example, is writing out only one vertical layer instead of 40 (== COSP_HT == nht_cosp). I can't figure out why the COSP1 version is behaving this way. It calls addfld in the same way as the COSP2 version, and with the same parameters.

**Comment by worleyph** [comment]
Running the COSP2 branch with lparasol_sim = .false. did not improve performance. Only thing I can find so far is the increased output when using COSP2, and this seems to be a bug fix when compared to the COSP1 logic.

**Comment by worleyph** [comment]
Not a big thing (at least for ne30 F case on Compy), but the cospsimulator_intr_run call overhead is very high with COSP2 (and not at all for COSP1) - perhaps some large array copies required because of the way fields are passed in?

I added the timer 'cosp_run_body' right inside of the routine cospsimulator_intr_run. The existing timer 'cosp_run' is right outside of the call.

COSP1:

(global stats)

     "a:cosp_run"                              -        900      900 8.928000e+05   1.692554e+04    24.393 (   504      0)    17.058 (    22      0)
     "a:cosp_run_body"                         -        900      900 8.928000e+05   1.691033e+04    24.366 (   504      0)    17.045 (    22      0)

(process 0)

              "a:cosp_run"                                                  -     992    -      18.248531     0.026970     0.013985         0.000038
                "a:cosp_run_body"                                           -     992    -      18.233027     0.026954     0.013977         0.000038

so almost no call overhead for COSP1.

COSP2:

(global stats)

     "a:cosp_run"                              -        900      900 8.928000e+05   3.794936e+04    74.029 (   262      0)    19.994 (   884      0)
     "a:cosp_run_body"                         -        900      900 8.928000e+05   2.114114e+04    37.520 (   844      0)    13.252 (   884      0)

(process 0)

              "a:cosp_run"                                                  -     992    -      40.155220     1.485926     0.017115         0.000038
                "a:cosp_run_body"                                           -     992    -      23.758701     0.758157     0.011485         0.000038

So, the cost of body of cospsimulator_intr_run is higher for COSP1 compared to COSP2, but a (much) bigger difference is in the call overhead.

**Comment by worleyph** [comment]
Note that I updated the previous comment to:

> So, the cost of body of cospsimulator_intr_run is higher for COSP2 compared to COSP1, but a (much) bigger difference is in the call overhead.

I had it the wrong order in the original.

**Comment by worleyph** [comment]
Sorry for the sequence of working updates, but the issue with CPL:COMM appears to be load imbalance or, at least, not associated with CPL:A2C in CPL:COMM. I added a barrier before the call to seq_map_map in component_exch (for c2x, which is a2c here) with also a timer prefix to capture just the CPL:A2C call, and got:

(global stats)

     "a2c-CPL:COMM"                            -        900      900 1.339200e+06   5.273588e+05   641.737 (   899      0)   290.735 (     0      0)
     "a2c-CPL:A2C"                             -        900      900 1.339200e+06   5.273578e+05   641.735 (   899      0)   290.733 (     0      0)
     "a2c-CPL:a2c_atma2atmx"                   -        900      900 1.339200e+06   5.270919e+05   641.382 (   899      0)   290.410 (     0      0)
     "a2c-ce_smm_bar"                          -        900      900 1.339200e+06   5.268654e+05   641.186 (   899      0)   290.197 (     0      0)
     "a2c-ce_smm"                              -        900      900 1.339200e+06   2.241836e+02     0.451 (    44      0)     0.178 (   891      0)

(process 0)

        "a2c-CPL:COMM"                                                          -    1488    -     290.734619     1.901490     0.000352         0.000057
           "a2c-CPL:A2C"                                                         -    1488    -     290.733490     1.901489     0.000351         0.000057
             "a2c-CPL:a2c_atma2atmx"                                             -    1488    -     290.410309     1.901318     0.000143         0.000057
               "a2c-ce_smm_bar"                                                  -    1488    -     290.197113     1.901166     0.000024         0.000057
               "a2c-ce_smm"                                                      -    1488    -       0.208587     0.006237     0.000100         0.000057

where "a2c-ce_smm_bar" is the new barrier, and "a2c-ce_smm"  is a timer around the call to seq_map_map .

**Comment by wlin7** [comment]
Completed a pair of multiple F-case runs on anvil, pre and post COSP2, almost simultaneously.
Consistent results are: a:cosp_run timer for cosp2 is 2x of cosp1; monthly cost with cosp2 increases between 14% to 22% from month to month, not monotonically during the run.

The cost of COSP, in terms of cosp_tun_time/total_simulation_rime, remains small, increasing from 1/% to 2/% for COSP2. 

Size of default history file cam.h0  increases by 16%. But the increase in cost at least is not due to writing more data. Disabling writing does not change the increase in cost. Arrays like CLD_CAL as @worleyph showed above do have same dimension size in the codes (nht_cosp=40).  Can't figure out why the masterlist when using cosp1 only sees 1 level. The coordinate "cosp_ht" is registered the same way with nht_cosp=40 (since use_vgrid=true).  Anyway it is a good fix.

It has also been verified that the increase of near 20% total runtime is due to cosp2. When set docosp=.false., the run times are about the same between pre and post COSP2.

The time spent on accumulation of additional arrays (such as CLD_CAL),  can't explain the increase in cost. The increase in cost largely remains when the following fields are excluded.
fexcl1='CFAD_SR532_CAL', 'CLD_CAL', 'CLD_CAL_ICE', 'CLD_CAL_LIQ', 'CLD_CAL_UN', 'CLRIMODIS', 'CLRLMODIS'

**Comment by worleyph** [comment]
The primary difference between performance of the COSP1 and COSP2 branches (for this F case and the ne30_ne30 resolution mesh) appears to be due to a load imbalance in calls to the COSP2 cospsimulator_intr_run, and the load imbalance also moves around between processes, so all of them suffer from it to some degree. For example, in the following I am running with 900 MPI processes and I changed pcols from 16 to 56, so that there is one chunk per process (instead of 4 chunks if use the default pcols=16). This has no impact on performance (I have run experiments with both pcols=16 and pcols=56), but it makes the investigation a little less complicated

(unmodified)
(COSP1)

    TOT Run Time:    1519.519 seconds       49.017 seconds/mday         4.83 myears/wday
    ATM Run Time:    1500.552 seconds       48.405 seconds/mday         4.89 myears/wday
    CPL COMM Time:     72.750 seconds        2.347 seconds/mday       100.87 myears/wday

(COSP2)

    TOT Run Time:    1870.768 seconds       60.347 seconds/mday         3.92 myears/wday
    ATM Run Time:    1560.092 seconds       50.326 seconds/mday         4.70 myears/wday
    CPL COMM Time:    396.792 seconds       12.800 seconds/mday        18.49 myears/wday

(added barrier right before and right after the call to radiation_tend in physpkg.90)
(COSP1)

    TOT Run Time:    1533.058 seconds       49.453 seconds/mday         4.79 myears/wday
    ATM Run Time:    1520.574 seconds       49.051 seconds/mday         4.83 myears/wday
    CPL COMM Time:      4.269 seconds        0.138 seconds/mday      1718.92 myears/wday

(COSP2)

    TOT Run Time:    1889.432 seconds       60.949 seconds/mday         3.88 myears/wday
    ATM Run Time:    1868.704 seconds       60.281 seconds/mday         3.93 myears/wday
    CPL COMM Time:      4.992 seconds        0.161 seconds/mday      1469.97 myears/wday

(removed barriers around radiation_tend and instead added barriers around the call to cospsimulator_intr_run in rrtmg/radiation.F90)
(COSP1)

    TOT Run Time:    1530.300 seconds       49.365 seconds/mday         4.80 myears/wday
    ATM Run Time:    1505.708 seconds       48.571 seconds/mday         4.87 myears/wday
    CPL COMM Time:     66.520 seconds        2.146 seconds/mday       110.31 myears/wday

(COSP2)

    TOT Run Time:    1908.971 seconds       61.580 seconds/mday         3.84 myears/wday
    ATM Run Time:    1891.585 seconds       61.019 seconds/mday         3.88 myears/wday
    CPL COMM Time:     74.058 seconds        2.389 seconds/mday        99.09 myears/wday

Note that adding the barrier at the end of the call to radiation_tend moves almost all of the cost that was in CPL COMM Time into ATM Run Time (for both COSP1 and COSP2). If instead we add the barrier to the end of the call to cospsimulator_intr_run, CPL COMM Time increases somewhat, but by similar amounts for COSP1 and COSP2, and the difference in performance is still in ATM Run Time. So, bc_physics load imbalance "perturbs" CPL COMM Time, and COSP2 has a much larger load imbalance, primarily (probably all) coming from the call to cospsimulator_intr_run.

I still haven't figured out where this is coming from, and the existing timers (and even some that I have added) haven't clarified anything. For the runs with the barrier before/after the call to cospsimulator_intr_run:

(COSP1)
(global stats)

     "a:cosp_pre_run_bar"                      -        900      900 2.232000e+05   5.901947e+03    14.648 (   316      0)     0.843 (   270      0)
     "a:cosp_run"                              -        900      900 2.232000e+05   1.417433e+04    16.124 (   475      0)    15.181 (   122      0)
     "a:cosp_run_body"                         -        900      900 2.232000e+05   1.415504e+04    16.101 (   475      0)    15.162 (   122      0)
     ...
     "a:cosp_post_run_bar"                     -        900      900 2.232000e+05   6.746615e+02     1.317 (   122      0)     0.374 (   475      0)

(process 0)

               "a:cosp_pre_run_bar"                                        -     248    -       6.683249     0.045484     0.000030         0.000010
                "a:cosp_run"                                                -     248    -      15.537122     0.069871     0.055388         0.000010
                  "a:cosp_run_body"                                         -     248    -      15.515648     0.069783     0.055307         0.000010
     ...
                "a:cosp_post_run_bar"                                       -     248    -       0.961848     0.075219     0.001052         0.000010

(COSP2)
(global stats)

     "a:cosp_pre_run_bar"                      -        900      900 2.232000e+05   9.874343e+03    16.609 (   112      0)     1.560 (   511      0)
     "a:cosp_run"                              -        900      900 2.232000e+05   2.591652e+04    66.345 (   617      0)    12.325 (   886      0)
     "a:cosp_run_body"                         -        900      900 2.232000e+05   1.574733e+04    35.002 (   617      0)     9.604 (   687      0)
     ...
     "a:cosp_post_run_bar"                     -        900      900 2.232000e+05   2.942153e+05   343.376 (   886      0)   289.358 (   617      0)

(process 0)

           "a:cosp_pre_run_bar"                                        -     248    -       9.788411     0.062203     0.000029         0.000009
           "a:cosp_run"                                                -     248    -      54.375118     1.494910     0.037191         0.000009
             "a:cosp_run_body"                                         -     248    -      29.659922     0.740577     0.030593         0.000009
     ...
           "a:cosp_post_run_bar"                                       -     248    -     301.325897     1.483712     0.000025         0.000009

So COSP1 is not seeing any load imbalance in the calls to cospsimulator_intr_run, while COSP2 is seeing a lot.

**Comment by worleyph** [comment]
@wlin7 , thanks for determining that the discrepancy in number of output levels is not a source of the performance differences.

**Comment by wlin7** [comment]
Hi Pat, thank you, too, for the very interesting analysis. Hopefully it will get closer to a solution soon. The numbers are obvious,  though I don't know how the barriers you added works. 

I also struggled to find an existing timer that can explain the majority of the difference in the total run time, because the time actually spent on cosp calculations is a small fraction, and none of the differences among the timers are anywhere close to 15% , the increase in total cost.

**Comment by ambrad** [comment]
Is it possible to put a timer at the start and end of every subroutine call (a) from E3SM into COSP2 and (b) E3SM into the COSP2 interface? The results would show whether the time is in COSP2 itself, the E3SM interface to COSP2, or -- hardest to interpret -- in E3SM code apparently unrelated to COSP2 but somehow affected by it.

**Comment by worleyph** [comment]
I put mpi_barrier calls before every timer in cospsimulator_intr_run, including at the very beginning and the very end of the routine. Two barriers "explain" all of the anomalous cost:

     "a:init_and_stuff_pre_bar"                -        900      900 2.232000e+05   1.274426e+05   149.620 (   787      0)   126.888 (    17      0)
     "a:subsample_and_optics_pre_bar"          -        900      900 2.232000e+05   1.311556e+05   154.004 (    78      0)   128.535 (     9      0)

The first barrier is at the very beginning of the routine, indicating that the overhead of the call itself (copying arrays included in the call itself) is both expensive and very erratic cost across the processes.

The second barrier precedes the subsample_and_optics timer, which means that it directly follows the construct_cospIN timer.  construct_cospIN is just a very large allocate .

**Comment by worleyph** [comment]
I have to give it up for the night. Will try two things tomorrow: (a) inline code for construct_cospIN and see if it makes any difference; (b) look at how cospsimulator_intr_run is called and try to remove any possibility of under-the-cover array copies (by doing it explicitly before the call, if necessary).

**Comment by wlin7** [comment]
@worleyph , thanks for narrowing the problem down. It makes good sense to me that problem is on preparation for the the actual calls to the simulators. Turning some simulators off, relative to cosp_lite, does not change the outcome. Instead, the increase in cost became even larger when more simulators were disabled. 

Regarding the overhead of the call itself, I would like to mention that the arguments to cospsimulator_intr_run are identical for cosp1 and cosp2. It does not copy more data in with cosp2. But it does use more local large arrays.

**Comment by worleyph** [comment]
@wlin7 , thank you - I had made assumptions before having the time to look at the code. Too bad actually, as the parameters to the call is something under our control. Not sure what to do about large local memory requirements, if this is indeed the source of the performance problem. Doesn't seem like it should be (to this degree).

**Comment by worleyph** [comment]
I'm not sure that I totally trust this result yet, but inlining construct_cospIN  eliminated the high cost at the a:subsample_and_optics_pre_bar barrier timer (completely). I'll check whether this change has any real impact on the version without extra barriers.

**Comment by zyuying** [comment]
Hi All,
 
A few comments below:
 
Just want to clarify that the Parasol simulator is part of the lidar simulator in COSP1 while it has been separated from the Calipso lidar simulator in COSP2 for the flexibility that the user can decide if it should be turned on or not, which is controlled by “lparasol_sim”. So, the computational cost should not be increased due to this change. 
 
Regarding the variable “CLD_CAL”, I am not sure why it is outputting only one layer in COSP1. It should have 40 levels. I will double check that. The single layer output variables are 'CLDTOT/HGH/MED/LOW_CAL'. 
 
Note that COSP2 includes some additional diagnostics, like radar surface precipitation and lidar opaque cloud fraction. These variables are currently not saved in the output, but it does take some computational costs for calculating these diagnostics. It would be useful to check how much these diagnostics increase the computer time. I will see if I can get the number quickly.

**Comment by worleyph** [comment]
Update:

(a) inlining the body of construct_cospIN (removing the routine call) eliminated half of the performance degradation compared to the COSP1 branch. 

(b) replacing 2D and 3D locally declared variables with allocate/deallocate logic had no performance impact (plus or minus).

Still looking for the source of the "other half" of the performance degradation.

**Comment by worleyph** [comment]
Update ???:

(b) while replacing 2D and 3D locally declared variables with allocate/deallocate logic had no impact, replacing the locally declared COSP2-type variables

    type(cosp_outputs)        :: cospOUT                  ! COSP simulator outputs                                                                                                                                    
    type(cosp_optical_inputs) :: cospIN                   ! COSP optical (or derived?) fields needed by simulators                                                                                                    
    type(cosp_column_inputs)  :: cospstateIN              ! COSP model fields needed by simulators                                                                                                                    

with allocate/deallocate logic:

    type(cosp_outputs), allocatable :: cospOUT            ! COSP simulator outputs                                                                                                                                       
    type(cosp_optical_inputs), allocatable :: cospIN      ! COSP optical (or derived?) fields needed by simulators                                                                                                       
    type(cosp_column_inputs), allocatable  :: cospstateIN ! COSP model fields needed by simulators                                                                                                                       

did have an effect. First, the discrepancy between the surrounding timer and the body timer disappeared:

      "a:cosp_run"                                                -     992    -      26.112429     0.799196     0.011374         0.000038
        "a:cosp_run_body"                                         -     992    -      26.097662     0.799181     0.011361         0.000038

Second, when adding a mpi_barrier with associated timer at both the beginning of the routine (right before the allocation of the type variables) and right after the allocation of the type variables:

       "a:cosp_run"                                                -     248    -     170.503922     0.802258     0.064111         0.000009
         "a:cosp_run_body"                                         -     248    -     170.495102     0.802220     0.064077         0.000009
           "a:cosp_new_typeallocs_pre_bar"                         -     248    -       7.688615     0.053342     0.011973         0.000009
           "a:cosp_new_typeallocs"                                 -     248    -      13.260859     0.670659     0.006862         0.000009
           "a:cosp_new_allocs_pre_bar"                             -     248    -     142.083527     0.716039     0.000020         0.000009

the barrier after the call to allocate the type variables captures all of the remaining extra cost introduced by using COSP2 instead of COSP1.

So, this is "illuminating". However, I don't know what to try next to eliminate the high cost introduced by allocating these types. Note that the timer around the allocation itself does not show that the cost is excessive.

    "a:cosp_new_typeallocs"                   -        900      900 2.232000e+05   8.401864e+03    24.846 (   191      0)     2.355 (   736      0)

at least not in the aggregate (if load imbalance per process moves around a lot, partially serializing the cost, this could have the hypothesized effect, but seems like really bad luck if so).

It is only the barrier following that indicates this. Using barriers in this fashion is often misleading, as it forces a synchronization that is not there naturally, and the extra cost can be artificial. In this case, however, the total cost of the run (when using pcols=56, so one chunk per process) is unchanged by adding the barrier, and the cost showing up at the barrier is comaprable to the cost that would otherwise show up in CPL:COMM, so it sure looks like the same cost, and it is still the best candidate for a source of the performance degradation (after implementing the inlining mentioned earlier).

**Comment by worleyph** [comment]
Not sure that I trust this (I'll try to verify tomorrow), but the only COSP type variable allocation that appears to be expensive (both explicitly and implicitly, as measured by a succeeding mpi_barrier) is

     type(cosp_optical_inputs), allocatable :: cospIN 

that is, putting timers around each individual allocate and putting timed barriers before, after, and in between, this is the only one that showed any significant cost, and it captured all of the performance degradation.

**Comment by ambrad** [comment]
Perhaps it's [this member variable](https://github.com/CFMIP/COSPv2.0/blob/34d8eef3d231a87c0f73e565f6b5d548876b294a/src/cosp.F90#L163) in COSPv2. For example, [this member](https://github.com/CFMIP/COSPv2.0/blob/34d8eef3d231a87c0f73e565f6b5d548876b294a/src/simulator/quickbeam/quickbeam.F90#L96) of the `radar_cfg` type is ~7.5 MB.

**Comment by worleyph** [comment]
@ambrad , makes sense. This is part of cosp_optical_inputs, and the other types (cosp_outputs and cosp_column_inputs) are only integer or real or pointers to integer or real. 

I'll see if I can try your suggestion tomorrow. Thanks!

**Comment by worleyph** [comment]
@ambrad 's conjecture was accurate. It appears that this is the source of all of the performance issues (in the particular case that I am running and on Compy with the Intel compiler). I implemented a proof-of-principle workaround and will push a WIP PR for people to look at. Since this touches the external repository, I don't know what the next step should be. Note that I propose to redefine the radar_cfg type to have allocatable members, which adds the requirements of allocating/deallocating these explicitly.

I backed out all of my changes except those required for the proposed change to the radar_cfg type and ran the usual case:

(COSP1)

    TOT Run Time:    1519.519 seconds       49.017 seconds/mday         4.83 myears/wday
    ATM Run Time:    1500.552 seconds       48.405 seconds/mday         4.89 myears/wday
    CPL COMM Time:     72.750 seconds        2.347 seconds/mday       100.87 myears/wday

(COSP2)

    TOT Run Time:    1524.348 seconds       49.173 seconds/mday         4.81 myears/wday
    ATM Run Time:    1504.808 seconds       48.542 seconds/mday         4.88 myears/wday
    CPL COMM Time:     70.548 seconds        2.276 seconds/mday       104.02 myears/wday

This uses pcols = 56. I'll also try the default pcols (=16) next.

**Comment by worleyph** [comment]
That didn't work - is there a way for me to create a branch with changes to code in externals so that I can share this? My "git commit -a" just failed with

     ERROR: One or more of your submodules contain uncommitted changes.
       Please either commit these changes first, or ensure the
       changes outside the submodule do not depend on these changes.

**Comment by worleyph** [comment]
Note that my changes are in three files:

     cam/src/physics/cam/cospsimulator_intr.F90
     cam/src/physics/cosp2/external/src/simulator/cosp_cloudsat_interface.F90
     cam/src/physics/cosp2/external/src/simulator/quickbeam/quickbeam.F90

**Comment by worleyph** [comment]
Using pcols=16 with this case (so 4 chunks per process), COSP2 might still be a little bit slower than COSP1 even wit the proposed changes, but this may be in the noise? 

(COSP1)

    TOT Run Time:    1535.475 seconds       49.531 seconds/mday         4.78 myears/wday
    ATM Run Time:    1503.060 seconds       48.486 seconds/mday         4.88 myears/wday
    CPL COMM Time:    118.105 seconds        3.810 seconds/mday        62.13 myears/wday

(COSP2)

    TOT Run Time:    1579.435 seconds       50.950 seconds/mday         4.65 myears/wday
    ATM Run Time:    1530.641 seconds       49.376 seconds/mday         4.79 myears/wday
    CPL COMM Time:    180.298 seconds        5.816 seconds/mday        40.70 myears/wday

I can see if some of the other things I tried eliminate this, but it would be better to check if the current proposed changes work and show improvement on other systems (Cori-KNL) and in the coupled cases that have also shown performance hits.

**Comment by worleyph** [comment]
I was conservative when evaluating @ambrad 's suggestion and modified the definition of the radar_cfg type. I just now went back and tried Andrew's original suggestion, to modify instead the definition of the cosp_optical_inputs type (to make the radar_cfg member allocatably). This worked just as well as my first approach, requires fewer modifications, and requires modifying only two files:

     cam/src/physics/cam/cospsimulator_intr.F90
     cam/src/physics/cosp2/external/src/cosp.F90

So, this is probably the suggestion we should make to the COSP developers. Note that it still requires touching an external file.

**Comment by wlin7** [comment]
Fantastic work, @worleyph . Thank you and @ambrad and Andrew for the hard work even during the weekend.

I will let the developer be aware of out solution.  Before he updates his COSPv2 repo, we can apply the fix in a local version of cosp.F90 and merge to master to clear the tests affected.

Pat, can you please create a PR, with your modifications to the two files? The following three files will be touched to have our localized version to work. We will switch back after the external repo is updated.

1. cospsimulator_intr stays at the original location
2. new cosp.F90 placed under cam/src/physics/cosp2/local/cosp.F90
3. update the path for cosp.F90 in cam/src/physics/cosp2/Cosp.cmake

Thanks again.

**Comment by worleyph** [comment]
And thanks @amametjanov for his prior experiments and for sharing his testing framework that made it simple for me to jump into this effort.
