### ISSUE TITLE
OOM with hires F-case using 1 element per rank (1350 nodes) on cori-knl

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#3519]
For the ATM, using 1 element per rank is typically where we find the max performance (in reasonable fashion). For hires (ne120), there are 86400 elements. On cori-knl, using 64 MPI's per node, we would need 1350 nodes. No threading. This is a configuration I've used many times in previous years. I tried this with a recent master and it failed with OOM. The same problem setup with fewer nodes worked (ie using 85,169,338, and 675 nodes). So I went back to some older repos and the same 1350-node test worked. So now I'm trying to find the PR that might have caused this.

```
Repo of Nov 6th,  2019 worked. (m19-nov6)
Repo of Dec 4th,  2019 worked. hash=78d081307 (m20-dec4)
Repo of Dec 9th,  2019 worked. hash=cddf95fc3 (b2019-12-09-cddf95fc3)
Repo of Dec 12th, 2019 worked. hash=1774b0c32 (b2019-12-12-1774b0c32)
Repo of Dec 16th, 2019 worked. hash=648b27b16 (b2019-12-16-afterPR3310-648b27b16)

Repo of Dec 17th, 2019 TIMEOUT hash=aa148226d (b2019-12-17-afterPR3331-aa148226d)

Repo of Dec 18th, 2019 OOM. hash=aa793efdf (b2019-12-18-afterPR3361-aa793efdf)
Repo of Dec 19th, 2019 OOM. hash=d615b57f5 (b2019-12-19-beforePR3349)
Repo of Dec 19th, 2019 OOM. hash=667156d86 (m22-dec19)
Repo of Jan 30th, 2020 OOM.
Repo of Feb 25th, 2020 OOM.
Repo of Mar 9th,  2020 OOM.
Repo of Mar 28th, 2020 OOM. Several attempts changing a few parameters

compset=FC5AV1C-H01A
res=ne120_ne120
5 days
No IO, empty user_nl_cam, PIO_VERSION=1
```
The OOM failure is very early in the run. Before the cpl.log file has data written to it.

I don't see any obvious diffs in the case directories between the last successful run with repo of Dec 16th and the next OOM with repo of Dec 18th.

For now I'm reporting, but ignoring the TIMEOUT of repo from Dec 17th. This happened after 76 minutes. The other successful jobs completed between 42 and 59 minutes. Almost all of the time for these jobs is in the initialization. The timed out job appears to have been initializing ice component.

**Comment by jonbob** [comment]
@ndkeen - what does the git log show from the oldest repo that failed? Any clues to what might have just been added to that one?

**Comment by ndkeen** [comment]
The output of git log in some of my repos is not what I would expect, so I need to double-check that I didn't mess something up there and will report back. However, it's still true that this was clearly working in Nov/Dec and stopped working sometime in Dec.

**Comment by jonbob** [comment]
@ndkeen - agreed. I'll see if I can figure out what PR's may have gotten in between what worked for you and what did not

**Comment by ambrad** [comment]
@ndkeen I'm probably confused, but the presence of, e.g., `micro_p3_tableversion` in the namelist makes me think you're using the scream rather than E3SM repo.

**Comment by ndkeen** [comment]
AGGH! That's it. My script to check out the repo at different specific dates was still hard-coded to use scream repo (when I last used it). No wonder the git logs weren't making sense. I will correct the above to reflect what I know.

**Comment by ndkeen** [comment]
I think I have found what happened in the repo to cause the OOM, but if that's really true, it might be that we are really close to the memory limit and this was just enough to push it over. In PR3361, there is a change in how much memory is allocated for a test of the memory system. This PR changed the amount we allocate mem_tmp from 1024*1024 to 1024*1024*128. If I change back to 1024*1024, a recent master will run the problem I've been trying to run (with 1350 nodes)

```
     ierr = GPTLget_memusage (msize, mrss0, mshare, mtext, mdatastack)
    !ndk allocate(mem_tmp(1024*1024*128))    ! 1 MWord, 1024 MB (128*8)
    allocate(mem_tmp(1024*1024))   
     mem_tmp = -1.0
     ierr = GPTLget_memusage (msize, mrss1, mshare, mtext, mdatastack)
     deallocate(mem_tmp)
```

**Comment by jonbob** [comment]
Good catch @ndkeen

**Comment by ndkeen** [comment]
I chatted with @amametjanov earlier who is skeptical that this PR is the real cause of the OOM. I haven't had a chance to look much closer yet, but certainly, this looks like innocent code and it could be there is some other issue.

**Comment by ndkeen** [comment]
This test of the memory system is allocating 1GB of memory and deallocating. Each rank is doing this which means ~64GB of memory allocated. One way to verify is to run ne4 F-case with 128 MPI's per node -- this case also hits OOM in the same way.

There must still be an increasing amount of memory use as we scale the ne120 problem with number of MPI's, but it's easy to get around this problem. This is a specific variety of OOM as it happens very early. If there is a case with OOM and the cpl.log file has larger than 0 length, this is likely NOT the issue.

**Comment by mt5555** [comment]
@ndkeen is this fixed yet? I agree that 64GB is too much memory to be allocating as part of a test.     

without an error code check, I assume the allocate() statement aborts.  we could add an error code and just print a warning if the allocate fails.

**Comment by rljacob** [comment]
I thought it would be fixed in latest CIME update but wasn't.  @jgfouca, do you know why the change to  cime/src/share/util/shr_mem_mod.F90 in https://github.com/ESMCI/cime/pull/3457/commits/da3c66984aac3ca5aea84dd5c0eab68c85b9fbf4 didn't make it over?

**Comment by jgfouca** [comment]
@rljacob , there were changes to that line on both sides and either subtree or my script must have selected the E3SM side.

**Comment by jgfouca** [comment]
Hmm, actually none of those changes made it over, so the entire file was somehow mishandled.

**Comment by jgfouca** [comment]
Should I make a PR with those changes?

**Comment by rljacob** [comment]
Yes please do.

**Comment by jgfouca** [comment]
Fixed by #3557 , @ndkeen , can you confirm?

**Comment by ndkeen** [comment]
I thought I had mentioned this in this github issue, but I'm also able to show this memory problem by using simple ne4 F case and requesting 128 MPI's on 1 node. To repeat, need some xmlchange commands. And I can verify that this test fails before this change (#3557) and completes after.

**Comment by ndkeen** [comment]
This wasn't assigned to anyone, but can we just say it's now fixed?

**Comment by jgfouca** [comment]
Thanks for confirming, @ndkeen
