### ISSUE TITLE
Build failure in mpas-ocean with maint-1.0 on cori

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#3528]
I'm getting a build failure in mpas-ocean with maint-1.0. I will try to see if there was a recent change to repo that caused it. In order to use maint-1.0 on cori, I needed to merge a PR to correct the directory names (going from "acme" to "e3sm"), but I don't think this created the problem.

```
create_test SMS_D.T62_oEC60to30v3.GMPAS-IAF

...

    Case dir: /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo
    Errors were:
        Building test for SMS in directory /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo
        ERROR: BUILD FAIL: mpaso.buildlib failed, cat /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/ocn.bldlog.200401-101458

...

End of ocn.bldlog:

make[2]: Leaving directory '/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/ocn/source/core_ocean'
( cd core_ocean; make CPPFLAGS="-DCORE_OCEAN -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL  -DLINUX   -DARCH_MIC_KNL  -DUSE_PIO2   -DOFFSET64BIT  -DMPAS_NO_LOG_REDIRECT -DMPAS_NO_ESMF_INIT -DMPAS_ESM_SHR_CONST -D_MPI -DMPAS_NAMELIST_SUFFIX=ocean -DMPAS_EXE_NAME=ocean_model -DMPAS_PERF_MOD_TIMERS -DUNDERSCORE -DMPAS_DEBUG -DMPAS_OPENMP -DCORE_OCEAN -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL  -DLINUX   -DARCH_MIC_KNL  -DUSE_PIO2   -DOFFSET64BIT  -DMPAS_NO_LOG_REDIRECT -DMPAS_NO_ESMF_INIT -DMPAS_ESM_SHR_CONST -D_MPI -DMPAS_NAMELIST_SUFFIX=ocean -DMPAS_EXE_NAME=ocean_model -DMPAS_PERF_MOD_TIMERS -DMPAS_DEBUG -DMPAS_OPENMP" CPPINCLUDES="-I/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/ocn/source/inc -I/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/intel/mpt/debug/threads/include -I/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/intel/mpt/debug/threads/mct/noesmf/c1a1l1i1o1r1g1w1e1/csm_share -I/opt/cray/pe/netcdf-hdf5parallel/4.6.1.3/INTEL/16.0/include -I/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/intel/mpt/debug/threads/pio -I/opt/cray/pe/parallel-netcdf/1.8.1.4/INTEL/18.0/include -I/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/ocn/source/inc -I/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/intel/mpt/debug/threads/include -I/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/intel/mpt/debug/threads/mct/noesmf/c1a1l1i1o1r1g1w1e1/csm_share -I/opt/cray/pe/netcdf-hdf5parallel/4.6.1.3/INTEL/16.0/include -I/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/intel/mpt/debug/threads/pio -I/opt/cray/pe/parallel-netcdf/1.8.1.4/INTEL/18.0/include" all ) 
make[2]: Entering directory '/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/ocn/source/core_ocean'
(/bin/bash ./get_cvmix.sh)
unlink: cannot unlink 'cvmix': Is a directory
(cd cvmix)
if [ -d cvmix ]; then \
        (cd cvmix; make all FC="ftn " FCFLAGS="-convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model consistent -fimf-use-svml  -qopenmp  -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created  -DMPAS_NO_LOG_REDIRECT -DMPAS_NO_ESMF_INIT -DMPAS_ESM_SHR_CONST -DMPAS_PERF_MOD_TIMERS" FINCLUDES="") \
else \
        (exit 1) \
fi
make[3]: Entering directory '/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/ocn/source/core_ocean/cvmix'
make[3]: *** No rule to make target 'all'.  Stop.
make[3]: Leaving directory '/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/ocn/source/core_ocean/cvmix'
make[2]: *** [Makefile:57: libcvmix] Error 2
make[2]: Leaving directory '/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/ocn/source/core_ocean'
make[1]: *** [Makefile:41: dycore] Error 2
make[1]: Leaving directory '/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/ocn/source'
make: *** [Makefile.in.ACME:73: all] Error 2
ERROR: mpas-ocean buildlib cd /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/ocn/source; make all CORE=ocean ESM=ACME DRIVER=ocean_cesm_driver GEN_F90=true ROOT_DIR="/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo/bld/ocn/source" failed: 512
```

**Comment by ndkeen** [comment]
Using a maint-1.0 repo I had from Oct23rd (and applying the same changes to config_machines.xml that allow using "e3sm" repo vc "acme") the build completed.

**Comment by jonbob** [comment]
@ndkeen - let me see if I can replicate that...

**Comment by jonbob** [comment]
@ndkeen - I just did a clean clone of maint-1.0 on cori and built a fully-coupled case jus fine. Can you point me to your failure?

**Comment by ndkeen** [comment]
OK thanks.
One case with issue is here:
`/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SMS_D.T62_oEC60to30v3.GMPAS-IAF.cori-knl_intel.20200401_101212_qpkajo`

I will check to see if my specific environment changes from the default are a problem.

**Comment by jonbob** [comment]
@ndkeen - I got the same failures you saw when using your codebase instead of mine. I compared them and you have extra directories under components/mpas-source/src/core_ocean for BGC and cvmix that I don't have -- and are not in git (at least for maint-1.0). That looks more like master -- any chance things got mixed and matched?

**Comment by ndkeen** [comment]
Hmm, so one thing I'm doing differently now when I clone repos is using the `--recursive` flag like so:  `git submodule update --recursive --init`

Are referring to this repo?

```
cori07% pwd
/global/cscratch1/sd/ndk/wacmy/E3SM_code/20200401-maint-1.0
cori07% git branch
* maint-1.0
  master
```

**Comment by jonbob** [comment]
yes -- I think master has left artifacts in the mpas-source

**Comment by jonbob** [comment]
@ndkeen - did you update master's submodules before checking out maint-1.0?

**Comment by ndkeen** [comment]
I *think* I am cloning master repo, updating submodules, checking out maint-1.0, and updating submodules again. But I will double-check.

I just tried the process again *without* the `--recursive` flag and I got the same build failure.

**Comment by jonbob** [comment]
I think it's problematic to have submodules floating around from master and assuming the other branches can be checked out over them. Can you try cloning and checking out maint-1.0 and not updating the master submodules first?

**Comment by jonbob** [comment]
Sorry -- I see I wasn't clear. I don't think you want to check out master and get its submodules before using the same codebase for maint-1.0 or any other branch. If you do that in your workflow, I think there are other git commands you need? sync? @jgfouca, any thoughts?

**Comment by ndkeen** [comment]
OK, I can try that, but this order is the way our run_e3sm scripts are checking out the code. At least the one I'm looking at right now. Clones master, submodule init, then checkout maint-1.0 (and actually I'm not seeing another submodule init which may be needed).

**Comment by jonbob** [comment]
ah, don't get me started on the whole run_e3sm pile - there's no guarantee that anything in there is a good workflow. So please try that by hand and see if it solves the issue...

**Comment by ndkeen** [comment]
OK, if I skip the submodule init after cloning master (or supply -b flag to git clone to get the branch directly), but use submodule init after checkout out maint-1.0, I indeed end up with many differences in the repo. And the test I was trying builds.  

Thanks for the help Jon.

We can close this issue. Would it make any sense to attempt a simple test to look for this before trying to build?

**Comment by ndkeen** [comment]
Closing issue with no changes needed as it involves how I was obtaining the repo. At least in this instance, it is important to not do `git submodule update --recursive --init` before checking out the branch (maint-1.0 in this case). But, of course, need this command after checking out branch.

**Comment by jonbob** [comment]
@ndkeen - do you want to open a PR to fix the run_e3sm scripts? I'm glad that was the problem but now worried about the automated scripts...

**Comment by ndkeen** [comment]
OK I created https://github.com/E3SM-Project/E3SM/pull/3530 as a start.

**Comment by cameronsmith1** [comment]
> ah, don't get me started on the whole run_e3sm pile - there's no guarantee that anything in there is a good workflow. So please try that by hand and see if it solves the issue...

Fixing the run_e3sm script template is a good way to help many users use the latest workflow :-).   It used the recommended workflow when it was written a few years ago, but times change ;-).

**Comment by ndkeen** [comment]
Note that this "solution" may have also corrected a problem I was having on theta with same repo. The issue was not the same -- in that case the code was trying to download data that was already there at failed.
