### ISSUE TITLE
PIO_TYPENAME setting only followed during testing.

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#3550]
Our config_pio.xml file has this block:
```
  <entry id="ATM_PIO_TYPENAME">
    <values>
      <value compset="DATM">netcdf</value>
    </values>
  </entry>
```
Any case that has datm for the atmosphere, e.g. any I or G case, should have PIO_TYPENAME for the atmosphere set to "netcdf". 

But this seems to only happen in the Jenkins-run testing.  Any attempt to build an I case or I test by hand results in a value of pnetcdf.   No idea why.

First noticed this when a namelist diff on compy showed a change from pnetcdf to netcdf.  Could not reproduce the setting of netcdf.   This was next  e932d0797.

We don't do a lot of testing on master.  Melvin has everything set to netcdf because its a workstation.

**Comment by rljacob** [comment]
To see this, to a test directory on cori, anvil or compy for an I case (using TestStatus output on cdash to fine the dir).   Do "./xmlquery PIO_TYPENAME".    Build the same test yourself (use the --no-build option) on that machine and examine PIO_TYPENAME in its casedir.

**Comment by jgfouca** [comment]
Looking at this now.
