### ISSUE TITLE
Error in create_newcase: Error: Multiple matches

### ISSUE THREAD

**Issue by dwang27** [E3SM-Project/E3SM#3566]
I am a new user of E3SM.
I downloaded run_e3sm.DECKv1b_piControl.ne30_oEC.cori-knl.csh and tried to run it on my machine.
Here is the create_newcase command I use.
/E3SM/cime/scripts/create_newcase --case test111 --compset A_WCYCL1850S_CMIP6 --script-root /E3SM/E3SM_simulations/test111/case_scripts --res ne30_oECv3_ICG --pecount S --handle-preexisting-dirs u --mach hydra --output-root /E3SM/E3SM_simulations/test111.
The error showed as :
Machine is hydra
ERROR: Multiple matches.

I have no idea what does this mean.
Anyone has any suggestions?

**Comment by jgfouca** [comment]
@dwang27 , this must be on a pretty old version of E3SM; I improved that error message years ago. I would avoid reusing cases if at all possible. See if that helps.

**Comment by rljacob** [comment]
The script is written for cori-knl so good that you switched to create_newcase.  But if you don't also port the build system to your machine, nothing will work.
Jim, its likely he has maint-1.0 which may not have that fix.

**Comment by jgfouca** [comment]
Closing with the recommendation to not reuse cases with old versions of E3SM.
