### ISSUE TITLE
Add case names to MPAS output file names

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/E3SM#3576]
Adding case names to MPAS output files will help to identify origin of the file, facilitating archiving, publication and distribution. @jonbob Please revive your branch on this. And thank you for taking care of it!

**Comment by chengzhuzhang** [comment]
Hi @jonbob, we are planning out the analysis tools to accommodate v2 new model component names (from 'cam' and 'clm2' to 'eam' and 'elm'). I was wondering if we could try to squeeze in this PR to have case name for MPAS output for v2 simulations?

**Comment by jonbob** [comment]
Thanks for the reminder @chengzhuzhang - yes, it seems like the best time to do this. I'll try to get started on it today

**Comment by chengzhuzhang** [comment]
Thank you for working on this, Jon!

**Comment by chengzhuzhang** [comment]
Hey @jonbob, just checking if we are going to make this before v2 simulation starts? I'm curious if adding case names will have some side effect, i.e., restart from old restart files that don't have case names in the file name.

**Comment by jonbob** [comment]
I'm working on it. It shouldn't be any more disruptive than changing "clm" to "elm" and "cam" to "eam" -- anyone who wants to use old restart files would have to rename them by hand, which I assume happens for the component name changes as well?

**Comment by rljacob** [comment]
Yes its just a rename.

**Comment by jonbob** [comment]
@chengzhuzhang - OK, I have a branch I'm testing and will make a PR once I think it's doing the right thing. At least it sets the output names correctly for a smoke test, but I need to make sure it understands how to restart

**Comment by xylar** [comment]
@chengzhuzhang, I had originally interpreted the request to be to add the case name as an attribute in the output files (which would actually be considerably more challenging).  If it is just to include the case name in the file name, could you rename the issue and change the description "MPAS output files" --> "MPAS output file names"?  That would clear things up.
