### ISSUE TITLE
cmake build on summit ignores OpenACC gpu compiler flags

### ISSUE THREAD

**Issue by xyuan** [E3SM-Project/E3SM#3585]
cmake build on summit ignores OpenACC gpu compiler flags due to the renamed/deleted file names in FILES_NEED_CUDA_FLAGS, this issue is fixed by PR #3584

**Comment by xyuan** [comment]
This issue was fixed, so I close this issue.

**Comment by rljacob** [comment]
Don't close until the fix is merged to master.

**Comment by whannah1** [comment]
Closing this because there are bigger problems with the summit configuration for the MMF.

**Comment by rljacob** [comment]
Then open an issue describing the problem.
