### ISSUE TITLE
New CMake system does not save preprocessed MPAS files for Debug

### ISSUE THREAD

**Issue by akturner** [E3SM-Project/E3SM#3586]
The old E3SM build system used to save the preprocessed MPAS source files. This was very useful for debugging as the line numbers given from a stack trace are for the preprocessed files. With the CMake build system these files aren't saved and its very difficult to determine what code line the stack trace refers to, making the new CMake build system hard to use for debugging. Could the new CMake build system keep the preprocessed MPAS source files?

**Comment by vanroekel** [comment]
@jgfouca any chance you have time for this one in the near future?  I think this would be a pretty important fix and without it it is nearly impossible to do debugging.  It's really the only reason I never use the cmake build system.

**Comment by jgfouca** [comment]
@vanroekel , sorry for the slow fix. I plan on getting to this this week.

**Comment by vanroekel** [comment]
thanks for the update @jgfouca!

**Comment by jgfouca** [comment]
@akturner , @vanroekel , @jonbob , I'm looking at this now and I think that Cmake system is doing what you want, it's just putting the generated files in a different spot than you're used to.

For example, I did this:
% ./create_test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST --no-run
...
% cd $case_dir
% ./xmlquery EXEROOT
...
% cd $EXEROOT/cmake-bld
% find -name "*.f90"
... lots of generated MPAS files ...

I was able to modify these files and do incremental builds etc just fine.

**Comment by jgfouca** [comment]
@akturner , @vanroekel , @jonbob , please advise.

**Comment by vanroekel** [comment]
@jgfouca this works for me.  All the files I need for there.  Thanks for pointing this out, I'll just have to get used to and remember the new location.

  I'll wait for @jonbob and @akturner to confirm this works for them.

**Comment by jgfouca** [comment]
@vanroekel , great! Glad to hear it

**Comment by jgfouca** [comment]
Closing. Reopen if there are still concerns.
