### ISSUE TITLE
Homme: Boundary exchange copy threading

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/E3SM#3587]
I noticed that in bndry_exchangeV_core singlethread_copy was initialized to .false. at declaration, but that means once it's set to .true., it retains that value at next subroutine call via an implicit save attribute. This was preventing the threaded copying from running. The fix is simply to initialize it in the executable part of the subroutine.

However, performance profiling on cori-knl with an F case, ne30pg2, 43 nodes (-pecount S), 32x4 proc x threads per node, shows that the fix actually slows down the boundary exchange. I speculate it's because the memory is not resident in HBM.

I'm working on a v2-performance PR for physgrid and SL transport. I was going to include the fix in it, but it's the one part of the PR that is not leading to clear speedup (again, in fact slowdown). So I'm dropping the commit and just reporting the issue here.

**Comment by ambrad** [comment]
Update: I did some more KNL runs today. Looks like I got a sequence of bad runs last week; now this fix shows a bit of speedup. We don't expect much speedup with the standard 32x4 decomp per node, but certainly we expect no slowdown. Based on today's runs, I'll likely include the fix in PR #3594.

**Comment by ambrad** [comment]
Never mind. There's too much variation to tell for sure. I want PR #3594 to have only robust improvements; this boundary exchange bug fix falls below that threshold.

**Comment by mt5555** [comment]
bug is also in bndry_exchangeS_* routines?  But probably not triggered since they would be unlikely to be called single threaded in a threaded run.
