### ISSUE TITLE
pio_freedecomp aborts when trying to sync a closed file

### ISSUE THREAD

**Issue by mt5555** [E3SM-Project/E3SM#3605]
A 5 month run (which triggers CICE h0 file writing) of F2010SC5-CMIP6 + ne4pg2_ne4pg2 crashes in Scorpio (but not in Scorpio classic), with error message:

59: PIO: FATAL ERROR: Aborting... An error occured, Syncing file (ncid=80) failed. Invalid file id. Unable to find internal structure associated with the file id. err=-33.

Problem seems to be that pio_freedecomp() when called with this interface, will call pio_syncfile(), but as the file has already been closed, this aborts.  

@jayeshkrishna : what's the correct fix?  should we call pio_freedecomp() before closing the file?  Or maybe pio_freedecomp() should not be calling pio_syncfile?  
Another option woudl be to use "call pio_freedecomp(File%iosystem,iodesc2d)" which avoids the pio_syncfile() call, but then the code segfaults later.  

code is in cice, ice_history_write.F90

`
      !-----------------------------------------------------------------
      ! close output dataset
      !-----------------------------------------------------------------

      call  pio_closefile(File)
      if (my_task == master_task) then
         write(nu_diag,*) ' '
         write(nu_diag,*) 'Finished writing ',trim(ncfile(ns))
      endif
      
      ! -------------------------
      ! clean-up PIO descriptors
      ! -------------------------
      call pio_freedecomp(File,iodesc2d)
      call pio_freedecomp(File,iodesc3d)
`

**Comment by jayeshkrishna** [comment]
The code above looks buggy, pio_freedecomp() is using a File that has already been closed. I will take a look and fix this issue.

**Comment by jayeshkrishna** [comment]
@mt5555 : Do you have a test case (create_newcase/create_test command) that shows the issue?

**Comment by jayeshkrishna** [comment]
jayeshkrishna/fix_cice_hist_sync_fail branch has a potential fix for this issue.

**Comment by mt5555** [comment]
That lets the code run further, but then I get this error, also in CICE:

PIO: FATAL ERROR: Aborting... An error occured, Writing multiple variables to file (f2010nh-ne4np4.cice.h.0001-01.nc, ncid=79) failed. Invalid arguments, invalid PIO decomposition id (518) provided. err=-33.

I'm running:
create_newcase -res ne4pg2_ne4pg2  -compset F2010SC5-CMIP6
and then changing the length from 5 days to 5 months (which triggers CICE h0 file writing).

**Comment by rljacob** [comment]
I'm not sure we have any tests that force CICE to write a history file.

**Comment by mt5555** [comment]
I'm running a relatively new compset.  A good test would be the regular ne4_ne4 F compset, but run for 2 months. (I haven't tried that yet...)

**Comment by mt5555** [comment]
update: proposed fix does work (I needed to do a clean build).  
@jayeshkrishna will you submit a PR for your branch?

This may be urgent, since any  F case that runs longer than a month will hit this bug?
