### ISSUE TITLE
Ocean BGC not supporting threading?

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#3619]
Use latest master with any machine that has a config with threads>1.   Create a case with the following.  (I did this on cori).
--compset BGCEXP_BCRC_CNPRDCTC_1850 --res ne30_oECv3

During ./case.setup, you get this error:
```
   Calling /global/u2/r/rjacob/E3SM/components/mpas-ocean/cime_config/buildnml
ERROR:  ERROR mpas-o buildnml: ocn bgc cannot be run with more than 1 thread
```

I thought ocean BGC threading was fixed on master?

**Comment by jonbob** [comment]
I'll check. If it is working, I'll make a PR to remove that check
