### ISSUE TITLE
land/sea ice mask inconsistency with ne120np4_r0125_oRRS18to6v3

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#3622]
This runtime error arises when trying to run an F-case using ne120np4_r0125_oRRS18to6v3 grid. It is intended to do an F-case nudging simulation to spin up land and derive a land IC at r0125 resolution.

The error message is like
`ERROR: (seq_domain_check)   inconsistency between land mask and sea ice mask:  n=          101  fracl=  -1.434970921420591E-003  fraci=  0.984238415340975`

Below is the backtracing in the codes
  ```
          shr_abort_mod_mp_           114  shr_abort_mod.F90
           seq_domain_mct_mp         427  seq_domain_mct.F90
           cime_comp_mod_mp_        1906  cime_comp_mod.F90
           MAIN__                             122  cime_driver.F90
```
I assumed up to this point what involved are just the domain files. For this case, the following domain files are used.
```
           LND_DOMAIN_FILE = domain.lnd.r0125_oRRS18to6v3.200212.nc
           OCN_DOMAIN_FILE = domain.ocn.oRRS18to6v3.170111.nc
           ICE_DOMAIN_FILE = domain.ocn.oRRS18to6v3.170111.nc

```
Note that with the same domain files, there is no problem with at least two other tri-grids, with difference in just atm grid,, one for lower resolution and the other for hjgher: ne30np4_r0125_oRRS18to6v3 and ne256pg2_r0125_oRRS18to6v3. I believe it is also ok for ne1024np4.

I am puzzled. Could there be other files or factors involved in determining the consistency between land mask and sea ice mask? 

Pinging @mt5555 , @brhillman , @rljacob , @jonbob , @paullric , @czender for help.

**Comment by wlin7** [comment]
The above domain.lnd and domain.ocn were generated from different times.  

The attributes in "domain.lnd.r0125_oRRS18to6v3.200212"  indicates this domain file is generated based on mapfile "/global/homes/t/taylorm/proj/mapping/map_oRRS18to6v3_to_r0125_nco.nc" by @mt5555.

Considering potential inconsistency because the domain.lnd and domain.ocn were not generated based on the same source, I re-did a gen_domain using map_oRRS18to6v3_to_r0125_nco.nc. The new domain.lnd.r0125_oRRS18to6v3 is identical. The new domain.ocn is used to replace the obe above. Same problem remains.

**Comment by wlin7** [comment]
The inconsistency between the land mask and sea ice mask is alerted using the following logic
`if ((1._R8-fraci(n)) > eps_frac .and. fracl(n) < eps_tiny) then`
eps_frac by default is 1e-02. I tried to bypass this checking by relaxing to 2.0e-2 to be beyond the printed values in e3sm.log for 1-fraci. The model would later be aborted with
`(seq_frac_check) [atm init] ERROR aborting`

**Comment by brhillman** [comment]
@wlin7 it looks like this configuration is not in master? You point out that the domain file is based on `/global/homes/t/taylorm/proj/mapping/map_oRRS18to6v3_to_r0125_nco.nc`...can you check how your run is configured in regards to the mapping files between the ocean and land? I think it's important that these mapping files that are used online in the model are the same as are used to create the domain files.

**Comment by ndkeen** [comment]
May or may not be same thing, but an error I would see with some older ne1024 attempts was:

``` 
263:  inconsistency between land mask and sea ice mask
 263:  n=         4042  fracl=   0.000000000000000E+000  fraci=
 263:   0.000000000000000E+000
 263:  ERROR: (seq_domain_check)   inconsistency between land mask and sea ice mask
 263: Image              PC                Routine            Line        Source
 263: e3sm.exe           0000000004B6D096  Unknown               Unknown  Unknown
 263: e3sm.exe           0000000002E0A3FC  shr_abort_mod_mp_         114  shr_abort_mod.F90
 263: e3sm.exe           0000000000489DDE  seq_domain_mct_mp         427  seq_domain_mct.F90
 263: e3sm.exe           0000000000419F8C  cime_comp_mod_mp_        1891  cime_comp_mod.F90
 263: e3sm.exe           0000000000421A34  MAIN__                    122  cime_driver.F90
 263: e3sm.exe           0000000000401F6E  Unknown               Unknown  Unknown
 263: e3sm.exe           0000000004D43C4F  Unknown               Unknown  Unknown
 263: e3sm.exe           0000000000401E5A  Unknown               Unknown  Unknown
```

**Comment by wlin7** [comment]
> @wlin7 it looks like this configuration is not in master? You point out that the domain file is based on `/global/homes/t/taylorm/proj/mapping/map_oRRS18to6v3_to_r0125_nco.nc`...can you check how your run is configured in regards to the mapping files between the ocean and land? I think it's important that these mapping files that are used online in the model are the same as are used to create the domain files.

Good points, @brhillman . In the current config, no direct mapping between ocn and lnd involved during runtime. The mapfile map_oRRS18to6v3_to_r0125_nco.nc is not in use. Same in the F-case ne30 run and ne256pg2 run (by @crterai ) that use the same domain.lnd and domain.ocn files. Ben, do you remember the map files between which components  that you had to mess with to fix a similar problem? That could give some helpful hint. Thanks.

**Comment by brhillman** [comment]
Okay I'm a little confused then, because I thought those mapping files were used in the domain checking code to confirm that the mapped land/ice fractions where consistent with what's in the domain files, but maybe those are all mapped to the atmosphere grid first for checking (the only grid that overlaps the domain of each component). So with that, I believe the problematic mapping was between either land or ocean to atmosphere. In one configuration, I solved this by creating "mono" maps for both the flux and state maps between each component (*not* the monotr maps, although in principle those should actually be *better*, but those were the maps I was having trouble with; again suspected inconsistency between the domain files and online mapping files).

**Comment by wlin7** [comment]
> , but maybe those are all mapped to the atmosphere grid first for checking (the only grid that overlaps the domain of each component).

I think this makes very good sense and those are the files that are different from ne30 or ne256pg2 cases. Either the quality of some of the mapfilesto/from atm has issue, or inconsistent in some way. Thanks Ben, this gives me extra ideas to explore. Note that I did't push the branch to remote because I wanted to test first those map files. I played with some of the mapping files, but not in exhaustive manner as I was not sure if map files were involved  in domain consistency check. They must.

**Comment by mt5555** [comment]
In a tri-grid setup, I think the identification of land/ocean/mixed points in the land model is computed during initialization based on the ocn->atm land mask.  So all points in the atmosphere that have at least partial land need to receive data from the land model.  Which means that the source points for the lnd->atm map associated with the partial land points on the atm grid need to be active in the land model.  

I'm not sure how this is done. It's a sophisticated algorithm developed by CSEG.  Best would be to somehow compute all points on the land grid which need to be active based solely on the ocn->atm and lnd->atm map, meaning the mask in the domain.lnd file is not needed or used.  But one possibility is that when doing this calculation,  the driver only considers possible land points based on the subset of land and partial land points identified in the domain.lnd file.  

This could explain some of Ben's earlier results when using the "monotr" map.  It has a wider stencil than an "aave" map, meaning the coastline on the atmosphere side is a little fuzzier and extends (with small land fraction) further out into the ocean.  The domain.lnd file would then also need to extend the land out further into the ocean.   

This is just wild speculation, but if ocean->atm is "monotr", you could try replacing it with an aave map (and regenerating a domain.lnd file).  

Also, if this is the problem, we should have the same issue with ocean, not just ice.  But maybe ice is the first condition that is checked?

Mark

**Comment by wlin7** [comment]
This issue is now considered resolved. All needed is a new LND2ATM mapping file. Previously a highorder mapping file was used. The problem is gone when a mono map is used. Note that both map files pass checks.

There could be other way, for example, using an alternative OCN2ATM or ICE2ATM maps; but these have not been tested. 

For record, varying domain files or ATM2LND maps has zero impact on the consistency check: the departures from unity do not change for any segments.

PR [#3663 ](https://github.com/E3SM-Project/E3SM/pull/3663) adds support for this grid (ne120_r0125_oRRS18to6v3) along with ne30_r0125_oRRS18to6v3.

**Comment by wlin7** [comment]
Thanks all for very helpful breakdown and tips. I am closing it now, but feel free to re-open if any further comments.

**Comment by mt5555** [comment]
@wlin7 , when you wrote:  "Previously a highorder mapping file was used.",  does that refer to the state map?  (since the flux map would normally have been of type "mono").  So that now both state and flux are using "mono" maps?   If this is the case, I would like to understand better what is going on.  

Or was the flux map high order (which would have been a mistake in the config)?

**Comment by wlin7** [comment]
Yes, @mt5555, I did use highorder map for both FMAP and SMAP. Both now changed to mono. I expected using different maps could affect accuracy; didn't expect it would cause such an inconsistency.

**Comment by wlin7** [comment]
In #3663, I am still using highorder map for LND2ATM_FMAP for ne30np4 to r0125. Thank you @mt5555 for pointing out this distinction. I will update that PR, though for ne30np4 it didn't cause land/ice mask inconsistency (the discrepancy small enough to not trigger the complaint). Your comments above on how the mixed points are handled help me to focus on LND2ATM map to find a fix.

**Comment by mt5555** [comment]
Great, based on these updates, I'm going to conclude that the main problem was the LND2ATM_FMAP - since it's it used for the land mask, the weights have to be monotone, so the use of high order weights (non monotone) was most likely the issue.  

The high-order could probably be used for state variable maps, but that's currently not recommended ( per recommendations:  https://acme-climate.atlassian.net/wiki/spaces/ED/pages/178848194/Transition+to+TempestRemap+for+Atmosphere+grid ) because it seems dangerous to use  mapping files with weights > 1, at least not until this has been thoroughly tested.

**Comment by wlin7** [comment]
> Great, based on these updates, I'm going to conclude that the main problem was the LND2ATM_FMAP - since it's it used for the land mask, the weights have to be monotone, so the use of high order weights (non monotone) was most likely the issue.

Exactly, Mark. Just completed another test earlier by replacing just LND2ATM_FMAP with a mono map, and no inconsistency issue. Although highorder map is ok for LND2ATM_SMAP in this test, we will use mono for both FMAP and SMAP.
