### ISSUE TITLE
F2010SC5-CMIP6 uses mosart?

### ISSUE THREAD

**Issue by mt5555** [E3SM-Project/E3SM#3641]
The F2010SC5-CMIP6 compset turns on the mosart river runoff model.  Historically I thought F compsets had this turned off, such as in FC5AV1C-L.   I noticed this because some obscure grids, which dont have a ROF mapping file default, will run with FC5AV1C-L, but not F2010SC5-CMIP6 

Should mosart be turned off in F2010SC5-CMIP6 or was this done intentionally?

the runoff I assume is ignored by the data ocean model in an F case and will have no impact on the solution.  But perhaps the output is of interest for some diagnostic?

**Comment by tangq** [comment]
@mt5555 , this was done intentionally. At some point, we decided to turn on ROF for F compsets. Additional diagnostic is one of the reasons (we will include some river development in v2), but I don't recall all the details. Pinning @golaz .

**Comment by mt5555** [comment]
great, thanks for the quick answer.
