### ISSUE TITLE
unexpected behavior in build system

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#3644]
On Compy when using PGI and -O2 optimization, building E3SM with pcols
set at runtime is not BFB when compared with building with pcols set at
compile time (using an F case). However, if we set the optimization level for all
of E3SM to -O1, it is BFB. The goal is not to build the whole model with -O1 
when the issue should affect only CAM.

However, even if I build ALL components and libraries with -O1 (overriding the
global setting), setting the whole model optimization level to -O2 reintroduces the 
non-BFB behavior.

Details follow. I modified both Macros.cmake and Macros.make to either

a) set model optimization to level to -O1 for the whole model, e.g., for
Macros.cmake

       if("${DEBUG}" STREQUAL "FALSE")
         set(FFLAGS "${FFLAGS}  -O1")
         set(CFLAGS "${CFLAGS}  -O1")
       endif()

Then add -O2 -Mnovect to each of the component models and libraries
relevant to the F case, as well as those already called out in the Macros
files (dwav, dice, dlnd, datm, docn, cpl, clm, cice, srof, sglc, swav, siac, 
sesp, gptl, csm_share, mct, pio2, and drof), e.g., for clm,

       if("${COMP_NAME}" STREQUAL "clm")
         set(FFLAGS "${FFLAGS} -O2 -Mnovect")
         set(CFLAGS "${CFLAGS} -O2 -Mnovect")
      endif()

except for cam, which I set to -O1 -Mnovect:

       if("${COMP_NAME}" STREQUAL "cam")
         set(FFLAGS "${FFLAGS} -O1 -Mnovect")
         set(CFLAGS "${CFLAGS} -O1 -Mnovect")
       endif()

b) set model optimization level to -O2 for the whole model, e.g., for
Macros.cmake, 

       if("${DEBUG}" STREQUAL "FALSE")
         set(FFLAGS "${FFLAGS}  -O2")
         set(CFLAGS "${CFLAGS}  -O2")
       endif()

then add -O1 -Mnovect to each of the other component models and libraries
(dwav, dice, dlnd, datm, docn, cam, cpl, clm, cice, srof, sglc, swav, siac, sesp, 
gptl, csm_share,mct, pio2, and drof), which includes cam this time, e.g.,

       if("${COMP_NAME}" STREQUAL "cam")
         set(FFLAGS "${FFLAGS} -O1 -Mnovect")
         set(CFLAGS "${CFLAGS} -O1 -Mnovect")
       endif()

       if("${COMP_NAME}" STREQUAL "clm")
         set(FFLAGS "${FFLAGS} -O1 -Mnovect")
         set(CFLAGS "${CFLAGS} -O1 -Mnovect")
       endif()

The result: 

      (a) is BFB between runtime and compile time pcols
      (b) is not BFB between runtime and compile time pcols

I have looked through the bldlogs, and the flags for (a) are 

     -O1 -O1 -Mnovect

for CAM files, and

     -O1 -O2 -Mnovect

for everything else (including the link step).

For (b), all files are compiled with

     -O2 -O1 -Mnovect

and this is also used for the link step. As far as I can tell, the later flags override 
the earlier ones, like they should. I have looked for files that are not included in 
the list of components and libraries, and have found nothing.

I suppose that system libraries and the like could be loaded based on the optimization level, but the link step for the BFB build is -O1 -O2 -Mnovect (so -O2 is operative) and for the non-BFB build the link step is -O2 -O1 -Mnovect (so -O1 is operative).

Note that -O1 -O1 -Mnovect for all files and for the link step is BFB, so linking with -O1 is not introducing the problem.

Help? I have no idea what I could be missing. I've tried other experiments as well, but the above is the clearest demonstration. For example, I also tried using Depends files, which adds the overriding flags even later in the list of flags, but this made no difference.

I also tried non-CMake build searlier, and saw the same behavior. I did not however try exactly the experiment described above. I'll try that as well, but do not expect it to change anything.

**Comment by amametjanov** [comment]
Just to double-check, are both Macros.make and Macros.cmake updated? Macros.make is still being used for building gptl, mct, pio and csm_share libraries.

Also, when re-building existing case, new CIME needs `./case.setup --keep [Macros.make, Macros.cmake]` prior to building to keep updates.

**Comment by worleyph** [comment]
Note that I had a similar problem with Intel on Compy, where setting "-fp-model fast"
for all of CAM, then overriding this for each individual CAM file in Depends did not restore
reproducibility, even though setting -fp-model source for all of CAM in Macros.cmake
and then setting -fp-model fast for all put a few files in CAM in the Depends file was BFB. I am not as confidant that I have looked at all options for this case yet (I stopped awhile back, having run out of ideas - the above issue is more recent.)

**Comment by worleyph** [comment]
@amametjanov , I modified both Macros.cmake and Macro.make. I also did a clean-all between each experiment (actually renamed the bld directory after each experiment so that I could save it). This version is just old enough that I don't need the "keep" option? The bldlogs reflect what I am requesting in the Macros files.

**Comment by worleyph** [comment]
@amametjanov , "keep" is in my version of case.setup, but 

     When cleaning/resetting a case, do not remove/refresh files in this list.

I am not resetting or cleaning the case, only ./case.build --clean-all; ./case.build . In any case, my Macros.cmake and Macros.make are not being overwritten.

**Comment by worleyph** [comment]
non-CMake build behaved the same (for case b) and was BFB with the CMake build. Looking at the bldlogs however, all files in e3sm.bldlog are compiled with -O2 only:

     cime/src/drivers/mct/main/seq_map_type_mod.F90
     cime/src/drivers/mct/main/t_driver_timers_mod.F90
     cime/src/drivers/mct/main/mrg_mod.F90
     cime/src/drivers/mct/main/component_type_mod.F90
     cime/src/drivers/mct/main/seq_map_mod.F90
     cime/src/drivers/mct/main/seq_io_mod.F90
     cime/src/drivers/mct/main/seq_diag_mct.F90
     cime/src/drivers/mct/main/seq_flux_mct.F90
     cime/src/drivers/mct/main/map_glc2lnd_mod.F90
     cime/src/drivers/mct/main/map_lnd2glc_mod.F90
     cime/src/drivers/mct/main/prep_atm_mod.F90
     cime/src/drivers/mct/main/prep_ice_mod.F90
     cime/src/drivers/mct/main/map_lnd2rof_irrig_mod.F90
     cime/src/drivers/mct/main/prep_wav_mod.F90
     cime/src/drivers/mct/main/prep_lnd_mod.F90
     cime/src/drivers/mct/main/prep_glc_mod.F90
     cime/src/drivers/mct/main/cplcomp_exchange_mod.F90
     cime/src/drivers/mct/main/prep_iac_mod.F90
     cime/src/drivers/mct/main/prep_rof_mod.F90
     cime/src/drivers/mct/main/prep_ocn_mod.F90
     cime/src/drivers/mct/main/prep_aoflux_mod.F90
     cime/src/drivers/mct/main/seq_domain_mct.F90
     cime/src/drivers/mct/main/seq_frac_mct.F90
     cime/src/drivers/mct/main/seq_hist_mod.F90
     cime/src/drivers/mct/main/seq_rest_mod.F90
     cime/src/drivers/mct/main/component_mod.F90
     cime/src/drivers/mct/main/cime_comp_mod.F90
     cime/src/drivers/mct/main/cime_driver.F90

In contrast, e3sm.bldlog for the CMake build indicates that the above are all compiled with

     -O2 -O1 -Mnovect

I was wondering what component or library (among dwav, dice, dlnd, datm, 
docn, cam, cpl, clm, cice, srof, sglc, swav, siac, sesp, gptl, csm_share,mct, pio2, 
and drof) was setting the -O1 -Mnovect flags for these files. Based on the
non-CMake build, none of them were, but the CMake build shows these flags being
applied, even though it is BFB with the non-CMake build.

So (@jgfouca ) is there a "group" name for the files listed above that I can use
(or I can try using a Depends file for these, I guess), and why does the non-CMake build 
and CMake build show different flags for these files? Thanks.

**Comment by amametjanov** [comment]
Maybe PGI is not disabling all -O2 optimizations with `-O2 -O1` sequence.
```
[mame117@compy-e e3sm_scratch]$ pgfortran -O1 -help
Reading rcfile /qfs/projects/ops/rh7/apps/pgi/19.10/linux86-64-llvm/19.10/bin/.pgfortranrc
-O1                 Set opt level. Some scheduling and register allocation is enabled. No global optimizations performed

[mame117@compy-e e3sm_scratch]$ pgfortran -O2 -help
Reading rcfile /qfs/projects/ops/rh7/apps/pgi/19.10/linux86-64-llvm/19.10/bin/.pgfortranrc
-O2                 Set opt level. All -O optimizations plus SIMD code generation
                    == -Mvect=simd
-M[no]vect[=[no]altcode|[no]assoc|cachesize:<c>|[no]fuse|[no]gather|[no]idiom|levels:<n>|nocond|[no]partial|prefetch|[no]short|[no]simd[:{128|256}]|[no]simdresidual|[no]sizelimit[:n]|[no]sse|[no]tile]
                    Control automatic vector pipelining
    [no]altcode     Generate appropriate alternative code for vectorized loops
    [no]assoc       Allow [disallow] reassociation
    cachesize:<c>   Optimize for cache size c
    [no]fuse        Enable [disable] loop fusion
    [no]gather      Enable [disable] vectorization of indirect array references
    [no]idiom       Enable [disable] idiom recognition
    levels:<n>      Maximum nest level of loops to optimize
    nocond          Disable vectorization of loops with conditionals
    [no]partial     Enable [disable] partial loop vectorization via inner loop distribution
    prefetch        Generate prefetch instructions
    [no]short       Enable [disable] short vector operations
    [no]simd[:{128|256}]
                    Generate [don't generate] SIMD instructions
     128            Use 128-bit SIMD instructions
     256            Use 256-bit SIMD instructions
     512            Use 512-bit SIMD instructions
    [no]simdresidual
                    Enable [disable] vectorization of the residual loop of a vectorized loop
    [no]sizelimit[:n]
                    Limit size of vectorized loops
    [no]sse         The [no]sse option is deprecated, use [no]simd instead.
    [no]tile        Enable [disable] loop tiling
```
Would this be BFB: `-O2 -O1 -Mnovect -Mnoassoc -Mnofuse -Mnogather -Mnoidiom -Mlevels:0 -Mnocond -Mnopartial -Mnoshort -Mnosimdresidual -Mnosse -Mnotile` ?

If local string replacement like
```
FFLAGS := $(filter-out -O2, $(FFLAGS))
CFLAGS := $(filter-out -O2, $(CFLAGS))
```
works, this justifies another CIME XML tag like GNU Make's `override`.

**Comment by worleyph** [comment]
Thanks. That is something worth investigating. I'll going to try putting those oddball files I identified above in a Depends file, and see whether it is just a bug in the CMake bldlog output. Your suggestion is more likely, but I can try mine quickly :-).

**Comment by worleyph** [comment]
@amametjanov , my experiment was fruitless; adding -O1 -Mnovect to the list of files above in the Depends files did show up in e3sm.bldlog for both CMake and Non-CMake builds, but did not change anything. I'll investigate your observation. Seems obvious now that you have mentioned it, ... glad I asked since I never thought of it.

**Comment by worleyph** [comment]
I was hoping that -O0 would override all of -O2. I only applied this to CAM, but it did not make it BFB. I'm trying adding 

     -O1 -Mnovect -Mnoassoc -Mnofuse -Mnogather -Mnoidiom -Mlevels:0 -Mnocond -Mnopartial -Mnoshort -Mnosimdresidual -Mnosse -Mnotile

just for CAM, first, to see if this makes any difference. If not, I'll try applying it to all components and libraries.

Note one weird behavior. I first tried

       ifeq ($(COMP_NAME),cam)
         FFLAGS := $(FFLAGS) -O0 -O1 -Mnovect
         CFLAGS := $(CFLAGS) -O0 -O1 -Mnovect
       endif

and the -O0 never showed up. Something in the build system logic eliminated -O0 after seeing it followed immediately by -O1 (@jgfouca ?)

**Comment by worleyph** [comment]
@amametjanov , wrong syntax:

     pgf90-Error-Unknown switch: -Mnoassoc
     pgf90-Error-Unknown switch: -Mnofuse
     pgf90-Error-Unknown switch: -Mnogather
     pgf90-Error-Unknown switch: -Mlevels:0
     pgf90-Error-Unknown switch: -Mnocond
     pgf90-Error-Unknown switch: -Mnopartial
     pgf90-Error-Unknown switch: -Mnoshort
     pgf90-Error-Unknown switch: -Mnosimdresidual
     pgf90-Error-Unknown switch: -Mnosse
     pgf90-Error-Unknown switch: -Mnotile

Reading the man entry above, looks like -Mnovect would disable everything you mentioned.

In any case, not sure now how to "undo" -O2 after setting it, if that in fact is the issue.

I did try the e3sm_remove_flag in the Depends file to try and remove -O2, and it did nothing as far as I can tell (@jgfouca ?)

I'll try

     FFLAGS := $(filter-out -O2, $(FFLAGS))

next.

**Comment by worleyph** [comment]
@amametjanov (and @jgfouca ): That worked! In Macros.make

       ifeq ($(COMP_NAME),cam)
         FFLAGS := $(filter-out -O2, $(FFLAGS))
         FFLAGS := $(FFLAGS) -O1 -Mnovect
         CFLAGS := $(filter-out -O2, $(CFLAGS))
         CFLAGS := $(CFLAGS) -O1 -Mnovect
       endif

and using 

     ./case.build --use-old

the build was BFB between the runtime and build pcols options. So ... how can I do something similar when building with CMake? The above syntax doesn't fit with Macros.cmake.

Thanks, @amametjanov !

**Comment by jgfouca** [comment]
@worleyph 

For cmake:
```
if (COMP_NAME STREQUAL "cam")
  string(REPLACE "-O2" "" FFLAGS "${FFLAGS}")
  set(FFLAGS "${FFLAGS} -O1 -Mnovect")
endif()
```

**Comment by worleyph** [comment]
@jgfouca , Thanks! I'll give it a try, but from the results so far it appears that appending flags does not always override everything that was listed earlier (e.g. -O2 -O1 != -O1, and even -O2 -O0 != -O0), at least for the PGI compiler. Being able to remove flags per file, in the Depends file, will be important then (i.e., issue #3648).

**Comment by worleyph** [comment]
Since this is a compiler issue, and not a build issue, I'll close this issue as soon as I test the above suggestion by @jgfouca , and we can move any further discussion to  #3648  .

Note that I may open another github issue, as there is some asymmetry between CMake and Make that I do not understand (already mentioned above).

**Comment by worleyph** [comment]
string(REPLACE "-O2" "" FFLAGS "${FFLAGS}")

worked fine. Thanks @jgfouca . Closing this issue.
