### ISSUE TITLE
Land in-line interpolation for initial condition (initInterp) broken

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/E3SM#3647]
It appears that the in-line interpolation option for land initial condition is currently broken on master (cff12d21ca4b498d90a54d67adc2f787772a1649).

When I tried using it, I got the following errors:

```
168:  ERROR interpinic set_mindist: Cannot find the closest output ni,no,type= 
168:        16369       26631 gridcell        
168:  ENDRUN:
168:  ERROR in initInterp.F90 at line 815
```

I also tried running another test with the same configuration, but using a previously interpolated file (from a few months ago) and everything worked fine.

Relevant files on compy. Failed test with land interpolation:

`/compyfs/gola749/E3SM_simulations/20200616.v1like.amip.ne30pg2_r05_oECv3.compy/test_1M_15nodes_initInterp
`

Successful test without land interpolation:

`/compyfs/gola749/E3SM_simulations/20200616.v1like.amip.ne30pg2_r05_oECv3.compy/test_1M_15nodes`

E3SM run script:

`/qfs/people/gola749/E3SM/scripts/run.20200616.v1like.amip.ne30pg2_r05_oECv3.compy.csh`

**Comment by bishtgautam** [comment]
I was able to reproduce this error in ICompset and am debugging this issue.

**Comment by golaz** [comment]
@bishtgautam : did you have a chance to look at this issue some more?

**Comment by bishtgautam** [comment]
@golaz I made some progress in identifying that lat/lon value for few cells is garbage. This causes the interpolation to crash. I will look into this further this week.
