### ISSUE TITLE
full performance archiving support for Compy and Anvil missing in Maint versions

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#3659]
In tags V1.2.0-beta, V1.1.1, V1.1.0, and maint-1.0-pf-v3.8, provenance.py is missing any mention of the system Compy, and it still has Anvil listed as using the PBS batch system (and not SLURM). Because of this, certain provenance and system information is not being archived when jobs based on these tags are run. Based on a recent examination of the performance archive on Compy, this is true for over half of the Compy E3SM workload.

**Comment by worleyph** [comment]
This should be a simple update? However, if the way CIME is written has changed at all since these tags and master, I might need help. I also have never tried to update a maintenance tag.

**Comment by worleyph** [comment]
In fact, I'll need guidance as to which tags I should modify in order to get these changes to where they are needed.

**Comment by worleyph** [comment]
@rljacob  and @singhbalwinder , I just tried 

      ./create_newcase --case FC5AV1C-L_ne4_ne4_PRf_fix -res ne4_ne4 -compset FC5AV1C-L -mach compy -compiler intel -project e3sm

using the tarball E3SM-1.1.0.tar.gz, and got

     ERROR: No machine compy found

So, what version(s) should I be trying to update?

**Comment by singhbalwinder** [comment]
I quickly skimmed through most of the tags and (unless I missed something) it looks like v2.0* tags are the only ones which has Compy. I didn't find Compy in any of the v1 tags (I randomly picked a few). Most likely, developers have their own versions in which they ported Compy's machine files and never pushed it back to update respective tags.

**Comment by worleyph** [comment]
Thanks. @rljacob and @sarats  , should I just give up on this? I'm willing to try to update provenance.py (though this differs between v1.2.0-beta, v1.1.0, and v1.0.0) and add syslog.compy, but am not up to adding compy from scratch. If someone wants to add compy to v1.2.0-beta, I'll hep with provenance.py, but even this won't solve the underlying problem, that people are running with their own ports.

I'll instead focus on updating the scripts to workaround the missing information.

**Comment by amametjanov** [comment]
If this is for `maint` branches (`syslog.compy` is missing on them), updates can be done same as for `master`, except starting a branch from `maint-1.0`, `maint-1.1` or `maint-1.2`: e.g.
```
$ git checkout maint-1.0
$ git checkout -b <name-of-new-branch>
```
tarballs are probably out-of-date.

**Comment by worleyph** [comment]
My mistake then ... I tried the tags v1.0.0, v1.1.0, and v1.2.0-beta. I'll try the maint tags.

**Comment by rljacob** [comment]
Yes update the head of the maint branches, not the tags.

**Comment by singhbalwinder** [comment]
Sorry, @rljacob and @amametjanov are right, you should checkout the branch like @amametjanov suggested.

**Comment by worleyph** [comment]
% git checkout maint-1.2

     error: The following untracked working tree files would be overwritten by checkout:
	     components/cam/src/physics/rrtmgp/external/README.md
	     components/cam/src/physics/rrtmgp/external/build/Makefile
	     components/cam/src/physics/rrtmgp/external/build/Makefile.conf.gfortran
	     components/cam/src/physics/rrtmgp/external/build/Makefile.conf.ifort
	     components/cam/src/physics/rrtmgp/external/build/Makefile.conf.nagfor
	     components/cam/src/physics/rrtmgp/external/build/Makefile.conf.pgfortran
	     components/cam/src/physics/rrtmgp/external/examples/mo_load_coefficients.F90
	     components/cam/src/physics/rrtmgp/external/examples/mo_simple_netcdf.F90
	     components/cam/src/physics/rrtmgp/external/examples/rfmip-clear-sky/Makefile
	     components/cam/src/physics/rrtmgp/external/examples/rfmip-clear-sky/Readme.md
	     components/cam/src/physics/rrtmgp/external/examples/rfmip-clear-sky/mo_rfmip_io.F90
	     components/cam/src/physics/rrtmgp/external/examples/rfmip-clear-sky/rrtmgp_rfmip_lw.F90
	     components/cam/src/physics/rrtmgp/external/examples/rfmip-clear-sky/rrtmgp_rfmip_sw.F90
	     components/cam/src/physics/rrtmgp/external/extensions/mo_fluxes_byband.F90
	     components/cam/src/physics/rrtmgp/external/extensions/mo_fluxes_byband_kernels.F90
	     components/cam/src/physics/rrtmgp/external/extensions/mo_fluxes_bygpoint.F90
	     components/cam/src/physics/rrtmgp/external/extensions/mo_heating_rates.F90
	     components/cam/src/physics/rrtmgp/external/extensions/mo_rrtmgp_clr_all_sky.F90
	     components/cam/src/physics/rrtmgp/external/rrtmgp/Make.depends
	     components/cam/src/physics/rrtmgp/external/rrtmgp/kernels/mo_gas_optics_kernels.F90
	     components/cam/src/physics/rrtmgp/external/rrtmgp/mo_gas_concentrations.F90
	     components/cam/src/physics/rrtmgp/external/rrtmgp/mo_gas_optics.F90
	     components/cam/src/physics/rrtmgp/external/rrtmgp/mo_rrtmgp_constants.F90
	     components/cam/src/physics/rrtmgp/external/rte/Make.depends
	     components/cam/src/physics/rrtmgp/external/rte/kernels/mo_fluxes_broadband_kernels.F90
	     components/cam/src/physics/rrtmgp/external/rte/kernels/mo_optical_props_kernels.F90
	     components/cam/src/physics/rrtmgp/external/rte/kernels/mo_rte_solver_kernels.F90
	     components/cam/src/physics/rrtmgp/external/rte/mo_fluxes.F90
	     components/cam/src/physics/rrtmgp/external/rte/mo_optical_props.F90
	     components/cam/src/physics/rrtmgp/external/rte/mo_rte_kind.F90
	     components/cam/src/physics/rrtmgp/external/rte/mo_rte_lw.F90
	     components/cam/src/physics/rrtmgp/external/rte/mo_rte_sw.F90
	     components/cam/src/physics/rrtmgp/external/rte/mo_source_functions.F90
     Please move or remove them before you switch branches.
     Aborting

???

However,

     % git checkout maint-1.0

appeared to have worked.

**Comment by singhbalwinder** [comment]
I guess you will have to remove `components/cam/src/physics/rrtmgp/external` manually before checking out `maint-1.2`

**Comment by worleyph** [comment]
Thanks. That worked. Guess that people working with maint-1.2 don't care about this?

**Comment by worleyph** [comment]
Just tried 

     ./create_newcase --case FC5AV1C-L_ne4_ne4_PRf_fix -res ne4_ne4 -compset FC5AV1C-L -mach compy -compiler intel -project e3sm

using maint-1.2. Same result:

     ERROR: No machine compy found

So, still no support for Compy in the maintenance branches (at least not in maint-1.2 - I did not try 1.1 or 1.0 - any reason to do so?)

**Comment by singhbalwinder** [comment]
I think both 1.1 and 1.0 should have Compy machine files.

**Comment by worleyph** [comment]
Thank you. Both 1.1 and 1.0 accepted the '-mach compy' in ./create_newacse. 

Just curious, why would maint-1.2 not be based on maint-1.1 as a starting point? Or, at least, be updated as updates are made to 1.1 to add, for example, support for Compy?

**Comment by singhbalwinder** [comment]
I haven't checked but Compy might be added to maint-1.1 after maint-1.2 branched off from maint-1.1. I don't know who is maintaining maint-1.2 but changes like machine file are need based changes. Maybe maint-1.2 developers never needed to run on Compy or they decided not to push their Compy machine files related changes back to the branch.

**Comment by rljacob** [comment]
All the maint-1.x branches are from master.  They all started before compy existed so compy has to be added to each one.

**Comment by worleyph** [comment]
I've created two branches:

     worleyph/maint-1.0/update_provenance_capture
     worleyph/maint-1.1/update_provenance_capture

and tested these on Compy. I'll test them on Anvil next. Assuming everything goes smoothly, what is the process for submitting a PR for maint-1.0 and maint-1.1. (If this is documented on a Confluence page, please just point me at it.) Also, who should I put down as reviewers and as integrator?

**Comment by worleyph** [comment]
Note that maint-1.1 isn't really supported on Anvil?

     ./create_newcase --case FC5AV1C-L_ne4_ne4_m1.1 -res ne4_ne4 -compset FC5AV1C-L -mach anvil -compiler intel -project condo

     ...
     Using project from config_machines.xml: ACME
     e3sm model version found: 074fd76
     Batch_system_type is pbs
     job is case.run USER_REQUESTED_WALLTIME None USER_REQUESTED_QUEUE None
     ERROR: No queues found

create_newcase does work for maint-1.0, but it also has

     Using project from config_machines.xml: ACME

which current master does not. Looks like it used the condo though, and my test job is running with performance data going into the performance archive.

**Comment by worleyph** [comment]
Tests passed for maint-1.0 on Anvil, so think that this is ready to submit as a PR. Advice on how to proceed would be appreciated.

**Comment by rljacob** [comment]
You do it like any other PR but choose "maint-1.0" as the "base".

**Comment by amametjanov** [comment]
This should now be fixed on Compy and Anvil for all 3 maint branches.
