### ISSUE TITLE
Scorpio 70x slower writing clm2.r at r0125 resolution

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#3706]
Land grid at r0125 (1/8 degree) resolution is being used in tri-grid configurations for NorthAmerica RRM, Antarctica RRM and multiple globally uniform high resolution grids (e.g., ne120pg2 thru ne1024pg2). It has been report writing restart file clm2.r is very slow with Scorpio (PIO_VERSION=2), and slower compared to using Scorpio classic (PIO_VERSION=1). 

The problem can be reproduced using an I-Case configuration. In an I-case simulation in preparing ICs for ne120pg2 as well as ne1024pg2, it is found that, over 6 restart writing intervals, writing clm2.r consistently took 6-7 minutes with Scorpio (PIO_VERSION=2), while just 3 to 5 seconds with Scorpio classic (PIO_VERSION=1), a difference of at least 70x. These numbers are based on tests that were completed on cori-knl less than 1 hour apart and with some overlapping (i.e., very comparable machine environment).  A 128-node pe-layout was used.

The  I-case can be created using  compset=ICRUCLM45,  grid=r0125_r0125_oRRS18to6v3.

**Comment by wlin7** [comment]
FYI: The pair of I-case simulations can be found under

/global/homes/w/wlin/gscrc/e3sm_scratch/cori-knl/20200703.ICRUCLM45.r0125_oRRS18to6v3/run and
/global/homes/w/wlin/gscrc/e3sm_scratch/cori-knl/20200703.ICRUCLM45.r0125_oRRS18to6v3.PIO1/run

**Comment by dqwu** [comment]
@wlin7 
Did you use a script to run this case on Cori or run it manually? To reproduce this issue, we need the same xml settings and user namelist files.

**Comment by wlin7** [comment]
Hi @dqwu ,

The following script is used for  run
~wlin/ACME/Cases/SCREAM/scripts/setup.20200703.ICRUCLM45-r0125-oRRS18to6v3.PIO1.csh

The run with PIO2 used essentially the same script (only diff in resetting PIO_VERSION and finidat)
~wlin/ACME/Cases/SCREAM/scripts/setup.20200703.ICRUCLM45-r0125-oRRS18to6v3.csh

Note that the time numbers reported above are based on the difference on time stamps for clm2.rh0 and clm2.r. of the same check points. To reproduce, you may change REST_OPTION to ndays or shorter for a quicker turnaround.

The pe-layout used is 
~wlin/ACME/Cases/SCREAM/cori-knl/20200703.ICRUCLM45.r0125_oRRS18to6v3/env_mach_pes.xml

**Comment by dqwu** [comment]
@wlin7 @jayeshkrishna 
It seems that your run directory is using the default lustre file system settings:
```
lfs getstripe /global/homes/w/wlin/gscrc/e3sm_scratch/cori-knl/20200703.ICRUCLM45.r0125_oRRS18to6v3.PIO1/run -d
stripe_count:  1 stripe_size:   1048576 pattern:       0 stripe_offset: -1
```
The default stripe count on Cori is 1 (default stripe size is 1M) and using this count could be very slow for scorpio (scorpio classic sets it to 16).

Could you please rerun the case with a higher stripe count like 128? You can manually set the new stripe count after case.setup is called:
lfs setstripe -S 1m -c 248 \`./xmlquery -value RUNDIR\`

FYI, a script that runs scream ne1024 F case on Cori sets the stripe count to 248 (maximum OST) and sets the stripe size to 2M.
```
    # Finally, run setup
    ./case.setup

    # Link to run directory
    ln -s `./xmlquery -value RUNDIR` run

    # Set file striping on run dir for writing large files
    ls -l run
    lfs setstripe -S 2m -c 248 run
```

**Comment by jayeshkrishna** [comment]
@dqwu do you need the link (ln -s) for the run directory (although it makes it easier to specify the steps above)? @wlin7 can directly set it for the run directory, right?

**Comment by dqwu** [comment]
That link is added by scream developers and not required. The following command should work as well after case.setup:
lfs setstripe -S 1m -c 128 \`./xmlquery -value RUNDIR\`

A hard-coded path is also OK.
lfs setstripe -S 1m -c 128 path_to_run_dir

**Comment by tangq** [comment]
Pinning @ndkeen as Noel found similar land restart writing slowness issue with the NA RRM.

**Comment by wlin7** [comment]
Thanks @dqwu on setting stripe for rundir. I am rerunning it. Please note that @ndkeen likely has reset the value and still seeing slow performance.

**Comment by wlin7** [comment]
@dqwu , much better now, the time stamp difference between clm.rh0 and clm2.r are now consistently under 30 seconds.
Still larger than with PIO1. For a fair comparison, I am going to rerun the one with PIO1 also with daily restart, Previous run has  monthly restart; the content of clm2.rh0 is different.

**Comment by wlin7** [comment]
On daily writing interval, with PIO2, writing of clm2.rh0 also takes about 30 seconds Writing of clm2.r begins at about the same time as clm2.rh0, so the total writing time for clm2.r is close to 1 minute with PIO2 and stripe count=128.

**Comment by wlin7** [comment]
Good news, Scorpio (PIO2) 2x faster writing clm2.r at r0125 resolution when the settings are appropriate. 

For the run with PIO1 and  writing daily restart files, (now IO amount and frequency identical to the PIO2 run), it took slightly over 2 minutes writing clm2.r. Another surprising fact, with PIO1, it took about same time in writing clm2.rh0 and clm2.r, with clm2.rh0 about 1/4 of the size.  With PIO2, it took under a minute (52 seconds) for clm2.r and about half of that for clm2.rh0.

What a turn! This issue can be closed now. Many thanks to @dqwu and @jayeshkrishna  for the very quick input.

**Comment by golaz** [comment]
I assume we don't expect average users to manually set the stripe themselves for every run? Maybe we should wait for https://github.com/E3SM-Project/scorpio/issues/317 until this is really considered solved?
