### ISSUE TITLE
PEM tests with ISMF fail

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#3719]
After #3695 was merged, PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_intel.JMasterExtra_coverage was observed to FAIL. I did some extra testing, and it appears that the problem is with ISMF. Here is the status of testing:

* PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_intel  FAIL
* PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-IAF.compy_intel  PASS
* PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF.compy_intel  PASS
* PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.compy_intel  FAIL

So the issue appears to have something to do with ISMF

**Comment by rljacob** [comment]
What is ISMF?

**Comment by jonbob** [comment]
ice sheet melt fluxes

**Comment by mark-petersen** [comment]
@jonbob I'm repeating these tests before and after the merge. Did you notice if this is fail to run or fail to compare? Please send paths if they are still on disk.

**Comment by jonbob** [comment]
It's a fail-to-compare, meaning the PEM test itself fails. It runs OK, just gets different answers

**Comment by jonbob** [comment]
I didn't save any of my tests for that, especially since it turned up in automated testing

**Comment by jonbob** [comment]
I did some more testing and it appears this issue started when the PR that turned redi on (#3682](https://github.com/E3SM-Project/E3SM/pull/3682)) was merged. I think because this test is in an extra coverage suite and doesn't run as often (and on compy which has had testing problems), we didn't catch it as quickly. Anyway, I checked out a version of master between 3682 and 3695 and this test failed. If I turned redi off, it passed -- so the issue has something to do with redi and ismf.

**Comment by jonbob** [comment]
@mark-petersen , @vanroekel - why don't we track progress on this confluence page, to avoid duplication of effort?

**Comment by vanroekel** [comment]
thanks for the update @jonbob On my end I've poked at this a little and tried running the latest master with redi on I confirm what @jonbob found, but interestingly with redi off I get a state validation failure in the ocean instead of a fail to compare.  I've been running this test

PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel

**Comment by vanroekel** [comment]
further update -- the failure seems to only occur with redi off and gm_closure = 'visbeck'

**Comment by jonbob** [comment]
My tests using master from this morning just passed?

PASS PEM_P480_Ld5_D.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel COMPARE_base_modpes
PASS PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.anvil_intel COMPARE_base_modpes

Now I'm confused...

**Comment by vanroekel** [comment]
Very weird, did you have a chance to run with redi off to confirm my result?

**Comment by jonbob** [comment]
Yes, I just turned redi off and it failed to run with state validation in the ocean

**Comment by jonbob** [comment]
I'm trying with current master on compy as well

**Comment by vanroekel** [comment]
Thanks @jonbob glad to know my testing was correct.

**Comment by jonbob** [comment]
Also passed one compy:

PASS PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-IAF-ISMF.compy_intel COMPARE_base_modpes

**Comment by jonbob** [comment]
But on compy it also fails with redi off

**Comment by vanroekel** [comment]
update so far.  The following configurations pass

1. constant GM + contant Redi
2. constant GM + no redi
3. no GM + no redi

these fail
1. Visbeck + no redi
2. old 3DGM (N2_dependent) + no redi -- fails later than (1)

**Comment by jonbob** [comment]
One more update -- apparently it has nothing to do with ISMF. This failed in the run with redi off:

PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-IAF.anvil_intel

But it passes for T62_oEC60to30v3.GMPAS-IAF.anvil_intel so something with mixed layers underneath ice shelves?

**Comment by vanroekel** [comment]
@jonbob I agree.  It definitely has to do with the indMLD array.  When I revert the 3DGM from cryo back to the original the test passes.  I'm testing a fix for visbeck now.

**Comment by vanroekel** [comment]
@jonbob and @mark-petersen I think I have this fixed now.  I'm running one more test and will post a MPAS-PR soon.  However, this will require some discussion and further testing before integration.  Solving this issue required fairly substantial changes to the visbeck integration and to the Redi N2 limiter.

**Comment by vanroekel** [comment]
another update, In testing this further, there is still something wrong.  Here is a summary (all have redi off)

1. Constant GM + contant phase speed = runs fine
2. Constant GM + variable phase speed = runs fine
3. old 3DGM + variable phase speed = runs fine
4. visbeck GM + constant phase speed = runs fine
5. visbeck GM + variable phase speed = **run fails**

**Comment by mark-petersen** [comment]
@vanroekel Is that last line still true?
5. visbeck GM + variable phase speed = run fails

**Comment by vanroekel** [comment]
No sorry for not updating.  All tests pass now with my changes in https://github.com/MPAS-Dev/MPAS-Model/pull/643
