### ISSUE TITLE
cannot checkout maint-1.0 branch due to untracked cime files

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/E3SM#3721]
I tried to checkout the latest maint-1.0 branch, but failed with errors below (a long list of cime files).

```
git checkout --track origin/maint-1.0
error: The following untracked working tree files would be overwritten by checkout:
        cime/.github/PULL_REQUEST_TEMPLATE
        cime/.gitignore
        cime/.nojekyll
        cime/.travis.yml
        cime/CMakeLists.txt
```

**Comment by rljacob** [comment]
Are you going from latest master to maint-1.0?   First do:
git submodule deinit cime

**Comment by tangq** [comment]
Yes, I used the latest master. It works after `git submodule deinit cime`.

Shall we add it to the documentation somewhere?

This issue also breaks the e3sm run script when specifying to use the maint-1.0 branch.

**Comment by rljacob** [comment]
I'm adding some notes on the page about switching to submodule: https://acme-climate.atlassian.net/wiki/spaces/EIDMG/pages/1184497694/Convert+CIME+in+E3SM+to+a+submodule.
