### ISSUE TITLE
maint-1.0 fails to build

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/E3SM#3722]
The latest maint-1.0 branch (v1.0.0-236-g849d9ee1a) fails to build on cori.

`ERROR: BUILD FAIL: mpaso.buildlib failed`

The build directory is at /global/cscratch1/sd/tang30/E3SM_simulations/20200720.QBO-MJO_H1.ne30_oEC.cori-knl/build

**Comment by ndkeen** [comment]
I suspect this is not specific to cori-knl. 

And, I can do the following:
```
git clone -b maint-1.0 git@github.com:E3SM-Project/E3SM maint13-jul20
cd maint13-jul20
git submodule update --recursive --init

cd cime/scripts
create_test SMS_D.ne30_oECv3_ICG.A_WCYCL1850S
```

It smells like what I went thru here: https://github.com/E3SM-Project/E3SM/issues/3528

**Comment by tangq** [comment]
It is the same as #3528 .

I can build the coupled case after NOT do `git submodule update --recursive --init` before checking out the maint-1.0 branch.

However, this solution is not ideal because people normally perform `git submodule update --recursive --init` immediately after  cloning the code following the documentation (https://acme-climate.atlassian.net/wiki/spaces/ED/pages/1868455/Development+Getting+Started+Guide)

Is there a better fix?

**Comment by rljacob** [comment]
Is this only on cori?  Seems like it should happen anywhere from what you are describing.

**Comment by tangq** [comment]
I reproduced the error on compy, so this is not specific to cori. I edited the title.

**Comment by ndkeen** [comment]
I think this is now an old issue and can be closed.

**Comment by ndkeen** [comment]
Closing old issue
