### ISSUE TITLE
F case on Compy using PGI compiler is not BFB wrt change in PE layout

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#3739]
An F case 

     -res ne4pg2_ne4pg2 -compset FC5AV1C-L -mach compy -compiler pgi

is not not BFB with respect to changes in PE layout (64x1 vs. 96x1) with the current optimization flags. 

Experiments indicate that this can be resolved (for this case and experimental setup, at least) by setting the non-DEBUG flags for the whole model to -O1, in both Macros.cmake:

       if("${DEBUG}" STREQUAL "FALSE")
         set(FFLAGS "${FFLAGS}  -O1")
         set(CFLAGS "${CFLAGS}  -O1")
       endif()

and Macros.make:

       ifeq ($(DEBUG),FALSE)
         FFLAGS := $(FFLAGS)  -O1
         CFLAGS := $(CFLAGS)  -O1
      endif

Moreover, the '-O2' performance can be recovered without losing BFB by adding '-O2' back in for the 'cam' component only, i.e.. for Macros.cmake:

      if("${COMP_NAME}" STREQUAL "cam")
        set(FFLAGS "${FFLAGS} -O2 -Mnovect")
      endif()

and for Macros.make:

       ifeq ($(COMP_NAME),cam)
         FFLAGS := $(FFLAGS) -O2 -Mnovect
       endif

Further investigations may be able to identify which non-CAM files require -O1 for BFB behavior (in LND? CPL? driver?), but the above may be sufficient in the meantime, as it is performant while recovering BFB. Similar epxeriments may be required to identify what compiler flags work for the other active components (OCN, ICE, ...)  in a fully coupled model run.

(@jgfouca , if the problem is found in the driver or share code, is this a CMAKE buld or non-CMAKE? If non-CMAKE, is there something equivalent to e3sm_remove_flags that works in a non-CMAKE Depends file?)

**Comment by amametjanov** [comment]
Since `PEM_Ln5.ne4_ne4.FC5AV1C-L.compy_pgi` (which is 96x1 vs 48x1) is passing in nightly tests, this appears to be `pg2`-specific?

Ran a few tests with latest master. These are BFB:
  PEM_D.ne4_ne4.FC5AV1C-L
  PEM_D.ne4pg2_ne4pg2.FC5AV1C-L
  PEM.ne4_ne4.FC5AV1C-L
  SMS_P64_D.ne4_ne4.FC5AV1C-L vs SMS_P96_D.ne4_ne4.FC5AV1C-L
  SMS_P64_D.ne4pg2_ne4pg2.FC5AV1C-L vs SMS_P96_D.ne4pg2_ne4pg2.FC5AV1C-L
  SMS_P64.ne4_ne4.FC5AV1C-L vs SMS_P96.ne4_ne4.FC5AV1C-L
  SMS_P64x2.ne4_ne4.FC5AV1C-L vs SMS_P96x2.ne4_ne4.FC5AV1C-L
  SMS_P64x2.ne4pg2_ne4pg2.FC5AV1C-L vs SMS_P96x2.ne4pg2_ne4pg2.FC5AV1C-L

These are not-BFB:
  PEM.ne4pg2_ne4pg2.FC5AV1C-L
  SMS_P64.ne4pg2_ne4pg2.FC5AV1C-L vs SMS_P96.ne4pg2_ne4pg2.FC5AV1C-L

So pg2 + pureMPI: either 96x1 vs 48x1 or 96x1 vs 64x1. Any thoughts from pg2 folks?

**Comment by whannah1** [comment]
We saw something similar with the MMF, which seemed to be related to pg2, but I think we confirmed that it was really just a coincidence that the change in columns per task for our np4 ERP test just happened to avoid the cause of the failure. That ERP failure is likely not related to this, but I think it would be good to try a range of ATM_NTASKS to see if it really is isolated to  pg2 (I suspect it can't be a physgrid thing).

**Comment by whannah1** [comment]
@worleyph it might be worth redoing a test with the aquaplanet compset. If that passes then I wonder if the land model is the culprit.

**Comment by worleyph** [comment]
If so, then weird that -O2 in compiling CAM wouldn't trigger it.

**Comment by worleyph** [comment]
@whannah1 , remind me how to run with aquaplanet. I can also add -O2 to LND and see if this causes the problem.

**Comment by whannah1** [comment]
@worleyph just use compset "F-EAMv1-AQP1"

**Comment by jgfouca** [comment]
@worleyph , sharedlibs (includes mct) are not built with cmake. This is an example of how the makefile system de-optimized a file (it uses cam files as an example even though cam is no longer build with Make):
```
ifeq ($(MODEL),cam)
  # These RRTMG files take an extraordinarily long time to compile with optimization.                                                                                                                                                              
  # Until mods are made to read the data from files, just remove optimization from                                                                                                                                                                 
  # their compilation.                                                                                                                                                                                                                             
  rrtmg_lw_k_g.o: rrtmg_lw_k_g.f90
        $(FC) -c $(FPPFLAGS) $(INCLDIR) $(INCS) $(FREEFLAGS) $(FFLAGS) $(FFLAGS_NOOPT) $<

  rrtmg_sw_k_g.o: rrtmg_sw_k_g.f90
        $(FC) -c $(FPPFLAGS) $(INCLDIR) $(INCS) $(FREEFLAGS) $(FFLAGS) $(FFLAGS_NOOPT) $<
```

**Comment by worleyph** [comment]
@jgfouca , thanks!

**Comment by worleyph** [comment]
@whannah1 , the comparable aquaplanet cases are BFB.

**Comment by worleyph** [comment]
Even though aquaplanet is BFB, the issue does not appear to be with the land: I tried compiling clm with -O2 , cam with -O2, and everything else -O1, and it was still BFB.

**Comment by worleyph** [comment]
Was able to reproduce the non BFB behavior by compiling CICE with -O2 . (Was not able to reproduce it compiling CAM, CPL, or CLM with -O2).

Note that I tried running ne4 and with phys_chnk_fdim set to 4, so same pcols for ne4 as get (naturally) with ne4pg2, and this was fine, so do not know why only the pg2 case is sensitive to this.

**Comment by worleyph** [comment]
@amametjanov , @whannah1 , problem went away if add -Mnovect to CICE when compiling, i.e.

       if("${COMP_NAME}" STREQUAL "cice")
         set(FFLAGS "${FFLAGS} -Mnovect")
       endif()

in Macros.cmake .
