### ISSUE TITLE
remove land code for non nitrification/denitrification?

### ISSUE THREAD

**Issue by rgknox** [E3SM-Project/E3SM#3745]
The soil BGC allocation code has different sections that simulation N dynamics when you have nitrification/de-nitrification (N/DN) and when you don't.   It seems that everyone I talk to says that no-one runs without N/DN.

Can we remove code that does **not** have N/DN?   I ask this because the allocation code is long and cumbersome, and being able to remove* a portion of this code would make it much more readable and understandable.

*Note: If we get a quorum and decide removing this stuff would be good, I also would ask that we don't move on this immediately. I have a PR on the horizon that has lots of changes to allocation and would have massive conflicts.

@jinyuntang @qzhu-lbl @wjriley @thorntonpe @dmricciuto @bsulman @xyk-ornl

**Comment by xyk-ornl** [comment]
@rgknox I agree it is time for us to remove the part of code that does not use N/DN for the reasons you mentioned. Thanks

**Comment by bbye** [comment]
@rgknox I know you didn't ping me, but from the crop model standpoint, it would be fine with me. The crop model runs with N/DN. I just need to update the crop test because for some reason N/DN is off by default.

**Comment by rgknox** [comment]
Thanks @bbye, good to know.  I suppose if the non N/DN code is removed, we would remove the namelist variable as well, which would force us to remove that setting from all test definitions.

**Comment by rgknox** [comment]
I'm working on this now, as I would like to have these changes in place before I finalize CNP-FATES.  My plan:

1) keep the use_nitrif_denitrif namelist parameter
2) remove all code for when use_nitrif_denitrif = false
3) add code in NitrifDenitrifMod, where, if use_nitrif_denitrif = False, the potential nitrification rate is set to 0.

The new code will just use the algorithms for using the nitrification and denitrification, just no nitrate will be ever be generated.  I like this method because it a) allows us to not have to change all of the build and namelist control code which should help make verifying these changes a little easier

If we want to completely remove the namelist parameter, that could be done in a separate PR

Thoughts?

@xyk-ornl @bbye @qzhu-lbl @bsulman @jinyuntang @dmricciuto @ckoven @wjriley @thorntonpe

**Comment by bishtgautam** [comment]
@rgknox This is a great idea and thanks for volunteering to clean up the code by deleting unused code. Go for it.

Reading through previous comments, @bbye is the current crop test using N/DN? If not, we should update the test to make sure this code cleanup doesn't break the crop model.

**Comment by bbye** [comment]
@bishtgautam The current crop test does not have N/DN turned on, but it should be turned on. It's not explicitly set as far as I can tell. Will these code mods set N/DN to true by default?

**Comment by rgknox** [comment]
@bbye, would you like to have a crop test for each with and without N/DN?

As for the staging of these changes, I could add the crop N/DN test, and then generate a baseline.  Then modify the code and make sure the crop N/DN test is b4b.  

The only thing, is that with my current plan, there will no longer be a true no N/DN test, so we won't be able to test that old crop test with no N/DN is not bit for bit.

**Comment by bbye** [comment]
Actually, there is no need for a crop test without N/DN. Your suggested staging of the change would work to ensure the test is b4b, and then you can remove the old test with N/DN turned 'off'.

**Comment by bsulman** [comment]
This sounds great to me! I'm all in favor of simplifying the code where possible.

**Comment by rgknox** [comment]
this issue has been resolved, closing
