### ISSUE TITLE
Domain incompatability with new ECwISC30to60E1r2 grid

### ISSUE THREAD

**Issue by darincomeau** [E3SM-Project/E3SM#3797]
In the process of trying to create a PR to bring a new grid into E3SM, I am getting the following error in the e3sm.log that kills the job during initialization:

```
105:  (seq_domain_check_grid) ERROR: incompatible domain grid coordinates
105:  ERROR: (seq_domain_check_grid)  incompatible domain grid coordinates
247:  (seq_domain_check_grid) ERROR: incompatible domain grid coordinates
```

The branch that I'm trying to create the PR from is here:
https://github.com/E3SM-Project/E3SM/tree/darincomeau/add_ECwISC30to60E1r2_grid

This grid had previously worked off an earlier branch off master around May 29, but with hard-coded paths for the grid, mapping, and domain files:
https://github.com/E3SM-Project/E3SM/tree/darincomeau/ECwISC30to60E1r2-clubbv2

I believe I've narrowed down the PR into master which causes the error with the new grid to appear, which is #3597 . When I cherry-pick my add_ECwISC30to60E1r2_grid branch onto the previous commit into master, #3713 , a case with the new grid builds and runs; cherry-picking this branch onto the next PR into master, #3597 , it then fails with the domain incompatibility error. The associated MPAS-Model PR is https://github.com/MPAS-Dev/MPAS-Model/pull/457

@mark-petersen , @mattdturner , do you have any thoughts on why this would happen? It's something about component coupling, so I think it's an E3SM issue, not an MPAS-Model issue. I can post more of the error message if its useful.

Tagging @jonbob as he's helped look into the issue and has also seen this behavior.

**Comment by mark-petersen** [comment]
@darincomeau thanks for the details here. Looking in the code, that error message is produced here:
```
git grep -in --recurse-submodules 'incompatible domain grid coordinates'
cime/src/drivers/mct/main/seq_domain_mct.F90:691:
        write(logunit,*) trim(subname)," ERROR: incompatible domain grid coordinates"
```
and is a check on the domain or mapping file coefficients, like this (for example)
```
cime/src/drivers/mct/main/seq_domain_mct.F90:362:
       call seq_domain_check_grid(ocndom_o%data, icedom_o%data,'lat' , eps=eps_oigrid, mpicom=mpicom_cplid, mask=mask)
```
There are tons of these calls, all for different variables. Is there a traceback that shows which variable this is for? I'm trying to understand how that performance PR could possibly alter a domain file check.

**Comment by darincomeau** [comment]
Thanks @mark-petersen . I don't see anything in any of the component logs that helps, but the end of the cpl.log is this:
```
(seq_mct_drv) : Performing domain checking
(seq_domain_check)  --- checking land maskfrac ---
(seq_domain_check)  --- checking ocean maskfrac ---
(seq_domain_check)  --- checking ice maskfrac ---
(seq_domain_check)  --- checking ocn/ice domains ---
(seq_domain_check_grid)  the domain size is =         1120
(seq_domain_check_grid)  maximum           difference for mask   1.00000000000000
(seq_domain_check_grid)  maximum allowable difference for mask  0.100000000000000
(seq_domain_check_grid)  the domain size is =         1120
```

The traceback in the e3sm.log isn't telling me much, but here it is:

```
694: MOSART decomp info proc =        54 begr =    249945 endr =    254572 numr =      4628
667: MOSART decomp info proc =        27 begr =    124984 endr =    129612 numr =      4629
695: MOSART decomp info proc =        55 begr =    254573 endr =    259200 numr =      4628
  0: MCT::m_Router::initp_: GSMap indices not increasing...Will correct
  0: MCT::m_Router::initp_: RGSMap indices not increasing...Will correct
  0: MCT::m_Router::initp_: RGSMap indices not increasing...Will correct
  0: MCT::m_Router::initp_: GSMap indices not increasing...Will correct
247: seq_domain_check_grid - n:198 d1:    1.000000 d2:    0.000000 diff:  1.00000000000000 eps:  0.10000000000000
105: seq_domain_check_grid - n:250 d1:    1.000000 d2:    0.000000 diff:  1.00000000000000 eps:  0.10000000000000
599: seq_domain_check_grid - n:106 d1:    1.000000 d2:    0.000000 diff:  1.00000000000000 eps:  0.10000000000000
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
105:  (seq_domain_check_grid) ERROR: incompatible domain grid coordinates
105:  ERROR: (seq_domain_check_grid)  incompatible domain grid coordinates
247:  (seq_domain_check_grid) ERROR: incompatible domain grid coordinates
105: Image              PC                Routine            Line        Source
105: e3sm.exe           000000000414948B  Unknown               Unknown  Unknown
105: e3sm.exe           0000000002DF2132  shr_abort_mod_mp_         114  shr_abort_mod.F90
105: e3sm.exe           000000000049C733  seq_domain_mct_mp         693  seq_domain_mct.F90
105: e3sm.exe           000000000049A7A9  seq_domain_mct_mp         358  seq_domain_mct.F90
105: e3sm.exe           000000000042D6BF  cime_comp_mod_mp_        1910  cime_comp_mod.F90
105: e3sm.exe           0000000000434EF9  MAIN__                    122  cime_driver.F90
105: e3sm.exe           000000000041632E  Unknown               Unknown  Unknown
105: libc-2.17.so       00002B22922313D5  __libc_start_main     Unknown  Unknown
105: e3sm.exe           0000000000416229  Unknown               Unknown  Unknown
```

**Comment by mark-petersen** [comment]
Can you send the path?

**Comment by darincomeau** [comment]
```
/lcrc/group/acme/ac.dcomeau/acme_scratch/anvil/20200826.A_WCYCL1850-DIB-ISMF_CMIP6.ne30_ECwISC30to60E1r2.0811b.anvil/run
```

**Comment by jonbob** [comment]
@mark-petersen - the error is coming during the call checking the mask. The only thing I can imagine is that somehow the MPAS PR touched the part of the code that sets frac or mask during the component init?

**Comment by darincomeau** [comment]
Just to clarify my testing:

git checkout b70c5c6e08b4191615b3df9245f6bbb275cbe1b1
git cherry-pick 20ca34e (I only cherry-picked the first commit to avoid JRA conflicts; T62 doesn't work with this because of a bad path that's fixed in that branch's third commit)
A_WCYCL1850-DIB-ISMF_CMIP6.ne30_ECwISC30to60E1r2 runs

git checkout c2f9cfba33fff1f6dcdda4930beff22723575617
git cherry-pick 20ca34e
A_WCYCL1850-DIB-ISMF_CMIP6.ne30_ECwISC30to60E1r2 fails with that error.

I was also surprised/stumped when that PR seems to be the breaking point.

**Comment by jonbob** [comment]
I can confirm that it doesn't impact oEC60to30v3wLI -- a SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_intel ran fine with a codebase that cherry-picked Darin's commits into master

**Comment by jonbob** [comment]
I did look, and I think both ocn and ice rely on code like this in their drivers to set the mask and frac:
````
    ! Build mask and frac based on landIceMask
    block_ptr => domain % blocklist
    do while ( associated(block_ptr) )
       call mpas_pool_get_subpool(block_ptr % structs, 'mesh', meshPool)
       call mpas_pool_get_subpool(block_ptr % structs, 'ocean_coupling',oceanCouplingPool)

       call mpas_pool_get_dimension(meshPool, 'nCellsSolve', nCellsSolve)

       call mpas_pool_get_array(oceanCouplingPool, 'landIceMask',landIceMask)

       if ( associated(landIceMask) ) then
          do i = 1, nCellsSolve
             if ( landIceMask(i) == 1 ) then
                data(i) = 0.0_RKIND
             else
                data(i) = 1.0_RKIND
             end if
          end do
       else
          do i = 1, nCellsSolve
             data(i) = 1.0_RKIND
          end do
       end if
````
I also checked and from the streams files, both ocn and ice sources for the landIceMask have identical values -- in fact, we use ncks to grab the ocean data and copy it into the ice file

**Comment by jonbob** [comment]
I commented out the line in mct that compares the mask between ocn and ice, and otherwise the ice/ocean grid consistency check passes and allows the code to successfully complete a five-day smoke test. That's not an acceptable way to run, but it does point to the issue being with the landIceMask in the ocean.

**Comment by xylar** [comment]
I know what happened.  We took out the lines for computing the `landIceMask` in code because it is more efficient to do it in COMPASS in a way that is independent of the level of topographic smoothing.  `landIceMask` should now be read in as part of the initial condition and never be altered.

However, I think the computation snuck back in as part of resolving a merge conflict:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/shared/mpas_ocn_diagnostics.F#L1650-L1662
That whole bit shouldn't be there.

Whoever resolved the merge conflict in:
https://github.com/MPAS-Dev/MPAS-Model/commit/50fc6dd0ddcb0cb356796e34e6f1f8a740d94c85
should probably go back through there and fix things up.  It seems like a lot got reverted around that bit of code.

It's 1 am for me so it's not a good idea for me to try to fix this but I'll review changes  in the morning if someone else wants to take this on.

**Comment by darincomeau** [comment]
That sounds promising - thanks @xylar !!

**Comment by jonbob** [comment]
Thanks @xylar -- it make sense. And makes you the hero! I was not looking forward to digging into all the changes in that PR...

**Comment by mattdturner** [comment]
Thanks @xylar .  That would be one of my commits.  I'm not sure how code would have gotten reverted like that during a rebase.

@jonbob how do you want me to approach resolving the issue?  Should I create a new branch to re-apply the code changes that were reverted in that commit?

**Comment by xylar** [comment]
@mattdturner, the commit I pointed to shows both you and @mark-petersen as authors.  My strong suspicion is that there were some pretty bad merge conflicts in `mpas_ocn_diagonstics.F` and one or the other of you had to go through and do the best you could to figure them out.  There was some reorganization in this particular section of code, making it particularly difficult to resolve the conflicts.

Anyway, my suggestion would be to put in a bug fix on `ocean/develop` as soon as you can, and the fix will propagate to E3SM soon hopefully.

**Comment by jonbob** [comment]
@mattdturner -- I think @xylar's suggestion is absolutely the right approach to get this fixed

**Comment by darincomeau** [comment]
Fixed by https://github.com/MPAS-Dev/MPAS-Model/pull/672
