### ISSUE TITLE
Current master is broken for v2 WaterCycle

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/E3SM#3835]
Current version of master (ef734371777a772ce8f4507ffa48c9b17859f1ec) is broken for v2 WaterCycle simulations on compy.

On compy, the code builds, but the PE layouts appear to be non-functional. I went back a few days to a3b0ba51e91111e07e2b274ff57509bdbed90527 and everything works fine.

Run script that works
`/qfs/people/gola749/E3SM/scripts/run.20200916.alpha4_fallback.piControl.EC30to60E2r2.compy.csh`

Run script that fails
`/qfs/people/gola749/E3SM/scripts/run.20200918.alpha4_fallback.piControl.EC30to60E2r2.compy.csh`

Credit goes to @xuezhengllnl for first discovering the problem.

**Comment by rljacob** [comment]
Here is what create_newcase outputs for the hash that works:
```
Pes     specification file is /qfs/people/jaco316/E3SM3/cime_config/allactive/config_pesall.xml
Machine is compy
Pes setting: grid match    is a%ne30np4.pg2_l%.+_oi%EC30to60E2r2 
Pes setting: machine match is compy 
Pes setting: compset_match is .*CAM5.+CLM45.+MPASSI.+MPASO.+MOSART.+ 
Pes setting: pesize match  is M 
Pes setting: grid          is a%ne30np4.pg2_l%r05_oi%EC30to60E2r2-1900_ICG_r%r05_g%null_w%null_z%null_m%EC30to60E2r2 
Pes setting: compset       is 1850_CAM5%CMIP6_CLM45%SPBC_MPASSI%SPUNUP_MPASO%SPUNUP_MOSART_SGLC_SWAV_SIAC_SESP 
Pes setting: tasks       is {'NTASKS_ATM': 1350, 'NTASKS_ICE': 1080, 'NTASKS_CPL': 1350, 'NTASKS_LND': 280, 'NTASKS_ROF': 280, 'NTASKS_OCN': 480} 
```

And the hash that doesn't work:

```
Pes     specification file is /qfs/people/jaco316/E3SM/cime_config/allactive/config_pesall.xml
Machine is compy
Pes setting: machine match is compy 
Pes setting: grid          is a%ne30np4.pg2_l%r05_oi%EC30to60E2r2-1900_ICG_r%r05_g%null_w%null_z%null_m%EC30to60E2r2 
Pes setting: compset       is 1850_CAM5%CMIP6_ELM%SPBC_MPASSI%SPUNUP_MPASO%SPUNUP_MOSART_SGLC_SWAV_SIAC_SESP 
Pes setting: tasks       is {'NTASKS_ATM': 160, 'NTASKS_ICE': 160, 'NTASKS_CPL': 160, 'NTASKS_LND': 160, 'NTASKS_WAV': 160, 'NTASKS_ROF': 160, 'NTASKS_OCN': 160, 'NTASKS_GLC': 160}
```
I think what happened is the pe layouts were using "CLM" and "CLM45" to distinquish different ones and those both became "ELM" which means the wrong one is now selected.  I'll have to stare at config_pesall.xml for a bit.

**Comment by rljacob** [comment]
Actually it was easier then that.  The correct entry still had "CLM45" in its compset.   My branch was started before that one was added.  Found a few of those.

**Comment by rljacob** [comment]
@golaz @xuezhengllnl  try again with latest master  46b6734d44d887bc

**Comment by golaz** [comment]
@rljacob : thanks for the quick fix. I tried again and everything works as expected.
