### ISSUE TITLE
allocated array returned to pointer variable not deallocated

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#3854]
In  subroutine atm_domain_mct( lsize, gsMap_a, dom_a ) in atm_comp_mct.F90:

         integer , pointer  :: idata(:)    ! temporary
         ...
         call mct_gsMap_orderedPoints(gsMap_a, iam, idata)

where mct_gsMap_orderedPoints (subroutine OrderedPoints_(GSMap, PEno, Points) in m_GlobalSegMap.F90)

     ! !DESCRIPTION:                                                                                                                                                         
     ! The function {\tt OrderedPoints\_()} takes the input {\tt GlobalSegMap}                                                                                               
     ! arguement {\tt GSMap} and returns a vector of the points owned by                                                                                                     
     ! {\tt PEno}.  {\tt Points} is allocated here.  The calling process                                                                                                     
     ! is responsible for deallocating the space.                       

And idata is not explicitly deallocated in  atm_domain_mct. Based on a google searches, it appears that

     "If you have pointers, you need to take care of deallocating the memory yourself"

that is, there is no automatic deallocation for allocated arrays pointed to by a local pointer variable.

Is this the correct interpretation? Should this be explicitly deallocated?

If so, it is a simple fix, and I can take care of it, but I am not confidant in my understanding.

**Comment by ambrad** [comment]
I agree: variables with the `pointer` annotation do not get deallocated when they go out of scope, whereas those with `allocatable` do. Here, why does mct_gsMap_orderedPoints allocate to a pointer type, though? Could it not make the output `idata` allocatable? I believe the language permits `allocatable, intent(out)`.

**Comment by ambrad** [comment]
I was interested in the question I posed above, so I wrote a little demonstrator:
```F90
module foo
  implicit none
contains
  subroutine alloc(a)
    integer, allocatable, intent(out) :: a(:)
    integer :: i
    allocate(a(1024000))
    do i = 1, 1024000
       a(i) = i
    end do
  end subroutine alloc

  subroutine bar()
    integer, allocatable :: a(:)
    call alloc(a)
    print *, a(1023003)
    a(1023003) = 42
    print *, a(1023003)
  end subroutine bar
end module foo

program main
  use foo
  call bar()
end program main
```
Then I built and run valgrind:
```
$ gfortran -Wall -pedantic -g mem.F90; valgrind --track-origins=yes ./a.out 
==21176== Memcheck, a memory error detector
==21176== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==21176== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==21176== Command: ./a.out
==21176== 
     1023003
          42
==21176== 
==21176== HEAP SUMMARY:
==21176==     in use at exit: 0 bytes in 0 blocks
==21176==   total heap usage: 22 allocs, 22 frees, 4,109,496 bytes allocated
==21176== 
==21176== All heap blocks were freed -- no leaks are possible
==21176== 
==21176== For counts of detected and suppressed errors, rerun with: -v
==21176== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
So `integer, allocatable, intent(out) :: a(:)` is clean both in terms of having valid memory and being deallocated automatically.

**Comment by worleyph** [comment]
@ambrad, thanks! I'll leave it to the MCT developers to decide whether to make this change, but it would then have to be propagated to all locations in E3SM that this routine is called, and to all other models that use MCT. To solve this particular issue, probably better just to add an explicit deallocate to the calling subroutine.

**Comment by rljacob** [comment]
Your interpretation of our original intent is correct.  The caller of OrderedPoints is responsible for deallocating that pointer.
When writing MCT, we struggled with "pointer" or "allocatable" for these arrays and can not recall right now why we chose "pointer".

**Comment by worleyph** [comment]
@rljacob , should I then create a PR to add the missing deallocate?

**Comment by rljacob** [comment]
Yes go ahead.
