### ISSUE TITLE
Two BGC configurations fail automated testing

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#3883]
Two BGC configurations that are part of automated testing now FAIL because the files they use for initial conditions have the incorrect number of snow layers. I can think of two quick solutions:
1. spinup up some short results using a G-case and replace the files these tests point at; or
2. set the number of snow layers to 1 in user_nl_mpassi for the purpose of testing.
Mat, Nicole -- any preference on this?

**Comment by njeffery** [comment]
We'll need to do the GCASE spinup eventually so that's my vote.  My only concern is that the coupler fix for ocean bgc needs to be in.  It won't fail if the test is short enough, but the results might be concerning.



________________________________

**Comment by jonbob** [comment]
OK, let's get the cpl fix underway as well...
