### ISSUE TITLE
scorpio timers in cime_pre_init2 not attributed correctly

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#3886]
Timing data from SCORPIO is being captured inside the
routine cime_pre_init2, but before the cime_pre_init2 timer
is called, leading to these SCORPIO timers being attributed
to GPTL_ROOT instead of to cime_pre_init2. To fix this requires
a few changes to 

cime/src/drivers/mct/main/cime_comp_mod.F90
cime/src/drivers/mct/main/cime_driver.F90

**Comment by worleyph** [comment]
@amametjanov and @rljacob, I can make a CIME branch to fix this, but would prefer to test it in a fresh checkout of E3SM master. Unfortunately, my previous CIME PR has not made it into E3SM yet (though it is in CIME master), and these changes are best applied on top of the previous ones. We can let this sit until after the next CIME update in E3SM, unless you have a better suggestion. Thanks,

**Comment by rljacob** [comment]
You could make a branch off of your previous branch, make the changes, and push that branch to CIME.

**Comment by amametjanov** [comment]
```
$ cd cime
$ git status
* (HEAD detached at 54ef8b8b6)
  master
HEAD detached at 54ef8b8b6
nothing to commit, working tree clean

$ git diff HEAD...origin/worleyph/driver/init_profiling2 > pr3716.diff
$ git apply pr3716.diff
<add and modify sources on top of that branch's diffs>
$ git stash
$ git checkout master
$ git fetch && git pull
$ git stash pop
$ git checkout -b worleyph/driver/fix-e3sm-issue-3886
<now commit changes and push to cime>
```

**Comment by worleyph** [comment]
@amametjanov and @rljacob , thank you. I'll give this a try.

**Comment by worleyph** [comment]
For background, the symptoms are (from a per-process timing file for a continuation run F case):

     Stats for thread 0:
                                    On  Called Recurse   Wallclock          max          min     UTR Overhead
     * "PIO:PIOc_get_vars_tc"        -      15    -       0.002866     0.001443     0.000028         0.000001
       "CPL:INIT"                    -       1    -     118.959518   118.959518   118.959518         0.000000
         "CPL:cime_pre_init1"        -       1    -       2.175700     2.175700     2.175700         0.000000
         "CPL:ESMF_Initialize"       -       1    -       0.001000     0.001000     0.001000         0.000000
         "CPL:cime_pre_init2"        -       1    -       1.815500     1.815500     1.815500         0.000000

     ...

       1 GPTL_ROOT
      13 CPL:init_readrestart
      13 CPL:RUN_LOOP
      27   PIO:openfile

       1 GPTL_ROOT
      13 CPL:init_readrestart
      13 CPL:RUN_LOOP
      27   PIO:PIOc_get_att_tc

       9 GPTL_ROOT
       3 CPL:init_readrestart
       3 CPL:RUN_LOOP
      15   PIO:PIOc_get_vars_tc

       1 GPTL_ROOT
      13 CPL:init_readrestart
       1 CPL:RESTART
      13 CPL:RUN_LOOP
      28   PIO:closefile

i.e., the above 4 PIO timers have calls attributed to GPTL_ROOT when they actually occur in CPL:cime_pre_init2 .

**Comment by worleyph** [comment]
@amametjanov (we can take this to slack or e-mail if more convenient):

     $ cd cime
     $ git status
     # HEAD detached at 54ef8b8
     nothing to commit, working directory clean
     
     $ git diff HEAD...origin/worleyph/driver/init_profiling2 > pr3716.diff
     fatal: ambiguous argument 'HEAD...origin/worleyph/driver/init_profiling2': unknown revision or path not in the working tree.
     Use '--' to separate paths from revisions, like this:
     'git <command> [<revision>...] -- [<file>...]'

**Comment by amametjanov** [comment]
Maybe git version is older.
```
$ git --version
git version 2.25.1
```
If that commit isn't available locally, it can be downloaded from this gist too: https://gist.github.com/amametjanov/7b72ab3c6c2cbb446caef0a0ff199503 .

**Comment by worleyph** [comment]
I tried on Compy. I can just move this to Cori ... where did you execute these commands?

**Comment by amametjanov** [comment]
Anvil, Compy, Theta. If local cime is out-of-date:
```
$ git checkout master && git fetch && git pull && git checkout 54ef8b8
```

**Comment by worleyph** [comment]
@amametjanov 

>  git checkout master && git fetch && git pull && git checkout 54ef8b8

does nothing inside of the cime directory of a fresh checkout of master. Output is

     Note: checking out '54ef8b8'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b new_branch_name
     
     HEAD is now at 54ef8b8... Add EAM case for 20TR CMIP6 docn component

The version of cime is unchanged (and does not include the changes from the recent PR that you submitted for me).

My concenrn is that if I create a branch based on the E3SM/cime version that it will conflict with the changes in my previous PR (some of the same code is being altered), causing integration problems. But if I use a standalone checkout of CIME master to make my branch, then I can't test it in E3SM.

I'll go ahead and make a branch using E3SM/cime, simply to document what I am proposing, I guess.

(@rljacob , would making a branch off of my early branch eliminate the conflicts when integrating with CIME master? I can easily add the "combined" changes to E3SM/cime when making a branch - what I did during development - is this any different?)
