### ISSUE TITLE
CRITICAL ERROR: ... config_nSnowLayers /= nSnowLayers with SMS_PT_D.ne120_oRRS18v3_ICG.A_WCYCL2000_H01AS 

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#3894]
A cdash test failed on cori-knl. `SMS.ne120_oRRS18v3_ICG.A_WCYCL2000_H01AS.cori-knl_intel.eam-cosplite`

Using a master of Oct 14th, I tried `SMS_PT_D.ne120_oRRS18v3_ICG.A_WCYCL2000_H01AS.cori-knl_intel.eam-cosplite` and I think I get the same error with that, which is:

```
1906: forrtl: error (76): Abort trap signal
1906: Image              PC                Routine            Line        Source
1906: e3sm.exe           0000000010ADF754  Unknown               Unknown  Unknown
1906: e3sm.exe           0000000010806710  Unknown               Unknown  Unknown
1906: e3sm.exe           0000000010BA4BF0  Unknown               Unknown  Unknown
1906: e3sm.exe           0000000010FD0901  Unknown               Unknown  Unknown
1906: e3sm.exe           000000001093AD42  Unknown               Unknown  Unknown
1906: e3sm.exe           0000000010908CCB  Unknown               Unknown  Unknown
1906: e3sm.exe           000000001090F585  Unknown               Unknown  Unknown
1906: e3sm.exe           000000000AAFC7E5  mpas_log_mp_log_a         824  mpas_log.f90
1906: e3sm.exe           000000000AAF977E  mpas_log_mp_mpas_         616  mpas_log.f90
1906: e3sm.exe           0000000009A166A0  seaice_column_mp_        8982  mpas_seaice_column.f90
1906: e3sm.exe           0000000009A11A9C  seaice_column_mp_        8757  mpas_seaice_column.f90
1906: e3sm.exe           00000000098861F9  seaice_column_mp_         235  mpas_seaice_column.f90
1906: e3sm.exe           00000000097BC6A3  seaice_initialize         114  mpas_seaice_initialize.f90
1906: e3sm.exe           000000000B0FE835  seaice_core_mp_mp         254  mpas_seaice_core.f90
1906: e3sm.exe           000000000B0FD3DA  seaice_core_mp_se         142  mpas_seaice_core.f90
1906: e3sm.exe           000000000965A0A3  ice_comp_mct_mp_i         562  ice_comp_mct.f90
1906: e3sm.exe           00000000004530D6  component_mod_mp_         257  component_mod.F90
1906: e3sm.exe           000000000041492E  cime_comp_mod_mp_        1371  cime_comp_mod.F90

with many log.seaice.*.err files that indicate:

CRITICAL ERROR: Check for inconsistencies in restart file: config_nSnowLayers /= nSnowLayers
```
I don't know exactly what that means, but I note:

```
cori09% grep -i snowlay run/ice.log.35186975.201016-181718 
        nSnowLayers = 1
        nAlgaeSnowLayers = 6
        nDOCSnowLayers = 4
        nDICSnowLayers = 2
        nDONSnowLayers = 2
        nPartIronSnowLayers = 2
        nDisIronSnowLayers = 2
        nzAerosolsSnowLayers = 6
       config_nSnowLayers = 5

/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/m45-oct14/SMS_PT_D.ne120_oRRS18v3_ICG.A_WCYCL2000_H01AS.cori-knl_intel.eam-cosplite.20201016_125047_6cm814
```

**Comment by njeffery** [comment]
The new defaults for running MPAS-SI  use 5 snow layers. All runs that begin from a 1 snow-layer (the previous default) spun-up sea ice run will trigger that error.   The solution is to begin with no ice conditions or a spun-up sea ice state with 5 snow layers.

**Comment by jonbob** [comment]
@ndkeen - that means we could change this test configuration to SMS_PT_D.ne120_oRRS18v3.A_WCYCL2000_H01A, or else run another G-case spinup for the oRRS18v3 ocean grid. This will not be a high-res configuration for v2, so I think it makes sense to either:
1. temporarily change the test to one that does not require spunup ocn/ice initial conditions; or
2. change this test to one that exercises the v2 high-res RRM configuration.
@rljacob - do you have a preference?

**Comment by rljacob** [comment]
I prefer 2.   But to support people using old restarts with v2, is it possible to put in code that would allow starting from an ice state with 1 layer? Maybe interpolate from 1 to 5 or fill in the other 4 with copies of the 1 layer?

**Comment by jonbob** [comment]
It's possible to change the number of layers in user_nl_mpassi, though I'm hesitant to suggest that. I don't think the single layer can be interpolated or copied to the five layers and be scientifically valid. If this is just for testing, we can run a one-month G-case to spinup a set of initial conditions. But otherwise this resolution can be run with any of the maint1 branches to support people using old restarts. Otherwise, I think they'll have to create new ones or move to the newer grids

**Comment by ndkeen** [comment]
This test is still reporting fail on CDASH

**Comment by ndkeen** [comment]
This test still fails in same way and reported on CDASH.

**Comment by maltrud** [comment]
i'll try to generate a 5 snow layer IC ASAP.

**Comment by ndkeen** [comment]
This is indeed just for testing. I would think whatever is appropriate to keep it going and be most relevant to current use-cases.

**Comment by maltrud** [comment]
we'll need it for any future runs using the RRS18v3 so it makes sense to do it.  i just did the same thing with a different grid so should be very straightforward.

**Comment by ndkeen** [comment]
fyi, `SMS.ne120_oRRS18v3.WCYCL1950` with current master also fails with same error message.

**Comment by ndkeen** [comment]
Trying `SMS.ne120_oRRS18v3_ICG.A_WCYCL2000_H01AS` with branch `jonbob/scripts/update_RRS18to6v3`

```
 ERROR: no alias ne120_oRRS18v3_ICG defined
```

and then with `SMS.ne120_oRRS18v3.WCYCL1950`
