### ISSUE TITLE
Radiation outputs are zero when nhtfrq < irad[s,l]w

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/E3SM#3906]
We recently discovered while running simulations with very high frequency output that there's an interesting "feature" (read: "bug"?) in our radiation fields output that requires some careful user attention if trying to get meaningful high frequency outputs. Since radiation is often called somewhat infrequently to save cost, it's possible to select an output frequency that's shorter than the radiation update frequency. When this happens, the radiation outputs will apparently contain zeros for the times between radiation update calls. For example, if radiation is only called every hour (the default if not specified explicitly in a namelist), but you try to write history files every half hour, then every other time index in the output files will contain all zeros. This is true for both RRTMG and RRTMGP, but only shows up when trying to write at intervals shorter than the radiation update interval (i.e., when `nhtfrq < irad[s,l]w`). I think this is actually because the output fields are not defined with the flag `flag_xyfill=.true.` set. At least with that flag, intermediate times are filled with `fillvalue`, so that when taking means over a time period you aren't inadvertently averaging a bunch of zeros (something we found out the hard way). I think we should implement a PR to fix the `addfld` calls to add this flag to prevent this from happening in the future, but for now users should take care to make sure that `nhtfrq >= irad[s,l]w`.

**Comment by PeterCaldwell** [comment]
So flag_xyfill will set rad outputs to nan instead of zero for steps when rad wasn't called? That seems like a no-brainer - setting to zero is clearly wrong. We should make this change in E3SM repo as well. We will still need to try to set rad call freq to match output freq because otherwise our rad output frequency won't be as frequent as we are expecting and our output files will be bloated with a bunch of unnecessary nans.

**Comment by brhillman** [comment]
Yes, agreed. I think we are in agreement that iradsw/iradlw not being set explicitly in recent runs was an oversight, although with the proposed fix, time averages should at least be "correct" in that case, even if we are saving some unnecessary nans. I'll put the PR together.
