### ISSUE TITLE
maint-1.1 not supported on Cori-KNL or on Cori-Haswell

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#3908]
I) For Cori-KNL using FC5AVIC-L and ne4_ne4:

 a) maint-1.1 still refers to /project/projectdirs/acme/inputdata

% ./case.setup
ERROR: inputdata root is not a directory: /project/projectdirs/acme/inputdata

 b) after replacing acme with e3sm in the case directory (three files), it then dies with 

% ./case.setup
...
   Calling /global/u2/w/worleyph/E3SM/MAINT/maint-1.1/E3SM/components/cice/cime_config/buildnml
ERROR: Command: './generate_cice_decomp.pl -ccsmroot /global/u2/w/worleyph/E3SM/MAINT/maint-1.1/E3SM -res ne4np4 -nx 866 -ny 1 -nproc 96.0 -thrds 1 -output all' failed with error 'b'Value "96.0" invalid for option nproc (number expected)\nSYNOPSIS\n     generate_cice_decomp.pl [options]\nOPTIONS\n     -ccsmroot <path>               Full pathname for ccsmroot\n                                    (required)\n     -nproc <number>      (or -n)   Number of mpi tasks used.\t\n                                    (required)\n     -nx <number>                   number of lons \n                                    (optional, default is 320)\n     -ny <number>                   number of lats\n                                    (optional, default is 384)\n     -res <resolution>    (or -r)   Horizontal resolution \n                                    (optional, default gx1v6)\n     -thrds <number>      (or -t)   Number of threads per mpi task\n                                    (optional, default 1)\n     -output <type>\t  (or -o)   Either output: all, maxblocks, bsize-x, bsize-y, or decomptype\n\t\t\t            (optional, default all)\n\nEXAMPLES\n\n   generate_cice_decomp.pl -res gx1v6 -nx 320 -ny 384  -nproc 80 -output maxblocks\n\n   will return a single value -- the optimum max number of blocks to utilize'' from dir '/global/u2/w/worleyph/E3SM/MAINT/maint-1.1/E3SM/components/cice/bld'

-------------

II) For Cori-Haswell using FC5AVIC-L and ne4_ne4:

 a) maint-1.1 still refers to /project/projectdirs/acme/inputdata

% ./case.setup
ERROR: inputdata root is not a directory: /project/projectdirs/acme/inputdata

 b) after replacing acme with e3sm in the case directory (three files), it then dies with 

% ./case.setup
ERROR: module command /opt/modules/default/bin/modulecmd python load cray-netcdf-hdf5parallel/4.6.1.3 cray-hdf5-parallel/1.10.2.1 cray-parallel-netcdf/1.8.1.4 failed with message:
cray-hdf5-parallel(3):ERROR:105: Unable to locate a modulefile for 'cray-hdf5-parallel/1.10.2.1'

---------------

Note that maint-1.0 builds and runs on Cori-KNL and Cori-Haswell, with full performance archiving.

Note that maint-1.2 builds on Cori-KNL and Cori-Haswell, but fails at runtime because it is still calling sqs in provenance.py and in syslog.cori-haswell and in syslog.cori-knl. After fixing this, maint-1.2 also runs and archives performance data successfully. Fixing this will be submitted as a separate github issue.

**Comment by worleyph** [comment]
Note that, as mentioned in Issue #3909 , maint-1.1 still uses 'sqs -f' in provenance.py, in syslog.cori-haswell, and in syslog.cori-knl . This will need to be fixed as well.

**Comment by ndkeen** [comment]
I thought PR 3980 should have closed this.
