### ISSUE TITLE
'-f' is no longer a valid option for 'sqs' command on NERSC, causing case.submit to fail for maint-1.2

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#3909]
As documented in Issue #3699 , '-f' is no longer a valid option for 'sqs' command on NERSC. A workaround was implemented for master and for maint-1.0. However it was not implemented for maint-1.2 (for either Cori-KNL or Cori-Haswell). It was also not implemented for maint-1.1, but maint-1.1 fails during setup (see Issue #3908 ), so it has other problems.

**Comment by worleyph** [comment]
Files that need to be changed are provenance.py, syslog.cori-haswell, and syslog.cori-knl . After making these changes, an F case ran successfully with full performance data archiving.

**Comment by rljacob** [comment]
Can you make the PR with those changes?

**Comment by worleyph** [comment]
@ndk submitted the PR to fix this for maint-1.0 (PR #3704 ). Changes should be identical. Could Noel take on this task? He'll need to make the identical changes (and more) in maint-1.1 .

**Comment by rljacob** [comment]
sure.

**Comment by ndkeen** [comment]
Thought PR 3981 would have closed this issue.
