### ISSUE TITLE
Discussion: cmake build system issues

### ISSUE THREAD

**Issue by jgfouca** [E3SM-Project/E3SM#3919]
@rljacob , @jonbob , @akturner , @amametjanov , @worleyph , I really want for everyone to feel like the new E3SM build system is working well for them. Let's use this issue as a place for discussion and gathering problems with the new system.

Please see this documentation page if you haven't already: https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/1011942171/E3SM+Build+System+and+CMake

**Comment by rljacob** [comment]
@sarats had some thoughts

**Comment by sarats** [comment]
Are the component level build logs separable?

Is detailed timing added to the various configure, build steps to help diagnose issues?

Regarding a recent issue encountered by @rljacob about mixing compilers, we would probably run into that scenario on other machines as well. So, a documented workaround would be great.

All things being equal, I would strongly prefer to have a 'old' Makefile option for working on testbeds and new supercomputers. We are running into scenarios where it's not just a CMake configuration issue but requires internal CMake development.
----
Just FYI, I have run into issues building CMake based applications with Fujitsu compilers on Fugaku and have started working with Kitware folks to resolve them. I understand the unique nature of this scenario but I'm tired of fighting with CMake over the past month.
See https://discourse.cmake.org/t/cmake-support-for-fujitsu-compilers/2055
and https://discourse.cmake.org/t/findblas-with-fujitsu-libraries/1953

**Comment by sarats** [comment]
It's a good idea to capture the CMake invocation separately (not just as part of a big log) for provenance.

**Comment by oksanaguba** [comment]
Having a separate non-cmake build system in e3sm won't help to build standalone homme.

**Comment by sarats** [comment]
@oksanaguba My comments are not limited to HOMME.

**Comment by jgfouca** [comment]
@sarats , @rljacob 

> Are the component level build logs separable?

Yes, if you use the `--separate-builds` flag from #3918

> Is detailed timing added to the various configure, build steps to help diagnose issues?

Yes, cmake supports that with minor changes. I will add that to 3918.

> Regarding a recent issue encountered by @rljacob about mixing compilers, we would probably run into that scenario on other machines as well.

It is true that CMake does not have good support for multiple compilers for the same language. There are two workarounds that I'm aware of. One, we can capture the compiler-selection indirection in a simple wrapper script and use that script as the compiler exe. Two, we can leverage cmake's add_custom_command capability to hardcode the compilations for a set of files. I will investigate this issue.

>  but I'm tired of fighting with CMake over the past month

I understand your frustration. I've also been waiting a long time for Kitware to fix the f90 dependency scanner. It would be nice if I had access to these machines so I could see how deep the problems are. In our (E3SM) case, we don't really need many of the fancier features of cmake, such as checking to see if the compiler is working and probing the compiler version; we just want it to generate the correct low-level Makefiles.

> All things being equal, I would strongly prefer to have 'old' Makefile option (as backup) 

I'd be OK with that if there were some automated way to keep the new and classic build systems working and consistent with each other, but I don't see how that's possible. In order for the build systems to be consistent, several sets of files will need to be kept consistent with each other:
* E3SM/cime_config/machines/Depends.$compiler.$machine.cmake  and E3SM/cime_config/machines/Depends.$compiler.$machine
* E3SM/components/*/cime_config/buildlib_cmake and E3SM/components/*/cime_config/buildlib
* E3SM/components/cmake/* and E3SM/cime/scripts/Tools/Makefile

 Any lack of consistency could break the build, or worse, appear to work but give you a binary that functions differently due to a change in flags. Even if someone was tasked with keeping both build systems working and consistent, that would leave us with the complexity and technical debt of both systems in a build system that already has far too much of both.

I'm not sure where to go from here. I guess I'd like to confirm that the Cmake situation is truly hopeless on some set of machines on which E3SM must work. Once that's confirmed, I suppose we don't have much choice but to try to support the classic system.

One thing that crosses my mind: I did a lot of work to ensure the Cmake system was file-for-file and flag-for-flag compatible with the classic system. We could potentially try to leverage and productize that work as the basis of a new test-type, let's call it BLD, that verifies the build systems against each other. If we had something like that, we could maybe think about supporting both Cmake and classic longterm. Note that this solution does not address my concerns about complexity and technical debt... it actually makes it worse since the BLD test type would require a fair bit of new code.

**Comment by jgfouca** [comment]
Closing since it appears the discussion is over. A separate ticket can be created for compiler mixing if that is still needed.
