### ISSUE TITLE
Assertion in SCORPIO in DEBUG=true build

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/E3SM#3988]
As part of getting the v2 RRM model running on cori-knl, we're running with DEBUG=true. We are seeing an assertion in SCORPIO during restart file write:
```
240: Assertion failed...
240: PIO: FATAL ERROR: Aborting... expected NULLs (/qfs/people/brad323/e3sm/externals/scorpio/src/clib/pio_getput_int.c: 1538)
```
SCORPIO is at today's version in master. I ran a smaller case on Compy to make it easier for the SCORPIO team to debug. Here is a reproducer script:
```bash
e3sm=/path/to/E3SM/root  # set e3sm to your E3SM root directory
wcid=e3sm
compset=A_WCYCL1850 
res=ne30pg2_r05_EC30to60E2r2
case=v2.$compset.$res
rm -rf $case
$e3sm/cime/scripts/create_newcase -case $case -res $res -compset $compset -project $wcid --handle-preexisting-dirs u --machine compy --compiler intel --pecount XS
cd $case

./xmlchange CAM_TARGET=theta-l

./xmlchange STOP_N=1
./xmlchange STOP_OPTION=nhours
./xmlchange REST_N=1
./xmlchange REST_OPTION=nhours
./xmlchange BUDGETS=TRUE
./xmlchange HIST_N=1
./xmlchange HIST_OPTION=nhours

./xmlchange DEBUG=TRUE

./case.setup
./case.build
./case.submit
```

**Comment by ambrad** [comment]
@jayeshkrishna I don't know whether this is actually a SCORPIO bug, but you likely know this code best and may be able to provide some insight.

**Comment by ambrad** [comment]
Here's most of a stack trace. The problem might be in how ROF uses SCORPIO.
```
273: e3sm.exe           000000000D22E1F7  pionfput_mod_mp_p         372  pionfput_mod.F90.in
273: e3sm.exe           000000000D248CA8  pionfput_mod_mp_p         670  pionfput_mod.F90.in
273: e3sm.exe           000000000CB00585  rtmio_mp_ncd_io_i        1000  RtmIO.F90
273: e3sm.exe           000000000C8B0D52  rtmtimemanager_mp         372  RtmTimeManager.F90
273: e3sm.exe           000000000C89B524  rtmrestfile_mp_rt          94  RtmRestFile.F90
273: e3sm.exe           000000000C811831  rtmmod_mp_rtmrun_        3049  RtmMod.F90
273: e3sm.exe           000000000C72D377  rof_comp_mct_mp_r         350  rof_comp_mct.F90
273: e3sm.exe           000000000047F9B6  component_mod_mp_         737  component_mod.F90
273: e3sm.exe           00000000004460DB  cime_comp_mod_mp_        2712  cime_comp_mod.F90
273: e3sm.exe           00000000004670A5  MAIN__                    153  cime_driver.F90
```

**Comment by ambrad** [comment]
I'm wondering if the `ncd_io_{log,int,real}_var0_nf` calls in RtmIO.F90 at lines 948, 1000, 1052 should use
```F90
status = pio_put_var(ncid, varid, temp(1))
```
rather than
```F90
status = pio_put_var(ncid, varid, start, count, temp)
```
If so, the routines can be cleaned up a bit to remove the unused start and count arrays.

**Comment by jayeshkrishna** [comment]
Yes, I agree these routines should not be passing the start/count arrays since the variable being written to is a scalar variable.

However let me also check how the NetCDF/PnetCDF libraries handle this case (if they allow a start/count of size/val  = 1 for writing to scalars then we might have to support the usage in Scorpio too i.e., ignore the start/count like we do and drop the assert)

**Comment by jayeshkrishna** [comment]
Looks like NetCDF just ignores (silently) starts/counts for scalar variables. We will need to remove the assert in Scorpio and may be add a slightly tighter condition check and warning.
