### ISSUE TITLE
Turning config_use_high_frequency_coupling on in seaice causes PEM failures

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#3989]
[PR #3984](https://github.com/E3SM-Project/E3SM/pull/3984) was merged to master and turned on config_use_high_frequency_coupling in MPAS-seaice, but is causing PEM failures. If we can't figure it out quickly, we should either revert that PR or submit a new one turning it back off

**Comment by proteanplanet** [comment]
@jonbob Something is not right here.  I have been running with this switched on using E3SM master for months.

**Comment by jonbob** [comment]
@proteanplanet - a PEM test failure doesn't mean the code won't run, just that it's getting different answers on different pe counts

**Comment by proteanplanet** [comment]
@jonbob Talk to you about it in half an hour...

**Comment by jonbob** [comment]
Sounds good. In the meantime, I tested that part of the code a bit and it's not due to the changes to ice_atmos you made in [PR #3948](https://github.com/E3SM-Project/E3SM/pull/3948) -- so it must be something already there in the highfreq coding

**Comment by akturner** [comment]
@jonbob @proteanplanet : The MPAS-Seaice standalone parallel tests fail with the high frequency coupling. Will investigate.
