### ISSUE TITLE
slurm job script output not treated correctly in performance archiving

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#4009]
In provenance.py, the job script output is treated differently on the different SLURM systems (anvil, compy, and the cori systems):

        elif mach == "anvil":
            globs_to_copy.append("%s*run*%s" % (case.get_value("CASE"), job_id))
        elif mach == "compy":
            globs_to_copy.append("slurm.err")
            globs_to_copy.append("slurm.out")
     ...
        elif mach in ["cori-haswell", "cori-knl"]:
            globs_to_copy.append("%s*run*%s" % (case.get_value("CASE"), job_id))

and none of these are correct (though they were at the time each system was first added or when moved to SLURM). They should instead be:

        if mach in ["anvil", "compy", "cori-haswell", "cori-knl"]:
            globs_to_copy.append("run*%s*%s" % (case.get_value("CASE"), job_id))

With the addition of chrysalis, the logic should be

        if mach in ["anvil", "chrysalis", "compy", "cori-haswell", "cori-knl"]:
            globs_to_copy.append("run*%s*%s" % (case.get_value("CASE"), job_id))

**Comment by worleyph** [comment]
@rljacob , I'm still uncertain as to the process. This issue won't be resolved until CIME has been updated and E3SM moves to the new version, correct? Has this already been done?

**Comment by rljacob** [comment]
Did #4010 fix this issue?    E3SM is now pointing to your branch on CIME in that PR.  That was easy to do since you started your branch from the version of master we were pointing to.

**Comment by worleyph** [comment]
Sorry - I really have no understanding how this works. Yes - my CIME branch that the associated E3SM PR points at fixes the problem, and @amametjanov has submitted that branch as a CIME PR. Does the E3SM PR really bring my CIME branch into E3SM master? Is it then replaced when E3SM is next merged with CIME master?

**Comment by rljacob** [comment]
Yes that's right.

**Comment by worleyph** [comment]
Thanks.
