### ISSUE TITLE
Hang in netcdf writes on Chrysalis

### ISSUE THREAD

**Issue by amametjanov** [E3SM-Project/E3SM#4015]
On Chrysalis, long-run jobs hang on various netcdf history writes. To reproduce:
```
./cime/scripts/create_test SMS_Lm3.ne30pg2_EC30to60E2r2-1900_ICG.A_WCYCL1850S_CMIP6
```
with `HIST_[N,OPTION]=[1,nmonths]`, `REST_[N,OPTION]=[1,nmonths]`, `RESUBMIT=9`.

Changing `PIO_TYPENAME=[pnetcdf,netcdf]` or `PIO_VERSION=[1,2]` does not help. This only manifests on Chrysalis, not Anvil. Netcdf module versions are same, pnetcdf 1.12.1 is known to work on other machines.

This appears to be a race condition triggered on a faster machine.

Runs with `maint-1.0` appear to be okay.

**Comment by sarats** [comment]
I presume this issue and corresponding workaround (removing env var) is limited to Intel MPI, right? 
We should track the OpenMPI/HPCX issue also (BFB reproducibility?) somewhere.
