### ISSUE TITLE
New surface dataset needed for NA RRM

### ISSUE THREAD

**Issue by bishtgautam** [E3SM-Project/E3SM#4029]
@tangq What is the `--res` for this configuration?

**Comment by tangq** [comment]
@bishtgautam , the land grid will be either northamericax4v1pg2 or northamericax4v1. Since I was not involved in the process of switch from the tri-grid to bi-grid, I will let @golaz to answer this question.

**Comment by golaz** [comment]
We definitely want to use the phys-grid, so I assume the correct answer is northamericax4v1pg2.

@tangq : what resolution do you specify when you configure your case?

**Comment by tangq** [comment]
In that case, northamericax4v1pg2 is the one, @golaz .

**Comment by bishtgautam** [comment]
@aldivi I successfully created surface dataset for 1850 and 2010 at northamericax4v1pg2 resolution, but I'm getting the following error when attempting to create the LULC time series 
```
 Open harvest file:
 /global/cscratch1/sd/gbisht/inputdata/lnd/clm2/rawdata/LUT_LUH2_HIST_LUH1f_0708
 2020/LUT_LUH2_historical_1858_c07082020.nc
(gridmap_map_read) reading mapping matrix data...
(gridmap_map_read) * file name                  : /global/cscratch1/sd/gbisht/inputdata/lnd/clm2/mappingdata/maps/northamericax4v1pg2/map_0.5x0.5_MODIS_to_northamericax4v1pg2_nomask_aave_da_c210112.nc
 * matrix dimensions rows x cols :      259200  x       57816
 * number of non-zero elements:       216389
 domain_clean: cleaning       259200
 Successfully made harvest and grazing

 pctpft_full < 0.0 =  -1.753281377858684E-007
  n, m, suma, pcturb_excess, sumpft =        37901           1
   51.1496979456281        94.6789010943452        94.6788991939972
 pctpft_full < 0.0 =  -2.194622439333216E-007
  n, m, suma, pcturb_excess, sumpft =        37901           7
   51.1496979456281        94.6789010943452        94.6788991939972
 pctpft_full < 0.0 =  -1.069981799162179E-006
  n, m, suma, pcturb_excess, sumpft =        37901          13
   51.1496979456281        94.6789010943452        94.6788991939972
abort:
srun: error: nid00028: task 0: Exited with exit code 134
srun: Terminating job step 37913677.2
```
Any ideas on how to fix this? To replicate my error, here are relevant files:
[northamericax4v1pg2-1850-2015.namelist](https://gist.github.com/bishtgautam/3dc4d9f4ef3f00b216f78553d992ebe9)
[northamericax4v1pg2.landuse_timeseries_hist_simyr1850-2015.txt](https://gist.github.com/bishtgautam/cdd332f46032a9167d48f1aa53caebdb)

**Comment by aldivi** [comment]
Hi Gautam,

It appears that you are using the version without the bug fix that was merged 9 days ago (#3890).
In line 1475 in mksurfdata.F90 the tolerance was still 1e-6, while the surrounding and directly related tolerances were 1e-5.

Alan

--
Alan Di Vittorio, Ph.D.
Lawrence Berkeley National Laboratory
Climate and Ecosystem Sciences Division
avdivittorio@lbl.gov

**Comment by bishtgautam** [comment]
Thanks @aldivi. I will run the code with the latest version and check if it fixes the error.

**Comment by wlin7** [comment]
Hi @aldivi and @bishtgautam ,

Can you please also help with creating the surface dataset for another RRM: antarcticax4v1pg2? It is for the use of the cryosphere group. Thanks.
