### ISSUE TITLE
Invalid compset name FC5AV1C-04P2

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#4046]
The following e3sm_integration test failed on anlworkstation:
`SMS_Ld9.ne4pg2_ne4pg2.FC5AV1C-04P2.anlworkstation_gnu.eam-thetahy_sl_pg2_mass`

Errors were:
```
Output: Did not find an alias or longname compset match for FC5AV1C-04P2 
Automatically adding SATM to compset
Automatically adding SLND to compset
Automatically adding SICE to compset
Automatically adding SOCN to compset
Automatically adding SROF to compset
Automatically adding SGLC to compset
Automatically adding SWAV to compset
Automatically adding SIAC to compset
Automatically adding SESP to compset
ERROR: Invalid compset name, FC5AV1C-04P2, all stub components generated
```

This error is introduced by PR #4007. Should we remove this test from e3sm_integration suite?

**Comment by ambrad** [comment]
Does anyone know what the new equivalent name of FC5AV1C-04P2 is? -04P2 adds 4 extra tracers. One of them, CO2_FFF, is inert and so is used to do a global mass conservation check in this test. If we know the new equivalent name, we can modify the test to use that new name.

**Comment by ambrad** [comment]
PR #4047 fixes this issue.
