### ISSUE TITLE
Error when using threads with ERS.f19_g16.I1850GSWCNPECACNTBC.machine_intel.elm-eca_f19_g16_I1850GSWCNPECACNTBC

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4083]
Another failing text reporting to CDASH. Originally found on cori-knl with next.  And I just repeated the test with same error on current master (Feb 8). Running again on cori without threads, test passes. And running same test with threads on chrysalis shows an error (however, it's the same error in issue 4082).
 
https://github.com/E3SM-Project/E3SM/issues/4082

```
207:  error ppool_patch is negative:       129820
207:  ppool_patch:  -4.609786533910168E-007
207:  ENDRUN:
207:  ERROR in PrecisionControlMod.F90 at line 752                                   
207:                                                                                 
207:                                                                                 
207:                                                                                 
207:                                                                                 
207:                                                                                 
207:                                        
207:  ERROR: Unknown error submitted to shr_abort_abort.
207: Image              PC                Routine            Line        Source             
207: e3sm.exe           0000000002BC8DFA  Unknown               Unknown  Unknown
207: e3sm.exe           00000000010E287E  shr_abort_mod_mp_         114  shr_abort_mod.F90
207: e3sm.exe           000000000050D9EF  abortutils_mp_end          43  abortutils.F90
207: e3sm.exe           0000000000BD1229  precisioncontrolm         752  PrecisionControlMod.F90
207: e3sm.exe           0000000000B53AC7  ecosystemdynmod_m         224  EcosystemDynMod.F90
207: e3sm.exe           000000000051C6C0  elm_driver_mp_elm        1235  elm_driver.F90
207: e3sm.exe           000000000168CDE3  Unknown               Unknown  Unknown
207: e3sm.exe           000000000163708A  Unknown               Unknown  Unknown
207: e3sm.exe           0000000001638936  Unknown               Unknown  Unknown
207: e3sm.exe           0000000001604085  Unknown               Unknown  Unknown
207: e3sm.exe           0000000000517D6C  elm_driver_mp_elm         617  elm_driver.F90
207: e3sm.exe           000000000050332A  lnd_comp_mct_mp_l         501  lnd_comp_mct.F90
207: e3sm.exe           0000000000424FA9  component_mod_mp_         737  component_mod.F90
207: e3sm.exe           0000000000404256  cime_comp_mod_mp_        2812  cime_comp_mod.F90
207: e3sm.exe           0000000000424B9D  MAIN__                    153  cime_driver.F90


/global/cscratch1/sd/e3smtest/e3sm_scratch/cori-knl/ERS.f19_g16.I1850GSWCNPECACNTBC.cori-knl_intel.elm-eca_f19_g16_I1850GSWCNPECACNTBC.JNextDeveloper20210205_090830

master:
/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/m52-feb8/ERS.f19_g16.I1850GSWCNPECACNTBC.cori-knl_intel.elm-eca_f19_g16_I1850GSWCNPECACNTBC.20210208_110604_nf3rd8
```

Testing with 1 thread does NOT exhibit this error.

**Comment by rgknox** [comment]
@ndkeen do we have a precedent of this test passing, ie can we look back and see what has changed since it started failing?

**Comment by ndkeen** [comment]
Looking on cdash, if we can believe the historical results, it looks like it passed on Jan 17th and then failed on Jan 21st and beyond. Now Jan 17th is when it claims was the first time this test was run. It could be that was the date of the clm->elm change which cdash would think is a different test?

In my own directories where I have run e3sm_developer, I see that this test did run on Sept 22nd 2020.
`/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/mfdirm/ERS.f19_g16.I1850GSWCNPECACNTBC.cori-knl_intel.elm-eca_f19_g16_I1850GSWCNPECACNTBC.G.gen`

For your internal testing, is it the case that testing with threads is not routine?

**Comment by rgknox** [comment]
When we test FATES-side changes, ie stuff that is not related to the interface between FATES and ELM, we do a thread change test (but then again, we use CESM as the host model for those tests).  If I remember correctly, it is an ERS test, where the restart simulation uses multi-threading and the other does not (or vise-versa).  So yeah, I think thread change tests are important.  Threading is code that is in the model, we should be covering it with tests continually. 

Now I'm trying to think of a scenario where adding the thread change to an ERS test (or similar) would be undesirable, and I can't think of it.

**Comment by rljacob** [comment]
ERS is just a restart test and doesn't change threading.  ERP does a restart while change threads and tasks.

**Comment by ndkeen** [comment]
I verified that a repo from Jan 14th does pass this test. Case here:
`/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/ERS.f19_g16.I1850GSWCNPECACNTBC.cori-knl_intel.elm-eca_f19_g16_I1850GSWCNPECACNTBC.20210303_160408_2bnpwb`

So it likely stopped working between the 14th and 21st of Jan -- and possibly we can say (from CDASH data) between the 17th and 21st.

**Comment by bishtgautam** [comment]
@ndkeen You are correct that PR #3990 broke this test. (cc: @rgknox)

**Comment by bishtgautam** [comment]
@rgknox The model is crashing on the second timestep with the P imbalance error
```
    Completed timestep: 0001-01-01_00:30:00
 Beginning timestep   : 0001-01-01_01:00:00
 column pbalance error =   1.301598917754319E-008           9
 Latdeg,Londeg=   50.2105263157894        132.500000000000
 begpb       =    19.6601288325846
 endpb       =    19.6601069345221
 delta store =  -2.189806246377657E-005
 input mass  =   1.912074070642588E-007
 output mass =   2.207625388166328E-005
 net flux    =  -2.188504647459903E-005
 ptol_pflux: =   1.240170494247755E-005
 sminp_to_plant: =   7.895289071739008E-005
 primp_to_labilep =   1.912074070642588E-007
 supplement_to_sminp =   0.000000000000000E+000
 secondp_to_occlp =   9.456608273211236E-009
 sminp_leached =   2.206679727339007E-005
 ENDRUN:
 ERROR in EcosystemBalanceCheckMod.F90 at line 751
```

**Comment by rgknox** [comment]
ok, will look into this

**Comment by rljacob** [comment]
Data point:  these ECA cases CAN run with threads:
ERS.f19_g16.I1850CNECACNTBC.chrysalis_intel.elm-eca
ERS.f19_g16.I1850CNECACTCBC.chrysalis_intel.elm-eca

Its the "CNPECACNT" cases that are giving runtime errors.

**Comment by rljacob** [comment]
The main error is the "column pbalance error" first reported in #4082 so closing this as a duplicate.
