### ISSUE TITLE
Archive runscript in case directory

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#4118]
Based on previous discussions over email, it would be good to copy the run script used for a simulation campaign into the case directory upon creation. Then it could be picked up in the performance archive sweep and uploaded to PACE along with other provenance information. 

This should be a one-line change to the run script. I'm unclear about the relationship between the run script in E3SM master vs. the simulation scripts repo, so need guidance on what script to target. Would be nice to have this for v2 runs.

cc @rljacob, @golaz, @philipwjones.

**Comment by sarats** [comment]
Looking at the script in master:

Lines 245-248 already get the absolute path of the script:
```
set this_script_name = `basename $0`
set relative_dir = `dirname $0`
set this_script_dir = `cd $relative_dir ; pwd -P`
set this_script_path = $this_script_dir/$this_script_name
```

Lines 684-687:
```
set script_provenance_dir  = $case_scripts_dir/run_script_provenance
set script_provenance_name = $this_script_name.`date +%F_%T_%Z`
mkdir -p $script_provenance_dir
```

This is currently getting copied to a provenance directory, we need to copy it to case directory once it's created (https://github.com/E3SM-Project/E3SM/blob/c29fb0e4a56466da1fab19b6f11b78c1133cf5bb/run_e3sm.template.csh#L600)

Open to other suggestions on capturing this for archiving.

**Comment by PeterCaldwell** [comment]
I'd suggest just changing the run script to put the copy of itself into the run script instead of into the provenance directory. I don't think we need copies in both places.

**Comment by golaz** [comment]
@sarats : please note that Water Cycle is now using a simplified run e3sm script. Here is an example:

https://github.com/E3SM-Project/SimulationScripts/blob/master/archive/v2/beta/coupled/run.20210205.v2_test02.piControl.ne30pg2_EC30to60E2r2.chrysalis.sh

The simplified run script also makes a copy of itself like the old one:

https://github.com/E3SM-Project/SimulationScripts/blob/c6a414c66607f97ddb022efd3906291796d95b92/archive/v2/beta/coupled/run.20210205.v2_test02.piControl.ne30pg2_EC30to60E2r2.chrysalis.sh#L373-L383

**Comment by rljacob** [comment]
Good idea but how will PACE recognize the run script?   CIME files in the case directory all have controlled names but the run script can be named anything.

**Comment by rljacob** [comment]
There's a provenance directory on each machine?

**Comment by sarats** [comment]
Regarding detecting for performance_archive capture/PACE, I hope there is a common prefix to all the simulation scripts.
run.*sh or a specific regex?

**Comment by sarats** [comment]
The run script apparently creates a provenance directory locally but I haven't seen it myself: $case_scripts_dir/run_script_provenance

**Comment by PeterCaldwell** [comment]
@rljacob - good point that we don't know what the run script will be named. I think we could insist all run scripts have the same ending (like *.run_e3sm.* or something), but that isn't ideal because it would be hard to enforce.

**Comment by rljacob** [comment]
As long as it ends in .sh, which it should as a shell script, that should be fine That would be the only .sh file in the case directory (except for hidden files like .env_mach_specific.sh)

**Comment by PeterCaldwell** [comment]
Eventually I want run scripts to be written in python,  but we can cross that bridge when we get to it.

**Comment by sarats** [comment]
Or there may hopefully be a time when a run script  is not needed anymore (wishful thinking I know)

Btw, did the naming convention discussion reach consensus?
https://acme-climate.atlassian.net/wiki/spaces/EWCG/pages/1373700754/Running+E3SM+-+best+practices

**Comment by sarats** [comment]
It's still unclear to me where the provenance directory is located relative to a case directory? I presume it's outside. 

@golaz Should we just add this 'extra copy to case directory' to the script at 
https://github.com/E3SM-Project/SimulationScripts/blob/master/archive/v2/beta/coupled/run.20210205.v2_test02.piControl.ne30pg2_EC30to60E2r2.chrysalis.sh
or is there a master version of the v2 simplified run template where this should be added?

From my scanning of the run scripts in the repo, it looks like run.*sh is the de facto convention.

**Comment by golaz** [comment]
@sarats: `/lcrc/group/e3sm/ac.golaz/E3SM_simulations/20210212.v2_newICs.piControl.ne30pg2_EC30to60E2r2.chrysalis/case_scripts/run_script_provenance `

**Comment by golaz** [comment]
Now that CIME has been rewritten in Python, it shouldn't be too hard to develop a proper Python API for it. That way @PeterCaldwell 's dream could become reality.

**Comment by jgfouca** [comment]
@golaz , see https://github.com/ESMCI/cime/issues/3393

**Comment by rljacob** [comment]
The run_script_provenance directory inside the case directory does what we want.  Just need to tell the PACE tools to look there.

**Comment by sarats** [comment]
Actually, we need the provenance logic in CIME to copy over that directory into the local performance archive for that experiment.

**Comment by sarats** [comment]
So, need to add the appropriate glob (run_script_provenance/*)  to https://github.com/ESMCI/cime/blob/56c121ed8c151f6f3b2b9a78c36df829ff7cf938/scripts/lib/CIME/provenance.py#L229
