### ISSUE TITLE
Capture memory logs in provenance

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#4119]
After the recent addition of memory profiling logs, following files need to be added to provenance capture in 
cime/scripts/lib/CIME/provenance.py 
Ref: https://github.com/E3SM-Project/E3SM/pull/4030
https://acme-climate.atlassian.net/wiki/spaces/EPG/blog/2021/01/17/2248474812/Memory+profiling

$RUNDIR/memory.{0,1,2,3,4}.$nsecs.log 

It would probably be good to add $LID to the filenames to disambiguate multiple jobs launched from the same run directory.

Be default there would be a memory.3.<run_duration>.log in $RUNDIR.

**Comment by rljacob** [comment]
@jgfouca can you maybe add this to the CIME update?
