### ISSUE TITLE
Print case group somewhere for post-processing tools

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#4121]
The case-group attribute has recently been added to create_newcase.
https://github.com/ESMCI/cime/issues/3825

Is this value printed to some log or output file? If not, we need it printed somewhere for post-processing tools or parsers in PACE to pick up.

As this addition may be specific to E3SM, I didn't post to CIME Github. Feel free to re-post there if that's more relevant.

**Comment by rljacob** [comment]
Its in the env_case.xml file.
`./create_newcase --case trygroup --res ne4_ne4 --compset FC5AV1C-L --case-group picontrol`

` <entry id="CASE_GROUP" value="picontrol">`
