### ISSUE TITLE
Updates cause failures for BGCEXP tests

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#4123]
The following tests are failing and like due to PR #4085 

SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.anvil_intel.elm-bgcexp
SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.anvil_intel.elm-bgcexp

**Comment by rljacob** [comment]
The smoke test itself is failing or unexpected diffs with baselines?

**Comment by jonbob** [comment]
The test is failing with an error:
```
CRITICAL ERROR: Check for inconsistencies in restart file: config_nSnowLayers /= nSnowLayers
```
I think I need to reorder some of the logic for the determining the IC files for that grid

**Comment by maltrud** [comment]
@jonbob let me know how i can help with this.  i can make a new 5 snow layer IC if you want.

**Comment by jonbob** [comment]
@maltrud - that's not actually the issue here. I just broke it with my PR to remove the _ICG grids. But I have a fix for it so it grabs the correct ICs, though at some point we'll have to redo the BGC spinups
