### ISSUE TITLE
branch runs - mpas-o and mpas-si restart files have the wrong name

### ISSUE THREAD

**Issue by mt5555** [E3SM-Project/E3SM#4129]
documenting a possible issue with branch runs using a different case name:

From the CIME documentation:
     -- In a branch run, all components are initialized using a consistent                          
      set of restart files from a previous run (determined by the                                    
      RUN_REFCASE and RUN_REFDATE variables in env_run.xml).  The case name                          
      is generally changed for a branch run, although it does not have to                            
      be. 

when attempting a branch run with a different case name, the mpas-o and mpasi-si rpointer files contain just the date stamp and not the full name of the restart file.  The mpas components then appear to construct the restart filename based on the new case name.  The run will then abort during initialization since these files dont exist.  

The atm and lnd components appear to avoid this issue by putting the full filename of the restat file in the rpointer files.

As CIME stages the restart files from the old case, after seeing the error messages a possible workaround is for the user to add symbolic links from the new names to the original names

**Comment by jonbob** [comment]
@mt5555 - I'm trying to understand this issue better. I don't think the rpointer files are used in a branch run, at least not for mpas components.
