### ISSUE TITLE
Readme updates for v2?

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#4134]
Opening an issue to discuss wish-list (if any). 

* We probably need to update the DOI for the new version.
* Sanity check running instructions and supported machine links.

Broken link on https://e3sm.org/model/running-e3sm/supported-machines/
> If you would like to try porting E3SM to your platform, start by porting CIME.
https://esmci.github.io/cime/users_guide/porting-cime.html (not working)

Sorry @rljacob if this duplicates any release checklist you might already have.

**Comment by sarats** [comment]
Need to update above link to https://esmci.github.io/cime/versions/master/html/users_guide/porting-cime.html

**Comment by rljacob** [comment]
Yes to updating the DOI.  Need to do that on the maint1-1 branch too.
