### ISSUE TITLE
case.st_archive in maint-1.0 automatically submit a new job if RESUBMIT> 0 

### ISSUE THREAD

**Issue by xuezhengllnl** [E3SM-Project/E3SM#4150]
How can I archive model output manually with case_st_archive without resubmitting jobs?

$./case.st_archive --last-date=0026-01-01 --force-move --no-incomplete-logs

When the st_archive is done, it submits a new job:

st_archive completed
resubmitting from st_archive, resubmit=2
Submitting job 'case.run', resubmit=2
submit_jobs case.run
job case.run depends on []
Submit job case.run
Submitting job script sbatch   --time 26:00:00 -p slurm --qos=watercycle --account e3sm .case.run 
Submitted job id is 178292
Submitted job case.run with id 178292

**Comment by rljacob** [comment]
Jim, this is maint-1.0 which is an old version of cime so it may have an old bug.  The behavior we want here is that a command-line invocation by the user of ./case.st_archive should NOT result in a resubmit.  The resubmit should only happen when CCS calls case.st_archive as part of its workflow.

**Comment by jgfouca** [comment]
Fixed.
