### ISSUE TITLE
Capture I/O stats in performance archive/PACE

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#4155]
Just opening an issue as a reminder.

We need to add the I/O stats file in the CIME provenance logic for capture in local performance archive and subsequent upload to PACE.

**Comment by sarats** [comment]
cc @grnydawn

**Comment by sarats** [comment]
@jayeshkrishna Did you get a chance to add the I/O stats to CIME?
scripts/lib/CIME/provenance.py

Note, we will need to update CIME once that PR goes in.

**Comment by jayeshkrishna** [comment]
Not yet, will finish up the work in couple of days.

**Comment by sarats** [comment]
Done.
