### ISSUE TITLE
TFREEZE_SALTWATER_OPTION needs to be “mushy” by default for E3SM

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#4162]
This was reported to me by @proteanplanet. cime/src/drivers/mct/cime_config/config_component_e3sm.xml sets the seawater freezing temperature option to “minus1p8” but that is not consistent with the rest of our model and needs to be switched. We may also want to wrap a line in shr_frz_mod.F90.in, which does not allow a freezing temperature below -2.0:
```
shr_frz_freezetemp = max(shr_frz_freezetemp,-2.0_R8)
```
with logic for cime_model so it does not get applied for E3SM.

**Comment by rljacob** [comment]
@jonbob As you know, we plan to bring the coupler out of cime and in to E3SM.   I could accelerate that if it will help.

**Comment by jonbob** [comment]
@rljacob - the code that calculates shr_frz_freezetemp is in cime/src/share, which I guess didn't come into E3SM? We would like to remove the line that does not allow a freezing temperature below -2.0, so should I make a CIME PR? Or is it possible to move some of the shared code into E3SM?

**Comment by rljacob** [comment]
All of the share code is going to be added to E3SM too.  Working on that now.

**Comment by jonbob** [comment]
Sounds good -- I'll just wait then. Thanks @rljacob
