### ISSUE TITLE
Excessive log output from FATES

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#4186]
In the ERS_Ld20.f45_f45.IELMFATES.*_*.elm-fates test, the e3sm.log file fills up with about 20K lines like this:

 44:  clmfates_interfaceMod.F90:: reading fates_fire_bark_scaler
 93:  clmfates_interfaceMod.F90:: reading fates_fire_crown_depth_frac
 45:  clmfates_interfaceMod.F90:: reading fates_fire_bark_scaler
 94:  clmfates_interfaceMod.F90:: reading fates_fire_crown_depth_frac
 46:  clmfates_interfaceMod.F90:: reading fates_fire_bark_scaler
 95:  clmfates_interfaceMod.F90:: reading fates_fire_crown_depth_frac

That stdout message should be changed to only output on the root task.

This is with latest master:   9ba634a366bed5ad3.  Observed on Chrysalis but probably happening on every machine.

**Comment by rljacob** [comment]
@bishtgautam reassigning to you because this needs to be fixed.

**Comment by rgknox** [comment]
this commit from #4157 was intended to address this

https://github.com/E3SM-Project/E3SM/pull/4157/commits/c35f5b82203f4d4600e7947d839131939240702c
