### ISSUE TITLE
biogenphys build error with IBM XLF compiler

### ISSUE THREAD

**Issue by xyuan** [E3SM-Project/E3SM#4195]
There is 
"1513-083 (E) Internal or module function th_sat was not set within the function"  error caused by /elm/src/external_models/fates/biogeophys/FatesHydroWTFMod.F90 when E3SM code was built with IBM XLF compiler, it can be fixed by inserting _th_sat = 0.0_r8_ to the following code

  function get_thsat_base(this) result(th_sat)
    class(wrf_type)     :: this
    real(r8)            :: th_sat
    **_th_sat = 0.0_r8_**
    write(fates_log(),*) 'The base thsat call'
    write(fates_log(),*) 'should never be actualized'
    write(fates_log(),*) 'check how the class pointer was setup'
    call endrun(msg=errMsg(sourcefile, __LINE__))
  end function get_thsat_base

Could anyone update the code in the biophysics branch to fix it?

**Comment by rgknox** [comment]
I believe this has been fixed, no?
@amametjanov

**Comment by amametjanov** [comment]
Yes, in E3SM-Project/E3SM#4289.
