### ISSUE TITLE
Missing perl modules at NERSC after maintenance affecting any new cases on Cori

### ISSUE THREAD

**Issue by xuw015** [E3SM-Project/E3SM#4240]
Hello everyone,

I met some problems to continue my RRM run after today Cori maintenance.  These problems I never met before so I have no idea about them. I will show the problems below. Please tell me where is wrong if you know. Thanks a lot. 

Error message: 
--------------------------------------------------------------------------------------------------------------------------------------
ERROR: Command: '/global/u1/x/xuw015/E3SM/components/elm/bld/build-namelist -infile /global/cscratch1/sd/xuw015/E3SM_simulations/cori-knl.RRM.E3SM.RRM.SAZM.CAPE.J.conusx4v1_conusx4v1/case_scripts/Buildconf/elmconf/namelist  -csmdata /global/cfs/cdirs/e3sm/inputdata -inputdata /global/cscratch1/sd/xuw015/E3SM_simulations/cori-knl.RRM.E3SM.RRM.SAZM.CAPE.J.conusx4v1_conusx4v1/case_scripts/Buildconf/elm.input_data_list -ignore_ic_year -namelist " &elm_inparm  start_ymd=20110101  /" -use_case 2000_control  -res ne0np4_conus_x4v1_lowcon  -clm_start_type default -envxml_dir /global/cscratch1/sd/xuw015/E3SM_simulations/cori-knl.RRM.E3SM.RRM.SAZM.CAPE.J.conusx4v1_conusx4v1/case_scripts -l_ncpl 96 -lnd_frac /global/cfs/cdirs/e3sm/inputdata/share/domains/domain.lnd.conusx4v1_tx0.1v2.161129.nc -glc_nec 0 -co2_ppmv 368.865 -co2_type diagnostic  -ncpl_base_period day  -config /global/cscratch1/sd/xuw015/E3SM_simulations/cori-knl.RRM.E3SM.RRM.SAZM.CAPE.J.conusx4v1_conusx4v1/case_scripts/Buildconf/elmconf/config_cache.xml -bgc sp -mask tx0.1v2' failed with error 'Can't locate XML/LibXML.pm in @INC (you may need to install the XML::LibXML module) (@INC contains: /global/u1/x/xuw015/E3SM/components/elm/bld /global/u1/x/xuw015/E3SM/components/elm/bld /global/u1/x/xuw015/E3SM/cime/utils/perl5lib /global/u1/x/xuw015/E3SM/cime/utils/perl5lib/Config/ /global/u1/x/xuw015/E3SM/components/elm/bld /usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.26.1 /usr/lib/perl5/vendor_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.26.1 /usr/lib/perl5/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/5.26.1 /usr/lib/perl5/site_perl) at /global/u1/x/xuw015/E3SM/cime/utils/perl5lib/Config/SetupTools.pm line 5.
BEGIN failed--compilation aborted at /global/u1/x/xuw015/E3SM/cime/utils/perl5lib/Config/SetupTools.pm line 5.
Compilation failed in require at /global/u1/x/xuw015/E3SM/components/elm/bld/CLMBuildNamelist.pm line 444.' from dir '/global/cscratch1/sd/xuw015/E3SM_simulations/cori-knl.RRM.E3SM.RRM.SAZM.CAPE.J.conusx4v1_conusx4v1/case_scripts/Buildconf/elmconf'
----------------------------------------------------------------------------------------------------------------------------------------

**Comment by ndkeen** [comment]
After Cori maintenance, it looks like NERSC hasn't yet done one of the routine tasks of installing additional perl modules. I sent an email to consulting at NERSC last night, but perhaps we should send more emails so they know it's not happening to just me.  As this as happened before, here is a simple test to show the issue:

```
cori04% cat xml-switch.pl
#! /usr/bin/perl
use strict; 
use warnings;
use Switch;
use XML::LibXML;
1;
cori04% ./xml-switch.pl 
Can't locate XML/LibXML.pm in @INC (you may need to install the XML::LibXML module) (@INC contains: /usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.26.1 /usr/lib/perl5/vendor_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.26.1 /usr/lib/perl5/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/5.26.1 /usr/lib/perl5/site_perl) at ./xml-switch.pl line 6.
BEGIN failed--compilation aborted at ./xml-switch.pl line 6.
```

Using the env var `PERL5LIB`, We may be able to use our own, but might also be easier to wait until it's completed.  I sent an email.

**Comment by ndkeen** [comment]
I recvd reply from NERSC (below). It might help if other folks also emailed NERSC so that we can more quickly resolve.

```
Short description: Missing perl modules on cori after maintenance
Click here to view: INC0167936

Hello Noel,

I can confirm this library is not present in System perl (/usr/bin/perl). Was this working prior to outage. Can you share output of `module list` and `which perl`. 

Generally we dont install perl packages in system perl. In this case we would need to install perl-XML-LibXML rpm. I will check if we are allowed to install rpms, if not we recommend you have an instance of Perl that you can manage. You can see this link https://www.perlmonks.org/?node_id=1055228 for more details 
```

I replied that of course this was working before outage (and pasted output requested)

**Comment by ndkeen** [comment]
Reply from NERSC:

```
We can install the rpm but it will take time until its deployed to system.
Generally these kind of changes are made during system outage.
I will keep you posted if we can get this installed sooner.
```

I also searched in mail to find 3 other similar issues in the past and pointed them to the
NERSC incidents numbers.

**Comment by xuw015** [comment]
Great. Thanks a lot.

**Comment by yshi5** [comment]
Hi @ndkeen, thanks for doing that! Is there any temporary solution to this issue before NERSC installing the missing module?

**Comment by cameronsmith1** [comment]
I had this problem last night.  I was trying to rerun a job that was identical to one I had done before (to make sure it was working before I started making changes!).

Thank you, @ndkeen for following up.  I will also contact NERSC to make sure they are aware that it is affecting multiple people.   I expect it will stop everyone using E3SM (and possibly CESM) at NERSC.

**Comment by cameronsmith1** [comment]
UPDATE: NERSC told me that they have received ~6 tickets from different people, so far.  They said they are working on it and will report the results through Noel's ticket, so there is no need to submit any other reports to NERSC.

**Comment by rljacob** [comment]
If you just need to resubmit a case, add --skip-preview-namelist
`./case.submit --skip-preview-namelist`

See https://github.com/ESMCI/cime/pull/3789#issuecomment-825226772 for how to add libXML to your own path.   This will only help during case.setup and case.build.  You'll still need to add --skip-preview-namelist when submitting.

**Comment by ndkeen** [comment]
I have been trying to find a work-around, but don't have a solution.

I also saw the issue Rob pointed, but that didn't work for me.

It may be that certain cases can get around this issue with `--skip-preview-namelist`, but none of the cases I tried will work. It may be that G cases can use that.

**Comment by rljacob** [comment]
Thanks for actually trying that suggestion from Jim (on a different issue).     The perl is all in the ELM and EAM buildnml chain so any cases without those models won't have a problem.

**Comment by mchinita** [comment]
Hi All,

Robert thanks for this suggestion. It worked for me! I was able to install XML-LibXML-2.0207 on my /global/cscratch1/ directory. 

I run E3SM-SCREAM in Single-Column Model on Cori. I couldn't build and run my code because LibXML was missing.
In the same directory that I build and submit my runs, I did:
curl -L http://cpanmin.us | perl - XML::LibXML 
export PERL5LIB=$HOME/perl5/lib/perl5:$PERL5LIB

And now my code builds and runs. 

Thanks again Robert. This is very appreciated.

**Comment by xuw015** [comment]
Yes, it also worked for me too. @mchinita Many thanks. @rljacob

**Comment by ndkeen** [comment]
Hmm, interesting -- not sure why it didn't work for me.

I also have another potential solution. It looks like NERSC installed perl here:
`/global/common/cori/software/perl5/lib/perl5`

And if I do `setenv PERL5LIB /global/common/cori/software/perl5/lib/perl5`,
I'm able to create new cases, build, etc.

I could also update `config_machines.xml` to include this.

**Comment by ndkeen** [comment]
I made a PR that will fix this.
I'm running e3sm_developer on cori-knl (and one simple test on cori-haswell). They seem to be working.

It's not clear the best way to handle this.

a) Merge this PR -- which will look in `/global/common/cori/software/perl5/lib/perl5` for perl modules that are not part of the normal distribution. Could be OK, but what happens when/if something changes in that directory?

b) Make a copy of what's needed from there into a place more controlled by us -- say in `/global/cfs/cdirs/e3sm`
Would need some testing and a new PR.

c) Wait to see if NERSC will include libxml module with system perl install (which requires no PR, but the same thing might happen after certain SW maintenance tasks)

**Comment by yshi5** [comment]
@ndkeen , I tried your fix by changing the machine file and it worked for me! Thanks a lot!
