### ISSUE TITLE
ERS.f19_f19.I20TRELMCN fails on cori-knl with "masterlist_addfld ERROR:M_LITR1C_TO_FIRE already on list"

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4245]
Using master of Apr22nd (which includes fix for perl libxml location):

```
ERS.f19_f19.I20TRELMCN.cori-knl_intel

fails with:

 77:  masterlist_addfld ERROR:M_LITR1C_TO_FIRE already on list
 77:  ENDRUN:
 77:  ERROR in histFileMod.F90 at line 348
```

I see that there are several tests failing with same error message:

```
ERS.f19_f19.I1850ELMCN.cori-knl_intel.20210422_194220_q070xc/run/e3sm.log.41814071.210422-210017: 38:  masterlist_addfld ERROR:M_LITR1C_TO_FIRE already on list
ERS.f19_f19.I20TRELMCN.cori-knl_intel.20210422_194220_q070xc/run/e3sm.log.41813386.210422-204002: 77:  masterlist_addfld ERROR:M_LITR1C_TO_FIRE already on list
ERS.f19_g16.I1850CNECACNTBC.cori-knl_intel.elm-eca.20210422_194220_q070xc/run/e3sm.log.41813808.210422-204642: 76:  masterlist_addfld ERROR:M_LITR1C_TO_FIRE already on list
ERS.f19_g16.I1850CNECACTCBC.cori-knl_intel.elm-eca.20210422_194220_q070xc/run/e3sm.log.41813985.210422-205523:127:  masterlist_addfld ERROR:M_LITR1C_TO_FIRE already on list
ERS.f19_g16.I1850CNRDCTCBC.cori-knl_intel.elm-rd.20210422_194220_q070xc/run/e3sm.log.41814003.210422-205551: 36:  masterlist_addfld ERROR:M_LITR1C_TO_FIRE already on list
ERS.f19_g16.I1850GSWCNPECACNTBC.cori-knl_intel.elm-eca_f19_g16_I1850GSWCNPECACNTBC.20210422_194220_q070xc/run/e3sm.log.41813662.210422-204649:127:  masterlist_addfld ERROR:M_LITR1C_TO_FIRE already on list
ERS.f19_g16.I1850GSWCNPRDCTCBC.cori-knl_intel.elm-ctc_f19_g16_I1850GSWCNPRDCTCBC.20210422_194220_q070xc/run/e3sm.log.41813741.210422-204649:127:  masterlist_addfld ERROR:M_LITR1C_TO_FIRE already on list
ERS.f19_g16.I20TRGSWCNPECACNTBC.cori-knl_intel.elm-eca_f19_g16_I20TRGSWCNPECACNTBC.20210422_194220_q070xc/run/e3sm.log.41813590.210422-204001:201:  masterlist_addfld ERROR:M_LITR1C_TO_FIRE already on list
ERS.f19_g16.I20TRGSWCNPRDCTCBC.cori-knl_intel.elm-ctc_f19_g16_I20TRGSWCNPRDCTCBC.20210422_194220_q070xc/run/e3sm.log.41813362.210422-204105: 34:  masterlist_addfld ERROR:M_LITR1C_TO_FIRE already on list

SMS_Ld2.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.cori-knl_intel.elm-bgcexp

```

**Comment by peterdschwartz** [comment]
I just messaged in slack but it's probably better to post here directly -- apologies for the repetition.

I'm guessing that the field is supposed to have a "_vr" at the end to differentiate from the non-vertically resolved field.  i.e. between the lines in ColumnDataType  5789 and line 5797.

so something like 
if (nlevdecomp > 1) then
       vr_suffix = "_vr"
    else
       vr_suffix = ""
    endif
needs to be added at the top of col_cf_init

**Comment by ndkeen** [comment]
Just adding that I tried a few more tests:

```
These fail in same way as above:
SMS.f19_f19.I1850ELMCN
SMS_P512x4.f19_f19.I1850ELMCN

While these passed:
SMS_D.f19_f19.I1850ELMCN
SMS_D_PMx1.f19_f19.I1850ELMCN
SMS_PMx1.f19_f19.I1850ELMCN
```

**Comment by peterdschwartz** [comment]
Thanks,
I ran ERS.f19_g16.I1850CNECACNTBC.cori-knl_intel and it PASS'd everything after making the change I described as well.  I'll try and look into SMS.f19_f19.I1850ELMCN next

**Comment by peterdschwartz** [comment]
@ndkeen SMS.f19_f19.I1850ELMCN PASSes for me after this fix as well rather than failing.  

> 20210426_122150_up42no: 1 test
  SMS.f19_f19.I1850ELMCN.cori-knl_intel (Overall: PASS) details:
    PASS SMS.f19_f19.I1850ELMCN.cori-knl_intel CREATE_NEWCASE
    PASS SMS.f19_f19.I1850ELMCN.cori-knl_intel XML
    PASS SMS.f19_f19.I1850ELMCN.cori-knl_intel SETUP
    PASS SMS.f19_f19.I1850ELMCN.cori-knl_intel SHAREDLIB_BUILD time=3
    PASS SMS.f19_f19.I1850ELMCN.cori-knl_intel MODEL_BUILD time=391
    PASS SMS.f19_f19.I1850ELMCN.cori-knl_intel SUBMIT
    PASS SMS.f19_f19.I1850ELMCN.cori-knl_intel RUN time=76
    PASS SMS.f19_f19.I1850ELMCN.cori-knl_intel MEMLEAK
    PASS SMS.f19_f19.I1850ELMCN.cori-knl_intel SHORT_TERM_ARCHIVER

**Comment by ndkeen** [comment]
OK.  Are you making a branch/PR?

**Comment by peterdschwartz** [comment]
I could do that, Though it might be simpler for you to make a PR so I could act as the land integrator and I'll go ahead a submit a test suite.
