### ISSUE TITLE
F-MMFOMP incompatible with Intel and OpenMP

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/E3SM#4272]
The F-MMFOMP compset adds a version of SAM with OpenMP offload directives to the MMF. However, it appears as though these directives are currently only compatible with the XL compiler, and trying to build with SMP true on Chrysalis with Intel causes numerous build fails. For now, we disable OpenMP with the MMF by explicitly setting NTHRDS=1, but eventually the MMF should support threading (outside the CRM) so this will likely need to be addressed.

**Comment by whannah1** [comment]
Closing because we have abandoned the fortran CRM.
