### ISSUE TITLE
Need reasonable default stripe count for large Lustre file systems for good IO performance

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4280]
On systems with Lustre file systems, such as cori and theta, we currently use the default stripe settings for all files which is a count of 1. For Scorpio classic (PIO_VERSION=1), I think the stripe was set to 16 for each output file. With the change to Scorpio (PIO_VERSION=2), we no longer set stripe commands. I think we should set the stripe count for each output file (say each netcdf file) perhaps with MPI hints.

What users currently do is add a command to the launch script to do `lfs setstripe -c 16 run` which sets stripe count for the entire 'run' directory. 

@wlin7 asked me if we still needed to set this for optimal IO performance.

**Comment by ndkeen** [comment]
I think the best approach is to set the striping for each output file. It may not hurt to set striping for entire 'run' directory, but seems sloppy.

**Comment by jayeshkrishna** [comment]
My vote would be to use the approach that gives us the best performance across all runs (But if the performance variance is small a simpler solution would also work. However we do not want to compromise the performance of configurations used for production simulations)

**Comment by mt5555** [comment]
going back to the PIO1 behavior (setting stripe to 16 for each history file) would give much better out-of-the-box performance, in nearly all cases.  Not optimal, but an improvement over the current situation.

**Comment by ndkeen** [comment]
Yes, we should at least be using a stripe count of 16 for all netcdf files.  We've seen several users now struggle with slow IO on Cori who did not know about this.

**Comment by mt5555** [comment]
users which dont know about this are probably running NE30, where a stripe equal to the number of OSTs seems too aggressive?

**Comment by stephenprice** [comment]
At the risk of crashing the party here -- one recent context this came up in (on Cori) is a config. w/ ne30 atmos. and r0125 land. The size of the land restart file (in particular) was problematic, requiring switching to CDF5 format (to even get it to write out the full file). Changing the stripe count to >1 also significantly (reduced) changed the overall run time.

**Comment by jayeshkrishna** [comment]
We are already working on this in a Scorpio Issue (https://github.com/E3SM-Project/scorpio/issues/409). @dqwu is testing out the different options and will be providing a solution soon.
