### ISSUE TITLE
branch run on Chrysalis

### ISSUE THREAD

**Issue by xuezhengllnl** [E3SM-Project/E3SM#4285]
I run into several issues when I conduct a branch run with master
1. The case cannot identify the correct restart files unless I make the following modification:
    $E3SM_CODES/components/mosart/cime_config/buildnml
                    #XZ refdir = os.path.join(din_loc_root, run_refdir, run_refcase, run_refdate)
                    refdir = os.path.join(run_refdir)
    $E3SM_CODES/components/mpas-ocean/cime_config/buildnml
        if run_type == 'hybrid' or run_type == 'branch':  #XZ 20210507
            lines.append('                  filename_template="{}.mpassi.rst.$Y-$M-$D_$S.nc"'.format(run_refcase))
        else:
            lines.append('                  filename_template="{}.mpassi.rst.$Y-$M-$D_$S.nc"'.format(casename))
    $E3SM_CODES/components/mpas-seaice/cime_config/buildnml
        if run_type == 'hybrid' or run_type == 'branch':  #XZ 20210507
            lines.append('                  filename_template="{}.mpassi.rst.$Y-$M-$D_$S.nc"'.format(run_refcase))
        else:
            lines.append('                  filename_template="{}.mpassi.rst.$Y-$M-$D_$S.nc"'.format(casename))
2. The branch simulation is non-BFB to the original simulation
 The test case is /lcrc/group/e3sm/ac.xzheng/E3SM_simulations /20210423.test3.v2rc1d.piControl.ne30pg2_EC30to60E2r2.chrysalis
 The reference case is /lcrc/group/e3sm/ac.xzheng/E3SM_simulations/20210423.v2rc1c.piControl.ne30pg2_EC30to60E2r2.chrysalis

**Comment by golaz** [comment]
This is an important functionality. During the v1 Water Cycle campaign, we relied heavily on the branch/hybrid capabilities for starting the various simulations from the control run. The non-BFB behavior of the "branch" simulation also worries me.

**Comment by rljacob** [comment]
We confirmed that ERS.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel passes.  It must be something in the particular logic for branch/hybrid runs.
