### ISSUE TITLE
Potential divide by zero in ocean parameterization

### ISSUE THREAD

**Issue by mark-petersen** [E3SM-Project/E3SM#4308]
This bug creates a divide by zero error, but only if latEdge is very close to zero, so it is dependent on the mesh. The exact jigsaw output varies by compiler and machine, so we did not see this error until now. This bug makes QU240 stand-alone nightly tests fail, but only with debug on.

**Comment by rljacob** [comment]
So it depends on the machine/compiler used to generate the mesh?  But once a buggy mesh is made, it happens on any machine?

**Comment by xylar** [comment]
@rljacob, if we had previously been using meshes that happened to have edges almost exactly at the equator, we would have noticed this sooner.  We generate meshes on the fly as part of our testing.  With a new version of one of the tools we use to do that (JIGSAW), it now generates such edges.  But this mesh has never been used for any E3SM simulations.  Such a mesh would also not be buggy itself, it would just expose this bug in the ocean code.

**Comment by rljacob** [comment]
Ok thanks.
