### ISSUE TITLE
modifying files in mpas-framework is not recognized by ./case.build

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#4341]
I tried to add a timer to a routine in 

     mpas-framework/src/framework/mpas_stream_manager.F

./case.build did not recognize the change and the timer was not added. This was an F case using MPASSI for ICE. I then tried

     ./case.build --clean ice
     ./case.build

and it still did not add the timer. I had to

     ./case.build --clean-all
     ./case.build

to get the timer added.

**Comment by worleyph** [comment]
@jgfouca , please reassign to whomever makes the most sense.

**Comment by jgfouca** [comment]
@worleyph , I'm the correct assignee. I will take a look at this.

**Comment by worleyph** [comment]
@jgfouca , were you able to reproduce this issue? is it still to be addressed? Thanks.

**Comment by jgfouca** [comment]
@worleyph , I'm currently taking another pass at the build system. I will make sure to keep this issue in mind.
