### ISSUE TITLE
double free or corruption for two tests on Summit with GCC/9.1.0

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/E3SM#4498]
The error message is "1: 4: double free or corruption (out)" for two tests:

- PET_Ln9_PS.ne30pg2_EC30to60E2r2.WCYCL1850.summit
- SMS_P12x2.ne4_oQU240.A_WCYCL1850.summit

**Comment by amametjanov** [comment]
Haven't seen this error in recent runs. Closing.
