### ISSUE TITLE
Maintenance with data files in inputdata at NERSC

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4505]
With new machines at NERSC, they do not want to propagate the soft-link to /project. We currently have many files in `/global/cfs/cdirs/e3sm/inputdata` that are pointing to `/project/projectdirs/ccsm/inputdata`. Therefore, on a new machine, would not be able to access. We could:

a) change all of the soft-links that point to `/project` to instead point to `/global` -- ie still pointing to same file in ccsm directory (ie `/global/cfs/cdirs/ccsm/inputdata`) -- no real change. If we do this option, should we try to do it ourselves or ask if admins can help?

b) remove all of the files that are soft-linked, let new E3SM cases download as needed

c) Create a new clean inputdata directory for a new machine

d) something else

@bishtgautam points out "If we do remove the soft links, we should (1) copy all the data that would be removed by soft link, and (2) let folks know that we will be doing this because it is possible few of the ongoing runs would fail."

@rljacob notes "There’s a possibility NERSC might get CESM users and we want them downloading new files to `/global/cfs/cdirs/ccsm1`"

**Comment by rljacob** [comment]
We should try to do a.

**Comment by ndkeen** [comment]
OK, I did ask NERSC and they did not want to tackle it.  I will try.

**Comment by rljacob** [comment]
If a is to much of a pain, lets do b.  But don't copy all the data that the links used to point to.  Let check_input_data download what's missing and needed.

**Comment by ndkeen** [comment]
Going thru all files in `/global/cfs/cdirs/e3sm/inputdata`, I count 76821 files, and 24220 soft-links.
24160 of those links are pointing to a location in `/project/projectdirs/ccsm1/inputdata`.
If I were to unlink all of those, and make a hard-copy, it would create an additional 3.1 TB of space.

Here is a shell script that could do just that:
`/global/cfs/cdirs/e3sm/inputdata/suggested-actions.sh`

We could:
a) go for it -- note this action not easy to undo
b) do in steps (for example, lnd, cpl, atm one at a time)
c) consider simply unlinking the files and NOT making the copy -- if a case needs it, will copy
d) instead of unlinking and copying, create a new symbolic link to the same file but in the cfs location (ie not project)
e) for Perlmutter and beyond, start fresh with a new inputdata location -- for example `/global/cfs/cdirs/inputdata` -- and let cases populate as needed -- this means having 2 copies of inputdata until we go with just one official.
e) something else

**Comment by ndkeen** [comment]
I went ahead and did (a).  Will close.

I saved the shell scripts used to do the relinks (unlink/link):

```
cori05% pwd
/global/cfs/cdirs/e3sm/inputdata/relink-nov-2021
cori05% ls -l
total 7858
drwxrwsr-x+  2 ndk e3sm    4096 Nov 12 15:49 ./
drwxrwsr-x+ 22 ndk e3sm   16384 Nov 12 15:32 ../
-rwxr-xr-x+  1 ndk e3sm  148707 Nov 12 15:49 suggested-actions-amwg_data.csh*
-rwxr-xr-x+  1 ndk e3sm 4083620 Nov 12 15:49 suggested-actions-atm.csh*
-rwxr-xr-x+  1 ndk e3sm  533562 Nov 12 15:49 suggested-actions-ccsm4_init.csh*
-rwxr-xr-x+  1 ndk e3sm  122427 Nov 12 15:49 suggested-actions-cpl.csh*
-rwxr-xr-x+  1 ndk e3sm    7951 Nov 12 15:49 suggested-actions-glc.csh*
-rwxr-xr-x+  1 ndk e3sm 2080300 Nov 12 15:49 suggested-actions-iac.csh*
-rwxr-xr-x+  1 ndk e3sm   37253 Nov 12 15:49 suggested-actions-ice.csh*
-rwxr-xr-x+  1 ndk e3sm  613784 Nov 12 15:49 suggested-actions-lnd.csh*
-rwxr-xr-x+  1 ndk e3sm  263182 Nov 12 15:49 suggested-actions-ocn.csh*
-rwxr-xr-x+  1 ndk e3sm     868 Nov 12 15:49 suggested-actions-rof.csh*
-rwxr-xr-x+  1 ndk e3sm   27412 Nov 12 15:49 suggested-actions-share.csh*
-rwxr-xr-x+  1 ndk e3sm     844 Nov 12 15:49 suggested-actions-validation.csh*
```
