### ISSUE TITLE
Recent change in land surface input data file (fsurdat)

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/E3SM#4534]
The default land surface input data file (`fsurdat`) for Water Cycle WCYCL20TR compset has changed recently. My tests are under

`/lcrc/group/e3sm/ac.golaz/E3SMv2/v2.LR.historical_0101_test`

Old file

`fsurdat = '/lcrc/group/e3sm/data/inputdata/lnd/clm2/surfdata_map/surfdata_ne30np4.pg2_simyr1850_c201210.nc'`

New file

`fsurdat = '/lcrc/group/e3sm/data/inputdata/lnd/clm2/surfdata_map/surfdata_ne30pg2_simyr1850_c210402.nc'`

As a result of this change, run_e3sm scripts used for the historical simulations of the Water Cycle v2.LR fail with current version of master with the following error (**tests_01** and **tests_02**):

 ```
ERROR: Initial conditions file (finidat) was generated from a different surface
  dataset
 than the one being used for the current simulation (fsurdat).
 Current fsurdat: surfdata_ne30pg2_simyr1850_c210402.nc
 Surface dataset used to generate initial conditions file: 
 surfdata_ne30np4.pg2_simyr1850_c201210.nc
 
 Possible solutions to this problem:
 (1) Make sure you are using the correct surface dataset and initial conditions 
 file
 (2) If you generated the surface dataset and/or initial conditions file yoursel
 f, then you may need to manually change the surface_dataset global attribute o
 n the
     initial conditions file (e.g., using ncatted)
 (3) If you are confident that you are using the correct surface dataset and ini
 tial conditions file,
     yet are still experiencing this error, then you can bypass this check by se
 tting:
       check_finidat_fsurdat_consistency = .false.
     in user_nl_elm
```

Adding 

`check_finidat_fsurdat_consistency = .false.`

to the run script does work and produces BFB results with the original simulations (**tests_03**)

Alternatively, specifying the old file works as well

`fsurdat = '/lcrc/group/e3sm/data/inputdata/lnd/clm2/surfdata_map/surfdata_ne30np4.pg2_simyr1850_c201210.nc'`

and is also BFB (**tests_04**).

Since results can be recovered, this is a **minor issue**. But it would be useful if anyone could explain what happened and the motivation for the change? Also, should we then make

`check_finidat_fsurdat_consistency = .false.`

a default setting (which is slightly uncomfortable).

Thanks!

**Comment by rljacob** [comment]
That change was in PR #4445.  @jonbob and @stephenprice, why was that file changed?

**Comment by rljacob** [comment]
@golaz if you're doing 20TR, shouldn't fsurdat be a pg2 version of: lnd/clm2/surfdata_map/surfdata_ne30np4_simyr1850_2015_c171018.nc ?

**Comment by jonbob** [comment]
@golaz - the new file was added to include elevation class information necessary for runs that include an active glc model, but it was otherwise supposed to be exactly the same. I did check that the results were BFB before we merged this PR, but didn't check with the run script. The hope was that any cryo simulations with active glc could use the same file that Water Cycle does, as well as to start including elevation class information in all new fsurdat files as we start trying to support MALI. I would worry about potential differences creeping in if we had two different fsurdat files for every resolution, but we can look at ways to point at the old file for WC configurations and the new one for cryo if we need to.

**Comment by golaz** [comment]
@jonbob : thank you for the explanation. This makes perfect sense now. 

The consistency check fails for newer v2 Water Cycle simulations that are branched from the piControl simulation because that one was run using the old fsurdat and that information is kept in the metadata of the restart file.

The simplest solution is then to just add

`check_finidat_fsurdat_consistency = .false.`

when needed.

We can close this.

**Comment by jonbob** [comment]
Thanks @golaz - I'm glad that makes sense and you're OK with using the new file

**Comment by golaz** [comment]
> @golaz if you're doing 20TR, shouldn't fsurdat be a pg2 version of: lnd/clm2/surfdata_map/surfdata_ne30np4_simyr1850_2015_c171018.nc ?

@rljacob : this is always very confusing to me. My understanding is that we are OK because the time varying componet comes from the LULC. But I could be mistaken.

**Comment by rljacob** [comment]
I'll note that the production test suite does initial runs so didn't see any issues.
