### ISSUE TITLE
atm_nbfb tests need reworked after switching to using new F2010 with mpassi

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#4540]
Currently atm_nbfb tests contain three tests running on chrysalis
```
PGN_P1x1.ne4_oQU240.F2010.chrysalis_intel
TSC.ne4_oQU240.F2010.chrysalis_intel 
MVK_PS.ne4_oQU240.F2010.chrysalis_intel
```
Previously the tests used ne4_ne4.FC5AV1C-L. 
After switching to F2010,  a new surfdata map (fsurdat) for simyr2010 is required, which is created and added via PR #4488.  Since the new F2010 uses mpassi for prescribed data ice, the grid needs to use mpas ocean/ice mask -- and oQU240 is chosen to go with ne4.  In addition, new mpas sea-ice partition files are needed for the MVK_PS and TSC tests. 

While the MVK_PS test passed with the new fsurdat and graph files, the other two tests failed due to how the tests were initialized: the tests were controlled by pgn.py and tsc.py, which are hardwired to use initial conditions from a customized run using FC5AV1C-04P2 on ne4_ne4 grid with a simyr2000 surface data map. This leads to significant mismatch of PFT weights between the surfdata map (fsurdat) and the initial condition file (finidat).

To rework, if introducing a new finidat (via spin-up run with F2010 on ne4_oQU240), changes must be made to pgn.py and tsc.py, via a PR to CIME. Alternatively, an elm testmod may be introduced to specify a new finidat (or null) in user_nl_elm to override the settings in pgn_py or tsc.py.  It is being tested if the elm testmod approach would work.

@singhbalwinder , @rljacob , please chime in.
We cannot simply switch to using F2010-CICE and ne4_ne4, because it would still encounter mismatches due to how the current setting initialize the tests.

Are these tests sensitive to what initial conditions are used? Does it matter using a null finidat?

**Comment by wlin7** [comment]
Use an elm testmod to specify an alternative finidat (tested with an empty one) does not work. It would still be overridden by the one specified via tsc.py/pgn.py, ne4_v1_init/b58d55680/SMS_Ly5.ne4_ne4.FC5AV1C-04P2.eos_intel.ne45y.clm2.r.0002-01-01-00000.nc, when the batch job is executed.

**Comment by rljacob** [comment]
We'll have to make new initial condition files and edit tsc.py an pgn.py to use them.

**Comment by wlin7** [comment]
Yes, Rob, we need that to truly test F2010 with mpassi with mpas ocean/ice mask. @singhbalwinder made a 5-year run with v1 to facilitate these tests. I am going to mirror that effort using F2010 on ne4_oQU240, and make the changes in tsc.py and pgn.py accordingly.

**Comment by wlin7** [comment]
Completed 5-year simulation with F2010 on ne4_oQU240.
Monthly eam.i files copied to /lcrc/group/e3sm/data/inputdata/atm/cam/inic/homme/ne4_v2_init
Monthly elm.r files copied to /lcrc/group/e3sm/data/inputdata/lnd/clm2/initdata/ne4_oQU240_v2_init

**Comment by wlin7** [comment]
PGN and TSC tests can run ok when these ICs and corresponding changes to pgn.py/tsc.py.

@singhbalwinder , @rljacob , does CESM do these tests? If so and using the  ne4_v1_init version of ICs, I would need to have the logic in the py files to support both.

**Comment by singhbalwinder** [comment]
I don't think CESM use these tests but @rljacob might know more about it.

**Comment by rljacob** [comment]
No CESM doesn't use those tests.

**Comment by wlin7** [comment]
That is good. Thanks. I am going to put in the PR right away.

**Comment by wlin7** [comment]
@rljacob , @singhbalwinder , I requested you both for a review of cime PR [#4092](https://github.com/ESMCI/cime/pull/4092). Thanks.
