### ISSUE TITLE
memory leak for ERP_Ld3.ne4_oQU240.F2010

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#4546]
A memory leak is being reported on some machine for ERP_Ld3.ne4_oQU240.F2010.

The leak started after the test was changed in PR #4488.  It went from
ERP_Ln9.ne4_ne4.FC5AV1C-L 
longname: 2000_EAM%AV1C-L_ELM%SPBC_CICE%PRES_DOCN%DOM_SROF_SGLC_SWAV

to

ERP_Ld3.ne4_oQU240.F2010
longname: 2010_EAM%CMIP6_ELM%SPBC_MPASSI%PRES_DOCN%DOM_MOSART_SGLC_SWAV

The message in TestStatus is something like:
2021-09-18 04:18:16: memleak detected, memory went from 5680.520000 to 6473.240000 in 1 days

Machines with memory leak:
mappy, gnu 8.1.0
cori-knl, intel 19.0.3
cori-haswell, intel 19.0.3
theta, intel 19.1.0

Machines without leak:
chrysalis, intel 20.0.4
anvil, intel 20.0.4
compy, pgi 19.10
compy, intel 19.0.5
ascent, gnu 8.1.1
ascent, xlf 16.1.1

**Comment by rljacob** [comment]
<p data-renderer-start-pos="1" style="margin: 0px; padding: 0px; font-size: 14px; line-height: 1.714; font-weight: 400; letter-spacing: -0.005em; color: rgb(23, 43, 77); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 251, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I ran a 20-day test on anvil with mpassi on its own set of pes and INFO_MPROF=1 so we get memory output for every ROOTPE. The output shows this:</p><p data-renderer-start-pos="147" style="margin: 0.75rem 0px 0px; padding: 0px; font-size: 14px; line-height: 1.714; font-weight: 400; letter-spacing: -0.005em; color: rgb(23, 43, 77); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 251, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Resident memory size:</p><div class="pm-table-container  sc-cqPOvA kdnXmt" data-layout="default" style="margin: 0px auto 16px; padding: 0px; position: relative; box-sizing: border-box; z-index: 0; transition: all 0.1s linear 0s; display: flex; clear: both; color: rgb(23, 43, 77); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 251, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: inherit;"><div class="pm-table-wrapper" style="margin: 0px; padding: 0px; overflow-x: auto;">

ROOTPE | comps | RSS day1 | RSS day2 | RSS day20
-- | -- | -- | -- | --
0 | cpl, atm | 744.578 | 779.293 | 858.012
108 | lnd, ocn, rof | 247.691 | 253.754 | 331.004
144 | ice | 322.328 | 323.141 | 342.570

</div></div>

**Comment by singhbalwinder** [comment]
May be we should try SMS and ERS to see if we get a memory leak there as well. If it is just ERP, there might be something to do with the threading.

**Comment by rljacob** [comment]
It also possibly related to the compiler version since intel 19 has it but not intel 20.

**Comment by rljacob** [comment]
More from @jonbob 
On cori if I move mpassi off to its own processor set, the test still fails and is complaining about memory on the nodes with cpl/atm/lnd/ocn/rof – so I don’t believe this is related to a memory leak in mpassi. I can put each component on its own pes and try to see which one is causing trouble?

OK, I moved lnd/rof/ocn off to another set of pes and the test still fails, pointing at a rootpe that only has cpl and atm. So if there is a memory leak, it would be with one of those two components?

For what it’s worth, the failing test on cori is pointing at the memory highwater when it complains. It does grow on cori but not on anvil, so I’m confused… The versions of intel are different, but not that much – cori has intel/19.0.3.199 and anvil uses intel/20.0.4

**Comment by rljacob** [comment]
Another test from @jonbob 
"Could it be that EAM has a leak related to the prescribed seaice data? Going from seaice on ne4 to oQU240 means going from 866 horizontal points to 7153

ERP_Ld3.ne4_oQU480.F2010.cori-knl_intel fails as well. Trying now with ne4pg2 – unless there’s a reason we want ne4 instead

ERP_Ld3.ne4pg2_oQU480.F2010.cori-knl_intel also fails, so there goes that idea"

**Comment by jonbob** [comment]
@singhbalwinder - I ran an ERS test on cori but it had similar results. But it also defaulted to running threaded, so I'll try to turn threading off and try again

**Comment by jonbob** [comment]
@rljacob - I'll try on compy, since it also has intel19 support. At least that may help resolve the question of compiler version

**Comment by singhbalwinder** [comment]
Thanks @jonbob . Is it reproducible with an SMS test? If yes, it may be easier to reproduce/debug.

**Comment by jonbob** [comment]
Note that the ERS tests don't fail the memory test, just say there's insufficient data. But the memory high-water changes are consistent with the ERP test results

**Comment by rljacob** [comment]
Another thing to try: go back to master before PR #4488 and see if ERP_Ld3.ne4_ne4.FC5AV1C-L has a memory leak on cori (running the old test for 3 days instead of 9 steps).
The results are implying that it's in the atmosphere.  If that test passes, we have to look at what code is being activated for 2000_EAM%AV1C-L vs. 2010_EAM%CMIP6

**Comment by rljacob** [comment]
Actually the results are more strongly indicating its a compiler bug and we should just upgrade the compilers.

**Comment by jonbob** [comment]
On compy using intel 19.0.5, the ERP memory leak test passes

**Comment by jonbob** [comment]
The SMS test doesn't show the memory leak, which is a bit confusing until I looked closer at the cpl logs. I think the issue isn't a memory leak per se but an I/O issue because of how the test is constructed. Running ERP or ERS for 3 days means the model will drop restart files at the end of the second day -- so the memory highwater is actually catching any memory used for restart output. Usually the memory leak test throws out the last day, probably to avoid measuring all the I/O finalization.

**Comment by rljacob** [comment]
I like that explanation but why don't all the 3 day ERP tests have a false memory leak?

**Comment by jonbob** [comment]
I like it too, but that is the obvious question. Unless some of the platforms and/or compilers are impacted differently by the restart output? But that's not something I have much knowledge of

**Comment by jonbob** [comment]
I'm trying a full-length ERS test on cori, just to see what that does

**Comment by jonbob** [comment]
Somehow the full-length ERS test passes the memleak, even though the memory highwater goes from 4743.46 to 5241.42 between days  5 and 6 (or 6 and 7, depending on how you count) when it writes the restart files. I would have expected that to cause it to fail, since the memory increase is more than 10%?

**Comment by jonbob** [comment]
And nothing in TestStatus.log about memory, so I'm a bit confused

**Comment by rljacob** [comment]
@amametjanov do you know if some tests have memory leak on and other's don't?

**Comment by jonbob** [comment]
env_test.xml does have a value for the tolerance:
````
    <entry id="TEST_MEMLEAK_TOLERANCE" value="0.10">
      <type>real</type>
      <desc>Expected relative memory usage growth for test</desc>
    </entry>

**Comment by jonbob** [comment]
Unless it does the memleak test on the second run, in which case it wouldn't find an issue. I guess for the ERP_Ld3 the second run wouldn't be long enough for a memory comparison and it's possible it then uses the first run? But I'm not sure how much logic is build into that part of the testing system. Let me try one final run, a full-length ERP test

**Comment by amametjanov** [comment]
All tests have memleak checking: default tolerance is 10%. A machine-specific value for `TEST_MEMLEAK_TOLERANCE` can be set in config_machines.xml.
I think the mem-highwater increase in the initial run of ERP is due to PIO_ROOT=0 and CPL_ROOTPE=0. A workaround is to add a testmod:
```
$ cat cime_config/testmods_dirs/allactive/pioroot1/shell_commands 
./xmlchange PIO_ROOT=1
```

**Comment by jonbob** [comment]
My longer ERP run also fails the memleak check, but I think I have an explanation. It's still looking at the cpl log from the first run because the second one is done in a different subdirectory -- so it does see the impact from the restart output. The ERS does both runs in the same directory, so it makes (some) sense that the testing picks the most recent cpl log to look at for a memory leak, which does not have the restart write.

**Comment by jonbob** [comment]
Thanks for the idea @amametjanov. The test does pass if I make the PIO_ROOT 1 for all components. Out of curiosity I ran some tests with PIO_ROOT 1 for all components but 0 for 1. So far it fails when ELM has PIO_ROOT=0, but I'll keep testing. @rljacob - I can try the older version as you suggested and just confirm that this issue is not something new.

**Comment by jonbob** [comment]
Also fails if PIO_ROOT=0 for EAM

**Comment by jonbob** [comment]
If I set PIO_ROOT=0 for ELM or EAM, the memory test fails (with all other components using PIO_ROOT=1). If cpl, ocn, or ice is the only component using PIO_ROOT=0, the test passes

**Comment by jonbob** [comment]
@rljacob - using master from 9/10/2021, ERP_Ld3.ne4_ne4.FC5AV1C-L.cori-knl_intel fails the memory test. So whatever problem this is, it was not introduced in the last few weeks

**Comment by jedwards4b** [comment]
If there is a mem leak you should be able to see it in an SMS test of sufficient length but instead of relying on the test you should inspect the coupler logs.  
Look for lines like
```
memory_write: model date =   20191114       0 memory =   66044.02 MB (highwater)        542.60 MB (usage)  (pe=    0 comps= cpl ATM LND GLC ESP)
```
and watch for growth in the memusage field (542.60 in this example).   You may need to change the PE layout to match that of the ERP test, for example if the problem is threading.

**Comment by jonbob** [comment]
Thanks @jedwards4b . As far as I can tell, the memory jump just comes from writing restart files, so an SMS test probably wouldn't catch it. I don't know if the jump is indicative of a leak or simply more usage for I/O (or just I)

**Comment by jedwards4b** [comment]
That could be the issue - the memory leak test is little faulty in that regard.  You can modify the SMS test to turn on high frequency output then run for a month just to be sure.  Once you've read in the data and written the first output you should expect the memory usage to stabilize.

**Comment by jonbob** [comment]
Thanks again @jedwards4b . I'll check with Rob and see if he's that concerned. My sense if that since this is the only test that fails the memleak check, it's simply capturing the restart write usage inadvertently. But it's Rob's call. Thanks for weighing in

**Comment by jonbob** [comment]
@rljacob - what do you want to do with this issue? I think my tests show that the memory leak is caused by highwater memory during the writing of restart files, particularly by ELM or EAM. I don't know if this is due to something in PIO or those components, or something about the platforms/compilers?

**Comment by rljacob** [comment]
@dqwu that is unrelated to the memory leak issue and is a problem with the GCE MPI library:  "MPAS has requested an MPI threading level of MPI_THREAD_MULTIPLE, but this is not supported by the MPI implementation;"

**Comment by dqwu** [comment]
@jonbob Do you know if MPAS code ever calls MPI_Abort with error code 1734831948 in some cases?
This error code is also mentioned in https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?t=8347

**Comment by jonbob** [comment]
@rljacob - what about changing the test to ERP_Ln18.ne4_oQU240.F2010 until we figure out the compiler memory dependence? It seems like running 18-steps will allow MOSART to fit in but running for a shorter amount of time will keep the memory checker from causing issues. I tested it on compy and got this:
````
PASS ERP_Ln18.ne4_oQU240.F2010.compy_intel CREATE_NEWCASE
PASS ERP_Ln18.ne4_oQU240.F2010.compy_intel XML
PASS ERP_Ln18.ne4_oQU240.F2010.compy_intel SETUP
PASS ERP_Ln18.ne4_oQU240.F2010.compy_intel SHAREDLIB_BUILD time=376
PASS ERP_Ln18.ne4_oQU240.F2010.compy_intel MODEL_BUILD time=1018
PASS ERP_Ln18.ne4_oQU240.F2010.compy_intel SUBMIT
PASS ERP_Ln18.ne4_oQU240.F2010.compy_intel RUN time=82
PASS ERP_Ln18.ne4_oQU240.F2010.compy_intel COMPARE_base_rest
PASS ERP_Ln18.ne4_oQU240.F2010.compy_intel MEMLEAK insuffiencient data for memleak test
PASS ERP_Ln18.ne4_oQU240.F2010.compy_intel SHORT_TERM_ARCHIVER
````

**Comment by rljacob** [comment]
Yes that's worth trying.  Ask Wade to try it on mappy to make sure.
