### ISSUE TITLE
Error at Setup on Cori after NERSC installed new default cmake version

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4548]
On Sep 21, NERSC updated default cmake version. The old version (that we were using) is still there, however, a module warning now appears of that it used. If CIME detects a warning/error from a module command, it will fail. This can be turned off (using allow_error=true) and I tested that. However, in this case, it seems easy enough to simply update cmake version just to avoid this.

`ndk/machinefiles/cori-update-cmake`

**Comment by ndkeen** [comment]
That is the name of a branch

**Comment by jingtao-lbl** [comment]
Change cmake version in ./cime_config/machines/config_machines.xml

**Comment by jingtao-lbl** [comment]
> Hi @ndkeen How do I update cmake version on my NERSC end? I don't understand what you mean by ndk/machinefiles/cori-update-cmake. Either, where can I add the allow_error flag to avoid the warning? I'd very much appreciate if you can give more details about the solutions.

@meng630 Change cmake version in ./cime_config/machines/config_machines.xml

**Comment by meng630** [comment]
Thank you all. My problem solved ^^
