### ISSUE TITLE
Create S/M/L load-balanced PE-layouts for high-res physgrid (ne120np4.pg2) WC-cases on Cori-KNL

### ISSUE THREAD

**Issue by amametjanov** [E3SM-Project/E3SM#4568]
Physgrid (pg2) is now default in low-resolution WC runs. High-resolution WC-compset was recently added in E3SM-Project/E3SM#4551. Previous PE-layouts for ne120np4 need to be adjusted to account for pg2: e.g. for V1-vs-V2 benchmarking comparison.

**Comment by ndkeen** [comment]
Finally getting to this. I have `ndk/machinefiles/cori-knl-pe-layouts-ne120pg2`

I decided to keep 2 different sets for MPASSI and CICE. I kept the same node counts, but needed to use fewer MPI's per node for the MPASSI layouts as it requires more memory.

Using simple 5-day SMS test which doesn't include IO, here are estimated SYPD:
   
```
      Nodes   CICE   MPASSI
T     43      .32    .29
S     85      .55    .52
M    169     1.0     .84
L    338     1.6     1.4
X   1024     2.4     2.2
```    

For the X size, recall there is 50% discount on cori for jobs with node counts at or above 1024.

We could slightly improve the MPASSI layouts if we generated more MPAS ICE partition files.
