### ISSUE TITLE
Cosine solar zenith angle forcing is off by a time-step in data models

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#4575]
Originally reported in https://github.com/ESMCI/cime/issues/3380

"From some analysis by Sean Swenson, we see that the cosine solar zenith angle forcing is off by a time-step. See the PPT file attached.

I think the problem is in shr_tInterpMod.F90 in shr_tInterp_getAvgCosz, where a time update happens and then the solar-zenith angle is calculated. I think that should be reversed the solar zenith angle is calculated and then the time-update happens.

This affects CLM standalone simulations for all forcing types (I compsets). But, also CORE_IAF and CORE2_IAF forcing (JRA and IAF C and G compsets as well as the DIAF compset)."

Issue was moved to https://github.com/ESCOMP/CDEPS/issues/120 and there's a fix in https://github.com/ESCOMP/CDEPS/pull/123

**Comment by rljacob** [comment]
@jonbob , @bishtgautam  See above and let me know if we need this fix.

**Comment by jonbob** [comment]
@rljacob - I do think we want this fix. I'm not sure if it's worth a lot of digging in to look at cosz every hour, if they've already tested it. I can run one-year G-cases to make sure nothing unexpected happens

**Comment by proteanplanet** [comment]
Yes, we definitely want to fix this.

**Comment by jonbob** [comment]
OK, I have a branch with it implemented -- I'll make a PR. I also have a 12 year test of a T62_EC30to60E2r2 G-case and will run mpas-analysis on the output
