### ISSUE TITLE
Why does it take so long to rebuild e3sm.exe?

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/E3SM#4624]
I'm curious if someone can explain to me the following. 

On chrysalis (probably on other machines as well), rebuilding the executable (no change, except a PE layout change) takes basically as long as building the executable in the first place.

```
cd /lcrc/group/e3sm/ac.golaz/E3SMv2/v2.LR.piClim-histaer_0021/build
ls --full-time e3sm.bldlog*
-rw-r--r-- 1 ac.golaz E3SM 258373 2021-10-27 11:50:49.000000000 -0500 e3sm.bldlog.211027-113523.gz
-rw-r--r-- 1 ac.golaz E3SM 237360 2021-10-27 12:09:40.000000000 -0500 e3sm.bldlog.211027-115540.gz
```
First build: 15 min 26 s (926 s)
Second build: 14 min 0 s (840 s)
**Saving: 9.3 %**

**Comment by jgfouca** [comment]
@golaz , a pelayout change forces a re-setup and full rebuild. The CIME case control system is not smart enough to distinguish between pelayout changes that could impact the build and those that cannot, so it has to assume a rebuild is needed. If this a feature that you'd like to see in CIME, please file a ticket here: https://github.com/ESMCI/cime/issues
