### ISSUE TITLE
PGN test not configured for V2

### ISSUE THREAD

**Issue by mt5555** [E3SM-Project/E3SM#4648]
Trying to run the PGN test with V2 results in configure errors with missing data sets.  This test case appears to rely on data that needs to exist in the clm2/initdata/"gridname"_v2_init/ directory.   This data only exists for v1, and the ne4_ne4 grid, running with the FC5AV1C-04P2 compset.   It looks like new data needs to be generated for v2, and for a v2 supported compset.  Instead of ne4_ne4, it might be better to use ne4_oQU240, to allow for the eventual use of F compsets using MPAS-I.  

As this test only runs for 1 timestep, why not use ne30?

Example:
```
./create_test PGN_P24x1.ne4_oQU240.F2010-CICE -q small -g -b master --baseline-root ~/scratch1/baselines/intel
...

        wget failed with output:  and errput --2021-11-08 17:18:30--  https://web.lcrc.anl.gov/public/e3sm/inputdata/lnd/clm2/initdata/ne4_oQU240_v2_init/20210915.v2.ne4_oQU240.F2010.elm.r.0002-06-01-00000.nc
```

**Comment by wlin7** [comment]
Same with the MVK test. The required input files are available on anvil/chrysalis' inputdata path, but was not on the INPUTDATA server. It is now copied over.

The data was produced for the atm_nbfb tests (PGN_P1x1 and TSC). Test with F2010 should also work.

**Comment by mt5555** [comment]
I've been using compy.  I'm running these tests directly, to learn about them for use evaluating new features.

It seems a good idea if this data was in the input data server, rather than only on chrysalis.

**Comment by mt5555** [comment]
An additional issue with this test:
The buildnml code, which collects the list of all files, only knows about the elm.r and eam.i files for the first instance, which ./case.submit will download.  But there is one unique file for each ensemble member, and the others will not be downloaded.

The CIME feature which constructs the different ensemble namelists should be modified to add each different ncdata/finidat to the Buildnml input data lists.

**Comment by singhbalwinder** [comment]
I noticed this issue and reported it to [here](https://github.com/ESMCI/cime/issues/2822). I thought it was resolved by CIME but I didn't check after that. It was fixed by [this commit](https://github.com/ESMCI/cime/commit/6511798d732888681e4c4125ba19c2a745ac48d0) but I am not sure if it is broken again.

**Comment by mt5555** [comment]
from that PR:  

"but requires a change in each external component to only delete the input_data_list file prior to the first instance and append with each instance."

we might need to make this change to the e3sm components?

**Comment by mt5555** [comment]
here's a patch for eam.  does this look correct?

```
diff --git a/components/eam/cime_config/buildnml b/components/eam/cime_config/buildnml
index 6ecb992..d1fd272 100755
--- a/components/eam/cime_config/buildnml
+++ b/components/eam/cime_config/buildnml
@@ -130,7 +130,6 @@ def buildnml(case, caseroot, compname):
         # -----------------------------------------------------
         # determine instance string
         # -----------------------------------------------------
-
         inst_string = ""
         if ninst_atm > 1:
             inst_string = "_{0:04d}".format(inst_counter)
@@ -202,8 +201,9 @@ def buildnml(case, caseroot, compname):
         # call build-namelist
         # -----------------------------------------------------
 
-        if os.path.exists(os.path.join(casebuild, "eam.input_data_list")):
-            os.remove(os.path.join(casebuild, "eam.input_data_list"))
+        if inst_counter ==1:
+           if os.path.exists(os.path.join(casebuild, "eam.input_data_list")):
+              os.remove(os.path.join(casebuild, "eam.input_data_list"))
 
         cam_buildnml_cmd =  os.path.join(srcroot, "components/eam/bld/build-namelist")
         cam_buildnml_cmd += " -infile {}/cesm_namelist".format(eamconf_dir)
diff --git a/components/mpas-seaice/cime_config/buildnml b/components/mpas-seaice/cime_config/buildnml
index 486683f..f2d30e5 100755
--- a/components/mpas-seaice/cime_config/buildnml
+++ b/components/mpas-seaice/cime_config/buildnml
@@ -40,7 +40,7 @@ def buildnml(case, caseroot, compname):
     #ninst_ice       = case.get_value("NINST_ICE")
     ninst_ice        = 1 # Change if you want multiple instances... though this isn't coded yet.
     ninst_ice_real   = case.get_value("NINST_ICE")
-    ntasks_ice       = case.get_value("NTASKS_ICE")
+    ntasks_ice       = case.get_value("NTASKS_PER_INST_ICE")
     rundir           = case.get_value("RUNDIR")
     run_type         = case.get_value("RUN_TYPE")
     run_refcase      = case.get_value("RUN_REFCASE")
```

**Comment by singhbalwinder** [comment]
Thanks Mark! I haven't looked at this code recently but from the comment and the code changes, it looks right to me.

**Comment by mt5555** [comment]
for elm, looks like we only need this change:  

```
diff --git a/components/elm/cime_config/buildnml b/components/elm/cime_config/buildnml
index 46512f2..dd074ee 100755
--- a/components/elm/cime_config/buildnml
+++ b/components/elm/cime_config/buildnml
@@ -138,8 +138,9 @@ def buildnml(case, caseroot, compname):
         # create elmconf/namelist
         # -----------------------------------------------------
 
-        if os.path.exists("{}/Buildconf/elm.input_data_list".format(caseroot)):
-            os.remove("{}/Buildconf/elm.input_data_list".format(caseroot))
+        if inst_counter ==1:
+            if os.path.exists("{}/Buildconf/elm.input_data_list".format(caseroot)):
+                os.remove("{}/Buildconf/elm.input_data_list".format(caseroot))
 
         elmicfile = ""
         elm_startfile = ""
```

**Comment by singhbalwinder** [comment]
Yeah, it looks right to me. Thanks!

**Comment by rljacob** [comment]
Regarding the test data, for those following along, the inputdata/atm/cam/inic/homme/ne4_v2_init directory has data from an ne4_oQU240.F2010 case.

@mt5555 is that ok or should we use ne4pg2 ?

**Comment by singhbalwinder** [comment]
Ideally, this test should not depend on the model resolution. Due to time constraint, I originally chose `ne4` so that this test can use minimal number of nodes and runs fast. We can use ne30pg2 as well for this test (like @mt5555 mentioned earlier). If I recall correctly, this test launches 36 one time step simulations. It will be more costly than a simple 36 time step simulation as this test has to initialize each simulation as well. `ne30` initialization cost is not that much and we can now run `ne30` on a single node, so we can give it a try.

**Comment by mt5555** [comment]
PGN is the physics column growth test?  So it makes sense to me what @singhbalwinder said above (it doesn't depend on model resolution).  And ne4 will have more physics columns than ne4pg2, so seems like a good idea to stick with ne4.

In the latest master, this test ran 20 ensemble members.   With ne4_oQU240.F2010 I ran into memory problems with 24 cores per ensemble member, but it ran with 32 cores per member, for a total of 16 nodes, which is very reasonable.
