### ISSUE TITLE
Bug in components/elm/src/biogeochem/DryDepVelocity.F90

### ISSUE THREAD

**Issue by samjsilva91** [E3SM-Project/E3SM#4677]
A bug exists in the ozone dry deposition code in the calculation of stomatal resistances, carried over from CESM. 
Following Emmons et al ([2020, JAMES](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019MS001882)), the stomatal resistances for shaded and sunlit leaves should be added in parallel as opposed to in series.

This should be a relatively straightforward bug fix, instead of
Rs = fsun * Rsun + (1‐fsun) * Rsha, the correct formula is:

1/Rs = fsun * (1/Rssun) + (1‐fsun) * (1/Rssha)

The bug is on line 459 in components/elm/src/biogeochem/DryDepVelocity.F90:
https://github.com/E3SM-Project/E3SM/blob/4f29ad3f15044b68210ab846ccb167f89f40853a/components/elm/src/biogeochem/DryDepVelocity.F90#L459

**Comment by singhbalwinder** [comment]
Sam: I have rearranged the equation so that I can add it in the code. I know it is very simple rearrangement but would you please double check it and see if it looks right to you? Thanks!

```
1/Rs = fsun * (1/Rssun) + (1‐fsun) * (1/Rssha)
1 = fsun * (1/Rssun)*Rs + (1‐fsun) * (1/Rssha)*Rs
Rssun*Rssha = fsun * (Rssha)*Rs + (1‐fsun) * (Rssun)*Rs
(Rssun*Rssha)/(fsun * (Rssha)+ (1‐fsun) * (Rssun)) = Rs
Rs = (Rssun*Rssha)/(fsun * (Rssha)+ (1‐fsun) * (Rssun))
```

**Comment by tangq** [comment]
@samjsilva91 , which E3SM versions are affected by this bug? E3SMv1 and/or E3SMv2? How big is the impact? It is good to document such information here for future references if available. Thanks.

**Comment by samjsilva91** [comment]
Hi @singhbalwinder: 
that seems correct to me. I probably would have done the slightly more simple approach of:
```
1/Rs = fsun * (1/Rssun) + (1‐fsun) * (1/Rssha)
Rs = 1/(fsun * (1/Rssun) + (1‐fsun) * (1/Rssha))
```

@tangq: This bug exists as of the current Master branch. The impact is relatively small. I've done some sensitivity studies and as long as the ratio of the shaded to sunlit leaves is within a factor of two, the influence of the bug is limited. This is consistent with Emmons et al (2020) which states that the bug fix leads to a "slight increase in ozone dry deposition rates".

**Comment by tangq** [comment]
Thanks for the clarifications, @samjsilva91
