### ISSUE TITLE
AMD compiler on Spock - create_test test fails

### ISSUE THREAD

**Issue by grnydawn** [E3SM-Project/E3SM#4679]
All of the tests in e3sm_developer test suite are failed with AMD compiler on Spock.

The failures are related to linking to essential libraries such as stdlibc++ or openmp. Most common error message is captured below that is a part of PIO build log:

```
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /gpfs/alpine/cli133/proj-shared/grnydawn/e3sm_scratch/spock/ERP_Ld3.ne4_oQU240.F2010.spock_amd.20211129_095754_0m306a/bld/amd/mpich/nodebug/threads/mct/lib/libgptl.a(gptl.o): undefined reference to symbol 'omp_get_num_threads'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /opt/rocm-4.2.0/llvm/lib/libompstub.so: error adding symbols: DSO missing from command line
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [tools/spio_finfo/CMakeFiles/spio_finfo.exe.dir/build.make:186: tools/spio_finfo/spio_finfo.exe] Error 1
```

From further investigation, the same test (ERP_Ld3.ne4_oQU240.F2010) was successfully built and ran (with some manual work, noted below) when "create_newcase" script is used instead of "create_test". I captured the commands used for both scripts:

[success case with create_newcase]
```
${E3SM}/cime/scripts/create_newcase --case "${CASEDIR}" --res ne4_oQU240 --compset F2010 --machine spock --compiler amd --project cli133 --output-root "${OUTROOT}" --workflow default
```
NOTE: Still, I had to add the path to LIBSCI in LD_LIBRARY_PATH to run the case without the error of not finding the library.

[failed case with create_test]
```
${E3SM}/cime/scripts/create_test --test-root ${TESTROOT} ERP_Ld3.ne4_oQU240.F2010  --machine spock --compiler amd --project cli133
```

In addition to this issue, I had to define a macro CPRAMD and modify "/share/util/shr_infnan_mod.F90.in" source file to support the macro as shown below:

```
 ! Flag representing compiler support of Fortran 2003's
 ! ieee_arithmetic intrinsic module.
-#if defined CPRIBM || defined CPRPGI || defined CPRNVIDIA || defined CPRINTEL ||  defined CPRCRAY || defined CPRNAG
+#if defined CPRIBM || defined CPRPGI || defined CPRNVIDIA || defined CPRINTEL ||  defined CPRCRAY || defined CPRNAG || defined CPRAMD
 #define HAVE_IEEE_ARITHMETIC
 #endif
```

The test is done at the commit 7cf3e80380 at ykim/spock/amd branch.

**Comment by rljacob** [comment]
@jgfouca any reason the build would be different between create_newcase and create_test ?

**Comment by grnydawn** [comment]
@jgfouca , @rljacob , @sarats , Thanks for the recommendation. After changing my test from ERP to SMS, the issue did not happen, and the SMS test case was built and run without error.

Also, after adding "-fopenmp" to all compiling and linking options, I could build ERP test case too without error. However, running the ERP test case ends up with core dump though. Error message says something related to MPI_THREAD_MULTIPLE. But, I think this is a different issue.

I have one difficulty on setting a library path in a cmake file. I got an error of not finding LIBSCI library even though I added the following cmake statements. Do you have any suggestion on this issue?

```
if (compile_threaded)
  string(APPEND SLIBS " -L$ENV{LIBSCI_PATH} -lsci_amd_mp")
endif()
if (NOT compile_threaded)
  string(APPEND SLIBS " -L$ENV{LIBSCI_PATH} -lsci_amd")
endif()

set(LIBSCI_PATH "$ENV{CRAY_LIBSCI_PREFIX_DIR}")
```

Error message is below:
```
56: /gpfs/alpine/cli133/proj-shared/grnydawn/e3sm_scratch/spock/ERP_Ld3.ne4_oQU240.F2010.spock_amd.20211130_103107_jt5v1m/bld/e3sm.exe: error while loading shared libraries: libsci_amd_mp.so.5.0: cannot open shared object file: No such file or directory
```

**Comment by rljacob** [comment]
If you're trying to verify restart, try an ERS test.  That will not change the threading.

**Comment by grnydawn** [comment]
@rljacob I tried a ERS test (ERS.f09_g16.I1850ELMCN) and got an error at the last linking phase. It failed at locating an essential "libstdc++.so.6". Error message is below:

```
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /gpfs/alpine/cli133/proj-shared/grnydawn/e3sm_scratch/spock/ERS.f09_g16.I1850ELMCN.spock_amd.20211130_111101_4igl5b/bld/amd/mpich/nodebug/nothreads/mct/lib/libpioc.a(spio_io_summary.cpp.o): undefined reference to symbol '_ZSt20__throw_length_errorPKc@@GLIBCXX_3.4'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /opt/cray/pe/gcc-libs/libstdc++.so.6: error adding symbols: DSO missing from command line
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

I copied a part of the linker command. The command has only the library options that I specified in cmake shown below:

```
python3 ... /Tools/e3sm_compile_wrap.py  /opt/cray/pe/craype/2.7.11/bin/ftn ...
...
 -L -lsci_amd -L/opt/cray/pe/parallel-netcdf/1.12.1.7/lib -lpnetcdf -L/opt/cray/pe/parallel-netcdf/1.12.1.7/amd/4.3/lib -lpnetcdf -L/opt/cray/pe/mpich/8.1.8/ofi/amd/4.0/lib -lmpich
```
I wonder why the environmental variables specified by "module" commands in "config_machines.xml" are not applied to the linker command? Do I have to specify LD_LIBRARY_PATH in cmake like below?

```
set(LD_LIBRARY_PATH "$ENV{CRAY_LD_LIBRARY_PATH}")
```

**Comment by jgfouca** [comment]
@grnydawn , 

`libsci_amd_mp.so.5.0: cannot open shared object file` This is probably a LD_LIBRARY_PATH issue which needs to be set in the environment, not CMake. I would double-check the environment settings for your machine in config_machines.xml.

**Comment by grnydawn** [comment]
@jgfouca , I am suspicious on LD_LIBRARY_PATH too. On Spock, LD_LIBRARY_PATH is not set with paths to the loaded modules, but CRAY_LD_LIBRARY_PATH has the paths. I am not sure if this causes the above issue or not, but I asked sys admin of Spock if not setting LD_LIBRARY_PATH is something expected.

**Comment by grnydawn** [comment]
@jgfouca , after replacing a linker from flang to cxx linker (CC) in cmake, most of LD_LIBRARY issues are resolved. However, I still have one issue about a missing shared library (LIBSCI) during runtime. While I am working on this issue with ORNL team, I am trying to find a way to use cmake to embed the path to the LIBSCI library in to e3sm.exe using rpath. I tried the following cmake statements but seems not working. Could you suggest what is a proper way to use the rpath in cmake? Or do you have any other suggestion to embed LIBSCI path in e3sm.exe?

string(APPEND FFLAGS " -L${LIBSCI_PATH}/lib -Wl,-rpath=${LIBSCI_PATH}/lib -lsci_amd_mp")
string(APPEND SLIBS " -L${LIBSCI_PATH}/lib -Wl,-rpath=${LIBSCI_PATH}/lib -lsci_amd_mp")
string(APPEND LDFLAGS " -L${LIBSCI_PATH}/lib -Wl,-rpath=${LIBSCI_PATH}/lib -lsci_amd_mp")

**Comment by jgfouca** [comment]
@grnydawn , it looks like you are doing the right thing by trying to use rpath to tell the executable where to find shared libs. I would recommend confirming that the executable contains the rpath you want via this command:

```
objdump -x $your_e3sm_exe |grep RPATH
```

The other approach would be to manipulate the environment settings for spock in config_machines.xml to ensure LD_LIBRARY_PATH contains the path to the missing library.

**Comment by grnydawn** [comment]
@jgfouca , it seems that Cray compiler wrapper has an issue of imposing rpath in their compiler wrapper on Spock according to an ORNL staff. He verified that "CC" wrapper did not embed the path to LIBSCI. I will try your second suggestion on modifying LD_LIBRARY_PATH in config_machines.xml.

**Comment by grnydawn** [comment]
@jgfouca @rljacob @sarats, after modifying LD_LIBRARY_PATH in config_machines.xml, 32 test cases are passed out of 52 tests in e3sm_developer test suite with AMD compiler on Spock.

TOTAL: 52 test cases with AMD compiler on Spock

FAIL : 20
* build failures: 5
    -> unable to open MODULE files
* memory and pointer failures: 14
    -> Segmentation fault
    -> free(): invalid pointer
    -> double free or corruption
    -> malloc(): memory corruption
* job submission failures: 1

PASS : 32

 It is not clear whether these failures are from either source code, compiler, or something I did on LD_LIBRARY_PATH.

[amd_spock_config_failures.txt](https://github.com/E3SM-Project/E3SM/files/7763575/amd_spock_config_failures.txt)

**Comment by jgfouca** [comment]
@grnydawn , those failures look unrelated to library issues.

**Comment by jgfouca** [comment]
@grnydawn , I'm unassigning myself since the remaining fails look related to the typical struggles of porting E3SM to a new platform (getting the env and compilation flags correct, etc) and not any systemic problem with the build system or CIME.

**Comment by grnydawn** [comment]
This issue does not exist in newer E3SM release
