### ISSUE TITLE
AMIP compset doesn't support the NA RRM grid

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/E3SM#4745]
The North America (NA) RRM AMIP run is part of the E3SMv2 NA RRM CMIP6 simulations. I got errors when creating it on chrysalis .

`ERROR: grid alias northamericax4v1pg2_WC14to60E2r3 not valid for compset 20TR_EAM%CMIP6_ELM%SPBC_MPASSI%PRES_DOCN%DOM_MOSART_SGLC_SWAV_SIAC_SESP`

We need to add the AMIP compset support for the NA RRM grid.

**Comment by golaz** [comment]
@wlin7 : is this something you could help with?

**Comment by golaz** [comment]
Once the compset works, we will also need default PE layouts if we don't have them. Maybe @amametjanov can help with that.

**Comment by wlin7** [comment]
Sorry, @tangq , @golaz , I missed the email notification for this issue.

The fix is simple, just to enable this grid also for DOCN. Currently it is only used for coupled atm/lnd/MPASO.  
Testing on chrysalis.

**Comment by tangq** [comment]
Thanks, @wlin7 , for the fix. I have already created the run script for the RRM AMIP simulation. Once it passes your test and merged to the master, I can start the NARRM AMIP run.

**Comment by wlin7** [comment]
Addressed via #4783 .
