### ISSUE TITLE
cmake bug for compy in debug mode

### ISSUE THREAD

**Issue by beharrop** [E3SM-Project/E3SM#4746]
There seems to be a bug in [intel_compy.cmake](https://github.com/E3SM-Project/E3SM/blob/master/cime_config/machines/cmake_macros/intel_compy.cmake) when `DEBUG=TRUE` that appends `-checkd all` instead of `-check all` and causes the build to fail

**Comment by singhbalwinder** [comment]
I also saw that a few weeks back. There is a typo in `cime_config/machines/cmake_macros/intel_compy.cmake` file. I can take care of it.

**Comment by beharrop** [comment]
Thanks @singhbalwinder
