### ISSUE TITLE
FATES SatPhen test failing with GNU compiler

### ISSUE THREAD

**Issue by peterdschwartz** [E3SM-Project/E3SM#4755]
The new SMS_Ld30.f45_f45.IELMFATES.mappy_gnu.elm-fates_satphen (from PR #4669 ) test is failing.  I replicated it on chrysalis using the gnu compiler.  The FAIL goes away if optimizations are disabled.

@glemieux @rgknox

**Comment by glemieux** [comment]
I've got a couple tests queued up on Cori to try and replicate it.  Hopefully I'll have some insight into this soon.

**Comment by glemieux** [comment]
@peterdschwartz I can confirm I'm seeing a similar failure on Cori using the gnu compiler.  @rgknox I think I've figured out the issue.  I'll post a new issue on the fates repo once I have it nailed down.  It looks like it'll be all on the fates side, so maybe we can get it in with the next elm-fates API update.

**Comment by peterdschwartz** [comment]
@glemieux Can you verify that the cases on cori pass if you run them in debug mode?  We may be able to modify the test on mappy to use debug mode while waiting for the fates update so that the testing dashboard is clean.

**Comment by glemieux** [comment]
@peterdschwartz yes I'm seeing the same thing: if I run with the gnu compiler in debug the test will pass.
