### ISSUE TITLE
COMPARE fails on GCP with gnu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4768]
The following two tests fail compare on GCP. 

```
ERS.ne4_oQU240.F2010.gcp_gnu.eam-thetahy_ftype2
ERS_Ld3.ne4pg2_oQU480.F2010.gcp_gnu.eam-thetahy_sl_pg2_ftype0
```

**Comment by ambrad** [comment]
What is GCP?

**Comment by ndkeen** [comment]
GCP= google cloud platform

The DEBUG versions of those tests are passing.  

```
ERS_D.ne4_oQU240.F2010.gcp_gnu.eam-thetanh_ftype2
ERS_D_Ld3.ne4pg2_oQU480.F2010.gcp_gnu.eam-thetahy_sl_pg2_ftype0
```

**Comment by ambrad** [comment]
Is there an action item for those of us who are responsible for these tests? In particular, is there a means for an E3SM dev to get onto GCP and run and debug these tests? Thanks.

**Comment by ndkeen** [comment]
Yea, I can add any of us as a user (will add you) -- I just wanted to document the fails for now. Most tests do pass on the machine. It's currently using gnu v8.

**Comment by ndkeen** [comment]
These 2 tests are no longer failing on GCP. It's not clear which PR fixed the issue, but we've already updated the compiler versions a couple of times (should be using version 12 now).
