### ISSUE TITLE
Uninitialied ndropmix and nsource in ndrop.F90 caused a PIO fatal error 

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/E3SM#4782]
The variables "ndropmix" and "nsource" are not initialized in the ndrop.F90, so they may contain "NaN" that caused a PIO fatal error when they were dumped to cam history files. 

A possible solution is to add the following two lines code to initialize the variables before the overall_main_i_loop:

```
   ndropmix = 0._r8
   nsource = 0._r8

   ! overall_main_i_loop
   do i = 1, ncol
```

The error message is as follows. The compiler is gcc/9.3.0 with cray-mpich/8.1.11 on Miller. Thank @jayeshkrishna for pointing out the cause of the error. 
```
PIO: FATAL ERROR: Aborting... An error occured, Writing variables (number of variables = 78) to file (v2.LR.piControl.eam.h3.0001-01-01-00000.nc, ncid=125) using PIO_IOTYPE_PNETCDF iotype failed. Non blocking write for variable (NDROPMIX, varid=51) failed (Number of subarray requests/regions=1, Size of data local to this process = 777600). err=-60. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/autofs/nccs-svm1_home1/mxu/MyGit/e3sm_v2/externals/scorpio/src/clib/pio_darray_int.c: 391)
```

**Comment by singhbalwinder** [comment]
Thanks @minxu74 and @jayeshkrishna for catching this!
