### ISSUE TITLE
Runtime error with SMS_Ld30.f45_f45.IELMFATES.X_gnu.elm-fates_satphen

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4816]
Before and after upgrading to GNU v9 on cori (PR #4810), this test is hitting the error below on cori-knl, cori-haswell, and perlmutter -- I also see the same test fails on mappy with GNU.

```
SMS_Ld30.f45_f45.IELMFATES.cori-knl_gnu.elm-fates_satphen
SMS_Ld30.f45_f45.IELMFATES.cori-haswell_gnu.elm-fates_satphen
```

```
32:  in sub-canopy layer in leafc_from_treelai
32:  this is not set up to work for lower canopy layers.
32:  problem in leafc_from_treelai  1073741823          11
32:  ENDRUN:ERROR in /global/cscratch1/sd/ndk/wacmy/ndk_mf_cori-update-gnuv9/components/elm/src/external_models/fates/biogeochem/FatesAllometryMod.F90 at line 811                                                                                                                                                                                                   \

32:  ERROR: Unknown error submitted to shr_abort_abort.

```
On perlmutter, I tested with gnuv9 and gnuv10. With cori-knl, fails same way with gnu8 and gnu9.
This test already uses 1 thread.
With DEBUG, the test on cori-knl at least passes.  `SMS_D_Ld30.f45_f45.IELMFATES.cori-knl_gnu.elm-fates_satphen`

**Comment by glemieux** [comment]
This appears to be the same issue as #4755.  PR https://github.com/NGEET/fates/pull/838 is currently under going final testing to address this fix.  Note that this update is planned to come in with the next API update #4777.

**Comment by peterdschwartz** [comment]
This didn't close automatically when the PR was merged to master so closing now.

**Comment by rljacob** [comment]
The syntax to autoclose is very picky.  Has to be "Fixes #", one per line not "Fixes Issue #".
