### ISSUE TITLE
AMD compiler issues on Crusher: SOLVED in upcoming release

### ISSUE THREAD

**Issue by grnydawn** [E3SM-Project/E3SM#4874]
51 tests out of 56 cases are failed using AMD compiler (PrgEnv-amd/8.2.0 amd/4.5.0) on Crusher.
This test is done on ykim/crusher/amd branch.

* 5 failed cases: "F90-F-0000-Internal compiler error. make_lltype_from_sptr(), no incoming arguments"
    => This issue is resolved now with (PrgEnv-amd/8.3.3 amd/5.1.0)

* 13 failed cases: similar to "F90-F-0004-Unable to open MODULE file seq_infodata_mod.mod"
   => These errors seem to be related to the maximum length of the include path argument in compiler command line(details below)

* 33 failed cases: NO BUILD
   => Not sure, but these errors seem to be dependent on the previously failed cases

** issue similar to "F90-F-0004-Unable to open MODULE file seq_infodata_mod.mod"
   => This type of error happens when a source file is compiled with an include path to MCT modules whose command line argument length is long such as 237. However, a similar compilation was successful when the length is 225. From comparisons to other failed and successful cases, I found there exists consistency in failure and success cases according to the length.

**Comment by sarats** [comment]
Can we put together a small reproducer for the max include path issue? Perhaps a test just trying to include that module...

**Comment by grnydawn** [comment]
@sarats , I created a simple test case with two simple source files and a long directory path below.

This test confirms that the issue is related to amdflang, not ftn wrapper because using ftn does not change test result.

test.F90
===========
program testlongarg
    use testmod, only : x
    print *, "x = ", x
end program

testmod.F90
==============
module testmod
    real :: x
end module

Compilation PASS with 236-char include path
=======================================
amdflang -I/ccs/home/grnydawn/temp/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890 /ccs/home/grnydawn/temp/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890/testmod.o test.F90 -o test.exe

Compilation FAIL with 246-char include path
=======================================
amdflang -I/ccs/home/grnydawn/temp/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890/1234567890 /ccs/home/grnydawn/temp/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890/1234567890/testmod.o test.F90 -o test.exe
F90-F-0004-Unable to open MODULE file testmod.mod (test.F90: 3)
F90/x86-64 Linux Flang - 1.5 2017-05-01: compilation aborted

**Comment by dmcdougall** [comment]
Is there a `testmod.mod` file anywhere?  Does the file actually exist?  Does it exist and have the incorrect spelling or case?

**Comment by grnydawn** [comment]
@dmcdougall, yes, testmod.mod files exist in both directory paths pointed by -I flags in the two test cases. I pre-compiled testmod.F90 in the both directories so that each directory contains three files "testmod.F90, testmod.o and testmod.mod".

**Comment by sarats** [comment]
@dmcdougall Were you able to replicate this issue internally?

**Comment by arghdos** [comment]
I just tried this on Crusher using ROCm 5.1.0 and 4.5.0:

```
$ echo $(pwd)
/ccs/home/nicurtis/test/flang
]$ pth="$(pwd)/tmp/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890/1234567890/" 
$ mkdir -p $pth
]$ amdflang -c testmod.f90 -o $pth/testmod.o
$ amdflang -I $pth $pth/testmod.o test.F90 -o test.exe
$ echo ${#pth}
258
```

and wasn't able to repro.  Do you still observe it @grnydawn?  I am 100% not a Fortan expert, so I easily could be missing something here.

**Comment by grnydawn** [comment]
@arghdos , yes, I am still seeing the same error with rocm 5.1.0 and 4.5.0 on Crusher. I think that the different test outcome comes from the directory path where testmod.f90 is compiled. In your commands, "amdflang -c testmod.f90 -o $pth/testmod.o" creates testmod.o in $pth directory but it creates testmod.mod in the current working directory. Therefore, next amdflang command can find the MOD file in the current directory, not from the path pointed by $pth.

**Comment by arghdos** [comment]
Ok, got it:

```
echo $(pwd)
/ccs/home/<user>/test/flang
pth="$(pwd)/tmp/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890/1234567890/1234567890/" 
# cleanup
rm -rf $pth *.mod
mkdir -p $pth
cp testmod.f90 $pth
pushd $pth
amdflang -c testmod.f90 -o testmod.mod
popd
amdflang -I $pth $pth/testmod.mod test.F90 -o test.exe
echo ${#pth}
```

Reproduces, will open a ticket internally.

**Comment by arghdos** [comment]
Test case added here: https://github.com/ROCm-Developer-Tools/aomp/commit/b1fb2271f32d93f39bd7afebc8a5e7d914b904cb

**Comment by ronlieb** [comment]
fix has landed in flang repo, will be in ROCm 5.3

**Comment by sarats** [comment]
Thanks @arghdos and @ronlieb. Let us know if/when this is available for beta testing.

@grnydawn I presume this is the only outstanding issue with AMD compiler at this stage, correct? Once we are able to build and run, we need to check for NaN and other floating point issues.

**Comment by grnydawn** [comment]
@sarats , the only known issue of the failed test cases is this issue. The other failed test cases might be related to this issue too but that could be confirmed once ROCm 5.3 is available.

**Comment by sarats** [comment]
Status: @grnydawn is going to check if rocm 5.3.0 has fixed this issue.
