### ISSUE TITLE
testing bless tool broken?

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#4875]
For several recent PRs that introduced NML only DIFFs, the blessing of those tests caused the baselines to seemingly disappear and cause real DIFFs. This issue is keeping the repo closed and is critical. The error look like:
````
Comparing hists for case 'ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel.C.JNextIntegration20220406_223454' dir1='/lcrc/group/e3sm/e3smtest/scratch/chrys/ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel.C.JNextIntegration20220406_223454/run', suffix1='',  dir2='/lcrc/group/e3sm/baselines/chrys/intel/master/ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel' suffix2=''
````
and causes this for the overall test result:
````
    File 'ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel.C.JNextIntegration20220406_223454.cpl.hi.0001-01-06-00000.nc' had no compare counterpart in '/lcrc/group/e3sm/baselines/chrys/intel/master/ERS_Ld5.T62_oQU120.CMPASO-NYF.chrysalis_intel' with suffix ''
Did not compare any hist files! Missing baselines?
FAIL
````

**Comment by rljacob** [comment]
This may have started after the last CIME update in #4796 on Feb 22.   It wasn't noticed until someone had a namelist-only bless to make.   When both namelist and diffs are blessed at the same time, this doesn't seem to happen.

**Comment by rljacob** [comment]
I checked one of the baseline directories were it said "no compare counterpart" and sure enough the cpl.hist file is missing but the namelist files are there.

**Comment by wlin7** [comment]
#4740 probably was the first NML-diff blessing (blessed on March 25) that saw baseline disappeared.
