### ISSUE TITLE
buildnml script in MPAS-CICE generates a broken path to mesh and graph files on Crusher system.

### ISSUE THREAD

**Issue by grnydawn** [E3SM-Project/E3SM#4908]
Building and running following case generates missing files of MPAS CICE mesh and graph files.

>> ${E3SM}/cime/scripts/create_newcase --res ne4pg2_ne4pg2 --compset F2010 ...

**** output on screen *****
...
Create namelist for component drv
...
Model mpassi missing file mesh = '/gpfs/alpine/cli115/world-shared/e3sm/inputdata/ice/mpas-cice/oQU240/..nc'
Model mpassi missing file graph96 = '/gpfs/alpine/cli115/world-shared/e3sm/inputdata/ice/mpas-cice/oQU240/.part.96'
...

**** end of output on screen *****

From checking cime, "buildnml" in ${E3SM}/components/mpas-seaice/cime_config seems to generate the path using Python codes below.

In "buildnml" script, if statements search a matching name to ice_grid. However, there is no statement that match to current "ne4np4.pg2" grid. Therefore, the variables of "grid_data", "grid_prefix", etc. remain as blank strings. And that looks to make wrong path that was shown above screen output like "...mpas-cice/oQU240/**..nc**" and "...oQU240/**.part.96**"

    grid_date = ''
    grid_prefix = ''
    decomp_date = ''
    decomp_prefix = ''
    data_iceberg_file = ''
    points_file = ''

    if ice_grid == 'oEC60to30v3':
    ....
    if ice_grid == 'oEC60to30v3wLI':
    ...

To me, it looks that this issue is related to somewhere in CIME or MPAS-ICE buildnml script.
[error_messages.txt](https://github.com/E3SM-Project/E3SM/files/8541786/mpas_cice_buildnml.txt)

**Comment by jonbob** [comment]
ne4np4.pg2 is not a valid mpas grid, so that resolution is incompatible with the F2010 compset that specifies MPASSI as  the seaice component. You'll have to either use the F2010-CICE compset or the ne4pg2_oQU480 resolution

**Comment by grnydawn** [comment]
@jonbob , Thanks for the explanation. I could build/run F2010-CICE with ne4pg2_oQU480 resolution without having the issue.

**Comment by jonbob** [comment]
@grnydawn -- you should also be able to run F2010 with ne4pg2_oQU480 or F2010-CICE with ne4pg2_ne4pg2. You just can't run F2010 with ne4pg2_ne4pg2....
