### ISSUE TITLE
Problem with EAM carbon budget with monthly restarts

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#4935]
I was testing the coupler carbon budget using a two-month restart test where I ran a baseline for two months with monthly restarts and then a second one-month test restarting from the first restart of the baseline test. The second run kept failing with the following error in EAM:
````
 CO2 MASS (kgCO2/m2) : period = monthly,: date =        10301           0

                       beg                          end                |        *NET CHANGE*
            0.00000000000000000E+00       0.43268619045104852E+01      |   0.43268619045104852E+01
-----------------------------------------------------------------------|-----------------------
           *SUM*             0.43268619045104852E+01                   |   0.43268619045104852E+01
    Relative Error:         -0.10020368862133358E+01
 time integrated flux =  -8.813325360304845E-003
 net change in state  =    4.32686190451049
 error                =    4.33567522987079
 ERROR: print_global_carbon_diags:Monthly CO2 conservation failure detected
````
From the initial run, the results should have looked like:
````
 CO2 MASS (kgCO2/m2) : period = monthly,: date =        10301           0

                       beg                          end                |        *NET CHANGE*
            0.43356752298707955E+01       0.43268619045104852E+01      |  -0.88133253603102091E-02
-----------------------------------------------------------------------|-----------------------
           *SUM*            -0.88133253603102091E-02                   |  -0.88133253603102091E-02
    Relative Error:          0.12316248208997671E-14
-----------------------------------------------------------------------|-----------------------
````
but for some reason the beginning mass is 0 from the restart

**Comment by beharrop** [comment]
Thanks for pointing this out to me @jonbob .  I thought I had the restarts working correctly, but this must have slipped past.  I will take a look and see what's gone wrong.

**Comment by jonbob** [comment]
Thanks @beharrop . I think it did work when I ran tests with restarts at year boundaries, for what that's worth

**Comment by beharrop** [comment]
Can you give me more details on how you are encountering this error, @jonbob ?  I am having trouble reproducing the error you are seeing.

**Comment by beharrop** [comment]
Thanks @jonbob .  I have been able to reproduce the problem and I have uncovered what is causing it too.

The co2 amount at the start of the month, time step, or simulation are stored in the physics buffer which is written to the restart files.  When I first wrote this, I thought I was being clever and saving on computation by only storing the co2 amounts when `is_last_step()` is `true`.  The problem you have uncovered is that when restart files are written before the final time step of the model, then the correct co2 amount isn't put into the physics buffer, and it is left with zeros.  Only restart files that are written on the final time step will work.  For example, if you restart your simulation using the restart files at the end of the original run, it will work without any issues (or at least it did in my trials).

To fix this, I need to either get rid of the `is_last_step()` flag and store the co2 amounts to the physics buffer every time step, or replace it with a similar logical flag that recognizes when a restart is going to be written.  Do you know of such a flag?  I was looking through `time_manager.F90`, but didn't see anything that looked quite right.  I see that in `atm_comp_mct.F90` there is a logical `rstwr` that gets passed to `cam_run4`, but the co2 stuff is happening in `phys_run2`, itself in `cam_run2`, so I am leaning towards just getting rid of the `is_last_step()` check entirely and storing co2 to the physics buffer each time step.

**Comment by jonbob** [comment]
Thanks Bryce -- that makes all kinds of sense. And I was tracking down a similar issue in the coupler budget, which is why I found this. I trust you to know the best way to fix it, and thanks so much for jumping on it.
