### ISSUE TITLE
eam-thetahy_sl_pg2 fails compare with nvidia compiler on pm-cpu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4961]
Using the nvidia compiler on CPU-only nodes of Perlmutter (`pm-cpu`), most tests pass, but these fail compare:

```
ERS_Ld3.ne4pg2_oQU480.F2010.pm-cpu_nvidia.eam-thetahy_sl_pg2
ERS_Ld3.ne4pg2_oQU480.F2010.pm-cpu_nvidia.eam-thetahy_sl_pg2_ftype0
```

I see that this issue has similar fails https://github.com/E3SM-Project/E3SM/issues/4768
using GNU (v8)

Also noting that 2 other tests fail compare with nvidia where we can have different issues.
```
ERS.ne4_oQU240.F2010.pm-cpu_nvidia.eam-hommexx
ERS_Ln9.ne4pg2_ne4pg2.F2010-MMF1.pm-cpu_nvidia.eam-mmf_crmout
```

**Comment by oksanaguba** [comment]
Do these pass with gnu on PM?

**Comment by ndkeen** [comment]
Yes, pretty much everything so far works with gnu on pm-cpu. These tests also pass with AMD compiler.

**Comment by ndkeen** [comment]
The "thetahy" tests are now passing with nvidia compiler (both with version used above and with latest version). The MMF test also works. The hommexx test still fails compare, but that is failing with multiple compilers on several machines.  SO I'm closing this issue.
