### ISSUE TITLE
NaN-value issue with Cray compiler CCE/14.0.0 on Crusher: ELM EcosystemBalanceCheckMod.F90

### ISSUE THREAD

**Issue by grnydawn** [E3SM-Project/E3SM#4996]
Among 57 e3sm_develper test cases, 21 tests are passed and 36 failed.

Among 36 failed tests, 16 are failed with the issue of "NaN-value". The failed test cases are:
ERS.f09_g16.I1850ELMCN.crusher_crayclang
ERS.f09_g16.I1850GSWCNPRDCTCBC.crusher_crayclang.elm-vstrd
ERS.f19_f19.I1850ELMCN.crusher_crayclang
ERS.f19_f19.I20TRELMCN.crusher_crayclang
ERS.f19_g16.I1850CNECACNTBC.crusher_crayclang.elm-eca
ERS.f19_g16.I1850CNECACTCBC.crusher_crayclang.elm-eca
ERS.f19_g16.I1850CNRDCTCBC.crusher_crayclang.elm-rd
ERS.f19_g16.I1850GSWCNPECACNTBC.crusher_crayclang.elm-eca_f19_g16_I1850GSWCNPECACNTBC
ERS.f19_g16.I1850GSWCNPRDCTCBC.crusher_crayclang.elm-ctc_f19_g16_I1850GSWCNPRDCTCBC
ERS.f19_g16.I20TRGSWCNPECACNTBC.crusher_crayclang.elm-eca_f19_g16_I20TRGSWCNPECACNTBC
ERS.f19_g16.I20TRGSWCNPRDCTCBC.crusher_crayclang.elm-ctc_f19_g16_I20TRGSWCNPRDCTCBC
ERS.r05_r05.IELM.crusher_crayclang.elm-V2_ELM_MOSART_features
SMS.ne4_oQU240.F2010.crusher_crayclang.eam-cosplite
SMS.r05_r05.I1850ELMCN.crusher_crayclang.elm-qian_1948
SMS_Ld1.hcru_hcru.I1850CRUELMCN.crusher_crayclang
SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.crusher_crayclang.elm-lulcc_sville

This issue is related to https://github.com/E3SM-Project/E3SM/issues/4623

This error is occurred at the following error check routine  in “E3SM/components/elm/src/biogeochem/EcosystemBalanceCheckMod.F90”:
 
         if (abs(errcb_grc(g)) > balance_check_tolerance) then
            err_found = .true.
            err_index = g
         end if
 
Because errcb_grc(g) contains NaN value, the "if" test should return false, but it goes into true path.

**Comment by sarats** [comment]
@mt5555 Regarding `SMS.ne4_oQU240.F2010.crusher_crayclang.eam-cosplite`, is cosplite part of the target workload on Frontier?

Otherwise, looks like this issue impacts the I-cases mostly.

**Comment by sarats** [comment]
We should do some investigation and prioritize NaN issues for the Cray folks to dig into.

**Comment by sarats** [comment]
Adding -hfp0 to ELM builds is a reasonable global fix. However, ELM folks should not rely on conditional execution based on a NaN value. Although it accidentally works due to IEEE behavior with many compilers, there ought to be a more explicit check. 

@peterdschwartz Perhaps you know who might be the best person to address this issue.

Context:
`
This error is occurred at the following error check routine in “E3SM/components/elm/src/biogeochem/EcosystemBalanceCheckMod.F90”:
```
     if (abs(errcb_grc(g)) > balance_check_tolerance) then
        err_found = .true.
        err_index = g
     end if
```
Because errcb_grc(g) contains NaN value, the "if" test should return false, but it goes into true path.
`

cc @thorntonpe @rljacob

**Comment by rljacob** [comment]
I agree the practice in ELM of initializing to NAN and then using that in if statements needs to go.  Why not initialize to some really large value like 10^8?

**Comment by rljacob** [comment]
Getting rid of the NaN inits would be a good thing.

**Comment by grnydawn** [comment]
HPE recommends to use -hfp0 option whenever a strict IEEE-compliance is required. I have tested several test cases with the option and with -O0, -O1, and -O2 optimization, and found no performance difference from using the option.
