### ISSUE TITLE
ftn-2116 compiler internal error from "optcg" of Cray compiler CCE/14.0.0 on Crusher

### ISSUE THREAD

**Issue by grnydawn** [E3SM-Project/E3SM#4997]
This error occurred during compilation of "E3SM/components/mpas-framework/src/core_ocean/gotm/src/turbulence/turbulence.F90"

The error message is:

ftn-2116 ftn: INTERNAL
  "/opt/cray/pe/cce/14.0.0/cce/x86_64/bin/optcg" was terminated due to receipt of signal 013:  Segmentation fault (core dumped).

Test case name is "ERS_Ld5.T62_oQU120.CMPASO-NYF.crusher_crayclang"

Entire command line is:

cd /gpfs/alpine/cli133/proj-shared/grnydawn/e3sm_tests/crusher_crayclang_cce14_debug3/ERS_Ld5.T62_oQU120.CMPASO-NYF.crusher_crayclang.20220531_115159_5psojv/bld/cmake-bld/mpas-framework/src && python3 /gpfs/alpine/cli133/proj-shared/grnydawn/e3sm_tests/crusher_crayclang_cce14_debug3/ERS_Ld5.T62_oQU120.CMPASO-NYF.crusher_crayclang.20220531_115159_5psojv/Tools/e3sm_compile_wrap.py  ftn -DCORE_OCEAN -DCPRCRAY -DEXCLUDE_INIT_MODE -DFORTRANUNDERSCORE -DLINUX -DMPAS_ESM_SHR_CONST -DMPAS_EXE_NAME="" -DMPAS_NAMELIST_SUFFIX="" -DMPAS_NO_ESMF_INIT -DMPAS_NO_LOG_REDIRECT -DMPAS_PERF_MOD_TIMERS -DNO_R16 -DOFFSET64BIT -DUSE_LAPACK -DUSE_PIO2 -D_MPI -I/gpfs/alpine/cli133/proj-shared/grnydawn/e3sm_tests/crusher_crayclang_cce14_debug3/ERS_Ld5.T62_oQU120.CMPASO-NYF.crusher_crayclang.20220531_115159_5psojv/bld/crayclang/mpich/nodebug/nothreads/mct/include -I/gpfs/alpine/cli133/proj-shared/grnydawn/e3sm_tests/crusher_crayclang_cce14_debug3/ERS_Ld5.T62_oQU120.CMPASO-NYF.crusher_crayclang.20220531_115159_5psojv/bld/crayclang/mpich/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/csm_share -I/gpfs/alpine/cli133/proj-shared/grnydawn/e3sm_tests/crusher_crayclang_cce14_debug3/ERS_Ld5.T62_oQU120.CMPASO-NYF.crusher_crayclang.20220531_115159_5psojv/bld/crayclang/mpich/nodebug/nothreads/mct/pio -I/opt/cray/pe/parallel-netcdf/1.12.1.7/crayclang/10.0/include -I/autofs/nccs-svm1_home1/grnydawn/repos/github/E3SM/components/mpas-framework/src/external/ezxml -I/gpfs/alpine/cli133/proj-shared/grnydawn/e3sm_tests/crusher_crayclang_cce14_debug3/ERS_Ld5.T62_oQU120.CMPASO-NYF.crusher_crayclang.20220531_115159_5psojv/bld/cmake-bld/framework -I/gpfs/alpine/cli133/proj-shared/grnydawn/e3sm_tests/crusher_crayclang_cce14_debug3/ERS_Ld5.T62_oQU120.CMPASO-NYF.crusher_crayclang.20220531_115159_5psojv/bld/cmake-bld/operators -I/opt/cray/pe/netcdf-hdf5parallel/4.8.1.1/crayclang/10.0/include -I/gpfs/alpine/cli133/proj-shared/grnydawn/e3sm_tests/crusher_crayclang_cce14_debug3/ERS_Ld5.T62_oQU120.CMPASO-NYF.crusher_crayclang.20220531_115159_5psojv/bld/cmake-bld/core_ocean/shared -I/autofs/nccs-svm1_home1/grnydawn/repos/github/E3SM/components/mpas-framework/src/core_ocean/gotm/include -f free -N 255 -h byteswapio -em -M1077 -em -J. -c /autofs/nccs-svm1_home1/grnydawn/repos/github/E3SM/components/mpas-framework/src/core_ocean/gotm/src/turbulence/turbulence.F90 -o CMakeFiles/ocn.dir/core_ocean/gotm/src/turbulence/turbulence.F90.o

**Comment by sarats** [comment]
Try adding turbulence.F90 to the NOOPT list

**Comment by grnydawn** [comment]
> 

I will try this and share its result here.

**Comment by sarats** [comment]
Status: this error is encountered for 10 tests in the `e3sm_integration` test suite and the build error occurs in in core_ocean/shared/mpas_ocn_config.f90. 
Known workaround: turn off inter-procedural analysis (ipa) optimization.

Details at https://docs.google.com/spreadsheets/d/1I0J9zUXCJufdnlxLSkXaww-w81ME4RLI_0cxKRh6a5U/edit#gid=1084235759

**Comment by abbotts** [comment]
@grnydawn , we think this issue should be fixed with CCE 15.0.0, which is available on Crusher now.

**Comment by grnydawn** [comment]
@abbotts , @sarats . CCE15.0.0 does seem resolve this issue as the test case above was passed with CCE15. I will try to run more test cases with CCE15 and will close this issue if I don't see this issue anymore.

**Comment by grnydawn** [comment]
This issue is resolved in CCE15. Closing the issue
