### ISSUE TITLE
SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.X.allactive-wcprodssp fail due to restart file

### ISSUE THREAD

**Issue by peterdschwartz** [E3SM-Project/E3SM#5060]
[SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.chrysalis_intel.allactive-wcprodssp](https://my.cdash.org/test/58087052) is failing due to PR #4993 fixing implementation of TWS_MONTH_BEGIN variable.  Restart file will likely need to be replaced.

**Comment by rljacob** [comment]
@wlin7 see above.

**Comment by rljacob** [comment]
Can say more about what the TWS_MONTH_BEGIN variable is?  Can we make the restart read smarter about that variable?  If its junk then set it to something else?

**Comment by rljacob** [comment]
Was is its value when the model runs for less than a month?  We only noticed a problem in our 31 day restart test.

**Comment by peterdschwartz** [comment]
The new variable `grc_ws%tws_month_beg` is initialized to `spval`.   The old variable `waterstate_vars%tws_month_beg_grc` was initialized to `NaN` but was used to write the restart files prior to this bug fix.

**Comment by rljacob** [comment]
But there must be some logic to just ignore that variable if ELM restarts before a month has passed.  Or how did ERS.f19_f19.IELM.chrysalis_intel, which runs for 11 days, pass before this fix?

**Comment by peterdschwartz** [comment]
The only flag related to these variables is `do_budgets` that I can see.  It looks like the `ERS.f19_f19.IELM.chrysalis_intel` test only compares the history output for the cpl and not elm ?  At least I don't see any elm.h0.0001-01.nc.base files in the run directory.

**Comment by rljacob** [comment]
Sorry I forgot about how the tests work.  Yes it looks like no other ERS tests write a regular ELM history file.  Most write no elm file at all or a custom one (like for FATES).

**Comment by wlin7** [comment]
@peterdschwartz , which variable in the restart file is read in to change the values in the new variable `grc_ws%tws_month_beg`? If its values have no impact on simulation results, we can change its values in the file using nco without worrying about implications, for this test and for any future runs that may opt to use a restart file from maint-2.0 (or the like).

**Comment by wlin7** [comment]
Non-integer variables in the restart file all have `spval` (1e+36) as miss or _fill values. Haven't found a variable that contains NaN. 
The ideal (more flexible) solution should be to do a fix in the code rather than manipulating the content of the restart file.

**Comment by peterdschwartz** [comment]
@wlin7  it's `TWS_MONTH_BEGIN`.   Doing `ncks -P -v TWS_MONTH_BEGIN`  on `/lcrc/group/e3sm/data/inputdata/e3sm_init/V2.SSP370_SSP585.ne30pg2_EC30to60E2r2/v2.LR.historical_0101/2015-01-01-00000/v2.LR.historical_0101.elm.r.2015-01-01-00000.nc`  shows all NaN values

**Comment by wlin7** [comment]
Thanks @peterdschwartz . See no problem resetting TWS_MONTH_BEGIN's values to 1e+36, and it is easy to do so when a similar situation arises -- a branch or a hybrid run from an existing elm.r file. For quick reference, I used the following command to reset the values.
 `ncap2 -O -s 'TWS_MONTH_BEGIN(:)=1.0e+36' v2.LR.historical_0101.elm.r.2015-01-01-00000.nc v2.LR.historical_0101.elm.r.2015-01-01-00000.nc
`

**Comment by wlin7** [comment]
The ssp tests are failing after the change to the restart file. Apparently, the dimension levurb = 5 is lost after ncap2. levurb is not used to define any variables in the restart file, but the restart run uses it to define runtime levurb. I will find a fix.

Also note that the TWS_MONTH_BEGIN NaN values in elm.r was only causing issue for runs with debug build. Same tests passed in e3sm_prod_next_intel suites -- but failing now due to missing levurb.

**Comment by peterdschwartz** [comment]
@wlin7 The debug fails make sense since the `-fpe0` triggers a floating point exception when manipulating `NaN`

**Comment by wlin7** [comment]
Thanks @peterdschwartz . Indeed the fatal message captured in e3sm.log is floating point invalid.

Added the missing dims back to the restart file, and the test run is ok. Below is the 2nd ncap2 command for the changes. The two ncap2 command can be combined if such a change needed for a future case. Don't know if there is an option to ncap2 that can retain the dims that are not in use in the netcdf file.

`ncap2 -O -s 'defdim("levurb",5);defdim("levtrc",10)' v2.LR.historical_0101.elm.r.2015-01-01-00000.nc v2.LR.historical_0101.elm.r.2015-01-01-00000.nc`

**Comment by wlin7** [comment]
The tests affected by this issue all ok now.
