### ISSUE TITLE
Two tests failing on GCP because PE layout not matching newer grid name (oEC60to30v3 vs EC30to60E2r2)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5080]
On GCP at least, there are 2 tests failing (likely OOM but not sure) as they are using default (1 node) layout when we want them to use the same layout used for other "ne30"-sized runs.

```
SMS_Ln5.ne30pg2_r05_EC30to60E2r2.BGCEXP_LNDATM_CNPRDCTC_1850.gcp_gnu
SMS_Ln5.ne30pg2_r05_EC30to60E2r2.BGCEXP_LNDATM_CNPRDCTC_20TR.gcp_gnu
```

For cases with
```
 a%ne30np4_l%ne30np4_oi%oEC60to30v3_r%r05_g%null_w%null_z%null_m%oEC60to30v3 
 2010_EAM%CMIP6_ELM%SPBC_MPASSI%PRES_DOCN%DOM_MOSART_SGLC_SWAV_SIAC_SESP 
```

In `components/eam/cime_config/config_pes.xml` we currently match with `<grid name="a%ne30.+_oi%oEC60to30v3">`

Now with
```
a%ne30np4.pg2_l%r05_oi%EC30to60E2r2_r%null_g%null_w%null_z%null_m%EC30to60E2r2
1850_EAM%CMIP6_ELM%CNPRDCTCBC_MPASSI%PRES_DOCN%DOM_SROF_SGLC_SWAV_SIAC_SESP_BGC%LNDATM
```

I can match both with something like:  `<grid name="a%ne30.+_oi%.*EC.*to">`

This "fixes" the fails in the sense that they now run with same 8-node PE layout that other cases use.

**Comment by ndkeen** [comment]
Which I have here `ndk/machinefiles/gcp-adjust-ne30-layout`

**Comment by ndkeen** [comment]
I merged this to master, but I see CDASH still reporting the tests as FAIL. I just cloned master and tried them each individually and they pass. So it's possible CDASH tests did not have the updates, or something not right with the checkout there.

**Comment by sarich** [comment]
You're correct, it didn't get the update.
I recloned the repo yesterday and forgot to change the submodule ssh links to http, there was an ssh error in updating last night.
```
Fetching submodule cime
Permission denied (publickey).
fatal: Could not read from remote repository.
```
Should be fixed now.
