### ISSUE TITLE
"ACC - barrier not supported" issue from offloading to GPU on Crusher using Cray compiler

### ISSUE THREAD

**Issue by grnydawn** [E3SM-Project/E3SM#5095]
I tried to build a shared library from a short Fortran programming with OpenMP offloading to GPU on Crusher using Cray compiler, and got following compiler error message. I also attached the Fortran source file to reproduce the issue including compiler command line:
 
```
   Error message      ::  ACC - barrier not supported
   Error detected     ::  File '/workspace/crayftn/pdgcs/v_mt_translate.c', line 3996
   Initiated from     ::  Line 1807 (v_main.c)
   Optimizer built    ::  2022-04-20 (production)
 
   File               ::  FML6ac1501e.F90
   Function           ::  launch
   at or near line    ::  29
 
   File path          ::  /tmp/jl_I8aFGS/FML6ac1501e.F90
   Compiler hash      ::  c98838affc7b58fed2a72f164d77c35e1bc8772f
   Target             ::  Heterogeneous
     CPU              ::  x86-trento
     ACCEL            ::  amdgcn-gfx90a
 
Creating internal compiler error backtrace (please wait):
[0x00000000bfd323] linux_backtrace ??:?
[0x00000000bfe211] pdgcs_internal_error(char const*, char const*, int) ??:?
[0x000000008f385e] MT_TRANSLATE::add_barrier_and_reset_code(int, int, int) ??:?
[0x000000009050fd] MT_TRANSLATE::partition_loop(int) ??:?
[0x0000000090aa32] mt_translation() ??:?
[0x00000000810865] void run_pass_helper<void>::exec<void (&)()>(int, char const*, void (&)()) ??:?
[0x0000000080297d] pdgcs_main ??:?
[0x00000000797742] PDGCS_do_proc ??:?
[0x000000006d9b73] cvrt_proc_to_pdg m_cvrt.c:?
[0x000000006da47f] m_cvrt_to_pdg ??:?
[0x000000007116c4] m_start_ipa ??:?
[0x00000000636d5f] main ??:?
[0x007fffeb7c42bc] ?? ??:0
[0x000000006b90d9] _start /home/abuild/rpmbuild/BUILD/glibc-2.26/csu/../sysdeps/x86_64/start.S:120
 
Note:  This is a non-debug compiler.  Technical support should
       continue problem isolation using a compiler built for
       debugging.
 
ftn-7991 ftn: INTERNAL LAUNCH, File = FML6ac1501e.F90, Line = 29
INTERNAL COMPILER ERROR:  "ACC - barrier not supported" (/workspace/crayftn/pdgcs/v_mt_translate.c, line 3996, version c98838affc7b58fed2a72f164d77c35e1bc8772f)
```

[cray_omptarget_bugreport.txt](https://github.com/E3SM-Project/E3SM/files/9192711/cray_omptarget_bugreport.txt)

**Comment by mattdturner** [comment]
I just started looking at this, so don't have an answer yet.

But if I change the `!$omp do` to `$!omp loop` inside the `$!omp target` region, then the code builds successfully.  I believe the `$!omp loop` construct was added in the OpenMP 5.0 spec, so I understand if portability is a concern.

Will this be an acceptable workaround for the time being?

**Comment by mattdturner** [comment]
In your original reproducer, shouldn't the `!$omp do collapse(2)` directive be `!$omp parallel do simd collapse(2)`?  I'm not sure what `!$omp do` without the `parallel` would actually do.

Adding in the `parallel` directive allows it to compile as well.

**Comment by grnydawn** [comment]
> 

$!omp loop works for me too with Cray compiler on Crusher. But, it did not work with Amd compiler on Crusher. I think that I need something that works for for both compilers.

**Comment by grnydawn** [comment]
> 

I am still learning openmp target and can not tell what is valid or not. But your suggestion (!$omp parallel do simd collapse(2)) seems to me reasonable. In the meantime, I got following warning message when I tried to follow your suggestion with Cray compiler on Crusher:

    !$omp parallel do simd collapse(2) private(j, i)
ftn-7256 ftn: WARNING LAUNCH, File = omptarget_fix2.f90, Line = 22 
   An OpenMP parallel construct in a target region is limited to a single thread.

Cray Fortran : Version 14.0.0 (20220420160222_c98838affc7b58fed2a72f164d77c35e1bc8772f)
Cray Fortran : Mon Aug 08, 2022  09:37:05
Cray Fortran : Compile time:  0.0842 seconds
Cray Fortran : 37 source lines
Cray Fortran : 0 errors, 1 warnings, 0 other messages, 0 ansi
Cray Fortran : "explain ftn-message number" gives more information about each message.

Did you have this warning too? Can I just ignore this warning message?

I tried to compile the same code with Amd compiler and it did not print any warning message.

**Comment by mattdturner** [comment]
I get that warning as well, and you can ignore it.

The compiler is stating that the `parallel` construct within a target region is limited to a single thread, which is true.  However, the `simd` construct is what allows for the parallelism across threads within a `target` region.  

`$!omp teams distribute` parallelizes across workgroups. For Fortran, `simd` parallelizes across threads in a workgroup. 

So, that warning message is accurate, but a bit misleading.
