### ISSUE TITLE
Fortran intrinsic `fraction` has no device function w/ Cray compiler

### ISSUE THREAD

**Issue by mattdturner** [E3SM-Project/E3SM#5112]
https://github.com/E3SM-Project/E3SM/blob/0b2ced33b791be3ebb6896872eb01c2ef0428aaa/components/mpas-ocean/src/shared/mpas_ocn_diagnostics.F#L1432

The above referenced line of code uses the `fraction()` Fortran intrinsic function.  During the Crusher Hackathon it was determined that during the port of MPAS-O to GPUs w/ OpenACC, this causes a link-time error on Crusher with the Cray compiler.  We believe this is due to there being no device function for `fraction()` in the Cray compiler.

I'm not sure how many other occurrences of this function there are in E3SM.

It wasn't immediately apparent to us what the `fraction` function was doing.  Is the use of this function necessary?  Can the functionality be replaced with something else?

CC'ing others involved in the initial discussion.
@sarats @mrnorman @brobey

**Comment by ambrad** [comment]
I wonder if this is actually a bug where a land or ice fraction variable is intended but the symbol `fraction` itself was accepted by the compiler because it is an intrinsic.

**Comment by sarats** [comment]
It's being used in https://github.com/E3SM-Project/E3SM/blob/master/components/homme/src/repro_sum_mod.F90 but the comments there give me hope (most likely Pat Worley) that they meant to use the bitwise representation. 

Btw, this helped decipher the semantics of `fraction`
[https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-onea[…]-reference/data-representation-models/model-for-real-data.html](https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/data-representation-models/model-for-real-data.html#model-for-real-data)
fraction(20) = 0.625

I have found instances of this at several other places, some are false positives - local array named fraction etc. We need to check/confirm that it's used intentionally if present.

**Comment by ambrad** [comment]
Sarat, I agree that in repro_sum_mod that `fraction` is used intentionally and correctly; the code is dissecting the floating point representation to repack it as an array of integers. In the MPAS case I suspect it's a typo.

**Comment by sarats** [comment]
Yes, I suspected that it's most likely accidental (assuming different semantics) in other cases.

Here are the instances I found with a basic grep. Some of these are local array ops but the MPAS ones most likely need to be audited.
```
components/eam/src/chemistry/mozart/mo_drydep.F90:                   fraction(npft_veg+1) = fraction(npft_veg+1) + area
components/eam/src/chemistry/mozart/mo_drydep.F90:                      fraction(n) = fraction(n) + vegetation_map(i_ndx,jj,n) * area
components/eam/src/chemistry/mozart/mo_drydep.F90:                   fraction(npft_veg+1) = fraction(npft_veg+1) + area * lake   (i_ndx,jj)
components/eam/src/chemistry/mozart/mo_drydep.F90:                   fraction(npft_veg+2) = fraction(npft_veg+2) + area * wetland(i_ndx,jj)
components/eam/src/chemistry/mozart/mo_drydep.F90:                   fraction(npft_veg+3) = fraction(npft_veg+3) + area * urban  (i_ndx,jj)
components/eam/src/chemistry/mozart/mo_drydep.F90:                      fraction(npft_veg+1) = fraction(npft_veg+1) + (1._r8 - total_land) * area
components/eam/src/chemistry/mozart/mo_drydep.F90:          fraction(:) = fraction(:)/total_area
components/eam/src/chemistry/mozart/mo_drydep.F90:             fraction(:) = fraction(:)/sum(fraction)
components/eam/src/chemistry/mozart/mo_drydep.F90:          tmp_frac_lu(i, 1, j) =     fraction(20)
components/eam/src/chemistry/mozart/mo_drydep.F90:          tmp_frac_lu(i, 6, j) =     fraction(19)
components/eam/src/chemistry/mozart/mo_drydep.F90:          tmp_frac_lu(i, 7, j) =     fraction(18)
components/eam/src/chemistry/mozart/mo_drydep.F90:          tmp_frac_lu(i, 8, j) =     fraction( 1)
components/eam/src/chemistry/bulk_aero/mo_setsoa.F90:  fraction(1)   = 1._r8
components/eam/src/chemistry/bulk_aero/mo_setsoa.F90:  fraction(2)   = 1._r8
components/eam/src/chemistry/bulk_aero/mo_setsoa.F90:  fraction(3)   = 1._r8
components/eam/src/chemistry/bulk_aero/mo_setsoa.F90:  fraction(4)   = 0.7_r8
components/eam/src/chemistry/bulk_aero/mo_setsoa.F90:  fraction(5)   = 0.2_r8
components/eam/src/chemistry/bulk_aero/mo_setsoa.F90:  fraction(6)   = 0.1_r8
components/eam/src/chemistry/bulk_aero/mo_setsoa.F90:          prod  = reaction_rates(i,k,rxn_soa(n)) * fraction(n) &
components/eam/src/chemistry/bulk_aero/mo_setsoa.F90:          prod  = reaction_rates(i,k,rxn_soa(n)) * fraction(n) &
components/mpas-ocean/src/Registry.xml:                  description="CVMix/KPP: surface layer entirely encompasses int(indexSurfaceLayerDepth) vertical layers and fraction(indexSurfaceLayerDepth) of the int(indexSurfaceLayerDepth)+1 layer."
components/mpas-ocean/src/shared/mpas_ocn_diagnostics.F:          tracersSurfaceLayerValue(:,iCell) = (tracersSurfaceLayerValue(:,iCell) + fraction(rSurfaceLayer) &
components/mpas-ocean/src/shared/mpas_ocn_diagnostics.F:            normalVelocitySurfaceLayer(iEdge) = (normalVelocitySurfaceLayer(iEdge) + fraction(rSurfaceLayer) &
components/mpas-framework/src/core_ocean/Registry.xml:                   description="CVMix/KPP: surface layer entirely encompasses int(indexSurfaceLayerDepth) vertical layers and fraction(indexSurfaceLayerDepth) of the int(indexSurfaceLayerDepth)+1 layer."
components/mpas-framework/src/core_ocean/shared/mpas_ocn_diagnostics.F:          tracersSurfaceLayerValue(:,iCell) = (tracersSurfaceLayerValue(:,iCell) + fraction(rSurfaceLayer) &
components/mpas-framework/src/core_ocean/shared/mpas_ocn_diagnostics.F:            normalVelocitySurfaceLayer(iEdge) = (normalVelocitySurfaceLayer(iEdge) + fraction(rSurfaceLayer) &
components/homme/src/repro_sum_mod.F90:               arr_frac  = fraction(arr(isum,ifld))
components/homme/src/repro_sum_mod.F90:!  1) arr_max_shift is the shift applied to fraction(arr_gmax) .
components/homme/src/repro_sum_mod.F90:                        arr_gsum(ifld) = fraction(X_8(jlevel))
components/homme/src/repro_sum_mod.F90:                        arr_gsum(ifld) = fraction(X_8(jlevel)) &
share/util/shr_reprosum_mod.F90:               arr_frac  = fraction(arr(isum,ifld))
share/util/shr_reprosum_mod.F90:!  1) arr_max_shift is the shift applied to fraction(arr_gmax) .
share/util/shr_reprosum_mod.F90:                        arr_gsum(ifld) = fraction(X_8(jlevel))
share/util/shr_reprosum_mod.F90:                        arr_gsum(ifld) = fraction(X_8(jlevel)) &
```

**Comment by philipwjones** [comment]
Just back in town - yes, the MPAS versions are intentional but there is an easy workaround. I thought I had replaced these due to a similar compiler issue in the past, but apparently not...we just need to subtract the integer from the real to get the fractional remainder.

**Comment by philipwjones** [comment]
Doh. @sarats correctly pointed out that MPAS is using this intrinsic incorrectly and this is a definite bug leading to incorrect results. I will create a new issue and a fix.
