### ISSUE TITLE
Not clear where to set CMAKE_CXX_FLAGS_RELEASE to override default -O3

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/E3SM#5153]
I've tried `set(CMAKE_CXX_FLAGS_RELEASE "-O1")` in several spots, including in cime_config/machines/cmake_macros/CMakeLists.txt and the machines/cmake_macros/ cmake file for the machine/compiler, but I still see -O3 in e3sm.bldlog for C++ files. Is there a place this line should go? Thanks.

**Comment by ambrad** [comment]
One potential workaround seems to be to place `string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O1")` in a component's CMakeLists.txt file.

**Comment by jgfouca** [comment]
@ambrad,

Luca's PR should fix things on the SCREAM side.

Until all our sharedlibs support cmake builds, the macros are going to be a bit wonky. I will try to improve the situation when I get some time. For now, we have to do things in a custom way that doesn't conform to CMake standards.

I believe this should work if you put it in the macro file for your machine/compiler combo:
```
if (NOT DEBUG)
  string(APPEND CFLAGS " -O1")
  string(APPEND CXXFLAGS " -O1")
  string(APPEND FFLAGS " -O1")
endif()
```

**Comment by jgfouca** [comment]
@ambrad , any thoughts on the workaround I described above?

**Comment by ambrad** [comment]
Yes, that's fine. I used something similar in SCREAM. I'll close this issue.
