### ISSUE TITLE
Problem with mpassi pointwiseStats output using gnu on anvil

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#5157]
After PR #5120 was merged, the BGC test SMS_Ld2.ne30pg2_r05_EC30to60E2r2.BGCEXP_CNTL_CNPRDCTC_1850 failed using gnu on anvil and crusher, with an error in the e3sm log pointing at PIO issues with the mpassi pointwiseStats output:

 "0: PIO: ERROR: Defining variable  (ndims = 1) in file pointwiseStats.0001-01-01.nc (ncid=89, iotype=PIO_IOTYPE_NETCDF) failed. NetCDF: Name contains illegal characters. NetCDF: Name contains illegal characters (error num=-59), (/gpfs/fs1/home/e3smtest/jenkins/workspace/ACME_Anvil_next/E3SM/externals/scorpio/src/clib/pio_nc.c:3091)"

After a bit more checking, the same run on chrysalis also had log.seaice.XXXX.err files complaining about:

"ERROR: MPAS IO Error: Bad return value from PIO"

but completed successfully. However, the pointwiseStats.0001-01-01.nc file was incomplete for both tests. The mpassi pointwiseStats AM is enabled by default when seaice bgc is on, though no list of points is available for this mesh. That analysis member seems unique about loading fieldNames into pointers without using the time_series_stats that were modified in PR #5120, and probably needs to be reworked in the same fashion. It is also possible to turn off the pointwiseStats AM for seaice bgc currently, since no points files are available for v2 grids.

**Comment by xylar** [comment]
@jonbob, I think you have it right.  `pointwiseStats` needs to be reworked the same as `timeSeriesStats`.  I think it should be easy but I won't have a fix until tomorrow.

**Comment by jonbob** [comment]
Thanks @xylar -- I don't think it's critical, but we might get the BGC people to put off their tag until this is fixed. @rljacob?? It only impacts BGC, so they could tag before PR 5120 or after the fix comes in
