### ISSUE TITLE
FillValue mismatch when writing timeSeriesStats in mpas-o

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#5235]
Recent runs to test a PR show errors in the e3sm log file when writing timeSeriesStats output, related to FillValue type mismatch. The errors look like:
````
0: PIO: ERROR: Writing variable (timeDaily_avg_normalVelocity, varid=7) attribute (_FillValue) to file (20221011.pre5218.chrysalis.mpaso.hist.am.timeSeriesStatsDaily.0001-01-01.nc, ncid=43) failed. Internal I/O library (PIO_IOTYPE_PNETCDF) call failed. NetCDF: Not a valid data type or _FillValue type mismatch (error num=-45), (/lcrc/group/acme/ac.jwolfe/e3sm_PR5218/externals/scorpio/src/clib/pio_getput_int.c:425)
````
The errors do not cause the run to abort and the variable values still look reasonable in the output

**Comment by xylar** [comment]
@cbegeman, is this something you would have any time to look into?  I know you're as busy as I am.

My suspicion is that it's to do with writing out the data in `float` (single precision) but having a fill value that is `double` (double precision).

**Comment by xylar** [comment]
The run that @jonbob and I are doing that shows this is:
```
-res TL319_EC30to60E2r2 -compset CMPASO-JRA1p4
```
run for a month.

**Comment by cbegeman** [comment]
@jonbob @xylar I'll try to give this a look today or over the weekend and let you know how far I get. My schedule is pretty full with meetings and travel next week.

**Comment by xylar** [comment]
@cbegeman, if you didn't get to this, no stress.  I will get to it sometime this coming week.

**Comment by cbegeman** [comment]
@xylar No, I didn't make too much progress on this before my trip. I have a branch here https://github.com/cbegeman/E3SM/tree/mpas-framework/bugfix_fillval where I added a single precision fill value to the mask field routines but that didn't resolve the error.

**Comment by xylar** [comment]
I think I have a fix here:
https://github.com/xylar/E3SM/tree/mpas-framework/bugfix-fillval
Testing now no Cori.

**Comment by cbegeman** [comment]
@xylar That's great! Thanks for prioritizing this!

**Comment by xylar** [comment]
I was testing on Cori but it's gone down.

**Comment by xylar** [comment]
My test on Cori timed out on knl and then again on haswell.  I'm trying on Chrysalis now that I have access again.
