### ISSUE TITLE
Fill values are not appearing in fields in timeSeriesStats

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/E3SM#5253]
Even when we specify a fill mask and fill value in the registry, we're not seeing the fill mask get propagated to fields in `timeSeriesStats`.  See https://github.com/E3SM-Project/E3SM/pull/5251#issuecomment-1292526164

**Comment by cbegeman** [comment]
@xylar I took a look at your run and the stream did not specify `useMissingValMask="true"` so the fill value mask is not applied. The masking feature is off by default. The masking works as expected in standalone when `useMissingValMask="true"` and `precision="single"`.

**Comment by xylar** [comment]
Okay, so the "bug fix" would be to turn on this feature in E3SM.

**Comment by xylar** [comment]
Thanks for figuring that out.
