### ISSUE TITLE
Broken WaterCycle compsets: WCYCL1850-1pctCO2 and WCYCL1850-4xCO2

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/E3SM#5261]
The WaterCycle compsets **WCYCL1850-1pctCO2** and **WCYCL1850-4xCO2** are broken on master (I used a relatively recent version as part of the v2.1 simulation campaign b02bfec1784525d8f05c9fe7d60cc044ca435c40).

They don't run and the eam namelist settings appear to come from some very old configuration (pre E3SMv1): 30 levels with completely different physics.

**Comment by golaz** [comment]
Tagging @wlin7 who might be able to help.

**Comment by rljacob** [comment]
Are those supposed to work in v2?

**Comment by wlin7** [comment]
> Are those supposed to work in v2?
Yes. I am looking into it.

**Comment by wlin7** [comment]
Fixed via PR #5263. Need to add a test to protect against such production compsets being broken.

**Comment by golaz** [comment]
Thank you @wlin7, this is great!

@rljacob : yes, we do need these compsets and we should protect them with tests. They are needed for the DECK simulations 1pctCO2 and abrupt-4xCO2.
