### ISSUE TITLE
improving accuracy of shr_reprosum_calc

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#5276]
The reprosum algorithm converts each floating point summand into a
vector of integers representation. These vectors are summed locally
first, and then globally (using an mpi_allreduce). All of this is
exact and reproducible. The final step is to convert the final sum, in
the vector of integers representation, back into a floating point
value.

For this last step, each component integer in the vector
representation is converted back into a floating point value (call it
a_{i} for the ith element of the vector), and then these values are
summed locally, smallest to largest, to get the final value. The
integer representation is first massaged so that all a_{i} have the
same sign and the range of values is usually not overlapping (least
significant binary digit in abs(a_{i}) represents a value larger than
that represented by abs(a_{i+1}) in most cases, but sometimes is equal
to).

As this final floating point sum is done serially on each process, the
full summation is reproducible. However, despite the care in
constructing the final floating point value, round-off error can be
introduced in the least significant digit (apparently in the least
significant binary digit). This level of inaccuracy has no practical
impact on overall model accuracy, but it can lead to some annoying
inconsistencies, for example, with the calculation using a 4-byte
integer vector representation potentially producing a slightly
different result from a calculation using an 8-byte integer vector
representation, even though everything else is the same.

One modification to decrease the likelihood of rounding errors is to
calculate this final sum of floating point values using the DDPDD
algorithm locally. (DDPDD is an alternative algorithm already available
in the reprosum code.) DDPDD uses a two-floating-point-value
representation of the intermediate values in the summation to
approximately double the precision, i.e., for double precision values,
summing in quad precision. In this case, round-off error is isolated
to the least significant digits is in the quad precision value, and it
is even less likely that this will impact the least significant digit
in the resulting double precision value (though not impossible).
(Note that the integer representation can also be made strictly
nonoverlapping prior to conversion to floating point values, but this
does not seem to change the numerics.)

This modification requires little code change, and only a very small
increase in the cost of the reprosum summations. The downside of this
change is that it is not BFB with the current algorithm in
practice in E3SM. For example, for a 5 day run on Chrysalis using

--compset WCYCL1850 --res ne30pg2_EC30to60E2r2 --pecount XS

(675 ATM processes) there are 42539 reprosum calls, all in ATM, and
using DDPDD for the final sum changes the result 154 times (so 0.36%
of the time).

Looking at the actual difference, it is always +/- 1 in the least
significant binary digit in the mantissa. But this is still enough to
perturb the model output, e.g. (from the atm.log) 

 nstep, te      241   0.26199544016604438E+10   0.26199556530333414E+10   0.69198168371446191E-04   0.98528687083867393E+05

vs.

 nstep, te      241   0.26199778307525997E+10   0.26199790667547684E+10   0.68348231909100610E-04   0.98528642347948073E+05

While it would be nice to have reprosum updated in this way, it is
unclear to me whether it is worth the cost of introducing a nonBFB
change for something that really does not improve the model in a
scientifically quantifiable way. This would primarily be a "code
cleanup" modification.

I can also put the option in the code and leave it disabled for the
time being, to be evaluated again in the future if a use case arises.

**Comment by ambrad** [comment]
1. In your run, what was the performance difference using double-double summation locally at the end?
2. Am I correct that the final step of converting double-double to double has a 1 ULP error, so a 1-ULP error can't be avoided regardless of method?
3. With double-double summation at the end, I'm thinking the sort can be skipped, potentially speeding up rather than slowing down the local part.
4. Does this particular operation have the form of accumulating doubles into a double-double, like this?
```
for i = 1,n
  a:double-double += b(i):double
```
If so, it might be worth making a special routine for this to save one addition and some memory.

I don't think I'm correct in all these points, but in 3 and 4, if I am, then I think the local step at the end would potentially be faster because it would use more ops but substantially less data movement (no sort) and no extra space.

**Comment by worleyph** [comment]
> 1. In your run, what was the performance difference using double-double summation locally at the end?

I did not attempt to measure this (yet). As implemented currently, I added logic, but did not remove the existing logic, so the cost of the local call to DDPDD is purely in addition to that of the original algorithm.

Note that the cost of shr_reprosum_calc is almost entirely in the mpi_allreduces (2 typically, though can be reduced to 1 if some additional information is provided to the call, which we aren't doing currently), followed by the conversion of the summands to integer and summing these before the second call to mpi_allreduce. The final summation in practice involves a vector of length 3 to 6, so is pretty much in the noise performance-wise. I'll quantify this in a future experiment.

Note that we haven't used reprosum in performance critical loops in the past. @philipwjones is  looking at using double-double representation in the inner products in the ocean iterative solve I believe.

> 2. Am I correct that the final step of converting double-double to double has a 1 ULP error, so a 1-ULP error can't be avoided regardless of method?

Given the nonoverlap property, the bit patterns are effectively concatenated rather any real arithmetic if positive (for a two's complement representation). I may be able to do something with that (summing as positives, then reapplying the sign?) Looking at this now (busy tomorrow, so later in the week). There will be rounding in any case. Still surprised that i4 and i8 can go different directions, and that DDPDD sometimes changes this as well. But experimentally (and "handwaving" logically) this is all in the ULP.

> 3. With double-double summation at the end, I'm thinking the sort can be skipped, potentially speeding up rather than slowing down the local part.

No sort is required. The vector of integers representation gives this for free. With the double-double summation, might be able to eliminate the logic used to remove overlap and make all components the same sign, but this cost is low. I'll verify this however. Note that DDPDD is not fullproof (which is why we don't use it all of the time), but using it in the particular case seems safe, especially after the integer summands are massaged.

> 4) Does this particular operation have the form of accumulating doubles into a double-double, like this? ...

Might be best if you look at the code. Calling shr_reprosum_ddpdd with the communicator MPI_NULL, where this routine is modified to return after the local summation if the communicator is MPI_NULL. So, you can look at the existing code to see what is going on. For code clarity, I decided to reuse this existing code, though the double-double algorithm can be implemented in-line with less expense (which is what I did in my original experiments).

If you want to look at my sandbox, go to 

     /gpfs/fs1/home/ac.worleyph/E3SM/worleyph/share/util/reprosum_accuracy_improvement/E3SM/share/util

Original is shr_reprosum_mod.F90_orig, potential proposal is shr_reprosum_mod.F90_update, instrumented working version is shr_reprosum_mod.F90.

**Comment by worleyph** [comment]
I do have some rough performance data already:

Original:

"a:shr_reprosum_int"                             -        675      675 2.445525e+06   3.364284e+02     0.981 (   112      0)     0.311 (   323      0)

Proposal (with redundancies)

"a:shr_reprosum_int"                             -        675      675 2.445525e+06   3.361708e+02     0.928 (   674      0)     0.361 (   393      0)

So new algorithm looks cheaper (though it isn't). Performance variability in mpi_allreduce makes comparisons messy. Would minimally need to run experiments on the same nodes. I'll add a timer to try to measure the cost of the new logic directly, but it may be too low level for any accurate measurements.

Note for the proposed update (to pick one randomly):

     "a:repro_sum_loopa"                              -        675      675 2.445525e+06   2.732509e+00     0.005 (   467      0)     0.003 (    14      0)
     "a:repro_sum_allr_minmax"                        -        675      675 2.445525e+06   2.746698e+02     0.887 (   112      0)     0.219 (   323      0)
     "a:repro_sum_loopb"                              -        675      675 2.445525e+06   7.952933e+00     0.013 (   470      0)     0.011 (   669      0)
     "a:repro_sum_allr_i8"                            -        675      675 2.445525e+06   3.492620e+01     0.058 (    25      0)     0.039 (   487      0)

loopa is associated with calculating the required length of the integer vector, as is the first mpi_allreduce (repro_sum_allr_minmax). loopb is the conversion of the summands to integer vectors and the local integer summation, and repro_sum_allr_i8 is the global summation. None of this includes the final summation logic. Note that the first mpi_allreduce captures load imbalance, and is by far the largest cost. 

So, only 5% of the cost is unaccounted for by these four timers, and the final summation will be some part of this.

**Comment by ambrad** [comment]
Ok. I agree that the performance difference is likely in the noise and certainly very small.

**Comment by philipwjones** [comment]
@worleyph - thanks, this looks good and seems like a reasonable approach to catch those cases. Once you're satisfied with testing, I would go ahead with a PR and others can determine the best timing for a non-bfb change.

@ambrad - Pat referred you to code, but for a simple background on DDPDD, this does not accumulate in quad due to the inconsistent standard support (both language and MPI) for true quad precision. There might be a bit broader support now but I think it's still not required in some standards (? could be wrong). So it mimics quad by accumulating both sums and residuals and uses a double complex data type to store the two doubles and pass through MPI. As Pat mentioned, this is indeed the algorithm that's currently int he MPAS reproducible sums (global_sum rather than the dmpar sums).

**Comment by rljacob** [comment]
Remind me:   these routines are only used to calculate the diagnostic global integrals in EAM?  So would it be a BFB change if you're looking at history?

**Comment by ambrad** [comment]
@rljacob I use them in the SL transport property preservation step. They would also be used if the component remap routines were to start using a nonlinear, strictly property preserving method.

**Comment by worleyph** [comment]
FYI - I believe that I've identified an alternative to using DDPDD for the final sum. If correct, this will be a little cleaner than the current proposal (and probably less expensive, though this is all in the noise anyway). I'm in the process of developing and testing this alternative, and will describe it here if it pans out.

**Comment by worleyph** [comment]
Sorry for the long silence. I was ill for 3 of the past 5 weeks (3 different illnesses - very annoying). I also went down a rabbit hole trying to analyze why my "new and improved" algorithm was not actually an improvement. After staring at bit patterns generated by E3SM experiments, I finally realized that Chrysalis (at least) is using a different rounding algorithm than I expected (the IEEE standard defines 5 different rounding modes, without specifying which to use?). Not a total waste as the original motivation was to have an algorithm that did not depend on the particulars of the rounding mode. So, I need to give this more thought. I have continued to verify that this is all in the last bit, and the current algorithm is fine (reproducible) if you are not obsessive-compulsive about it. I'm still going to take another whack at an improvement, either something new or the above mentioned DDPDD-based modification, but don't know when I will have something to offer.

**Comment by worleyph** [comment]
I've finished investigating the issue(s) and come up with a fix. As far as I can tell, the variability that can occur when changing from using 8-byte integers (i8) to 8-byte integers (i4) could also affect reproducibility when changing numbers of MPI tasks and OpenMP threads. It takes a pretty contrived example to demonstrate the i4 vs. i8 difference, and I do not observe it in E3SM. Reproducing the variability when changing the number of computational threads is likely to be even more difficult, but I can't rule it out.

In the process of investigating this, I determined:
a) The code needs more comments, both high level description and in-line comments. (I had to rediscover/reconfirm some of the algorithm details as I worked through this.) The code also needs some cosmetic clean-up (both appearance and consistency in coding conventions).
b) Some logic to prevent bad things from happening (overflow and catastrophic cancellation) is flawed in some edge cases. It's not a big deal (since overflow would be obvious if it were happening, and catastrophic cancellation won't happen even with the error I found - the code is just not doing exactly what the comments say it does), but fixing this is also important for the fix I came up for the (potential) reproducibility issue.
c) I found an alternative to using the DDPDD local sum that eliminates the nonreproducibility. This is not BFB with the current algorithm, but it is BFB with using the DDPDD local sum in my experiments, so this appears to improve accuracy as well as eliminating the potential for nonreproducibility.

I propose to submit 3 PRs, reflecting (a), (b), and (c) above. PR for (a) is BFB for sure. PR for (b) is highly likely to be BFB with respect to E3SM testing. PR for (c) will not be BFB.

Should I proceed with this? @rljacob @sarats @mt5555 @philipwjones @ambrad ?

**Comment by philipwjones** [comment]
Yes, go ahead. Glad to see you're enjoying retirement...

**Comment by rljacob** [comment]
Yes go ahead. Thanks!

**Comment by sarats** [comment]
Sounds good, please go ahead at your own pace ;)
