### ISSUE TITLE
Add ability to run maint-2.0 on pm-cpu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5284]
Similar to https://github.com/E3SM-Project/E3SM/issues/5280 for maint-1.0, we would also like to use pm-cpu with the maint-2.0 branch.  In that branch, we did have machine `perlmutter`, but that was actually for what is now `pm-gpu` (with ability to also run on just the CPU's of those GPU nodes).  I will change this to be `pm-cpu` and maybe not even include `pm-gpu` for now.

**Comment by ndkeen** [comment]
I am making a branch that removes any reference to machine `perlmutter` and replaces with `pm-cpu`.  I was going to remove any mention of `pm-gpu`.  Is that what we want?  I could also add `pm-gpu` to this branch.

**Comment by rljacob** [comment]
Go ahead and add pm-gpu.

**Comment by ndkeen** [comment]
OK I have branch `ndk/maint20/port-to-pm-cpu`

**Comment by ndkeen** [comment]
This was completed by the above PR
