### ISSUE TITLE
Warning error for 'ssh' variable in ocn.log

### ISSUE THREAD

**Issue by darincomeau** [E3SM-Project/E3SM#5287]
In certain configurations, I'm seeing the following warning message written to the ocn.log file at every timestep:

```
WARNING: Error: Field ssh has more than one time level, but no timeLevel argument given.
```

As far as I can tell from testing on today's master, this is only appearing in G-cases with ocn grids that have ice-shelf cavities.

Warning message appears:
`TL319_ECwISC30to60E2r1.GMPAS-JRA1p4`
`T62_ECwISC30to60E2r1.GMPAS-IAF`

Warning message absent:
`TL319_EC30to60E2r2.GMPAS-JRA1p4`
`T62_EC30to60E2r2.GMPAS-IAF`
`CRYO1850.ne30pg2_ECwISC30to60E2r1`

@xylar has identified a couple potential fixes I'm testing, but there's confusion why the warning messages (apparently) only appear in `GMPAS-*.*wISC*` configurations.

**Comment by xylar** [comment]
I suspect:
https://github.com/E3SM-Project/E3SM/blame/master/components/mpas-ocean/driver/ocn_comp_mct.F#L2633,
which was last modified in
https://github.com/E3SM-Project/E3SM/pull/5047

Prior to that merge, the issue would only have been seen in runs with MOSART on.

As @darincomeau says, why this is only seen now in certain runs and not others is a mystery.  We should be seeing the message at ever ocean coupling step for any configuration as far as I can tell.

**Comment by darincomeau** [comment]
@xylar indeed that fix did remove the warning messages from the case I was seeing. I'll put together a PR.
