### ISSUE TITLE
Extraenous mpaso.waveOuput files

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/E3SM#5300]
Two (related) issues.

(1) Two of my recent v2.1 simulations have large monthly wave output file (about 340 MB for each monthly file). As far as I know, I'm not running with the wave model. 

`-rw-r--r-- 1 ac.golaz E3SM 347M Nov 11 14:33 v2_1.LR.abrupt-4xCO2_0101.mpaso.waveOutput.0150-12-01_00.00.00.nc`

The simulations are

```
/lcrc/group/e3sm/ac.golaz/E3SMv2_1/v2_1.LR.abrupt-4xCO2_0101
/lcrc/group/e3sm/ac.golaz/E3SMv2_1/v2_1.LR.1pctCO2_0101
```

(2) Short term archiving does not move mpaso.waveOutput files.

**Comment by jonbob** [comment]
@golaz - it looks like there's an implementation bug in the mpaso buildnml to determine when the waveOutput stream should be added to streams.ocean. Your case correctly has 
````
   <entry id="MPASO_WAVE" value="false">
````
which should keep that stream from being added. I'm sure @sbrus89 will be able to fix it quickly

**Comment by sbrus89** [comment]
@golaz, sorry for the inconvenience. Thank you for pointing this out. I opened #5302 to address this.

**Comment by sbrus89** [comment]
To clarify, #5302 addresses the issue (1). Fixing (2) requires a PR to cime, which is on my todo list.
