### ISSUE TITLE
MOSART: Use of uninitialized variable

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/E3SM#5332]
Here:
https://github.com/E3SM-Project/E3SM/blob/fb7d271bfc9f343d395b4f08992cd5a949397cef/components/mosart/src/riverroute/MOSART_heat_mod.F90#L91
`Qsur` and `Qsub` are used without being initialized. I'm guessing this routine isn't used in standard configurations.

**Comment by rljacob** [comment]
No go ahead.
