### ISSUE TITLE
MPAS: mpas_dmpar uses uninitialized threadNum in mpas_dmpar_minloc_real

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/E3SM#5333]
`threadNum` isn't set in this routine:
https://github.com/E3SM-Project/E3SM/blob/fb7d271bfc9f343d395b4f08992cd5a949397cef/components/mpas-framework/src/framework/mpas_dmpar.F#L1000-L1026

**Comment by ambrad** [comment]
@jonbob I doubt this is urgent because I'm guessing the routine is never used in practice, but I figured I'd ping you so you'd know about this uninitialized variable.

**Comment by jonbob** [comment]
Thanks @ambrad -- always appreciate the chance to clean up code! We'll get on it
