### ISSUE TITLE
Bug in MPAS-ocean split implicit solver

### ISSUE THREAD

**Issue by vanroekel** [E3SM-Project/E3SM#5361]
When running in debug on anvil @scalandr encountered the following error 
```
forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable GLOBALREPRODSUM2FLD1 when it is not allocated

```
Looking into the code it is this function call that is the problem  https://github.com/E3SM-Project/E3SM/blob/master/components/mpas-ocean/src/mode_forward/mpas_ocn_time_integration_si.F#L1174-L1179

The allocate of the array mentioned in the error is here  https://github.com/E3SM-Project/E3SM/blob/master/components/mpas-ocean/src/mode_forward/mpas_ocn_time_integration_si.F#L645-L657

The array allocate is wrapped in an `if(config_btr_si_partition_mach_mode)` so if that variable is false the array is never allocated and the error occurs.

An easy solution is to have the allocation and later deallocation occur regardless of `config_btr_si_partition_mach_mode`, but wonder if this is the most appropriate solution.  What is your desired behavior @hyungyukang?

**Comment by hyungyukang** [comment]
@vanroekel, Thanks for reporting this. I see what's the problem. Actually I made some changes for this part in the GPU-accelerated SI solver code. But I still haven't uploaded it yet, because there is another problem when running with GPU. I'm going to fix this part first.

**Comment by hyungyukang** [comment]
@vanroekel and @scalandr, I've updated the SI solver code (mostly baroclinic parts as in the split-explicit code) and fixed the allocation bug. Could you please re-try your simulation? Please use this branch: [hkang/ocean/si-bug-fix](https://github.com/E3SM-Project/E3SM/compare/hkang/ocean/si-bug-fix). Once your simulation is running appropriately, I will open a PR for this update. 
So far, the branch passed `PEM_Ln9_D.T62_oQU240.GMPAS-IAF.cori-knl_gnu` and `SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu` using configurations `config_time_integrator = 'split_implicit'` and `config_btr_si_partition_match_mode = .true.`
