### ISSUE TITLE
Build system slowness, pauses on Chrysalis.

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#5392]
See #5392 for one specific example of slowness on Chrysalis.

Other weirdness:
I usually run ./case.build at my prompt while logged in to chrlogin1.  I'll just open another window/login while I'm waiting.   Many times, the output from case.build will freeze.  The window doesn't respond to hitting the return key.  Then, after a few minutes, I either get a newline (and later the MODEL BUILD HAS FINISHED SUCCESSFULLY message) or find my connection has dropped.  When logging back and checking CaseStatus, sometimes the build has finished, sometimes I have to restart ./case.build.  It usually finishes the second time.

more example in comments below.

**Comment by rljacob** [comment]
Nevermind.  Found the real problem.  See #5393

**Comment by rljacob** [comment]
Reopening because there is just to much weird slowness on chrysalis.

**Comment by rljacob** [comment]
Changed issue description.  Use comments for more examples.

**Comment by jgfouca** [comment]
@rljacob , I assume I can close this? You can reopen with updates if needed.

**Comment by rljacob** [comment]
Yeah this was probably some filesystem issue.
