### ISSUE TITLE
./case.build fails after successful build

### ISSUE THREAD

**Issue by oksanaguba** [E3SM-Project/E3SM#5422]
Chrysalis, today's master, using ./case.build 2x in a row leads to the model being built successfully at first, and build fail for kokkos for the 2nd instance.

The script:
```
#!/bin/bash -e
#SBATCH --job-name ogtests
##SBATCH -p acme-medium
##SBATCH -p compute
#SBATCH -p debug
##SBATCH --account=condo           
#SBATCH -N 1
#SBATCH --time=3:30:00


#The -e option means "if any pipeline ever ends with a non-zero ('error') exit status, terminate the script immediately". 

which=acme-integrator
fol=test-master-build2x
nn=64
fcomp=F2010
${which}/cime/scripts/create_newcase -case $fol -res ne4_oQU240 -mach chrysalis -compiler intel -compset $fcomp
cd $fol

./xmlchange CAM_TARGET=theta-l

if true; then
ncore=64
./xmlchange NTASKS=${nn}
./xmlchange NTHRDS=1
./xmlchange MAX_MPITASKS_PER_NODE=$ncore
./xmlchange MAX_TASKS_PER_NODE=$ncore

if true; then
./xmlchange --file env_mach_pes.xml NTASKS_ATM=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_CPL=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_OCN=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_WAV=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_GLC=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_ROF=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_LND=${nn}
#do not modify these!
./xmlchange --file env_mach_pes.xml NTASKS_ICE=64
./xmlchange --file env_mach_pes.xml NTASKS_ESP=1
./xmlchange ROOTPE=0
fi

fi

./case.setup

./case.build
./case.build
```

Result:
```
[ac.onguba@chrlogin1 ~]$ grep BUILD slurm-277623.out 
MODEL BUILD HAS FINISHED SUCCESSFULLY
[ac.onguba@chrlogin1 ~]$ grep FAILED slurm-277623.out 
ERROR: /gpfs/fs1/home/ac.onguba/acme-integrator/share/build/buildlib.kokkos FAILED, cat /lcrc/group/e3sm/ac.onguba/scratch/chrys/test-master-build2x/bld/kokkos.bldlog.230128-011758
```

**Comment by jgfouca** [comment]
@oksanaguba , I tried on mappy and it worked fine. On chrysalis, I get the same failure as you. The actual error:

```
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /usr/local/include
CMake Error at core/src/cmake_install.cmake:46 (file):
  file INSTALL cannot set permissions on "/usr/local/include": Operation not
  permitted.
Call Stack (most recent call first):
  core/cmake_install.cmake:47 (include)
  cmake_install.cmake:47 (include)
```

It's like CMake got confused about the prefix.

**Comment by jgfouca** [comment]
@oksanaguba , I found the root of the problem. If I try to configure kokkos twice without blowing away the build directory, it sets the prefix to /usr/local:

```
% cmake -DKokkos_ENABLE_SERIAL=On -DCMAKE_CXX_COMPILER=icpc -DCMAKE_INSTALL_PREFIX=/lcrc/group/e3sm/ac.jgfouca/scratch/chrys/test-master-build2x/bld/intel/openmpi/nodebug/nothreads/mct /lcrc/group/e3sm/ac.jgfouca/scratch/chrys/E3SM/externals/kokkos
...

% grep PREFIX CMakeCache.txt
CMakeCache.txt:CMAKE_INSTALL_PREFIX:PATH=/lcrc/group/e3sm/ac.jgfouca/scratch/chrys/test-master-build2x/bld/intel/openmpi/nodebug/nothreads/mct

% cmake -DKokkos_ENABLE_SERIAL=On -DCMAKE_CXX_COMPILER=icpc -DCMAKE_INSTALL_PREFIX=/lcrc/group/e3sm/ac.jgfouca/scratch/chrys/test-master-build2x/bld/intel/openmpi/nodebug/nothreads/mct /lcrc/group/e3sm/ac.jgfouca/scratch/chrys/E3SM/externals/kokkos
...

% grep PREFIX CMakeCache.txt
CMakeCache.txt:CMAKE_INSTALL_PREFIX:PATH=/usr/local
```

So this appears to be a problem with Kokkos. Un-assigning myself.

**Comment by oksanaguba** [comment]
Are you saying this is in kokkos submodule? i haven't tried standalone kokkos. i will try that, thanks.

**Comment by jgfouca** [comment]
Yes, there's something going wrong in the kokkos submodule. What I don't understand is why I don't see this behavior on other machines.

**Comment by oksanaguba** [comment]
@jgfouca isn't it expected that if cmake config line is called again, then cmake cache is erased first?

**Comment by jgfouca** [comment]
@oksanaguba , no, the point of the cache is to preserve cache-var settings when repeating cmake calls, so you can re-call cmake without having to provide all your `-DX=Y` arguments again. If you do provide a new `-DX=Y` on a re-call, it's supposed to take the new value over the cached value.

**Comment by jonbob** [comment]
who's in charge of the kokkos submodule? I'm seeing this problem as well -- it means we can't build the code and then change some small thing and rebuild without cleaning the build first. It makes development even more time-consuming

**Comment by oksanaguba** [comment]
i will make an issue in main kokkos repo. one solution is to cd to bld/cmake-bld and build there (does it work for mpas? i use the same script for the 1st and all other builds, so i do not like it, but...), or you could just point your kokkos module to another commit.

**Comment by oksanaguba** [comment]
Current kokkos master has the same issue, https://github.com/kokkos/kokkos/issues/5863 .

**Comment by jgfouca** [comment]
@oksanaguba , that's unfortunate. You can use my standalone demonstration of the bug from above in the bug ticket. What will make the bug harder for them to fix is that it only seems to happen on certain machines, like chrysalis. I was not able to reproduce the problem on mappy.

**Comment by oksanaguba** [comment]
Tes, when i created a kokkos issue, they said they could not reproduce. At the moment i am trying to bisect kokkos repo, except the very first commit i picked to use gets cmake freeze on chrysalis.

**Comment by jgfouca** [comment]
@oksanaguba , do any of them have access to chrysalis? Is there something about chrysalis that exposes the error (ARCH, the backends we have enabled, etc)? I remember the cmake version on chrysalis was quite recent, so I don't think that's it.

**Comment by oksanaguba** [comment]
I also tried a different cmake vertion on chrysalis, so far it is all the same.

**Comment by jgfouca** [comment]
@oksanaguba , how comfortable are you in cmake? We may need to add the cmake equivalent of printfs to see exactly where things start going wrong. There is some point in the cmake program where `CMAKE_INSTALL_PREFIX` is getting set to the wrong value.

**Comment by oksanaguba** [comment]
I do not know cmake well. I tried to see if there is verbose option for cmake (not make) and did not find it. I see that the trivial output differs from iteration 1 to iteration 2, like this:
```
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= icpc
```

**Comment by jgfouca** [comment]
@oksanaguba , would you like me to do some digging?

**Comment by oksanaguba** [comment]
Yes, thanks!

**Comment by jgfouca** [comment]
@oksanaguba , no problem. Can you paste a link to your kokkos ticket here?

**Comment by oksanaguba** [comment]
https://github.com/kokkos/kokkos/issues/5863
