### ISSUE TITLE
Slightly re-arranging directory structure for mpas-seaice testing

### ISSUE THREAD

**Issue by proteanplanet** [E3SM-Project/E3SM#5440]
To accommodate new E3SM testing infrastructure coming to the sea ice model, I would like to suggest rearranging the directory tree under https://github.com/E3SM-Project/E3SM/tree/master/components/mpas-seaice, whereby the current directory,  "testing_and_setup", and all of its contents, which I believe is for running mpas-seaice outside of the E3SM framework, is renamed "mpas", and is shifted down one notch to under a new directory named "test", thus copying the EAM hierarchy.  We would then add a second directory under "test" named "e3sm" which will include infrastructure for single column testing and new scripts within E3SM, such as https://github.com/E3SM-Project/SimulationScripts/blob/master/archive/PPSLRCI/E3SM_SeaIce_Developer.sh, thus ending up with a new directory tree for mpas-seaice:

E3SM/components/mpas-seaice

<img width="539" alt="Screen Shot 2023-02-07 at 1 18 19 PM" src="https://user-images.githubusercontent.com/14379090/217355739-afbcb2df-a562-4f48-a068-72f8d9f5b099.png">

Please comment if you vehemently disagree, and also mention if there are any relative directory locations or names scripted under the existing "testing_and_setup" that would be affected by this change.

**Comment by njeffery** [comment]
I like it.

**Comment by erinethomas** [comment]
this works for me.

**Comment by eclare108213** [comment]
I like it too.

**Comment by darincomeau** [comment]
looks good to me.

**Comment by jonbob** [comment]
works for me

**Comment by proteanplanet** [comment]
After consultation with @akturner and @njeffery, @jonbob and I will change this plan so that stand-alone test code is not being kept in two places at once (MPAS-Dev and E3SM-Project).  The new plan is to create a new test directory, with the new E3SM-Polar-Developer.sh script under an E3SM subdirectory, and a submodule for the MPAS-Dev standalone testing mainly developed by @akturner situated under an adjacent MPAS subdirectory.  At @jonbob suggestion, we will first submit a PR to add this new test directory and content, and then I will approve deletion of the aging stand-alone testing code in https://github.com/E3SM-Project/E3SM/pull/5477.  It will be my responsibility to keep the hash up to date, with prompting from @akturner

**Comment by proteanplanet** [comment]
This issue is being closed, now with the MPAS testing infrastructure removed, and just one script currently in PR for testing of the sea ice model in the E3SM framework.
