### ISSUE TITLE
Compiler optimization flags specification

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#5446]
@oksanaguba mentioned that although she used `-O2` in machine config for building, apparently some files were compiled using `-O3`.

Since we want a reliable mechanism to study impact of optimizations, I think compiler opt flags should be explicitly specified in the machine macros and shouldn't be overridden. We should consider the best way to handle library builds as well in concurrence.

@ambrad suggested discussion with @bartgol and @jgfouca.

Example:
```
er/fgpu-build-feb10-r8-o2flag/bld/crayclang-scream/mpich/nodebug/threads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/include -I/autofs/nccs-svm1_home1/onguba/scream-amb2/components/eamxx/../../externals/scorpio/src/clib --amdgpu-target=gfx90a -fno-gpu-rdc -I/opt/cray/pe/mpich/8.1.23/ofi/crayclang/10.0/include -Wall -O3 -DNDEBUG -O3 -fno-gpu-rdc --offload-arch=gfx90a -std=gnu++14 -MD -MT eamxx/src/mct_coupling/CMakeFiles/theta-l_kokkos_4_72_10.dir/__/__/__/homme/src/share/cxx/CaarFunctor.cpp.o -MF CMakeFiles/theta-l_kokkos_4_72_10.dir/__/__/__/homme/src/share/cxx/CaarFunctor.cpp.o.d -o CMakeFiles/theta-l_kokkos_4_72_10.dir/__/__/__/homme/src/share/cxx/CaarFunctor.cpp.o -c /autofs/nccs-svm1_home1/onguba/scream-amb2/components/homme/src/share/cxx/CaarFunctor.cpp
```

cc @mt5555

**Comment by bartgol** [comment]
I disagree that we should not be able to override flags. I mean, for a general production run, it might be an acceptable approach, but as a developer, I want to be able to build component X in debug mode, and component Y in release mode. Furthermore, we sometimes run into very peculiar issues, perhaps related to compilers or TPLs bugs, which we can only work around by reducing opt level of a single file. Although that's not optimal, sometimes it's too time consuming to track down the origin of the issue (especially if it _is_ a compiler/tpl bug).

I think machine files should contain _default_ opt flags, but individual component should be able to change them. At least for a power-user scenario.

**Comment by sarats** [comment]
Shouldn't master reflect production scenario? Your example is a developer/debugging scenario.

> only work around by reducing opt level of a single file
That's what Depends files are for. 

In above case, we want -O2 builds. What's your option for that?

**Comment by sarats** [comment]
cc @rljacob

**Comment by bartgol** [comment]
> That's what Depends files are for.

I don't know what Depends files are :) 

As for why  -O3 gets injected, I suspect is b/c of `CMAKE_<LANG>_FLAGS_RELEASE` (and similarly for other build types). If `CMAKE_BUILD_TYPE` is defined, cmake will attach `CMAKE_<LANG>_FLAGS_${CMAKE_BUILD_TYPE}` to the flags, putting them _at the end_ of the already declared flags. The rationale is that these vars should contain optimization flags, or, more generally, flags that should be added to _all_ files.

A project _should_ ensure that these vars contain what's best for the project. Perhaps E3SM needs to set these according to mach files?

**Comment by sarats** [comment]
Yes, I thought our CMake config already does this. We **don't want** CMake picking the flag for us.

**Comment by rljacob** [comment]
I don't know if this changed with the conversion to cmake but the old system was to have a production-ready optomized flag setting for each compiler set at a top level which would then be applied to every file.   Then the machine file could add (or replace?) the flags for the compiler, but it would still apply for the whole build.  Then Depends file is used for  any per-file compiler settings.   The DEBUG=TRUE flag would switch everything to use the debugging flags with the same hierarchy.   I don't think we ever had an easy way to set debug or non-debug on a component basis.

**Comment by bartgol** [comment]
Notice that a component can do
```

**Comment by sarats** [comment]
Back to the main question, how do we ensure CMake is setting our project preferred opt level?

**Comment by jgfouca** [comment]
Hi all,

The transition to CMake was awkward due to needing to support backwards compatibility and not wanting to totally rewrite CIME etc, so we are doing many things in a non-standard way. Don't forget our build system also manages the builds of shared libs, some of which don't use CMake as their build system.

A couple examples of non-standard E3SM-isms:
1) E3SM build system does not use CMAKE_BUILD_TYPE, we use the DEBUG setting from CIME to set flags
2) We don't use CMAKE_$LANG_FLAGS or anything variables that have special meaning in CMake
3) We use Depends files to specify flag modifications on specific platforms

I'm sure there are more items that I cannot think of.

@sarats, all you should need is something like this:
```
if (NOT DEBUG)
  string(APPEND FFLAGS " -O2")
endif()
```

**Comment by sarats** [comment]
@oksanaguba That's what your build had for CXXFLAGS, correct?

**Comment by jgfouca** [comment]
Just a tip: once the build is done, you can look at $case/Macros.make to get an idea of how the Cmake macro tree was resolved.

**Comment by oksanaguba** [comment]
@sarats i do not think i found explicitly set opt. flags for CXXFLAGS anywhere for crusher. O2 was set explicitly for CFLAGS and FFLAGS. Originally sorting out opt flags wasn't a priority, but now it is. Except that it seems that O3 is there for scream/dycore files by default.

**Comment by sarats** [comment]
So my PR has following:
https://github.com/E3SM-Project/E3SM/pull/5444/files#diff-9e2f04a98dd1e364535f06f5d3b62c2c95d522caeff7a1b9cd2ab6eaae10ebe1R34-R38

```
if (NOT DEBUG)
  string(APPEND CFLAGS   " -O2")
  string(APPEND CXXFLAGS " -O2")
  string(APPEND FFLAGS   " -O2")
endif()
```

Don't you have a similar section for yours?

**Comment by oksanaguba** [comment]
yes, but only 
```
if (NOT DEBUG)
  string(APPEND CFLAGS " -O2 -hnoacc -hfp0 -hipa0")
  string(APPEND FFLAGS " -O2 -hnoacc -hfp0 -hipa0")
endif()
```
This is in scream repo, of course.

**Comment by jgfouca** [comment]
@oksanaguba , I think you just need to add a similar line for CXXFLAGS

**Comment by oksanaguba** [comment]
yes, thanks. maybe i misunderstood previous messages. we can add this flag.

**Comment by rljacob** [comment]
@jgfouca is there any equivalent to the old global compiler settings that were in config_compilers.xml (A default set of flags for each compiler was at the top of that file.)

**Comment by jgfouca** [comment]
@bartgol, thanks. I forgot about that change.

@rljacob, yes, that would be the compiler macro (e.g. `gnu.cmake`). That macro gets processed before the machine-specific macros.

**Comment by bartgol** [comment]
@jgfouca We should probably also change EKAT then, since it automatically sets RELEASE/DEBUG flags to "-O3" / "-g" as part of `SetCommonFlags`. We should leave the decision for these flags to the host project.

**Comment by jgfouca** [comment]
@bartgol , agree.

**Comment by sarats** [comment]
Definitely!

**Comment by sarats** [comment]
@jgfouca Minor clarification, you mean each compiler_base.cmake would be invoked before the machine specific one, right?
For instance, crayclang.cmake before crayclang_frontier.cmake.

**Comment by jgfouca** [comment]
@sarats , yes, the `$compiler_$machine.cmake` macro gets processed last.

**Comment by sarats** [comment]
At this point, this looks resolved.
