### ISSUE TITLE
Runtime error with nvidia compiler using threads in LND with SMS.r05_r05.IELM.pm-cpu_nvidia.elm-topounit

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5450]
Using nvidia compiler on pm-cpu, this test fails:
`SMS.r05_r05.IELM.pm-cpu_nvidia.elm-topounit`
Default is to use 64 MPI's and 2 threads.
Running with `PMx1` (ie, no threads), the test completes.
Also verified that 1 thread for LND only still works -- using 64x2 for all other components.

In elm.log:
```
 dtime_sync=          1800  dtime_elm=          1800  mod =             0
 Beginning timestep   : 0001-01-01_00:00:00
    Completed timestep: 0001-01-01_00:00:00
 Beginning timestep   : 0001-01-01_00:30:00
 aerodynamic parameter error in UrbanFluxes
 h_r - z_d <= z_0
 ht_roof, z_d_town, z_0_town:     3.000000000000000
    23.94499219281045         1.277023251147663
 elm model is stopping
 local  landunit index =          4492
 global landunit index = ERROR:
 get_proc_bounds ERROR: Calling from inside  a threaded region
```

With DEBUG build, I see this error in e3sm.log:
```
 0: MCT::m_Router::initp_: GSMap indices not increasing...Will correct
 0: MCT::m_Router::initp_: RGSMap indices not increasing...Will correct
 0: MCT::m_Router::initp_: RGSMap indices not increasing...Will correct
 0: MCT::m_Router::initp_: GSMap indices not increasing...Will correct
 0: Warning: ieee_underflow is signaling
 0: Warning: ieee_inexact is signaling
 0: FORTRAN STOP
 0: double free or corruption (out)
```

Note similar to https://github.com/E3SM-Project/E3SM/issues/5384

**Comment by ndkeen** [comment]
I verified that if I leave all components with 2 threads and set LND to have 1 thread, the DEBUG case completes.

So there is something in LND that is getting confused with threading and nvidia compiler.

**Comment by rljacob** [comment]
Discussion during telecon:  related to topo

**Comment by ndkeen** [comment]
Was there a change that could have impacted this?  I no longer see it failing on cdash?

Will run test now with next.

Could be good to match PR's to fixes.

**Comment by ndkeen** [comment]
Passed again, so will close.  I wonder if some inputdata was updated?
