### ISSUE TITLE
ERP test with ne4pg2 failed on Compy

### ISSUE THREAD

**Issue by huiwanpnnl** [E3SM-Project/E3SM#5503]
The `e3sm_atm_developer` test suite does not have an `ERP` test for the pg2 grid, so I tried one but found it to fail on Compy. Then I added the following suite in `cime_config/tests.py` to diagnose the issue:

```
    "eam_ne4_vs_ne4pg2" : {
        "tests"   : (
            "ERP_Ln18.ne4_oQU240.F2010",
            "ERP_Ln18.ne4pg2_oQU480.F2010",
            "SMS_Ln18.ne4pg2_oQU480.F2010",
            "REP_Ln18.ne4pg2_oQU480.F2010",
            "ERS_Ln18.ne4pg2_oQU480.F2010",
            "PET_Ln18.ne4pg2_oQU480.F2010",
            "PEM_Ln18.ne4pg2_oQU480.F2010",
            )
        },
```
and here are the results from Compy:

```
PASS ERP_Ln18.ne4_oQU240.F2010.compy_intel RUN

FAIL ERP_Ln18.ne4pg2_oQU480.F2010.compy_intel (phase RUN)
PASS SMS_Ln18.ne4pg2_oQU480.F2010.compy_intel RUN
PASS REP_Ln18.ne4pg2_oQU480.F2010.compy_intel RUN
FAIL ERS_Ln18.ne4pg2_oQU480.F2010.compy_intel (phase RUN)
PASS PET_Ln18.ne4pg2_oQU480.F2010.compy_intel RUN
FAIL PEM_Ln18.ne4pg2_oQU480.F2010.compy_intel (phase RUN)
```

To repeat my test, please use the following commands:

```
git clone -b huiwanpnnl/atm/eam_ne4_vs_ne4pg2 --recursive git@github.com:E3SM-Project/E3SM.git eam_ne4_vs_ne4pg2
cd eam_ne4_vs_ne4pg2/cime/scripts
./create_test eam_ne4_vs_ne4pg2 --wait
```

The branch [`huiwanpnnl/atm/eam_ne4_vs_ne4pg2`](https://github.com/E3SM-Project/E3SM/tree/huiwanpnnl/atm/eam_ne4_vs_ne4pg2) is identical to today's master except for the addition of the `eam_ne4_vs_ne4pg2` test suite defined above.

**Comment by rljacob** [comment]
@amametjanov can you see if you can reproduce on Chrysalis?

**Comment by ambrad** [comment]
I think there might be a time step divisibility issue affecting the restart tests. The PEM test is also failing in the RUN phase, not the COMPARE phase, so something might be amiss without the PE layouts. On Chrysalis, I switched Ln22 to Ld3 and get all PASSes in COMPARE:
```
     PASS ERP_Ld3.ne4_oQU240.F2010.chrysalis_intel COMPARE_base_rest
    PASS ERP_Ld3.ne4pg2_oQU480.F2010.chrysalis_intel COMPARE_base_rest
    PASS ERS_Ld3.ne4pg2_oQU480.F2010.chrysalis_intel COMPARE_base_rest
    PASS PEM_Ld3.ne4pg2_oQU480.F2010.chrysalis_intel COMPARE_base_modpes
    PASS PET_Ld3.ne4pg2_oQU480.F2010.chrysalis_intel COMPARE_base_single_thread
    PASS REP_Ld3.ne4pg2_oQU480.F2010.chrysalis_intel COMPARE_base_rep2
```
@huiwanpnnl I suggest you rerun with Ld3. If we still see test failures, then someone can look into compiler flag issues for compy_intel. Note the nightly testing for compy_intel is pretty thin. e3sm_integration has a number of PEM/T, ERS/P tests for various pg2 grid aliases.

**Comment by huiwanpnnl** [comment]
Thank you @ambrad. 

I reran with Ld3 and got a PASS for ERS (and PET, REP) in COMPARE:

```
    PASS ERP_Ld3.ne4_oQU240.F2010.compy_intel COMPARE_base_rest
    PASS ERS_Ld3.ne4pg2_oQU480.F2010.compy_intel COMPARE_base_rest
    PASS PET_Ld3.ne4pg2_oQU480.F2010.compy_intel COMPARE_base_single_thread
    PASS REP_Ld3.ne4pg2_oQU480.F2010.compy_intel COMPARE_base_rep2
```

PEM failed (as should be expected from the Ln18 results, I suppose?):
```
FAIL PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel (phase RUN)
```

**Comment by jonbob** [comment]
As @ambrad said, the PEM test may have failed due to a layout issue.  I'll run it and see if that's correct and look for a fix

**Comment by jonbob** [comment]
This is just due to a missing mpas-seaice graph file. Let me create that and the test should then pass fine. Oh wait, it already exists but I think the scripts fail to download it automatically when it the second case I'll just copy it by hand and retry

**Comment by jonbob** [comment]
OK, it now passes for me:
````
PASS PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel CREATE_NEWCASE
PASS PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel XML
PASS PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel SETUP
PASS PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel SHAREDLIB_BUILD time=350
PASS PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel MODEL_BUILD time=920
PASS PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel SUBMIT
PASS PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel RUN time=95
PASS PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel COMPARE_base_modpes
PASS PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel MEMLEAK
PASS PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel SHORT_TERM_ARCHIVER
````
@huiwanpnnl, can you also please give it a try?

**Comment by huiwanpnnl** [comment]
Thank you very much, @jonbob. With your graph file and following @ambrad's suggestion of using Ld3, I now get PASSes for all of the following:

```
  ERP_Ld3.ne4_oQU240.F2010.compy_intel (Overall: PASS) details:
  ERP_Ld3.ne4pg2_oQU480.F2010.compy_intel (Overall: PASS) details:
  ERS_Ld3.ne4pg2_oQU480.F2010.compy_intel (Overall: PASS) details:
  PEM_Ld3.ne4pg2_oQU480.F2010.compy_intel (Overall: PASS) details:
  PET_Ld3.ne4pg2_oQU480.F2010.compy_intel (Overall: PASS) details:
  REP_Ld3.ne4pg2_oQU480.F2010.compy_intel (Overall: PASS) details:
```

**Comment by huiwanpnnl** [comment]
@rljacob, I guess we could close this issue now, noting that for restart tests with `ne4pg2`, we should do `_Ld3` instead of `_Ln18`.
