### ISSUE TITLE
Missing CMake macro files for crusher-scream-cpu

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#5546]
crusher-scream-cpu supports 3 compilers:
```
  <machine MACH="crusher-scream-cpu">
    ...
    <COMPILERS>gnu,crayclang-scream,amdclang</COMPILERS>
```

However, we only have crayclang-scream_crusher-scream-cpu.cmake so far.

gnu_crusher-scream-cpu.cmake is missing:
There are some build errors with "--machine=crusher-scream-cpu --compiler=gnu"

amdclang_crusher-scream-cpu.cmake is also missing:
No build errors with "--machine=crusher-scream-cpu --compiler=amdclang", but
PnetCDF is disabled in SCORPIO (PNETCDF_PATH is not set).

**Comment by ambrad** [comment]
Hi @dqwu I'm removing myself as the assignee because I don't support the Crusher CPU builds for SCREAM. Our interest is in the GPUs, not the CPUs. We don't have the resources to support all possible build options. Sorry.
