### ISSUE TITLE
homme_tool fail to build on Perlmutter

### ISSUE THREAD

**Issue by hyma68** [E3SM-Project/E3SM#5550]
Hi,

I was trying to build homme_tool on Perlmutter to create different topo files for various RRM configurations but can't get it done because of a "pio_mod" not found issue. I was following the guide on the following two confluence pages. 

https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/2712338924/V3+Topography+GLL+PG2+grids
https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/872579110/Running+E3SM+on+New+Grids#5.-Generate-topography-file

Here is the command I use to compile homme_tool (I source the /global/common/software/e3sm/anaconda_envs/load_latest_e3sm_unified_pm-cpu.sh before building this)

--
cmake -C /pscratch/sd/h/hyma/RRM/E3SM/components/homme/cmake/machineFiles/perlmutter-gnu.cmake -DPREQX_NP=4 /pscratch/sd/h/hyma/RRM/E3SM/components/homme
make -j4 homme_tool
--

The error message I got is 

[ 83%] Building Fortran object src/tool/CMakeFiles/homme_tool.dir/__/share/planar_mesh_mod.F90.o
cd /global/homes/h/hyma/CODE/E3SM/homme_build/src/tool && /pscratch/sd/h/hyma/RRM/E3SM/externals/kokkos/bin/kokkos_launch_compiler /pscratch/sd/h/hyma/RRM/E3SM/externals/kokkos/bin/nvcc_wrapper /opt/cray/pe/craype/2.7.19/bin/CC /opt/cray/pe/craype/2.7.19/bin/ftn -DCPRGNU -DHAVE_CONFIG_H -DHOMMEXX_CONFIG_IS_CMAKE -DHOMME_WITHOUT_PIOLIBRARY -DINCLUDE_CMAKE_FCI -DLINUX -DSPMD -D_NO_MPI_RSEND -I/global/homes/h/hyma/CODE/E3SM/homme_build -I/global/homes/h/hyma/CODE/E3SM/homme_build/src/tool -I/global/homes/h/hyma/CODE/E3SM/homme_build/utils/cime/CIME/non_py/src/timing -I/global/homes/h/hyma/CODE/E3SM/homme_build/src/tool/homme_tool_modules -I/global/homes/h/hyma/CODE/E3SM/homme_build/utils/csm_share/modules -I/global/homes/h/hyma/CODE/E3SM/homme_build/kokkos/build/core/src -I/pscratch/sd/h/hyma/RRM/E3SM/externals/kokkos/core/src -I/global/homes/h/hyma/CODE/E3SM/homme_build/kokkos/build/containers/src -I/pscratch/sd/h/hyma/RRM/E3SM/externals/kokkos/containers/src -I/pscratch/sd/h/hyma/RRM/E3SM/components/homme/../../externals/kokkos/core/src -I/pscratch/sd/h/hyma/RRM/E3SM/components/homme/../../externals/kokkos/containers/src -I/pscratch/sd/h/hyma/RRM/E3SM/components/homme/../../externals/kokkos/algorithms/src -I/global/homes/h/hyma/CODE/E3SM/homme_build/kokkos/build -I/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/cuda/11.7/include -w -fallow-argument-mismatch -ffree-line-length-none -O3 -g  -Jhomme_tool_modules -c /pscratch/sd/h/hyma/RRM/E3SM/components/homme/src/share/planar_mesh_mod.F90 -o CMakeFiles/homme_tool.dir/__/share/planar_mesh_mod.F90.o
/pscratch/sd/h/hyma/RRM/E3SM/components/homme/src/tool/gll_subcell_grid.F90:12:9:

   12 |     use pio, only : file_desc_t, pio_def_dim, var_desc_t, pio_int, pio_def_var, &
      |         1
Fatal Error: Cannot open module file 'pio.mod' for reading at (1): No such file or directory
 
---
There are four machine files for Perlmutter and I tried all of them and none of them are working (perlmutter-gnu.cmake, perlmutter-nocuda-gnu.cmake, perlmutter-nocuda-nvidia.cmake, perlmutter-nvidia.cmake). I asked around and it seems no one has encountered this issue on other machines. Also, most of the people I asked are still working on cori or other machines. 

Please let me know if anyone has successfully built the homme_tool on perlmutter and how should I make any changes. Thank you. 

ps. people suggested me to post this issue on E3SM GitHub. Please point me to the right place to post this issue if this is not.

**Comment by mt5555** [comment]
@ndkeen is working on the PM machine files for standalone HOMME ( which includes the homme_tool ).   The error above means that HOMME's build system didn't compile PIO.  It could be that the PIO submodule was not downloaded (i.e. after cloning the E3SM did you run the commands to init all the submodules, per E3SM developer's guide?).   Or it couldn't compile PIO for some reason (but then I think it would error out earlier).  

As a short term workaround, you could try running on Cori instead of PM, as Cori is known to have a working machine file.

**Comment by hyma68** [comment]
Hi Mark @mt5555 

Thanks for the suggestion and comment. I was actually able to got homme_tool executable compiled with the following steps on Perlmutter. Forgot to update the issue here.

source /global/common/software/e3sm/anaconda_envs/load_latest_e3sm_unified_pm-cpu.sh
eval $(/pscratch/sd/h/hyma/RRM/E3SM/cime/CIME/Tools/get_case_env)
cmake -C /pscratch/sd/h/hyma/RRM/E3SM/components/homme/cmake/machineFiles/perlmutter-nocuda-gnu.cmake -DBUILD_HOMME_WITHOUT_PIOLIBRARY=OFF -DPREQX_PLEV=26 /pscratch/sd/h/hyma/RRM/E3SM/components/homme/
make -j4 homme_tool

I followed the steps on V3 Topography: GLL/PG2 grids E3SM confluence page. There was a recent update by Ben Hillman. I don't know which machine he was using but those steps work for my on Perlmutter. Apparently, "-DBUILD_HOMME_WITHOUT_PIOLIBRARY=OFF" is the right flag to use. I tried a different flag to turn off pio compile when I first got the error message but it didn't work. 

https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/2712338924/V3+Topography+GLL+PG2+grids

**Comment by mt5555** [comment]
One note of caution: since you mentioned the "V3" topography page.  That's the rougher topography that was recently made the default in SCREAM and will hopefully be considered for V3.  If you want to use it in the current EAM compsets, you need two additional namelist options ( pgrad_correction=1, hv_ref_profiles=6).   If you are running V2 or current V3 EAM, you might want to use the smoother topography given on the V2 topography page.

**Comment by hyma68** [comment]
Thank you @mt5555 . I am doing SCREAM-RRM runs so I am referring to the V3 topo page.

**Comment by mt5555** [comment]
PM-CPU machine files added, homme_tool now undergoing nightly testing on perlmutter:

https://my.cdash.org/builds/2663866
