### ISSUE TITLE
Inconsistent default atm masterfield list between F and B cases after merging UCI-chem

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#5613]
This occur in next after merging #4707 (hash: 3136fb9ac81654935edb091b4a6097cb62fcba08)

Example tests are

```
SMS_Ld1.ne30pg2_r05_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod_1850_r05
SMS_Ln5.ne30pg2_r05_oECv3.F2010.chrysalis_intel.eam-wcprod_F2010.20230421_082849_ytrn83
```
The wcprod tests set to exclude some fields in the form of

 fexcl1 = 'CFAD_SR532_CAL', 'LINOZ_DO3', 'LINOZ_DO3_PSC', 'LINOZ_O3CLIM', 'LINOZ_O3COL', 'LINOZ_SSO3'

During runtime, B case failed because it didn't see fields like 'LINOZ_DO3', 'LINOZ_O3CLIM' in the FLDLST, while F case didn't complain.

It might suggest linoz was not enabled at all for B case.

**Comment by wlin7** [comment]
Indeed, runtime, it says do_lin_strat_chem= F linoz_v2= F linoz_v3= F. 

That is because the linoz data has been updated, and the logical control do_lin_strat_chem is conditioned on the new file.

The old file is ` linoz_data_file                = 'linoz1850-2015_2010JPL_CMIP6_10deg_58km_c20171109.nc'`
The new file is `linoz_data_file                = 'linv3_1849-2015_2010JPL_cmip6_historical_10deg_58km_c20210625.nc'
`
B case tests ok after updating linoz_data_file

**Comment by rljacob** [comment]
There's no point in making a bug report on next.   If testing on next shows that a PR has a problem, mention it in the PR comments and fit it in that PR.

**Comment by wlin7** [comment]
Huh, the purpose was not to make a report, trying to seek quick help to solve a puzzle that I couldn't figure out at the time.

**Comment by rljacob** [comment]
Ok.  And this was briefly a problem on master in hash 0a84e53e61e1dc1

**Comment by wlin7** [comment]
Yes, for a few minutes, until companion #5614 is merged. This does raise a potential problem (if https://github.com/E3SM-Project/E3SM/commit/0a84e53e61e1dc193819bd46ef604e31c04b56c6 happen to be checked out for some purpose.

**Comment by rljacob** [comment]
I'm still seeing run fail with message about "FLDLST: LINOZ_DO3                            in fexcl(           2 ) not found"
next prod anvil. hash  cf8520939a87b
SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.anvil_intel.allactive-wcprodssp
SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP585.anvil_intel.allactive-wcprodssp

**Comment by wlin7** [comment]
Yeah, the wcprodssp tests failed for the same reason, but [need a different fix ](https://github.com/E3SM-Project/E3SM/pull/5614#issuecomment-1518680695)(a new data file needs to be generated first). Good to continue to track the problem here.

**Comment by rljacob** [comment]
If this is going to take more then a few days, why not just remove the fexcl1 line from user_nl_eam in the ssp testmod?  You can add it back when the files are ready.

**Comment by wlin7** [comment]
Sounds good. We touched this option during today's meeting. I am going to test it, and if the test can go well (with essentially altered chemistry due to lack of key input file), I will put in a PR to modify the testmod.
