### ISSUE TITLE
gnu and nvidia debug mode test failure after UCI-chem PR

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#5624]
Tests like `SMS_D_Ln5.ne4_oQU240.F2010.pm-cpu_gnu` failed with following error msg
```
At line 122 of file /global/u2/w/wlin/ACME/integration/postCIME5/E3SM.activeMerge/components/eam/src/chemistry/mozart/rate_diags.F90
22: Fortran runtime error: Array bound mismatch for dimension 3 of array 'rxt_rates_vmr' (31/7)

```
The statement (L122) pointed to is `rxt_rates_vmr = rxt_rates`, where the lhs is declared as `rxt_rates_vmr(ncol,pver,gas_pcnst)
`
The test sets to use components/eam/src/chemistry/pp_linoz_mam4_resus_mom_soag/chem_mods.F90, which has gas_pcnst=31 and rxntot = 7.

rxt_rates at L122 is passed in from caller reaction_rates declared as `(ncol,pver,max(1,rxntot))`, apparently with largely 3rd dimension rate.

The code can be changed to `rxt_rates_vmr = rxt_rates(:,:,:gas_pcnst)`  [No, can't do this, see correction below]

Scientifically, is the code correct? Also interesting that debug test with intel compiler didn't pick up this issue.

[Correction: in chem_mods.F90 above, gas_pcnst=31, previously was mistaken as 6 which is for gascnt.]

**Comment by tangq** [comment]
[Blame view](https://github.com/E3SM-Project/E3SM/blame/master/components/eam/src/chemistry/mozart/rate_diags.F90#L122) shows that line 122 was added as part of the commit ([52d6eea16](https://github.com/E3SM-Project/E3SM/commit/52d6eea16e6a7431f0cf91c0d56e0ed1e87bfcfb)) to write out the vertically integrated CH4 production rate.

@hsiangheleellnl , can you help answer @wlin7 's questions? Thanks.

**Comment by keziming** [comment]
In this subroutine, it declares rxt_rates_vmr(ncol,pver,gas_pcnst)?
at above level (mo_gas_phase_chemdr.F90), reaction_rates(ncol,pver,max(1,rxntot))   

Coudl it be caused by this inconsistent?

**Comment by wlin7** [comment]
I mixed up gas_pcnst with gascnt in chem_mods.F90. `gas_pcnst=31`, actually. It is larger than `rxntot=7` in `components/eam/src/chemistry/pp_linoz_mam4_resus_mom_soag/chem_mods.F90` that is used to build the case. Should campp generate a new chem_mods.F90 for such a test?

**Comment by wlin7** [comment]
@keziming , if to run test, you can use perlmutter.

**Comment by tangq** [comment]
Yes, we should regenerate the auto-generated code (chem_mods.F90) for this test. There are two ways: 1) create a new pp_chemistry-mechanism directory which will contain the new chem_mods.F90 file; 2) use the -usr_mech_infile of CAM_CONFIG_OPTS to generate the file online. But I am not sure which fix is better because:

- The test will need to use the new chem_mods.F90 created by the chemistry pre-processor to be consistent with the chemistry mechanism, which in this case should be [pp_chemUCI_linozv3_mam4_resus_mom_soag_tag.in](https://github.com/E3SM-Project/E3SM/blob/master/components/eam/chem_proc/inputs/pp_chemUCI_linozv3_mam4_resus_mom_soag_tag.in).
- v3atm will soon merge new aerosol features (e.g., MAM5, Nitrate, etc.), which come with modifications to the mechanism. Then, we will need to create new pp directories.


> I mixed up gas_pcnst with gascnt in chem_mods.F90. `gas_pcnst=31`, actually. It is larger than `rxntot=7` in `components/eam/src/chemistry/pp_linoz_mam4_resus_mom_soag/chem_mods.F90` that is used to build the case. Should campp generate a new chem_mods.F90 for such a test?

**Comment by wlin7** [comment]
This is a v2 test, so we may not want to get linozv3 involved. Based on how rxt_rates and rxt_rates_vmr are used for the diagnostics calculations, the more straightforward fix I think is to declare having the same 3rd dimension size as rxt_rates passing in from caller, namely` rxt_rates_vmr(ncol,pver,max(1,rxntot))`. That should work since it is the only caller from gas_phase_chemdr. rxt_rate_vmr appears to be just a work array to store the input rxt_rate for additional calculations, while rxt_rate is converted to molecular number density unit for outfld.

**Comment by tangq** [comment]
@wlin7 , the logic makes sense to me. I'd defer to @hsiangheleellnl to confirm if there is any side effects. @hsiangheleellnl , can you confirm the fix suggested by Wuyin is okay?

**Comment by wlin7** [comment]
@hsiangheleellnl , @tangq . PR #5626 is created for the fix based on the above discussion. Please take a look. We can merge the PR after the tests DIFFs due to #4707 and companion PRs are cleared.

**Comment by hsiangheleellnl** [comment]
So far, I did not see anything wrong with PR #5626. Sorry for the late reply.
