### ISSUE TITLE
Randomness in computed TCO, SCO, TROPMASS after UCI-chem PR

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#5637]
The problem emerges after the tests diffs were blessed following the merge of UCI-chem (#4707) and the companion PRs.

Several of the tests returned diff again on the following variables 
`TCO, SCO, TROPMASS , TROPMASSB, TROPMASST  (some tests only the first 3)
`
The simulation results are otherwise unaffected by the diffs in these variables.

Below are some of the tests (not exhaustive) that report the problem

```
SMS_D_Ln5.ne4_oQU240.F2010.chrysalis_intel.eam-cosplite_nhtfrq5
SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod
SMS_Ld1.ne30pg2_r05_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod_1850_r05

SMS.ne30pg2_r05_oECv3.F20TR.compy_intel.eam-wcprod_F20TR
SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850-1pctCO2.compy_intel.allactive-wcprod_1850_1pctCO2
... (all compy prod tests)
```

**Comment by rljacob** [comment]
Are those quantities computed using a global sum at all?

**Comment by rljacob** [comment]
Also does this happen on other machines?

**Comment by tangq** [comment]
It might have something to do with the new tropopause algorithm, but I need more details to say for sure. I will contact @wlin7 offline.

**Comment by keziming** [comment]
@wlin7 could you share me the path of these simulations? I want to check the atm_in to make sure the configuration for chemistry is right.

**Comment by wlin7** [comment]
@rljacob , the behavior are not the same among the machines (taking the prod_next tests as example): anvil is ok, chrysalis has one, and compy has 7. It would be interesting if the issue is also related to optimization level.

@keziming , on chrysalis, here is one of the tests (not in wcprod suite)
`/lcrc/group/e3sm/e3smtest/scratch/chrys/SMS_D_Ln5.ne4_oQU240.F2010.chrysalis_intel.eam-cosplite_nhtfrq5.C.JNextIntegration20230425_233542/run`

This test shows diff in SCO, TCO and TROPMASS.

**Comment by keziming** [comment]
@wlin7 I see it is V2-linoz3-MAM4 setting. The chemUCI is off.  I am not sure if linoz3 is the potential cause. The linoz3 can provide 3D tropopause, but that relies on E90. Here is no E90 input. Maybe @tangq can provide more clear information. Another way is to set back to use linoz2 to see if linoz3 cause this issue.

**Comment by tangq** [comment]
The E90 tropopause will depend on the chemUCI mechanism, either chemUCI+Linozv3 or chemUCI+Linozv2. Since chemUCI+Linozv3 will be the E3SMv3, we probably want to (if possible) update these tests to use chemUCI+Linozv3. Thanks for looking into the details, @keziming .

**Comment by wlin7** [comment]
> What do you mean by a "v2 test"?

Though UCI-chem PR is NBFB, its core feature is not turned on when using current F2010 compset. The PR is implemented in a way to support both v2 and v3 use of Linoz (O3), but NBFB even for v2 compset. 

@tangq , @keziming , I am going to test with chemUCI-Linozv3 on.  If no problem with chemUCI-Linozv3, we may still need to find a fix  for the codes.

**Comment by rljacob** [comment]
Found one test that had diffs on only 4 of the 5 variables:
https://my.cdash.org/test/78680811
SMS_Ld1.ne30pg2_r05_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod_1850_r05.C.JNextProd20230425_223746

**Comment by wlin7** [comment]
REP test is designed to catch this kind of problem. Below are the results of 3 REP tests, using F2010 or F20TR_chemUCI-Linozv3

```
FAIL REP_D_Ln5.ne4_oQU240.F2010.chrysalis_intel.eam-cosplite_nhtfrq5                                       
PASS REP_D_Ln5.ne4pg2_oQU480.F2010.chrysalis_intel.eam-cosplite_nhtfrq5                                 
PASS REP_D_Ln5.ne4pg2_oQU480.F20TR_chemUCI-Linozv3.chrysalis_intel.eam-ne4_v3atm_rtmoff  (need changes in mo_exp_sol.F90)
```

Look like the problem is more than about the chem/phys option

**Comment by jonbob** [comment]
@wlin7 - I ran this test on chrysalis with some extra debug flags and found some uninitialized variables that might be responsible for this random behavior. One is in tropopause.F90 in subroutine tropopause_e90_3d_output, where the compiler was complaining about tropP and tropT. I added:
````
    ! Find the tropopause
    call tropopause_e90_3d(pstate, tropLevB, tropLevU, tropFlag, tropFlagInt, tropP=tropP, tropT=tropT, tropZ=tropZ)

    tropPdf(:,:) = 0._r8
    tropFound(:) = 0._r8
    tropP(:) = 0._r8   !! new line
    tropT(:) = 0._r8   !! new line
    tropDZ(:,:) = fillvalue
    do i = 1, ncol
      if (tropLevB(i) /= NOTFOUND) then
        tropPdf(i, tropLevB(i)) = 1._r8
        tropFound(i) = 1._r8
        tropDZ(i,:) = pstate%zm(i,:) - tropZ(i)
      end if
    end do
````  
It also found problems in subroutine tphysbc in physpkg.F90, where these arrays needed to be initialized:
````
     det_ice(:) = 0._r8
     flx_cnd(:) = 0._r8
     flx_heat(:) = 0._r8
````
and diag_phys_writeout in cam_diagnostics.F90, where it needed:
````
    p_surf(pcols) = 0._r8
    p_surf_t1(pcols) = 0._r8
    p_surf_t2(pcols) = 0._r8
````

**Comment by tangq** [comment]
@jonbob , good catch for the subroutine `tropopause_e90_3d_output`. It seems that we'd like to initialize `tropP` and `tropT` before calling `tropopause_e90_3d` like below because we want to use the `tropP` and `tropT` returned by `tropopause_e90_3d`.

```
    tropP(:) = 0._r8   !! new line
    tropT(:) = 0._r8   !! new line

   ! Find the tropopause
    call tropopause_e90_3d(pstate, tropLevB, tropLevU, tropFlag, tropFlagInt, tropP=tropP, tropT=tropT, tropZ=tropZ)

    tropPdf(:,:) = 0._r8
    tropFound(:) = 0._r8
    tropDZ(:,:) = fillvalue
```

**Comment by wlin7** [comment]
@jonbob , these are nice found by themselves. It must be something like these giving random values. More digging still needed for this problem, though. tropP and tropT are local in this subroutine, and only involved in outfld to TROPE3D_P and TROPE3D_T. Interestingly, NBFB was not previously reported on this two arrays. However this may matter more when using v3atm config that has E90. The current v2-like test does not use E90.

Some other observations related to these NBFB tests. 
1. Diff in TCO and SCO are supposed to come from diff in the determination of tropopause. However, TROP_P and TROP_T, which are also present in eam.h0, do not report diff.
2. When E90 is not present, call_tropopause_e90_3d effectively do nothing. Assumed this is ok.

**Comment by wlin7** [comment]
I think the problem is with tropFlag, which is for flagging 3D tropospheric level. It is used for computing TROPMASS, TROPMASSB nd TROPMASST in `mo_chm_diags.F90`. However, as can be seen in chemistry.F90 which calls gas_phase_chemdr which then  passes tropFlag to chm_diags, tropFlag is never computed when E90 is not present
```
!-----------------------------------------------------------------------
! get tropopause level
!-----------------------------------------------------------------------
    e90_ndx = get_spc_ndx('E90')
    if (e90_ndx <= 0) then
      call tropopause_find(state, tropLev, primary=TROP_ALG_HYBSTOB, backup=TROP_ALG_CLIMATE)
    else
      call tropopause_e90_3d(state, tmp_tropLev, tropLev, tropFlag, tropFlagInt)
    end if

```
We could initialize tropFlag to 0 before this block. It also means the follow-up calculation of TROPMASS etc. are meaningless.

**Comment by wlin7** [comment]
With tropFlag and tropFlagInt in `chemistry/mozart/chemistry.F90` initialized as follows, `REP_D_Ln5.ne4_oQU240.F2010.chrysalis_intel.eam-cosplite_nhtfrq5` PASS
```
! initialize tropospheric level flags
    tropFlag = .false.
    tropFlagInt = 0
    e90_ndx = get_spc_ndx('E90')
    if (e90_ndx <= 0) then
      call tropopause_find(state, tropLev, primary=TROP_ALG_HYBSTOB, backup=TROP_ALG_CLIMATE)
    else
      call tropopause_e90_3d(state, tmp_tropLev, tropLev, tropFlag, tropFlagInt)
    end if
```

**Comment by jonbob** [comment]
@wlin7 -- sorry those uninitialized variables weren't the problem. But it looks like you did uncover the problem!

**Comment by wlin7** [comment]
Yours were useful find as well, @jonbob . Plus I was following your footstep to back trace the problem. Note that the work around I posted above would still make no sense for science, because the computed quantities such as TCO and SCO would still be meaningless. Ideally, we still need a fix for v2-like config in the current code base.

**Comment by wlin7** [comment]
To make the codes also work for v2-like config (no E90, no 3D tropopause) -- producing meaningful tropospheric/stratospheric partitioning of related diagnostics (e.g., TCO & SCO), we can add a check on e90_ndx to where tropFlag is used.

```
e90_ndx=-1
e90_ndx = get_spc_ndx('E90')

if (present(tropFlag)) then               -->   if (e90_ndx > 0 .and. present(tropFlag)) then   ! or simply change  to using e90_ndx only
if (.not. present(tropFlag)) then       -->   if (e90_ndx < 0 .and. .not. present(tropFlag)) then
```
With this modified if-logic, tropLev as computed by tropopause_find above when no E90 present will be used to compute the tropospheric and stratospheric sums. (Note: tropLev becomes ltrop in chm_diags)

**Comment by tangq** [comment]
@wlin7 , thanks for catching these uninitialized variables for cases when e90 is not used. It is not easy to think of all the possible cases when developing a new feature. I am glad that we seem have more tests that are able catch these missing cases.

Your modifications look great to me. Thanks!
