### ISSUE TITLE
PIO: FATAL ERROR: with SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.gcp12_gnu.allactive-wcprod

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5643]
With next of April 26th (have not verified on master yet), I see the error below with two tests that were working recently.
The other test is similar: `SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.gcp12_gnu.allactive-wcprodssp`

```
  0: PIO: FATAL ERROR: Aborting... An error occured, Writing variables (number of variables = 376) to file (SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.gcp12_gnu.allactive-wcprod.20230427_153313_m3tg4w.eam.h0.0001-01-01-00000.nc, n\
cid=116) using PIO_IOTYPE_PNETCDF iotype failed. Non blocking write for variable (TROPE3D_P, varid=302) failed (Number of subarray requests/regions=1, Size of data local to this process = 4320). NetCDF: Numeric conversion not re\
presentable (err=-60). Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/home/ndk/wacmy/nexty-apr26/externals/scorpio/src/clib/pio_darray_int.c: 395)
```

**Comment by dqwu** [comment]
@ndkeen 
Is this issue reproducible on some other machines?

Looks like the data buffer passed to PnetCDF API ncmpi_iput_varn are invalid (out of range) as NC_ERANGE (-60) is returned.
```
                        ierr = ncmpi_iput_varn(file->fh, varids[nv], rrcnt, startlist, countlist,
                                               bufptr, llen, iodesc->mpitype, vdesc->request + vdesc->nreqs);
```
According to PnetCDF documentation:
`NC_ERANGE: One or more of the specified values are out of the range of values representable by the external data type of the variable. (Does not apply to the ncmpi_get_var() and ncmpi_get_var_all()). Note NC_ERANGE is not a fatal error. The nonblocking request will be still added to the queue when NC_ERANGE is returned. Users are responsible to ensure no pending request exists when closing the file. `

**Comment by dqwu** [comment]
@ndkeen 
Could you please verify with E3SM master as well? It could be a bug introduced to E3SM next branch of April 26th. Do all failed tests used debug mode (e.g. SMS_D_Ld1)?

**Comment by ndkeen** [comment]
It is a recent fail. It was passing up until and including Apr 18th.  The next fail was April 22.

Note that a test without the testmod does pass:
`SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.gcp12_gnu`

**Comment by dqwu** [comment]
> It is a recent fail. It was passing up until and including Apr 18th. The next fail was April 22.
> 
> Note that a test without the testmod does pass: `SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.gcp12_gnu`

Does it pass if you remove the debug mode (SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.gcp12_gnu.allactive-wcprod)?

**Comment by ndkeen** [comment]
Indeed OPT build (ie, non-DEBUG) test passed:
`SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.gcp12_gnu.allactive-wcprod`

**Comment by dqwu** [comment]
> Indeed OPT build (ie, non-DEBUG) test passed: `SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.gcp12_gnu.allactive-wcprod`

Do you think we should open a related E3SM issue? It seems probable that the latest E3SM code changes might generate out-of-range data values in Fortran's debug mode on the E3SM side, which would then be passed to SCORPIO/PnetCDF.

**Comment by dqwu** [comment]
@ndkeen Please also check if this issue is also reproducible on some other machines in addition to GCP.

**Comment by dqwu** [comment]
> > Indeed OPT build (ie, non-DEBUG) test passed: `SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.gcp12_gnu.allactive-wcprod`
> 
> Do you think we should open a related E3SM issue? It seems probable that the latest E3SM code changes might generate out-of-range data values in Fortran's debug mode on the E3SM side, which would then be passed to SCORPIO/PnetCDF.

Sorry for the confusion, this is already an E3SM issue. I thought it was created as a SCORPIO issue instead.

**Comment by ndkeen** [comment]
There are 6 of the extra_coverage tests failing with this error on GCP.

**Comment by wlin7** [comment]
Likely due to the same cause as #5637. I am going to put in a PR for #5637 and see if it also fixes this issue.

**Comment by ndkeen** [comment]
Using this branch (and using recent changes to PE layouts on GCP that was just merged to master), I ran e3sm_extra_coverage.  Aside from 1 test that is known to fail missing partition files (not yet generated), all of the test complete, but then fail baseline DIFF. I'm not sure the status of the baselines, but I know there is some movement. So it looks like your change here does indeed address this issue.  

We will have to remember that this error message might mean a problem such as this.  Ideally we might have checks before writing to PIO.

**Comment by rljacob** [comment]
When was the last time GCP had no baseline diffs?  There have been a bunch of diff-causing PRs recently.

**Comment by wlin7** [comment]
PR #4707 (UCI-chem) must be responsible for GCP diffs. No request to bless GCP diffs after merging that PR. @ndkeen , nice to see the new PR does fix this issue and the similar tests.

**Comment by ndkeen** [comment]
Fixed by https://github.com/E3SM-Project/E3SM/pull/5656
