### ISSUE TITLE
Use of nomask domain files for wISC files cause D-case to fail

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#5653]
Testing of PR #5611 found that the use of nomask domain files causes D-cases to fail. Currently we have a mix of mask and nomask domain files for the wISC meshes, and we need to consistently make them the mask files

**Comment by rljacob** [comment]
Can you explain the difference between mask and no-mask domain files?

**Comment by jonbob** [comment]
@rljacob - sure. For the meshes with ice shelf cavities, the ocn/ice has two extents: one at the surface and the other including the cavities and extending under the shelves. We use a mask to distinguish those extents and end up with different mapping  and domain files. It makes sense to use the masked extent for the domain files -- since they are mostly used for splitting up the surface between ocn/ice and lnd. And our testing shows the choice of which domain file we use doesn't impact B- and G-cases, so the problem didn't show up until we tried D-cases
