### ISSUE TITLE
Array bound mismatch for dimension 1 of array 'linoz_o3_clim' (15/14) with `F20TR_chemUCI-Linozv3.pm-cpu_gnu.eam-v3atm_rtmoff`

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5661]
With `SMS_D_Ln5.ne30pg2_EC30to60E2r2.F20TR_chemUCI-Linozv3.pm-cpu_gnu.eam-v3atm_rtmoff`
and May 3rd next (which includes 1-threaded default PE layouts for pm-cpu -- update: now on master), I see:

```
290: At line 353 of file /global/cfs/cdirs/e3sm/ndk/repos/nexty-may3/components/eam/src/chemistry/mozart/lin_strat_chem.F90
290: Fortran runtime error: Array bound mismatch for dimension 1 of array 'linoz_o3_clim' (15/14)
```

I noted this here https://github.com/E3SM-Project/E3SM/issues/5648, but making separate issue for this error.

**Comment by wlin7** [comment]
Interesting `SMS_D_Ln5.ne4pg2_oQU480.F20TR_chemUCI-Linozv3.pm-cpu_gnu.eam-ne4_v3atm_rtmoff` didn't catch this. Look like a problem of ncol vs pcols mismatch when grid or pe-layout changes.

**Comment by ndkeen** [comment]
Yep Wuyin, that's probably what's happening. It might just now appear with these PE layout changes and could be yet another example of ncol/pcols mismtach.

**Comment by wlin7** [comment]
It turns out not the exact kind of ncol vs pcols mismatch. For this test, -DPCOLS=16 is set via compiler.
The reported line of 353 is
`dO3(:,:)     =   o3_vmr(:,:)  - linoz_o3_clim(:,:)`

I think the error message says the size of the 1st dimension of dO3 is 15 (ncol=15), while the size of 1st the dimension of linoz_o3_clim is 14. If indeed so, then the chunks were mixed up.

**Comment by wlin7** [comment]
With the following changes (lines 353 - 359 in lin_strat_chem.F90), with upper bound ncol added on rhs
 ```
      dO3(:,:)     =   o3_vmr(:,:)  - linoz_o3_clim(:ncol,:)
       dN2O(:,:)    =  n2o_vmr(:,:)  - linoz_n2o_clim(:ncol,:)
       dNOY(:,:)    =  noy_vmr(:,:)  - linoz_noy_clim(:ncol,:)
       dCH4(:,:)    =  ch4_vmr(:,:)  - linoz_ch4_clim(:ncol,:)
       dH2O(:,:)    =  h2o_vmr(:,:)  - linoz_h2o_clim(:ncol,:)
       dTemp(:,:)   =  temp(:ncol,:)     - linoz_t_clim(:ncol,:)
       dCOL(:,:)     =  o3col(:,:)*convert_to_du - linoz_o3col_clim(:ncol,:)
```
The execution can go beyond that block (though more of the same below). 1st dimsize for array like linoz_o3_clim being 15 (when ncol=14, and pcols=16) is why the error is trigger, but remains a puzzle.

Among those lines, `temp` in `dTemp(:,:)   =  temp(:ncol,:)     - linoz_t_clim(:ncol,:)` was a clear bug without upper bound. `dTemp` is declared as (`ncol,pver)` , while `temp` as `(pcols,pver)`. 

The error of the same kind then moves to  line 369,  Array bound mismatch for dimension 2 of array 'xsfc' (14/15).

**Comment by wlin7** [comment]
The error in the block starting at line 367 can be fixed with explicit upper bound

```
       xsfc(1,:)=   linoz_o3lbs(:ncol,pver) !  ozone surface constant (varying in lat)
       xsfc(2,:)=   linoz_n2o_clim(:ncol,pver) !  n2o (constant throughout latitude)
       xsfc(3,:)=   linoz_o3lbs(:ncol,pver)*3.e-3_r8  !noylnz
       xsfc(4,:)=   linoz_ch4_clim(:ncol,pver) ! ch4 (constant throughout latitude)
```
Then there is more starting from line 390, also with array from the 'fields' data structure. Again, we really need to know why some of the chunk having mismatched 1st dimension.

**Comment by jinboxie** [comment]
I'd like to note that the linoz variable, such as the linoz_o3_clim or linoz_o3lbs, etc are input from linoz input forcing data initially with a dimension of (time, 27, 20), for every timestep, the data is input and first do horizontal interpolated to the desired horizontal grid in function read_za_trc in components/eam/src/chemistry/utils/tracers.F90, and then vertical levels in function vert_interp in components/eam/src/chemistry/utils/tracers.F90. After the process, it is input to function linv2_strat_chem_solve/linv3_strat_chem_solve in components/eam/src/chemistry/mozart/lin_strat_chem.F90 for further calculation as is shown here.

**Comment by wlin7** [comment]
After applying upper bound ncol to all pointers associated with the data in the `field` data structure. This SMS_D test can run ok.

Also note that the previous comment of `pcols` being set by macro `-DPCOLS `is incorrect. It would be done so only when `-DPPCOLS` is also passed to the compiler. pcols=15 is therefore legitimate values determined in `phys_grid.F90::phys_grid_init`.
