### ISSUE TITLE
Aqueous chemistry bug

### ISSUE THREAD

**Issue by Jiwengithub** [E3SM-Project/E3SM#5713]
In the aqueous chemistry, the total condensate mass mixing ratio including both liquid and ice was used in the calculation of production of sulfate from the aqueous chemistry processes. However, the liquid water mass mixing ratio should be used based on the formula used (Jiwen also communicated with NCAR people to confirm this). Thus, the bug fix was about using the liquid water mass mixing ratio instead of the total condensate mass mixing ratio in the aqueous chemistry. 
[mo_gas_phase_chemdr.F90.gz](https://github.com/E3SM-Project/E3SM/files/11535996/mo_gas_phase_chemdr.F90.gz)

**Comment by crterai** [comment]
Adding @hwangacme to this thread, since Hailong was part of a discussion on this topic in the v3atm fork.

**Comment by crterai** [comment]
Detailed information on the bug fix can be found on this page, including test simulations with the fix:
https://acme-climate.atlassian.net/wiki/spaces/NGDAP/pages/3764289545/Aqueous+chemistry+bug+fix
