### ISSUE TITLE
MVK Baseline pass/fail

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#5716]
When #4707 was merged to next, it messed up the ozone chemistry for basic cases and the climate changed.  The MVK test noticed it with a BASELINE_FAIL.

> 2023-05-16 01:25:36: BASELINE FAIL for test 'JNextAtm_nbfb20230516_003403'.
> Test status: fail; Variables analyzed: 121; Rejecting: 61; Critical value: 13; Ensembles: statistically different

After the fix was merged (#5687), the number of rejects went down but still above the threshold:

> 2023-05-22 01:32:16: BASELINE FAIL for test 'JNextAtm_nbfb20230522_003515'.
> Test status: fail; Variables analyzed: 121; Rejecting: 15; Critical value: 13; Ensembles: statistically different
> https://web.lcrc.anl.gov/public/e3sm/e3smtest/evv/MVK_PS.ne4_oQU240.F2010.chrysalis_intel.C.JNextAtm_nbfb20230522_003515/index.html

That was hash  9703f05642 which was placed on next on May 21 and results returned May 22.

On May 22, three more PRs were added to next and they were all BFB with no impact on the atmosphere.  With this hash 8745060c, the MVK test is now passing on May 23 results.

> 2023-05-23 08:52:13: BASELINE PASS for test 'JNextAtm_nbfb20230523_003413'.
>     Test status: pass; Variables analyzed: 121; Rejecting: 9; Critical value: 13; Ensembles: statistically identical
>         https://web.lcrc.anl.gov/public/e3sm/e3smtest/evv/MVK_PS.ne4_oQU240.F2010.chrysalis_intel.C.JNextAtm_nbfb20230523_003413/index.html

How can the MVK test get different results on what should be the same atmosphere code?

**Comment by salilmahajan** [comment]
Hi @rljacob,  each time the MVK test is run, it generates a new 30-member ensemble of next where each ensemble member uses a slightly different initial condition - initial conditions are perturbed by random machine precision numbers. The randomization algorithm is seeded with the current time (@mkstratos, correct me if I am mistaken here). Hence, even though the atmosphere code may not change, the ensemble realizations (and hence their statistics) are different with every MVK generated ensemble.  The MVK test statistics thus may differ for each iteration.   

The current threshold value of 13 to determine the test fail/pass status was derived by resampling approaches using a large low-res (ne4) control ensemble run of E3SMv1. Looking at the history of MVK test results for the past few months, we think it may be a little too low for E3SMv2/v3dev. We are currently in the process of revising this value for E3SMv2 by running and evaluating a large control ensemble with E3SMv2 - initial quick evaluations suggest that it should be around 18.

**Comment by rljacob** [comment]
Thanks, Salil.  That make sense.
