### ISSUE TITLE
An unintended PEM DIFF mpassi.hist.am.regionalStatistics for ne30pg2_EC30to60E2r2.WCYCL1850

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#5731]
This is observed with a manually created test for PEM_Ln9.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel using the master branch (89fea95e13bf715cbb58b649f0738e2b9b7b7782). Same when using master of recent days. 

The standalone PEM_Ln9.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel is a PASS. But DIFF from the current master baseline.
The test compares cpl.hi and mpassi.hist.am.regionalStatistics. It is the latter reports diff on 7 variables (totalIceArea, totalIceVolume, totalIceExtent etc.). Other than the mpassi regional statistics, the simulation results are not affected

The manually created test (using create_test) turns out using different a pe-layout, and what is used by the nightly test.

From manually created test

```
Comp  NTASKS  NTHRDS  ROOTPE PSTRIDE
CPL :   2752/     1;      0      1
ATM :   2752/     1;      0      1
LND :    192/     1;   2560      1
ICE :   2560/     1;      0      1
OCN :    640/     1;   2752      1
ROF :    192/     1;   2560      1
GLC :      1/     1;      0      1
WAV :      1/     1;      0      1
IAC :      1/     1;      0      1
ESP :      1/     1;      0      1

```

From nightly test reported on the dashboard
```
Comp  NTASKS  NTHRDS  ROOTPE PSTRIDE
CPL :    192/     1;      0      1
ATM :    192/     1;      0      1
LND :    192/     1;      0      1
ICE :    192/     1;      0      1
OCN :     64/     1;    192      1
ROF :    192/     1;      0      1
GLC :      1/     1;      0      1
WAV :      1/     1;      0      1
IAC :      1/     1;      0      1
ESP :      1/     1;      0      1


```

Are these diffs in mpassi.regionalStatistics expected after pe-layout changes?

**Comment by wlin7** [comment]
Similarly, for `ERP_Ld3.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-pioroot1`, 70 fields in `mpaso.hist.am.global` diff from baseline, while the simulation results otherwise are not affected (e.g., cpl.hi, and mpassi.hist.am.timeSeriesStatsDaily).

**Comment by jonbob** [comment]
@wlin7 - pe-layout changes will impact the analysis member output (hist.am files), so that would be expected

**Comment by jonbob** [comment]
@wlin7 -- are you OK with this answer? Does it resolve the issue?

**Comment by wlin7** [comment]
Good the diff is expected. The only inconvenience is when running tests manually, it would report DIFF, and need to inspect the cprnc output to make sure the diff are only on these diagnostics output. It would be ideal if the pe-layout can be made the same, running manually, or from jenkins.

**Comment by rljacob** [comment]
PEM is supposed to change the layout.  What we need is a way to turn off output of those files.

**Comment by wlin7** [comment]
Sure, Rob, PEM changes the layout. My message above meant for PEM and other tests. For PEM tests, it would bepelayout for the 1st run (and accordingly the one for case2). It seems to be since a recent cime change, the default pe-layout becomes different for the same test created manually or by jenkins. 

Agreed, if we don't need to compare these mpaso and mpassi statistics, there would be no issue. But there must be interest of checking these statistics for some tests.

**Comment by wlin7** [comment]
@amametjanov pointed out why such discrepancies (pe-layout then member based output). I didn't specify `--pesfile $e3sm/cime_config/testmods_dirs/config_pes_tests.xml` in my manual tests. With --pesfile, consistent pe-layout would be ensured.

**Comment by rljacob** [comment]
Oh I missed that you were comparing manual with Jenkins.   Yes we're running smaller node counts with Jenkins so they get through overnight on anvil and chrysalis.   Not a new cime feature (specifying a config_pes file on command line) but one we're using for the first time.
