### ISSUE TITLE
Incorrect units of active tracer tendencies in the ocean Registry

### ISSUE THREAD

**Issue by cbegeman** [E3SM-Project/E3SM#5784]
In the process of @akturner's work on frazil flux budgets, we discovered that `salinityTend` needed to be divided by a factor of `layerThickness`. This indicates that the units should have an additional factor of `m`. By inspecting the tracer tendency updates in both RK4 and split-explicit, I confirmed that the `activeTracerTend`'s are divided by a factor of `layerThickness`. I found no place where the `activeTracerTend`'s are divided by `layerThickness` prior to being written to streams. My proposed bugfix is here: 7b00e5ace26ae30549bafee5bf79a053bbc18543.

**Comment by darincomeau** [comment]
Units in that commit look good (CF-compliant) to me

**Comment by mark-petersen** [comment]
Yes, it is correct to include a length unit in the numerator, since we time-step thickness-weighted tracers: 
![image](https://github.com/E3SM-Project/E3SM/assets/4036816/d3edb999-f567-458c-938a-2c6311fd5c62)
Thanks for checking!

**Comment by cbegeman** [comment]
Great, thanks @darincomeau and @mark-petersen!

**Comment by cbegeman** [comment]
Resolved by https://github.com/E3SM-Project/E3SM/pull/5883
