### ISSUE TITLE
Import cmake file from Albany 

### ISSUE THREAD

**Issue by mperego** [E3SM-Project/E3SM#5786]
As discussed offline at the E3SM all hands meeting, it would be nice if E3SM build system could import the Albany cmake configuration file. The file is store in the `ALBANY_PATH` folder. 
As an example here is the Albany path for perlmutter:
`/global/common/software/fanssie/albany-e3sm-serial-release-gcc/`

Albany libraries should be added to the `LD_LIBRARY_PATH` during the case.setup.

In addition, we'd like the build to provide the `ALBANY_PATH` as a environmet variable, rather than by setting it in the 
`cime_config/machines/cmake_macros/*.cmake` file.

I'll be happy to test this capability when ready. Thanks @jgfouca for agreeing to work on it!

Pinging @bartgol @jewatkins so that they stay in the loop.

**Comment by jgfouca** [comment]
@mperego , on perlmutter, what create_test command could I run to get a case that uses albany?

**Comment by jgfouca** [comment]
Also, it looks like the file permissions on `/global/common/software/fanssie` are too tight. I am not able to see anything under that directory.

**Comment by jgfouca** [comment]
One other thing, I remember you had some requirements regarding the environment variable... Like you wanted it stored in the case env settings or something like that. Can you remind me exactly what you needed?

**Comment by jewatkins** [comment]
we might want to migrate that build over to `/global/common/software/e3sm/` if we want to make it e3sm project accessible

**Comment by jgfouca** [comment]
@jewatkins , that's a good idea.

**Comment by mperego** [comment]
> One other thing, I remember you had some requirements regarding the environment variable... Like you wanted it stored in the case env settings or something like that. Can you remind me exactly what you needed?

Yeah, I think that's right. 
We export the `ALBANY_PATH` env variable before setting up and  building the case from scratch. 
But when the test is already built, we would like to be able to run it without manually re-exporting the env variable and re-adding the Albany libraries to the`LD_LIBRARY_PATH`.

**Comment by mperego** [comment]
Here is the script we use to create the test (sorry, it's a bit messy).
[BGelm.bash.txt](https://github.com/E3SM-Project/E3SM/files/11911126/BGelm.bash.txt)

**Comment by bartgol** [comment]
@jgfouca some more toughts:

- I would like to keep the ALBANY_PATH in the mach cmake macro file as a "fallback" option. If the env var is present, honor it, otherwise use the cmake macro one. Perhaps we should just wrap the set command in the cmake macro file in an if. Something like
```
  if (NOT DEFINED $ENV{ALBANY_PATH})
    set (ALBANY_PATH /path/to/albany)
  else ()
    set (ALBANY_PATH $ENV{ALBANY_PATH})
  endif()
```
- We would like to pull in albany via find package, like `find_package(Albany REQUIRED HINTS ${ALBANY_PATH})` (of course, only if the compset requires mali).
- In order to not have to set ALBANY_PATH in the env everytime we run, I think it must be in config_machines.xml. But can config_machines.xml have some conditionals, like (using some python as pseudocode):
```
  if "ALBANY_PATH" in env:
     <env name="ALBANY_PATH">env["ALBANY_PATH"] </env>
  else:
     <env name="ALBANY_PATH">/path/to/default/albany</env>
```

**Comment by jgfouca** [comment]
Can I test using this dir `/global/common/software/e3sm/mali_tpls/albany-e3sm-serial-release-gcc` ?

**Comment by jewatkins** [comment]
Yes, @mcarlson801 just installed it.

**Comment by xylar** [comment]
Hi everyone, please don't use `/global/common/software/e3sm/`.  This location has *very* limited disk space and all of it is needed for E3SM-Unified (which we are currently testing a new version of).  As it is, I have had to delete a bunch of earlier versions of E3SMU to make room for our current testing and this problem is made worse by competing with MALI TPLs.  There *should* be another space (albeit not with as fast of disk access) where you can install.  I'll try to figure out where that is.

We can also try to increase our quota but for now I think E3SMU needs to take priority.

**Comment by xylar** [comment]
An update, I learned form @ndkeen about the command `cmnquota`:
```
$ cmnquota e3sm
                  ---------- Space (GB) ---------     ------------- Inode --------------
Project             Usage      Quota    Percent          Usage       Quota     Percent  
---------------   ---------  ---------  ---------     ----------  ----------  ----------
e3sm                     22         50         45         815084     1000000          81
```
I will ask for an increase in both disk space (to 100 GB) and inodes (to 2M) but it seems like inodes are the issue we're hitting. @mcarlson801, @jewatkins and others, do you know if your software is using a lot of inodes?  If not, it's probably fine to leave it.  Conda and spack environments (what I'm using) use huge numbers of inodes so you might be in the noise.

**Comment by jewatkins** [comment]
@xylar Thanks for looking into this. It's unclear to me how that inode number is calculated but I don't think `mali_tpls` uses many inodes. I checked usage details by user on the data dashboard https://my.nersc.gov/data-mgt.php and mcarlson is not even on the list of top users for both e3sm and fanssie. It looks like they increased the quota too so I think we're okay now:
```
                  ---------- Space (GB) ---------     ------------- Inode --------------
Project             Usage      Quota    Percent          Usage       Quota     Percent  
---------------   ---------  ---------  ---------     ----------  ----------  ----------
e3sm                     21        100         21         793051     2000000          39
```
BTW, as I was snooping, I noticed not all the directories in `mali_tpls` are shared with e3sm. @mcarlson801 Could you open up permissions when you get back?

**Comment by xylar** [comment]
Yep, I got the quota increased so we're good now.  Sorry about that.

**Comment by mcarlson801** [comment]
Ah woops, I'm just seeing this since I was on vacation but it looks like it is already resolved. @jewatkins Permissions are now opened up for all the files, hopefully that didn't block anyone!

**Comment by jgfouca** [comment]
@mcarlson801 , there are still some permissions issues with the Trillions installation. It has a dependency on a boost that is not readable to other users:

```
external_packages/Boost/BoostConfig.cmake:  INTERFACE "/global/cfs/cdirs/m1041/mcarlson/boost-1.72.0/gcc-11.2.0/include"
external_packages/BoostLib/BoostLibConfig.cmake:  IMPORTED_LOCATION "/global/cfs/cdirs/m1041/mcarlson/boost-1.72.0/gcc-11.2.0/lib/libboost_system.so")
external_packages/BoostLib/BoostLibConfig.cmake:  IMPORTED_LOCATION "/global/cfs/cdirs/m1041/mcarlson/boost-1.72.0/gcc-11.2.0/lib/libboost_program_options.so")
external_packages/BoostLib/BoostLibConfig.cmake:  INTERFACE "/global/cfs/cdirs/m1041/mcarlson/boost-1.72.0/gcc-11.2.0/include"
```

Which causes this CMake error:
```
CMake Error in mpas-framework/src/CMakeLists.txt:
  Imported target "albanyLib" includes non-existent path

    "/global/cfs/cdirs/m1041/mcarlson/boost-1.72.0/gcc-11.2.0/include"
```

**Comment by mcarlson801** [comment]
> @mcarlson801 , there are still some permissions issues with the Trillions installation. It has a dependency on a boost that is not readable to other users:

This should be fixed now. I moved the boost installation to `mali_tpls` and rebuilt everything.
