### ISSUE TITLE
Confusion between scalar and vector stress calculations

### ISSUE THREAD

**Issue by quantheory** [E3SM-Project/E3SM#5834]
To explain the bug here I need to give some background.

# Background

For models like EAM that have a sub-grid-scale "gustiness" parameterization, it is necessary to distinguish between the mean magnitude of the surface stress (or "scalar" surface stress), and the mean stress as a vector that opposes the wind (or "vector" surface stress). If we use $\langle a \rangle$ to refer to an average of quantity "$`a`$" over a grid cell and a single time step, and if $\tau$ is the vector surface stress, then

$$\langle \left| \tau \right| \rangle \ge \left| \langle \tau \rangle \right|$$

where the left hand side is the scalar surface stress and the right hand side is the magnitude of the vector surface stress. These stresses are computed based on an average near-surface wind speed with gustiness included. If $u$ is a near-surface wind velocity, this can be expressed 

$$\langle \left| u \right|^2 \rangle = \left| \langle u \rangle \right|^2 + \langle \left| u - \langle u \rangle \right|^2 \rangle$$

which can be shown using the usual identity for the variance of a distribution $\langle(x-\langle x\rangle)^2\rangle=\langle x^2 \rangle-\langle x \rangle^2$. This is more commonly written using notation like this:

$$ U^2 = U_v^2 + U_g^2 $$

where $U$ is the root-mean-square wind speed over the grid cell, $U_v$ is the resolved wind speed (with respect to the surface), and $U_g$ is the "gustiness" wind speed, and each of the terms in this equation is defined to be equal to the one in the preceding equation (e.g. $U=\sqrt{\langle \left| u \right|^2 \rangle}$).

The difference between scalar and vector wind stresses is most apparent when $U_v$ is small and $U_g$ is large. In this case, the scalar wind stress will be large because on short length/time scales, wind gusts produce large stresses. However, the vector wind stress will be small, since a small $U_v$ means that there is no strongly preferred direction in which the wind blows, and so when averaged over the whole grid cell, the stress vectors at different locations largely cancel out.

For this reason, it is common to use the parameterization

$$ \left| \langle \tau \rangle \right| = \left(\frac{U_v}{U}\right) \langle \left| \tau \right| \rangle \qquad (*)$$

to relate the scalar and vector stresses. See for instance equations (3-4) of [Zeng et. al. (2002)](https://doi.org/10.1175/1520-0493(2002)130%3C2125:POWGFT%3E2.0.CO;2). This guarantees that in the limit $U_v \to 0$, the vector stress also becomes $0$, as it should.

# Nature of the bug

Currently, the atmosphere only exports gustiness-enhanced winds to the surface (i.e. it only supplies winds with total magnitude $U$). This means that none of the surface components can evaluate the right-hand side of (*), and so only the scalar stress can be calculated. However, the vector stress is the stress that should actually contribute to the next atmosphere (and ocean/sea ice) momentum budget. Thus, the wrong stress is currently being used.

# History of the bug

1. The gustiness code originally added to the ocean only, in #1035, does not appear to have had this issue. However, the evaluation of (*) is effectively "bundled in" with the decomposition of the stress into zonal and meridional components, so it is not obvious at first glance that the factor of $U_{v}/U$ is intentionally being applied here.
2. Pull request #1624 was intended to be a bug fix, but that PR actually introduces this bug to the ocean stress calculations. This appears to be an understandable mistake, because the code as written in the previous commit appears as if the effective multiplication by $U_v/U$ is accidental, rather than intentionally converting scalar to vector stress.
3. Pull requests #2679, #2720, and #2789 collectively replaced the gustiness parameterization in the ocean with one that applies to all components. In doing so, they produced the current behavior, where all surface components are now subject to the bug, and they do not have sufficient information about the gustiness to easily correct the formula.
4. Pull request #4229 introduced an XML option called `ATM_SUPPLIES_GUSTINESS`, which causes the atmosphere to supply $U_v$ and $U_g$ to the components (rather than $U$), and causes the surface flux calculations to perform the scalar-to-vector stress conversion. This PR was intended to solve this bug (and to address #4073), but the option that was added to do so has never been turned on by default.

# How to fix the bug

Make `ATM_SUPPLIES_GUSTINESS=TRUE` the default setting (eventually, it should probably be the only option). The issue described at #5835 should be fixed as well; it interacts with this bug because if `ATM_SUPPLIES_GUSTINESS=TRUE`, part of the fix must be applied in the surface components, not just in the atmosphere.

# Effect on model output

This bug fix reduces the effect of gustiness on wind speeds, and thus is likely to increase both the average wind speeds near the surface, and many fluxes (e.g. sensible and latent heat, dust, sea salt...). @mabrunke has performed short runs recently with the fix, but AFAIK we do not have a full climate evaluation yet. The gustiness parameters may need to be retuned if the effect of the fix is large; again, this should probably be done with #5835 also fixed.

**Comment by rljacob** [comment]
cc @oksanaguba @wlin7 @singhbalwinder @golaz @crterai

**Comment by singhbalwinder** [comment]
Adding @polunma and @beharrop

**Comment by quantheory** [comment]
Just making a note here that I've submitted 4 gustiness-related bugs today, which represent partially distinct but interrelated issues:

1. This one.
2. #5835
3. #5836
4. #5837

**Comment by quantheory** [comment]
Tagging the correct @mabrunke (I had the wrong username in the original post before I edited it).
