### ISSUE TITLE
EAM's 'U10' output includes a gustiness enhancement

### ISSUE THREAD

**Issue by quantheory** [E3SM-Project/E3SM#5836]
Note: this bug is diagnostic-only; to the best of my understanding, a fix will result in bit-for-bit output, except for the U10 field. (The `u10` variables used in some aerosol code appear to be based on a completely separate calculation.)

Because the surface models only have access to a gustiness enhanced wind (see #5834), the value of 10-meter wind speed that they supply to the atmosphere model includes a contribution from gustiness. This means that it is unsuitable for comparison to other data sets that only include winds that are "resolved" or otherwise averaged over space and time scales greater than the effects of gustiness.

If #5834 is fixed, then this can be resolved by rescaling U10 in the surface models, namely by multiplying U10 by a factor of $U_v/U$, where $U_v$ is the resolved wind speed with respect to the surface, and $U$ is the gustiness-enhanced wind.

Optionally, we could also produce an output for the gustiness-enhanced wind (called something like `U10GUST`). This may be useful for comparing to data sets with resolution fine enough to resolve gustiness. However, doing so would likely require coupling (an) additional field(s) from the surface to atmosphere if this is intended to be an atmospheric output. That's because the resolved wind speed is with respect to the surface, and over the ocean, the surface has a non-zero velocity with respect to the earth (and this velocity is not currently known to the atmosphere).

If this is not changed, there needs to at least be clear documentation somewhere that U10 includes gustiness, and is not comparable to data products representing larger-scale wind averages.

**Comment by quantheory** [comment]
Upon further reflection, it turned out to be easier to fix this entirely in the atmosphere model, which is what the branch I'm working on now does. I did have to fudge the value slightly by neglecting the velocity of the ocean surface.

**Comment by rljacob** [comment]
@quantheory your last comment says it would be fixed in just the atmosphere model but you fixed it in the coupler as well?

**Comment by quantheory** [comment]
@rljacob Yes, I ended up going with my original idea where coupler fields are added to ensure that ocean/sea-ice velocity is properly accounted for in U10, so that last comment should be ignored. Of course the sea ice does not apply gustiness for now, but I did add an exported field so that if gustiness is ever reimplemented over sea ice, it will be easy to send out the correct diagnostic information for that case.

**Comment by rljacob** [comment]
Is it right to call U10 a "diagnostic"?  We usually use that for output fields that never impact the state.

**Comment by quantheory** [comment]
@rljacobs Yes, that description actually does apply here; the U10 change itself was verified to only affect U10 output fields and does not feed into the physics. (That commit was bundled with other answer-changing commits in #5850, but I verified that the commit fixing this particular issue was not answer-changing outside of a couple of diagnostic fields.)

I should note that there are *other* wind variables that are *also* called U10 (or something similar) in the code, and some of those feed back into aerosol emissions. Which makes this a bit confusing. But those variables are defined and calculated differently from the diagnostic U10 described here.
