### ISSUE TITLE
Possible double-counting of boundary-layer gustiness contributions over land

### ISSUE THREAD

**Issue by quantheory** [E3SM-Project/E3SM#5837]
Since EAMv2, a gustiness value calculated by CLUBB has been used to enhance the mean wind speeds; this is meant to represent the effects of the boundary-layer turbulence/convection accounted for by CLUBB. But the land model already calculates its own estimate for a convective gustiness contribution `wc`. E.g. see [here](https://github.com/E3SM-Project/v3atm/blob/1f97213ce7ab8f3dcea486feb36ceba934cba27b/components/elm/src/biogeophys/BareGroundFluxesMod.F90#L299-L306). This `wc` appears to be a parameterization accounting for the same convective sub-grid-scale motion that is handled by CLUBB, meaning that the same process is used to enhance the wind twice and gustiness is overestimated.

Assuming that this needs to be fixed, the `wc` enhancements should be removed from the land model (in each of the bare ground, lake, urban, and forest canopy modules). Or rather, a flag should be added to turn off the `wc` calculation, and the default behavior should be to not apply `wc`.

If the COARE or UA atmosphere-ocean coupling methods are ever intended to be used in the future, they should probably be modified as well, as both options also appear to apply a gustiness contribution similar to `wc`.

**Comment by mabrunke** [comment]
`wc` is definitely not needed when coupled to the atmosphere, but it should still be kept for running ELM offline.
