### ISSUE TITLE
A mysterious non-BFB then crash of F2010.v3alpha02 on chrysalis

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#5839]
Have this issue on record in case of recurring.

The case is created using `/home/ac.wlin/E3SM/Cases/testing/scripts/run.20230724.F2010.v3alpha02.chrysalis.sh` with branch `wlin/atm/v3compsets_alpha02 `(hash `5244c09444d6a44a1eedeaff27453f38b82e1fcd`)

The first submit crashed after 106 steps, with fatal error message
```
 314:  ERROR: EOS bad state: d(phi), dp3d or vtheta_dp < 0
 313: Image              PC                Routine            Line        Source
 313: libpnetcdf.so.3.0  000015555101512A  tracebackqq_          Unknown  Unknown
 313: e3sm.exe           0000000004CDC630  shr_abort_mod_mp_         114  shr_abort_mod.F90
 313: e3sm.exe           0000000001D95C7E  eos_mp_pnh_and_ex         140  eos.F90
 313: e3sm.exe           0000000001DA5FFB  prim_advance_mod_        1152  prim_advance_mod.F90
```
Leading to it, there were numerous warnings of (from other PEs, too).
```
 ...
 313:  k,vtheta(k):           61   306.186802330999
 313:  WARNING:CAAR: theta<   100.000000000000       applying limiter
 313:  k,vtheta(k):           62   305.724707498358
 313:  WARNING:CAAR: theta<   100.000000000000       applying limiter
 313:  k,vtheta(k):           63   305.299093122926
 313:  WARNING:CAAR: theta<   100.000000000000       applying limiter
 ...
```
Surprised by the crash, as the same v3alpha02 configuration has been run extensively, the case was simply re-submitted. The new submission is running well beyond the previous failure point, and still going. Inspection of atm.log found the two runs started to diverge at step 74

```
--- From the 1st run, JobId:  364745.230724-231422

 nstep, te       70   0.26321884719121580E+10   0.26321878888101244E+10  -0.32239896429885130E-04   0.98542020384004180E+05
 nstep, te       71   0.26322029287668619E+10   0.26322023302804232E+10  -0.33090497252545241E-04   0.98542043663520642E+05
 nstep, te       72   0.26322175422119293E+10   0.26322169223801594E+10  -0.34270678764708138E-04   0.98542067649127013E+05
 nstep, te       73   0.26322342840809488E+10   0.26322335324636612E+10  -0.41557126186725249E-04   0.98542096493303266E+05
 nstep, te       74   0.26322512725177503E+10   0.26322505630863056E+10  -0.39224648377792309E-04   0.98542124044915457E+05
 nstep, te       75   0.26322675882191315E+10   0.26322668138295164E+10  -0.42816189307475543E-04   0.98542154288875870E+05

--- From the 2nd stable run, JobId: 365043.230725-111252

 nstep, te       71   0.26322029287668619E+10   0.26322023302804232E+10  -0.33090497252545241E-04   0.98542043663520642E+05
 nstep, te       72   0.26322175422119293E+10   0.26322169223801594E+10  -0.34270678764708138E-04   0.98542067649127013E+05
 nstep, te       73   0.26322342840809488E+10   0.26322335324636612E+10  -0.41557126186725249E-04   0.98542096493303266E+05
 nstep, te       74   0.26322512716248837E+10   0.26322505622676482E+10  -0.39220545332202207E-04   0.98542124042309253E+05
 nstep, te       75   0.26322675784416881E+10   0.26322668074552803E+10  -0.42628025205636195E-04   0.98542154164384308E+05

```
Don't see any other info that could explain the issue among the log files. 
The RUNDIR is `/home/ac.wlin/pe3sm/E3SM_testings/E3SMv3_dev/20230724.F2010.v3alpha02.chrysalis/run`

**Comment by wlin7** [comment]
Hope to determine if the failure was caused by a machine issue or by a model code issue. In this case, the run crashed within a day after the apparent divergence. It would be more cumbersome if a similar failure occurs well into a simulation.

**Comment by rljacob** [comment]
what was the job number for the above run?

**Comment by wlin7** [comment]
@rljacob , the job number for the failed run is 364745. The job started at 2023-07-24 23:14:18. It would be helpful to know if the hardware has any anomaly around that time. BTW, the resubmitted job started at 2023-07-25 11:12:35 and ran well.

**Comment by rljacob** [comment]
@mahf708 can you list the job numbers from your failed jobs here?

**Comment by mkstratos** [comment]
This error has happened a few times recently for the MVK nightly test too, which uses 90 nodes. It started on 26th July, also on the 27th, and today. The job numbers are:
365182
365879
368090

Today's error appears in `/lcrc/group/e3sm/e3smtest/scratch/chrys/MVK_PS.ne4_oQU240.F2010.chrysalis_intel.C.JNextAtm_nbfb20230803_003636/run/atm_0025.log.368090.230803-013147`
```
SHR_REPROSUM_CALC: Input contains  0.12000E+03 NaNs and  0.00000E+00 INFs on MPI task    2304
 ERROR: shr_reprosum_calc ERROR: NaNs or INFs in input
```

**Comment by rljacob** [comment]
I don't see anyway that a storage issue could affect the values in memory.

**Comment by amametjanov** [comment]
The culprit in the first comment of this issue was node `chr-0435`. I've encountered all the errors mentioned in this issue (reprosum NaNs, `Error in advance_xp2_xpyp`) while isolating the node.
The node is taken out-of-job-rotation. Please re-open the issue if you run into further errors.

**Comment by wlin7** [comment]
MVK_PS.ne4_oQU240.F2010.chrysalis_intel test failed today with unexpected but somewhat familiar error message
`SHR_REPROSUM_CALC: Input contains  0.24600E+03 NaNs`

JobId: 372153.230811-032457

The past few days, the test returned diff. The test last failed on 08/05/23.
