### ISSUE TITLE
minLevelCell issue in mpas_ocn_vmix_cvmix.F

### ISSUE THREAD

**Issue by vanroekel** [E3SM-Project/E3SM#5840]
There is an array `Nsqr_iface` in the cvmix driver that is not initialized correctly for `minLevelCell .ne. 1`

https://github.com/E3SM-Project/E3SM/blob/master/components/mpas-ocean/src/shared/mpas_ocn_vmix_cvmix.F#L474

The line referenced here should, I believe be

Nsqr_iface(1:minLevelCell(iCell)-1) = Nsqr_iface(minLevelCell(iCell))

instead.

Bug fix is not expected to change the climate.

**Comment by vanroekel** [comment]
@cbegeman could you please confirm that this change I'm proposing is correct and I can make the one line PR?

**Comment by xylar** [comment]
@vanroekel, for what it's worth, I'm quite sure that you're correct and this line is a bug.  I'm not sure if @cbegeman is around at the moment -- she was headed out on vacation.  So I would say you can just make a PR.

**Comment by vanroekel** [comment]
Thanks for the confirmation @xylar   i have issued the PR

**Comment by cbegeman** [comment]
@vanroekel I confirm that this is a bug. Thanks for fixing this!
