### ISSUE TITLE
Build fails with F compsets using finite volume dycore in E3SM v2.0

### ISSUE THREAD

**Issue by AlexAudette** [E3SM-Project/E3SM#5848]
To preface this, I am new to E3SM , but have used CESM1 quite a lot over the previous years and I have also played a bit with CESM2, so I have some background with CIME and the general code structure of E3SM. 

I am trying to run the F1850 and F20TR compsets on Perlmutter using the finite volume dycore (grid f19_g16). No matter the compset, I get the following error in the build: 

```

ierr = pio_inq_att(File, PIO_GLOBAL, 'current_metdata_filename',xtype, slen)
           1
Error: There is no specific function for the generic 'pio_inq_att' at (1)
/global/u2/a/aaudette/E3SMv2.0/components/eam/src/dynamics/fv/metdata.F90:883:11:

ierr = pio_inq_att(File, PIO_GLOBAL, 'next_metdata_filename',xtype, slen)
            1
Error: There is no specific function for the generic 'pio_inq_att' at (1)
/global/u2/a/aaudette/E3SMv2.0/components/eam/src/dynamics/fv/metdata.F90:254:18:
```

Is the FV dycore still supported in E3SM 2.0? Is there a way to fix this 
-Alex

**Comment by whannah1** [comment]
The FV dycor is not supported in E3SM and there is no plan to revive it. I suggest you use the standard ne30pg2 grid instead.

**Comment by AlexAudette** [comment]
Thanks, I was trying to bring a module from CESM1.2 that was using the FV dycore, but I'll adapt it to the SE one. Cheers!

**Comment by whannah1** [comment]
What specifically are you trying to bring in?

**Comment by AlexAudette** [comment]
I am trying to bring in the water tracers from iCESM1.2. Most of it is in the physics grid and a small part uses the FV dynamics (mostly initialization).

**Comment by whannah1** [comment]
Adding an advective tracer (to the existing tracer array infrastructure) is not too difficult. If there are special calculations that need to be done on the dycor side of things then it's going to be way more involved.

What's special about these water tracers?

**Comment by AlexAudette** [comment]
Nothing too complicated, just the initialization is done in the inidat.F90 module. I was just trying the easy way first with the same dycor as iCESM1.2 if it was possible as it would require less work from me.
