### ISSUE TITLE
A non-BFB puzzle of FDPSCREAM test with v3atm code base

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#5853]
The test is SMS_Ln9_P24x1.ne4_ne4.FDPSCREAM-ARM97.pm-cpu_gnu, and the issue first appeared when running the test using branch wlin/atm/v3compsets_alpha02 (#5823). The test is intended to guard the SCREAMv0 configuration while merging in v3atm features. With this v3atm based branch, the test is deemed NBFB with the master baseline. The NBFB remains in a test merge of the PR to master.

The test runs cprnc on cpl.hi and eam.h0 files. Further examination shows the test's cpl.hi is identical to that in the baseline, while 6 of 243 variables in eam.h0 are deemed different. The 6 variables are  ICIMR, ICWMR, IWC, TGCLDLWP, TOT_CLD_VISTAU, TOT_ICLD_VISTAU. RMS of the 6 variables, including the normalized RMS, are all 0s.

Furthermore, the per step global statistics in atm.log are BFB. The nature of the differences in the 6 variables is not clear. It also turns out the content in eam.h0 is from initial state (step 0). This is because the test is run 9 steps, while default output frequency nhtfrq is 10 steps. Apparently the test introduced by #5496 is ill defined. This will be revised (changed to L10) after clearing the current NBFB issue. 

Since the current ema.h0 only contains step 0 data, the seemingly difference in the 6 variables could be due to issues in initialization of certain variables.

Attn: @crterai @bogensch @ndkeen .

**Comment by wlin7** [comment]
Here is one such test
`/pscratch/sd/w/wlin/e3sm_scratch/pm-cpu/SMS_Ln9_P24x1.ne4_ne4.FDPSCREAM-ARM97.pm-cpu_gnu.C.20230721_212126_2iogbb`

**Comment by crterai** [comment]
Thanks for tagging us on this change. I didn't think that the cloud water was initialized in the DPSCREAM case, so it's surprising to me that it comes out as NBFB from initialization (even if RMS is zero...). 
Is the test performed using this branch (`wlin/atm/v3compsets_alpha02`)?

**Comment by wlin7** [comment]
Yes, chris, that is the branch used for the test. I think this NBFB itself not a concern for DPSCREAM configuration, because the results are matter-of-factly BFB. However, this issue may potentially expose a hidden problem.

**Comment by rljacob** [comment]
This is now down to just 2 variables diffing at least on chrysalis_intel.  Can we just bless this?

**Comment by rljacob** [comment]
Blessing took care of it.  Test now passes.
