### ISSUE TITLE
Invalid and random P3_dim_input values in eam.h# causing some cime tests labeled as DIFF 

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#5863]
First of all, the issue has no impact on simulation results. The affected tests are otherwise BFB.

The normal values for P3_dim_input are sequentially 1 to 16. But for some tests, such as `SMS.ne30pg2_r05_oECv3.F20TR.chrysalis_intel.eam-wcprod_F20TR` and `SMS.ne30pg2_r05_oECv3.F20TR.chrysalis_intel.eam-wcprod_F20TR
`, the values become corrupted, like in  `SMS.ne30pg2_r05_oECv3.F20TR.chrysalis_intel.eam-wcprod_F20TR`'s baseline `eam.h0.1985-01-06-00000.nc`:
```
 P3_input_dim = -75552, 32767, 12, 0, 1295328040, 5461, 0, 0, -75632, 32767,
    1359239902, 5461, 1601200502, 1601268076, 1751349349, 1701277281 ;

```
These values also vary from one run to another, causing the tests to be labeled as DIFF. It can happen to all eam.h# files.

But the issue does not occur to all tests. For example, `SMS_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.chrysalis_intel.allactive-wcprod_1850`, and tests with pm-cpu that save eam.h# files, have normal P3_input_dim values.

**Comment by rljacob** [comment]
Do only certain fields in the output show a diff?

**Comment by wlin7** [comment]
Only that corrupted P3_input_dim array show diff (with randomness).

**Comment by rljacob** [comment]
Do we know how to fix this?

**Comment by wlin7** [comment]
Not yet. Still working on it. The issue first emerged in v3atm repo, but lost tracking in master with P3 not enabled for cime tests.
