### ISSUE TITLE
OpenACC bug in /components/mpas-ocean/src/shared/mpas_ocn_tendency.F

### ISSUE THREAD

**Issue by nickheavens-cgg** [E3SM-Project/E3SM#5866]
At line 433 (in maint2.1) and 437 (in master) of E3SM/components/mpas-ocean/src/shared/mpas_ocn_tendency.F in the ocn_tend_vel subroutine, there is an error in the OpenACC declaration referring to ssh_sal. This variable does not exist. 

` !$acc update device(ssh_sal)`

The error received in maint2.1 for MPAS-Ocean compiled for OpenACC is: 

`FATAL ERROR: data in update device clause was not found on device 1: name=ssh_sal(:)`

I believe ssh is meant, and I have successfully ran past this error by correcting the update device call to ssh, i.e., 
 
`!$acc update device(ssh) `

**Comment by philipwjones** [comment]
it's actually for ssh_sal which is not allocated if self-attraction and loading is turned off. This should be moved into the compute routine where it is only updated if the option is turned on. Bug fix PR has been created.
