### ISSUE TITLE
Need better tracking of performance baselines

### ISSUE THREAD

**Issue by amametjanov** [E3SM-Project/E3SM#5885]
Currently, performance baselines -- throughput in SYPD and memory in MB of virtual-size/"highwater" -- are tracked in `$BASELINE_ROOT/master/$case/cpl.log.gz`.
We need:
1. separate tracking (and blessing) of throughput and memory baselines
2. standardized blessing of new baselines through `bless_test_results`

Recent throughput and memory DIFF 2023-Aug-09: https://my.cdash.org/viewTest.php?buildid=2385973
Recent memory DIFF 2023-Jul-20: https://my.cdash.org/viewTest.php?buildid=2375089

**Comment by jgfouca** [comment]
Thanks, @amametjanov ! @wadeburgess , we may need to add some features to our jira ticket system for blessing in order to accommodate the handling of performance data. I can handle the scripting side (bless_test_results) unless @jasonb5 wants to take it.

**Comment by wadeburgess** [comment]
@amametjanov  Anything you need me to do to change the Help Desk forms, please create a ticket at https://acme-climate.atlassian.net/servicedesk/customer/portal/2

**Comment by sarats** [comment]
Checking in, perhaps we should outline all the features needed and start prioritizing?

**Comment by jgfouca** [comment]
@sarats , yes, that would help get the ball rolling. @amametjanov , did you create the Help Desk ticket that describes the needed enhancements to the ticket system? Also, if you can describe exactly what it means to bless a performance result in terms of what files need to be moved where, that would give us what we need to update bless_test_results. @jasonb5 , I was thinking about tasking you with this, but I can do it if you are busy.

**Comment by amametjanov** [comment]
Help Desk ticket: `SES-2735 Performance blessing`.
Memory and throughput baseline numbers are in `cpl.log`. Baselines could be stored in `cpl-mem.log` and `cpl-tput.log`.

Also, since this requires a CIME update, the script that runs Jenkins jobs `cime/CIME/Tools/jenkins_generic_job` needs a new option `--save-timing` (`create_test` has it): this will be needed to archive "HPC Suite" runs in PACE.

**Comment by sarats** [comment]
To clarify/add, we need to check if the difference exceeds a configurable threshold (say 5%) over the baseline and where that should be handled.

**Comment by jasonb5** [comment]
@jgfouca I can looks at this, just finishing up the last of the hist_utils issue.
