### ISSUE TITLE
Trouble with short-term archiving and RESUBMIT on pm-cpu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5901]
We see some strange errors with a launch script that does short-term archiving and resubmits on pm-cpu.
When I try a job with short-term archiving, I see the main job and a separate st job start right away. Which seems like that should not be the case -- would think the archiving needs to let the job complete first.  Anyway, my hunch is that there may some interaction (or race condition) around these 2 jobs (main and short-term archive job) and the resubmit of another 2 jobs.

We don't see the error if we turn off short-term archiving _or_ if we don't do resubmits (just manually issue restart).

An error like this was seen in e3sm.log:
```
  0:  ERROR: (seq_infodata_Init) :: rpointer file read returns an error condition
  0: #0  0x22c2b2c in __shr_abort_mod_MOD_shr_abort_backtrace
```

reproducing script:
```
#!/bin/sh
export CIME_MODEL=e3sm
#export COMPSET=2000_DATM%CRU_ELM%BGC_SICE_SOCN_MOSART_SGLC_SWAV
export COMPSET=IELM
export RES=f45_f45
export MACH=pm-cpu
export PROJECT=e3sm
export COMPILER=gnu

export TAG='f45'
#export CASEROOT=/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/me25-aug22
#export CIMEROOT=/global/cfs/cdirs/e3sm/ndk/repos/me25-aug22/cime/scripts
#cd ${CIMEROOT}

export CIME_HASH=`git log -n 1 --pretty=%h`
export ELM_HASH=`(cd ../../components/elm/src;git log -n 1 --pretty=%h)`
export GIT_HASH=E${ELM_HASH}
#export CASE_NAME=test.${GIT_HASH}.DEBUG.ielm.without-st
export CASE_NAME=test.${GIT_HASH}.DEBUG.ielm.with-st

./create_newcase --case=${CASE_NAME} --res=${RES} --compset=${COMPSET} --mach=${MACH} --compiler=${COMPILER} --project=${PROJECT}

cd ${CASE_NAME}

./xmlchange STOP_N=4
./xmlchange STOP_OPTION=ndays
./xmlchange REST_N=4
./xmlchange REST_OPTION=ndays
./xmlchange RESUBMIT=1
./xmlchange SAVE_TIMING=FALSE
./xmlchange DEBUG=TRUE

./xmlchange DATM_MODE=CLMGSWP3v1
./xmlchange RUN_STARTDATE='1900-01-01'
./xmlchange ELM_FORCE_COLDSTART=on
./xmlchange DATM_CLMNCEP_YR_ALIGN=1965
./xmlchange DATM_CLMNCEP_YR_START=1965
./xmlchange DATM_CLMNCEP_YR_END=2014

./xmlchange JOB_WALLCLOCK_TIME=00:28:00
./xmlchange JOB_QUEUE=debug

# with ST, use these 3 lines, without, I comment all three
./xmlchange DOUT_S_SAVE_INTERIM_RESTART_FILES=TRUE
./xmlchange DOUT_S=TRUE
./xmlchange DOUT_S_ROOT='$CASEROOT/run'

./xmlchange RUNDIR=${CASE_NAME}/run
./xmlchange EXEROOT=${CASE_NAME}/bld

cat >> user_nl_datm <<EOF
taxmode = "cycle", "cycle", "cycle"
EOF

./case.setup
./case.build
./case.submit
```

**Comment by rljacob** [comment]
I saw  a very similar bug on Chrysalis when running with CIME case control system directly.   Namely the archive job was submitted immediately and tried to run immediately.   The st archive job is supposed to have a dependency on the main job and not run until it finishes.  My workaround was to set DOUT_S to false and run case.st_archive manually.

**Comment by jasonb5** [comment]
This issue and #5907 may be related, both caused as side effect from the CIME update #5812. Looking into both now.

**Comment by ndkeen** [comment]
I think we can we close this now?
