### ISSUE TITLE
Building cprnc on aarch64 fails

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/E3SM#5952]
Building on aarch64 fails with an error related to picking up the wrong mcmodel flag from:

```cmake
if (CMAKE_SYSTEM_PROCESSOR MATCHES "^aarch64")
  set(CFLAGS "-mcmodel=small")
  set(FFLAGS "-mcmodel=small")
else()
  set(CFLAGS "-mcmodel=medium")
  set(FFLAGS "-mcmodel=medium")
endif()
```

Not sure what the difference is, but is there a need for medium in general or can we simplify with small for everything?

> -mcmodel=small
Generate code for the small code model: the program and its symbols must be linked in the lower 2 GB of the address space. Pointers are 64 bits. Programs can be statically or dynamically linked. This is the default code model.

> -mcmodel=medium
Generate code for the medium model: the program is linked in the lower 2 GB of the address space. Small symbols are also placed there. Symbols with sizes larger than -mlarge-data-threshold are put into large data or BSS sections and can be located above 2GB. Programs can be statically or dynamically linked.

Changing both sets to small enables the the build (also proceeding to full model build) to pass.

**Comment by sarats** [comment]
I think @amametjanov (?) might have added `-mcmodel=small` probably for A64FX or some other ARM architecture where it was needed.

@mahf708 Which ARM CPU are you using? Apple?

**Comment by sarats** [comment]
> Changing both sets to small enables the the build (also proceeding to full model build) to pass.

Can you clarify? Shouldn't aarch64 pick up small already?

**Comment by amametjanov** [comment]
`-mcmodel=medium` was needed for Fujitsu A64FX CPUs on Fugaku and Apple M2 chips were not yet available (BTW, `arch` and `uname -m` in the terminal should show the arch).
If cmake is recognizing M2 as `aarch64`, then please make the change to just always set `-mcmodel=small`.
When needed, I'll have to check on something other than `CMAKE_SYSTEM_PROCESSOR` to set `-mcmodel=medium`.
