### ISSUE TITLE
Need Global Water Budget in MOSART

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/E3SM#6024]
Based on earlier discussion,  we need to develop a global budget diagnostic for MOSART. Note from Gautam, currently MOSART physics does not include any energy (i.e., water transported by MOSART has no heat associated with it). So we only need global water budget for now.

**Comment by chengzhuzhang** [comment]
@hydrotian Tian, we discussed this earlier at all-hands, I just created this issue so it won't slip. I think you already have some off-line calculation (documented in your blog), but it would be easier to have those diagnostics available in log files.

**Comment by hydrotian** [comment]
@chengzhuzhang I will work on it and let you know.
