### ISSUE TITLE
Frontier: build errors with the default Cray Clang compiler

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#6042]
This issue is only reproducible with the default Cray Clang compiler (not reproducible with GNU compiler).

Steps to reproduce the build errors on a Frontier login node:
```
git clone https://github.com/E3SM-Project/E3SM.git
cd E3SM

git submodule update --init --recursive

cd cime/scripts
./create_newcase --machine=frontier --case X_f19_g16 --compset X --res f19_g16

cd X_f19_g16

./case.setup

./case.build
```

Build errors:
`"/opt/cray/pe/cce/15.0.1/cce/x86_64/bin/cce_omp_offload_linker" was terminated due to receipt of signal 013:  Segmentation fault (core dumped).`

**Comment by dqwu** [comment]
@sarats Is this a known issue to you?

**Comment by dqwu** [comment]
@jgfouca Could you please check if it is related to recent CMake build system updates? Thanks.

**Comment by dqwu** [comment]
@jgfouca 
This issue is caused by PR #5988.

For Cray Clang compiler, ADIOS2 2.9.1 was built using the following modules/flags (see a workaround mentioned in E3SM-Project/scorpio#528):

[modules] load craype-accel-amd-gfx90a and rocm/5.4.0
[CXXFLAGS]: add -fopenmp flag

Rebuilding ADIOS2 2.9.1 without these modules/flags should fix the linking error for CCE omp offload linker.

We can close this issue if the updated ADIOS2 2.9.1 lib for Cray Clang compiler on Frontier works.

**Comment by dqwu** [comment]
@jgfouca I have updated /lustre/orion/cli115/world-shared/frontier/3rdparty/adios2/2.9.1/cray-mpich-8.1.23/crayclang-15.0.1 on Frontier. Please verify if this build issue is fixed with the rebuilt ADIOS2 lib, thanks.

**Comment by jgfouca** [comment]
Thanks, @dqwu. It looks like it works now.
