### ISSUE TITLE
Error on perlmutter with stealth feature log-law drag

### ISSUE THREAD

**Issue by cbegeman** [E3SM-Project/E3SM#6055]
The indices of `kineticEnergyCell` in the log-law drag function raise an error on perlmutter with gnu, mpich debug=on.

Migrated from https://github.com/MPAS-Dev/compass/issues/722, compliments of @gcapodag.

**Comment by gcapodag** [comment]
Hi @cbegeman sorry I could not get to this sooner. Do you need me to review it?

**Comment by cbegeman** [comment]
@gcapodag No rush on reviewing https://github.com/E3SM-Project/E3SM/pull/6056 because we won't be getting it in until after the code freeze. But when it's convenient, it wouldn't hurt to have you try out the fix as well.
