### ISSUE TITLE
Fails with nvidiagpu compiler and SMS_Ld1.T62_oEC60to30v3.CMPASO-NYF.pm-gpu_nvidiagpu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#6127]
This test fail on cdash `SMS_Ld1.T62_oEC60to30v3.CMPASO-NYF.pm-gpu_nvidiagpu`
The run actually does not fail, but hangs. I've tried letting it run longer and using more nodes (same result).
On a similar machine at NERSC (muller), it does fail -- but no useful info.

These are new tests to the machine (using gpu compiler and in this case, nvidiagpu).
I tried with the default compiler `gnugpu` and it passes.
I also tried on pm-cpu with both GNU and nvidia and both pass.
When I try with debug, ie `SMS_D_Ld1.T62_oEC60to30v3.CMPASO-NYF.pm-gpu_nvidiagpu`, it fails with floating-point exception, but does not give any more useful info. I tried turning on coredumps and it claims to fail:
```
            do iCell = 1, nCells
               sshTend(iCell) = 0.0_RKIND
               do i = 1, nEdgesOnCell(iCell)
                  iEdge = edgesOnCell(i, iCell)
                  if (maxLevelEdgeTop(iEdge).eq.0) cycle

                  flux = btrvel_temp(iEdge) * wctEdge(iEdge)
```
at the last line there. Maybe `btrvel_temp(iEdge) or wctEdge(iEdge)` are not OK?

This is in source file `bld/cmake-bld/core_ocean/mode_forward/mpas_ocn_time_integration_split_ab2.f90`

This is with default nvidia compiler version 22.7.  There is a 23.9 and I tried that as well with what looks like same results.

I also just tried running with gnugpu and DEBUG and it passed.

**Comment by jonbob** [comment]
@hyungyukang -- can you take a look at this? But please let me know if I can help in any way

**Comment by hyungyukang** [comment]
@jonbob , sure, I will take a look at this. I also need to process #6116, so I can deal with this issue together with #6116.

**Comment by hyungyukang** [comment]
This issue has been fixed in #6116, so I am closing it.

**Comment by rljacob** [comment]
This issue isn't fixed until the fix is merged to master.  It will autoclose when that happens.

**Comment by ndkeen** [comment]
After recent NERSC maintenance, we need to add a module for nvidiagpu builds which is done here
https://github.com/E3SM-Project/E3SM/pull/6166
After that, I can build and run this test with your change and it works.

**Comment by ndkeen** [comment]
As the nvidiagpu tests both passed last night, I think that means this PR is on next. I had also just merged the PR I noted above to next.
