### ISSUE TITLE
mksurfdata.pl is broken

### ISSUE THREAD

**Issue by bishtgautam** [E3SM-Project/E3SM#6137]
@brhillman reported

```
./mksurfdata.pl -res usrspec -usr_gname ne256pg2 -usr_gdate 230119 \
-usr_mapdir /global/cfs/cdirs/e3sm/bhillma/grids/ne256pg2/fsurdat \
-dinlc /global/cfs/cdirs/e3sm/inputdata -d
ERROR: mapping file for this resolution does NOT exist (/global/cfs/cdirs/e3sm/bhillma/grids/ne256pg2/fsurdat/map___to_ne256pg2_nomask_aave_da_c230119.nc).
```

The new `fert` field was added in #5981.

cc: @bbye

**Comment by bishtgautam** [comment]
@bbye What is the rawdata netcdf file for the `fert` that would be in `lnd/clm2/rawdata/`? Also, is this netcdf file already on one of the supported machines?

**Comment by bbye** [comment]
The raw datafile for fertilizer is mksrf_fert.c220309.nc. I thought I had moved this into the anvil input directory, but apparently I didn’t. It’s there now in: /homes/ccsm-data/inputdata/lnd/clm2/rawdata/

From: Gautam Bisht ***@***.***>
Reply-To: E3SM-Project/E3SM ***@***.***>
Date: Tuesday, January 2, 2024 at 10:17 PM
To: E3SM-Project/E3SM ***@***.***>
Cc: "Drewniak, Beth A." ***@***.***>, Mention ***@***.***>
Subject: Re: [E3SM-Project/E3SM] mksurfdata.pl is broken (Issue #6137)


@bbye<https://github.com/bbye> What is the rawdata netcdf file for the fert that would be in lnd/clm2/rawdata/? Also, is this netcdf file already on one of the supported machines?

**Comment by bbye** [comment]
The lmask should be ISRIC-WISE.
