### ISSUE TITLE
MPAS-Seaice standalone makefile is broken

### ISSUE THREAD

**Issue by akturner** [E3SM-Project/E3SM#6138]
The MPAS-Seaice standalone makefile (https://github.com/E3SM-Project/E3SM/blob/master/components/mpas-framework/Makefile) is broken and does not work. It appears there is a missing "endif" on the line after this: https://github.com/E3SM-Project/E3SM/blob/master/components/mpas-framework/Makefile#L630

**Comment by xylar** [comment]
@akturner, I think this might be the same issue that @mark-petersen reported in #6133 and is fixing in #6134
