### ISSUE TITLE
MMF Gordon Bell test fails to build on Frontier

### ISSUE THREAD

**Issue by whannah1** [E3SM-Project/E3SM#6140]
While trying to test the planned Gordon Bell configuration on Frontier I initial ran into various build errors, but many of them were fixed by merging in the [simulations/cess-production](https://github.com/E3SM-Project/scream/tree/simulations/cess-production) branch from the SCREAM fork. But I'm still left with a linking error that seems similar to what @xyuan and @jgfouca have reported on slack.
@abbotts @sarats 
branch => [whannah/Gordon-Bell-2024-test](https://github.com/E3SM-Project/E3SM/tree/whannah/Gordon-Bell-2024-test)

Here is the error I'm getting on my current branch:
ld.lld: error: undefined symbol: _gfortran_erfc_scaled_r8
```
> grep "Error" /lustre/orion/cli115/proj-shared/hannah6/e3sm_scratch/frontier/tests/SMS_Ln3.ne4pg2_ne4pg2.F2010-MMF1.frontier_crayclanggpu.20240105_120034_mkfnqo/bld/e3sm.bldlog.240105-120429 -B10
ld.lld: error: undefined symbol: _gfortran_erfc_scaled_r8
>>> referenced by The Cpu Module
>>>               Tracer1beckBGCReactionsType.F90.o:(calc_bgc_reaction$tracer1beckbgcreactionstype_) in archive ../lnd/liblnd.a
>>> referenced by The Cpu Module
>>>               Tracer1beckBGCReactionsType.F90.o:(calc_bgc_reaction$tracer1beckbgcreactionstype_) in archive ../lnd/liblnd.a
>>> referenced by The Cpu Module
>>>               Tracer1beckBGCReactionsType.F90.o:(calc_bgc_reaction$tracer1beckbgcreactionstype_) in archive ../lnd/liblnd.a
>>> referenced 3 more times
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
Target /lustre/orion/cli115/proj-shared/hannah6/e3sm_scratch/frontier/tests/SMS_Ln3.ne4pg2_ne4pg2.F2010-MMF1.frontier_crayclanggpu.20240105_120034_mkfnqo/bld/e3sm.exe built in 23.205038 seconds
gmake[2]: *** [cmake/cpl/CMakeFiles/e3sm.exe.dir/build.make:569: /lustre/orion/cli115/proj-shared/hannah6/e3sm_scratch/frontier/tests/SMS_Ln3.ne4pg2_ne4pg2.F2010-MMF1.frontier_crayclanggpu.20240105_120034_mkfnqo/bld/e3sm.exe] Error 1
gmake[2]: Leaving directory '/lustre/orion/cli115/proj-shared/hannah6/e3sm_scratch/frontier/tests/SMS_Ln3.ne4pg2_ne4pg2.F2010-MMF1.frontier_crayclanggpu.20240105_120034_mkfnqo/bld/cmake-bld'
gmake[1]: *** [CMakeFiles/Makefile2:717: cmake/cpl/CMakeFiles/e3sm.exe.dir/all] Error 2
gmake[1]: Leaving directory '/lustre/orion/cli115/proj-shared/hannah6/e3sm_scratch/frontier/tests/SMS_Ln3.ne4pg2_ne4pg2.F2010-MMF1.frontier_crayclanggpu.20240105_120034_mkfnqo/bld/cmake-bld'
gmake: *** [Makefile:94: all] Error 2
```

**Comment by sarats** [comment]
I'm not sure why building with OpenMP would trigger

**Comment by rljacob** [comment]
@jgfouca had linking errors that turned out to be from the ulimit in his environment being to low.

**Comment by sarats** [comment]
Btw, the SCREAM branches were created to mimic the Frontier configuration used in E3SM/main but perhaps now involve a few new things as software configurations changed. To summarize, there shouldn't be any radical changes but you need to carefully review the edits you are bringing in by merging the scream/cess branch.

**Comment by abbotts** [comment]
I think the symbol and gfortran depency is coming from libcraymath, which requires gfortran. We forward some math functions to it. I'm surprised it's not already getting linked in, though.

**Comment by sarats** [comment]
Perhaps adding the -craype-verbose flag to the link line would show us if it's missing

**Comment by jgfouca** [comment]
@whannah1 , I was able to get past that particular symbol by adding `-lgfortran` to the link line. I also had to add `-lmpifort`. I am still struggling with a couple more missing symbols (`_dgemm_` and `_idmax_`).

**Comment by sarats** [comment]
dgemm and idmax are from BLAS, do you have either libsci or reference blas (netlib) linked?

**Comment by jgfouca** [comment]
@sarats , I was trying to use openblas, but the cess_production branch did need the openblas module, so something is wrong. I'm looking at it.

**Comment by sarats** [comment]
I don't understand why we need Openblas instead of libsci on a machine like Frontier?

**Comment by jgfouca** [comment]
@sarats , thanks for the tip, `-lsci_cray` did resolve those missing symbols. I will try to redo the build without openblas.

**Comment by whannah1** [comment]
@jgfouca Can you point me to your branch so I can see your changes?

@sarats good point about the unnecessary changes, I considered doing the merge "by hand" one file at a time when I was hit with a bunch of merge conflicts, but I figured it was quicker to merge in those unnecessary changes instead.

**Comment by sarats** [comment]
For future reference, if you can't use libsci for whatever reason, use AMD's libraries for AMD CPUs which is based on BLIS, a decent open source alternative.

https://www.amd.com/en/developer/aocl/dense.html

**Comment by sarats** [comment]
@whannah1 You probably need a few module updates in config_machines and maybe some minor things in cmake macros. At least, it would make it easy for me to review. Don't bring in other stuff unless you are really sure it's needed.

**Comment by whannah1** [comment]
ok, I'm gonna go back to my basic branch before any machine changes and make some incremental changes based on @jgfouca 's branch

**Comment by jgfouca** [comment]
@whannah1 , I think I am very close to having a working build if you can wait like 30m.

**Comment by jgfouca** [comment]
@rljacob , no, it's fixed in SCREAM.

**Comment by whannah1** [comment]
I'm going to remerge Jim's SCREAM branch into my E3SM GB branch and try running again

**Comment by jgfouca** [comment]
Now fixed in E3SM.
