### ISSUE TITLE
ERROR: (shr_tInterp_getCosz)  ERROR: lon lat cosz sizes disagree with `ERS_D_Ld9.1x1_brazil.IELMFATES`

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#6180]
Test may not relevant, but with `ERS_D_Ld9.1x1_brazil.IELMFATES.pm-cpu_gnu`:
```
4:  ERROR: (shr_tInterp_getCosz)  ERROR: lon lat cosz sizes disagree
```

**Comment by glemieux** [comment]
I think this is a duplicate of https://github.com/E3SM-Project/E3SM/issues/4718

**Comment by ndkeen** [comment]
Wow, 2021.  You def got me beat
