### ISSUE TITLE
Error: nonlinear remapping issue in seq_nlmap_mod.F90

### ISSUE THREAD

**Issue by erinethomas** [E3SM-Project/E3SM#6199]
ERROR: 
code crashes in seq_nlmap_mod.F90 (line 267) due to mincol not being defined before use. 

 42: forrtl: severe (194): Run-Time Check Failure. The variable 'seq_nlmap_mod_mp_sort_rowcols_$MINCOL' is being used in '/gpfs/fs1/home/ac.ethomas/E3SM/20240130/driver-mct/main/seq_nlmap_mod.F90(267,17)' without being defined
 42: Image              PC                Routine            Line        Source
 42: e3sm.exe           00000000008C6F32  seq_nlmap_mod_mp_         267  seq_nlmap_mod.F90
 42: e3sm.exe           00000000008C2AE1  seq_nlmap_mod_mp_         200  seq_nlmap_mod.F90
 42: e3sm.exe           00000000008A7DCF  seq_map_mod_mp_se         189  seq_map_mod.F90
 42: e3sm.exe           000000000058BAC5  prep_lnd_mod_mp_p         192  prep_lnd_mod.F90
 42: e3sm.exe           000000000044505C  cime_comp_mod_mp_        1975  cime_comp_mod.F90
 42: e3sm.exe           0000000000489F04  MAIN__                    122  cime_driver.F90
 42: e3sm.exe           0000000000427E22  Unknown               Unknown  Unknown
 42: libc-2.28.so       000015554503D493  __libc_start_main     Unknown  Unknown
 42: e3sm.exe           0000000000427D2E  Unknown               Unknown  Unknown

**Comment by rljacob** [comment]
which machine/compiler is this?

**Comment by erinethomas** [comment]
Chrysalis / Intel compiler

**Comment by erinethomas** [comment]
yes latest Master (hash: 104a2027d9ad34fbd9198422641ad47f19db65c0)

**Comment by ambrad** [comment]
Thanks for the error report. I'll look into it.

**Comment by ambrad** [comment]
I see the problem.

**Comment by erinethomas** [comment]
great thanks for looking into this!
