### ISSUE TITLE
no compset that enables marine BGC with active ocean, ice, land, river components.

### ISSUE THREAD

**Issue by maltrud** [E3SM-Project/E3SM#6208]
The GPMPAS-JRA compset was created allow simulations using active ocean, ice, land, river components.  However, there are no GPMPAS compsets that enable marine BGC (ie, analogs to GMPAS-OECO-IAF and GMPAS-OIECO-IAF).  These need to be created to support HES objectives.

**Comment by rljacob** [comment]
What about this compset that we test?     
BGCEXP_CNTL_CNPRDCTC_1850
1850_EAM%CMIP6_ELM%CNPRDCTCBC_MPASSI%BGC_MPASO%OIECO_MOSART_SGLC_SWAV_BGC%BCRC

**Comment by maltrud** [comment]
@rljacob I am only adding G-case compsets for now.

**Comment by maltrud** [comment]
@rljacob , @jonbob I'm going to make a PR soon with new compsets.  FYI, for new mapping files, I'm using the Tempest versions.  for old mapping files, I left "as-is" since Jon will be replacing them all soon.  I hope that sounds ok.

**Comment by rljacob** [comment]
Just be sure to following the map name convention for the Tempest maps.

**Comment by maltrud** [comment]
Jon created the maps so I assume they have the correct convention.
