### ISSUE TITLE
`SMS_Lm1.ne30pg2_ECwISC30to60E2r1.WCYCL1850` broken

### ISSUE THREAD

**Issue by darincomeau** [E3SM-Project/E3SM#6230]
The test `SMS_Lm1.ne30pg2_ECwISC30to60E2r1.WCYCL1850` off master dies at the end of the month in land with this at the end of the lnd.log:

```
 time integrated flux =  -1.898220433018436E+050
 net change in state  =    15326895.4805661
 current state        =    11.9818119753306
 relative error [%]   =   1.990829226678872E+043
 ENDRUN:
 ERROR in CNPBudgetMod.F90 at line 929






 ERROR: Unknown error submitted to shr_abort_abort.
 ```

**Comment by darincomeau** [comment]
I also see this with `SMS_Lm1_P1280.ne30pg2_IcoswISC30E3r5.WCYCL1850.chrysalis_intel`.
This is off master
`*   5886da6f5b (HEAD -> master, origin/master, origin/HEAD) Merge branch 'jgfouca/fix_prov_git_config' into master (PR #6227)`

**Comment by darincomeau** [comment]
Narrowing down the range a bit, `SMS_Lm1_P1280.ne30pg2_IcoswISC30E3r5.WCYCL1850.chrysalis_intel` passes on master as of Jan 24, `*   e832fb54a5 (HEAD) Merge branch E3SM-Project/ndk/machinefiles/pm-gpu-nvidiagpu-fix (PR #6166)`

**Comment by ndkeen** [comment]
This may be same error as here: https://github.com/E3SM-Project/E3SM/issues/6188

I also tried `SMS_D_Lm1.ne4_oQU240.F2010.pm-cpu_gnu` and `SMS_D_Lm1.ne4_oQU240.F2010.pm-cpu_intel` which failed the same way (ie I think same error ne4/ne30)

**Comment by ndkeen** [comment]
Also see the error with `ERS_Ld31.ne4pg2_oQU480.F2010.pm-cpu_intel` using `rljacob/update-test-v3res`

**Comment by rljacob** [comment]
@darincomeau which science case is using ne30pg2_ECwISC30to60E2r1 ?
The only tests we have for that MPAS mesh are these:
            "ERS_P480_Ld5.T62_ECwISC30to60E2r1.GMPAS-DIB-IAF-PISMF",
            "PEM_P480_Ld5.T62_ECwISC30to60E2r1.GMPAS-DIB-IAF-PISMF",

**Comment by darincomeau** [comment]
@rljacob the grid is misleading, it's what I had on hand when I created the issue. The issue (I believe) is really the compsets, from here: https://github.com/E3SM-Project/E3SM/pull/6108

I've been using https://github.com/E3SM-Project/E3SM/pull/6233 as a fix in my testing that requires more than one month.

**Comment by ndkeen** [comment]
This is the error that causes tests like the following to fail
```
ERS_Ld31.ne4pg2_oQU480.F2010.pm-cpu_intel
SMS_Ly1.ne4pg2_oQU480.F2010.pm-cpu_intel
SMS_Lm1.ne4pg2_oQU480.F2010.pm-cpu_intel
```

**Comment by rljacob** [comment]
If you have a chance, try with the latest version of next.

**Comment by ndkeen** [comment]
Same error with next of Feb 26th with `ERS_Ld31.ne4pg2_oQU480.F2010.pm-cpu_intel`

**Comment by rljacob** [comment]
Does the SMS_Lm1 test work?

**Comment by ndkeen** [comment]
Yes, was about to update that `SMS_Lm1.ne4pg2_oQU480.F2010.pm-cpu_intel` does complete using next of Feb 26th

**Comment by rljacob** [comment]
I'm seeing differences in fill pattern reported on gcp.  1 for ERS and 2 for ERP which implies one field has a number-of-tasks dependency.

**Comment by rljacob** [comment]
Turned out the ERP diff was just from #6233
