### ISSUE TITLE
Update ELM case description

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#6245]
In the README.case file created in every case directory, this text appears for WCYCL:
```
 Component LND is clm4.5 physics:clm4.5 cn:alm1.0 C-N-P, nutirent competition via relative demand, ctc soil casc
ade with black carbon deposition:
```

Should "clm4.5" be in that string?  Need to fix this before v3.0.0 tag.

**Comment by thorntonpe** [comment]
I think this should say "Component LND is elm3.0 physics and BGC, with C-N-P, nutrient competition via relative demand, CTC decomposition model, and black carbon deposition"

**Comment by thorntonpe** [comment]
...if it is the default active BGC case, such as what we're using in the v3 water cycle experiments.

**Comment by rljacob** [comment]
I had to remind myself how that string is formed.  There's a block of code in ELM's config_component.xml called "description" and the string is formed by **appending** every line that matches the regexp for the component in the order they are listed in that block.  Since v3 uses "ELM%CNPRDCTCBCTOP"  That will match each of these lines:
```
<desc compset="_ELM"               >clm4.5 physics:</desc>
<desc compset="_ELM%[^_]*CN"       >clm4.5 cn:</desc>
<desc compset="_ELM%[^_]*CNPRDCTCBC" >alm1.0 C-N-P, nutirent competition via relative demand, ctc soil cascade with black carbon deposition:</desc>
```
That entire block needs to be edited both to update for v3 and to be aware of how it works.

**Comment by thorntonpe** [comment]
@rljacob can you remind me - is the E3SM standard that the components are intended to index their version numbers with major coupled model releases?

**Comment by rljacob** [comment]
@bishtgautam and @thorntonpe since the v3 runs are going to start within days, can you make a PR to fix this soon?

**Comment by thorntonpe** [comment]
I've started a branch to fix this, will push it to my fork for Gautam's review later today.
