### ISSUE TITLE
Issues with branch run and continue run of latest maint-2.0 on perlmutter 

### ISSUE THREAD

**Issue by jinboxie** [E3SM-Project/E3SM#6255]
I'm having problem with maint-2.0 on perlmutter. I'm using the latest version of maint-2.0 of commit 5a3fe8970ac3a3fdf02bc2692cd6e6a1883e5035. It is the Tue Feb 6 12:12:06 2024 -0500 version.
I'm trying to use this version on perlmutter to build and run a branch simulation using the F20TR compset and I have met with several problems.
1. The second problem is the branch run. Where I used the restart files from https://acme-climate.atlassian.net/wiki/spaces/EWCG/pages/3174924293/v2.LR.amip. The simulation could run, but stops every time after one month at 2000.01.31.84600s, and cannot output historic files. Log files say it stops at 
 151: e3sm.exe           0000000002FBB933  piolib_mod_mp_clo        1108  piolib_mod.F90
 151: e3sm.exe           0000000001AAB3A0  histfilemod_mp_hi        3377  histFileMod.F90
 151: e3sm.exe           0000000001A08268  elm_driver_mp_elm        1462  elm_driver.F90
 151: e3sm.exe           00000000019EC8C2  lnd_comp_mct_mp_l         506  lnd_comp_mct.F90
 151: e3sm.exe           0000000000444A2E  component_mod_mp_         751  component_mod.F90
 151: e3sm.exe           000000000042532C  cime_comp_mod_mp_        2876  cime_comp_mod.F90

2. I tried use the same casename as the restart files and use CONTINUE_RUN to circumvent what I had met in problem 2. And it's really problematic. It does not run and stops at first timestep showing log error of below
ERROR: set_field_dimensions: mdim size must be > 0

I wonder if there's anything wrong in the setup?
The running script is also attached below. 
[run.txt](https://github.com/E3SM-Project/E3SM/files/14394729/run.txt)

**Comment by ndkeen** [comment]
I assume you know about recent issues that were addressed/worked-around here https://github.com/E3SM-Project/E3SM/issues/6195

**Comment by jinboxie** [comment]
> I assume you know about recent issues that were addressed/worked-around here #6195

Hi Noel,
Thank you for letting me know. It may be the same situation, as I had been using one version behind that $6195 commit. Let me see if this solves the issue.

**Comment by jinboxie** [comment]
This is solved through the workaround at https://github.com/E3SM-Project/E3SM/issues/6195.
