### ISSUE TITLE
Restart broken in maint2.1 for ELM subgrid.

### ISSUE THREAD

**Issue by peterdschwartz** [E3SM-Project/E3SM#6296]
maint2.1 may fail on restart due to incorrect weights. This is because the topounit weights were never written to or read from restart, which was added later in master.

The simple fix is to insert a `compute_higher_order_weights` call after the subgrid info is read in but prior to evaluating the consistency of the weights. Alternatively, the topounit weights could be added to the restart file, but this could cause fails if running maint2.1 from a restart without those variables.

**Comment by peterdschwartz** [comment]
Note:  I already have a fix for this and will make a PR.

**Comment by rljacob** [comment]
Can you add some logic to the ELM restart read to inquire if a variable is present and then take action?  If its not, it could do something else besides failing.  Just skip it if its not needed or initialize some other way if it needed.
