### ISSUE TITLE
MOSART is not stopping on "Negative channel storage found! "

### ISSUE THREAD

**Issue by bishtgautam** [E3SM-Project/E3SM#6302]
@tanzeli1982 found that while MOSART reports a warning about negative channel storage, it doesn't stop.

```
17: Warning: Negative channel storage found! -
8.932405345574364E+051
193: Warning: Negative channel storage found! -
9.479406226017329E+081
449: Warning: Negative channel storage found! -
2.183048555764361E+087
23: Warning: Negative channel storage found! -
1.674015257872732E+080
456: Warning: Negative channel storage found! -
9.508709584880304E+073
```

**Comment by liho745** [comment]
@bishtgautam I found that the "shr_sys_abort" line corresponding to this error was commented off in a very early commit, #f05d5e5f2f6ea3be7d4293d67bc513a5c1c584f1, back in 2015.  Is it better to fix the bug in a branch off this early commit, or a branch off the most recent master branch?

**Comment by rljacob** [comment]
Does this happen in regular water cycle cases?  If not, just fix it from head of master.

**Comment by bishtgautam** [comment]
This negative error does not show up in the regular water cycle simulations because the MOSART grid resolution is coarse. However, if the resolution is increased (as being done in the ICoM project), we get this warning instead of the model crashing.

@liho745 As Rob suggests, let's add the fix from the head of the master.

**Comment by liho745** [comment]
PR #6313 has been submitted to fix this issue.
