### ISSUE TITLE
debugging run with the v3 output is pointing to a line in chemistry.F90

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/E3SM#6304]
a debugging run with the v3 output is pointing to a line in chemistry.F90:
```
 forrtl: error (182): floating invalid - possible uninitialized real/complex variable.
 e3sm.exe           0000000000E8EC7A  chemistry_mp_chem        1590  chemistry.F90
```
This is the line:
`               gas_ac_layers(:ncol,1) = gas_ac_layers(:ncol,1) + gas_ac(:ncol,k)`

_Originally posted by @rljacob in https://github.com/E3SM-Project/E3SM/issues/6284#issuecomment-2012904911_

bug report from Rob regarding `SMS_D_Ld1.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-wcprod`

**Comment by ndkeen** [comment]
fwiw, same error on pm-cpu:
```
509: forrtl: error (65): floating invalid
509: Image              PC                Routine            Line        Source
509: libpthread-2.31.s  00001476B65EF910  Unknown               Unknown  Unknown
509: e3sm.exe           0000000000E5CFB9  chemistry_mp_chem        1590  chemistry.F90
509: e3sm.exe           0000000002C8C9C1  physpkg_mp_tphysa        1806  physpkg.F90
509: e3sm.exe           0000000002C83C70  physpkg_mp_phys_r        1436  physpkg.F90
509: e3sm.exe           000000000093FFDB  cam_comp_mp_cam_r         307  cam_comp.F90
509: e3sm.exe           00000000008FE9A4  atm_comp_mct_mp_a         706  atm_comp_mct.F90
509: e3sm.exe           00000000004AECF3  component_mod_mp_         757  component_mod.F90
509: e3sm.exe           00000000004715C7  cime_comp_mod_mp_        3116  cime_comp_mod.F90
509: e3sm.exe           000000000049759B  MAIN__                    153  cime_driver.F90
```

**Comment by hsiangheleellnl** [comment]
@ndkeen Thanks for reporting this issue. I try to find where is the bug now. 
@tangq Do you have any thoughts?

**Comment by tangq** [comment]
@hsiangheleellnl , nothing obvious to me. You might want to look at the test `SMS_D_Ld1.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-wcprod`, @rljacob pointed to.

**Comment by hsiangheleellnl** [comment]
@ndkeen or @rljacob could you provide the path of SMS_D_Ld1.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-wcprod?

**Comment by rljacob** [comment]
Current path is here:  /lcrc/group/e3sm2/e3smtest/scratch/chrys/SMS_D_Ld1.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-wcprod.C.JNextIntegration20240324_233506/run

**Comment by rljacob** [comment]
You can recreate this run by going to E3SM/cime/scripts in a clone of latest master and running:
./create_test SMS_D_Ld1.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-wcprod

**Comment by jtolento** [comment]
In my experience, since updating to the v3 tag, I've also produced this error when running CAM_CONFIG_OPTS with 'cosp', while also setting debug=true. If you don't need 'cosp,' consider running without it, it might help.

**Comment by rljacob** [comment]
@hsiangheleellnl what is your progress on this?

**Comment by hsiangheleellnl** [comment]
gas_ac contains NaN. That is why the model complains of "floating invalid". It happened to me before when I turned on the debug setting, the model crashed due to the NaN value. But I cannot trace why gas_ac (actually O3) contains NaN. Now I am trying to set debug=false.

**Comment by amametjanov** [comment]
I was able to get past this issue in my runs of `SMS_D.ne30pg2_r05_IcoswISC30E3r5.WCYCL1850.chrysalis_intel.allactive-wcprod_1850` with this patch:
```
$ git diff components/eam/src/chemistry/mozart/chemistry.F90 
diff --git a/components/eam/src/chemistry/mozart/chemistry.F90 b/components/eam/src/chemistry/mozart/chemistry.F90
index 57412d8f81..11ad9bb145 100644
--- a/components/eam/src/chemistry/mozart/chemistry.F90
+++ b/components/eam/src/chemistry/mozart/chemistry.F90
@@ -923,7 +923,7 @@ end function chem_is_active
     use cfc11star,             only : init_cfc11star
     use phys_control,          only : phys_getopts
     use chem_mods,             only : adv_mass
-    use infnan,                only : nan, assignment(=)
+    use infnan,                only : nan, assignment(=), isnan
     use mo_chem_utls,          only : get_spc_ndx
     use cam_abortutils,            only : endrun
     use aero_model,            only : aero_model_init
@@ -1584,6 +1584,9 @@ end function chem_is_active
                  gaschmbudget_2D_L3_e .lt. gaschmbudget_2D_L3_s .or. gaschmbudget_2D_L4_e .lt. gaschmbudget_2D_L4_s ) then
                    call endrun('chem_readnl: ERROR 2D chem diags layers, layer ending index is less than starting index')
              end if
+             where (isnan(gas_ac(:ncol,:)))
+               gas_ac(:ncol,:) = 0._r8
+             end where
 
              do k= gaschmbudget_2D_L1_s, gaschmbudget_2D_L1_e ! 0-90 hPa
                ftem_layers(:ncol,1) = ftem_layers(:ncol,1) + ftem(:ncol,k)
```

**Comment by tangq** [comment]
@hsiangheleellnl , at which `nstep` do you first see NaN in `gas_ac`? This block of code diagnoses the tendencies of gas tracers between the current time step and the previous time step (stored in `pbuf` at the end of mo_gas_phase_chemdr.F90, lines 1791-1814).

So, when `nstep=0`, `Diff(:ncol,1)=0.0_r8`. when `nstep~=0`, `Diff=(ftem-gas_ac)/dt`. When NaNs first show up should provide some glues.

**Comment by tangq** [comment]
@hsiangheleellnl , we don't have to initialize gas_ac to zeros when nstep=0. You just need to check if it's the first timestep to decide whether `gas_ac` should be used in the calculation (see other if-statements in that section for example).

> @tangq NaNs in `gas_ac` happen when `nstep=0`. Is it because `gas_ac` did not claim `gas_ac=0` at the first timestep?

**Comment by tangq** [comment]
This is great, @hsiangheleellnl . Have you confirmed that the chemdyg results are BFB with this change?
