### ISSUE TITLE
Potential bug in MPAS ocean output 

### ISSUE THREAD

**Issue by zhangshixuan1987** [E3SM-Project/E3SM#6432]
I was trying to prepare a high-frequency SST and Sea Ice cover (SIC) forcing data from the B-case (fully coupled), then use it to drive an F-case (atmosphere only with F-compset) simulation. I used the B-case simulation conducted with E3SM v3, i.e. 20231209.v3.LR.piControl-spinup.chrysalis [https://acme-climate.atlassian.net/wiki/spaces/CM/pages/4032626741/20231209.v3.LR.piControl-spinup.chrysalis], to extract the high-frequency SST (i.e. ``temperatureAtSurface") from _*hist.am.highFrequencyOutput*_  files.  This model historical output archives 5-day (or pentad) mean values for each month.  When I process the data, one issue arises in the model output:  
- Technically, we should have 7 pentads in January of each year (except for the 0001-01-01 when the model is started), which is also confirmed if we check the _*hist.am.highFrequencyOutput*_  files. 
-  However, this is not true for the _*hist.am.highFrequencyOutput*_  files at restart points. There are only 6 instead of 7 pentads in files at, such "0041-01-01", "0081-01-01"  and many other time slices when the simulation was restarted.  This caused a gap between  "0040-12"  and "0041-01" or "0080-12" and "0081-01" with the missing of the first 5-day mean at January.  

I think that the above problem will bring some issues for the post-processing or extra attention for users who will use the products. For my case, I indeed spent some time to figure out this feature in model output, and I have to carefully arrange the time in my forcing file for the SST, and to ensure the consistency between SST and sea ice cover data. 

I would like to report it here to see if the ocean people notice this, and whether they could apply some changes in model code to make the historical output more continuous.

**Comment by xylar** [comment]
@zhangshixuan1987, I agree, this is a bug.  These 2 namelist options should be set to `.true.` and they default to `.false.`:
https://github.com/E3SM-Project/E3SM/blob/41a0ccf8ca2da120659f9efe2c96fd43fb12025a/components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml#L824-L825
In the sea-ice model, which writes out high frequency output as well, they are both set to `.true.`:
https://github.com/E3SM-Project/E3SM/blob/41a0ccf8ca2da120659f9efe2c96fd43fb12025a/components/mpas-seaice/bld/namelist_files/namelist_defaults_mpassi.xml#L475-L476
so presumably you are not seeing the same issue with sea-ice concentration (SIC).

**Comment by xylar** [comment]
@zhangshixuan1987 or @wlin7, could you change these 2 options in a user namelist file and verify that the problem is fixed?  Feel free to make a PR with these changes and I will review it, or I can make the PR and include one or both of you as reviewers (but that might take a couple of days, since I'm traveling back to Germany right now).

**Comment by xylar** [comment]
@zhangshixuan1987, after a discussion at this morning's MPAS DevOps meeting, an alternative solution is to change `truncate` to `append` here:
https://github.com/E3SM-Project/E3SM/blob/master/components/mpas-ocean/cime_config/buildnml#L862
Could you also give that a try?  If it works, that might actually be a preferable solution.

**Comment by zhangshixuan1987** [comment]
> @zhangshixuan1987, I agree, this is a bug. These 2 namelist options should be set to `.true.` and they default to `.false.`:
> 
> https://github.com/E3SM-Project/E3SM/blob/41a0ccf8ca2da120659f9efe2c96fd43fb12025a/components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml#L824-L825
> 
> 
> In the sea-ice model, which writes out high frequency output as well, they are both set to `.true.`:
> https://github.com/E3SM-Project/E3SM/blob/41a0ccf8ca2da120659f9efe2c96fd43fb12025a/components/mpas-seaice/bld/namelist_files/namelist_defaults_mpassi.xml#L475-L476
> 
> 
> so presumably you are not seeing the same issue with sea-ice concentration (SIC).

Hi @xylar: I conducted a set of 2-month short-term simulations on Compy with the code changes you suggested:
- The code for this simulation is master branch on March 21 2024 ([commit 2cfa5f184848e9de083d71a7c670a8af8efcfde4](https://github.com/E3SM-Project/E3SM/commit/2cfa5f184848e9de083d71a7c670a8af8efcfde4)).
- Sensitivity experiments were conducted without (/compyfs/zhan391/e3sm_project/E3SMv3_testings/20240521.v3.default.WCYCL1850.ne30pg2_r05_IcoswISC30E3r5.compy) and with (see /compyfs/zhan391/e3sm_project/E3SMv3_testings/20240521.v3.f6432.WCYCL1850.ne30pg2_r05_IcoswISC30E3r5.compy)) the changes in the namelist_defaults_mpaso.xml suggested above.

The changes here indeed solved the issue I described at this bug report:

- **Without change:** `ncdump -t -v xtime 20240521.v3.default.WCYCL1850.ne30pg2_r05_IcoswISC30E3r5.compy.0161-01-01_00.00.00.nc`
```
data:

xtime =
 "0161-01-06_00:00:00",
 "0161-01-11_00:00:00",
 "0161-01-16_00:00:00",
 "0161-01-21_00:00:00",
 "0161-01-26_00:00:00",
 "0161-01-31_00:00:00" ;
```

- **With change:** `ncdump -t -v xtime 20240521.v3.f6432.WCYCL1850.ne30pg2_r05_IcoswISC30E3r5.compy.mpaso.hist.am.highFrequencyOutput.0161-01-01_00.00.00.nc`
```
data:

xtime =
  "0161-01-01_00:00:00",
  "0161-01-06_00:00:00",
  "0161-01-11_00:00:00",
  "0161-01-16_00:00:00",
  "0161-01-21_00:00:00",
  "0161-01-26_00:00:00",
  "0161-01-31_00:00:00" ;
```

As I mentioned in https://github.com/E3SM-Project/E3SM/pull/6434, I think that the solution proposed here should be a preferred one to me as it avoid some potential issues as discussed on the #6434.
