### ISSUE TITLE
improve inputdata checks

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/E3SM#6558]
Per @rljacob: We got this advice “If you don’t need to download it, you can send a HTTP HEAD request, like these examples https://gist.github.com/dehowell/884204 or this https://stackoverflow.com/a/35881430
That would be easier on the webserver and should run faster.”

**Comment by bartgol** [comment]
Out of curiosity: does this address the 403 Forbidden error as well?

**Comment by rljacob** [comment]
No.  Those were from blocks put in at the web server.  This is just good practice going forward.
