### ISSUE TITLE
Model stops with land temperature > 400K due to negative carbon stock

### ISSUE THREAD

**Issue by thorntonpe** [E3SM-Project/E3SM#6591]
Very high temperature calculated by land model is causing a model stop when critical threshold is exceeded. The high temperatures are coming from an excessively high canopy height calculated by the model. The excessive height is coming from a negative value for stem carbon. The negative stem carbon is coming from a negative dynamic carbon allocation parameter. The negative allocation parameter is coming from a very low productivity for multiple years, and the lack of a lower bounds constraint on that parameter under conditions of low productivity.  
The confluence of these conditions is very rare, but the problem was showing up in isolated gridcells after multiple years of coupled simulation in the V3LR campaign.

**Comment by rljacob** [comment]
Possibly related:  https://github.com/E3SM-Project/E3SM/issues/5803

**Comment by ndkeen** [comment]
It could be nice to show the error message one might see if this was tripped. Or a way to reproduce the problem.

**Comment by ndkeen** [comment]
Thanks, yea I saw that in the related issue. I thought it might be responsible for other issues, but this is only place I've seen that error message.
