### ISSUE TITLE
Excessive building up of surface ponding water

### ISSUE THREAD

**Issue by jinyuntang** [E3SM-Project/E3SM#6605]
When doing simulaitons for xxxCNPPHSWFMCROP, where xxx represents the forcing, the land model  may build up surface ponding water to unrealistically large magnitude and then crashes. Some exploration indicates that this is caused by some missing runoff mechanisms associated with the use of h2osfcflag=1.

**Comment by rljacob** [comment]
What version of E3SM is this seen in ?

**Comment by jinyuntang** [comment]
@rljacob this is in the branch jytang/lnd/BGCV2_compsets_rebase I rebased with the master a while ago for conducting CBGC-v3 experiments. Was this issue fixed in current master by setting h2osfcflag from the namelist?

**Comment by rljacob** [comment]
I don't know.  I asked because its an important piece of information when reporting an issue.

**Comment by jinyuntang** [comment]
@rljacob , I checked current master, it seems h2osfcflag is put into the namelist. So essentially it only needs to be included when configuring the compset of cbgc runs. Therefore, I don't see this as an issue needs to be fixed. So I will close this issue.
