### ISSUE TITLE
Output PIO_BUFFER_SIZE_LIMIT in logs when user chooses the default (-1) in CIME

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/E3SM#6610]
The SCORPIO internal buffer cache size (CIME: env_run.xml: PIO_BUFFER_SIZE_LIMIT) used by the library is written out in e3sm log only when the user explicitly sets the cache size in env_run.xml (it is not written out in the default case).

@ndkeen suggested that it would be helpful to users to add that info (for the default case) in the e3sm logs.

**Comment by ndkeen** [comment]
Yes thanks. I was looking thru old archived performance data and I was unable to find this value. I'm pretty sure the default is always being used (which I think is 64MB), but could be a nice thing to write out "somewhere". Maybe with SPIO stat data? e3sm.log?

**Comment by jayeshkrishna** [comment]
> Yes thanks. I was looking thru old archived performance data and I was unable to find this value. I'm pretty sure the default is always being used (which I think is 64MB), but could be a nice thing to write out "somewhere". Maybe with SPIO stat data? e3sm.log?

ok, I will add it in the e3sm log

**Comment by ndkeen** [comment]
Have you tested this?

**Comment by jayeshkrishna** [comment]
> Have you tested this?

Yes, do you see any issues with the change?

**Comment by ndkeen** [comment]
I also tested it and it looks like it is doing what I might expect
