### ISSUE TITLE
Homme: "newchild: child prim_run can't be a parent of itself"

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/E3SM#6785]
I noticed recently that Homme runs give the error message quoted in the title. This is a GPTL timer error. I believe it's due to recently added code here and in related lines: https://github.com/E3SM-Project/E3SM/blob/744cb2c1bebd3e1487e0e7ba246d8d7d583e3c53/components/homme/src/prim_main.F90#L247

This is in the program main, so it can't affect EAM/EAMxx runs.

@oksanaguba I'm tagging you because I believe you modified the timer code there.

**Comment by oksanaguba** [comment]
thanks, Andrew, i agree that code is not right. on which machine did you see this message so that i could fix it? i do not see it on chrysalis in nightlies.

**Comment by ambrad** [comment]
I see it when I do any theta-l-nlev* run. The error message is in the output from the run, I think stderr. Perhaps the nightly logs catch only stdout.

**Comment by ambrad** [comment]
This must be a latent issue in a branch I'm working on that showed up when I rebased on master. Sorry for the false alarm.
