### ISSUE TITLE
GPTL compilation failing on local machine

### ISSUE THREAD

**Issue by mpaiao** [E3SM-Project/E3SM#6866]
I am trying to compile E3SM on my local computer, but the compilation is failing at GPTL. For reference, I am using a MacBook Pro, and installed both python and gcc/gfortran through HomeBrew. I am using Python 3.13.0 and gcc-14. I am using the `e3sm-unified` environment for compilation.

The error that I keep getting is similar to this (these errors appear multiple times at different lines):
```bash
/path_to/E3SM/share/timing/f_wrappers.c:53:37: error: 'FCI_GLOBAL' declared as function returning a function
   53 | #define gptlfinalize                FCI_GLOBAL(gptlfinalize,GPTLFINALIZE)
      |                                     ^~~~~~~~~~
```
 and  
 ```bash
/path_to/E3SM/share/timing/f_wrappers.c:54:37: error: redefinition of 'FCI_GLOBAL'
   54 | #define gptlprint_mode_query        FCI_GLOBAL(gptlprint_mode_query,GPTLPRINT_MODE_QUERY)
      |                                     ^~~~~~~~~~
 ```

The full log is available in [this file](https://github.com/user-attachments/files/18215330/gptl_bldlog_241220-175116.txt).

Does anyone have any suggestion on how to fix these errors, or at least how to switch them back to warnings? Thanks!

---
PS: From my understanding, the errors I am getting are caused by code constructions that used to trigger warnings in older gcc versions, but that result in errors in gcc-14. 

I actually found a few other compilation errors in other files and I was able to fix them in these branches:
- [E3SM/mpaiao-pr-initfix](https://github.com/mpaiao/E3SM/tree/mpaiao-pr-initfix). Two minor updates in python code due to variable `netcdf_args` being initialised in an if block with no else.
- [MCT/mpaiao-pr-fcfuncfix](https://github.com/mpaiao/MCT/tree/mpaiao-pr-fcfuncfix). Several declarations of function type seemed to be missing.
If these are useful/desirable, I am happy to turn them into pull requests.

**Comment by ambrad** [comment]
I think the errors above may be a red herring. I suspect the real issue is that something has gone wrong in configuration, leading to these downstream errors. GPTL usually builds first or nearly first, making it an early point of failure when there are configuration problems.

To make progress, look for files with name CMakeError.log and CMakeOutput.log in the build tree and read through them looking for clues to configuration issues.

It's possible your branches won't be needed once the configuration phase works.

**Comment by mpaiao** [comment]
Thanks! I will see if I can find any configuration issue. In the mean time, these are the [gnu_local_cmake.txt](https://github.com/user-attachments/files/18218155/gnu_local_cmake.txt) file and the [config_machines_xml.txt](https://github.com/user-attachments/files/18218161/config_machines_xml.txt) files I left on my `${HOME}/.cime` directory.

I checked the build tree but neither CMakeError.log nor CMakeOutput.log exist, so maybe the compilation failed even before the point in which these files are produced? I see such files in the build tree when I create the case on Perlmutter.

**Comment by ambrad** [comment]
One other place to look for messages is the gptl.bldlog file.

I probably can't provide anything else that's useful, but one thing I noticed and wonder about is
```cmake
set(SCXX                    "${GNUCOMP_PATH}/bin/g++-14")
set(SCC                     "${GNUCOMP_PATH}/bin/gcc-14")
set(SFC                     "${GNUCOMP_PATH}/bin/gfortran-14")
set(CMAKE_CXX_COMPILER      "${SCXX}")
set(CMAKE_C_COMPILER        "${SCC}")
set(CMAKE_Fortran_COMPILER  "${SFC}")
```
I'm thinking you need an MPI wrapper for at least the Fortran compiler. But I'm definitely not sure; I don't know all the ways the E3SM build system can be configured.

**Comment by rljacob** [comment]
Don't use e3sm-unified for compilation.   That has had conflicts with CIME in the past.

I don't think we've tested with gcc14 so those mpi-serial fixes might be needed.  Please make a PR for them to https://github.com/ESMCI/mpi-serial

**Comment by mpaiao** [comment]
Thanks for the feedback @rljacob. I will try to compile again without e3sm-unified, though when I was trying to do it before AGU, it was giving errors at much earlier stages of the case creation. I will post the error here if I see it again. 

It looks like someone implemented many similar changes to mine in mpi-serial since I forked E3SM earlier this month, the main difference being that I declared functions as `void` and the other person declared the functions as `int` in `mpi-serial`. I think both are equally fine, the functions just needed to be declared as some type, so I made a pull request for the `mpi-serial` that only adds the declaration of a few functions in `type.h` and `mpi.h`, which were also needed for compiling mpi-serial with gcc-14.

**Comment by mpaiao** [comment]
I tried to compile the code and create the case without e3sm-unified but it crashes at the exact same place when building f_wrappers.c from GPTL.

@ambrad At least in the past, I was able to compile E3SM without mpi on my computer, by setting my machine to default to mpi-serial. However, it's been a while since I tried to compile the code locally, has this option changed?

**Comment by ambrad** [comment]
I didn't know about mpi-serial.

**Comment by rljacob** [comment]
We haven't supported building E3SM with mpi-serial for a while.   We didn't purposely break it but no longer test it.

If you're trying to run on a personal laptop/comptuer, try using the docker container we use for testing:  https://github.com/E3SM-Project/containers/pkgs/container/containers-ghci

**Comment by mpaiao** [comment]
I am trying to compile on my local computer because I am making changes to FATES. My goal is to run multiple short, single-site tests with my changes in the FATES code without spending node hours on Perlmutter for debugging. 

I thought Docker was mostly for when we want to use the code as is, but maybe I misunderstood that.

**Comment by mpaiao** [comment]
Many thanks for the feedback @mahf708. Indeed it seems I hit a dead end with the MacOS compilation with the current E3SM version. I will document what I found so far, but for now I will probably just use Perlmutter. 

----
The compilation failure in my original post is happening because of the `FortranCInterface` utility of `CMake` that is not creating the correct mangling for Fortran modules and symbols, it is generating a very minimal file instead. This is how the file `bld/gnu/mpi-serial/nodebug/nothreads/gptl/gptl/cmake_fortran_c_interface.h` looks like on my Mac:

```
#ifndef FCI_HEADER_INCLUDED
#define FCI_HEADER_INCLUDED

#endif
```

versus what is generated on Perlmutter

```
#ifndef FCI_HEADER_INCLUDED
#define FCI_HEADER_INCLUDED

/* Mangling for Fortran global symbols without underscores. */
#define FCI_GLOBAL(name,NAME) name##_

/* Mangling for Fortran global symbols with underscores. */
#define FCI_GLOBAL_(name,NAME) name##_

/* Mangling for Fortran module symbols without underscores. */
#define FCI_MODULE(mod_name,name, mod_NAME,NAME) mod_name##_mp_##name##_

/* Mangling for Fortran module symbols with underscores. */
#define FCI_MODULE_(mod_name,name, mod_NAME,NAME) mod_name##_mp_##name##_

#endif
```
Because the mangling configuration is incorrect, `FCI_GLOBAL` is never defined properly on my Mac, the compilation crashes when it tries to use it.

I tried to activate debugging and verbose output for the interface utility, but I have only a very basic understanding of CMake. It basically said that gcc-14 and gfortran-14 were oddly not compatible with each other. I tried to simplify the compilation settings and options, but I kept reaching the same crashing point.

For now, I will close this issue. But if anyone knows how to fix it at any point, feel free to reopen this issue and post a suggestion.

**Comment by rljacob** [comment]
What OS version is on your mac?

**Comment by mpaiao** [comment]
> What OS version is on your mac?

Sequoia 15.1.1. My MacBook Pro is an older one, still Intel processor (Intel Core i9).
