### ISSUE TITLE
PIO? Ocean? Titan? failures for A_WCYCL2000 / ne30_oEC

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#760]
My apologies for not providing a more precise diagnosis, but wanted to advertise this issue.

On Titan, 

```
  -compset A_WCYCL2000 -res ne30_oEC -mach titan -compiler pgi
```

The out-of-the-box PE and PIO layout works fine. However, changing

```
 <entry id="PIO_STRIDE"   value="-1"  />
```

to

```
 <entry id="PIO_STRIDE"   value="32"  />
```

causes an arithmetic exception almost immediately in ocean initialization (no ocn.log output). Default PIO stride is 4. When setting this to 16, the model also runs. Setting it to 64, it also dies.

This also occurs with other PE layouts, with possibly different PIO_STRIDE settings. I have not seen similar behavior on other systems (yet?).

I have not seen this behavior before, and the ease of generating this failure concerns me. However, if the model dies during ocean initialization, you might try modifying PIO settings.

**Comment by worleyph** [comment]
@rljacob, should I close this? Titan is "no more" and nothing has been updated on this topic since 2016.

**Comment by rljacob** [comment]
yes
