### ISSUE TITLE
Fail to create a case using ICN compset on constance

### ISSUE THREAD

**Issue by liho745** [E3SM-Project/E3SM#823]
I just tried to create a new case with the ICM compset which invokes RTM, but failed at “cesm_setup” stage. The commands I used are as below. (Note: I was able to do so successfully with the IMCN compset, everything the same)

./create_newcase -case test2 -res f19_g16 -compset ICN -mach constance_intel
cd test2
./cesm_setup

**Comment by bishtgautam** [comment]
This compset doesn't exist any longer. So, won't fix it.
